### ISSUE TITLE
"Assistance" tab ignore user input password

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#100]
TG789vAC v2 (Tiscali)
GUI Version [ 8.6.4 ]

Enabling "Assistance" in permanent mode the GUI allow to set an user/password, but when you save is just ignored and a random one with the user "assist" is assigned

**Comment by Ansuel** [comment]
can you tell me if the modem is reachable from wan?

**Comment by FrancYescO** [comment]
Remote Assistance is working, only SSH seems to not work

**Comment by Ansuel** [comment]
the card show the random password?

**Comment by FrancYescO** [comment]
no. the random password is just shown the first time (instead of the one you've set in the textbox) than once enables this is how the GUI looks:
![](https://i.imgur.com/xwRllLv.png)
![](https://i.imgur.com/UgdOlHi.png)
