### ISSUE TITLE
Broadband card stuck TG789 V3

### ISSUE THREAD

**Issue by nutterthanos** [Ansuel/tch-nginx-gui#1001]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[DebugHelper2020-09-12-1421.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/5470112/DebugHelper2020-09-12-1421.tar.gz)
[network.txt](https://github.com/Ansuel/tch-nginx-gui/files/5470111/network.txt) renamed from network so it can be uploaded

Device Model: iiNet/Technicolor TG789 V3
Gui Version: 9.6.2 Dev

Description of problem: Broadband Card stuck when opening with processing

How to reproduce (if possible):
Open Broadband card and it will be stuck
Media/Photos (if possible):
https://gyazo.com/fef3922b8598571bad0d7081de234888
@FrancYescO

**Comment by nutterthanos** [comment]
@FrancYescO

**Comment by FrancYescO** [comment]
should be fixed now, but only on new installs, so execute these commands:
```
uci del network.wan
uci rename network.ppp=wan
```

**Comment by nutterthanos** [comment]
welp i bugged it again

**Comment by FrancYescO** [comment]
how?

**Comment by nutterthanos** [comment]
idk

**Comment by nutterthanos** [comment]
im rebooting it

**Comment by nutterthanos** [comment]
nope it came back even after reboot

**Comment by nutterthanos** [comment]
i might have to post debughelper and network conf again

**Comment by nutterthanos** [comment]
[network.txt](https://github.com/Ansuel/tch-nginx-gui/files/5471926/network.txt)
[DebugHelper2020-11-01-2256.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/5471927/DebugHelper2020-11-01-2256.tar.gz)

**Comment by nutterthanos** [comment]
nvm 
![image](https://user-images.githubusercontent.com/50470661/97817839-d79b3780-1cee-11eb-98ca-30cea4fbf779.png)

**Comment by nutterthanos** [comment]
but internet toggle says off stile #990

**Comment by FrancYescO** [comment]
hope #990 it's fixed now.

but about this issue i need a confirmation that is present also after a reset (you will not lose root) and that a reinstall of the GUI at the latest dev version

PS. why you are not using 18.3.0442-ver3.4.1 on your device? is this unrootable (the GUI upgrade should preserve root)?

**Comment by nutterthanos** [comment]
well i thought what is the safest way of doing the firmware upgrade with the gui installed?

**Comment by FrancYescO** [comment]
just sending the new rbi via the gateway page, it will automatically try to maintain root and reinstalls the GUI.
