### ISSUE TITLE
Internet connection freezes on upload

### ISSUE THREAD

**Issue by aetonsi** [Ansuel/tch-nginx-gui#1002]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[DebugHelper2020-11-05-1110.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/5493529/DebugHelper2020-11-05-1110.tar.gz)

**Device Model**
DGA ( DGA4132 ) AGTHP_2.2.0

**Gui Version**
9.5.38-ba81e28c

**Description of problem**
When uploading data to any destination, the internet connection freezes for everyone connected to the AP.
It is as if the router cannot handle a continuous upload stream, and consequently any browsing becomes temporarily impossible.
This happens with any upload, to any server (eg Google Drive, Youtube, Mega.nz, speedtest.net, ecc)

**How to reproduce (if possible)**
Just upload a big file or start a speed test

**Media/Photos (if possible)**
Results of `ping -t 8.8.8.8` during a **speedtest.net** test follow.
Please notice
- the raise from ~40ms (my average) to ~150ms during the download test; this is expected
- the return to ~38ms after the end of the download test
- the raise to over 3-4000ms followed by the complete death of the connection (`Request timed out.`) during the **upload** test
- the return to normality a few seconds (~15s) after the end of the upload test
```log
Reply from 8.8.8.8: bytes=32 time=38ms TTL=116
Reply from 8.8.8.8: bytes=32 time=38ms TTL=116
Reply from 8.8.8.8: bytes=32 time=43ms TTL=116
Reply from 8.8.8.8: bytes=32 time=91ms TTL=116
Reply from 8.8.8.8: bytes=32 time=105ms TTL=116
Reply from 8.8.8.8: bytes=32 time=114ms TTL=116
Reply from 8.8.8.8: bytes=32 time=115ms TTL=116
Reply from 8.8.8.8: bytes=32 time=103ms TTL=116
Reply from 8.8.8.8: bytes=32 time=122ms TTL=116
Reply from 8.8.8.8: bytes=32 time=115ms TTL=116
Reply from 8.8.8.8: bytes=32 time=110ms TTL=116
Reply from 8.8.8.8: bytes=32 time=140ms TTL=116
Reply from 8.8.8.8: bytes=32 time=159ms TTL=116
Reply from 8.8.8.8: bytes=32 time=134ms TTL=116
Reply from 8.8.8.8: bytes=32 time=140ms TTL=116
Reply from 8.8.8.8: bytes=32 time=131ms TTL=116
Reply from 8.8.8.8: bytes=32 time=99ms TTL=116
Reply from 8.8.8.8: bytes=32 time=110ms TTL=116
Reply from 8.8.8.8: bytes=32 time=38ms TTL=116
Reply from 8.8.8.8: bytes=32 time=38ms TTL=116
Reply from 8.8.8.8: bytes=32 time=1261ms TTL=116
Reply from 8.8.8.8: bytes=32 time=2160ms TTL=116
Reply from 8.8.8.8: bytes=32 time=1840ms TTL=116
Reply from 8.8.8.8: bytes=32 time=2038ms TTL=116
Reply from 8.8.8.8: bytes=32 time=2377ms TTL=116
Reply from 8.8.8.8: bytes=32 time=3549ms TTL=116
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Reply from 8.8.8.8: bytes=32 time=1487ms TTL=116
Reply from 8.8.8.8: bytes=32 time=311ms TTL=116
Reply from 8.8.8.8: bytes=32 time=161ms TTL=116
Reply from 8.8.8.8: bytes=32 time=59ms TTL=116
Reply from 8.8.8.8: bytes=32 time=38ms TTL=116
Reply from 8.8.8.8: bytes=32 time=42ms TTL=116
Reply from 8.8.8.8: bytes=32 time=47ms TTL=116
```

Additional test:
![image](https://user-images.githubusercontent.com/18366087/98228915-85aa1a00-1f59-11eb-886c-4c3f2040bb3a.png)

**Comment by FrancYescO** [comment]
i don't think there is much we can do here.
it's just fulfilling your upload bandwidth and also ping fails, you could try enabling/disabling dosprotect/rpfilter/qos or play around with these options to try getting a better behaviour

**Comment by aetonsi** [comment]
Hi, i can confirm the device itself is the problem. Even using the stock room, the problem persists: it's bufferbloat...
I tried messing around with those settings but to no avail..

**Comment by lorenzocanalelc** [comment]
@aetonsi Install this https://openwrt.org/docs/guide-user/network/traffic-shaping/sqm, but don't use piece_of_cake.qos because it seems not to work on our device, use the default one instead (fq_codel, simple.qos.
It works for me on my ADSL you just need to tweak it to fit your line
