### ISSUE TITLE
QoS: Possibile limitare banda dispositivo?

### ISSUE THREAD

**Issue by d3nny89** [Ansuel/tch-nginx-gui#1005]
Avendo una connessione condivisa mi chiedevo se fosse possibile tramite QoS (o altro metodo) limitare la banda e/o la velocità di connessione internet di uno specifico dispositivo pc (tramite MAC Address) connesso al router tramite wifi.

Grazie

**Comment by d3nny89** [comment]
@Ansuel

**Comment by FrancYescO** [comment]
tramite il qos di default puoi prioritizzare: https://www.ilpuntotecnico.com/forum/index.php/topic,81461.msg263640.html#msg263640

tramite qualcosa del genere puoi anche limitare banda: https://github.com/xMase/Traffic-Shaping-DGA4132
