### ISSUE TITLE
[TG789vac v2] Last stable update bricked the router

### ISSUE THREAD

**Issue by Digitalone1** [Ansuel/tch-nginx-gui#1007]
Description of problem:
I updated to the latest stable version. No issues until my router rebooted automatically and now it's not booting correctly anymore. Every time I switch it on/off, it's stuck on a purple flashing light. Can't access to the main page at 192.168.1.1. No connectivity.

What can I do now?

**Comment by Ansuel** [comment]
@Digitalone1 use the bootp recovery method to reflash the firmware, reroot and reinstall the gui. The old stable had a bug and you were unlucky by rebooting the modem before the updating to the new version

**Comment by Digitalone1** [comment]
> @Digitalone1 use the bootp recovery method to reflash the firmware, reroot and reinstall the gui. The old stable had a bug and you were unlucky by rebooting the modem before the updating to the new version

Can you give me a guide to follow? Never heard about this method.

Anyway, if I manage to fix it, I will never update anymore, I need connection for work and can't run the risk to break the router. :(

**Comment by Ansuel** [comment]
1. Download Tftpd64 
2. Download the firmware
3. Set static ip for the network interfacte that will be connected to the modem
192.168.1.10
255.255.255.0
192.168.1.1

4. Open tftpd64 as admin
Settings
Tab TFTP
- Base Dir The directory where is the firmware located
- Security None
- Pxe Compatibility
Tab DHCP
- Start 192.168.1.0
- Size 32
- Lease 3000
- boot name of the firmware

- def router 192.168.1.10
- mask 255.255.255.0
- dns 192.168.1.10
- wins 192.168.1.10

Power off the modem, make sure the ethernet cable is not connected to a wan port
Keep the reset button pressed and power on the modem. Wait some time and it will start to download the firmware image if you set up all correctly.

Also about update this was a coincidence, 99% it doesn't brick the modem.

**Comment by Digitalone1** [comment]
Did it. The router returned to work, but I can't access to page at 192.168.1.1

I tried to login with admin password, but it's not accessing. Don't know how to get root access and reinstall the modded firmware.

**Comment by Digitalone1** [comment]
I think that `admin` password is correct, but the firmware throws an error and I can't do nothing. It seems that the only way to get root access is giving some commands from the GUI. At least internet works, but not the voip.

I download the firmware from [here](https://hack-technicolor.readthedocs.io/en/stable/Repository/) (Tiscali version).

Is there a way to install directly the modded firmware from TFTP? I don't see an rbi file in the release.

**Comment by FrancYescO** [comment]
use reset button to reset password and acces the GUI, you can only apply the mod after install official RBI firmwares

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/1004
