### ISSUE TITLE
Terminal doesn't load on Update/Extension/DSLdriver Change

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#1008]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model:  TG789vac V2 and DGA4132
Gui Version: 9.6.10-663c1ee8

Description of problem: The terminal doesn't load on the stable release (Same as https://github.com/Ansuel/tch-nginx-gui/issues/1003)

How to reproduce (if possible): Upgrade/Downgrade to Stable and the terminal will not work anymore, it will work fine on the DEV Release

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
Probably lua minifier breaks js on stable release
