### ISSUE TITLE
Scheda Codec VoIP non funzionante

### ISSUE THREAD

**Issue by lorenzobucci** [Ansuel/tch-nginx-gui#1010]
Device Model: TG789vac v2
Gui Version: 9.6.10

Description of problem:
Non visualizzo i codec della telefonia VoIP e inoltre vengono segnalati degli errori sulle impostazioni per il POS. La scheda funziona normalmente per qualche ora dopo ogni aggiornamento della GUI per poi ritornare permanentemente nello stato che vedete negli screenshot.

How to reproduce (if possible):
Scheda Telefonia > Codec

Media/Photos (if possible):
![image](https://user-images.githubusercontent.com/28896230/99781902-bfae1b00-2b18-11eb-9508-e2f7bcd72481.png)

![image](https://user-images.githubusercontent.com/28896230/99781964-d2c0eb00-2b18-11eb-9374-c30208b939bd.png)

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/1010
