### ISSUE TITLE
GUI update button not working on 9.6 and using gz file GUI disappears

### ISSUE THREAD

**Issue by VGerris** [Ansuel/tch-nginx-gui#1013]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: Technicolor TG799vacXTREAM

Gui Version:  9.4.70-184d06d3

Description of problem: when clicking update, the screen shows executing and a close and x button but it never does anything.
When I download the file from git and upload it manually, the router reboots and the GUI shows an Nginx not allowed error and is otherwise gone. Then I reinstall it with

 curl -k https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/GUI.tar.bz2 --output /tmp/GUI.tar.bz2
bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf -

How to reproduce (if possible):
Run update on 9.4.70 GUI 

Media/Photos (if possible):

![Screenshot from 2020-12-05 23-52-02](https://user-images.githubusercontent.com/793993/101267044-0f195b80-3755-11eb-9f56-cba60cf77c4e.png)

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/921

**Comment by VGerris** [comment]
why was this closed? I I run :
per versione stabile:
wget https://github.com/Ansuel/gui-dev-build-auto/raw/master/GUI.tar.bz2
bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force

I have the same problem

**Comment by FrancYescO** [comment]
post result after executing these command, user curl -k as wrote on first post not wget.

**Comment by VGerris** [comment]
Hi, Sorry I used curl, there is not wget, I just get the exact same issue. Router reboots, version is still 9.4 and it shows the update.
My commands (on the router):

curl -k https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/GUI.tar.bz2 --output /tmp/GUI.tar.bz2
bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force

**Comment by vg-minnity** [comment]
hi,

It turned out I did not have enough space on the device, so it just filled up and rebooted.
When I cleared out spaced it worked as expected.
The router became unstable though, with routing rules not working properly, so I had to replace it to have proper internet connection.
Will see if I can make it back to work properly.
Thanks for the support!

**Comment by VGerris** [comment]
hi,

It turned out I did not have enough space on the device, so it just filled up and rebooted.
When I cleared out spaced it worked as expected.
The router became unstable though, with routing rules not working properly, so I had to replace it to have proper internet connection.
Will see if I can make it back to work properly.
Thanks for the support!
