### ISSUE TITLE
la pagina web crasha durante la navigazione/salvataggio

### ISSUE THREAD

**Issue by fabio1999ita** [Ansuel/tch-nginx-gui#1015]
Device Model: MediaAccess DG ( MediaAccess DGA4131FWB )
Gui Version: 9.6.25-3b0cbe40

Description of problem:
buonasera, dopo aver fatto un reset della gui personalizzata al mio router fastweb ed aver aggiornato all'ultima versione stabile mi capita spesso che la pagina web del router crashi quando navigo oppure salvo qualche modifica
dopo essere crashata si riprende dopo tipo 10 minuti se va bene, se no serve un riavvio
conoscete una soluzione?

**Comment by FrancYescO** [comment]
che significa crasha?

**Comment by fabio1999ita** [comment]
> che significa crasha?

si blocca completamente, se provo a fare il refresh non la raggiunge piu', poi se va bene come ho scritto si riprende dopo 10 minuti

**Comment by FrancYescO** [comment]
credo dipenda dalle operazioni che vengono fatte prima che poi inizia a non rispondere piu' (probabilmente perchè ha alto carico sulla CPU)

probabilmente collegato a questa issue https://github.com/Ansuel/tch-nginx-gui/issues/892

**Comment by fabio1999ita** [comment]
questa cosa succede anche non facendo nulla, capita anche a caso, non avevo questo problema alla prima installazione della GUI, è iniziato dopo aver fatto il primo reset da GUI, poi ne ho fatto ancora un altro ma non è cambiato nulla

ora la cpu in impostazioni eco l'ho su auto, forse conviene provare a mettere 1/1?

**Comment by Dark4Codrutz** [comment]
9.6.25 su DGA4132 qui, nessun sintomo di qui hai descritto (forse a meno del #892, non so dire di preciso).

Per quanto riguarda la CPU , apri una shell SSH e vedi con il commando `top` se c'è qualche processo che mangia tutta la CPU come ha suggerito @FrancYescO

**Comment by fabio1999ita** [comment]
ho risolto facendo il reset completo da tasto e sbloccandolo nuovamente da zero installando poi la gui

**Comment by Dark4Codrutz** [comment]
> ho risolto facendo il reset completo da tasto e sbloccandolo nuovamente da zero installando poi la gui

Spesso anche io ho scontrato stranezze con il config in seguito a firmware update.
Se mai ti ricapita basta che fai Factory Reset da GUI -> Modem.

**Comment by fabio1999ita** [comment]
> > ho risolto facendo il reset completo da tasto e sbloccandolo nuovamente da zero installando poi la gui
> 
> Spesso anche io ho scontrato stranezze con il config in seguito a firmware update.
> Se mai ti ricapita basta che fai Factory Reset da GUI -> Modem, così lasci intatto il root e la Gui custom stessa ma ripristini tutte le configurazioni interne.

ho provato piu' volte ma il reset da gui non ha funzionato
