### ISSUE TITLE
wireless time control not working after an update

### ISSUE THREAD

**Issue by albertolg** [Ansuel/tch-nginx-gui#1020]
TG789vac v2, after latest update my wireless schedule is not working (the wirless doesn't turn on or off at scheduled time). I had a problem with an update, my modem did a reset to default and I had to reinstall the GUI. After that the GUI is ok but the wireless schedule is not working.

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/730
