### ISSUE TITLE
Client Monitoring not working

### ISSUE THREAD

**Issue by SamuelePilleri** [Ansuel/tch-nginx-gui#1022]
Device Model: DGA4132
Gui Version: 9.6.25-3b0cbe40

Description of problem: Client monitoring not displaying anything

How to reproduce: Go to the Cards page >> Wireless >> Client Monitoring (left column menu) >> Select a device from the list >> Nothing happens.

Expected behaviour: A modal open with wireless stats about signal strength and such.

Media/Photos: This is what should be displayed (from an old screenshot)
![Screenshot](https://user-images.githubusercontent.com/13276940/101790988-5449de80-3b03-11eb-8f79-6c0ad18f5a34.png)

**Comment by Dark4Codrutz** [comment]
+1 can reproduce this

**Comment by Ansuel** [comment]
Can someone test Dev ? I can't reproduce this.

Il Ven 11 Dic 2020, 20:30 Codrut Ban <notifications@github.com> ha scritto:

**Comment by SamuelePilleri** [comment]
I see you are actively working on the repo, what version should we flash (without bricking our devices xP) ?

**Comment by Dark4Codrutz** [comment]
Stay on the Stable channel 😉From: Samuele PilleriSent: venerdì 11 dicembre 2020 21:51To: Ansuel/tch-nginx-guiCc: Codrut Ban; CommentSubject: Re: [Ansuel/tch-nginx-gui] Client Monitoring not working (#1022) I see you are actively working on the repo, what version should we flash (without bricking our devices xP) ? —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Ansuel** [comment]
try to open the browser console and tell me if there is an error reported. Also try the dev gui

**Comment by SamuelePilleri** [comment]
There is an error in the console:

```
Uncaught SyntaxError: expected property name, got end of script
    jQuery 18
        y
        Me
        append
        html
        W
        html
        load
        c
        fireWith
        l
        o
        send
        ajax
        load
        n
        <anonymous>
        dispatch
        handle
cards.lp:1:4837
    jQuery 18
```

Needless to say, column 4837 doesn't exist in that file.

Perhaps I should note that I'm using Firefox. Also, I've just found out login doesn't work in Edge Chromium, but that's a separate issue.

**Comment by SamuelePilleri** [comment]
I may be wrong, but I feel it has to do with that unhappy `\'Error \'` escape on [line 42](https://github.com/Ansuel/tch-nginx-gui/blob/e479249f4fa5bc8c76b48b19270b64f7c2708956/decompressed/gui_file/www/gateway-snippets/cards.lp#L42).
