### ISSUE TITLE
Suggestion: Upload Power Tweaking

### ISSUE THREAD

**Issue by knightian** [Ansuel/tch-nginx-gui#1025]
Is it possible to let us tweak upload power levels?

Lately I have noticed that my upload power level has dropped from about 8.6db to 7.4db and I've lost 2Mbps from my upload rate as a result.

Is there a way to enable tweaking of the upload power so I can bring it back up to 8.6dB and get my upload bandwidth back? Happy to sacrifice some download power to do it as I am getting download speed of 8Mbps faster than my plan allows for anyway.

**Comment by FrancYescO** [comment]
for now, not possible on broadcom, and also if your stats are dropped tweaking can cause just instability.
