### ISSUE TITLE
Aggiornamento da AGTHP_2.2.2_001 (19.4) a 2.2.3_003 (18.3) (Codice Errore: 16)

### ISSUE THREAD

**Issue by webmaster0520** [Ansuel/tch-nginx-gui#1027]
Dispositivo: TIM HUB
Modello: DGA4132
Versione Firmware: AGTHP_2.2.2_001 (19.4)
Versione GUI: 9.6.50-a5f2b677 (DEV Branch)

Descrizione del Problema:
Posseggo un TIM HUB con software AGTHP_2.2.2_001 (19.4). Vista la disponibilità del nuovo Firmware AGTHP_2.2.3_003 (18.3), volevo aggiornarlo. Il problema è che quando provo ad effettuare l'operazione di aggiornamento firmware dall'apposita Card della GUI Ansuel, inizia il processo di aggiornamento, caricando il File RBI, ma dopo circa 10 secondi compare il seguente messaggio di errore:

Aggiornamento firmware fallito. (Codice errore: 16).

**Comment by FrancYescO** [comment]
il firmware 2.2.3_003 non è più nuovo del 2.2.2_001 ed entrambi sono firmware beta ed è sconsigliato utilizzarli.

per downgradare il 2.2.2 puoi usare solo TFTP o il flash diretto di mtd se lo hai rootato.
