### ISSUE TITLE
[SECURITY FLAW] Web GUI exposed on WAN

### ISSUE THREAD

**Issue by knightian** [Ansuel/tch-nginx-gui#1031]
Web GUI is exposed on WAN when port 80 and 443 forwarded and the device the ports are forwarded to is offline. There is no option to disable this behaviour in the GUI.

Device Model: TG789MYRvac v2 HP
Gui Version: 9.6.50

Description of problem: The web GUI inteface has taken over my ports 80 and 443 when my device that would normally accept the connections on port 80 or 443 goes offline. Instead of going to my usual services at port 80 or 443, it exposes the Web GUI of the modem to the public. 

I have spent time to go through all areas of the GUI and there seems to be no way to disable this behaviour.

Security risk.

**Comment by lorenzocanale-LC** [comment]
I think it depends on the Device configuration, not directly on the GUI.
#887

**Comment by knightian** [comment]
@lorenzocanale-LC Ah yes I see you found the same problem.

**Comment by knightian** [comment]
It does indeed appear that referencing an IP instead of a MAC address mitigates the problem for now.

**Comment by FrancYescO** [comment]
closing this for https://github.com/Ansuel/tch-nginx-gui/issues/887
