### ISSUE TITLE
Is there a way to disable wireless isolation?

### ISSUE THREAD

**Issue by ferrarimarco** [Ansuel/tch-nginx-gui#1032]
Hi!

Is there a way to disable wireless isolation between devices connected to different wireless networks? Or is it just that the routes are missing?

Thanks for all your work on this!

**Comment by FrancYescO** [comment]
depending on you device you should just change your wireless config accordly..

<img width="320" alt="image" src="https://user-images.githubusercontent.com/4574593/102193719-b9fbe900-3ebc-11eb-96dc-5bf15788532a.png">

**Comment by ferrarimarco** [comment]
Thanks @FrancYescO ! I was looking in the GUI :)
