### ISSUE TITLE
Il router non si connette al PPP

### ISSUE THREAD

**Issue by Andrea055** [Ansuel/tch-nginx-gui#1033]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[tmp.zip](https://github.com/Ansuel/tch-nginx-gui/files/5694954/tmp.zip)

Device Model: Technicolor DGA4131
Gui Version:9.6.25-3b0cbe40

Description of problem: Il modem non si riesce al collegare al PPP e resta bloccato, trova la linea (xdsl,wan e fibra) ma non si collega, provato su FTTH Windtre e ADSL Tim

How to reproduce (if possible):Provare a connettersi ad una rete che usa il PPPoe routed

Media/Photos (if [[possible):
![unknown (1)](https://user-images.githubusercontent.com/26500347/102201102-f122c800-3ec5-11eb-8d33-735bdc13c9a6.png)

**Comment by FrancYescO** [comment]
immagino la GUI c'entra poco, semplicemente hai messo impostazioni sbagliate.

quasi sicurametne il VLAN ID o ne caso della ADSL VPI/VCI.

**Comment by Andrea055** [comment]
Ho controllato più volte sul sito della Tim, sembra giusto.
![unknown (2)](https://user-images.githubusercontent.com/26500347/102203520-faf9fa80-3ec8-11eb-911a-e20c6971c4bd.png)

**Comment by FrancYescO** [comment]
uci show network
uci show xtm

**Comment by Andrea055** [comment]
Senza wansensing sembra andare, grazie per il supporto

**Comment by BeTmAsTeR** [comment]
Commento qui sotto per non stare ad aprire un'altra issue, sto avendo questo stesso problema col mio 789vac v2 TIM

Resetto il router, già dalla GUI technicolor "stock" noto che il router non si connette al PPP, scarico la gui manualmente e la copio con SCP, avvio l'installazione pensando possa risolvere il problema, il problema non si risolve, come nello screenshot di Andrea trova la linea ma non il PPP

I dati sono corretti, sono gli stessi che usavo fino ad ieri e che ho comunque ricontrollato per sicurezza

uci show network:
`root@dsldevice:~# uci show network
network.loopback=interface
network.loopback.ifname='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.globals=globals
network.globals.ula_prefix='auto'
network.globals.default_ps='0'
network.lan=interface
network.lan.type='bridge'
network.lan.proto='static'
network.lan.ipaddr='192.168.1.1'
network.lan.netmask='255.255.255.0'
network.lan.force_link='0'
network.lan.igmp_snooping='1'
network.lan.ipv6='0'
network.lan.ip6assign='64'
network.lan.pppoerelay=''
network.lan.ifname='vlan_eth0' 'vlan_eth1' 'vlan_eth2' 'vlan_eth3'
network.eth0=device
network.eth0.mtu='1500'
network.eth0.name='eth0'
network.eth1=device
network.eth1.mtu='1500'
network.eth1.name='eth1'
network.eth2=device
network.eth2.mtu='1500'
network.eth2.name='eth2'
network.eth3=device
network.eth3.mtu='1500'
network.eth3.name='eth3'
network.vlan_eth0=device
network.vlan_eth0.type='8021q'
network.vlan_eth0.ifname='eth0'
network.vlan_eth0.name='vlan_eth0'
network.vlan_eth0.mtu='1500'
network.vlan_eth0.vid='1'
network.vlan_eth1=device
network.vlan_eth1.type='8021q'
network.vlan_eth1.ifname='eth1'
network.vlan_eth1.name='vlan_eth1'
network.vlan_eth1.mtu='1500'
network.vlan_eth1.vid='1'
network.vlan_eth2=device
network.vlan_eth2.type='8021q'
network.vlan_eth2.ifname='eth2'
network.vlan_eth2.name='vlan_eth2'
network.vlan_eth2.mtu='1500'
network.vlan_eth2.vid='1'
network.vlan_eth3=device
network.vlan_eth3.type='8021q'
network.vlan_eth3.ifname='eth3'
network.vlan_eth3.name='vlan_eth3'
network.vlan_eth3.mtu='1500'
network.vlan_eth3.vid='1'
network.bcmsw_int=switch
network.bcmsw_int.reset='1'
network.bcmsw_int.type='bcmsw'
network.bcmsw_int.qosimppauseenable='0'
network.bcmsw_int.jumbo='1'
network.bcmsw_int.unit='0'
network.bcmsw_int.enable_vlan='0'
network.bcmsw_ext=switch
network.bcmsw_ext.reset='1'
network.bcmsw_ext.type='bcmsw'
network.bcmsw_ext.qosimppauseenable='0'
network.bcmsw_ext.unit='1'
network.bcmsw_ext.enable_vlan='1'
network.bcmsw_ext.jumbo='1'
network.lan_switch=switch_vlan
network.lan_switch.device='bcmsw_ext'
network.lan_switch.vlan='1'
network.lan_switch.ports='1* 2* 3* 4* 8t'
network.wan=interface
network.wan.proto='pppoe'
network.wan.vendorid='Technicolor'
network.wan.authfail='0'
network.wan.mtu='1500'
network.wan.ipv6='0'
network.wan.release='1'
network.wan.iface6rd='0'
network.wan.username='timadsl'
network.wan.keepalive='4,20'
network.wan.metric='0'
network.wan.password='timadsl'
network.wan.ifname='vlan_wan'
network.wan.peerdns='1'
network.wan.auto='1'
network.vdsl_check=interface
network.vdsl_check.proto='pppoe'
network.vdsl_check.ifname='ptm0'
network.vdsl_check.keepalive='5,10'
network.vdsl_check.auto='0'
network.vdsl_check.reqopts='1 3 6 15 33 42 51 121 249'
network.vdsl_check.vendorid='Technicolor'
network.vdsl_check.graceful_restart='1'
network.vdsl_check.authfail='0'
network.vdsl_check.mtu='1500'
network.vdsl_check.ipv6='0'
network.vdsl_check.release='1'
network.vdsl_check.iface6rd='0'
network.bt_iptv=interface
network.bt_iptv.ifname='vlan_wan'
network.bt_iptv.auto='1'
network.bt_iptv.proto='static'
network.bt_iptv.ipaddr='169.254.10.1'
network.bt_iptv.netmask='255.255.255.255'
network.eth4=device
network.eth4.mtu='1500'
network.eth4.name='eth4'
network.ptm0=device
network.ptm0.mtu='1508'
network.ptm0.name='ptm0'
network.vlan_wan=device
network.vlan_wan.type='8021q'
network.vlan_wan.ifname='ptm0'
network.vlan_wan.mtu='1508'
network.vlan_wan.name='vlan_wan'
network.vlan_wan.vid='101'
network.wwan=interface
network.wwan.auto='1'
network.wwan.metric='10'
network.wwan.proto='mobiled'
network.wwan.session_id='0'
network.wwan.profile='1'
network.wan6=interface
network.wan6.ifname='@wan'
network.wan6.proto='dhcpv6'
network.wan6.reqopts='12 21 22 23 24 25 31 56 64 67 82 83'
network.wan6.noslaaconly='1'
network.wan6.iface_464xlat='0'
network.guest=interface
network.guest.proto='static'
network.guest.type='bridge'
network.guest.ipv6='0'
network.guest.ip6hint='1'
network.guest.netmask='255.255.255.128'
network.guest.ipaddr='192.168.168.126'
network.guest.ifname='wl0_1' 'wl1_1'
network.guest.force_link='0'
network.config=config
network.config.wan_mode='pppoe'
network.ipoe=interface
network.ipoe.proto='dhcp'
network.ipoe.metric='1'
network.ipoe.reqopts='1 3 6 43 51 58 59'
network.ipoe.release='1'
network.ipoe.neighreachabletime='1200000'
network.ipoe.neighgcstaletime='2400'
network.ipoe.ipv6='1'
network.waneth4=device
network.waneth4.enabled='1'
network.waneth4.type='8021q'
network.waneth4.name='waneth4'
network.waneth4.vid='835'
network.wanptm0=device
network.wanptm0.enabled='1'
network.wanptm0.type='8021q'
network.wanptm0.name='wanptm0'
network.wanptm0.vid='835'
`

uci show xtm
`root@dsldevice:~# uci show xtm
xtm.ptm0=ptmdevice
xtm.ptm0.priority='low'
xtm.atm0=atmdevice
xtm.atm0.ulp='ppp'
xtm.atm0.vpi='0'
xtm.atm0.vci='38'
xtm.atm0.path='fast'
xtm.atm0.enc='vcmux'
xtm.atmwan=atmdevice
xtm.atmwan.ulp='eth'
xtm.atmwan.vpi='8'
xtm.atmwan.vci='35'
xtm.atmwan.path='fast'
xtm.atmwan.enc='llc'
`

Questa cosa mi è già successa precedentemente ma ho sempre risolte reinstallando completamente, stavolta però vorrei capire il motivo

Grazie in anticipo :+1:
