### ISSUE TITLE
Minor corrections in GUI and Bank Info.

### ISSUE THREAD

**Issue by PrototypeGR** [Ansuel/tch-nginx-gui#1034]
Device Model: DGA4130
Gui Version: 9.6.55-0c0ca39d

Description of problem:

1. First small issue is bank_1 is not showing the Active Version.
2. Small correction to some English words, It is **advised** to check this if you are downgrading the firmware. and After this you **have** to reinstall the GUI.  and full stop (.) at the end of the 3rd sentence.

Media/Photos (if possible):
![image](https://user-images.githubusercontent.com/14006475/102208114-ab6efb00-3ed7-11eb-989c-914e2001551d.png)
![image](https://user-images.githubusercontent.com/14006475/102208824-8fb82480-3ed8-11eb-807c-57ecd3d3afd2.png)

**Comment by FrancYescO** [comment]
1. is just correct as is. bank1 is used as modoverlay.
