### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by lorenzocanalelc** [Ansuel/tch-nginx-gui#1036]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: Tg789vac V2
GUI Version: gui_hash 'd41d8cd98f00b204e9800998ecf8427e' (Should be latest)

After upgrading the GUI from 9.6.58 to latest I'm not able to access it anymore (And I had to upgraded it via ssh because the GUI was stucked on Idle... when trying to update). The GUI report 403 Forbidden and logread says 

```
Wed Dec 16 08:13:22 2020 daemon.err nginx: 2020/12/16 08:13:22 [error] 8431#0: *4 directory index of "/www/docroot/" is forbidden, client: 192.168.10.243, server: localhost, request: "GET / HTTP/1.1", host: "192.168.10.1"
Wed Dec 16 08:13:25 2020 daemon.err nginx: 2020/12/16 08:13:23 [error] 8431#0: *5 lua entry thread aborted: runtime error: /usr/lib/lua/web/lp.lua:175: bad argument #1 to 'setfenv' (integer expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'setfenv'
	/usr/lib/lua/web/lp.lua:175: in function 'include'
	/usr/lib/lua/web/web.lua:188: in function 'exit'
	/usr/lib/lua/web/sessionmgr.lua:248: in function 'redirectIfNotAuthorized'
	/usr/lib/lua/web/sessionmgr.lua:368: in function 'checkrequest'
	Wed Dec 16 08:13:49 2020 daemon.notice [4243]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
```
The second error happened after trying to access via HTTPS

**Comment by FrancYescO** [comment]
firmware? if this cannot be replicated probably better to just ignore it as it could be a per-device issue..

**Comment by lorenzocanalelc** [comment]
Fixed by sending upgradegui via ssh
