### ISSUE TITLE
SSH indicator wrongly reports disabled after Gui Update

### ISSUE THREAD

**Issue by Dark4Codrutz** [Ansuel/tch-nginx-gui#1039]
Device Model/Firmware: DGA4132
GUI Version: 9.6.65 (even older)

Description of problem, HOW TO REPRODUCE, Media/Photos:

After Gui Update the "SSH enabled" indicator is grayed/disabled on the Cards homepage and the toggle inside the System Extras modal results disabled but in fact the functionality is enabled (from pre-update) and working.

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/960

**Comment by Dark4Codrutz** [comment]
ups, my bad 😣
should have searched first
