### ISSUE TITLE
MAC address showed incorrectly under Wireless Access Control List

### ISSUE THREAD

**Issue by Digitalone1** [Ansuel/tch-nginx-gui#1046]
Device Model/Firmware: MediaAccess TG789vac v2
GUI Version: 9.6.25-3b0cbe40

Description of the problem:
MAC addresses under Wireless Access Control List are proceeded by `MAC Address" >`.
Just add a MAC address and see it yourself. I think it's easily reproducible, at least it happens on my version.

**Comment by FrancYescO** [comment]
just for reference 
<img width="593" alt="immagine" src="https://user-images.githubusercontent.com/4574593/102721642-562e5180-42fc-11eb-9c97-95d44924226d.png">
