### ISSUE TITLE
GUI support of VLAN modification

### ISSUE THREAD

**Issue by deldos** [Ansuel/tch-nginx-gui#1047]
Hi all,

I am switching from VDSL to bonded VDSL where instead of the modem features the connection will be done over ethernet cable.

My modem is:

Product Name DGA ( DGA4132 )
Software Version AGTHP_2.0.0
GUI: 9.6.65

In order to do that I need to change the parameters from the GUI. Unfortunately I am not able to see any similar option. In the past two days I was reading a lot of posts but none of them was clear how I can make a modification to achieve this required from T-mobile:

General parameters for VDSL when connecting a modem via VDSL bonding bridge (Terminator)
This is a connection where the Ethernet cable (RJ45) from the Cetin Terminator leads to the WAN port of the xDSL modem.

Parameter		Value
WAN service type	PPPoE
Type			Ethernet
MTU			1492
VLAN			allow
802.1P Priority		0
802.1Q VLAN ID		848
PPP Username		adsl
PPP Password		adsl__

Appreciate any suggestions how this setting can be done.

Thank you in advance
DelDos

**Comment by FrancYescO** [comment]
<img width="527" alt="immagine" src="https://user-images.githubusercontent.com/4574593/102764264-2eca9980-437b-11eb-8ab2-e6747d90f60a.png">
