### ISSUE TITLE
GUI 9.6.67 - Strings not translated

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#1048]
@Ansuel 
@FrancYescO 

NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: TIM HUB
GUI Version: 9.6.67

Please go to Cards >> Mod GUI >> Debug Report and press the Generate button.
Attach the debug file here:

Description of problem, HOW TO REPRODUCE, Media/Photos:

Stringhe non tradotte nella GUI

**_------------------------ Opzioni e utility GUI_**

- Stringhe non presenti nei file lingua

CWMP Spoof Settings

Disable CWMP Update. Any firmware update from CWMP will be rejected and not flashed. Consider that CWMP that request a firmware update will keep requesting it until the update is actually installed. Autoconfiguration won't work. Manually set the version in the System Extra tab to spoof a version or upgrade the firmware.

Disable CWMP Update

Change the Modem Serial. Consider that the modem serial is the Factory ID + Serial.

Modem Serial

Debug Report & Advanced settings

**_------------------------ Wifi_**

- Stringhe presenti nel fuile lingua ma non tradotte

Short Guard Interval

Space Time Block Code

Force Radio Down

- Stringa presenet solo nel file lingua

Burst frame

**_------------------------ Elenco applicazioni_**

Change the default page in system-extra to set this GUI as default

**_------------------------ Condivisione stampante_**

-S embra che la traduzione non funzioni

To connect: \\192.168.1.1\ or \\modemtim\

**_------------------------ Configurazione XDSL_**

- Stringhe non tradotte

Phy Extra Value

Phy Extra Mask

**Comment by bovirus** [comment]
@Ansuel 
@FrancYescO 

Could be possible to update the source code to add language strings?

**Comment by FrancYescO** [comment]
#1054
