### ISSUE TITLE
RFC3021 seems to be unsupported

### ISSUE THREAD

**Issue by fra-pel** [Ansuel/tch-nginx-gui#1050]
Hi,
first of all thank you for the great job you do.

I need to set up a FTTH connection with static ip address P-t-p on subnet mask /31 (RFC3021), but when I go to set the subnet mask (255.255.255.254) the system gives me an error ("subnet mask non corretta".)

If I try to set the subnet mask from ssh with the command: `ifconfig eth4 netmask 255.255.255.254` everything works perfectly but after a few hours the subnet mask is changed automatically.

If i set the netmask 255.255.255.254 on LUCI WebUI works but i like your GUI 👍 

THANKS

Device Model: DGA ( DGA4130 )
Firmware: AGTEF_2.2.1 
GUI Version: 9.6.65

**Comment by Ansuel** [comment]
The errori Is displayed in broadband (Internet) settings right?

Il Mar 22 Dic 2020, 17:04 Francesco Pellegrino <notifications@github.com>
ha scritto:

**Comment by fra-pel** [comment]
Yes,

![RFFC3021](https://user-images.githubusercontent.com/18364456/102909935-04abd100-447a-11eb-8756-d6bd13b0460e.PNG)
