### ISSUE TITLE
XMAS LED Lightshow Easteregg?

### ISSUE THREAD

**Issue by rkilchmn** [Ansuel/tch-nginx-gui#1051]
Hi,

Just wondering if others experienced a XMAS LED Lightshow?
My router just started flashing the multi-color LEDs pretty much randomly.
Everything seems to work fine, so I assume this is a hidden "easteregg" feature and I was not hacked?

Marry XMAS around the world from Australia,

Cheers Roger

**Comment by cjsmns** [comment]
Yes, I noticed this too. I thought something was up with my modem, so I rebooted it and then came here and saw your comment. LOL.

**Comment by daddychill95** [comment]
Same here on my Telstra Smart Modem Gen2! Thought I'd properly broken something until I saw your comment!

**Comment by Robb110** [comment]
Oh thank God. I was so scared while playing Valorant that at any moment it could go down lol

**Comment by mada199122** [comment]
is there a way to turn the led off?
Thanks

**Comment by Arci996** [comment]
> is there a way to turn the led off?
I'd also like to turn that off, it's great that there is a Christmas easter egg but I have my modem in my bedroom and sleeping is kinda hard with bright lights blinking.

**Comment by cjsmns** [comment]
I just logged into the web interface and had a look at the CRON Rules. Found one in there for /etc/christmas_tree.sh. I just deleted it, then logged in via ssh and ran a `ps` to find the processes running and then I just ran a `kill` command to kill all the processes running that the script had started.

Mind you, this just stopped it, so all the LED's are in their last state, so a reboot later should fix that.

**Comment by Rithari** [comment]
> I just logged into the web interface and had a look at the CRON Rules. Found one in there for /etc/christmas_tree.sh. I just deleted it, then logged in via ssh and ran a `ps` to find the processes running and then I just ran a `kill` command to kill all the processes running that the script had started.
> 
> Mind you, this just stopped it, so all the LED's are in their last state, so a reboot later should fix that.

Infinite cheers for this. 
I couldn't wrap my head around it last year and this year it finally clicked. I thought they weren't christmas lights last year and just some bug, took so long to find a solution that it had stopped by itself. This year I figured it out instantly. Thankfully you guys did all the hard work already and found the relevant stuff!  What would be great though is a GUI option for it. 
Merry Christmas everyone!

**Comment by zacchi4k** [comment]
I appreciate the Easter egg, but please next time put a warning or disclaimer about it, I was scared someone managed to get remote access to my router or something :P

**Comment by deldos** [comment]
I believe that you can also modify the blinking lights from GUI:

![image](https://user-images.githubusercontent.com/17853989/103097963-62225800-4609-11eb-9f11-7a1f683bc70d.png)

**Comment by diptanw** [comment]
This is truly one of the best easter eggs I’ve seen. Nonetheless, the first thought was that somebody hacked my router. Merry Christmas!

**Comment by Rithari** [comment]
> I believe that you can also modify the blinking lights from GUI:
> 
> ![image](https://user-images.githubusercontent.com/17853989/103097963-62225800-4609-11eb-9f11-7a1f683bc70d.png)

That's odd, I've never seen that before. 



> This is truly one of the best easter eggs I’ve seen. Nonetheless, the first thought was that somebody hacked my router. Merry Christmas!

Undoubtedly a great Easter egg, but a heads up would've been cool so no one gets freaked out or bashes their heads about it.
Happy holidays!
