### ISSUE TITLE
Turn off LEDs on DGA4131FWB

### ISSUE THREAD

**Issue by BreakSecurity** [Ansuel/tch-nginx-gui#1052]
With the latest GUI the LEDs do NOT turn off correctly. To solve:

in /etc/rc.local
`(sleep 10m && for i in /sys/class/leds/* ; do echo 0 > "$i"/brightness ; done) &`

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/890
https://github.com/Ansuel/tch-nginx-gui/issues/1021

your's just a workaround not applicable in all conditions.
