### ISSUE TITLE
Original firmware showed up after GUI upgrade

### ISSUE THREAD

**Issue by Digitalone1** [Ansuel/tch-nginx-gui#1053]
Device Model/Firmware: MediaAccess TG789vac v2

Description of problem:
Yesterday I rebooted the router and found out the original default Tiscali firmware:

```
Software Version 16.3
Firmware Version 16.3.7636-2921002-20170419153951
```

In the past I had #1007 issue. Then I resolved it even if it was very hard and frustrating. I remember to have already rebooted the device without issues. A couple of days ago I launched the update to 9.6.65 and everything went fine, network was working, no problem.

Last night I had to reboot it. Many hours passed after the update, quite one day after, but at the startup I found out the original default Tiscali firmware.

Honestly, I will stick with it, I'm very tired of having issues with this project even if I like it and appreciate your great work. Besides, the GUI became very slow in the last times, I had to wait about a minute to switch from Stats to Cards page. The original firwmare surprised me with its fast responsiveness, even if the lack of some features is a downside.

Just out of curiosity, I'd like to know why this thing happened. Do you have an idea?

And, please, would you be very kind to tell me how I can modify the textual config to enable the wifi regdomain bypass for increasing the power transmission? At least I will enable the root and try to do it from ssh console. That was the only option I really needed.

Thanks.

Merry Christmas and happy new year.

**Comment by Digitalone1** [comment]
I thought the root had to be enabled, but it's already done and I can access to ssh through root user set after the recovery mode I did following #1007.

**Comment by FrancYescO** [comment]
unfortunately performances on mips devices never been that good, but pretty sure you got some other problem that caused the "1min switch to cards"

the issue that caused your full reset is already solved in the latest version, my suggestion is to have an advanced backup to have it ready to reset in these cases

you can change the /etc/config/wireless to change region and set one with lower restrictions

**Comment by Digitalone1** [comment]
@FrancYescO  Any way to access the device through Filezilla to copy the config files on my PC?

**Comment by FrancYescO** [comment]
no it does not support SCP protocol, you should use winscp
