### ISSUE TITLE
Can't upgrade firmware from 1.0.3 to 2.2.1, DGA4130

### ISSUE THREAD

**Issue by Sam-arch99** [Ansuel/tch-nginx-gui#1059]
Device Model/Firmware: DGA4130/AGTEF
GUI Version: 9.6.65-stable, 9.6.69-dev

I'm trying to upgrade my DGA4130 from firmware 1.0.3 to 2.2.1, so I've installed the latest dev GUI but my DGA always reverts to 1.0.3 + official TIM GUI after GUI Firmware upgrade to 2.2.1.
Downgrading the GUI to 9.5.17-stable also doesn't work, I always end up with the official TIM GUI. Upgrading again to 9.6.x does work but for some reason I'm not able to upgrade the Firmware with this version. I guess it has to do something wit OBP but I don't know how to fix this issue.
When installing the MOD GUI (9.6.69-dev or 9.6.65-stable) I get the following error:
```
/etc/rc.common: line 1: can't create /proc/prozone/bootfail: nonexistent directory
/etc/rc.common: line 1: can't create /proc/prozone/bootcounter: nonexistent directory
/etc/rc.common: line 1: can't create /proc/prozone/bootbank: nonexistent directory
```
rootdevice log 9.5.38-stable.:
```
Root Script: Installing in progress...
killall: ledfw.lua: no process killed
/etc/rc.common: /etc/modgui_scripts/04_config.sh: line 632: /etc/init.d/mobiled: Permission denied
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
Invalid ISP
mkdir: can't create directory '/overlay/bank_1': File exists
cp: can't stat '/overlay/bank_2/*': No such file or directory
Unlocking /dev/mtd3 ...

Writing from /dev/mtd4 to /dev/mtd3 ...
```
Result: TIM GUI with factory defaults, root still active. It also takes ages to boot after trying to install 9.5.x GUI.

So for some reason my device does seem to refuse any MOD GUI version < 9.6.x. When installing 9.5.x via ssh my DGA reboots and goes back to the official TIM GUI (without loosing root).
Is there any way to remove the MOD GUI 9.6.x files without removing root so I'm able to install 9.5.x and upgrade to fw 2.2.1? 
Any ideas how to fix this problem?

**Comment by Sam-arch99** [comment]
I've managed to downgrade to 9.5.38-stable and was able to upgrade the firmware to 2.2.1. I've installed the latest dev gui 9.6.69 and first I was missing IP Extras, System Extras and xDSL config at the GUI but after a factory reset + reinstall of the MOD GUI everything was showing up. I don't know if this was a specific problem with my device or a general 9.6.x GUI problem. Anyway I'm happy that everything is working now!

**Comment by FrancYescO** [comment]
Too much mixing of versions too hard to undestand what's happening, also if you do not provide a debug zip or logs from `/overlay/modgui_log`, consider 9.6.65 as a non-downgradable GUI version.
just use the latest version without coming from some other oldeversionmix (`mtd -r erase rootfs_data` and directly root the 1.0.3) and all should go good.

disappearing of cads is caused by TIM CWMP, `upgradegui` should (at least temporary) fix this issue.
