### ISSUE TITLE
Missing Card Background Image

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#106]
With Telstra TG800 Internet Access (003_internet.lp) card has no background (world) image.  No background image on NFC (016_nfc.lp) card either.

**Comment by kevdagoat** [comment]
Clear cache on your browser, worked for me

**Comment by flywire** [comment]
Cleared cache, still not displayed. Where is the image?

**Comment by Ansuel** [comment]
can you pass me a dump of the flash? i need the extra card for nfc support...

**Comment by flywire** [comment]
Firmware emailed. Version 8.7.24 actually removes NFC card.

**Comment by Ansuel** [comment]
can't find it also 

the firmware i need is the output of this command


dd if=/dev/mtd3 of=/tmp/bank_1
dd if=/dev/mtd4 of=/tmp/bank_2

**Comment by flywire** [comment]
Ethernet: [Fixed Wireless Discussion (NBN)](https://whirlpool.net.au/wiki/highlights_from_the__fixed_wireless_discussion__nbn___thread) - **7 W-NTD**

**Comment by Ansuel** [comment]
@flywire sorry but can you give me one screen of the missing image ?

**Comment by flywire** [comment]
Full screen shot emailed.
version 8.7.33: nfc card displayed on tg800 with background image. :)
