### ISSUE TITLE
Registering voip on DGA4132 

### ISSUE THREAD

**Issue by Kwbmm** [Ansuel/tch-nginx-gui#1060]
Device Model/Firmware: DGA4132
GUI Version: 9.6.65-89342d7b

After rooting and installing this GUI, for whatever reason, TIM Voip stopped working. I don't care much about it, to be honest.

Since I am bored now, I have attempted to set it up: I managed to retrieve the SIP password and the outbound proxy, and fill them in the voip config. However, I was not successful. 

![sip profile](https://user-images.githubusercontent.com/8115374/103485407-47649600-4df6-11eb-9715-c1c584b309ec.png)

I'm quite confident that the sip profile is correct: in `tel num` I set my phone number, in the form  `0039<prefix><number>` and as password I set the sip psw.

I'm not sure the global config is right though:

![image](https://user-images.githubusercontent.com/8115374/103485440-a32f1f00-4df6-11eb-9df9-ff0e52fce02e.png)

I have attempted to set the outbound proxy in `Primary proxy` but I still can't register. The only other thing I change is the `Name`, that I set to TIM, but that shouldn't matter. The rest of the field in the screenshot were prefilled.

Does anyone know how to fix this?

**Comment by Kwbmm** [comment]
Well, disregard the above. I know get green lights on both `Registered` and `Call Status`. I fixed by putting the `tel num` in the form `+39<prefix><num>` instead of the 2 leading 0s.

However, the phone still doesn't work, I get the same tone you get when the line is busy. Not sure if it's the phone's issue or if I need to set something else up on the router

**Comment by FrancYescO** [comment]
if it was autoconfigured you should just not change the default values... if you change DNS it will stop working as voip domains are only resolved by the TIM dns

**Comment by Kwbmm** [comment]
Yeah, it's definitely the DNS. Changing the DNS is the only reason why I installed this guy :D

Thanks anyway! :)
