### ISSUE TITLE
GUI stability issue?

### ISSUE THREAD

**Issue by PrototypeGR** [Ansuel/tch-nginx-gui#1063]
Device Model/Firmware: DGA4130/17.1.8049-0001002-20200722101309

GUI Version: 9.6.69-3bd8c3f6

Attach the debug file here: 
[DebugHelper2021-01-06-2236.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/5778079/DebugHelper2021-01-06-2236.tar.gz)

Description of problem: Could you please look at the debug and log files? Lately the router is losing Broadband connection (the LED goes red and Internet LED turns off for couple seconds/minutes and then it re-syncs again by itself. In general my connection won't last more than one day before it happens again.

**Comment by FrancYescO** [comment]
if it drop xDSL sync not a GUI issue but more likely a physical link VDSL issue.

you can just try to change xDSL driver to see if you find one with a better stability

**Comment by PrototypeGR** [comment]
Is there any way to get more xDSL drivers no matter the firmware version?

**Comment by FrancYescO** [comment]
you should see all available versions in the selectbox in xdsl page and probably few of these will not work

**Comment by PrototypeGR** [comment]
The versions which are shown are based on firmware version? Because I can see 6 of them only.

**Comment by PrototypeGR** [comment]
Also is it possible to upgrade firmware without losing any of the settings?

**Comment by FrancYescO** [comment]
if you do no have the possibility to select some xdsl drivers it's becouse are incompatible on the firmware.
firmware upgrades do not delete settings, but simply do an advanced backup before upgrade.

**Comment by PrototypeGR** [comment]
As i have tried in the past, if i take a backup and i try restore it after i will get a error message that it's not possible to recover the settings due to different firmware version.

**Comment by PrototypeGR** [comment]
After firmware update i can't open Telephony settings 
[error.log](https://github.com/Ansuel/tch-nginx-gui/files/5805324/error.log)

**Comment by FrancYescO** [comment]
have you shared somewhere the dump of this firmware? (if RBI is missing)

**Comment by PrototypeGR** [comment]
No i haven,t only the log above. I can't provide any logs from this device anymore because i will stop using it since my provider sent me a new model which they just brought, Zyxel.
