### ISSUE TITLE
SSH state not reflected correctly in GUI

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#1069]
Device Model/Firmware: DGA 4132 Cobalt 18.3.k
GUI Version: 9.6.69

Description of problem:

On the "System Extra" card, the state of SSH is often not reflected correctly, mostly 'off' instead of the real state 'on'.
It seems that the state is not being read correctly out of the configuration upon boot. Once you toggle the state in a running session, it is correct again, but only to the next boot.

**Comment by Dark4Codrutz** [comment]
duplicate of #960

**Comment by meyergru** [comment]
Ah, right... closing this...
