### ISSUE TITLE
Cannot login with existed GUI password 

### ISSUE THREAD

**Issue by xvoidnessx** [Ansuel/tch-nginx-gui#1070]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Product: vcnt-a_telstra
Release: Champagne (18.1.c)
Version: 18.1.c.0585-2881002-20201117075121-997890ad60fe9778c40bd52bd30ef46eabcbe1e4
GUI Version: Telstra DJA0231 GUI Version 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: - cant logon

After installing the new GUI - my existing password to the GUI no longer work - is there any way to reset via ssh - i can still access ssh

**Comment by TheMKDev** [comment]
I have the same issue here. I tried resetting it, re-rooting and installing the GUI. Any solutions? Is it possible to set the password via SSH?

**Comment by FrancYescO** [comment]
```
uci set web.usr_admin.srp_verifier='27d5cc49530f8f1821f01cf7605b61645124e190e13e1defd6295d5160c0421ce0750c4b9324fb1a45ea805c94a0785f4ee9b15b7791bdda55c96536f684c246d845890627330ad4d689802057abfbc0db2d707e61f241a194369185a2d1d87127da527526359f991a62c31090d7541f24bab25e21880c53136241e3c9c552c53cdf66b8526262472b61cb5f21a227cbc64f7b7f7c7d0dda4b9214de024522a113acf5c6b33499f80e91474ffc4be2e351e32e178cb68fedefe2edee7d1f53078aa02e78760b89b50204b30a66d89e5aad3edce03e6a8eb4a36690d2614f05365d09a805222c33feabeae3f32c044745c68b1cd70adfebdb1b54e5b6efdc798d'
uci set web.usr_admin.srp_salt='cbee79d6'
uci commit web
```

password will be resetted to _admin_

**Comment by besbesbechir** [comment]
> ```
> uci set web.usr_admin.srp_verifier='27d5cc49530f8f1821f01cf7605b61645124e190e13e1defd6295d5160c0421ce0750c4b9324fb1a45ea805c94a0785f4ee9b15b7791bdda55c96536f684c246d845890627330ad4d689802057abfbc0db2d707e61f241a194369185a2d1d87127da527526359f991a62c31090d7541f24bab25e21880c53136241e3c9c552c53cdf66b8526262472b61cb5f21a227cbc64f7b7f7c7d0dda4b9214de024522a113acf5c6b33499f80e91474ffc4be2e351e32e178cb68fedefe2edee7d1f53078aa02e78760b89b50204b30a66d89e5aad3edce03e6a8eb4a36690d2614f05365d09a805222c33feabeae3f32c044745c68b1cd70adfebdb1b54e5b6efdc798d'
> uci set web.usr_admin.srp_salt='cbee79d6'
> uci commit web
> ```
> 
> password will be resetted to _admin_

the uci set web.usr_admin.srp_verifier is too long that cannot write it all in the command, it stops before this 044745c68b1cd70adfebdb1b54e5b6efdc798d'
any solution for this problem?

**Comment by Peter-3126** [comment]
The long command will end in a '>' prompt to allow you to past the rest of string. Execute the commend to get back to the command prompt #
Enter the remaining commands from the # prompt.
Worked the first time to reset to 'admin'. I changed the admin password in the web interface and it has locked me out ... will not change the password to admin a second time using this command sequence.
