### ISSUE TITLE
The login button works only if you click the text inside it

### ISSUE THREAD

**Issue by ferrarimarco** [Ansuel/tch-nginx-gui#1074]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4130, AGTEF_2.2.1
GUI Version: v9.6.65

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: N/A (will attach later if needed)

Description of problem, HOW TO REPRODUCE, Media/Photos:

1. Open the GUI login page.
2. Fill the username and password fields.
3. Click the Login button, but not on the "Login" string

This is a somewhat minor issue, but it's misleading because the GUI highlights the button once it acquires focus (example: with a muose-over event).

Thanks for all your work on this!

**Comment by capriele** [comment]
Please check this pull request: [link](https://github.com/Ansuel/tch-nginx-gui/pull/1083)

**Comment by ferrarimarco** [comment]
Nice, thanks!
