### ISSUE TITLE
Problema Pi-Hole + TIM Hub

### ISSUE THREAD

**Issue by MarcoInc** [Ansuel/tch-nginx-gui#1077]
Salve a tutti. Creo nuovamente un post su un problema che ho avuto anni fa (thread originale #885 ) e mi si sta ripresentando in forma diversa in questi mesi.
Il mio TIM-Hub (DGA4132) rootato allo stato attuale ha la GUI 9.6.65-89342d7b e FW AGTHP_2.2.1.
Riassumendo, avevo un problema ad usare Pi-Hole, su un Raspberry 3 B+, settandone l'IP nella sezione IP DNS nella scheda "Accesso ad Internet" del TIM-Hub, così da avere la copertura di Pi-Hole su tutta la rete. Il problema stava nel fatto che dopo una mezz'oretta la fonia (primo LED rosso acceso) smetteva di funzionare ma il Pi-Hole faceva lo stesso il suo lavoro. Sotto suggerimento @FrancYescO citandomi il thread #353  sono riuscito a risolvere il problema, a bloccare la pubblicità e ad usare la fonia correttamente, grazie ai seguenti comandi inviati al TIM-Hub via SSH:

```
 for i in $(cat /tmp/resolv.conf.ppp  | grep -v '^#' | grep nameserver | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}');
 do
   uci add_list dhcp.@dnsmasq[0].server="/telecomitalia.it/$i"
 done   
 
 uci commit dhcp
 /etc/init.d/dnsmasq restart 
```

Dopo un anno  abbandonai l'uso del Pi-Hole visto che volevo farci altri progetti. 
Da qualche mese ho provato ad riprendere il progetto Pi-Hole con il mio TIM-Hub ma mi si è presentato un nuovo problema.
Dopo aver configurato il tutto, come al solito la fonia non mi funzionava (solito primo LED rosso) e ho riusato i comandi sopracitati, e la fonia ha ripreso a funzionare, ma dopo averli inseriti, il Pi-Hole non fa assolutamente il proprio lavoro, seppur l'IP sia settato in IP DNS del TIM-Hub, e non bloccando più la pubblicità come se il server scritto nel comando non sia più corretto o come se gli anni sia cambiato qualcosa che rende il tutto incompatibile.
Ho provato ad usare il Pi-Hole con un altro modem e la fonia viene mantenuta e il Pi-Hole fa bene il suo lavoro, quindi ci sarebbe qualcosa che non va nel TIM-Hub stesso. Ho tentato di fare reset e ripristini di configurazione al TIM-Hub ma il problema rimane.
Come potrei riavere la mia fonia usando il Pi-Hole sul mio Tim-HUB allo stato attuale?
Grazie anticipatamente

**Comment by FrancYescO** [comment]
Non credo ci sia qualcosa per cui non dovrebbe funzionare, il DNS come lo stai impostando, sul timhub che lo assegna via DHCP? o nella pagina internet?

**Comment by SoteraMarco** [comment]
Il Raspberry ha un ip statico impostato dal TimHub che poi vado ad inserire qui:
![image](https://user-images.githubusercontent.com/47932432/110208026-08e76800-7e87-11eb-9991-c9e0200360e3.png)

nelle impostazioni DHCP ho lasciato tutto così com'è, anche perché se lo vado ad inserire qui l'IP del Raspberry, PiHole non fa il suo lavoro.
![image](https://user-images.githubusercontent.com/47932432/110207980-ba39ce00-7e86-11eb-8e2e-217f5534dfea.png)

Riguardo alla cache dici che devo pulirla/disabilitarà da PiHole? (giù estratto della documentazione ufficiale)
![image](https://user-images.githubusercontent.com/47932432/110208102-7d220b80-7e87-11eb-919a-55681ce66e11.png)

**Comment by MarcoInc** [comment]
Problema risolto. Descrivo il problema se magari qualcuno dovesse avere un problema simile.
Dopo aver analizzato il Query Log del PiHole, nel momento in cui il primo led diventava rosso, ho notato che un record segnava lo Status con Retried SERVFAIL. Dopo una ricerca online ho compreso che il problema stava nel Upstream DNS Resolver, ergo  il DNS Cloudflare integrato nel PiHole non riconosceva dei domini, gli stessi che posso trovare nell'impostazioni del VoIP del TimHub. Mi è bastato settare dei DNS custom con quelli della TIM è adesso il VoIP funziona come dovrebbe. Per chi fosse interessato i DNS di TIM sono:
85.38.28.6
85.38.28.7
Grazie!
