### ISSUE TITLE
Transmission/Amule/Aria2 restart trigger

### ISSUE THREAD

**Issue by capriele** [Ansuel/tch-nginx-gui#1079]
Probably it could be useful to trigger Transmission/Amule/Aria2 restart when the usb is plugged in and out.

Here you can find an example that simply trigger transmission restart (I'm supposing that transmission is currently installed on the device): 
- just create a file **XX-filename** under **/etc/hotplug.d/usb**
- **XX** is a number and should be greater than the biggest one present in this folder
- below you can find the file's content

```
root@dsl:/# cat /etc/hotplug.d/usb/60-transmission 
#!/bin/sh
/etc/init.d/transmission restart
```

**Comment by FrancYescO** [comment]
if you have the possibility insert these as PR so we can go faster :D

**Comment by capriele** [comment]
Yes, sure. The only thing that I miss is where to place my `/etc/hotplug.d/usb/60-transmission` inside the repo.
Do you prefer a more scripty way?
So, I can update the transmission installation script in order to create this file

**Comment by capriele** [comment]
You can find the pull request here: [link](https://github.com/Ansuel/tch-nginx-gui/pull/1080)
