### ISSUE TITLE
Problem to update and modem freezed

### ISSUE THREAD

**Issue by SuperKali** [Ansuel/tch-nginx-gui#1086]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4132 
GUI Version: LATEST

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:

Description of problem, HOW TO REPRODUCE, Media/Photos:
![modem](https://user-images.githubusercontent.com/19473898/114949428-54f7d600-9e51-11eb-9aaf-8939d331eab1.png)

**Comment by FrancYescO** [comment]
missing infos on the device and how the error appeared.
just issue `upgradegui` with the modem connected to internet to check if the error get fixed
