### ISSUE TITLE
VOIP not registering

### ISSUE THREAD

**Issue by milouk** [Ansuel/tch-nginx-gui#1091]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: Technicolor TG7892 v2

GUI Version: 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: [DebugHelper2021-06-14-2240.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/6650812/DebugHelper2021-06-14-2240.tar.gz)

Description of problem, HOW TO REPRODUCE, Media/Photos:

So I have tried to setup my VOIP without success. I have the SIP credentials and all the required info but it fails to register the number. (I know that VOIP needs VLAN ID 837 while Internet VLAN ID 835, but I don't know where I can set the VLAN ID for VOIP)

Here is a screenshot of a successfull call with the router from my ISP

<img width="1278" alt="Screenshot 2021-06-14 at 22 56 15" src="https://user-images.githubusercontent.com/22796276/121951828-1785cb00-cd64-11eb-92fb-9346cc39287d.png">

Also I can't seem able to enable secondary and third codec e.g., G.729

<img width="1136" alt="Screenshot 2021-06-15 at 00 15 20" src="https://user-images.githubusercontent.com/22796276/121960532-e5c63180-cd6e-11eb-970c-7dcc4e6d390e.png">

<img width="1361" alt="Screenshot 2021-06-14 at 22 41 31" src="https://user-images.githubusercontent.com/22796276/121949993-cf65a900-cd61-11eb-9322-6acb6a3c5753.png">
<img width="1361" alt="Screenshot 2021-06-14 at 22 43 07" src="https://user-images.githubusercontent.com/22796276/121950262-105dbd80-cd62-11eb-9e1a-f3e4b3072189.png">
<img width="1361" alt="Screenshot 2021-06-14 at 22 43 37" src="https://user-images.githubusercontent.com/22796276/121950271-13f14480-cd62-11eb-809e-95e70cbf74bd.png">
<img width="1361" alt="Screenshot 2021-06-14 at 22 43 58" src="https://user-images.githubusercontent.com/22796276/121950274-1489db00-cd62-11eb-9b52-a6c2e5b3b142.png">
<img width="1361" alt="Screenshot 2021-06-14 at 22 44 04" src="https://user-images.githubusercontent.com/22796276/121950278-15227180-cd62-11eb-9d94-3575d3d5b6f4.png">
<img width="1361" alt="Screenshot 2021-06-14 at 22 46 08" src="https://user-images.githubusercontent.com/22796276/121950476-574bb300-cd62-11eb-9955-cfc2cc074bc1.png">

by typing `logread | grep mmpbx` I get 

```
Mon Jun 14 22:34:56 2021 user.debug mmpbxd[2468]: caught signal 15
Mon Jun 14 22:34:56 2021 user.debug mmpbxd[2468]: [MMBRCMFXS]     :E: hwCleanup:849 - FXS-hwCleanup called
Mon Jun 14 22:34:56 2021 user.debug mmpbxd[2468]: [MMBRCMFXS]     :C: hwCleanup:880 - Error switching relay, returned error: 8
Mon Jun 14 22:34:56 2021 user.debug mmpbxd[2468]: [MMBRCMFXS]     :C: hwCleanup:880 - Error switching relay, returned error: 8
Mon Jun 14 22:34:58 2021 user.debug mmpbxd[2468]: [MMBRCM]        :E: onDspEventReceived:2314 - endpointdd ioctl (ENDPOINTIOCTL_ENDPT_GET_EVENT) returned (status:1)
Mon Jun 14 22:35:03 2021 user.info root: Mmpbx stopped, mmpbx.state=NAstopped
Mon Jun 14 22:35:05 2021 user.info root: Mmpbx starting mmpbx.state=STARTING
Mon Jun 14 22:35:14 2021 user.debug mmpbxd[2977]: [MEMM] Info: Pooldescr [memm_pooldesc] reallocated to increase its size (107 elements)
Mon Jun 14 22:35:17 2021 user.debug mmpbxd[2977]: [MMBRCMFXS]     :C: switchRelay:985 - Error switching relay, returned error: 8
Mon Jun 14 22:35:17 2021 user.debug mmpbxd[2977]: [MMBRCMFXS]     :C: switchRelay:985 - Error switching relay, returned error: 8
Mon Jun 14 22:35:18 2021 user.debug mmpbxd[2977]: [MMRVSIPIMPL::NETWORKOBJ]:C: onStackLogEvent:1924 - TRANSACTION  - TransactionTransportTrxStateChangeEv - pTransc=0x0xd6dbf8: Message failed to be sent (rv=0:OK)
Mon Jun 14 22:35:18 2021 user.debug mmpbxd[2977]: [MMRVSIPIMPL::REGTERMOBJ]:E: regTermObjFirewallUpdate:3835 - Unable to retrieve currentDestination from SIP network ..
Mon Jun 14 22:35:18 2021 user.debug mmpbxd[2977]: [MMRVSIPIMPL::REGTERMOBJ]:E: registerStateChanged:1327 - statusCode 0
Mon Jun 14 22:35:18 2021 user.debug mmpbxd[2977]: [MMRVSIPIMPL::REGTERMOBJ]:E: registerStateChanged:1379 - In case of a previous send socket error, retry after 30 sec```

**Comment by FrancYescO** [comment]
you cannot set more interfaces with VLAN ID from the GUI, you need to manually add the device and interface (from what i can see you already have the `voip` interface, you need to add the device with the VLANID and make voip  interface use this device) via uci or directly in `/etc/config/network` than select the added interface in the Telephony general card.

**Comment by FrancYescO** [comment]
probably the proto is not dhcp? these settings really depends on what your ISP needs.. 

also the `option ip4table 'iptv'` looks strange in the voip block

**Comment by milouk** [comment]
What could be instead of dhcp? Udp maybe? 

Here is a successul register call to my isp 

<img width="1278" alt="Screenshot 2021-06-14 at 22 56 15" src="https://user-images.githubusercontent.com/22796276/121951828-1785cb00-cd64-11eb-92fb-9346cc39287d.png">

Regarding to `option ip4table 'iptv'` I put `voip`. Does this sound better?

**Comment by FrancYescO** [comment]
sincerly idk what the `ip4table` option does, try also removing and restarting network, your main issue is that you have no routing to the network 10.x as you can see from the `ip r` command but seems the vlan_voip interface is UP so probably dhcp as proto is okay

go also in `/etc/config/mmpbxrvsipnet` to be sure that the transport_type is UDP

**Comment by milouk** [comment]
ok so mini update on this. 

I read somewhere that my ISP enables an internal "local" network and i Have to setup a second wan interface to get an IP in order to register. (whatever that means)

However, I changes the registar and proxy from `ngn.hol.net` to an IP i found in the logs of the router from my ISP 

```
DNS SRV Info:
  enable=1, normal_dns=0 no=2 cur=0 cur_regok=0 failover_in_fallback=0
slist[0] priority=10, weight=50 ttl=900, primary_proxy=1 target=10.120.25.57:5060
slist[1] priority=20, weight=50 ttl=900, primary_proxy=0 target=10.120.65.9:5060
  dtmf_relay=0 (0:inband, 1:rfc2833, 2:SIP INFO, 3:AUTO)
```

Now I am gettings

```
Tue Jun 15 21:12:16 2021 user.debug mmpbxd[412]: [MEMM] Info: Pooldescr [memm_pooldesc] reallocated to increase its size (107 elements)
Tue Jun 15 21:12:19 2021 user.debug mmpbxd[412]: [MMBRCMFXS]     :C: switchRelay:985 - Error switching relay, returned error: 8
Tue Jun 15 21:12:19 2021 user.debug mmpbxd[412]: [MMBRCMFXS]     :C: switchRelay:985 - Error switching relay, returned error: 8
Tue Jun 15 21:12:20 2021 user.debug mmpbxd[412]: [MMRVSIPIMPL::REGTERMOBJ]:E: regTermObjFirewallUpdate:3835 - Unable to retrieve currentDestination from SIP network ..
Tue Jun 15 21:12:20 2021 user.debug mmpbxd[412]: [MMRVSIPIMPL::REGTERMOBJ]:E: registerStateChanged:1327 - statusCode 403
```

And in the stats page `Registration refused`.

Though the credentials i enter are correct 100%. 

PS `/etc/config/mmpbxrvsipnet` transport_type is indeed UDP

**Comment by milouk** [comment]
Update:

I increased the logging and got this:

```
Tue Jun 15 21:44:33 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: profileTimerCb:454 - SIP registration state: Registering
Tue Jun 15 21:44:33 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: onMsgRecv:2945 - get message
Tue Jun 15 21:44:33 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: onMsgRecv:2949 - statusCode 403
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: regTermObjFirewallUpdateByDNSSRV:3961 -  No need to acceptAllDnssrvProxies: 0
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMNETWORKSIP]  :D: mmNetworkSipGetSubscriptionNotifier:6947 - MMPBX_ERROR_NOTSUPPORTED
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:E: regTermObjFirewallUpdate:3835 - Unable to retrieve currentDestination from SIP network ..
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMNETWORKSIP]  :D: mmNetworkSipGetSubscriptionNotifier:6947 - MMPBX_ERROR_NOTSUPPORTED
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::INTERFACESELECTION]:D: defaultEventProcess:550 - Event (2) not be process (MMPBX_ERROR_NOTSUPPORTED)
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: regTermObjStartInterfaceUpdateAfterBackoff:4030 - Failed to start interface selection with network = 0x67e468 (MMPBX_ERROR_NOTSUPPORTED)
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:E: registerStateChanged:1327 - statusCode 403
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::NETWORKOBJ]:D: networkObjNetworkAutoResetProcess:2502 - auto reset is disabled, no need do reset network for 0x67e468
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: registerStateChanged:1386 - auto reset sip network not run!
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: registerStateChanged:1392 - start timer with interval  180 seconds
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: registerStateChanged:1402 - Restarting config timer for regTerm (0x674970)
Tue Jun 15 21:44:34 2021 user.debug mmpbxd[7869]: [MMRVSIPIMPL::REGTERMOBJ]:D: registerStateChanged:886 - Application handle (Mtf Terminal handle) of RegClient not found: Unable to process RegState change!
```

Does this help?

**Comment by FrancYescO** [comment]
it's not a credentials error and probably not a configuration of telephony card, the issue is something that you cannot setup from the GUI and is the second interface for the voip.

probably until issuing `ip r` does not appear a line starting with 10. the issue is still somewhere in the network file

take a look also at file `/etc/config/mwan` and check if voip interface is setted here

**Comment by milouk** [comment]
So, `etc/config/mwan` outputs 

```
root@OpenWrt:~# cat /etc/config/mwan

config globals 'globals'

config host 'mmpbx'
	option policy 'voip_only'

config host 'udhcpc'
	option path '/sbin/udhcpc'
	option policy 'voip_only'

config rule 'voipr1'
	option policy 'voip_only'
	option proto 'tcpudp'
	option src_port '5060'
	option src 'loopback'

config rule
	option src 'lan'
	option dest_port '5060'
	option proto 'udp'
	option to_offset '100'
	option from_offset '0'
	option string ' ims.wind.gr '
	option policy 'voip_only'

config policy 'voip_only'
	option interface 'voip'
```

I dont know whether `option string ' ims.wind.gr '` plays any role but it sure is wrong, because that is of my previous ISP

Also `ip r` is 
```
default via 62.38.0.170 dev pppoe-wan  proto static  metric 5
62.38.0.170 dev pppoe-wan  proto kernel  scope link  src 79.166.178.141
192.168.1.0/24 dev br-lan  proto kernel  scope link  src 192.168.1.254
192.168.168.0/25 dev wl0_1  proto kernel  scope link  src 192.168.168.1
192.168.168.128/25 dev wl1_1  proto kernel  scope link  src 192.168.168.129
239.0.0.0/8 dev br-lan  scope link
```

Ineed there is nothing starting with 10.x..

**Comment by FrancYescO** [comment]
As you are receiving a 403 message probably not, are you sure URI is correct?

btw, your OP infos are fuorviant, you are saying its a 789 but the debug zip is from a DGA4132 with an old GUI version and an old firmware

**Comment by milouk** [comment]
The thing is that you are correct about the routing. It can't resolve `ngn.hol.net` while it should be able. It can only resolve the IP.  As far as i undestand the URI is the phone right?

Im sure i have a 789v2 and the latest stable GUI

<img width="245" alt="Screenshot 2021-06-15 at 23 47 10" src="https://user-images.githubusercontent.com/22796276/122121199-04423080-ce34-11eb-9a72-d7e7b7c201a6.png">

<img width="534" alt="Screenshot 2021-06-15 at 23 46 56" src="https://user-images.githubusercontent.com/22796276/122121293-1d4ae180-ce34-11eb-9bcd-4b9c8e0aa850.png">

**Comment by FrancYescO** [comment]
ignore the DGA thing, my bad.

depends on your ISP, URI sometime is countrycode + phone number

if it cannot resolve ngn.hol.net, its a DNS issue, but probably you don't need the A record but the SRV of this like you posted above

**Comment by FrancYescO** [comment]
check also if you have `user_param_value` in your `/etc/config/mmpbxrvsipnet` and try to remove it than restart telephony

**Comment by milouk** [comment]
The URI according to the successfull call logs is without a country number. However, i see it uses the DNS record instead of the SRV but as you said it might not be important whether i use one or another. 

Comparing the REGISTER call from my 789 and the one from the orginal ISP router i have

ORIGINAL:

```
REGISTER sip:ngn.hol.net SIP/2.0
Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,REGISTER,INFO,PRACK,REFER,SUBSCRIBE,NOTIFY,UPDATE
Call-ID: 2926780948-BDD6-0001
Contact: <sip:xxxxxxx@10.223.100.175:5060;user=phone>
Content-Length: 0
CSeq: 1 REGISTER
Expires: 1800
From: <sip:xxxxxx@ngn.hol.net>;tag=7d-846930886
Max-Forwards: 70
Session-ID: 33796139df7fc5cf2aabe24290970d8c
Supported: replaces,timer,100rel,199
To: <sip:xxxxxxx@ngn.hol.net>
User-Agent: VFH300S / FW 1.0.10.07T3
Via: SIP/2.0/UDP 10.223.100.175:5060;rport;branch=z9hG4bKb84cebfc25a180744094fdfbfec73830
```
and i get

```
SIP/2.0 401 Unauthorized 11030230330
Via: SIP/2.0/UDP 10.223.100.175:5060;received=10.223.100.175;rport=5060;branch=z9hG4bKb84cebfc25a180744094fdfbfec73830
To: <sip:xxxxx@ngn.hol.net>;tag=h7g4Esbg_11ee4866074e205c431efa03ec6
From: <sip:xxxxx@ngn.hol.net>;tag=7d-846930886
Call-ID: 2926780948-BDD6-0001
CSeq: 1 REGISTER
Service-Route: <sip:10.120.25.57:5060;transport=udp;lr>
WWW-Authenticate: Digest realm="ims.mnc005.mcc202.3gppnetwork.org",nonce="C8862E368471BE6000000000ABAA253E",algorithm=MD5,qop="auth"
Content-Length: 0
```

789v2

```
CSeq: 1 REGISTER
Via: SIP/2.0/UDP 10.223.116.204:5060;rport;branch=z9hG4bK-3-ef4-5ea9635a-8289a8
Max-Forwards: 70
X-Serialnumber: CP1908TAG3J
User-Agent: VFH300S / FW 1.0.10.07T3 -- CP1908TAG3J
Expires: 1800
Contact: <sip:xxxxxx@10.223.116.204:5060>;audio;+g.3gpp.icsi-ref="ims.mnc005.mcc202.3gppnetwork.org"
Content-Length: 0
```

and i get 

```
SIP/2.0 403 Forbidden 110200201005001
From: <sip:xxxxx@10.120.25.57>;tag=8630d0-adf74cc-13c4-EDC2F2-29120d15-3c078f28-ef3
To: <sip:xxxxxx@10.120.25.57>;tag=h7g4Esbg_9e0f24e00508005c4d4919039bf
Call-ID: 85e860-adf74cc-13c4-EDC2F2-41403054-15bfdcea-ef2
CSeq: 1 REGISTER
Via: SIP/2.0/UDP 10.223.116.204:5060;received=10.223.116.204;rport=5060;branch=z9hG4bK-3-ef4-5ea9635a-8289a8
<sip:10.120.25.57:5060;transport=udp;lr>
Content-Length: 0
```

PS i removed `user_param_value` but nothing happened. Most probably this was needed as in the original request there is `Contact: <sip:xxxxxxx@10.223.100.175:5060;user=phone>`

**Comment by FrancYescO** [comment]
you are registering on different SIP servers, your original modem is registering on 10.223.100.175 instead the 789vac on 10.120.25.57 that idk where it came from..

**Comment by milouk** [comment]
I think `10.223.100.175` was my Original Routers Source IP from which the call originated. (the equivalent for 789vac is `10.223.116.204`. 

On the other hand `10.120.25.57` is the SRV equivalent of ngn.hol.net which originated from the `sipctrl.log` file I got from the original router 

```
[sip show line]
<Line 0 Info>
  enable=1
  user=xxxxx@ngn.hol.net
  pw=xxxxxx
  telno=xxxxxx
  display_name=Account1
  reg_state=2
  (0=NotReg, 1=Registering, 2=RegOK, 3=UnReging, 4=RegFail, 5=TryNext, 6=UnregOK)
  pre_reg_ok=1
  sipreg_idx=0
  send_reg=1
  single_use=0
  busy_reject=0
  telno_hide=0
  local_port=5060 
  tx_port_type=1 (1=UDP, 2=TCP, 4=TLS)
  nProfile=1 nProviderId=1
  CF Mode 0 (1=CF_NA, 2=CF_BUSY, 4=CF_ALL, 16=CF_NL)
  CFU_number: 
  CFB_number: 
  CFNA_number: 
  fallback_primary_now=0, fallback_pending=0
DNS SRV Info:
  enable=1, normal_dns=0 no=2 cur=0 cur_regok=0 failover_in_fallback=0
slist[0] priority=10, weight=50 ttl=900, primary_proxy=1 target=10.120.25.57:5060
slist[1] priority=20, weight=50 ttl=900, primary_proxy=0 target=10.120.65.9:5060
  dtmf_relay=0 (0:inband, 1:rfc2833, 2:SIP INFO, 3:AUTO)
```

**Comment by milouk** [comment]
Compared to the original request I see i am missing these headers:

`Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,REGISTER,INFO,PRACK,REFER,SUBSCRIBE,NOTIFY,UPDATE`
and

`Contact: <sip:xxxxxxx@10.223.100.175:5060;user=phone>``

**Comment by FrancYescO** [comment]
try changing the `re_registration_mode` option for `ims` to `standard` or viceversa

unfortunately the mmpbxrvsipnet is undocumented so you just need to do some trial and error..

there is also the possibility that your ISP does not accept the registration if the modem is not connected to the ACS server

**Comment by milouk** [comment]
If being connected to the ACS server is the thing then im outta luck since i dont have the tr069 credentials. But some other guys managed to connect with after market routers (fritz!box and vigor) so i guess ACS is not mandatory

**Comment by FrancYescO** [comment]
did you checked the if something changed in the registration header?

**Comment by milouk** [comment]
The registration header remained the same.

Almost everyone has managed to connect with a fritz!box with just the basic configuration. Would asterisk have more chances to work?

**Comment by milouk** [comment]
By the way the whole SIP config taken from the original router is as follows :

```
[sip]
sig_port=5060
rtp_port=10000
rtp_port_max=10020
sig_tos=184
voice_tos=184
qos_enable=1
session_time_enable=1
session_time=1800
session_time_min=90
dtmf_event_payload=0
crypto=1
mwi_enable=0
mwi_period=3600
digit_map=1xxxxx|[26789]xxxxxxxxx|4[0-2]xxxxxxxx|54xxx|50xxxxxxxx|00xxxxxxxxxxx.T|807xxxx|*xx*.T|*xx*x.#|*#xx#|#xx#|#xx*x.#|*xx*x.*x.#|*xx*x.T|*xx#|**xx
reg_T1=32
reg_T2=100
stun_enable=0
stun_addr=
base_time=30
o_base_time=90
max_time=1800
srtp=0
only_trusted_ca=0
prefer_crypto=AES_CM_128_HMAC_SHA1_80
reg_mode=0 (0=fallback, 1=secure, 2=insecure)
naptr_enable=0
enable_100rel=1
use_white_list=0
clip_source=0
option_enable=0
option_time=250
emergency=100|166|199|112
nat_short_num=
ims_call_feature_enable=0
internal_enable=0
codec_perport=0
ipv6_support=0
codec_perport=0
gain_perport=0
bEcPerport=0
bRtcpPerport=1
bFaxPerport=0
bJBPerport=1

[sipreg-1]
sip_reg_enable=1
sip_provider_id=1
proxy=ngn.hol.net
proxy_port=5060
sec_proxy=
sec_proxy_port=5060
reg_proxy=ngn.hol.net
reg_proxy_port=5060
user_agent=
sec_user_agent=
reg_domain=ngn.hol.net
ob_enable=0
obproxy=
obproxy_port=0
sec_obproxy=
sec_obproxy_port=5060
reg_expire=1800
reg_period=0
dnssrv_enable=1
keep_alive_enable=0
keep_alive_timeout=0
tx_port_type=1

[sip-line1]
enable=1
user=xxxxxx@ngn.hol.net
pw=xxxxxxx
telno=xxxxxxx
display_name=Account1
cf_number=
sipreg_idx=0
single_use=0
busy_reject=0
telno_hide=0
send_reg=1
local_port=5060
txptype=1
sipprovider_id=1
sipprofile_id=1
sipline_id=1
Guiline_idx=0
sipabsoluteline_id=101
nRegisterStatus=2
nRegisterResponseCode=200
nCallStatus=0
nEmergencyCall=0
dtmf_relay=0
```

If that helps somehow

**Comment by milouk** [comment]
Ok so I managed to fix it. The clue here was to set `10.120.25.57` as primary proxy and `ngn.hol.net` as primary registrar and it registered successfully. Thanks a lot for your help
