### ISSUE TITLE
TG789vac v2 Vant-6. PPP Connecting Issue. No internet on new GUI

### ISSUE THREAD

**Issue by axel9546** [Ansuel/tch-nginx-gui#1092]
HW: TG789vac v2 Vant-6
GUI Version: 9.6.78-6868047d
Debug: 
[DebugHelper2021-06-30-0000.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/6736774/DebugHelper2021-06-30-0000.tar.gz)

Photos: 
![Screenshot_20210630-000529](https://user-images.githubusercontent.com/32848389/123873564-f2ce4d80-d936-11eb-9e72-405a9392e367.png)

Everything seems to be fine but I can't get internet. Before changing GUI it seemed to work fine, but always with the problem of disconnections.

I have tried many times to change TIM Parameters with no luck (on this GUI).
Whats the problem?
Thanks

**Comment by FrancYescO** [comment]
configuration issue and not a GUI issue.
probably you haven't set VLAN ID in broadband modal.

**Comment by axel9546** [comment]
Ho settato tutto come riporta tim nei parametri di configurazione. Intendi il 835?

**Comment by FrancYescO** [comment]
si

**Comment by axel9546** [comment]
> 
> 
> si
Questa è la GUI di MST/UNO che come vedi funziona (anche internet funziona).
Quando pero vado a metttere l'altra GUI, e vado a rimettere gli stessi parametri, non funziona la PPP. Dice sempre "in connessione"
![Cattura](https://user-images.githubusercontent.com/32848389/123908839-6c3a6000-d978-11eb-888e-d7ff07aa003d.PNG)

**Comment by FrancYescO** [comment]
Ricapitola tutti i valori che cambi, nell'ordine in cui lo fai.

Prova a cambiare il tipo di connessione in DHCP e poi reimposti PPP

**Comment by axel9546** [comment]
> Ricapitola tutti i valori che cambi, nell'ordine in cui lo fai.
> 
> Prova a cambiare il tipo di connessione in DHCP e poi reimposti PPP

Lo faccio tramite configurazione guidata in alto a destra della GUI

Cmq

In banda larga
Stato rilevazione WAN su off
modalità vdsl
Uso VLAN 835

In Accesso internet
PPPoE routed

Connessione PPP
IPV6  off

utente/pass timadsl/timadsl

Trova automaticamente DNS ON

**Comment by FrancYescO** [comment]
non usare la confiugurazione guidata

**Comment by axel9546** [comment]
> non usare la confiugurazione guidata

Sono andato a reinserilri a mano, ma sempre lo stesso problema, torno alla GUI Stock, e funziona, aggiorno alla GUI moddata, ma non si connette, ricontrollo i parametri, sono gli stessi, ma non si connette

**Comment by FrancYescO** [comment]
Posta il file /etc/config/network

**Comment by axel9546** [comment]
> Posta il file /etc/config/network

[network.zip](https://github.com/Ansuel/tch-nginx-gui/files/6742359/network.zip)

**Comment by FrancYescO** [comment]
il problema è che lo hai configurato sul firmware MST e non direttamente su GUI, sposta la riga `option ifname 'ptm0'` dal blocco `vlan_wan` a `wanptm0`

**Comment by axel9546** [comment]
>il problema è che lo hai configurato sul firmware MST e non direttamente su GUI
Come si configurava su GUI?

**Comment by FrancYescO** [comment]
resetta reinstalla la GUI e configura direttamente la connessione a internet dopo averla installata

**Comment by axel9546** [comment]
> resetta reinstalla la GUI e configura direttamente la connessione a internet dopo averla installata

Installo la GUI 9.6.79. al comando /tmp$ /etc/init.d/rootdevice force ho questo output:
```
Installing openssl-util (1.0.2g-1) to root...
Configuring openssl-util.
Root Script: Detected low flash space device...
```
è normale?

**Comment by axel9546** [comment]
1) Ho modificato una impostazione nel dhcp. (Spostato IP DNS).

2) Ho rimesso come stava prima.(Copiato e Reincollato lo stesso IP DNS di prima).

3) dà di nuovo "ppp in connessione".

 Perche? Ho rimesso come stava prima.

**Comment by FrancYescO** [comment]
Che significa "Spostato IP DNS", cioè funzionava ma appena hai modificato le impostazioni LAN è tornato a non funzionare?
