### ISSUE TITLE
Possibilità di inserire un doppio DNS

### ISSUE THREAD

**Issue by eliazarx** [Ansuel/tch-nginx-gui#1093]
Buongiorno! Innanzitutto grazie per l'ottimo lavoro!

Volevo chiederVi se c'era la possibilità di poter abilitare un doppio DNS: uno per internet ed un secondo per il VOIP.

Cordiali saluti.

**Comment by FrancYescO** [comment]
Da gui no, configurando manualmente una seconda interfaccia nel file config network si, ma piuttosto usa una soluzione del genre https://github.com/Ansuel/tch-nginx-gui/issues/353#issuecomment-575753520
