### ISSUE TITLE
Can’t change lan ip because of spf ip

### ISSUE THREAD

**Issue by venvsia** [Ansuel/tch-nginx-gui#1094]
I would like to use my 4131 as dumb ap but i can’t change my lan ip (right now both ap and router have same 192.168.1.254 ip)because it asks for spf ip and i don’t have it and i don’t know how to turn it off or set.

**Comment by FrancYescO** [comment]
just input in a random one in another private subnet

**Comment by venvsia** [comment]
> just input in a random one in another private subnet

can you suggest me one? I tried many but any of them worked. Thank you for your reply.

**Comment by FrancYescO** [comment]
192.168.123.123

**Comment by venvsia** [comment]
> 192.168.123.123

thank you, i’ll try it as soon as i reach home and let you know. Have a good we (:

**Comment by venvsia** [comment]
> 192.168.123.123

Hi FrancYescO, i did what you suggested and now i'm able to connect.
Problem is that the acces point itself have no internet access. I attached a [screenshot](https://snipboard.io/CBX0od.jpg) of my actual config.


Am I missing something or it's supposed to work like that?

**Comment by FrancYescO** [comment]
you are still mixing same subnet on different interfaces.

probably what you want to achieve can be done putting an ip on another subnet in local lan (actually is 192.168.1.250) and than bridge and DHCP ON wan after selecting ETH mode in broadband modal (i suppose is already in this way, but is conflcting with LAN address.)
