### ISSUE TITLE
[DGA4132] openssl is missing after clean install 2.2.1

### ISSUE THREAD

**Issue by Blackyfff** [Ansuel/tch-nginx-gui#1095]
Steps to reproduce:

Clean install AGTHP_2.2.1 in a bank.
Switch bank and manually root the previosly installed 2.2.1 in the other bank.
Switch bank again and install GUI (9.6.78). 

Note: I have OBP check and bank1-erasing deactivated before 'rootdevice force', but I don't think it has something to do with this issue. The device has no internet connection.

Many things (e.g. curl) are broken.

`openssl` is not available in cli (I haven't checked if it got broken during GUI install or if it is missing in the clean firmware).

Fix:

after GUI install do manually `opkg install` the following packages:

libopenssl_1.0.2t-1_arm_cortex-a9_neon.ipk
openssl-util_1.0.2t-1_arm_cortex-a9_neon.ipk

Maybe that is also the cause for #1086

**Comment by FrancYescO** [comment]
it will be not installed if during install there is no internet connection, in fact opening the modgui modal you should see a warn that ask you to install specific apps.

**Comment by Blackyfff** [comment]
Thank you for the answer.
I've never seen that warning, but because the GUI Update doesn't fit my needs I didn't use it very often, so I didn't know about that.
It would be great to see that warning using `rootdevice force` in cli, because this is the recommended installation method and I think for new users it is not intentional to have a somewhat broken installation, if they follow the instructions in the Readme for the cause they have no internet connection. Can you can state that clear there, please?

If that is intended behavior please close this issue.

**Comment by FrancYescO** [comment]
if you folllow the readme it is just asking for a WAN connection active, offline installation it's a fallback procedure, but yes probably a line of warn during the install it's a good thing to have
