### ISSUE TITLE
GUI dev 9.6.81 - Strings untranslated

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#1100]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4132
GUI Version: 9.6.8.1

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:

Description of problem, HOW TO REPRODUCE, Media/Photos:

@FrancYescO 

Check screenshots for explanation
![Ansuel-GUI-01](https://user-images.githubusercontent.com/1262554/128051542-4493e92b-7e0a-494c-9267-52d38f4579a5.jpg)

![Ansuel-GUI-02](https://user-images.githubusercontent.com/1262554/128051543-4aa726a3-4dde-49cc-b6c8-65653caf7815.jpg)

![Ansuel-GUI-03](https://user-images.githubusercontent.com/1262554/128051545-920083f5-165b-42c5-8a9e-a666eaae6306.jpg)

![Ansuel-GUI-04](https://user-images.githubusercontent.com/1262554/128051547-bfc9fd30-19b4-4b2a-8d01-db186e570dda.jpg)

![Ansuel-GUI-05](https://user-images.githubusercontent.com/1262554/128051548-8ca0994d-20e9-4488-a510-4d79a35a2541.jpg)

![Ansuel-GUI-06](https://user-images.githubusercontent.com/1262554/128051549-223b1873-06a7-490b-9166-f701d0f261fe.jpg)

![Ansuel-GUI-07](https://user-images.githubusercontent.com/1262554/128051552-161036db-6308-487d-853b-adcaa1c996bf.jpg)

![Ansuel-GUI-08](https://user-images.githubusercontent.com/1262554/128051556-59cdbaf9-0215-4562-992c-b4a657559192.jpg)

![Ansuel-GUI-09](https://user-images.githubusercontent.com/1262554/128051558-7fbdc6f4-db62-402c-8f7f-4fe261d25c7f.jpg)

![Ansuel-GUI-10](https://user-images.githubusercontent.com/1262554/128051559-63c0bc04-dfab-4c17-ba63-e9837a507c77.jpg)

**Comment by FrancYescO** [comment]
Force radio down e short interval, già discusso
Flow Cache, rx e tx bytes, non ci vedo traduzione
Connesso/Disconnesso un po fuorviante ma non mi sembra un grosso problema e almeno non variamo la modale
NoPresent e NoSignal son regression che ci tireremo sempre dietro perchè non appartengono alla GUI web...

**Comment by bovirus** [comment]
@FrancYescO 

Ribadisco il mio parere: non condivido il fatto di non tradurre ciò che è perfettamente traducibile e non è un nome proprio.

"Force radio down" -> "Forza radio OFF".
"Flow cache" -> "Cache flusso"
"tx bytes" -> "Byte TX"
"rx bytes" - > "Byte RX"

Le traduzioni ci sono. Però bisogno volerle applicare.

Grazie.

**Comment by FrancYescO** [comment]
i primi due sono nomi, e la traduzione letterale ne porta solo confusione.
le altre non vedo come possano costituire una traduzione, oltre all'errore del cambio dal plurale al singolare, ma le darò per buone

**Comment by bovirus** [comment]
@FrancYescO 

I primi due sono nomi di funzione (e non nomi propri) e quindi sono traducibili.

Mi spiace ma se non vedi una cosa così basilare (tx/rx bytes non è italiano..) non so come aiutarti.
Nè mi risulta che in italiano la parola "Bytes" si traduca con la s finale.

Secondo me avere la traduzione con pezzi in inglese (eccetto se sono nomi propri o sono legati a funzioni esterne e quindi non traducibili) da l'idea di un lavoro fatto a metà.
