### ISSUE TITLE
GUI dev 9.6.81 - Error to disable WPS on 2.4 Ghz with separate Wifi SSID

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#1101]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4132
GUI Version: 9.6.81

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:

Description of problem, HOW TO REPRODUCE, Media/Photos:

With separet Wifi SSId , trying to disable teh WPS button I got this error.Dsia

![Ansuel-GUI-error-WPS](https://user-images.githubusercontent.com/1262554/128051773-e91217e1-0acd-409e-b565-eb8f1200e485.jpg)

**Comment by FrancYescO** [comment]
duplicate https://github.com/Ansuel/tch-nginx-gui/issues/1097
