### ISSUE TITLE
Downgrade/Upgrade - Aggiornamento firmware fallito. (Codice errore: 16)

### ISSUE THREAD

**Issue by filippopetri** [Ansuel/tch-nginx-gui#1106]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4132 / AGTHP_2.3.1
GUI Version: 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: [DebugHelper2021-08-27-1052.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/7065562/DebugHelper2021-08-27-1052.tar.gz)

Description of problem, HOW TO REPRODUCE, Media/Photos: Tentativo di downgrade -> Aggiornamento firmware fallito. (Codice errore: 16)

![image](https://user-images.githubusercontent.com/29519115/131100591-8856c462-bce8-483c-99ab-a053143b63b0.png)

**Comment by filippopetri** [comment]
Update: l'errore si verifica anche tentando l'aggiornamento alla AGTHP_2.3.2, il problema non è limitato solamente al downgrade.

**Comment by FrancYescO** [comment]
Il problema è di tutti i firmware 19.x, la GUI ha il cambio firmware non funzionante il fulcro della questione è questa funzione dove technicolor a quanto pare ha rotto la logica che permetteva l'upgrade sui device single bank e che noi sfruttavamo per upgradare sullo stesso bank
https://github.com/FrancYescO/tch_firmware_extracted/blob/AGTEF_2.3.1_CLOSED/lib/upgrade/platform.sh#L183

in breve, si è un problema della GUI da risolvere.
