### ISSUE TITLE
Wifi TX power

### ISSUE THREAD

**Issue by ErikPelli** [Ansuel/tch-nginx-gui#1107]
I have a TIM Hub (DGA4132) whit the GUI in this repository.
In the GUI there is a section where you can modify the transmission power of the AP (from -6 dBm to +6 dBm).
I can't find an indication of the actual transmission power so I don't understand what is the base power (where you add or remove dBm).
I use another AP with OpenWrt and I can set all the powers from 0dBm to 20dBm (100mW, IT country) and from 0 to 23dBm (200mW, US country), which is more easy to understand.
How can I do using tch nginx gui to know the actual transmission power (or how I can calculate it from the base power)?

**Comment by diekmanu** [comment]
I hope someone can answer this. In theory this could mean that the transmission power could exceed 20dBm/100mW (20dBm +6dBm?). So the router (wifi) operates outside the regulatory requirements - at least in the EU. 
Chipset for 2.4GHz part seems to be the Broadcom BCM43217.

**Comment by FrancYescO** [comment]
for what i know there we have no info about this, is just a part of wifi config that technicolor put in place and we allowed to edit.

**Comment by ErikPelli** [comment]
> for what i know there we have no info about this, is just a part of wifi config that technicolor put in place and we allowed to edit.

Oh ok, in fact if I try to change it, there is no visible change.
Is this repository still maintained? There hasn't been a new commit for 1 month.

**Comment by diekmanu** [comment]
When I change this to +6dBm the Wi-Fi signal is definitely stronger. Around -65dBm with the default setting in my environment. -58dBm when the highest transmission power is set.
