### ISSUE TITLE
[Help request / feature request] Setting up full bridge mode

### ISSUE THREAD

**Issue by Nesousx** [Ansuel/tch-nginx-gui#1114]
Hi,

First, this is more a "help request" than an issue. Feel free to remove this if I am out of topic.

However, I'd very grateful for some help in setting up a full bridge mode and maybe add a GUI option so that anyone can easily use it.

I have been reading, several times,  [this topic](https://github.com/Ansuel/tch-nginx-gui/issues/853) where @LuKePicci explains in details how to set up the full bridge mode for two openWRT devices. Unfortunately, I can't figure out how to adapt it for myself.

I have an actual opnsense router which manages various things for me : VLANs, firewall, DHCP, etc. I'd like to keep it, and use the DGA 4130 / 4132 as a simple "dumb" modem.

Could anyone help me do that please? Or better, could this become a GUI "button" for anyone to use?

Many thanks in advance, I'll be happy to provide any config asked.

NB : my current ISP uses pppoe DHCP over VLAN 835 (Orange VDSL France), and I have to send MAC + user_id (no password) via DHCP options, in order to authenticate.

**Comment by FrancYescO** [comment]
Basically the way to set a full bridge is:
- in broadband modal set you layer 1 connection (in you case VDSL and VLAN 835)
- go in internet card and select the bridge mode
