### ISSUE TITLE
Missing PPPOE packets with sfp connected to router

### ISSUE THREAD

**Issue by johol** [Ansuel/tch-nginx-gui#1118]
Hello,
I need some help. I'm using a DGA4132 FW AGTHP_2.0.1 Ansuel GUI 9.6.90 in bridge mode.
Everything is working fine when I connect one of the ethernet ports eth0-eth3 to the router. With tcpdump I see
PPPOE packets flowing from eth0 to ptm0.
But I would like to use the sfp port. With eth4 connected to the router with fiber, everyting is working  (ping, http, ssh)
I see PPPOE packets on eth4 but not on ptm0. Seems, that the bridge is not working with eth4.

cat network

config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'none'
        option default_ps '0'

config interface 'wan'
        option auto '1'
        option demand '0'
        option macaddr '10:13:31:B4:40:xx'
        option ipv6 '0'
        option ifname 'ptm0'
        option proto 'bridge'
        option rpfilter '0'
        option enabled '1'
        option keepalive_adaptive '0'

config config 'config'
        option wan_mode 'bridge'

config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.201.121'
        option gateway '192.168.201.1'
        option netmask '255.255.255.0'
        option ip6assign '64'
        option force_link '0'
        option ipv6 '0'
        option rpfilter '0'
        option ifname 'eth0 eth1 eth2 eth3 eth4 ptm0.7'

config switch 'bcmsw'
        option reset '1'
        option enable_vlan '0'
        option qosimppauseenable '0'
        option jumbo '0'

cat ethernet

config port 'eth0'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth1'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth2'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth3'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth4'
        option enable '1'
        option speed 'auto'
        option duplex 'full'
        option wan '1'

config port 'eth5'
        option enable '0'
        option speed 'auto'
        option duplex 'full'

config mapping
        option port 'eth5'
        option wlan_remote '1'

config globals 'globals'
        option eth4lanwanmode '1'

Please let me know, if there is a mistake in the config

Cheers,
Joerg

**Comment by FrancYescO** [comment]
maybe you'll find something useful in this discussion https://www.ilpuntotecnico.com/forum/index.php/topic,80163.0.html

closing as is not GUI specific issue
