### ISSUE TITLE
Gui dev upgrade

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#112]
Come mai se sono nel canale dev e trova un aggiornamento più recente sul canale stable non installa quello come succedeva con le precedenti versioni?

**Comment by Ansuel** [comment]
su che versione sei ? comunque la versione 8.7.3 non l'ho ancora messa

**Comment by nclmrc** [comment]
Con la 8.7.2. Ma dalla 8.6.59 non mi si aggiornava alla stabile.

>

**Comment by nclmrc** [comment]
Hai messo già la 8.7.3?
Esce un errore.
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 2271dd96378e042673258bb5aa85e4ff
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: 66f1cde9296521eb6e0cb5d43116fe44
Upgrade Script: Stable version found: 872
Upgrade Script: Dev version found: 873
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
'bin/ash: can't open '/etc/rc.common
Upgrade Script: Upgrade Done

**Comment by nclmrc** [comment]
Se la 8.7.3 non l'hai messa allora funziona perché mi ha messo la 8.7.2

**Comment by Ansuel** [comment]
prova ora

**Comment by nclmrc** [comment]
Ha funzionato. Devo verificare se trova una versione più recente sul ramo stabile,  passa sulla stabile.

**Comment by Ansuel** [comment]
Domani credo che fixero un altro paio di bug e metterò in stabile.

Il Dom 26 Ago 2018, 23:45 Niccolò Marchi <notifications@github.com> ha
scritto:
