### ISSUE TITLE
DGA4132 port forwarding 5060

### ISSUE THREAD

**Issue by shopy95** [Ansuel/tch-nginx-gui#1120]
I updated the modem to the Answel version but I can not open the port 5060 because occupied by another application. Why?

**Comment by FrancYescO** [comment]
> because occupied by another application

...disable telephony/mmpbxd

**Comment by shopy95** [comment]
But is this a root command?

**Comment by shopy95** [comment]
How it should be written?

**Comment by FrancYescO** [comment]
is not a commend is just what you need to do, maybe in /etc/config/mmpbxd or /etc/config/firewall you will find something
