### ISSUE TITLE
Won’t Update to 9.06.92

### ISSUE THREAD

**Issue by realindiahotel** [Ansuel/tch-nginx-gui#1123]
Hi,
it says 9.06.92 is available as an update, however when I run the updater it reports that 9.06.91 is the latest and so it only updates to 9.06.91 and still says there is an update available 

![20C777E3-C8A1-43A4-A271-95522ED2E388](https://user-images.githubusercontent.com/2297007/150780727-494de1ba-b17c-4460-90a3-9a0f3cba7e04.jpeg)

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/commit/e602dd867e951e153ab66018c384aa9784b676ce
