### ISSUE TITLE
Traffic monitor

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#113]
Ma è una scelta voluta che il graffico alle 2 riparta da sinistra? 
![screenshot_20180827-072715_chrome](https://user-images.githubusercontent.com/38593316/44642147-32c49780-a9cb-11e8-93bf-8ee6b7fe1cf2.jpg)
 Più che altro a volte vengono delle righe orizzontali per coprire i buchi temporali. Mettendo il grafico da sinistra verso destra si eviterebbero.

**Comment by nclmrc** [comment]
Un altro piccolo bug per la Wi-Fi 2.4
![20180829_000340](https://user-images.githubusercontent.com/38593316/44753635-07eb5800-ab1f-11e8-8c3c-c28951290e27.jpg)

**Comment by nclmrc** [comment]
![screenshot_20180830-063949_chrome](https://user-images.githubusercontent.com/38593316/44829973-b1b20e00-ac1f-11e8-9d0c-db66301e0be2.jpg)

**Comment by Ansuel** [comment]
passami di nuovo la cartella trafficmon

**Comment by nclmrc** [comment]
[trafficmon.zip](https://github.com/Ansuel/tch-nginx-gui/files/2336160/trafficmon.zip)

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/44908570-3aae6f80-ad1c-11e8-8211-12a6701cfa15.png)
[trafficmon.zip](https://github.com/Ansuel/tch-nginx-gui/files/2339765/trafficmon.zip)

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/45153052-054dca00-b1d3-11e8-9d1a-a6188189f21f.png)
![immagine](https://user-images.githubusercontent.com/38593316/45153072-11398c00-b1d3-11e8-8de8-9dbd63cebafc.png)
![immagine](https://user-images.githubusercontent.com/38593316/45153088-1a2a5d80-b1d3-11e8-87ac-a90974717f8b.png)

**Comment by nclmrc** [comment]
Sempre qualche problema sulla wifi 2.4

**Comment by nclmrc** [comment]
puoi controllare per favore?

garzie
