### ISSUE TITLE
Is there a Compatibility list or Wiki?

### ISSUE THREAD

**Issue by protonbeam** [Ansuel/tch-nginx-gui#1131]
Is there a Compatibility list or Wiki as I think it maybe helpful as It looks like I'm not the only 1 it's gone wrong for 
https://forums.whirlpool.net.au/archive/9xv6j74j maybe we need a don't install tch-nginx-gui on this device list especially it there isn't a widely available rbi file.

**Comment by FrancYescO** [comment]
Tested devices is the first thing that is wrote in the readme, unfortunately there is no way to know if this will work on a device until it get installed, if any bug popup we can fix it, but we should at least have logs of whats happening.
