### ISSUE TITLE
unable to install luci , appears arm7 is not supported? 

### ISSUE THREAD

**Issue by sophtron** [Ansuel/tch-nginx-gui#1133]
Device Model/Firmware: Technicolor DWA0122BLN.  
Software Version 19.4.0381-4961004-20200907123835-RA   (19.4 Damson)
GUI Version: 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:
[DebugHelper2022-03-13-2327.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/8239602/DebugHelper2022-03-13-2327.tar.gz)

Description of problem, HOW TO REPRODUCE, Media/Photos:
`Unknown app install script for 19.4 armv7l` returned while trying to install luci app  through extensions card,

**Comment by GiuseppeP96** [comment]
Anyone solved?

**Comment by FrancYescO** [comment]
should be already solved installing dev version

**Comment by GiuseppeP96** [comment]
> should be already solved installing dev version

Stilo having : "Unknown app install script for 19.4 armv7l"
Versione software
19.4 Damson
Versione GUI
9.6.92-29c5b4ed

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/1166
