### ISSUE TITLE
Issue with telstra smart modem 2

### ISSUE THREAD

**Issue by rickasheye** [Ansuel/tch-nginx-gui#1136]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: Telstra Smart Modem 2 (Technicolor version) Egyptian Blue (20.3.c)
GUI Version: ??

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:

Description of problem, HOW TO REPRODUCE, Media/Photos:
install the product?

i maybe missing something but when i installed it. it says connection refused when connecting to the gui?

**Comment by FrancYescO** [comment]
post screenshots, debug zip, and GUI version installed, not enougth infos to help you.

**Comment by rickasheye** [comment]
ahh sorry man i reverted it back to stock i might just sit on stock for a while. in the process of getting the next model. but as i remembered it still worked internet access, ssh access and all but everytime i tried to connect to the control panel it just hit connection refused i think i might've did something wrong when installing it. it was well is running the latest 20.3.c but yeah i think the service to launch the control panel failed to start due to some sort of conflict? anyway afterwards i reverted it an installed a script that did just about what this does without some issues, more orientated for the telstra smart modem 2.
