### ISSUE TITLE
Install latest version of Luci

### ISSUE THREAD

**Issue by antomanc** [Ansuel/tch-nginx-gui#1138]
through the button in the gui I have installed Luci but it is version 15, is it possible to install version 17?

**Comment by FrancYescO** [comment]
luci packages needs to be, patched, recompiled and uploaded to some repository, the scope of the GUI is to just issue a script to install these.

Unfortunately there are no clear information around on what patches were done to have the actual packages working, so it's up to you, if you want to retry to patch the v17 of the packages
