### ISSUE TITLE
Support Request: Setting LAN Interface Mode

### ISSUE THREAD

**Issue by DeadClown49** [Ansuel/tch-nginx-gui#1144]
Device Model/Firmware: MediaAccess TG789vac v2 / VANT-6
GUI Version: 9.6.65-89342d7b

Description of problem, Media/Photos:
Hi, I'm aware this probably isn't the right place/way to ask but I need assistance setting the ethernet interface mode manually. Currently, it is set to 1000BASE-T on my NVIDIA Shield (Ethernet 2) and 100BASE-T on my laptop (Ethernet 3). However, I wish for the laptop to be 
1000BASE-T and the Shield to be 100BASE-T (from my understanding multiple devices cannot be 1000BASE-T).

I have confirmed the cables being utilised isn't the issue and the devices are capable of these speeds. The laptop was able to utilise 1000BASE-T however once the Shield was connected to the network it gave the shield priority.

I have tried:
 - Setting priority in Devices List
 - Adding labels to devices in Devices List
 - Adding the laptop to the ethernet after the shield
 - Connecting to different ethernet ports
 - Switching ethernet ports and cables between the devices
 
Any assistance is appreciated.

From stats page:
LAN 2 - Shield
LAN 3 - Laptop (This device I wish to be 1000BASE-T)
![image](https://user-images.githubusercontent.com/43370329/173741215-69b9c75a-50d2-4a07-b997-ebbbf57d50b1.png)

**Comment by kevdagoat** [comment]
Hi mate,

> (from my understanding multiple devices cannot be 1000BASE-T)

All ports on the TG789 are gigabit (1000base-t) capable, you can have multiple gigabit devices connected to the router (using a different ethernet port for each device) and they all will operate at gigabit (1000base-t) speeds.

> I have confirmed the cables being utilised isn't the issue and the devices are capable of these speeds. The laptop was able to utilise 1000BASE-T however once the Shield was connected to the network it gave the shield priority.

Hmmm this one seems like a problematic port or modem, both should link at gigabit speeds with a good cable and each device supporting gigabit speeds, does the laptop actually support gigabit? I say this because the web interface data may have not been updated when you plugged only your laptop in, leading to the illusion that the device is running at gigabit.

Check your cables (i know that you say it is good, but triple check), maybe try switching the shield cable and the laptop cable.

**Comment by DeadClown49** [comment]
Hey mate, cheers for the quick reply.

> All ports on the TG789 are gigabit (1000base-t) capable, you can have multiple gigabit devices connected to the router (using a different ethernet port for each device) and they all will operate at gigabit (1000base-t) speeds.

Hmm interesting, not sure why I thought it was only 1 device able to do 1000base-t

> Hmmm this one seems like a problematic port or modem, both should link at gigabit speeds with a good cable and each device supporting gigabit speeds, does the laptop actually support gigabit? I say this because the web interface data may have not been updated when you plugged only your laptop in, leading to the illusion that the device is running at gigabit.

The laptop indeed support gigabit, speed test on the laptop with the shield connected to the ethernet in rest mode is 98mbps, whereas with the shield physically disconnected, im getting 876mbps on the laptop

> Also best place to ask in future is the WP forums: https://forums.whirlpool.net.au/forum/82

Ah thank you I wasn't aware of this site

> Check your cables (i know that you say it is good, but triple check), maybe try switching the shield cable and the laptop cable.

Checked again with a spare I had laying around, no dice, switched the shield cable and the laptop cable (and also the ports) and the shield was still the only device that has 1000base-t. I don't think I have any other devices currently with support for gigabit ethernet however I can look around or if needsby borrow a mates device to test.

**Comment by FrancYescO** [comment]
its surely a workaround, but you can use the `ethctl` command to force a mode on a port or somehow debug the issue.

**Comment by DeadClown49** [comment]
> its surely a workaround, but you can use the `ethctl` command to force a mode on a port or somehow debug the issue.

Workaround or not it worked, thank you very much (and also thank you @kevdagoat for your assistance) - both devices now running 1000FD and speed testing both devices confirmed that they were running correctly.

**Comment by DeadClown49** [comment]
Quick update (I will re-close it's just to assist anyone who may also have the issue... likely myself in a few months again) - be sure to check it stays, went away on a holiday and turned off the router, have come back and just realised the same issue has occurred so need to repeat the steps again.
