### ISSUE TITLE
Router Crashes from time to time

### ISSUE THREAD

**Issue by xSqne** [Ansuel/tch-nginx-gui#1145]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4131FWB
GUI Version: 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: [DebugHelper2022-06-19-1828.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/8935933/DebugHelper2022-06-19-1828.tar.gz)

Description of problem, HOW TO REPRODUCE, Media/Photos:
My router started crashing since yesterday at random intervals. I'm not sure if this is faulty software or hardware, but it has been working flawlessly for a few months.

**Comment by FrancYescO** [comment]
pretty sure, hardware 
https://www.ilpuntotecnico.com/forum/index.php/topic,80598.msg261190.html#msg261190
