### ISSUE TITLE
GUI not responding . 

### ISSUE THREAD

**Issue by finos2** [Ansuel/tch-nginx-gui#1146]
Device Model/Firmware:TG789vac v2 VANT-6
GUI Version:9.6.65

Debug zip : 
[DebugHelper2022-06-20-1829.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/8942042/DebugHelper2022-06-20-1829.tar.gz)

went to use the CPE after having it at storage for a while , the first time it booted up fine , i powered it down to move it to its final location , on its first bootup the gui was slugish  after a while it gave me 503 erros, _i rebooted it pulling the power_ , the 2nd time it stuck with the `i` led on white , 
on a 3rd reboot , the device opened , i was able to sync a vdsl line , but almost none of the cards were working . 

![image](https://user-images.githubusercontent.com/20401903/174640446-d0fe9844-ddc6-48e6-94d1-74c935a7d6d5.png)
![image](https://user-images.githubusercontent.com/20401903/174640458-c0c404ae-5c82-4efe-aa19-f3d26f2f259e.png)

**Comment by skdubg** [comment]
I recommend updating to the Dev version first.
The green skin usually works very well.

please report back

**Comment by finos2** [comment]
_havent perfomed the update to Dev yet _ (sorry im kinda busy ) 

but the router seems stable ,i got it to boot up fully sync a line etc ... could it be a one off issue

**Comment by finos2** [comment]
Performed `RTFD` and re installed ansuel and now seems stable . 

Thanks
