### ISSUE TITLE
8.7.2 does not show anymore VoIP password 

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#115]
Tiscali 16.3

Also if you go in the Codec tab and than back to global will show

`invalid path Device.Services.VoiceService.{i}.PhyInterface.{i}.`

error alert

is not possible to move the voip password in the "Phone Numbers" tab near each line of sip profile?

https://i.imgur.com/maIaSPu.png

**Comment by Ansuel** [comment]
voip password were present before this update?

**Comment by FrancYescO** [comment]
sure

**Comment by Ansuel** [comment]
strange...

give me output of transformer-cli get uci.mmpbxrvsipnet. (remove sensible data)

**Comment by FrancYescO** [comment]
Unfortunately due to https://github.com/Ansuel/tch-nginx-gui/issues/116

actually i have no ssh access, looking at the code I think is something like that the def of the passwords variables never called

**Comment by FrancYescO** [comment]
```
root@OpenWrt:~# transformer-cli get uci.mmpbxrvsipnet.
uci.mmpbxrvsipnet.mmpbxrvsipnetNumberOfEntries [unsignedInt] = 1
uci.mmpbxrvsipnet.radvisionNumberOfEntries [unsignedInt] = 0
uci.mmpbxrvsipnet.profileNumberOfEntries [unsignedInt] = 2
uci.mmpbxrvsipnet.networkNumberOfEntries [unsignedInt] = 1
uci.mmpbxrvsipnet.mmpbxrvsipnet.@global.trace_level [string] = 4
uci.mmpbxrvsipnet.mmpbxrvsipnet.@global.radvision_trace_level [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.fax_transport [string] =
uci.mmpbxrvsipnet.network.@sip_net.session_expires [string] = 1800
uci.mmpbxrvsipnet.network.@sip_net.no_answer_response [string] = 480
uci.mmpbxrvsipnet.network.@sip_net.dtmf_relay_translation [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.call_waiting_reject_response [string] = 486
uci.mmpbxrvsipnet.network.@sip_net.cac [string] = -1
uci.mmpbxrvsipnet.network.@sip_net.dtmf_relay [string] = auto
uci.mmpbxrvsipnet.network.@sip_net.proxy_selection_policy [string] =
uci.mmpbxrvsipnet.network.@sip_net.rtp_local_port_min [string] =
uci.mmpbxrvsipnet.network.@sip_net.sdp_call_hold_direction [string] =
uci.mmpbxrvsipnet.network.@sip_net.timer_D [string] = 50000
uci.mmpbxrvsipnet.network.@sip_net.secondary_proxy_port [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.timer_J [string] = 32000
uci.mmpbxrvsipnet.network.@sip_net.domain_name [string] = ims.tiscali.net
uci.mmpbxrvsipnet.network.@sip_net.401_407_waiting_time [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.transparent_soc_transmission [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.primary_proxy [string] = srvrm.p.ims.tiscali.sys
uci.mmpbxrvsipnet.network.@sip_net.switch_back_to_primary_proxy_timer [string] =
uci.mmpbxrvsipnet.network.@sip_net.timer_F [string] = 32000
uci.mmpbxrvsipnet.network.@sip_net.min_session_expires [string] = 90
uci.mmpbxrvsipnet.network.@sip_net.transport_type [string] = UDP
uci.mmpbxrvsipnet.network.@sip_net.control_qos_field [string] = dscp
uci.mmpbxrvsipnet.network.@sip_net.early_detect_fax [string] =
uci.mmpbxrvsipnet.network.@sip_net.fail_behaviour [string] = stop
uci.mmpbxrvsipnet.network.@sip_net.control_qos_value [string] = ef
uci.mmpbxrvsipnet.network.@sip_net.realtime_qos_field [string] = dscp
uci.mmpbxrvsipnet.network.@sip_net.escape_star [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.escape_hash [string] = 1
uci.mmpbxrvsipnet.network.@sip_net.min_period_proxy_redundancy [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.realtime_qos_value [string] = ef
uci.mmpbxrvsipnet.network.@sip_net.timer_T4 [string] = 5000
uci.mmpbxrvsipnet.network.@sip_net.reinvite_stop_audio [string] =
uci.mmpbxrvsipnet.network.@sip_net.session_timer [string] = enabled
uci.mmpbxrvsipnet.network.@sip_net.secondary_registrar [string] = ims.tiscali.net
uci.mmpbxrvsipnet.network.@sip_net.realm_check [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.reg_expire [string] = 3600
uci.mmpbxrvsipnet.network.@sip_net.reg_back_off_timeout [string] = 60
uci.mmpbxrvsipnet.network.@sip_net.ingress_media_timeout [string] = 1000
uci.mmpbxrvsipnet.network.@sip_net.timer_B [string] = 32000
uci.mmpbxrvsipnet.network.@sip_net.secondary_proxy [string] =
uci.mmpbxrvsipnet.network.@sip_net.reg_expire_T_before [string] = 1
uci.mmpbxrvsipnet.network.@sip_net.re_registration_mode [string] = ims
uci.mmpbxrvsipnet.network.@sip_net.timer_T1 [string] = 500
uci.mmpbxrvsipnet.network.@sip_net.call_waiting_provisional_response [string] = 182
uci.mmpbxrvsipnet.network.@sip_net.provisional_timer [string] = 180
uci.mmpbxrvsipnet.network.@sip_net.interface [string] = broadif1
uci.mmpbxrvsipnet.network.@sip_net.reliable_provisional_response [string] = supported
uci.mmpbxrvsipnet.network.@sip_net.realm [string] =
uci.mmpbxrvsipnet.network.@sip_net.privacy_handling [string] = apply
uci.mmpbxrvsipnet.network.@sip_net.local_port [string] = 5060
uci.mmpbxrvsipnet.network.@sip_net.uri_clir_format [string] = standard
uci.mmpbxrvsipnet.network.@sip_net.rtp_local_port_max [string] =
uci.mmpbxrvsipnet.network.@sip_net.forking_mode [string] = default
uci.mmpbxrvsipnet.network.@sip_net.primary_registrar_port [string] = 5060
uci.mmpbxrvsipnet.network.@sip_net.user_friendly_name [string] = SIP network
uci.mmpbxrvsipnet.network.@sip_net.secondary_registrar_port [string] =
uci.mmpbxrvsipnet.network.@sip_net.primary_proxy_port [string] = 0
uci.mmpbxrvsipnet.network.@sip_net.rport_in_via [string] = 1
uci.mmpbxrvsipnet.network.@sip_net.primary_registrar [string] = ims.tiscali.net
uci.mmpbxrvsipnet.network.@sip_net.interface6 [string] =
uci.mmpbxrvsipnet.network.@sip_net.timer_T2 [string] = 4000
uci.mmpbxrvsipnet.network.@sip_net.rejection_response [string] = 486
uci.mmpbxrvsipnet.profile.@sip_profile_0.user_name [string] = 00390000000000@ims.tiscali.net
uci.mmpbxrvsipnet.profile.@sip_profile_0.network [string] = sip_net
uci.mmpbxrvsipnet.profile.@sip_profile_0.password [password] = 1800000000000
uci.mmpbxrvsipnet.profile.@sip_profile_0.display_name [string] = 00390000000000
uci.mmpbxrvsipnet.profile.@sip_profile_0.uri [string] = 00390000000000
uci.mmpbxrvsipnet.profile.@sip_profile_0.enabled [string] = 1
uci.mmpbxrvsipnet.profile.@sip_profile_1.user_name [string] = line2
uci.mmpbxrvsipnet.profile.@sip_profile_1.network [string] = sip_net
uci.mmpbxrvsipnet.profile.@sip_profile_1.password [password] = line2
uci.mmpbxrvsipnet.profile.@sip_profile_1.display_name [string] = line2
uci.mmpbxrvsipnet.profile.@sip_profile_1.uri [string] = line2
uci.mmpbxrvsipnet.profile.@sip_profile_1.enabled [string] = 0

```

**Comment by Ansuel** [comment]
can you test latest dev ?

**Comment by FrancYescO** [comment]
8.7.22 cannot open Telephony modal, stuck on "Processing..."
going directly in /modals/mmpbx-global-modal.lp = ERR_EMPTY_RESPONSE

**Comment by Ansuel** [comment]
Give me the log with logread

**Comment by FrancYescO** [comment]
> Thu Aug 30 21:04:04 2018 daemon.err nginx: 2018/08/30 21:04:04 [error] 31634#0: *100 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #7 to 'format' (no value)
> stack traceback:
> coroutine 0:
>         [C]: in function 'format'
>         /usr/lib/lua/web/taint.lua:280: in function 'format'
>         /usr/lib/lua/web/ui_helper.lua:685: in function 'createLabel'
>         [string "/modals/mmpbx-global-modal.lp"]:190: in function 'content'
>         /usr/lib/lua/web/web.lua:249: in function 'process'
>         content_by_lua(ngThu Aug 30 21:04:05 2018 daemon.info dnsmasq-dhcp[31500]: DHCPDISCOVER(br-lan) 255.255.255.255 7c:dd:90:ce:fc:ba
> Thu Aug 30 21:04:05 2018 daemon.info dnsmasq-dhcp[31500]: DHCPOFFER(br-lan) 192.168.1.93 7c:dd:90:ce:fc:ba
> Thu Aug 30 21:04:05 2018 daemon.err nginx: 2018/08/30 21:04:04 [error] 31634#0: *98 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #7 to 'format' (no value)
> stack traceback:
> coroutine 0:
>         [C]: in function 'format'
>         /usr/lib/lua/web/taint.lua:280: in function 'format'
>         /usr/lib/lua/web/ui_helper.lua:685: in function 'createLabel'
>         [string "/modals/mmpbx-global-modal.lp"]:190: in function 'content'
>         /usr/lib/lua/web/web.lua:249: in function 'process'
>         content_by_lua(ngiThu Aug 30 21:04:05 2018 daemon.err nginx: 2018/08/30 21:04:05 [error] 31634#0: *86 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #7 to 'format' (no value)
> stack traceback:
> coroutine 0:
>         [C]: in function 'format'
>         /usr/lib/lua/web/taint.lua:280: in function 'format'
>         /usr/lib/lua/web/ui_helper.lua:685: in function 'createLabel'
>         [string "/modals/mmpbx-global-modal.lp"]:190: in function 'content'
>         /usr/lib/lua/web/web.lua:249: in function 'process'
>         content_by_lua(ngiThu Aug 30 21:04:07 2018 daemon.info dnsmasq-dhcp[31500]: DHCPDISCOVER(br-lan) 255.255.255.255 7c:dd:90:ce:fc:ba
> Thu Aug 30 21:04:07 2018 daemon.info dnsmasq-dhcp[31500]: DHCPOFFER(br-lan) 192.168.1.93 7c:dd:90:ce:fc:ba
> Thu Aug 30 21:04:07 2018 daemon.err nginx: 2018/08/30 21:04:07 [error] 31634#0: *106 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #7 to 'format' (no value)
> stack traceback:
> coroutine 0:
>         [C]: in function 'format'
>         /usr/lib/lua/web/taint.lua:280: in function 'format'
>         /usr/lib/lua/web/ui_helper.lua:685: in function 'createLabel'
>         [string "/modals/mmpbx-global-modal.lp"]:190: in function 'content'
>         /usr/lib/lua/web/web.lua:249: in function 'process'
>

**Comment by Ansuel** [comment]
should be good now

**Comment by FrancYescO** [comment]
working on 8.7.24
