### ISSUE TITLE
NAT helper Fix 

### ISSUE THREAD

**Issue by Alex2610** [Ansuel/tch-nginx-gui#1158]
Come suggerito da [lorenzocanalelc](https://www.ilpuntotecnico.com/forum/index.php?action=profile;u=73330)
allego i file da lui postati, credo vadano inseriti opportunamente e avviata una build:
"Comunque per coloro i quali necessitano la card NAT Helper funzionante su GUI Ansuel con i nuovi firmwares ecco i file modificati funzionanti, il file 092_natalghelper.lp va inserito su /www/cards/ mentre nat-alg-helper-modal.lp va su /www/docroot/modals/

https://www.mediafire.com/file/liik48ljaxs9ne8/Card_NAT_Helper_MOD.zip/file
[Card NAT Helper MOD.zip](https://github.com/Ansuel/tch-nginx-gui/files/10337234/Card.NAT.Helper.MOD.zip)
"

**Comment by FrancYescO** [comment]
duplicate https://github.com/Ansuel/tch-nginx-gui/issues/1147
