### ISSUE TITLE
System Extra "Some parameters failed validation" 

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#116]
"Some parameters failed validation"  when clicking save in the System extra Tab, also enabling SSH From WAN will not work (port 22 still closed remotely)

https://i.imgur.com/4V6fTq5.png

**Comment by Ansuel** [comment]
can you show me the page? any empty box?

**Comment by FrancYescO** [comment]
what page you need? the GUI is just shown correctly, but if i enable SSH WAN, is semply not reachable from another network

and everytime i save in this page shows the error in the screenshot

**Comment by Ansuel** [comment]
system extra

**Comment by FrancYescO** [comment]
![](https://i.imgur.com/sHjLIiz.png)
![](https://i.imgur.com/zjSH96r.png)

**Comment by FrancYescO** [comment]
These firewall rules (default input by Tiscali) were the reason of WAN SSH not working:
```
config rule 'wan_SSH_rule1'
	option src 'wan'
	option proto 'tcp'
	option dest_port '22'
	option enabled '1'
	option name 'Allow-SSH-wan'
	option family 'ipv4'
	option target 'ACCEPT'
	option src_ip '195.130.246.0/24'

config rule 'wan_SSH_rule5'
	option src 'wan'
	option proto 'tcp'
	option dest_port '22'
	option enabled '1'
	option name 'Allow-SSH-wan'
	option family 'ipv4'
	option target 'ACCEPT'
	option src_ip '213.205.40.160/27'
```

**Comment by Ansuel** [comment]
Will add a rule in the root script to remove them ;)

Il Sab 1 Set 2018, 08:35 Francesco M <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
can you retry this?

**Comment by FrancYescO** [comment]
```
Some parameters failed validation
fwversion_override: String cannot be empty.
Some parameters failed validation
telnet_enable: 0 or 1 expected.
```
Now we can easily get to the point 👯‍♂️ 
Some Optional validations needed around 😁
