### ISSUE TITLE
Impossibile installare alcuna GUI

### ISSUE THREAD

**Issue by faddanicolo** [Ansuel/tch-nginx-gui#1160]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4132 / AGTHP_2.3.4
GUI Version: 9.6.93-838e0f26

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: [DebugHelper2023-01-08-1341.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/10368425/DebugHelper2023-01-08-1341.tar.gz)

Description of problem, HOW TO REPRODUCE, Media/Photos:
Stavo configurando la mia installazione di pihole, finchè non sono rimasto a un problema, ovvero il router forza i dispositivi connessi ad utilizzare il server DNS del PPP invece di quello assegnato (da DHCP o manualmente). Così ho provato ad installare la GUI LuCi per provare a disabilitare la protezione Rebind DNS, ed è qui che il problema è sorto. Ogni volta che provo ad installare una GUI, che sia LuCi, Aria2 o Transmission (a quanto pare Telstra funziona) l'installazione si ferma a questo punto: 
[LuCi.txt](https://github.com/Ansuel/tch-nginx-gui/files/10368401/LuCi.txt)
[Aria2.txt](https://github.com/Ansuel/tch-nginx-gui/files/10368405/Aria2.txt)
[Transmission.txt](https://github.com/Ansuel/tch-nginx-gui/files/10368423/Transmission.txt)
Controllando dal visualizzatore eventi tutti e tre gli installer tornano con lo stesso errore: `async exec of '/usr/share/transformer/scripts/wrapper.sh "/usr/share/transformer/scripts/appInstallRemoveUtility.sh install luci "' failed exit code=143`
Un errore simile viene menzionato in questo post #1150, non so se siano del tutto uguali in quanto nel mio caso non arriva all'installazione di libubox.

Edit: Ho provato ad installare diverse versioni della GUI, notando che questo errore si verifica solo dopo la versione 9.6.92, prima della quale esce scritto solamente l'errore `Unknown app install script for 19.4 armv7l`

**Comment by Bellissim0** [comment]
Ciao, da quello che ho dedotto dal trial ed error che ho effettuato anche io, la gui non (o almeno gli script di installazione) non sono updatati per il firmware 2.3.4 (e non so quali precedenti), installando il firmware 2.2.1 l'installazione di luci funziona perfettamente, l'unico problema è che, non so come, il mio DGA4132 si è updatato da solo alla versione 2.3.4 e, nonostante io abbia ancora la gui di ansuel, luci non funziona più, onestamente non mi va di rifare tutta la procedura da capo e di tornare al 2.2.1 per poi improvvisamente vedermi di nuovo il modem aggiornato alla 2.3.4, usavo luci principalmente per il qos quindi se qualcuno di voi sapesse come installare una versione di luci senza passare dalla gui oppure fornire una qualche alternativa all'sqm di luci compatibile col firmware 2.3.4 mi farebbe un enorme favore

**Comment by faddanicolo** [comment]
Io per l'sqm ho seguito questa guida: [](https://www.ilpuntotecnico.com/forum/index.php/topic,85190.0.html), per instllarla ho dovuto fare il downgrade della GUI a causa di alcuni problemi con il download

**Comment by SuperMitic** [comment]
> la gui (o almeno gli script di installazione) non sono updatati per il firmware 2.3.4 (e non so quali precedenti), installando il firmware 2.2.1 l'installazione di luci funziona perfettamente

I am getting the same issue on DGA4132 using both latest Dev 9.6.99 and stable 9.6.65
Sto riscontrando lo stesso problema su DGA4132 usando sia la Dev sia la Stable GUI.
Con 2.2.1 AGTHP (Homeware 18) riesco a installare e utilizzare LUCI
Con i firmware 2.3.x e successivi (compreso il 2.4) (Homeware 19), non riesco a installare LUCI nè con le repo homeware 18 nè con 19. Ottengo questo errore su libubox:
`check_data_file_clashes: Package libubox20191228 wants to install file /lib/libubox.so 	But that file is already provided by package * libubox20170601`

Hai trovato una soluzione?

**Comment by FrancYescO** [comment]
Hai fatto casino nel provare ad installare:
teoricamente, dopo aver disinstallato da gui e dopo aver messo le repo della 18 su un fw 19 dovresti riuscire ad installare luci da gui

**Comment by SuperMitic** [comment]
Sono riuscito a installare LUCI da terminale usando lo script di installazione fornito dalla GUI. Tuttavia da GUI ho provato e riprovato, ma non si installa. Si blocca senza dare nessun errore.

**Comment by SuperMitic** [comment]
Tuttavia mi installa luci git20 dai repo Homeware 18. è possibile installare una versione più recente? Ad esempio la git21 presente nei repo di Homeware 19? Ottengo l'errore postato nei commenti precedenti. C'è qualche modo per risolvere il problema di dipendenza libubox?

**Comment by FrancYescO** [comment]
No, meno che non prendi una versione nuova e la ripatchi come fu fatto all'epoca con i pacchetti che hai scaricato da quella repo

**Comment by faddanicolo** [comment]
Scusate, riprendo il mio argomento principale, quindi sarebbe necessario tornare a homeware 18.3 (AGTHP 2.2.3) per poter far funzionare le GUI custom? Se si, sapete se il WoW funzionasse ancora o bisognerebbe tornare ancora più indietro?

**Comment by FrancYescO** [comment]
La GUI per quanto con qualche limitazione/bug funziona anche sui 19.x

Che io sappia non ci sono problemi con WoW.

**Comment by faddanicolo** [comment]
Attualmente con versione 19.4 e gui 9.6.96 il WoW e le custom GUI non funzionano, prima di aggiornare il fw funzionava perfettamente quindi suppongo sia per quello

**Comment by faddanicolo** [comment]
Sono tornato alla versione 18.3 e adesso sia con gui stabile che dev le custom GUI possono essere installate dal menu senza problemi. Per quanto riguarda il WoW, adesso le configurazioni si salvano ma i pacchetti non arrivano al PC. Stesso identico problema di #279, nonostante adesso il file wol sia giusto continua a non funzionare.

**Comment by faddanicolo** [comment]
Dopo svariati tentativi sono riuscito a trovare il problema... Quando la porta del dispositivo WoW della GUI viene cambiata viene inviato il comando "ip neigh del $dest_ip lladdr ff:ff:ff:ff:ff:ff nud permanent dev $dest_intf", il quale fa passare il dispositivo selezionato da "<$dest_ip> dev <$dest_inf> lladdr ff:ff:ff:ff:ff:ff PERMANENT" a "<$dest_ip> dev <$dest_inf> FAILED" (linee visualizzabili tramite il comando "ip neigh show"). Dopodichè viene inviato il comando "ip neigh add $dest_ip lladdr ff:ff:ff:ff:ff:ff nud permanent dev $dest_intf", il quale ritorna un errore "RTNETLINK answers: File exists" in quanto la linea è già presente.
Per risolvere il problema è bastato cambiare l'ultimo comando in "ip neigh replace $dest_ip lladdr ff:ff:ff:ff:ff:ff nud permanent dev $dest_intf", in quanto ha sia funzione di aggiunta che di rimpiazzo.

**Comment by FrancYescO** [comment]
Hai cambiato il comando … dove?
________________________________

**Comment by faddanicolo** [comment]
Dentro /etc/init.d/wol

**Comment by faddanicolo** [comment]
Vorrei aggiungere che non sono sicuro che questo fix funzioni per fw >= 19.x in quanto in quelle versioni non riuscivo a fare salvare la configurazione tramite gui (come in #1103).
