### ISSUE TITLE
Problema connessione: Not Found

### ISSUE THREAD

**Issue by mattiacolombomc** [Ansuel/tch-nginx-gui#1167]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: DGA4130
GUI Version: 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here: **Unable to do it, the pop-up is avoiding me to do it**
![image](https://github.com/Ansuel/tch-nginx-gui/assets/55593934/2228b366-ff9b-47a0-8075-948d183a858e)

Description of problem, HOW TO REPRODUCE, Media/Photos:
I don't know how to reproduce it, everything worked fine till the power went out 1 hour ago. I also tried to unplug the modem, simulate a crash with `echo c > /proc/sysrq-trigger;`. I don't really know what to do and I'm offline. My ISP (TIM) has confirmed they have no problem on their side.

**Comment by FrancYescO** [comment]
`upogradegui` command from terminal / upgrade to dev versin

**Comment by mattiacolombomc** [comment]
Didn't solve. Had to take the original `/etc/config/network` config from my backup and copy it into place. maybe it could be useful for future reference. 
Also - if I may ask -  why did you choose this versioning system? Seems like the latest `stable` version is not stable at all.
Thanks anyways for your work guys, amazing stuff!

**Comment by FrancYescO** [comment]
simply because dev can have some other broken things, but yeah as the develop status is pretty in stuck the latest dev can be considered stable..
