### ISSUE TITLE
Style Fix - Horizontal scrolling shown when not needed

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#117]
Are these css style really needed ?

https://github.com/Ansuel/tch-nginx-gui/search?q=max-width%3A880px%3Boverflow-x%3Aauto&unscoped_q=max-width%3A880px%3Boverflow-x%3Aauto

they cause glitch in the UI like this: https://i.imgur.com/O06bE3j.png

**Comment by kevdagoat** [comment]
That’s not really a glitch

**Comment by FrancYescO** [comment]
@kevdagoat and what is it? why the horizontal scrollbar is here? is pretty useless :\

**Comment by kevdagoat** [comment]
It’s due to your browsers window size.
