### ISSUE TITLE
TG789vac v2 with Tiscali original firmware: red blinking info button after installing GUI

### ISSUE THREAD

**Issue by apbard** [Ansuel/tch-nginx-gui#1173]
I have a TG789vac v2 with original firmware tiscali version 16.3.7636
I successfully rooted the device following: https://www.ilpuntotecnico.com/forum/index.php/topic,77988.html
Then I wanted to install this gui and executed:
```
curl -k https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/GUI.tar.bz2 --output /tmp/GUI.tar.bz2 && bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force
```
It started printing/logging stuff till:
```
Writing from /dev/mtd3 to /dev/mtd4 ...
/etc/rc.common: line 1: can't create /proc/prozone/bootfail: nonexistent directory
/etc/rc.common: line 1: can't create /proc/prozone/bootcounter: nonexistent directory
/etc/rc.common: line 1: can't create /proc/prozone/bootbank: nonexistent directory
Unlocking bank_1 ...
Erasing bank_1 ...
Rebooting ...
```

then the modem auto-rebooted. Now the modem has the info button blinking red. What has going wrong? How can I recover?

thanks in advance for the help.
@Ansuel @FrancYescO

**Comment by FrancYescO** [comment]
Crossposting
