### ISSUE TITLE
Error when i try install Luci extension

### ISSUE THREAD

**Issue by madfactory** [Ansuel/tch-nginx-gui#1180]
Device Model/Firmware: DGA ( DGA4130 ) / AGTEF_2.4.0_002
GUI Version: 9.6.99
error when i try install Luci from extension card

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 * 	libiwinfo20181126
 * 	libiwinfo-lua
 * 	libiwinfo20181126
 * 	libiwinfo-lua
 * opkg_install_cmd: Cannot install package luci.
mv: can't rename '/www/cgi-bin': No such file or directory
mv: can't rename '/www/luci-static': No such file or directory
mv: can't rename '/www/index.html': No such file or directory
sed: /usr/lib/lua/luci/model/uci.lua: No such file or directory
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
/usr/share/transformer/scripts/appInstallRemoveUtility.sh: line 210: /etc/init.d/uhttpd: not found
of available packages in /var/opkg-lists/chaos_calmer_telephony_macoers
No packages removed.
Installing libuci-lua (2019-09-01-415f9e48-4) to root...
Downloading https://repository.macoers.com/homeware/19/brcm6xxx-tch/VANTW/base/libuci-lua_2019-09-01-415f9e48-4_arm_cortex-a9_neon.ipk
Installing luci (git-21.217.07088-5294ba2-1) to root...
Downloading https://repository.macoers.com/homeware/19/brcm6xxx-tch/VANTW/luci/luci_git-21.217.07088-5294ba2-1_all.ipk
Installing rpcd (2020-05-26-67c8a3fd-1) to root...
Downloading https://repository.macoers.com/homeware/19/brcm6xxx-tch/VANTW/base/rpcd_2020-05-26-67c8a3fd-1_arm_cortex-a9_neon.ipk
Configuring libuci-lua.
Configuring rpcd.

**Comment by FrancYescO** [comment]
duplicate: https://github.com/Ansuel/tch-nginx-gui/issues/1166
basically you need to force install 18.x packages

**Comment by madfactory** [comment]
Collected errors:
 * opkg_download_pkg: Package luci is not available from any configured src.
 * opkg_install_pkg: Failed to download luci. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci.
mv: can't rename '/www/cgi-bin': No such file or directory
mv: can't rename '/www/luci-static': No such file or directory
mv: can't rename '/www/index.html': No such file or directory
sed: /usr/lib/lua/luci/model/uci.lua: No such file or directory
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
/usr/share/transformer/scripts/appInstallRemoveUtility.sh: line 210: /etc/init.d/uhttpd: not found
f available packages in /var/opkg-lists/chaos_calmer_telephony_macoers
Downloading https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/target/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_core_macoers
No packages removed.
Installing libuci-lua (2019-05-17-f199b961-1) to root...
Downloading https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base/libuci-lua_2019-05-17-f199b961-1_arm_cortex-a9_neon.ipk
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Installing luci (git-21.217.07088-5294ba2-1) to root...
Installing rpcd (2018-11-28-3aa81d0d-2) to root...
Downloading https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base/rpcd_2018-11-28-3aa81d0d-2_arm_cortex-a9_neon.ipk
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Configuring libuci-lua.
Configuring rpcd.

**Comment by Pfurr** [comment]
> duplicate: #1166 basically you need to force install 18.x packages

ciao, scusa, ma cosa si dovrebbe fare anche io ho questo errore il mio firmware GUI MediaAccess DGA4131FWB 9.6.65-89342d7b con tch-nginx-gui 9.6.65 [Latest], non mi installa luci in nessun modo dall'interfaccia
