### ISSUE TITLE
Problem on power injection/extraction (poe)

### ISSUE THREAD

**Issue by pepitosbazzegutisbazzeguti** [Ansuel/tch-nginx-gui#1187]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model/Firmware: MediaAccess TG ( Technicolor TG789vac Xtream_IAD ); Software Version: 16.2 Jade (FASTWEB)
GUI Version: 9.6.65-89342d7b

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:

Description of problem, HOW TO REPRODUCE, Media/Photos:
It's not, I think, a Gui problem...
I put the router on a wall, 10 meter away from the power source. I used poe injector/extractor to transmit power on ethernet cable (CAT 6). Power arrives on the router, but it's not working (no link on ehternet cable; no wifi, no leds, excepts for power...). I tried only the ethernet cable without poe energy and it's working; I tried another router with poe injector/extractor and it's working. So the question is: why the fastweb router is not working?

**Comment by FrancYescO** [comment]
pretty sure cuz it require more amps and the injector/cables do too much resistance
