### ISSUE TITLE
Problemi nell' installare LuCI da GUI

### ISSUE THREAD

**Issue by ferrvittorio** [Ansuel/tch-nginx-gui#1191]
Nome prodotto DGA ( DGA4132 )
Versione software 19.4 Damson
Versione GUI 9.6.65-89342d7b

> Unknown app install script for 19.4 armv7l

Sembra essere un problema dei repo di opkg?

> root@modemtim:~# opkg update
> Downloading http://downloads.openwrt.org/snapshots/targets/brcm6xxx-tch/VBNTJ_502L07p1/packages/Packages.gz
> *** Failed to download the package list from http://downloads.openwrt.org/snapshots/targets/brcm6xxx-tch/VBNTJ_502L07p1/packages/Packages.gz
> 
> Collected errors:
>  * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/targets/brcm6xxx-tch/VBNTJ_502L07p1/packages/Packages.gz, wget returned 8.

Please go to Cards >> GUI Settings >> Debug Report and press the Generate button.
Attach the debug file here:
[DebugHelper2024-05-26-0951.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/15446639/DebugHelper2024-05-26-0951.tar.gz)

**Comment by FrancYescO** [comment]
usa ultima versione dev
