### ISSUE TITLE
Broken GUI After reboot

### ISSUE THREAD

**Issue by LucaCraft89** [Ansuel/tch-nginx-gui#1195]
Device Model/Firmware: TIM HUB+ DGA4331 / VCNT-3 Firmware: 1.1.1
GUI Version: [9.6.65](https://github.com/Ansuel/tch-nginx-gui/releases/tag/9.6.65)

Description of problem, HOW TO REPRODUCE, Media/Photos:
I installed the GUI normally and it worked, after i rebooted my device i get this "broken" page, i haven't touched the network config at all and passed the tar thru a USB drive
![image](https://github.com/user-attachments/assets/f6349e19-6253-4537-8419-472cfd564072)
in my experience i would think this is some issue with rewrite but this is using nginx so i have no idea
I tried:
- resetting the device and re-rooting it and doing everything from scratch
- redownloading the tar multiple times and over different networks and devices (also different USB drives)
- downloading it directly from the modem 
- doing everything over serial instead of ssh

I checked:
- that the bank plan was optimal every time
but in the end, it all always resulted in the above "broken" page

also:
![image](https://github.com/user-attachments/assets/76ac493a-f38a-4c53-9e24-c9ed0f196e9b)

**Comment by LucaCraft89** [comment]
> fully reset, reinstall the GUI, and check if reproducible.
> 
> as said, pretty sure was broken by the failed luci install #1194

as i described i already did that multiple times with no success

**Comment by FrancYescO** [comment]
so:
- reset
- install gui - working
- reboot - broken?

if this need a debug zip when was working just after the reset

**Comment by LucaCraft89** [comment]
is there a way to get it without resetting it or i have to reset it?

**Comment by LucaCraft89** [comment]
[DebugHelper2024-07-15-1515.tar.gz](https://github.com/user-attachments/files/16235012/DebugHelper2024-07-15-1515.tar.gz)
here you go, just reset it and done the log also this time it was a little different, i had to do the /etc/init.d/rootdevice force command twice because the first time it kicked me out of ssh for some reason but it is installed and working, i will not reboot the modem for now

**Comment by FrancYescO** [comment]
> i had to do the /etc/init.d/rootdevice force command twice because the first time it kicked me out of ssh for some reason but it is installed and working

this is surely unwanted and can cause some random bugs, btw try the reboot too see if replicable now

**Comment by LucaCraft89** [comment]
i managed to fix it thanks to release https://github.com/Ansuel/tch-nginx-gui/releases/tag/9.7.5 that fixed issue https://github.com/Ansuel/tch-nginx-gui/issues/1194 that allowed me to finish the LuCi installation that apparently remained corrupt even after full reset and now the modem works like a charm

**Comment by FrancYescO** [comment]
so... install of the GUI on a resetted DGA4331 is still causing this issue after reboot
installing luci after this bug happens (how if the gui is broken?) fix the gui ?!

**Comment by LucaCraft89** [comment]
I did it thru terminal with opkg install Luci and magically it worked

**Comment by FrancYescO** [comment]
doubting it is working in the correct way... on what port is responding? and is it working after reboot?

**Comment by LucaCraft89** [comment]
ok port 80 and no sign of custom gui, confirm it is fully functional even after reboot
