### ISSUE TITLE
wol/wow can't be enabled with 9.7.6

### ISSUE THREAD

**Issue by bltoby** [Ansuel/tch-nginx-gui#1196]
With clean updated gui 9.7.6 I can't enable the wol/wow function.

**Comment by FrancYescO** [comment]
missing all other template infos, was working before 9.7.6?

**Comment by bltoby** [comment]
DGA4132 with firmware 2.3.5


Yes, at least with old 9.6.97 it has been always working.

**Comment by FrancYescO** [comment]
try to revert this line from `replace` to `add` (`/etc/init.d/wol` file)  https://github.com/Ansuel/tch-nginx-gui/commit/b7e437eaffadf0f46b382c53b452b8bd7ba80559#diff-d11039dd2d1e443b87d862c508966dd10a3d2bbff02b75d13d7b7afeb8ec7c8aR37

https://github.com/Ansuel/tch-nginx-gui/issues/1160#issuecomment-2036621715

**Comment by bltoby** [comment]
Well, the real problem is the firmware probably from 2.3.x

The router won't be able to save any configuration for wow. When you click save the configuration, the router will give a successful feedback, but it actually didn't save any thing.

I have to go back to firmware 2.2.1 to be able to enable wow once again.

**Comment by bltoby** [comment]
but with firmware 2.3.5 the wifi are much more stable, so upgrade to 2.3.5 again. Workaround is manually change the wol file to save the desired settings, not by gui.
