### ISSUE TITLE
Traduzioni mancanti

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#120]
Nel Tab : **Telefonia** - **Registro Qualità**, continuano a non essere tradotti i termini : 

**Remoteparty** , **ReceiveInterarrivalJitter** , **FarEndInterarrivalJitter**

Grazie

**Comment by Ansuel** [comment]
Se trovi altro segnala qui

Il Mar 28 Ago 2018, 19:22 Francesco M <notifications@github.com> ha scritto:
