### ISSUE TITLE
Menu not displaying on right side

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#122]
After login menus are normally on right side. In gui 8.7.13 they re under logo and left side is cut off.

**Comment by Ansuel** [comment]
skin ? screenshot?

**Comment by flywire** [comment]
Default skin, blue line is left edge of window.
![snip](https://thumb.ibb.co/dBUN2p/Capture1.gif )

**Comment by Ansuel** [comment]
can you try to clear cache?

**Comment by flywire** [comment]
Fixed.
