### ISSUE TITLE
Error shown in Telephony > Codec Tab

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#123]
`invalid path Device.Services.VoiceService.{i}.PhyInterface.{i}.`
![](https://i.imgur.com/x3qsKxL.png)

**Comment by FrancYescO** [comment]
```
root@OpenWrt:/tmp/log/nginx# transformer-cli get Device.Services.VoiceService.
ERROR   invalid path Device.Services.VoiceService.
```

**Comment by Ansuel** [comment]
transformer-cli get Device.Services. this?

**Comment by FrancYescO** [comment]
Also nothing.
________________________________

**Comment by FrancYescO** [comment]
The issue is that `Device.` should be replaced with `InternetGatewayDevice.` ... also the other telephony modals are empty cause of this

**Comment by kevdagoat** [comment]
I do not get this error at all in the telephony codec tab

**Comment by FrancYescO** [comment]
i'm pretty sure is just a Tiscali firmware personalization, must find a way to get it working on all devices...
