### ISSUE TITLE
Error when saving in "Gateway"

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#124]
Parameters seems to be saved correctly but error is thrown.

`Some parameters failed validation`

![](https://i.imgur.com/YE5n2Er.png)
![](https://i.imgur.com/8panlFS.png)
![](https://i.imgur.com/zgMd40T.png)

**Comment by FrancYescO** [comment]
Here a cleaned config dir
[config.zip](https://github.com/Ansuel/tch-nginx-gui/files/2342144/config.zip)

**Comment by FrancYescO** [comment]
```
root@OpenWrt:~# transformer-cli get uci.power.
uci.power.cpu.cpuspeed [string] = 256
uci.power.cpu.wait [string] = 1
uci.power.ethernet.eee [string] = 0
uci.power.ethernet.ethapd [string] = 0
uci.power.ethernet.autogreeen [string] = 0
root@OpenWrt:~# transformer-cli get uci.ledfw.
uci.ledfw.status_led.enable [string] = 0
uci.ledfw.timeout.ms [string] = 0

```

**Comment by FrancYescO** [comment]
Yes
________________________________

**Comment by FrancYescO** [comment]
ehm, now not.

**Comment by Ansuel** [comment]
mh... strange... i think i know the problem but we need to retrigger the error...

**Comment by FrancYescO** [comment]
What can i try to retrigger?

**Comment by Ansuel** [comment]
Open system config and remove import restricted line 
Then go to the page and tell me...

**Comment by FrancYescO** [comment]
removing import_restricted line from `/etc/config/system` and than trying to save in gateway modal **does not** retrigger the error.

**Comment by Ansuel** [comment]
can you update and try to retrigger this error? now it does output what actually failed validation

**Comment by FrancYescO** [comment]
If I'm not wrong the issue is gone with some of the latest commits... I'll try on a stock Tiscali router in few hours

**Comment by FrancYescO** [comment]
Confirming, the issue seems solved... don't ask me how :D

**Comment by FrancYescO** [comment]
```
Some parameters failed validation
system_network_timezone: Invalid value.
```

i've flashed v8.7.54 on a tiscali firmware the error came back...

**Comment by Ansuel** [comment]
Strange think I will add a check in rootdevice...

Il Ven 7 Set 2018, 18:01 Francesco M <notifications@github.com> ha scritto:
