### ISSUE TITLE
Popup 

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#125]
Possibile che il popup dell'aggiornamento sia sempre visibile.

**Comment by FrancYescO** [comment]
immagini sia stato già risolto https://github.com/Ansuel/tch-nginx-gui/issues/121
o comunque a me non lo fa.

**Comment by Ansuel** [comment]
In realtà il problema non c'è mai stato...

**Comment by nclmrc** [comment]
![screenshot_20180831-005116_chrome](https://user-images.githubusercontent.com/38593316/44883647-1faa1400-acb8-11e8-8038-536130c8880f.jpg)
È normale?

**Comment by Ansuel** [comment]
Mi pare strano che non scompaia... Resettare quella finestrella è la prima
cosa che fa l'interfaccia quando fai il login...

Il Ven 31 Ago 2018, 00:52 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Dimmi te cosa posso provare a fare.

**Comment by nclmrc** [comment]
Cambiando skin in parte è sparita.

**Comment by Ansuel** [comment]
Cosa vuol dire in parte

**Comment by nclmrc** [comment]
Sulla skin verde. Il verde si camuffa con il verde e rimane solo sullo sfondo bianco
