### ISSUE TITLE
Port Forwarding rules not applied immediately

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#126]
When you add a new `IPv4 port mapping` it will not not be applied immediately after the successfull add.

**Comment by nclmrc** [comment]
Any update?

**Comment by FrancYescO** [comment]
no. but the probably is still present

**Comment by Ansuel** [comment]
update on this?

**Comment by kevdagoat** [comment]
Ok to close?
Doesn’t seem GUI related

**Comment by FrancYescO** [comment]
yes can be fixed thought GUI but i need more tests to confirm what is wrong..

**Comment by kevdagoat** [comment]
Any update?

**Comment by Ansuel** [comment]
Can anyone test this?

Il giorno Mar 6 Nov 2018, 01:03 Kevdagoat <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment]
seems solved.
