### ISSUE TITLE
Improve Hostnames Retrive

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#135]
È possibile far fare al HUB da DHCP relay , così da rimandare le richieste ad un altro server in rete? Chiedo questo perché se lo disabilito i dispositivi mi vengono tutti come unknow.

**Comment by nclmrc** [comment]
Se avete qualche altra soluzione per implementare il recupero dell'hostname in assenza di DHCP.

**Comment by FrancYescO** [comment]
Non credo ci sia modo per recuperare gli hostname senza qualche sorta di comunicazione con chi assegna l'ip, cosa che credo facesse il Forwarder DHCP

**Comment by nclmrc** [comment]
Qualche configurazione da suggerirmi?

**Comment by FrancYescO** [comment]
prova se tramite file di config riesci a trovare modo di abilitare il DHCP forwarder..

**Comment by nclmrc** [comment]
Sarebbe lo stesso del dhcp relay secondo te?

**Comment by FrancYescO** [comment]
Sì è la stessa cosa
________________________________
