### ISSUE TITLE
TG799/800vac No Icon

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#137]
Would it be possible to intergrate my iconfix repository with this main one to fix the icon issue when installing this gui on telstra TG799/800 modems.

https://github.com/kevdagoat/tch-nginx-gui-tg799-800-icon-fix

**Comment by Ansuel** [comment]
I'm still waiting for the dump... I really need it :(

**Comment by kevdagoat** [comment]
This?
/bin$ /etc/init.d/rootdevice debug
Root Script: Rooting in progress...
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Stopping nginx and transformer
Root Script: Checking if we are on TIM configuration
Root Script: Unlocking web interface if needed
Root Script: Check and cleanup
Root Script: Remove default dns
Root Script: Purify wan
Root Script: Fix dns bug
Root Script: Fix Sysupgrade
Root Script: Check orig config
Root Script: Trafficmon inizialization
Root Script: Restore original mapper
Root Script: Remove https check
Root Script: Check css presence
Root Script: Check if dnsmasq is names as we need it for the webui
Root Script: Check driver setting
/etc/rc.common: line 1: transformer-cli: not found
Root Script: Check Dropbear config file
Root Script: Check ddns directory
Root Script: Check eco param
Root Script: Sync dhcp configuration for new webui
Root Script: Create gui type in config
Root Script: Add new web option
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
ash: 1: unknown operand
Root Script: Moving aria2 dir
Root Script: Creating new option for led definition
Root Script: Creating and checking real version
Root Script: Creating new wol implementation
Root Script: Sync new xdsl option
Root Script: Creating utility simbolic link
Root Script: Clean old script
Root Script: Adding fast cache options
Root Script: Setting root flag
Root Script: Disable reboot after crash, this gives race condition...
Root Script: Save root password if modified
Root Script: Setting dropbear settings
Root Script: Restarting dropbear
Root Script: Doing various check and generating hash...
Root Script: Update branch detected: STABLE
Root Script: Updating GUI in /root folder from /tmp
Root Script: Detected upgrade!
Root Script: Old GUI hash: 66f1cde9296521eb6e0cb5d43116fe44
Root Script: New GUI hash: 66f1cde9296521eb6e0cb5d43116fe44
Root Script: Resetting version info...
Root Script: Sync version
Root Script: Apply modification
Root Script: Restart power init
Root Script: Restarting dnsmasq
Root Script: Process done.
Root Script: Checking if ISP is detected...
Root Script: Restarting transformer
Root Script: Waiting transformer to start for 20 seconds
Root Script: Restarting nginx
Root Script: Restarting transformer a second time cause it's just shit...
Root Script: Resetting cwmp and watchdog

Sent from Mail for Windows 10
