### ISSUE TITLE
SNR Margin UP

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#138]
Come mai questo valore nella GUI è sempre 0? Se faccio xdslctl info --show mi esce tutt'altro valore.

**Comment by nclmrc** [comment]
Penso sia un problema di recupero valori. Nella precedenti versioni download e upload erano in ordine scambiato.

**Comment by Ansuel** [comment]
transformer-cli get sys.class.xdsl.@line0.DownstreamSNRMpb

**Comment by Ansuel** [comment]
transformer/cli get sys.class.xdsl.@line0.DownstreamNoiseMargin

**Comment by nclmrc** [comment]
scusa con questi mi esce l snr in down, io ho problemi con l up

**Comment by FrancYescO** [comment]
transformer-cli get sys.class.xdsl.@line0.UpstreamNoiseMargin

**Comment by nclmrc** [comment]
con questi ok:

root@DGA4132:~# transformer-cli get sys.class.xdsl.@line0.DownstreamSNRMpb
sys.class.xdsl.@line0.DownstreamSNRMpb [string] =  7.0
root@DGA4132:~# transformer-cli get sys.class.xdsl.@line0.DownstreamNoiseMargin
sys.class.xdsl.@line0.DownstreamNoiseMargin [int] = 7

**Comment by nclmrc** [comment]
mi spieghi cosa è successo?

**Comment by Ansuel** [comment]
prova con questa versione...

in pratica io mi baso sul valore SNRM_down 

se ha qualche valore, si setta di prendere i valori di up e down da SNRM invece se è 0 li prende dalle stringhe normali (per ADSL)

Ora hanno settato che in ADSL, le stringhe SNRM funzionano dando il valore in down ma non in up

Ora ho messo la condizione sia per up che per down (prima si basava solo sul down) ora dovrebbe andare...

**Comment by FrancYescO** [comment]
Non sarebbe meglio mettere la condizionale Su quale tipo di connessione è attiva0? VDSL o adsl
________________________________

**Comment by nclmrc** [comment]
Sempre 0.0

**Comment by Ansuel** [comment]
prova ora

**Comment by nclmrc** [comment]
Comunque con l'adsl funzionano questi:
transformer-cli get sys.class.xdsl.@line0.UpstreamNoiseMargin
transformer-cli get sys.class.xdsl.@line0.DownstreamNoiseMargin
