### ISSUE TITLE
Broadband modal "Some parameters failed validation"

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#139]
Save button on Broadband modal shows "Some parameters failed validation" but all seems saved correctly (the VLAN ID)

on UNO firmware when rebooted first time the VLAN id seems was set on GUI but PPP wan't came online until i click save on the broadband modal, another reboot than got the PPP correctly online with no intervention

**Comment by kevdagoat** [comment]
PPP settings don’t work for Telstra modems

**Comment by FrancYescO** [comment]
@kevdagoat can you be more specific? Do you get any error?

Btw this issue should be strictly connected with https://github.com/Ansuel/tch-nginx-gui/issues/118 as we are using same interface names

**Comment by kevdagoat** [comment]
Nothing. It doesn’t put the credentials in the config file, which means: once I am connected to the dslam I get no internet

**Comment by FrancYescO** [comment]
So looks the issue is in the ppp modal and not broadband (here you can set only the VLAN ID), you get no error on save?
