### ISSUE TITLE
/usr/lib/lua/web/lp.lua Changed?

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#145]
Does that file get changed when installing the GUI?

**Comment by flywire** [comment]
No

**Comment by kevdagoat** [comment]
Ok

**Comment by flywire** [comment]
Interesting - complete match with vant-y_CRF779-17.2.0213-820-RB.rbi.decrypted dated 31/10/2017

**Comment by kevdagoat** [comment]
Ok thanks, will close.
