### ISSUE TITLE
TAB Relay

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#147]
Nel Tab relay è rimasta la dicitura dhcp relay. C'è un motivo?

**Comment by FrancYescO** [comment]
Credo sia una dimenticanza... più che altro avevi provato ad attivare il relay sulle vecchie versioni? ti funzionava mica?

**Comment by nclmrc** [comment]
Quel relay è per inoltrare la richiesta ad un dhcp via wan

**Comment by FrancYescO** [comment]
Sì ma è stato tolto perché buggato... Io non ho mai avuto occasione di provarlo

**Comment by FrancYescO** [comment]
E comunque se ricordo bene veniva chiesta l'interfaccia o ip dove inviare la richiesta di dhcp non era a forza la wan
