### ISSUE TITLE
Merge Request: LITE patch

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#154]
I have made a patch for this GUI which removes the icons over the lights. Can be found here 
https://github.com/kevdagoat/tch-nginx-gui-LITE

**Comment by FrancYescO** [comment]
Can you post directly the modded/removed files? i think we should take it as a skin

**Comment by kevdagoat** [comment]
[files.zip](https://github.com/Ansuel/tch-nginx-gui/files/2351891/files.zip)

**Comment by kevdagoat** [comment]
will write a script to install

**Comment by kevdagoat** [comment]
[liteskin.sh.txt](https://github.com/Ansuel/tch-nginx-gui/files/2352019/liteskin.sh.txt)
Had to upload it as text as GitHub doesn't support .sh files

**Comment by kevdagoat** [comment]
Will close this now and create a pull request

**Comment by kevdagoat** [comment]
No
Have changed my mind

**Comment by Ansuel** [comment]
the best thing would be a skin...

**Comment by kevdagoat** [comment]
See the pull request for the skin script

**Comment by Ansuel** [comment]
Pls create dedicated LITE skin

**Comment by kevdagoat** [comment]
I don’t have any idea on how to write css templates :(

**Comment by kevdagoat** [comment]
See above. 
I am closing this for now
