### ISSUE TITLE
cwmpd SetParametersValue Fault ... is there any mod to the default config?

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#155]
After installing the GUI on Tiscali firmware seems CWMP is not able to set values, looking at log there are 2 messages `SetParametersValue Fault`, is something here that can cause these conflicts or disallow remote edit?

can i get a more Verbose log?

Here i wrote just more detail:
https://www.ilpuntotecnico.com/forum/index.php/topic,78585.msg240754.html#msg240754

**Comment by Ansuel** [comment]
Any news on this?
