### ISSUE TITLE
Unwanted error echo in rootscript if no wan connection

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#161]
```
root@dsldevice:~# /etc/init.d/rootdevice force
Root Script: Rooting in progress...
interface wan has no physdev or physdev has no suitable ip
ping: sendto: Network is unreachable
```

**Comment by kevdagoat** [comment]
Not really an issue.
It is looking for an IP address.

**Comment by kevdagoat** [comment]
This is causing it:
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
				curl -k -s https://repository.ilpuntotecnico.com//files/Ansuel/AGTEF/GUI.tar.bz2 --output /root/GUI.tar.bz2
			else

**Comment by FrancYescO** [comment]
I know, but i think we should suppress errors and only show on debug if needed
________________________________

**Comment by kevdagoat** [comment]
Should be able to add a check into the script to check for internet

**Comment by kevdagoat** [comment]
The error message was going to stderr rather than stdout.
Added a redirect at the end of the line

**Comment by kevdagoat** [comment]
I do not get the message even without internet or wan plugged in

**Comment by FrancYescO** [comment]
Only one of the 2 messages are gone with the PR
```
root@OpenWrt:~# /etc/init.d/rootdevice force
Root Script: Rooting in progress...
interface wan has no physdev or physdev has no suitable ip
root@OpenWrt:~#
```

**Comment by kevdagoat** [comment]
Done
