### ISSUE TITLE
Telstra Firmware Transformer Issues

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#166]
This is what happens in the log while running the rootdevice script

` Tue Sep  4 18:46:19 2018 user.notice root:                                      _
Tue Sep  4 18:46:19 2018 user.notice root:      /\  (Modified Gui RootScript)  | |
Tue Sep  4 18:46:19 2018 user.notice root:     /  \    _ __   ___  _   _   ___ | |
Tue Sep  4 18:46:19 2018 user.notice root:    / /\ \  | '_ \ / __|| | | | / _ \| |
Tue Sep  4 18:46:19 2018 user.notice root:   / ____ \ | | | |\__ \| |_| ||  __/| |
Tue Sep  4 18:46:19 2018 user.notice root:  /_/    \_\|_| |_||___/ \__,_| \___||_|
Tue Sep  4 18:46:19 2018 user.notice root:
Tue Sep  4 18:46:19 2018 user.notice root:                              (Christo)
Tue Sep  4 18:46:19 2018 user.notice Root Script: Rooting in progress...
Tue Sep  4 18:46:19 2018 daemon.info watchdog-tch[6223]: stopping daemon (5.13)
Tue Sep  4 18:46:22 2018 user.notice mobiled: Delaying Mobiled startup. Waiting for 5837 to terminate
Tue Sep  4 18:46:22 2018 daemon.info transformer: [mobiled] Reloading config
Tue Sep  4 18:46:22 2018 daemon.info transformer: [mobiled] Cleaning up...
Tue Sep  4 18:46:22 2018 daemon.info transformer: [mobiled] Cleanup done
Tue Sep  4 18:46:23 2018 user.notice mobiled: Starting Mobiled
Tue Sep  4 18:46:23 2018 daemon.info transformer: [mobiled] Adding statemachine 1
Tue Sep  4 18:46:24 2018 user.notice Flow Cache Setting: Starting service...
Tue Sep  4 18:46:24 2018 user.notice Flow Cache Setting: Setting l2tp options to 1
Tue Sep  4 18:46:24 2018 user.notice Flow Cache Setting: Setting gre options to 1
Tue Sep  4 18:46:24 2018 user.notice Flow Cache Setting: Setting ipv6 options to 1
Tue Sep  4 18:46:24 2018 user.notice Flow Cache Setting: Setting mcast options to 1
Tue Sep  4 18:46:24 2018 user.notice Flow Cache Setting: Setting mcast-learn options to 1
Tue Sep  4 18:46:24 2018 daemon.notice transformer: [mobiled] (PlatformConfigure) runs PlatformConfigure-Main.check(timeout, 1)
Tue Sep  4 18:46:24 2018 authpriv.info dropbear[5920]: Early exit: Terminated by signal
Tue Sep  4 18:46:25 2018 daemon.notice transformer: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1, PlatformConfigure)
Tue Sep  4 18:46:25 2018 authpriv.info dropbear[7310]: Not backgrounding
Tue Sep  4 18:46:27 2018 daemon.info dnsmasq[6712]: exiting on receipt of SIGTERM
Tue Sep  4 18:46:27 2018 daemon.info dnsmasq[6711]: exiting on receipt of SIGTERM
Tue Sep  4 18:46:27 2018 daemon.info dnsmasq[6710]: exiting on receipt of SIGTERM
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: started, version 2.76 cachesize 150
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP conntrack dns-filterno-ipset no-auth no-DNSSEC loop-detect inotify
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq-dhcp[7487]: DHCP, IP range 192.168.2.129 -- 192.168.2.253, lease time 1h
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq-dhcp[7487]: DHCP, IP range 192.168.2.1 -- 192.168.2.125, lease time 1h
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq-dhcp[7487]: DHCP, IP range 10.0.0.1 -- 10.0.0.137, lease time 1h
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: using local addresses only for domain lan
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: reading /tmp/resolv.conf.auto
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: using local addresses only for domain lan
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: using nameserver 10.0.0.139#53 [0]
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: read /etc/hosts - 2 addresses
Tue Sep  4 18:46:30 2018 daemon.crit dnsmasq[7489]: failed to create listening socket for port 53: Address already in use
Tue Sep  4 18:46:30 2018 daemon.crit dnsmasq[7489]: FAILED to start up
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7487]: read /tmp/hosts/dhcp.main - 3 addresses
Tue Sep  4 18:46:30 2018 daemon.info dnsmasq[7488]: started, version 2.76 cachesize 150
Tue Sep  4 18:46:31 2018 daemon.info dnsmasq[7488]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP conntrack dns-filterno-ipset no-auth no-DNSSEC loop-detect inotify
Tue Sep  4 18:46:31 2018 daemon.warn dnsmasq[7488]: warning: interface fonopen does not currently exist
Tue Sep  4 18:46:31 2018 daemon.info dnsmasq-dhcp[7487]: read /etc/ethers - 0 addresses
Tue Sep  4 18:46:31 2018 daemon.info dnsmasq[7488]: using local addresses only for domain hotspot
Tue Sep  4 18:46:31 2018 daemon.warn dnsmasq[7488]: no servers found in /tmp/resolv.conf.hotspot, will retry
Tue Sep  4 18:46:31 2018 daemon.info dnsmasq[7488]: read /etc/hosts - 2 addresses
Tue Sep  4 18:46:31 2018 daemon.info dnsmasq[7488]: read /tmp/hosts/dhcp.hotspot - 3 addresses
Tue Sep  4 18:46:32 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
Tue Sep  4 18:46:33 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
Tue Sep  4 18:46:36 2018 daemon.crit dnsmasq[7526]: failed to create listening socket for port 53: Address already in use
Tue Sep  4 18:46:36 2018 daemon.crit dnsmasq[7526]: FAILED to start up
Tue Sep  4 18:46:41 2018 daemon.crit dnsmasq[7537]: failed to create listening socket for port 53: Address already in use
Tue Sep  4 18:46:41 2018 daemon.crit dnsmasq[7537]: FAILED to start up
Tue Sep  4 18:46:41 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Tue Sep  4 18:46:41 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Tue Sep  4 18:46:41 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
Tue Sep  4 18:46:42 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
Tue Sep  4 18:46:43 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
Tue Sep  4 18:46:46 2018 daemon.crit dnsmasq[7540]: failed to create listening socket for port 53: Address already in use
Tue Sep  4 18:46:46 2018 daemon.crit dnsmasq[7540]: FAILED to start up
Tue Sep  4 18:46:51 2018 daemon.crit dnsmasq[7541]: failed to create listening socket for port 53: Address already in use
Tue Sep  4 18:46:51 2018 daemon.crit dnsmasq[7541]: FAILED to start up
Tue Sep  4 18:46:54 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: starting daemon (5.13):
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: int=5s realtime=yes sync=no soft=no mla=0 mem=0
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: ping: no machine to check
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: file: no file to check
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: pidfile: no server process to check
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: interface: no interface to check
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: temperature: no sensors to check
Tue Sep  4 18:46:54 2018 daemon.info watchdog-tch[7614]: test=none(0) repair=none(0) alive=none heartbeat=none to=root no_act=no force=no
Tue Sep  4 18:46:54 2018 daemon.err watchdog-tch[7614]: cannot open none (errno = 2 = 'No such file or directory')
Tue Sep  4 18:46:55 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
Tue Sep  4 18:46:56 2018 daemon.crit dnsmasq[7625]: failed to create listening socket for port 53: Address already in use
Tue Sep  4 18:46:56 2018 daemon.crit dnsmasq[7625]: FAILED to start up
Tue Sep  4 18:46:56 2018 daemon.info procd: Instance dnsmasq::dnsmasq s in a crash loop 6 crashes, 0 seconds since last crash
Tue Sep  4 18:47:03 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Tue Sep  4 18:47:03 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Tue Sep  4 18:47:03 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
Tue Sep  4 18:47:03 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
Tue Sep  4 18:47:04 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
Tue Sep  4 18:47:13 2018 user.debug mmpbxd[5421]: [SIPDEV_APN]    :E: resetAPNConnection:120 - Could not connected to Apple Push Notification Service: could not reslove host (14)
Tue Sep  4 18:47:13 2018 user.debug mmpbxd[5421]: [SIPDEV_APN]    :I: resetAPNConnection:126 - apn connection started apn mode 0 ret=13. `

**Comment by Ansuel** [comment]
post a better log also lots of error from transformer can be ignored (if something very wrong happen tranformer just crash and doesn't run so this could cause problem only on his specific map... )
