### ISSUE TITLE
Error latest gui with interface different than ptm0

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#175]
Lo fa anche con la 68.
La pagina non funziona

192.168.1.254 non ha inviato dati.

ERR_EMPTY_RESPONSE

**Comment by Ansuel** [comment]
Manda log...

**Comment by nclmrc** [comment]
Da dove li posso ricavare.

Il Mer 12 Set 2018, 23:50 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
logread

**Comment by nclmrc** [comment]
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/2376996/log.txt)

**Comment by Ansuel** [comment]
ti consiglio di tornare ad una gui vecchia o di eliminare il file www/info-cards/003_graph 

il problema deriva dal fatto che sei in adsl...

devo ancora includere un sistema per rilevare il tipo di interfaccia e questo crea il problema

**Comment by nclmrc** [comment]
Ma non eri riuscito a scoprirlo tramite xdslctl state

**Comment by Ansuel** [comment]
MH no devo utilizzare un altro modo rispetto a quello xdsl

Il Gio 13 Set 2018, 00:07 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Puoi leggere il file network e vedere se nella wan è configurata una wan
atmo pre.

Il Gio 13 Set 2018, 00:09 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
Si basare tutto sull'interfaccia collegata alla wan non è una cattiva idea

Il Gio 13 Set 2018, 00:11 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Così sei su una configurazione statica che funziona anche in assenza di
portante.

Il Gio 13 Set 2018, 00:12 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
Se vuoi provare questa versione

Il Gio 13 Set 2018, 00:14 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Questa va, ma perché prima vedevo in prima pagina i dispositivi wifi
connessi mentre adesso solo quelli ethernet?

Il Gio 13 Set 2018, 00:29 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
![screenshot_20180913-003722_chrome](https://user-images.githubusercontent.com/38593316/45456990-43744d80-b6ed-11e8-82d9-4ecd5e9edd5a.jpg)
Undefined

**Comment by nclmrc** [comment]
Forse ho capito. Nonostante mi trovi 3 dispositivi. Prendono il primo come host1 il secondo 8 il terzo 9
