### ISSUE TITLE
Stats page issue tracklist

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#187]
![immagine](https://user-images.githubusercontent.com/38593316/45553746-fe5b3300-b834-11e8-941a-82fff2216583.png)
Xdsl stat può essere un pò alzato, e quel Noise Margin Downstream fallo stare in una riga sola.

Grazie

**Comment by nclmrc** [comment]
Il menù in alto nella scheda stat andrebbe allineato sulla destra. 
Grazie 
![screenshot_20180914-204132_chrome](https://user-images.githubusercontent.com/38593316/45569093-ca950300-b85e-11e8-9fc0-b7fbc0a073df.jpg)

**Comment by nclmrc** [comment]
![screenshot_20180914-215423_chrome](https://user-images.githubusercontent.com/38593316/45572174-d84f8600-b868-11e8-99db-94db64bd48e4.jpg)
La freccia che punta il basso se cliccata non risponde.

**Comment by nclmrc** [comment]
il numero di telefono non mi si vede per intero, forse perchè non inizia per +39

**Comment by nclmrc** [comment]
Ho fatto i conti perdo 3 cifre che equivalgono al +39. Io lo lascerei per intero non farei il substring.

**Comment by Ansuel** [comment]
nel tuo numero c'è il più?

**Comment by nclmrc** [comment]
No solo numero

**Comment by nclmrc** [comment]
Con l'ultima hai risolto grazie?

**Comment by Ansuel** [comment]
Me lo devi dire tu ahahahahahah

Il Lun 17 Set 2018, 21:37 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
ho correto il messaggio

**Comment by nclmrc** [comment]
è rimasto solo i margini da mettere se possibile su una riga sola

**Comment by nclmrc** [comment]
Forse per non avere problemi sia nella versione desktop sia mobile,  converrebbe mettere attenuazioni e margini up e down in due righe separate. Mi sembra meglio poi decidi te.
![screenshot_20180919-175324_chrome](https://user-images.githubusercontent.com/38593316/45765684-e79e4d00-bc35-11e8-821c-fbcaeea6a589.jpg)

**Comment by FrancYescO** [comment]
- Mettere le maiuscole sulle sigle e acronimi "Wan Stats", "Dslam", "Cpu", "Gui"
- Abbravierei "Dslam Firmware Version" in "Dslam Firmware" in modo da poter recuperare un po di margine sinistro sulle card
- Il grafico WAN non utilizza tutta la larghezza
![image](https://user-images.githubusercontent.com/4574593/46263231-ca5a6000-c50c-11e8-85cb-8ce01d102bc8.png)
- le info vanno a caporigo quando non necesario (guarda uptime)
![image](https://user-images.githubusercontent.com/4574593/46263237-e827c500-c50c-11e8-8f15-ee67822326e6.png)
- le tabelle, a righe colorate alternate non hanno trasparenza e nascondono l'icona di sfondo della card:
![image](https://user-images.githubusercontent.com/4574593/46263265-32a94180-c50d-11e8-8c19-eaf6c59194db.png)

**Comment by Ansuel** [comment]
riguardo trasparenza e stringhe puoi fare un pull request?

**Comment by nclmrc** [comment]
Si può chiudere?
