### ISSUE TITLE
Connected devices not showing up in gui stats

### ISSUE THREAD

**Issue by Diavulrus** [Ansuel/tch-nginx-gui#188]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: DGA4130
Gui Version: 8.7.78

Description of problem: In the new stats interface only one device is shown while the others seem not to be present

How to reproduce (if possible):

Media/Photos (if possible):
![screenshot_2018-09-14 gateway](https://user-images.githubusercontent.com/32335829/45566169-28711d00-b856-11e8-89ba-a439e9bcad97.png)

**Comment by Ansuel** [comment]
can you post a screen of the connected device modal (the page that show the device from the cards page)

**Comment by nclmrc** [comment]
Penso sia lo stesso problema

**Comment by Diavulrus** [comment]
![screenshot_2018-09-14 gateway 1](https://user-images.githubusercontent.com/32335829/45569510-01b7e400-b860-11e8-92be-d84919ea84ef.png)
![screenshot_2018-09-14 gateway 3](https://user-images.githubusercontent.com/32335829/45569511-01b7e400-b860-11e8-914f-63d66f93818d.png)
![screenshot_2018-09-14 gateway 2](https://user-images.githubusercontent.com/32335829/45569512-01b7e400-b860-11e8-8c7a-5182bc9ef917.png)
![screenshot_2018-09-14 gateway 4](https://user-images.githubusercontent.com/32335829/45569515-01b7e400-b860-11e8-9ff1-4cab39235519.png)

Ecco la lista dei dispositivi connessi.
Sì, credo anche io sia lo stesso problema, scusa ma non mi ero accorto che avevi già aperto l'issue sullo stesso argomento prima di aprirne uno nuovo

**Comment by Ansuel** [comment]
perdonami ma alla porta ethernet 3 hai collegato uno switch? comunque grazie mi hai confermato che il problema c'è...

**Comment by Diavulrus** [comment]
Alla porta 3 c'è collegato un access point della unifi quindi tutti i dispositivi wifi risultano collegati a quella porta come dispositivi lan. Figurati!

**Comment by nclmrc** [comment]
@Ansuel la cosa strana è che appena l'hai implementata ha funzionato poi no

**Comment by nclmrc** [comment]
@Ansuel ma la tabella da dove se la ricava? Da rpc.hosts?

**Comment by nclmrc** [comment]
Hai caricato l'ultima versione?

**Comment by Ansuel** [comment]
sto avendo problemi con ftp

**Comment by nclmrc** [comment]
Provata fix funziona.
