### ISSUE TITLE
Gui Issue tracklist

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#189]
https://github.com/Ansuel/tch-nginx-gui/issues/87

Ho riprovato un po tutte le skin e ho riscontrato alcuni di questi issues. Inoltre il popup dell'aggiornamento ad esempio sulle skin viola e verde ha un comportamento strano, sparisce a tratti.

**Comment by nclmrc** [comment]
Centratura mobile e freccine per spostarsi sulle skin viola e blu.  La verde è perfetta ti consiglio se non vuoi perderci il capo di ripartire da quella e cambiare i colori.
Per quanto riguarda il popup dell'aggiornamento andrebbe visto caso x caso perché ce un comportamento diverso.

**Comment by nclmrc** [comment]
Per quelle fritz style nella versione mobile il menu a scomparsa sulla sinistra non scorre e non si raggiunge le ultime voci in basso

**Comment by Ansuel** [comment]
qualcuno può testare i temi ?

**Comment by nclmrc** [comment]
Che modifiche hai implementato?

**Comment by Ansuel** [comment]
in versioni vecchie avevo migliorato alcune cose poi mi sono perso... ho bisogno di un recappone perchè sto per pubblicare in stabile

**Comment by nclmrc** [comment]
Ti mando per mail screen con un po di problemi.

**Comment by nclmrc** [comment]
Nel tema viola mancano le freccine e si vede a metà il popup dell' aggiornamento in alto. Negli altri il popup copre i dati della cpu.

**Comment by nclmrc** [comment]
Nel tema viola almeno nella versione mobile non è centrata. A destra c'è ancora sfondo.

**Comment by Ansuel** [comment]
altro ? ho fixato i problemi che mi hai inviato

**Comment by Ansuel** [comment]
dei popup a cosa ti riferisci? alle foto ?

**Comment by nclmrc** [comment]
Al popup che indica l'aggiornamento eseguito

**Comment by nclmrc** [comment]
In stat i valori xdsl up e down è meglio metterli su due righe

**Comment by Ansuel** [comment]
ok fatto poi ?

**Comment by nclmrc** [comment]
Mi sembri quasi tutto ok adesso.  Io sarei per seguire questo dal prossimo filone di beta

**Comment by nclmrc** [comment]
Puoi riguardare i valori xdsl su due righe

**Comment by Ansuel** [comment]
ho fatto la modifica ma non l'ho pushata... se non la vedi è per questo motivo

**Comment by nclmrc** [comment]
Puoi aggiornare il logo technicolor con questo

**Comment by nclmrc** [comment]
Questo meglio http://logok.org/wp-content/uploads/2014/08/Technicolor-logo.png

**Comment by nclmrc** [comment]
Questa icona https://img.tim.it/sdr/landing/smart-modem/img/tim-hub-03.png ottimizza meglio la scheda secondo me

**Comment by nclmrc** [comment]
mi rimane questo sulla GUI.
![immagine](https://user-images.githubusercontent.com/38593316/46520963-41ca1f80-c87e-11e8-9d99-f0c50c2b337e.png)

**Comment by nclmrc** [comment]
da verificare l'icona wan in stats.
![immagine](https://user-images.githubusercontent.com/38593316/46525988-4d711280-c88d-11e8-94a2-7c7369bc5979.png)

**Comment by nclmrc** [comment]
potresti mettere il globo in wan stats

**Comment by nclmrc** [comment]
Oltre il globo in wan stat, si può mettere il logo bianco sui temi a a sfondo scuro.

**Comment by FrancYescO** [comment]
puó andare cosí? si riesce a schirire un pó tramite css in modo che non bisogna mettere un ulteriore immagine con scritta bianca

![image](https://user-images.githubusercontent.com/4574593/47261959-d23d6c80-d4da-11e8-9e84-942ed636d811.png)

```
-webkit-filter: opacity(.8) drop-shadow(0px 0px 0px #fff );
  filter: opacity(.8) drop-shadow(0px 0px 0px #fff);
```

**Comment by FrancYescO** [comment]
come non detto `logo_white.webp` giá lo abbiamo bisognerebbe solo spostare il logo (magari come background image del div logo) nel css anziché nel template

**Comment by nclmrc** [comment]
Si perfetto

**Comment by nclmrc** [comment]
Ho notato nei temi fritz base. La notifica di avvenuto aggiornamento è posizionata in fondo coprendo parte delle schede.
