### ISSUE TITLE
Support Wireless control also for guest wifi

### ISSUE THREAD

**Issue by BreakSecurity** [Ansuel/tch-nginx-gui#198]
Device Model: MediaAccess TG789vac v2
Gui Version: 8.7.83

Description of problem: The rule dont apply to Guest network (ap1) but only to standard wifi (ap0)

How to reproduce (if possible): set a rule with guest wifi turned on, wait and see

Media/Photos (if possible):

Feature request: 
1) ability to apply rules to a chosen AP
2) ability to turn wifi on after the rule was applied by pressing wifi button on router (usefoul if someone as to use wifi more)
2.1) if the wifi is not being used for n time after the rule was ignored by pressing the button reapply the rule 

Config file (tod): 
```
config tod 'global'
	option tod_enabled '1'
	option tracelevel '4'
	option enabled '1'
	option time_change_monfreq '10'

config action 'action07DA998E57A9BC72DD76822D9EEE8F5F'
	option script 'wifitodscript'
	option enabled '1'
	option object 'wifitod.wifitod07DA998E57A9BC72DD76822D9EEE8F5F'
	list timers 'timer07DA998E57A9BC72DD76822D9EEE8F5F'

config timer 'timer07DA998E57A9BC72DD76822D9EEE8F5F'
	option stop_time 'Mon,Tue,Wed,Thu,Fri,Sat,Sun:07:30'
	option start_time 'Mon,Tue,Wed,Thu,Fri,Sat,Sun:03:00'

config wifitod 'wifitod07DA998E57A9BC72DD76822D9EEE8F5F'
	list ap 'ap007DA998E57A9BC72DD76822D9EEE8F5F'
	list ap 'ap107DA998E57A9BC72DD76822D9EEE8F5F'

config ap 'ap007DA998E57A9BC72DD76822D9EEE8F5F'
	option ap 'ap0'
	option state '0'

config ap 'ap107DA998E57A9BC72DD76822D9EEE8F5F'
	option ap 'ap1'
	option state '0'

config action 'action72CB8ECCB3E22FA146BBA7DC24A9C779'
	option object 'wifitod.wifitod72CB8ECCB3E22FA146BBA7DC24A9C779'
	option script 'wifitodscript'
	option enabled '1'
	list timers 'timer72CB8ECCB3E22FA146BBA7DC24A9C779'

config timer 'timer72CB8ECCB3E22FA146BBA7DC24A9C779'
	option stop_time 'Mon,Tue,Wed,Thu,Fri,Sat,Sun:13:30'
	option start_time 'Mon,Tue,Wed,Thu,Fri,Sat,Sun:13:15'

config wifitod 'wifitod72CB8ECCB3E22FA146BBA7DC24A9C779'
	list ap 'ap072CB8ECCB3E22FA146BBA7DC24A9C779'
	list ap 'ap172CB8ECCB3E22FA146BBA7DC24A9C779'

config ap 'ap072CB8ECCB3E22FA146BBA7DC24A9C779'
	option state '0'
	option ap 'ap0'

config ap 'ap172CB8ECCB3E22FA146BBA7DC24A9C779'
	option ap 'ap1'
	option state '0'


```

**Comment by Ansuel** [comment]
@BreakSecurity i made some progress in the latest version can you test it and suggest some changes?

**Comment by Ansuel** [comment]
i know the problem with the dark skin 
did you test the rule for guest wifi ?

**Comment by BreakSecurity** [comment]
It works fine. I found a bug when you try to modify an existing rule the change don't apply

**Comment by BreakSecurity** [comment]
Yep the only problem I had is trying to modify an old rule. Do you think other suggestion ar possible?

**Comment by Ansuel** [comment]
I fixed the edit yesterday can you try to create a new rule and edit

**Comment by BreakSecurity** [comment]
![immagine](https://user-images.githubusercontent.com/38836022/46472491-a4b7aa00-c7dd-11e8-9032-f7f4d66b340c.png)
Still pretty ugly same text repeted and time not visible.

**Comment by kevdagoat** [comment]
You do realise this is impossible?

There are two chips on the board that handle wifi, the cpu (brcm63xxx) handles 2.4ghz and a separate chip handles 5ghz.

Each chip can only “create” 3 wifi networks, 1 master wifi network with all of the settings available and 2 slave networks that are subsections of the master. It will always be impossible to change settings on the slave channels that might make it faster then the master channel.

Example:
The master channel mode is set to A/N (not AC)
The slave channel cannot have a different mode as every time a packet is sent from a device to the chip (or vice versa) the chip would have to turn off (or on) a different mode, resulting in lost packets and really slow secondary networks. It would also put a ton of stress on the chip.

**Comment by BreakSecurity** [comment]
Sorry but you misunderstood I only want a button to setup a guest wifi like in UNO FW or iiNet.

**Comment by kevdagoat** [comment]
Ahh so like a click of a button sets up a wifi network?

**Comment by BreakSecurity** [comment]
Like an option to add/setup guest wifi. We can add other option to like deny access to modem pages to guest or limit only to cards page, limit bandwidth and so on...

**Comment by BreakSecurity** [comment]
#291 reference to this too

**Comment by kevdagoat** [comment]
Is this ok to close?

**Comment by FrancYescO** [comment]
No.

**Comment by Ansuel** [comment]
the point 2 needs to much work and would result in too much modification to the default behaviour
