### ISSUE TITLE
nginx.conf always loses the ssl setting on GUI upgrade

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#20]
Every time the GUI is updated, the /etc/nginx.conf gets modified.

There is a section that normally reads:

```
    init_worker_by_lua '
        local sessioncontrol = require("web.sessioncontrol")
        sessioncontrol.setManagerForPort("default", "80")
        sessioncontrol.setManagerForPort("assistance", "443")
    ';
```

I modified it to use ssl for the GUI as well:

```
    init_worker_by_lua '
        local sessioncontrol = require("web.sessioncontrol")
        sessioncontrol.setManagerForPort("default", "80")
        sessioncontrol.setManagerForPort("default", "443")
    ';
```

After every update, it is like this and thus SSL no longer works:

```
    init_worker_by_lua '
        local sessioncontrol = require("web.sessioncontrol")
        sessioncontrol.setManagerForPort("default", "80")
               sessioncontrol.setManagerForPort("default", "443")
        sessioncontrol.setManagerForPort("assistance", "443")
    ';
```

**Comment by meyergru** [comment]
The second setting does. https:// instead of https:// , no problem.

**Comment by Ansuel** [comment]
can you login with admin and assist user?

**Comment by meyergru** [comment]
I did not know about assist user, but admin works fine.

**Comment by Ansuel** [comment]
if i try to access 443 port from wan nginx respond with 404 not found? it's the same for you?

**Comment by meyergru** [comment]
I never tried to use the GUI from WAN side, as I only use bridge mode, I can only access it from the outside transfer net of my router. With that, port 80 always works, whereas the usual setup for 443 (namely, "assistance") always leads to an error. Once I redirect port 443 to "default", both 80 and 443 (SSL) work.

I never got what "assistance" was for anyway, I simply assume it just does not work.

**Comment by Ansuel** [comment]
assistance is a temp user to permit access to the modem from wan (should be used for isp) anyway in new dev update it should work

**Comment by meyergru** [comment]
The setting is now as in your new code:

```
    init_worker_by_lua '
        local sessioncontrol = require("web.sessioncontrol")
        sessioncontrol.setManagerForPort("default", "80")
        sessioncontrol.setManagerForPort("assistance" or "default", "443")
    ';
```

However, I always get a 404 with https://192.168.7.1:

![grafik](https://user-images.githubusercontent.com/17402664/38333788-e1a17f5e-3859-11e8-8be7-40d06feac7cc.png)

BTW, this works (but I don't know if it helps):

```
    init_worker_by_lua '
        local sessioncontrol = require("web.sessioncontrol")
        sessioncontrol.setManagerForPort("default", "80")
        sessioncontrol.setManagerForPort("default" or "assistance", "443")
    ';
```
