### ISSUE TITLE
Removing the GUI!!

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#202]
How do I remove the gui????? accidentally installed it on a tg797 Tried:
Firmware flash 
JFFS2 reset
unmounting /overlay
firstboot
and tftp flash

**Comment by kevdagoat** [comment]
rm -R / 
worked

**Comment by Ansuel** [comment]
never... to reset the gui just remove anything in overlay and reboot but you will remove also rootscript and next boot = locked

**Comment by kman82** [comment]
Can anyone share how I can remove the over lay..i have ssh access on a technicolor 3 smartmodem

**Comment by FrancYescO** [comment]
press 1 time reset button.
