### ISSUE TITLE
dhcp name

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#209]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: dga4130
Gui Version: 8.8.13

Description of problem:
Ciao ho un dga4132 ed ho installato la nuova gui versione dev. firmware 1.2.0
ci sono alcune cose che non mi tornano...
ad esempio non so come mai, ho assegnato gli ip statici e mi succede questo:
con gli ip assegnati in modo manuale sul pc la gui non mi fa vedere il nome del device che e' connesso, mette unknown
con gli ip assegnati in modo automatico va, vedo tutto, ma se riavvio il modem su tutti i pc in cui e' assegnato il modo automatico cancella i dns e mette come dns  192.168.0.1, il che non lo fa' navigare ovviamente....
se metto il dhcp sul client in automatico ma reimposto i dns, sempre sul client, il router non fa' vedere l'hostname. ecco il problema !
How to reproduce (if possible):

Media/Photos (if possible):

**Comment by dga4130-renato** [comment]
![schermata del 2018-09-23 13-31-24](https://user-images.githubusercontent.com/43514633/45927539-07cf5400-bf35-11e8-882b-571d7c5f0969.png)

**Comment by dga4130-renato** [comment]
Stranamente sul server dns c'era 192.168.0.1, quindi il problema di assegnare i giusti dns e' risolto.
rimane il fatto che non comunica il nomehost quando sul client e' abilitato un indirizzo fisico riservato con i suoi dns

**Comment by FrancYescO** [comment]
Se stai usando la dev i DNS per la WAN assegnali dalla modal internet non sul dhcp... Anche se il problema degli hostname non credo dipenda da questo

**Comment by dga4130-renato** [comment]
Puoi spiegarti meglio ? Non sono espertissimo

Il dom 23 set 2018, 17:19 Francesco M <notifications@github.com> ha scritto:

**Comment by FrancYescO** [comment]
Ma con gli ip dinamici che assegna il DHCP i nomi li vedi? Perché quando assegni quelli statici tramite MAC (quindi sul modem e non sui dispositivi) assegni manualmente un nome al dispositivo (che imposti insieme all'IP da assegnare) e il modem userá quello assegnato ignorando l'hostname reale

**Comment by dga4130-renato** [comment]
non si vedono....a meno che non togli i dns dal client e lasci sia il modem che li assegna

**Comment by FrancYescO** [comment]
Ma con i DNS settati intendi direttamente sul client o quelli che prende da DHCP?

**Comment by nclmrc** [comment]
È normale. Assegna la staticità attraverso il modem.

**Comment by FrancYescO** [comment]
se imposti manualmente l'ip sul client il DHCP del modem non lo richiama proprio é normale compaia come unknow.

per ovviare imposta l'ip che vuoi assegnare al client dal modem in modo da potergli dare cosí anche un nome

**Comment by dga4130-renato** [comment]
Ed infatti lo avevo fatto. Ma non lo prende. Si collega con l'IP assegnato na il nome rimane unknown

**Comment by nclmrc** [comment]
Rimuovi la staticità sul pc stesso.

Il Lun 24 Set 2018, 06:35 dga4130-renato <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment]
Chiudo in favore di questa https://github.com/Ansuel/tch-nginx-gui/issues/135
