### ISSUE TITLE
CPU load does not show on Gateway tile

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#21]
See here:

![grafik](https://user-images.githubusercontent.com/17402664/38257077-e5e57d9a-375f-11e8-8436-918b7ea6a32b.png)

This is in bridge mode. To my recollection, I saw it correctly on a modal page which I cannot seem to find in bridge mode any more.

**Comment by meyergru** [comment]
Wow. In Chrome, once I reload the page, the load is shown. What is that?

**Comment by Ansuel** [comment]
that thing is based on ajax request of a lua file... can you provide me the error of the browser where is not shown?

**Comment by meyergru** [comment]
When I open the start page, the Firefox console shows this:

![grafik](https://user-images.githubusercontent.com/17402664/38292406-ebab4514-37e3-11e8-8c1a-4816efb4413f.png)

**Comment by Ansuel** [comment]
@meyergru what version are you using?

**Comment by meyergru** [comment]
6.7.61

**Comment by Ansuel** [comment]
@meyergru too strange try clean cache?

**Comment by meyergru** [comment]
Yes. I even tried it with SSL and without, because I suspected the XHR request goes wrong, but it is never called. Even with Chrome, only the frist refresh works (automatically after 5 secs).

I think the error message tells a tale: It seems there is a problem with the knockout construct, although I am at a loss why. Probably, the ko object is not yet instantiated when the GatewayCard is called.

**Comment by Ansuel** [comment]
it's strange cause gateway.lp load the knockout js so....

**Comment by meyergru** [comment]
That was the correct hint: Yes, it does so - but asynchronously! Remove the "async" attribute and ko will be ready at the right time. I just did that and it works right away. It even fixes the problem for initial loading in Chrome!

**Comment by Ansuel** [comment]
Will remove async then

**Comment by meyergru** [comment]
Should be done with the latest commit.
