### ISSUE TITLE
telegestione

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#210]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: dga4132
Gui Version:8.8.13

Description of problem:
la telegestione funziona solo se ho il cellulare allacciato alla rete locale, ma se spengo la wifi sul telefono non mi trova il modem.

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
inizia con il chiarire cosa intendi con telegestione.
che l'interfaccia del modem all'indirizzo 192.168.x.x sia raggiungibile solo via wifi é normale, per raggiungerla via wan devi abilitare l'assistenza remota e se necessario un DDNS.

**Comment by dga4130-renato** [comment]
Intendo con la app di Telecom.
Se sono connesso in wifi si collega senza problemi all'interfaccia del modem..se non sono connesso alla wifi locale e quindi fuori casa mi dice modem non raggiungibile

**Comment by FrancYescO** [comment]
sai dire da quale versione ha smesso di funzionare o l'ultima che ricordi funzionasse?

**Comment by dga4130-renato** [comment]
Mi pare di ricordare che sia successo quando ho iniziato ad usare le  devo.
Ho rimesso la versione stabile ma nulla. Deve essere un problema di configurazione

**Comment by FrancYescO** [comment]
Hai mica disattivato il CWMP? Hai ancora il problema?

**Comment by Ansuel** [comment]
Hai per caso cambiato DNS ?

**Comment by dga4130-renato** [comment]
Si. Dici sia quello ??

**Comment by dga4130-renato** [comment]
Telegestione (CWMP)
Attivato
Indirizzo ACS: None
Periodicità: 900

**Comment by FrancYescO** [comment]
Prova reimpostando gli originali
________________________________

**Comment by dga4130-renato** [comment]
Avevo reimpostato questo, ma non si connette lo stesso.
cwmpd.cwmpd_config.acs_url='https://regman-mon.interbusiness.it:10800/acs/'
poi ho smesso di giocare con la config... dopo l'ultimo problema meglio evitare.
Avevo cambiato web.remote.user='assist' con un altro nome per poi reimportarlo ma si e' inchiodato tutto, mi e' toccato riprestinare da 0, mezza nottata da urlo !

**Comment by Ansuel** [comment]
inserisci questo nell'url

https://regman-tl.interbusiness.it:10700/acs/

**Comment by dga4130-renato** [comment]
gia provato ma non va nemmeno con 10500

**Comment by dga4130-renato** [comment]
per scrupolo riprovo

**Comment by Ansuel** [comment]
ma questi link li puoi aprire dal pc?

**Comment by Ansuel** [comment]
il problema nasce dai dns 
se vuoi mantenere telegestione dovresti modificarli per la lan

**Comment by dga4130-renato** [comment]
per scrupolo riprovo.. nulla non va.

**Comment by dga4130-renato** [comment]
per telefono uso l'applicazione sul cellulare di tim, non l'ho mai attaccato, quindi non se se attaccandolo alla porta dietro funziona o no

**Comment by dga4130-renato** [comment]
Ok provo domani appena ho un attimo libero
