### ISSUE TITLE
xDSL Card Enabled on Ethernet

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#216]
Device Model: TG800, GUI Version [ 8.8.13 ]

Description of problem: xDSL Card Enabled on Ethernet - should be disabled.

Note: https://github.com/Ansuel/tch-nginx-gui/issues/118#issuecomment-422966786

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/pull/214
should fix it.. at least when you switch broadband mode

**Comment by FrancYescO** [comment]
To hide these tab/buttons you have to disable xDSL

**Comment by flywire** [comment]
@FrancYescO - How? Broadband, Advanced, Switch connection mode then switch back to Ethernet again makes no difference.

BTW User shouldn't have to disable something system knows doesn't exist.

**Comment by FrancYescO** [comment]
it switch back to eth cause of wansensing enabled.. if xdsl is not present in the modem these buttons should be correctly hidden, if is present and enabled these are here.

**Comment by flywire** [comment]
Where is wansensing turned off (modem supports xdsl)?

**Comment by FrancYescO** [comment]
the only place to disable wansensing is the wizard (and idk if is working)... probably deattaching the eth cable will easily allow you to switch to xdsl in broadband to disable

**Comment by flywire** [comment]
> place to disable wansensing is the wizard

No, this totally screwed installation:

![guibridgemodem](https://user-images.githubusercontent.com/11288701/46563663-24608880-c946-11e8-8755-74b030e1679c.png)

I re-flashed modem. Is there better way to recover from this?
