### ISSUE TITLE
Diagnostics Card DSL Icons Displayed and Activated with Ethernet

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#218]
Device Model: TG800, GUI Version [ 8.8.13 ]

Description of problem: DSL icons displayed with Ethernet Connection and can be activated. Note there are no tabs for two Diagnostics DSL tabs.

How to reproduce (if possible): Select Diagnostics card, one of the first two (DSL) Icons

Note: #118 (comment)

**Comment by FrancYescO** [comment]
You should be now able to fully disable xDSL (after switching in broadband modal) to hide these icons/tabs
