### ISSUE TITLE
Internal server error in traffic monitor tab

### ISSUE THREAD

**Issue by Diavulrus** [Ansuel/tch-nginx-gui#219]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: AGTEF
Gui Version: 8.8.13

Description of problem: opening the traffic monitor tab under local network the internal server error displays

How to reproduce (if possible): enter the gui, open the cards tab, go to local network, open the traffic monitor tab

Media/Photos (if possible):
![cattura](https://user-images.githubusercontent.com/32335829/46081461-d8bb1b80-c19c-11e8-97f4-9a64d32e1fc0.PNG)

Log of the error (obtained via logread):
`Wed Sep 26 14:54:22 2018 daemon.err nginx: 2018/09/26 14:54:21 [error] 5081#0: *6 lua entry thread aborted: runtime error: [string "/modals/traffic-monitor.lp"]:117: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        [string "/modals/traffic-monitor.lp"]:117: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.50.0.200, server: localhost, request: "GET /modals/traffWed Sep 26 14:54:38 2018 daemon.err nginx: 2018/09/26 14:54:37 [error] 5081#0: *7 lua entry thread aborted: runtime error: [string "/modals/traffic-monitor.lp"]:117: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        [string "/modals/traffic-monitor.lp"]:117: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.50.0.200, server: localhost, request: "GET /modals/traffWed Sep 26 14:55:23 2018 kern.warn kernel: [  327.066000] dosprotect rpfilter drop IN=br-lan OUT= MAC= SRC=192.50.0.1 DST=192.50.0.255 LEN=238 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=UDP SPT=138 DPT=138 LEN=218 MARK=0x8000`

**Comment by nclmrc** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/113

**Comment by Ansuel** [comment]
fixed
