### ISSUE TITLE
Tiles are a little small...

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#22]
I have a hard time seeing the most important info on the startup tiles, e.g., not all of the 4 WiFis are shown and more... I have done a small mod to gw.css, so it looks like this:

![grafik](https://user-images.githubusercontent.com/17402664/38257547-b4ab6522-3760-11e8-851d-6f5a64532ce1.png)

[Here is the commit](https://github.com/meyergru/tch-nginx-gui/commit/99c8e20f85f4d9e224081a4ef196d711052fde2e)

BTW: I am in the process of translating the GUI to German. The change is completely modular, only a new de-de folder under lang.

**Comment by Ansuel** [comment]
Feel free to push pull request 
If you want you can add custom CSS file to add extended card.

**Comment by meyergru** [comment]
Alas, I did a branch that already has more than only this inside. But you can diff my linked commit.

**Comment by meyergru** [comment]
I just found that there occurs a jump in tile widths between 1300 and 1400px. The reason is that the default width of span3 is 220px (from gw.css), but there are other definitions in responsive.css.

The defined intervals there are:

0-767
768-979
1200-1300
>1400

The interval 980-1199 is covered by the default in gw.css, but 1301-1399 is handled just the same! So, the width is a mere 166px for that interval.

Thus, line 519 of responsive.css should read:

```
@media screen and (min-width: 1200px) and (max-width:1399px) {
```

**Comment by Ansuel** [comment]
feel free to push a corrected one :)

**Comment by meyergru** [comment]
Did just that!
