### ISSUE TITLE
xDSL cards show weired value

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#220]
Device Model: 789vac v2
Gui Version: 8.8.13

xDSL cards show weired value

How to reproduce (if possible): connect vdsl than disconnect cable

![image](https://user-images.githubusercontent.com/4574593/46095757-981fca00-c1bd-11e8-80b8-e3df45f36b26.png)
![image](https://user-images.githubusercontent.com/4574593/46095819-bf769700-c1bd-11e8-96ba-c530fec31a99.png)

**Comment by Ansuel** [comment]
output di questo xdslctl info --vendor

**Comment by Ansuel** [comment]
fixed
