### ISSUE TITLE
Last gui

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#221]

**Comment by giulio63** [comment]
con la gui 8.8.14 non fa entrare nella tab "Banda Larga" e "Stato Gui"

**Comment by giulio63** [comment]
ti ringrazio :-) intanto ho rimesso la 8.8.13 che mi ero salvato e tutto è tornato normale

**Comment by nclmrc** [comment]
`Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 48c7d4b9b7268b2b43afe2b541654df3
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: 66f1cde9296521eb6e0cb5d43116fe4                                                                                                                                                             4
Upgrade Script: Stable version found: 8.07.02
Upgrade Script: Dev version found: 8.08.15
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same n                                                                                                                                                             ame) at line 138, byte 20
Upgrade Script: Upgrade Done
root@DGA4132:~#
`

**Comment by nclmrc** [comment]
```

Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 48c7d4b9b7268b2b43afe2b541654df3
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: 66f1cde9296521eb6e0cb5d43116fe44
Upgrade Script: Stable version found: 8.07.02
Upgrade Script: Dev version found: 8.08.15
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
uci: Parse error (section of different type overwrites prior section with same name) at line 138, byte 20
Upgrade Script: Upgrade Done
root@DGA4132:~#
```

**Comment by nclmrc** [comment]
non mi è possibile accedere a cards

**Comment by FrancYescO** [comment]
cards sulla 8.8.15 penso sia rotto su tutti non-DGA ma comunque dovrebbe essere risolto tutto quello citato qui (a parte i parse error dello script che non ho capito da dove saltano fuori) nel PR https://github.com/Ansuel/tch-nginx-gui/pull/222

che intendi con la seconda connessione pppoe no sta salendo? dove la tieni configurata?

**Comment by nclmrc** [comment]
ho una seconda connessione pppoe in network, prima funzionava tutto regolarmente

**Comment by nclmrc** [comment]
Qualcuno mi può passare la 8.8.13

**Comment by giulio63** [comment]
io ce l'ho la 8.8.13 da installare manualmente e sembra funzionare correttamente.
mentre con la 8.8.15 con TimHub (DGA4132) non funzionano le tab "Banda Larga" e "Stato Gui" e funziona correttamente lo "switch"  Cards-Stats . ma si sa cosa dovevano aggiungere o correggere le versioni successive alla 8.8.13 ? non riesce ad avere un change log completo ed aggiornato

**Comment by nclmrc** [comment]
Puoi caricarla qua grazie

Il Gio 27 Set 2018, 18:56 giulio63 <notifications@github.com> ha scritto:

**Comment by giulio63** [comment]
Gui versione 8.8.13

[GUI_dev_8.8.13.tar.bz2.zip](https://github.com/Ansuel/tch-nginx-gui/files/2425129/GUI_dev_8.8.13.tar.bz2.zip)

**Comment by FrancYescO** [comment]
Basta che guardi i commit.
________________________________

**Comment by nclmrc** [comment]
Tornando indietro non ho risolto,  penso si sia rotto qualcosa.

**Comment by giulio63** [comment]
si pero' credo che il changelog della Gui sia quello che gli utenti controllano di più per seguire gli aggiornamenti, il quale però non viene aggiornato dettagliatamente. lo chiedevo solo per cercare di allineare le informazioni, ma nessun problema.

**Comment by FrancYescO** [comment]
Senza dettagli o log si può fare poco
________________________________

**Comment by giulio63** [comment]
beh allora è di sicuro qualcosa di piu' serio. io sto facendo avanti ed indietro per confrontare alcune cose ma nessun altro problema se non quelli già segnalati

**Comment by Ansuel** [comment]
un changelog ad ogni dev version è un pò overkill come cosa...

la pagina changelog.lp viene aggiornata quando si va avanti di major da 8.7 a 8.8 per esempio (non in questo caso perchè si è dovuti passare a 8.8 perchè si era arrivati a 8.7.99 )

**Comment by nclmrc** [comment]
@Ansuel dimmi se hai bisogno di log per capire cosa è successo?

**Comment by nclmrc** [comment]
Se hai caricato qualcosa c'è stato un problema sul trasferimento.

**Comment by FrancYescO** [comment]
@nclmrc credo il tuo file network si sia completamente rotto

**Comment by nclmrc** [comment]
Ho ripristinato uno di qualche giorno fa ora va meglio. Si deve essere corrotto in qualche aggiornamento.

**Comment by nclmrc** [comment]
Come mai nell'ultima gui 8.8.16 non c'è più il tema nuovo?

**Comment by FrancYescO** [comment]
Intendi la pagina stats? Non riesci ad accederci nemmeno cliccando in alto a destra?
________________________________

**Comment by nclmrc** [comment]
Intendo la skin che era stata aggiunta nelle ultime beta

Il Gio 27 Set 2018, 22:12 Francesco M <notifications@github.com> ha scritto:

**Comment by FrancYescO** [comment]
Continuo a non capire a quale ti riferisci .. Telstra?
________________________________

**Comment by nclmrc** [comment]
Le skin come quelle fritz viola viola verde blu.

Il Gio 27 Set 2018, 22:28 Francesco M <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
bhe sono scomparse?

**Comment by nclmrc** [comment]
L'ultima che avevi aggiunta e mi piaceva si è scomparsa

Il Gio 27 Set 2018, 22:42 Ansuel Smith <notifications@github.com> ha
scritto:
