### ISSUE TITLE
No “Log Viewer” tab in “Diagnostics” modal

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#226]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having! - haha I wrote that :)

Device Model: tg799
Gui Version:
8.8.20

Description of problem:

No “Logviewer” tab in diagnostics.

Media/Photos (if possible):
![fcae83f2-f22e-4d0b-8aed-93bd2ea83252](https://user-images.githubusercontent.com/42062334/46181203-fc927480-c2f6-11e8-8097-e9807a47b2b4.jpeg)
![f0f70345-48cd-42b7-aef3-62d94a0004ef](https://user-images.githubusercontent.com/42062334/46181204-fc927480-c2f6-11e8-934e-5518fe106692.png)

**Comment by Ansuel** [comment]
Log view are in user card
You are right we should add something to highlight it

**Comment by kevdagoat** [comment]
Ahh ok.
