### ISSUE TITLE
Traffic monitor

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#227]
Allego schermata del traffico errata:
![screenshot_20180928-071144_chrome](https://user-images.githubusercontent.com/38593316/46189298-3b6ffc80-c2ee-11e8-983f-96c05588f97e.jpg)

**Comment by Ansuel** [comment]
can you test latest version ?

**Comment by nclmrc** [comment]
![screenshot_20180929-081029_chrome](https://user-images.githubusercontent.com/38593316/46241810-50689080-c3bf-11e8-9efe-76397091d26d.jpg)
Non capisco cosa siano quei numeri sotto i grafici.  Millisecondi?

**Comment by nclmrc** [comment]
@Ansuel sembrerebbe sistemato.  Ma come mai alle 2 riparte il grafico da sinistra. Non sarebbe meglio mostrare le ultime 24 ore, con a destra l'ora attuale?

**Comment by Ansuel** [comment]
in pratica parte da mezzanotte + fuso orario + eventuale ora legale quindi dalle 2

**Comment by nclmrc** [comment]
Capito l'unica cosa è che mi viene sempre da guardare all estrema destra per vedere l'ora attuale, se ci fosse verso senza sbatterci la testa.
