### ISSUE TITLE
xDSL Stats Card crashing stats.lp

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#230]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: tg799
Gui Version: 8.8.20

Description of problem:
See title.

Media/Photos (if possible):
![032c49cb-2e0f-4fe8-8bf3-d6c58ed19c94](https://user-images.githubusercontent.com/42062334/46237362-9bca7100-c3b6-11e8-8773-09c64bd0a6ab.jpeg)
![da8dca84-53d4-420e-92ac-eba4e52706cc](https://user-images.githubusercontent.com/42062334/46237363-9bca7100-c3b6-11e8-94ca-133b68374b23.jpeg)

**Comment by kevdagoat** [comment]
> Excluding the xdsl stuff that should be an easy fix.
> 
> Seems my solution of force adding a wanptm0 (and probably also the eth) interface in the rootdevice script was not good enought, we should find a way to find the correct interface name if already added (iterate for all devices in lua and check for ifname) and only add if not found
> something with the needed ifname (in rootdevice script)

Let’s just revert it for now until we develop a better solution

**Comment by Ansuel** [comment]
anyway transformer issue can be ignored as they don't create lots of problems

**Comment by Ansuel** [comment]
any update on this?

**Comment by FrancYescO** [comment]
"Status Down" but the card is shown, is this what we want?
![image](https://user-images.githubusercontent.com/4574593/46263046-3b4c4880-c50a-11e8-9a7c-52cf7f4af1c5.png)

**Comment by kevdagoat** [comment]
![41a1e500-3931-4165-a8eb-b491a2882505](https://user-images.githubusercontent.com/42062334/46263887-11197b80-c548-11e8-810d-4bb42c79d384.jpeg)
Still there

**Comment by Ansuel** [comment]
i need the log pls

**Comment by kevdagoat** [comment]
Updated and have no GUI :( “500 Internal Server Error”
Log:
` Mon Oct  1 10:10:32 2018 daemon.err nginx: 2018/10/01 10:10:32 [error] 10669#0: *1 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 10.0.0.13, server: localhost, request: "GET /cards.lp HTTP/1.1", host: "10.0.0.138"
Mon Oct  1 10:10:33 2018 daemon.err nginx: 2018/10/01 10:10:33 [error] 10669#0: *2 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 10.0.0.13, server: localhost, request: "GET /cards.lp HTTP/1.1", host: "10.0.0.138"
Mon Oct  1 10:10:34 2018 daemon.err nginx: 2018/10/01 10:10:34 [error] 10669#0: *3 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 10.0.0.13, server: localhost, request: "GET /cards.lp HTTP/1.1", host: "10.0.0.138"
Mon Oct  1 10:10:34 2018 daemon.err nginx: 2018/10/01 10:10:34 [error] 10669#0: *4 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 10.0.0.13, server: localhost, request: "GET /cards.lp HTTP/1.1", host: "10.0.0.138"
Mon Oct  1 10:10:35 2018 daemon.err nginx: 2018/10/01 10:10:35 [error] 10669#0: *5 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 10.0.0.13, server: localhost, request: "GET /cards.lp HTTP/1.1", host: "10.0.0.138"
Mon Oct  1 10:10:49 2018 daemon.err nginx: 2018/10/01 10:10:49 [error] 10669#0: *6 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 10.0.0.13, server: localhost, request: "GET / HTTP/1.1", host: "10.0.0.138"
ould not initialize ssl connection (18)
Mon Oct  1 10:11:20 2018 user.debug mmpbxd[1531]: [SIPDEV_APN]    :I: resetAPNConnection:126 - apn connection started apn mode 0 ret=13. `
