### ISSUE TITLE
Remember that modems in bridge mode do not have internet access...

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#24]
I saw something in your last commit that I noticed before:

You use the forum repository in order to load adsl_phy.bin for a specific driver version.

That is not possible for a modem in bridge mode. Maybe you should include all the drivers in the image.

A similar problem exists for the upgrade check for the GUI - there is even a check in crontab, which I disabled manually, because I always get a hint that an upgrade is available, even if that cannot be checked at all.

**Comment by Ansuel** [comment]
Include all the adsl_phy in the image would grow the gui tar a lot... If someone is in bridge mode then it should change it manually... (Not that hard actually) 
For the check, yes I should include a something to check if the modem has connection...

**Comment by Ansuel** [comment]
i added some check in new dev ;)
