### ISSUE TITLE
IP Extras >> Dos Protect Option not working [8.7.2-stable]

### ISSUE THREAD

**Issue by Kherby** [Ansuel/tch-nginx-gui#242]
DGA4130/4132 @ Bridgde Mode
GUI Version: 8.7.2-stable

The Dos Protect Option under IP Extras is not working/ has no effect. 
If i manually go the /etc/config/dosprotect and set **option enabled '0' option rpfilter '0'** i can see the right state at the GUI.
Not sure if it's only related to Bridge mode but i guess it will be the same in Router mode.

**Comment by BreakSecurity** [comment]
Reopen. it still don't apply... GUI version: 8.8.47

**Comment by BreakSecurity** [comment]
Don't work. GUI version: 8.8.55

**Comment by FrancYescO** [comment]
Confirming not working on 8.8.55 TG789

**Comment by Kherby** [comment]
The option seems to work for me with 8.8.55 (DGA4130 in Bridge Mode).
I've just tested it by enabling and disabling the Dos Protect (+rp filter) via GUI and the correct values will be set and the GUI shows the right status.
I'm using the new Red/Dark skin, maybe this makes a difference...

**Comment by Ansuel** [comment]
@FrancYescO 
transformer-cli get uci.dosprotect.

**Comment by FrancYescO** [comment]
```
root@dsldevice:~# transformer-cli get uci.dosprotect.
uci.dosprotect.globals.enabled [string] =
uci.dosprotect.globals.rpfilter [string] =
```
When saving from modal it seems a little too fast

**Comment by Ansuel** [comment]
any update on this?

**Comment by FrancYescO** [comment]
nothing changed turning on, save, refresh the page and dos protection is off

**Comment by FrancYescO** [comment]
We found that the issue is that the dosprotect config file is missing under /etc/config we must check if this func is supported on 789
________________________________

**Comment by kevdagoat** [comment]
Also missing on TG799vac
