### ISSUE TITLE
GUI Skin color

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#245]
i see in Extra System there's the option random color for the GUI. Is possible add the possibility to choose the color directly with a selection.
Thanks

**Comment by FrancYescO** [comment]
ma é il colore di cosa? a me sembra non aver alcun effetto quell'opzione

**Comment by Ansuel** [comment]
tema dark-red quell'opzione attivata e guarda che magia !

**Comment by FrancYescO** [comment]
tutto d'un tratto mi sento fatto di LSD

**Comment by FrancYescO** [comment]
Comunque la questione di scegliere il colore potrebbe aiutare anche ad ottimizzare lo spazio occupato dalle skin (relativamente poco ma vabbhé) alla fine le skin si ridurrebbero a due (fritz e stock) con magari la possibilitá di scegliere il colore primario, secondario e terziario (che é alla fine quello che attualmente le differenzia) ... si eviterebbe anche di dover replicare le modifiche su tutti i css in caso di fix da fare

**Comment by nclmrc** [comment]
Secondo me è la soluzione migliore. Anche passando direttamente i codici
del colore.

Il Mar 2 Ott 2018, 14:18 Francesco M <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
andrebbero reworkati i temi per fare una cosa del genere... Per ora stiamo finendo di mettere apposto le ultime cose perchè la versione stabile è davvero troppo vecchia. Appena verrà rilasciata la stabile mi metterò al lavoro sul rework dei temi
