### ISSUE TITLE
nginx SSL Certificate Error on Startup

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#247]
nginx will not start unless I remove the SSL config in the config file.

nginx: [emerg] BIO_new_file("/etc/nginx/server.crt") failed (SSL: error:02001002:lib(2):func(1):reason(2):fopen('/etc/nginx/server.crt','r') error:2006D080:lib(32):func(109):reason(128))

**Comment by FrancYescO** [comment]
gui version? modem? when this happened?

**Comment by kevdagoat** [comment]
Dont know :)
GUI still not working
(TG799)

**Comment by FrancYescO** [comment]
what you mean with gui still not working? you said that removing the fiel will fix..

**Comment by kevdagoat** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/240

**Comment by FrancYescO** [comment]
@kevdagoat i think this issue is strictly connected to some wrong configuration or something corrupted on your device (probably during some try to get telstra gui working) ... i suggest you to do a factory reset and start from scratch as is pretty hard to understand what's wrong

**Comment by kevdagoat** [comment]
Would have done that in the first place but it is my main modem that provides:
- My phone line
- My Internet 
- My servers with network access

I can wait.

**Comment by Ansuel** [comment]
can you try to restore nginx bin ? 

cp /rom/usr/sbin/nginx /usr/sbin/

and restart nginx?

**Comment by kevdagoat** [comment]
Ok. Will try.

**Comment by kevdagoat** [comment]
Nope:
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/nginx/server.key") failed (SSL: error:0906D06C:lib(9):func(109):reason(108):Expecting: ANY PRIVATE KEY error:140B0009:lib(20):func(176):reason(9))

**Comment by Ansuel** [comment]
ummm it looks like you have corrupted key... try remove it and restart the modem

**Comment by kevdagoat** [comment]
By now it just needs a factory reset :(
