### ISSUE TITLE
Strings cutted in header of cards when not needed

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#250]
![image](https://user-images.githubusercontent.com/4574593/46446218-5ec9fa00-c77b-11e8-8ec9-c8f92dd08852.png)
when mouse hover:
![image](https://user-images.githubusercontent.com/4574593/46446239-7e612280-c77b-11e8-8f75-ddbabec40ab4.png)

**Comment by Ansuel** [comment]
this should be fine tuned... :( for now i will disable for stats card
