### ISSUE TITLE
opkg update > distfeeds.conf (invalid package source)

### ISSUE THREAD

**Issue by Kherby** [Ansuel/tch-nginx-gui#251]
Device Model: DGA4130
Gui Version: 8.8.47-dev

By running opkg update i realised that there is a invalid package source in the distfeeds.conf located at /etc/opkg/.

Console output:
```
root@DGA4130:~# opkg update
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_base
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_packages
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_luci
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_routing
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_telephony
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_management
Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz, wget returned 8.
```
Anyway I wonder if the the source should be replaced with: https://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/ ?
Should it be completly removed from the distfeeds config? Or is it just a old placeholder?

**Comment by kevdagoat** [comment]
It does not need to be changed. That list is already present.
Also this is not a GUI issue 😊

Sent from Mail for Windows 10

From: Kherby
Sent: Thursday, October 4, 2018 2:56 PM
To: Ansuel/tch-nginx-gui
Cc: Subscribed
Subject: [Ansuel/tch-nginx-gui] opkg update > distfeeds.conf (invalid packagesource) (#251)

Device Model: DGA4130
Gui Version: 8.8.47-dev
By running opkg update i realised that there is a invalid package source in the distfeeds.conf located at /etc/opkg/.
Console output:
root@DGA4130:~# opkg update
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_base
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_packages
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_luci
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_routing
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_telephony
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_management
Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTK/packages/Packages.gz, wget returned 8.
Anyway I wonder if the the source should be replaced with: https://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/ ?
Should it be completly removed from the distfeeds config? Or is it just a old placeholder?

**Comment by FrancYescO** [comment]
The last source is a default placeholder (that points to an invalid repo) also do not consider the repository.ilpuntotecnico.com safe, as an opkg upgrade will break the modem, is just the default owrt repo recompiled adding -tch architecture.

**Comment by Ansuel** [comment]
Actually the forum repo is based on the source provided from technicolor
Upgrade critical package on openrt is always wrong (for example upgrade
libc would brake brick every openwrt modem)


Il Gio 4 Ott 2018, 09:53 Francesco M <notifications@github.com> ha scritto:

**Comment by Kherby** [comment]
Allrighty, thanks for the information... 
I wouldn't "upgrade" any packages anyway as it doesn't make much sense and might break some proprietary broadcom stuff.
