### ISSUE TITLE
Ports Card ports order and WiFi always showing "Active"

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#253]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: TG799vac
Gui Version: 8.8.55 STABLE

Description of problem:
Ports are not in order and my modems wifi is not online at the moment

Media/Photos (if possible):
![image](https://user-images.githubusercontent.com/42062334/46527255-41a04300-c8c3-11e8-977b-61e3e2c0384f.png)

Will create a pull request if i find a fix

**Comment by Ansuel** [comment]
are you sure the wifi is not online ?  check in the wifi tab

about the order i'm checking it

**Comment by Ansuel** [comment]
with latest version the order should be right

**Comment by kevdagoat** [comment]
It is definitely off!

**Comment by Ansuel** [comment]
post a screenshot

**Comment by Ansuel** [comment]
any update ?

**Comment by flywire** [comment]
TG799 GUI Version [ 8.8.67 ]
Ports ordered alphabetically and wifi status updated.

**Comment by kevdagoat** [comment]
Is fixed now
