### ISSUE TITLE
Question: Card Backgound Mapping

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#254]
How do I change the images on the cards?
I know this line changes it but how do I work out the number of the glyphicon?

`<div class="login_bg" data-bg-text="&#xf212;">\
`

**Comment by Ansuel** [comment]
Font awesome icon take hex code an replace for example search f212

Il Ven 5 Ott 2018, 11:45 Kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
Ahh ok, thanks for that.

Sent from Mail for Windows 10
