### ISSUE TITLE
WAN Traffic Stats

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#257]
Mi sono accorto che dopo un riavvio WAN Traffic su Stats non riparte, occore fare un "upgradegui" per farlo ripartire.

**Comment by nclmrc** [comment]
inviato log x email

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/46537286-2e847780-c8b1-11e8-8c4e-da254bc45c25.png)

**Comment by Ansuel** [comment]
tipo di connessione? prima funzionava?

**Comment by nclmrc** [comment]
Adsl. Nemmeno prima al primo avvio. Mi ero accorto ci metteva un po ma
pensavo fosse normale. Dopo un upgradegui parte. Andrà messo qualche
comando enable all avvio o eseguire uno script allo via.

Il Ven 5 Ott 2018, 17:05 Ansuel Smith <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
mostra il traffico immediato sulla wan quanto stai usando la linea in teoria...

**Comment by nclmrc** [comment]
Si ma dovrebbe essere una media. Fino alla scorsa versione era cosi. Tipo
il traffico ogni tot secondi

Il Ven 5 Ott 2018, 19:49 Ansuel Smith <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
traffic monitor te lo da di un giorno questo si aggiorna ogni 10 secondi ed è in tempo reale sono due cose differenti

**Comment by nclmrc** [comment]
Si ma se vedi il grafico cresce sempre

Il Ven 5 Ott 2018, 19:51 Ansuel Smith <notifications@github.com> ha scritto:

**Comment by nclmrc** [comment]
Sinceramente prima il grafico usciva corretto

**Comment by nclmrc** [comment]
@Ansuel se devo fare delle prove dimmi pure

**Comment by nclmrc** [comment]
Prima mi ricordo divideva il traffico degli ultimi 10 secondi per 10. Ora secondo me non fa la differenza per ricavare il traffico degli ultimi 10 secondi

**Comment by nclmrc** [comment]
Per quanto riguarda lo script in che senso non riesce ad individuare la connessione predefinita?

**Comment by Ansuel** [comment]
fai questo comando

transformer-cli get rpc.network.interface.@wan.ifname

**Comment by Ansuel** [comment]
Fixed in latest dev, will push in stable when ecoled will be fixed
