### ISSUE TITLE
Modem at reboot always set to 'pppoe' even if I set 'dhcp' (UNO fw 17.2)

### ISSUE THREAD

**Issue by BreakSecurity** [Ansuel/tch-nginx-gui#258]
Device Model: TG789vac V2
Gui Version: 8.8.55 STABLE

Description of problem:

in network file config option:
	option ifname 'ptm0'
	option proto 'dhcp'
at every reboot become:
	option ifname 'vlan_wan'
	option proto 'pppoe'

How to reproduce (if possible):
 	I have Fastweb VDSL so DHCP mode is requested to obtain IP

**Comment by FrancYescO** [comment]
firmware?

**Comment by BreakSecurity** [comment]
17.2

**Comment by FrancYescO** [comment]
UNO? it seems an issue with wansensing script of this firmware

**Comment by BreakSecurity** [comment]
yes

only way to avoid this is:
#Put your custom commands here that should be executed once
#the system init finished. By default this file does nothing.

#overwrite the configuration file "*" with the one with your settings "*_2" at every startup
#sovrascrive il file di configurazione "*" con quello che ha le vostre impostazioni "*_2" ad ogni avvio
cp -f /etc/config/*_2 /etc/config/*
example:
cp -f /etc/config/network_2 /etc/config/network
cp -f /etc/config/cwmpd_2 /etc/config/cwmpd

#reload affected modules
#ricarica i moduli interessati
/etc/init.d/* reload
example:
/etc/init.d/network reload
/etc/init.d/cwmpd reload

exit 0

but a fix would be great

**Comment by FrancYescO** [comment]
if you want to try these commands should clean the wansensing script of UNO from all forced values
```
sed -i '/[cC][wW][mM][pP][dD]/d' /etc/wansensing/L2EntryExit.lua
sed -i '/mtu= "1500"/{N;d}' /etc/wansensing/L2EntryExit.lua
sed -i '/[mM][tT][uU]/d' /etc/wansensing/L2EntryExit.lua
sed -i '/vlan = default_vlan/{N;d}' /etc/wansensing/L2EntryExit.lua
sed -i '/vci/d' /etc/wansensing/L2EntryExit.lua
sed -i '/vpi/d' /etc/wansensing/L2EntryExit.lua
sed -i '/enc/d' /etc/wansensing/L2EntryExit.lua
sed -i '/ulp/d' /etc/wansensing/L2EntryExit.lua
sed -i '/"proto", "pppoa"/d' /etc/wansensing/L2EntryExit.lua
sed -i '/"proto", "pppoe"/d' /etc/wansensing/L2EntryExit.lua
```

**Comment by FrancYescO** [comment]
Have you tested it?
________________________________

**Comment by BreakSecurity** [comment]
Sadly I don't have this modem at the moment i was thinking the commands were tested.

**Comment by Ansuel** [comment]
i added this command to latest gui... this can be closed

**Comment by FrancYescO** [comment]
@BreakSecurity could you share a full network file configured for for Fastweb IT VDSL

**Comment by BreakSecurity** [comment]
@FrancYescO here is it:
```
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'auto'
        option default_ps '0'

config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'
        option force_link '0'
        option igmp_snooping '1'
        option ipv6 '0'
        option ip6assign '64'
        list ifname 'vlan_eth0'
        list ifname 'vlan_eth1'
        list ifname 'vlan_eth2'
        list ifname 'vlan_eth3'
        list pppoerelay ''

config device 'eth0'
        option mtu '1500'
        option name 'eth0'

config device 'eth1'
        option mtu '1500'
        option name 'eth1'

config device 'eth2'
        option mtu '1500'
        option name 'eth2'

config device 'eth3'
        option mtu '1500'
        option name 'eth3'

config device 'vlan_eth0'
        option type '8021q'
        option ifname 'eth0'
        option name 'vlan_eth0'
        option mtu '1500'
        option vid '1'

config device 'vlan_eth1'
        option type '8021q'
        option ifname 'eth1'
        option name 'vlan_eth1'
        option mtu '1500'
        option vid '1'

config device 'vlan_eth2'
        option type '8021q'
        option ifname 'eth2'
        option name 'vlan_eth2'
        option mtu '1500'
        option vid '1'

config device 'vlan_eth3'
        option type '8021q'
        option ifname 'eth3'
        option name 'vlan_eth3'
        option mtu '1500'
        option vid '1'

config switch 'bcmsw_int'
        option reset '1'
        option type 'bcmsw'
        option qosimppauseenable '0'
        option jumbo '1'
        option unit '0'
        option enable_vlan '0'

config switch 'bcmsw_ext'
        option reset '1'
        option type 'bcmsw'
        option qosimppauseenable '0'
        option unit '1'
        option enable_vlan '1'
        option jumbo '1'

config switch_vlan 'lan_switch'
        option device 'bcmsw_ext'
        option vlan '1'
        option ports '1* 2* 3* 4* 8t'

config interface 'wan'
        option vendorid 'Technicolor'
        option authfail '0'
        option mtu '1500'
        option ipv6 '0'
        option release '1'
        option iface6rd '0'
        option reqopts '1 3 6 43 51 58 59'
        option neighgcstaletime '2400'
        option metric '1'
        option neighreachabletime '1200000'
        option auto '1'
        option ifname 'ptm0'
        list dns '1.1.1.1'
        list dns '1.0.0.1'
        list dns '8.8.8.8'
        option proto 'dhcp'

config interface 'vdsl_check'
        option proto 'pppoe'
        option ifname 'ptm0'
        option keepalive '5,10'
        option auto '0'
        option reqopts '1 3 6 15 33 42 51 121 249'
        option vendorid 'Technicolor'
        option graceful_restart '1'
        option authfail '0'
        option mtu '1500'
        option ipv6 '0'
        option release '1'
        option iface6rd '0'

config interface 'bt_iptv'
        option ifname 'vlan_wan'
        option auto '1'
        option proto 'static'
        option ipaddr '169.254.10.1'
        option netmask '255.255.255.255'

config device 'eth4'
        option mtu '1500'
        option name 'eth4'

config device 'ptm0'
        option mtu '1508'
        option name 'ptm0'

config device 'vlan_wan'
        option type '8021q'
        option ifname 'ptm0'
        option mtu '1508'
        option name 'vlan_wan'
        option vid '101'

config interface 'wwan'
        option auto '1'
        option metric '10'
        option proto 'mobiled'
        option session_id '0'
        option profile '1'

config interface 'wan6'
        option ifname '@wan'
        option proto 'dhcpv6'
        option reqopts '12 21 22 23 24 25 31 56 64 67 82 83'
        option noslaaconly '1'
        option iface_464xlat '0'

config interface 'guest'
        option proto 'static'
        option type 'bridge'
        option ipv6 '0'
        option ip6hint '1'
        option netmask '255.255.255.128'
        option ipaddr '192.168.168.126'
        list ifname 'wl0_1'
        list ifname 'wl1_1'
        option force_link '0'

config config 'config'
        option wan_mode 'dhcp'

config interface 'ipoe'
        option proto 'dhcp'
        option metric '1'
        option reqopts '1 3 6 43 51 58 59'
        option release '1'
        option neighreachabletime '1200000'
        option neighgcstaletime '2400'
        option ipv6 '1'

config device 'waneth4'
        option enabled '1'
        option type '8021q'
        option name 'waneth4'
        option vid '835'

config device 'wanptm0'
        option enabled '1'
        option type '8021q'
        option name 'wanptm0'
        option vid '835'
        option ifname 'ptm0'
```

**Comment by FrancYescO** [comment]
@BreakSecurity so you are connecting with no VLAN ID (or is set to 101?)

**Comment by BreakSecurity** [comment]
option vid '835'

**Comment by FrancYescO** [comment]
@BreakSecurity this is in set in the `wanptm0` section but in the `wan` section you are using `ptm0` as interface... could you give me also an `ifconfig` execution from ssh?

PS. are you in VULA TIM or MAKE?

**Comment by BreakSecurity** [comment]
bcmsw     Link encap:Ethernet  HWaddr 
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:892140 errors:0 dropped:5 overruns:0 frame:0
          TX packets:791642 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:157764635 (150.4 MiB)  TX bytes:486542161 (464.0 MiB)
          Base address:0xda00

br-guest  Link encap:Ethernet  HWaddr 
          inet addr:192.168.168.126  Bcast:192.168.168.127  Mask:255.255.255.128
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

br-lan    Link encap:Ethernet  HWaddr 
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:4000823 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9979667 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:433114482 (413.0 MiB)  TX bytes:732649807 (698.7 MiB)

eth0      Link encap:Ethernet  HWaddr 
          inet6 addr: fe80::1213:31ff:fea1:67bc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4011590 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9975406 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:506683629 (483.2 MiB)  TX bytes:866457943 (826.3 MiB)


eth1      Link encap:Ethernet  HWaddr 
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


eth2      Link encap:Ethernet  HWaddr 
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


eth3      Link encap:Ethernet  HWaddr 
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:70 errors:0 dropped:0 overruns:0 frame:0
          TX packets:70 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:6000 (5.8 KiB)  TX bytes:6000 (5.8 KiB)

ptm0      Link encap:Ethernet  HWaddr 10:13:31:A1:67:BC
          inet addr:xxx.xxx.xxx.xxx  Bcast:xxx.xxx.xxx.xxx  Mask:255.255.248.0
          inet6 addr: fe80::1213:31ff:fea1:67bc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1508  Metric:1
          RX packets:9959612 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3996609 errors:0 dropped:991 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:765568745 (730.1 MiB)  TX bytes:512954438 (489.1 MiB)

vlan_eth0 Link encap:Ethernet  HWaddr 
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:124674 errors:0 dropped:0 overruns:0 frame:0
          TX packets:115039 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:11515931 (10.9 MiB)  TX bytes:22368591 (21.3 MiB)

vlan_eth1 Link encap:Ethernet  HWaddr 
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
10:13:31:A1:67:BC
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vlan_eth3 Link encap:Ethernet  HWaddr 
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vlan_wan  Link encap:Ethernet  HWaddr 
          inet addr:169.254.10.1  Bcast:255.255.255.255  Mask:255.255.255.255
          inet6 addr: fe80::1213:31ff:fea1:67bc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1508  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:258 (258.0 B)

wl0_1     Link encap:Ethernet  HWaddr 
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:98369
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wl1_1     Link encap:Ethernet  HWaddr 
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:10440
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
