### ISSUE TITLE
Good work!

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#26]
@SeproDE I'm watching what you are doing with the fritz_style... love it... only problem.. the first screen is not so great as it's empty... do you know some way to relocate the info in the card to the right?

**Comment by SeproDE** [comment]
Not so bad for a first try.
![image](https://user-images.githubusercontent.com/4618135/38709740-ef575934-3ebc-11e8-8365-bb93357f3a9a.png)

Over the coming days I will try making the style work better on different screen sizes.

**Comment by Ansuel** [comment]
You are so good
We just need to correct the logo with technicolor on white... Fell free to push a PR when you have a good skin ;)
