### ISSUE TITLE
Upgrade available! Version: 8.8.56 STABLE

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#260]
Device Model: TG800, GUI Version [ 8.8.56 ] with Telstra enabled.

Description of problem: **Upgrade message never cleared after upgrade.**
```
root@mygateway:~# uci show env.var.outdated_ver
env.var.outdated_ver='1'
```

How to reproduce (if possible): Upgrade to GUI Version 8.8.56.

**Comment by 0jay** [comment]
Pref the old margins tbh, now unable to scroll reliably on iPad without loading a card interface

**Comment by kevdagoat** [comment]
Always had that problem ;)

**Comment by 0jay** [comment]
Sure, no way around it now.

**Comment by 0jay** [comment]
Also I think Free memory variable is actually displaying used memory

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/260#issuecomment-427542488
> every update resets my root password

https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/base/etc/init.d/rootdevice
> rootchecks() {
	logger_command "Save root password if modified"
...

**Comment by 0jay** [comment]
nice one.

**Comment by Ansuel** [comment]
nobody ever reported it so i never checked...

**Comment by 0jay** [comment]
You want me to open a separate issue for it?

**Comment by Kherby** [comment]
I have upgraded 8.8.55 from 8.8.47-dev and it saved my modified root password.... (DGA4130)

**Comment by nclmrc** [comment]
Also with dga4132

**Comment by 0jay** [comment]
Ok.

**Comment by flywire** [comment]
@Ansuel - What are the rules to change root password? I've seen issues on other forums root password not saved (including due to certificate, dropbear setting or something for particular model).

**Comment by nclmrc** [comment]
In the latests stable root password is reset also with DGA4132

**Comment by nclmrc** [comment]
@Ansuel io ho risolto. Avevo creato uno script che tra le tante cose faceva "passwd root -d xxxxxx". Questo comando fa si che la password non venga inserita criptata all' interno di /etc/shadow

**Comment by flywire** [comment]
Regression withTelstra TG799vac GUI Version 8.11.4 2018

![image](https://user-images.githubusercontent.com/11288701/50887291-f019ce00-1446-11e9-8c01-27ce446be1ac.png)
