### ISSUE TITLE
Does V17.3 Firmware Really Exist?

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#261]
Is 17.3 a typo?

https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/upgrade-pack-specificDGA/etc/opkg.conf_17.3 

Closest in Australia is V17.2 - [Technicolor Firmware Repository](https://whirlpool.net.au/wiki/hw_model_1622)

**Comment by kevdagoat** [comment]
Yep.
So does:
- 17.4
- 18.1
https://www.technicolor.com/distribute/home-experience/regulatory-information

Sent from Mail for Windows 10

From: flywire
Sent: Saturday, October 6, 2018 1:05 PM
To: Ansuel/tch-nginx-gui
Cc: Subscribed
Subject: [Ansuel/tch-nginx-gui] Does V17.3 Firmware Really Exist? (#261)

Is 17.3 a typo?
https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/upgrade-pack-specificDGA/etc/opkg.conf_17.3
Closest in Australia is V17.2 - Technicolor Firmware Repository

**Comment by flywire** [comment]
Can package configuration be based on major version without minor version to support Australian versions too?

**Comment by FrancYescO** [comment]
No. DGA4130/2 have 17.3 (and also 17.3.a/b/c)

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/96#issuecomment-427547411
> apply_right_opkg_repo()

https://forums.whirlpool.net.au/archive/2650998#r56274778

**Comment by Ansuel** [comment]
@flywire can you confirm that someone actually test that repo ? 
isp apply special compilation flag to their modem and this can cause some problems...

**Comment by flywire** [comment]
@Ansuel - Just did file compare. I missed slight change in domain name from Whirlpool forum: ilpuntotecnico**eadsl**.com

- I can confirm whirlpool post as used to install vnstat package on my v17.2 TG800 (but has since gone with gui upgrade).

- I can also confirm [whirlpool post](whrl.pl/Re8xlC) as used to install vnstat package on my v17.2 TG799. Note **two** files.

**Comment by kevdagoat** [comment]
Is this ok to close?
