### ISSUE TITLE
Stats interface lists Free Memory but displaying used memory

### ISSUE THREAD

**Issue by 0jay** [Ansuel/tch-nginx-gui#262]
Mentioned in flywire's 8.8.56 post

Device Model: TG799vac
Gui Version: 8.8.56

Description of problem:
Stats interface lists Free Memory but displaying used memory (incorrect labelling)

**Comment by 0jay** [comment]
Ok, I’ll have a look next week when I get access to the modem.
Mine was showing 40MB free which seems pretty unlikely but it’s possible I
guess.

**Comment by Ansuel** [comment]
try to compare that value with 
free 
in a ssh console

**Comment by 0jay** [comment]
Will do. I dont have access to the unit until next week, I’ll let you know then.

**Comment by kevdagoat** [comment]
/www/docroot/modals$ free
             total         used         free       shared      buffers
Mem:        246940       224012        22928            0        13444
-/+ buffers:             210568        36372
Swap:            0            0            0

Is indeed displaying free memory, albeit a bit inaccurate though:
![image](https://user-images.githubusercontent.com/42062334/46863170-3f049700-ce49-11e8-850f-31c63efaf9b4.png)

**Comment by 0jay** [comment]
Yeah I’ve been thinking on that, I’m comparing it to a completely stripped system reading. 

I’ve been under the hammer studying for exams etc and post up for distraction sometimes, obv times when I should think it through before I post up.

Sorry to waste your time, @Ansuel
