### ISSUE TITLE
No cleanup after update (GUI.tar.bz2 remains in tmp)

### ISSUE THREAD

**Issue by 0jay** [Ansuel/tch-nginx-gui#263]
Device Model: TG799vac
Gui Version: 8.8.56

Description of problem:
No cleanup after update (GUI.tar.bz2 remains in tmp)

**Comment by kevdagoat** [comment]
Not really a problem.
/tmp is ram, you have 256mbytes of it.

If you reboot it will be gone

**Comment by 0jay** [comment]
not saying it’s a problem.

I’m suggesting it should be part of the clean up routine to clear it.

y wanna recommend a reboot after install in the guide?

**Comment by Kherby** [comment]
Can't reproduce this (DGA4130). I did a upgrade from 8.8.55 to 8.8.56 (via GUI) and GUI.tar.bz2 doesn't remain in /tmp/...

**Comment by 0jay** [comment]
I was playing around with dev versions for a while. Probably did 8-10 update/downgrades all via the gui.

**Comment by kevdagoat** [comment]
Will have a look at rootdevice and maybe add in some code to remove
