### ISSUE TITLE
Impostazioni ECO

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#271]
Secondo me andrebbe rivista in impostazioni ECO la dicitura "x of max frequence".
1 come 100%, 1/1 50%, 1/2 25% e così via. 
![screenshot_20181009-192425_chrome](https://user-images.githubusercontent.com/38593316/46686972-028f2c00-cbfa-11e8-8091-6115aeb12690.jpg)

**Comment by Ansuel** [comment]
Fixed
