### ISSUE TITLE
Community Maintainable Documentation

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#272]
Initialise documentation the community can maintain (wiki, readthedocs, etc).

**Comment by kevdagoat** [comment]
Definitely!

**Comment by kevdagoat** [comment]
Thinking about it more, here are some benefits:
- @Ansuel if you are away the community can still develop
- Takes work off of the maintainers @Ansuel @FrancYescO 
- Should allow for an excellent and smooth install procedure for beginners

Future Suggestions
- A .exe that you run to root and install GUI
- Diagnostic collection for help (eg. downloadable assistance log)

**Comment by BreakSecurity** [comment]
Great idea!!!

**Comment by kevdagoat** [comment]
Github wiki would work

**Comment by flywire** [comment]
If someone starts it I will contribute.

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/wiki

feels free to contribute
