### ISSUE TITLE
Popolamento tabella "Indirizzi IP statici" del DHCP

### ISSUE THREAD

**Issue by umbertoB67** [Ansuel/tch-nginx-gui#273]
Device Model: MediaAccess TG789vac v2 ( MediaAccess TG789vac v2 )
Gui Version: 8.8.68

Description of problem:
C'è un modo per popolare rapidamente la tabella degli "**Indirizzi IP statici**" del **DHCP**?
Magari anche editando direttamente qualche file di configurazione del TG789vac v2.
In una futura versione sarebbe utile poter uplodare un csv con tutte le info necessarie per aggiungere batch tutte le entry necessarie.

Grazie.

PS: ho provato ad esportare la configurazione ed aggiungere una entry nella sezione [dhcp], ma l'import poi fallisce. Es:
dhcp.@host[3]=host
dhcp.@host[3].name='PC-01'
dhcp.@host[3].mac='00:12:90:f1:ed:12'
dhcp.@host[3].ip='192.168.1.20'

**Comment by Ansuel** [comment]
edita direttamente le impostazioni con win scp 

per il file csv :( sorry ma troppo lavoro per qualcosa di troppo specifico

**Comment by umbertoB67** [comment]
Grazie per la risposta.

> edita direttamente le impostazioni con win scp
quale file devo editare? in quale cartella lo trovo?
> per il file csv :( sorry ma troppo lavoro per qualcosa di troppo specifico
No problem! :-)

Grazie. Ciao.

**Comment by Ansuel** [comment]
/etc/config/dhcp fai riferimento a openwrt

Il Gio 11 Ott 2018, 19:08 umbertoB67 <notifications@github.com> ha scritto:
