### ISSUE TITLE
Add Abbreviated Device Description to Footer

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#274]
For easy issue entry with copy swipe footer could change from:
`GUI Version [ 8.8.68 ] 2018 Changelog`
to:
`TG800TLS GUI Version 8.8.68 2018 Changelog`

ie add model shortcode. Maybe changelog link could even sit on the version No.

BTW - Product doesn't always format well: eg 'Product Name Technicolor TG ( Technicolor TG800vac )'.

**Comment by kevdagoat** [comment]
Will have a look at this

**Comment by kevdagoat** [comment]
So far:
![image](https://user-images.githubusercontent.com/42062334/46857757-45d8dd00-ce3c-11e8-9a80-e227822dbaca.png)

Sadly the changelog is in Italian

**Comment by flywire** [comment]
> Sadly the changelog is in Italian
I have a fix for that at work (next week)

cat /etc/config/env
```
config envvars 'var'
...
	option prod_number '799vac'
...
	option provisioning_code 'Telstra'
```

**Comment by kevdagoat** [comment]
Thanks for that. Will add it

**Comment by kevdagoat** [comment]
![image](https://user-images.githubusercontent.com/42062334/46858862-da443f00-ce3e-11e8-927e-11877a422232.png)
That ok?

**Comment by flywire** [comment]
I think same line as `GUI Version'. Seems `provisioning_code` is needed to distinguish HW versions too.

**Comment by kevdagoat** [comment]
Dont think that is possible atm

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
![image](https://user-images.githubusercontent.com/42062334/46860005-f1386080-ce41-11e8-8edc-d1f711179a70.png)

What do you think.
Cant stick GUI version and model number on the same line due to the limitations of the format() function

**Comment by Ansuel** [comment]
limitation ? ??? 

just search string.format lua

**Comment by kevdagoat** [comment]
example?

**Comment by kevdagoat** [comment]
Im not a Lua person. I write C++

**Comment by flywire** [comment]
```
> = string.format("%s %q", "Hello", "Lua user!")   -- string and quoted string
Hello "Lua user!"
```

**Comment by Ansuel** [comment]
string.format("First arg:%s Second arg:%s",first_Arg,second_arg)

**Comment by kevdagoat** [comment]
oh ok.
Will do that then

**Comment by kevdagoat** [comment]
`html[#html+1] =				       string.format("<p>%s GUI Version <a href data-toggle="modal" data-remote="modals/changelog.lp">%q</a> 2018 ",cui.gui_version ,cui.product_number) `

Sadly that crashes nginx

**Comment by kevdagoat** [comment]
Got it
![image](https://user-images.githubusercontent.com/42062334/46861175-9eac7380-ce44-11e8-823a-64889eea5d67.png)

**Comment by kevdagoat** [comment]
Done
#276

**Comment by flywire** [comment]
I still think we need `provisioning_code` to distinguish variant.

**Comment by kevdagoat** [comment]
ok

**Comment by kevdagoat** [comment]
![image](https://user-images.githubusercontent.com/42062334/46861818-28107580-ce46-11e8-9d66-9d5c43d3cbde.png)

**Comment by kevdagoat** [comment]
May as well do something similar for the gateway modal
![image](https://user-images.githubusercontent.com/42062334/46862178-e9c78600-ce46-11e8-81d8-cb762122a36a.png)

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/pull/281

Would only leave changelog language translation issue.

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/pull/317#issue-226905596, https://github.com/Ansuel/tch-nginx-gui/issues/274#issuecomment-429249353

> `cat /etc/config/env`
```
config envvars 'var'
...
	option variant_friendly_name 'TG800vac'
```

If no `option variant_friendly_name` could define from `option prod_friendly_name 'Technicolor TG799vac'`

```
if ( variant_friendly_name == "" ) then 
	variant_friendly_name = string.gsub(prod_friendly_name,"Technicolor ","")
end
provisioning_variant_code = provisioning_code .. " " .. variant_friendly_name
```

1. What about other variants?
2. Would be nice to write them as environment variables back to `cat /etc/config/env`

**Comment by flywire** [comment]
www/cards/001_gateway.lp
```
elseif ( variant == "Technicolor TG800vac" ) then
	model = "_TG800vac"
```
Should probably rename `model` to `variant_friendly_name`, remove leaving `_` and reuse code.

**Comment by flywire** [comment]
More robust version: [footer.lp](https://github.com/Ansuel/tch-nginx-gui/files/2544499/footer.lp.txt)

Gateway is getting laggy which would improve by reducing duplicate code.

Will create `env.var.variant_friendly_name='TG800vac'` equivalent where it doesn't exist and adjust code.

**Comment by flywire** [comment]
I'm still trying to get on top of the code so any comments, tweaks or checks welcome.

`variant` would only be a temporary variable in the `rootdevice` script. I expect `env.var.prod_friendly_name` would always exist so `env.var.variant_friendly_name` should always be set. If it was null

What do you think about: www/gateway-snippets/[footer.lp](https://github.com/Ansuel/tch-nginx-gui/files/2545524/footer.lp.txt)? (Needs `env.var.variant_friendly_name` set to work.)

**Comment by flywire** [comment]
If this doesn't look right for your gateway please run these commands and post result:

```
uci show env.var.company_name
uci show env.var.prod_name
uci show env.var.prod_friendly_name
uci show env.var.prod_number
uci show env.var.provisioning_code
uci show env.var.hardware_version
uci show env.var.variant_friendly_name

```

**Comment by scotty03** [comment]
For a MyRepublic TG789MYRvac v2 HP I got the following

env.var.company_name='Technicolor'
env.var.prod_name='MediaAccess TG'
env.var.prod_friendly_name='MediaAccess TG789MYRvac v2 HP'
env.var.prod_number='789MYRvac v2 HP'
uci show env.var.provisioning_code : Entry not found
env.var.hardware_version='VBNT-L'
uci show env.var.variant_friendly_name : Entry not found

Hope that helps

**Comment by flywire** [comment]
> Hope that helps

Certainly, wasn't expecting `uci show env.var.provisioning_code : Entry not found`. They're a real mixed bag.

**Comment by kevdagoat** [comment]
Will do some editing and create a pr.

Sent from Mail for Windows 10

**Comment by scotty03** [comment]
> 
> 
> > Hope that helps
> 
> Certainly, wasn't expecting `uci show env.var.provisioning_code : Entry not found`. They're a real mixed bag.

And that is also the only firmware available as even MYR have not updated the firmware since release in 2016. They did advertise for a firmware developer 18 months ago but don't know if they hired anyone I saw the ad on Linkedin

**Comment by flywire** [comment]
> Will do some editing and create a pr.

Steady up and lets discuss this.

@Ansuel, What are your thoughts on https://github.com/Ansuel/tch-nginx-gui/pull/332 for `env.var.variant_friendly_name`? Given dump from @scotty03 I wonder how many gateways use `env.var.provisioning_code` and `env.var.variant_friendly_name`.

I thought `env.var.variant_friendly_name` might be a convenient alias for model but not if it is only used in Telstra TG800vac. `env.var.prod_friendly_name='MediaAccess TG789MYRvac v2 HP'` is a reasonable name alias but `env.var.prod_friendly_name='Technicolor TG799vac'` would be better as `Telstra TG799vac`. I'd be concerned redefining `env.var.prod_friendly_name` on Telstra gateways without knowing everything the variable is used for. Maybe define `env.var.variant_name`?

www/cards/001_gateway.lp
The case statement in https://github.com/Ansuel/tch-nginx-gui/pull/332 is much cleaner and the `_` could be stripped from the model and added to the `<source srcset="/img/gateway_');...` lines.

If environment variable(s) are used for above these files can be rationalised:
1. `etc/init.d/rootdevice`
2. `www/docroot/modals/gateway-modal.lp`
3. ` www/info-cards/001_gateway.lp`

and `www/gateway-snippets/footer.lp` adjusted.

Benefits are cleaner, less redundant code and a little faster.

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/346 - same issue, code in https://github.com/Ansuel/tch-nginx-gui/pull/332/commits/f00cd1ae2a66621ac01e9d5e93ee46827147404f

Pick the variable name then might need to change around to something like:

```
variant=$( uci get env.var.prod_friendly_name )
case "$variant"
in
	DGA4130)
		model=AGTEF ;;
	DGA4132)
		model=AGTHP ;;
	*TG789*)
		model=TG789vac ;;
	*TG799*)
		model=TG799vac ;;
	*TG800*)
		model=TG800vac ;;
esac
```

**Comment by scotty03** [comment]
@flywire hold onto your hat the provisioning code changes between firmwares on a iinet TG789vac v2

iinet TG789vac v2 - with UNO 17.2 firmware
env.var.company_name='Technicolor'
env.var.prod_name='MediaAccess TG'
env.var.prod_friendly_name='MediaAccess TG789vac v2'
env.var.prod_number='789vac v2'
env.var.provisioning_code='Netlynk MST'
env.var.hardware_version='VANT-6'
uci show env.var.variant_friendly_name : Entry not found

iinet TG789vac v2 - 16.3 Aqua iinet firmware
env.var.company_name='Technicolor'
env.var.prod_name='MediaAccess TG'
env.var.prod_friendly_name='MediaAccess TG789vac v2'
env.var.prod_number='789vac v2'
env.var.provisioning_code='Technicolor TG789vac v2'
env.var.hardware_version='VANT-6'
uci show env.var.variant_friendly_name : Entry not found

**Comment by flywire** [comment]
Yeah random! @scotty03 - Can you do the dga4132?

**Comment by scotty03** [comment]
Yeah random! @scotty03 - Can you do the dga4132?
@flywire 

env.var.company_name='Technicolor'
env.var.prod_name='DGA'
env.var.prod_friendly_name='DGA4132'
env.var.prod_number='4132'
uci show env.var.provisioning_code : Entry not found
env.var.hardware_version='VBNT-S'
env.var.variant_friendly_name='AGHP'

**Comment by flywire** [comment]
A bag full of old models:

```
root@mygateway:/# find '/etc/boards' -name 'env' -print -exec cat {} \; -exec echo \;
/etc/boards/GBNT-G/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG399ac'
        option prod_name 'MediaAccess TG'
        option prod_number '399ac'
        option ssid_prefix 'TNCAP'


/etc/boards/VANT-4/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG789vac HP'
        option prod_name 'MediaAccess TG'
        option prod_number '789vac HP'
        option ssid_prefix 'TNCAP'


/etc/boards/VANT-6/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG789vac v2'
        option prod_name 'MediaAccess TG'
        option prod_number '789vac v2'
        option ssid_prefix 'TNCAP'


/etc/boards/VANT-7/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG789vac v2 HP'
        option prod_name 'MediaAccess TG'
        option prod_number '789vac v2 HP'
        option ssid_prefix 'TNCAP'


/etc/boards/VANT-8/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG589vac v2'
        option prod_name 'MediaAccess TG'
        option prod_number '589vac v2'
        option ssid_prefix 'TNCAP'


/etc/boards/VANT-D/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG789vac'
        option prod_name 'MediaAccess TG'
        option prod_number '789vac'
        option ssid_prefix 'TNCAP'


/etc/boards/VANT-E/config/etc/config/env

config envvars 'var'
        option company_name 'Technicolor'
        option prod_name 'Technicolor TG'
        option prod_friendly_name 'MediaAccess TG799vac'
        option prod_number '799vac'
        option ssid_prefix 'Telstra'
        option CONF_VERSION 'CRF283'
        option provisioning_code 'Telstra'
        option rtfds '1'

/etc/boards/VANT-R/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG799vac'
        option prod_name 'MediaAccess TG'
        option prod_number '799vac'
        option ssid_prefix 'TNCAP'


/etc/boards/VBNT-A/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TGiiNet-2'
        option prod_name 'MediaAccess TG'
        option prod_number 'iiNet-2'
        option ssid_prefix 'TNCAP'


/etc/boards/VBNT-B/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'DHA0120 for Telstra'
        option prod_name 'DHA'
        option prod_number '0120'
        option ssid_prefix 'Telstra'
        option provisioning_code 'Telstra'
        option rtfds '1'

/etc/boards/VBNT-L/config/etc/config/env
config envvars 'var'
        option company_name 'Technicolor'
        option prod_friendly_name 'MediaAccess TG789MYRvac v2 HP'
        option prod_name 'MediaAccess TG'
        option prod_number '789MYRvac v2 HP'
        option ssid_prefix 'TNCAP'


```
