### ISSUE TITLE
Last GUI 8.8.71

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#275]
![immagine](https://user-images.githubusercontent.com/38593316/46861098-1f9e4780-ce12-11e8-8216-9f11dc975e0a.png)
Appare la scehrmata di login, faccio il login poi esce questo.
Qua il log:
https://pastebin.com/JStdK2Ti

**Comment by Ansuel** [comment]
transformer-cli get uci.network.device.
transformer-cli get rpc.network.interface.@wan.ifname

**Comment by nclmrc** [comment]
root@DGA4132:~# transformer-cli get uci.network.device.
uci.network.device.@waneth4.enabled [string] =
uci.network.device.@waneth4.type [string] = 8021q
uci.network.device.@waneth4.mtu [string] =
uci.network.device.@waneth4.vid [string] = 835
uci.network.device.@waneth4.name [string] = waneth4
uci.network.device.@waneth4.igmpversion [string] =
uci.network.device.@waneth4.macaddr [string] = A4:91:B1:2B:08:EC
uci.network.device.@waneth4.ifname [string] = eth4
uci.network.device.@waneth4.ipv6 [string] = 0
uci.network.device.@wanptm0.enabled [string] =
uci.network.device.@wanptm0.type [string] = 8021q
uci.network.device.@wanptm0.mtu [string] =
uci.network.device.@wanptm0.vid [string] = 835
uci.network.device.@wanptm0.name [string] = wanptm0
uci.network.device.@wanptm0.igmpversion [string] =
uci.network.device.@wanptm0.macaddr [string] = A4:91:B1:2B:08:EC
uci.network.device.@wanptm0.ifname [string] = ptm0
uci.network.device.@wanptm0.ipv6 [string] = 0
uci.network.device.@wlnet_b_5eth5.enabled [string] = 1
uci.network.device.@wlnet_b_5eth5.type [string] = 8021q
uci.network.device.@wlnet_b_5eth5.mtu [string] =
uci.network.device.@wlnet_b_5eth5.vid [string] = 3
uci.network.device.@wlnet_b_5eth5.name [string] = wl1_1
uci.network.device.@wlnet_b_5eth5.igmpversion [string] =
uci.network.device.@wlnet_b_5eth5.macaddr [string] =
uci.network.device.@wlnet_b_5eth5.ifname [string] = eth5
uci.network.device.@wlnet_b_5eth5.ipv6 [string] = 0

rpc.network.interface.@wan.ifname [string] = atmwan

**Comment by nclmrc** [comment]
root@DGA4132:~# transformer-cli get uci.network. | grep atmwan
uci.network.interface.@lan.pppoerelay.@1.value [string] = atmwan
uci.network.interface.@wan.ifname [string] = atmwan
uci.network.interface.@wan.device [string] = atmwan

**Comment by Ansuel** [comment]
transformer-cli get rpc. | grep atmwan

**Comment by nclmrc** [comment]
root@DGA4132:~# transformer-cli get rpc. | grep atmwan
rpc.network.interface.@lan.ppp.ll_intf [string] = atmwan
rpc.network.interface.@lan.ppp.ll_dev [string] = atmwan
rpc.network.interface.@wan.ifname [string] = atmwan
rpc.network.interface.@wan.ppp.ll_intf [string] = atmwan
rpc.network.interface.@wan.ppp.ll_dev [string] = atmwan
rpc.system.tcpdump.intflist [string] = atmvoip atmwan br-lan eth0 eth1 eth2 eth3 eth4 eth5 pppoe-voip pppoe-wan wl0 wl0_1 wl1_1

**Comment by Ansuel** [comment]
should be fixed in latest stable
