### ISSUE TITLE
Fix For Last Firmware 1.1.2

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#278]
Ho aggiornato il firmware e mi escono questi errori dopo aver rimesso la GUI.
Log:
https://pastebin.com/fGFeAUbc

**Comment by nclmrc** [comment]
Mannaggia a Technicolor. Hanno aggiunto una c nella versione firmware.
17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a

**Comment by Ansuel** [comment]
Dovrei aver fixato

Il Dom 14 Ott 2018, 11:27 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
non era quello, infatti nel firmware beta c'era già la c

**Comment by nclmrc** [comment]
@Ansuel Ti ho mandato una mail

**Comment by nclmrc** [comment]
Ora ho rimosso luci con lo script manualmente e settato la variabile luci in env a 0. Almeno la schermata di login della gui la vedo.

**Comment by nclmrc** [comment]
Ti sei fatto un idea di cosa possa essere?

**Comment by Ansuel** [comment]
Non è fixato ?

Il Lun 15 Ott 2018, 21:07 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
No

Il Lun 15 Ott 2018, 21:32 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Sempre quel errore mi esce

**Comment by Ansuel** [comment]
@nclmrc ho bisogno di questo comando

transformer-cli get uci.version.version.@version[0].mask

**Comment by nclmrc** [comment]
root@DGA4132:~# transformer-cli get uci.version.version.@version[0].mask
uci.version.version.@version[0].mask [string] = 17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0
root@DGA4132:~#

**Comment by Ansuel** [comment]
transformer-cli get uci.version.

**Comment by Ansuel** [comment]
@nclmrc

**Comment by nclmrc** [comment]
root@DGA4132:~# transformer-cli get uci.version.
uci.version.versionNumberOfEntries [unsignedInt] = 2
uci.version.version.@version[0].custo [string] = e42126873d3e0a02149d2c844b66c7706aa70f1c
uci.version.version.@version[0].package [string] =
uci.version.version.@version[0].mask [string] = 17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0
uci.version.version.@version[0].kernel [string] = 413169f93c49fce9392f8a29ecf9149e13cca086
uci.version.version.@version[0].product [string] = vbnt-s
uci.version.version.@version[0].oid [string] = 5b9bb1a3c0f0e171f39b1e41
uci.version.version.@version[0].config [string] = d96cab359f20d67aef464859849f1d49123a7bf0
uci.version.version.@version[0].version [string] = 17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0
uci.version.version.@version[0].marketing_version [string] = 17.3.c
uci.version.version.@version[0].technicolor [string] = 6957fbdcc09b3cd60bbb2061871c498fa30087d2
uci.version.version.@version[0].timestamp [string] = 17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0
uci.version.version.@version[0].marketing_name [string] = Cyan
uci.version.version.@version[0].openwrt [string] = cb16baf33312df1c3c94ad4347aa95cb662e3c5a
uci.version.version.@version[1].custo [string] = 62cb5bf0c6dd51e512a02f491c1c674570258759
uci.version.version.@version[1].package [string] =
uci.version.version.@version[1].mask [string] = 1681019
uci.version.version.@version[1].kernel [string] = 413169f93c49fce9392f8a29ecf9149e13cca086
uci.version.version.@version[1].product [string] = vbnt-s
uci.version.version.@version[1].oid [string] = 5ad78cd02e32ce7234ac0ec5
uci.version.version.@version[1].config [string] = 2b000d1f81ba522961071ab98383057683762dc6
uci.version.version.@version[1].version [string] = 17.3.0268-1681019-20180418202208-2b000d1f81ba522961071ab98383057683762dc6
uci.version.version.@version[1].marketing_version [string] = 17.3
uci.version.version.@version[1].technicolor [string] = 65644eeb87a4ce9c6e469c4c03c721a290ef8bb1
uci.version.version.@version[1].timestamp [string] = 20180418202208
uci.version.version.@version[1].marketing_name [string] = Cyan
uci.version.version.@version[1].openwrt [string] = 9994478e65e83f08b6a62e6edefa48bff72d3cf6
root@DGA4132:~#

**Comment by Ansuel** [comment]
uci show version

cat /etc/config/version

**Comment by nclmrc** [comment]
root@DGA4132:~# uci show version
version.@version[0]=version
version.@version[0].version='17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
version.@version[0].mask='17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
version.@version[0].timestamp='17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
version.@version[0].product='vbnt-s'
version.@version[0].marketing_name='Cyan'
version.@version[0].marketing_version='17.3.c'
version.@version[0].config='d96cab359f20d67aef464859849f1d49123a7bf0'
version.@version[0].openwrt='cb16baf33312df1c3c94ad4347aa95cb662e3c5a'
version.@version[0].kernel='413169f93c49fce9392f8a29ecf9149e13cca086'
version.@version[0].custo='e42126873d3e0a02149d2c844b66c7706aa70f1c'
version.@version[0].technicolor='6957fbdcc09b3cd60bbb2061871c498fa30087d2'
version.@version[0].lte='8fa387fa4c87540a79baa20e46012abee36ccfa6'
version.@version[0].routing='e5b651af0315a6b5a8e034e0e530270544f32428'
version.@version[0].packages='f161ea0e5ad061ae6af0024cf1d88b7a795010f6'
version.@version[0].oid='5b9bb1a3c0f0e171f39b1e41'
version.@version[1]=version
version.@version[1].version='17.3.0268-1681019-20180418202208-2b000d1f81ba522961071ab98383057683762dc6'
version.@version[1].mask='1681019'
version.@version[1].timestamp='20180418202208'
version.@version[1].product='vbnt-s'
version.@version[1].marketing_name='Cyan'
version.@version[1].marketing_version='17.3'
version.@version[1].config='2b000d1f81ba522961071ab98383057683762dc6'
version.@version[1].openwrt='9994478e65e83f08b6a62e6edefa48bff72d3cf6'
version.@version[1].kernel='413169f93c49fce9392f8a29ecf9149e13cca086'
version.@version[1].custo='62cb5bf0c6dd51e512a02f491c1c674570258759'
version.@version[1].packages='c858b7d53626e4a888cbf8839e93ed0e036304bc'
version.@version[1].routing='e5b651af0315a6b5a8e034e0e530270544f32428'
version.@version[1].lte='ba4efa592f7aab51ebbea41f737811889e0bd084'
version.@version[1].technicolor='65644eeb87a4ce9c6e469c4c03c721a290ef8bb1'
version.@version[1].oid='5ad78cd02e32ce7234ac0ec5'
root@DGA4132:~#

**Comment by nclmrc** [comment]
root@DGA4132:~# cat /etc/config/version
config version
        option version '17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
        option mask '17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
        option timestamp '17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
        option product 'vbnt-s'
        option marketing_name 'Cyan'
        option marketing_version '17.3.c'
        option config 'd96cab359f20d67aef464859849f1d49123a7bf0'
        option openwrt 'cb16baf33312df1c3c94ad4347aa95cb662e3c5a'
        option kernel '413169f93c49fce9392f8a29ecf9149e13cca086'
        option custo 'e42126873d3e0a02149d2c844b66c7706aa70f1c'
        option technicolor '6957fbdcc09b3cd60bbb2061871c498fa30087d2'
        option lte '8fa387fa4c87540a79baa20e46012abee36ccfa6'
        option routing 'e5b651af0315a6b5a8e034e0e530270544f32428'
        option packages 'f161ea0e5ad061ae6af0024cf1d88b7a795010f6'
config version
        option version '17.3.0268-1681019-20180418202208-2b000d1f81ba522961071ab98383057683762dc6'
        option mask '1681019'
        option timestamp '20180418202208'
        option product 'vbnt-s'
        option marketing_name 'Cyan'
        option marketing_version '17.3'
        option config '2b000d1f81ba522961071ab98383057683762dc6'
        option openwrt '9994478e65e83f08b6a62e6edefa48bff72d3cf6'
        option kernel '413169f93c49fce9392f8a29ecf9149e13cca086'
        option custo '62cb5bf0c6dd51e512a02f491c1c674570258759'
        option packages 'c858b7d53626e4a888cbf8839e93ed0e036304bc'
        option routing 'e5b651af0315a6b5a8e034e0e530270544f32428'
        option lte 'ba4efa592f7aab51ebbea41f737811889e0bd084'
        option technicolor '65644eeb87a4ce9c6e469c4c03c721a290ef8bb1'
        option oid '5ad78cd02e32ce7234ac0ec5'
root@DGA4132:~#

**Comment by Ansuel** [comment]
strano qualcosa si è fregato nell'aggiornamento o.o hai due versioni

**Comment by nclmrc** [comment]
Quali sarebbero?

Il Lun 15 Ott 2018, 23:31 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
nel senso nel file che mostra le versioni ce ne sono due 
e non so se è un bug telecom ma la mask non dovrebbe contenere la versione intera ma solo un numero

**Comment by nclmrc** [comment]
Secondo me è successo casino quando ho ripristinato la vecchia cartella
config.

Il Lun 15 Ott 2018, 23:34 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Ripristinato i file version da rom

**Comment by nclmrc** [comment]
Riavviato, vediamo che succede

**Comment by Ansuel** [comment]
i file? quali !

**Comment by nclmrc** [comment]
Quelli presenti in /rom/etc/config/

Il Lun 15 Ott 2018, 23:46 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
......... mai farlo .....

quelle sono configurazioni vuote non configurazioni di default... 

bastava ripristinare il file version ma comunque non avevo detto di farlo...

**Comment by nclmrc** [comment]
Nel file version avevo due versioni

**Comment by Ansuel** [comment]
potevi semplicemente eliminare la prima sezione...

**Comment by nclmrc** [comment]
Mi sono assicurato che il file version in rom fosse presente in parte anche nella configurazione attiva

**Comment by Ansuel** [comment]
nha non serve

**Comment by Ansuel** [comment]
anzi la 1.1.2 è diventata stabile? spero di no...

**Comment by nclmrc** [comment]
Sempre questi errori

**Comment by nclmrc** [comment]
root@DGA4132:/etc/config# logread -f
 Tue Oct 16 00:04:25 2018 daemon.err nginx: 2018/10/16 00:04:25 [error] 4187#0: *11 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:337: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        /usr/lib/lua/web/web.lua:337: in function 'isDemoBuild'
        [string "header.lp"]:112: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "/gateway.lp"]:32: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginxTue Oct 16 00:04:25 2018 daemon.err nginx: 2018/10/16 00:04:25 [error] 4187#0: *12 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:337: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        /usr/lib/lua/web/web.lua:337: in function 'isDemoBuild'
        [string "header.lp"]:112: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "/gateway.lp"]:32: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginxTue Oct 16 00:04:25 2018 daemon.err nginx: 2018/10/16 00:04:25 [error] 4187#0: *13 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:337: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        /usr/lib/lua/web/web.lua:337: in function 'isDemoBuild'
        [string "header.lp"]:112: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "/gateway.lp"]:32: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginxTue Oct 16 00:04:25 2018 daemon.err nginx: 2018/10/16 00:04:25 [error] 4187#0: *14 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:337: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        /usr/lib/lua/web/web.lua:337: in function 'isDemoBuild'
        [string "header.lp"]:112: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "/gateway.lp"]:32: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginxTue Oct 16 00:04:25 2018 daemon.err nginx: 2018/10/16 00:04:25 [error] 4187#0: *15 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:337: attempt to perform arithmetic on a nil value
stack traceback:
coroutine 0:
        /usr/lib/lua/web/web.lua:337: in function 'isDemoBuild'
        [string "header.lp"]:112: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "/gateway.lp"]:32: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginxTue Oct 16 00:04:25 2018 daemon.err nginx: 2018/10/16 00:04:25

**Comment by nclmrc** [comment]
Il file version:
root@DGA4132:/etc/config# cat version
config version
        option version '17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
        option mask '17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
        option timestamp '17.3.c.0337-8041027-20180914150331-d96cab359f20d67aef464859849f1d49123a7bf0'
        option product 'vbnt-s'
        option marketing_name 'Cyan'
        option marketing_version '17.3.c'
        option config 'd96cab359f20d67aef464859849f1d49123a7bf0'
        option openwrt 'cb16baf33312df1c3c94ad4347aa95cb662e3c5a'
        option kernel '413169f93c49fce9392f8a29ecf9149e13cca086'
        option custo 'e42126873d3e0a02149d2c844b66c7706aa70f1c'
        option technicolor '6957fbdcc09b3cd60bbb2061871c498fa30087d2'
        option lte '8fa387fa4c87540a79baa20e46012abee36ccfa6'
        option routing 'e5b651af0315a6b5a8e034e0e530270544f32428'
        option packages 'f161ea0e5ad061ae6af0024cf1d88b7a795010f6'
root@DGA4132:/etc/config#

Il valore mask è cambiato

**Comment by nclmrc** [comment]
Si è stabile per questo ho aggiornato 😀

Il Mar 16 Ott 2018, 00:02 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
merd.... finita la pacchia... vabbè...

**Comment by nclmrc** [comment]
Ho visto però che dall'ultima beta la versione è rimasta la stessa. Io sono
passato da 1.1.1 a 1.1.2

Il Mar 16 Ott 2018, 00:11 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Appena messo Luci mi va di default sulla 80. È cambiato qualcosa nell' ultima versione 1.1.2, prima non faceva così.

**Comment by nclmrc** [comment]
Per completezza ti giro anche il file versioncusto aggiornato. 
root@DGA4132:/etc/config# cat versioncusto

config override 'override'
        option fwversion_prefix 'AGTHP_'
        option fwversion_suffix ''
        option fwversion_override_real '1.1.2'
        option fwversion_override '1.1.2'

root@DGA4132:/etc/config#

**Comment by Ansuel** [comment]
Come installi luci?

Il Mar 16 Ott 2018, 00:35 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Provato sia da gui sia da script

**Comment by Ansuel** [comment]
apri altra issue
