### ISSUE TITLE
conversione driver dslam IFTN xdsl

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#282]
@Ansuel Ho riguardato i dati per questo valore "0xd087" mi risulterebbe, invece di 13.8.7 come ti dissi la scorsa volta, 13.2.7.42.0.16. Sinceramente però non capisco affatto la conversione

**Comment by Ansuel** [comment]
e questa lunga versione da dove uscirebbe?

**Comment by nclmrc** [comment]
Presa direttamente dal dslam

Il Mar 16 Ott 2018, 17:04 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
ed io come farei ad ottenerla...

**Comment by nclmrc** [comment]
Non lo so, infatti mi sembra troppo complicato.

Il Mar 16 Ott 2018, 18:04 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Ma soprattutto non ci vedo una logica.

**Comment by Ansuel** [comment]
purtroppo noi ci possiamo solo basare su cosa ci comunica il dslam, e lo comunica con dei valori in esadecimale che converto per creare la versione...

non credo modem come i fritzbox usano altri metodi per prendere la versione... 
se ne conosci altri dimmi pure e implemento.
