### ISSUE TITLE
Version Spoofing

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#284]
Aggiornando la versione sembra che abbia salvato il valore ma in realtà non è così. Semmai di default mettiamo un valore più alto. Almeno 1.1.2 o 1.2.0.

**Comment by FrancYescO** [comment]
il default dovrebbe essere il valore reale ammenocché non si é usato il version spoofing, in quel caso é giusto mantenga il valore vecchio

**Comment by Ansuel** [comment]
in realtà per problemi di autoconfigurazione, di default se trova quel file setta la versione all'ultima stabile tim.. quindi 1.1.0, dovrei aggiornare script

**Comment by nclmrc** [comment]
Ma non da possibilità di modificarlo

Il Gio 18 Ott 2018, 12:57 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment]
volevo dire quello che penso sia il comportamento giusto del version spoof (cioé attivarsi e forzare la versione definita solo se si é andati a toccarlo) attualmente non ho guardato bene il funzionamento

**Comment by nclmrc** [comment]
Modifico ma la modifica non viene salvata.

Il Gio 18 Ott 2018, 13:08 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
forse ho capito, viene modificato, ma di default fa visualizzare 1.1.1

**Comment by nclmrc** [comment]
confermo è cosi, semmai si andrebbe aggiornato lo script

**Comment by Ansuel** [comment]
aggiornato valore, da me si modifica correttamente da gui

**Comment by nclmrc** [comment]
A me non fa vedere il valore scritto in configurazione

**Comment by nclmrc** [comment]
Ora di default 1.2.0
