### ISSUE TITLE
Stats - WAN Traffic

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#288]
@Ansuel C'è qualcosa che non mi torna nel grafico dei dati:
![immagine](https://user-images.githubusercontent.com/38593316/47223869-8bf0ec00-d3ba-11e8-8220-b1a9c7cc9c9f.png)
Se scarico costantemente alla mia massima velocità  dovrei avere un andamento orizzontale costante sul valore massimo, invece mi ritrovo picchi e valori nulli. Anche sui valori di picco non ho corrispondenza, il tempo tra nullo-picco-nullo sono 10 secondi visto che il refresh è ogni 5 secondi. Avendo una velocità massima di 1,2 MB/s mi aspetterei un valore costante a 6MB per 5 secondi.
A disposizione per chiarimenti o consigli.

**Comment by nclmrc** [comment]
Facendo un riavvio mi sono accorto che non riparte al boot, è necessario un upgradegui

**Comment by nclmrc** [comment]
@Ansuel che ne pensi

**Comment by nclmrc** [comment]
Hai fatto qualche modica nelle ultime release @Ansuel?

**Comment by FrancYescO** [comment]
credo il problema e' la velocita' di campionamento da 10sec qual era prima e' stata portata a 5, io non noto problemi ma a quanto pare 5 e' troppo veloce ... il problema si presenta sempre?

![image](https://user-images.githubusercontent.com/4574593/47873795-6b8d4c80-de12-11e8-99ec-db7090103265.png)

**Comment by nclmrc** [comment]
Dipende, oggi sembra andare bene.

**Comment by nclmrc** [comment]
@FrancYescO si ci sta si potrebbe riportare a 10

**Comment by nclmrc** [comment]
@Ansuel puoi verificare come mai traffic monitor si avvia solo dopo un upgradegui, mentre al riavvio in automatico no

**Comment by FrancYescO** [comment]
@nclmrc hai ancora il problema del picco-nullo? ti funziona sempre solo dopo un upgradegui?

**Comment by nclmrc** [comment]
@FrancYescO i picchi ci sono sempre anche se meno evidenti. Forse sarebbe da provare a rimettere 10. Si devo fare sempre un upgradegui.

**Comment by FrancYescO** [comment]
cioe', se fai reboot appena si riaccende non funziona il grafico, se vai da ssh e fai upgradegui poi inizia a funzionare?

**Comment by nclmrc** [comment]
Si esatto

**Comment by FrancYescO** [comment]
comunque credo il problema sia altrove... non riesco a riprodurre nessuno dei due problemi su DGA4132 fw1.0.3:
- dopo il reboot il grafico mi funziona correttamente gia dal primo login
- il traffico e' sempre visualizzato in modo corretto

immagino sia in qualche modo collegato a https://github.com/Ansuel/tch-nginx-gui/issues/299#issuecomment-433486774

**Comment by nclmrc** [comment]
@FrancYescO 1.1.1

**Comment by FrancYescO** [comment]
a me il problema non lo fa e c'e da capire da cosa e' causato, l'unica per farla semplice e' partire da un factory reset.

**Comment by nclmrc** [comment]
Secondo me dipende dell'interfaccia wan che non viene riconosciuta all'avvio. Questo perché ho due interfacce una San dati e una wan voip. Secondo me solo @Ansuel è in grado di capire la cosa. Per quanto riguarda il tempo io tornerei a mettere 10 secondi.

**Comment by FrancYescO** [comment]
fai un po queste prove con chrome:
tasto destro quando sei nella pagina con il grafico non funzionante, ispeziona elemento > tab network > selezione XHR in alto
fai uno screenshot delle richieste in particolare mi interessa quella che inizia con `traffic_graph.lua`

possibilmente seleziona una di quelle richieste e manda la response (che trovi tra le tab di destra)

ripeti sia quando funziona che quando non funziona

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/49700172-991ca100-fbdb-11e8-9796-fa07238884e9.png)
i rossi sono tutti 404 not found

**Comment by nclmrc** [comment]
la richiesta è di questo tipo:
http://dga4132.ddns.net/ajax/traffic_graph.lua?interface=atmwan&oldrx=702323&oldtx=255233

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/49700234-455e8780-fbdc-11e8-9a8e-2b53fa3a9366.png)

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/49700251-8060bb00-fbdc-11e8-9325-376bfa5914e6.png)

**Comment by nclmrc** [comment]
dopo upgradegui sono diventati tutti 200

![immagine](https://user-images.githubusercontent.com/38593316/49700349-bce0e680-fbdd-11e8-813f-a2ccd8acb100.png)

**Comment by nclmrc** [comment]
nella cartella /root ho questo file trafficdata che mi si crea in automatico
![immagine](https://user-images.githubusercontent.com/38593316/49700448-efd7aa00-fbde-11e8-881c-ddf5288ded30.png)

**Comment by FrancYescO** [comment]
anziche' fare un upgradegui controlla se facendo `/etc/init.d/nginx restart` poi funziona

**Comment by nclmrc** [comment]
Non è stato sufficiente

**Comment by FrancYescO** [comment]
/etc/init.d/transformer restart

E dopo di nuovo restart di nginx
________________________________

**Comment by nclmrc** [comment]
Avevo già provato

**Comment by FrancYescO** [comment]
sempre quando non funziona controlla se c'e il file /www/docroot/ajax/traffic_graph.lua

**Comment by nclmrc** [comment]
Presente e leggibile

**Comment by FrancYescO** [comment]
invia il file /etc/config/web o controlla semplicemente se ci sono riferimenti a traffic_graph.lua

**Comment by nclmrc** [comment]
web -> https://pastebin.com/3FM8syXJ
web_back -> https://pastebin.com/tG2MwaTa

**Comment by FrancYescO** [comment]
`/etc/init.d/rootdevice debug`
passami il risultato e dimmi se dopo l'esecuzione ti funziona il grafico..

**Comment by nclmrc** [comment]
Dopo questo funziona:
root@DGA4132:~# /etc/init.d/rootdevice debug
Root Script: Rooting in progress...
Root Script: Apply specific device file...
Root Script: DGA device detected!
Root Script: Extracting custom-ripdrv-specificDGA.tar.bz2 ...
Root Script: Extracting telnet_support-specificDGA/TG800.tar.bz2 ...
Root Script: Extracting upgrade-pack-specificDGA.tar.bz2 ...
Root Script: Extracting upnpfix-specificDGA.tar.bz2 ...
Root Script: Extracting dlnad_supprto-specificDGA.tar.bz2 ...
Root Script: Extracting wgetfix-specificDGA.tar.bz2 ...
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Stopping nginx
Root Script: Checking if we are on TIM configuration
Root Script: Unlocking web interface if needed
Root Script: Check variant_friendly_name set
Root Script: Check and cleanup
Root Script: Remove default dns
Root Script: Purify wan
Root Script: Fix dns bug
Root Script: Enable dlnad
Root Script: Fix Sysupgrade
Root Script: Check orig config
Root Script: Restore original mapper
Root Script: Transformer lib check
Root Script: Remove https check
Root Script: Check css presence
Root Script: Check if dnsmasq is names as we need it for the webui
Root Script: Check driver setting
Root Script: Check Dropbear config file
Root Script: Check ddns directory
Root Script: Check eco param
Root Script: Enable new upnp
Root Script: Sync dhcp configuration for new webui
Root Script: Create gui type in config
Root Script: Add new web option
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
Root Script: Moving aria2 dir
Root Script: Creating new option for led definition
Root Script: Old build detected, moving wansensing file
Root Script: Checking downgrade limitation bit
Root Script: Checking opkg conf
Root Script: Creating and checking real version
Root Script: Creating new wol implementation
Root Script: Sync new xdsl option
Root Script: Creating utility simbolic link
Root Script: Clean old script
Root Script: Adding fast cache options
Root Script: Reworking sfp interface in network...
Root Script: Reinstalling telstra gui if needed...
Root Script: Checking if wan_mode option exist...
Root Script: Inizialize and start dosprotect...
Root Script: Checking if intercept is enabled and disabling it if on...
Root Script: Trying to clean wansensing script from hardcoded interface...
Root Script: Setting root flag
Root Script: Disable reboot after crash, this gives race condition...
Root Script: Save root password if modified
Root Script: Setting dropbear settings
Root Script: Restarting dropbear
Root Script: Doing various check and generating hash...
Root Script: Update branch detected: DEV
Root Script: Updating GUI in /root folder from /tmp
Root Script: Detected upgrade!
Root Script: Old GUI hash: 111a856933a0c1c0d596d798f6148e57
Root Script: New GUI hash: 111a856933a0c1c0d596d798f6148e57
Root Script: Resetting version info...
Root Script: Sync version
Root Script: Apply modification
Root Script: Restart power init
Root Script: Restarting dnsmasq
Root Script: Process done.
Root Script: Checking if ISP is detected...
Root Script: Restarting transformer
Root Script: Restarting nginx
Root Script: Trafficmon inizialization
Root Script: Resetting cwmp and watchdog
root@DGA4132:~#

**Comment by FrancYescO** [comment]
e poi continua a rompersi al riavvio?
l'ultima modifica del file /etc/config/web a quando risale? dopo il riavvio cambia?

qui sembra essere la NAND che ci sta salutando...

**Comment by nclmrc** [comment]
Ora ho riavviato e ti faccio sapere,  comunque dei problemi simili li avevo avuti con uhttpd. @Ansuel se lo ricorda. Mi passi il tuo file web lo confronto.

**Comment by nclmrc** [comment]
Al riavvio solito problema.

**Comment by FrancYescO** [comment]
[web.txt](https://github.com/Ansuel/tch-nginx-gui/files/2665066/web.txt)
dovrebbe essere pressocche' lo stesso di quello che viene generato a te dopo aver eseguito `/etc/init.d/rootdevice`

**Comment by nclmrc** [comment]
risolto, fatto un merge tra il tuo file e le mie password, adesso parte tutto regolarmente all'avvio

**Comment by nclmrc** [comment]
si può rimettere il campionamento a 10 secondi?

**Comment by FrancYescO** [comment]
si ma ci sarebbe stato da capire perche' questo file ti veniva resettato dopo che il rootdevice lo modificava...

cosi come il campionamento a 10secondi piuttosto vorrei capire perche a te non va bene a 5 mentre a me non ha mai sbagliato un colpo

**Comment by FrancYescO** [comment]
piu' che altro controlla sempre con le request di chrome, quella a traffic_graph e' fatta ogni 10 secondi?
il risultato e' sempre congruente? in questo screenshot https://github.com/Ansuel/tch-nginx-gui/issues/288#issuecomment-445553677 hai selezionato la tab headers non response

**Comment by nclmrc** [comment]
è fatta ogni 5 secondi

**Comment by FrancYescO** [comment]
c'e bisogno delle response... di quando fa il picco e quando invece va a 0

**Comment by nclmrc** [comment]
picco
![immagine](https://user-images.githubusercontent.com/38593316/49801789-698ca680-fd4b-11e8-971a-56f16fad68b0.png)
![immagine](https://user-images.githubusercontent.com/38593316/49801811-7dd0a380-fd4b-11e8-8324-4d935726bec8.png)


0
![immagine](https://user-images.githubusercontent.com/38593316/49801836-9345cd80-fd4b-11e8-9a32-2531481fb3cf.png)
![immagine](https://user-images.githubusercontent.com/38593316/49801846-9b9e0880-fd4b-11e8-9ffb-5670df73b0de.png)

**Comment by nclmrc** [comment]
Da questi dati @ FrancYescO ti viene in mente qualcosa?

**Comment by FrancYescO** [comment]
non vedo problemi... e' da analizzare meglio...

**Comment by nclmrc** [comment]
I valori adesso facendo degli iperf mi sembrano in linea con le performance dell'Adsl. Chiudo.

**Comment by nclmrc** [comment]
mi sembra ad oggi che sia cambiato poco, si può provare a mettere il campionamento a 10s
![immagine](https://user-images.githubusercontent.com/38593316/53901719-e58f4580-403f-11e9-810b-cc0a91a7e924.png)
grazie

**Comment by putipower** [comment]
https://ibb.co/gjjG0Fp  come mi funziona normalmente scaricando a 50mbit
https://ibb.co/5FC3b22 invece da luci sembra perfetto e....
https://ibb.co/SR3PmBv come apro il monitoraggio da luci anche sulla gui si mette a funzionare bene

**Comment by nclmrc** [comment]
Ho notato anche da Luci che il traffico dell'interfaccia atm wan è un po' irregolare, certamente non hai livelli della GUI dove il problema è molto accentuato. Se invece da Luci monitoro il traffico sul bridge  Lan è molto più regolare.

**Comment by nclmrc** [comment]
@Ansuel ho recuperato qualche grafico. Il problema sembra dell'interfaccia atmwan in generale. Ho fatto partire un iperf3 verso un server remoto sul Raspberry collegato sull'eth0. Come vedi i due grafici non sono simmetrici.
![immagine](https://user-images.githubusercontent.com/38593316/54488322-baf38700-48a0-11e9-8a29-01dc3dbdc6f2.png)
![immagine](https://user-images.githubusercontent.com/38593316/54488336-d78fbf00-48a0-11e9-8fbd-665e952fd52a.png)

**Comment by Ansuel** [comment]
l'interfaccia atmwan non conta in modo corretto i pacchetti... e comunque non sono bug risolvibili... se c'è un bug è nel driver che conta i pacchetti presente nel kernel

**Comment by nclmrc** [comment]
@Ansuel ho capito dove sta il problema. il raspberry ha un IP pubblico che ottiene tramite il PPPoE Relay presente nel DGA4132. appena butto giù il PPPoE sul raspberry il grafico torna apposto. Secondo te perchè il conto sballa quando si attiva il PPPoE Relay? Problema di driver?

**Comment by Ansuel** [comment]
credo sia più imputabile al fatto che con relay i pacchetti vanno inviati "raw" quindi non vengono contati...

**Comment by nclmrc** [comment]
E secondo te sull interfaccia eth0 vengono visualizzati correttamente?

**Comment by FrancYescO** [comment]
@nclmrc il traffico generato dal raspberry non lo vedi su nessun altra interfaccia? qualcuna che faccia riferimento alla linea dsl e non alle eth pero'

**Comment by nclmrc** [comment]
Sulla eth0 lo vedo e correttamente, come puoi vedere dal grafico.

**Comment by FrancYescO** [comment]
anzi a riguardare i grafici, anche sulla atmwan viene visualizzato bene il traffico, essendo encapsulato in frame PPP viene visualizzato a spruzzi (e qui forse la colpa e' dei driver kernel che aggiornano piu in ritardo) ma la somma della banda consumata in un lasso di tempo direi che combacia

**Comment by nclmrc** [comment]
provato a cambiare driver xdsl non è cambiato niente

**Comment by FrancYescO** [comment]
È proprio il driver del kernel che si occupa di questa roba (e quello non abbiamo ancora trovato modo di cambiarlo ne ovviamente di poterlo compilare)

**Comment by nclmrc** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/288#issuecomment-470246039 confermo che succede pure a me.

**Comment by FrancYescO** [comment]
Riesci a fare questa stessa prova dopoche apri luci?
https://github.com/Ansuel/tch-nginx-gui/issues/288#issuecomment-445554477

**Comment by nclmrc** [comment]
Dopo che ho aperto luci il traffico funziona regolarmente

Inviato da Samsung Galaxy Note 8

Il Mer 20 Mar 2019, 09:35 Francesco M <notifications@github.com> ha scritto:

**Comment by nclmrc** [comment]
Adesso ok
