### ISSUE TITLE
Disable technician account?

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#29]
There is a "technician" account in the /etc/passwd with an unknown password. and a restricted shell.

I have set the passwd to another one, but I doubt that many people think about that. I have no idea what to do in that respect, though. Maybe the passwords of the unix accounts should be changeable via the GUI in order to get the users attention? Or by disabling that account in the rootdevice script?

**Comment by Ansuel** [comment]
That account gives access to the limited shell clash
Nobody knows the password... Disabling that is very easy but can be useful if one day we discover the password and that shell is vulnerable.

**Comment by meyergru** [comment]
Yes, maybe I will need that pretty soon...
