### ISSUE TITLE
Wireless Control TG789vac V2 (16.3 Tiscali)

### ISSUE THREAD

**Issue by BreakSecurity** [Ansuel/tch-nginx-gui#291]
Device Model: TG789vac V2
Gui Version: 8.9.1 DEV

Description of problem: 
ENG -> Opening menu Wireless Control an error show up:
ITA -> Aprendo il menù a tendina controllo wireless viene riportato il seguente errore:
-Si è verificato un Internal Server Error, per favore contattare l´amministratore

Log:
daemon.err | nginx | 2018/10/21  04:41:56 [error] 12154#0: *10 lua entry thread aborted: runtime error:  [string "/modals/tod_wireless-modal.lp"]:299: attempt to index a nil  value

daemon.err | nginx | 2018/10/21  04:40:23 [error] 12154#0: *12 lua entry thread aborted: runtime error:  [string "/modals/tod_wireless-modal.lp"]:299: attempt to index a nil  value

**Comment by FrancYescO** [comment]
appena ti esce l'errore scrivi dai il comando `logread ` da ssh e posta qui le ultime righe (o prendi il log dalla modal di gestione mode sempre poco dopo che ti dato l'errore)

se intendi questa pagina io riesco ad aprirla tranquillamente su 8.8.90
![image](https://user-images.githubusercontent.com/4574593/47261628-73282980-d4d3-11e8-9b00-bf98edca154b.png)

**Comment by BreakSecurity** [comment]
Updated info

**Comment by BreakSecurity** [comment]
Any progress on this?

**Comment by Ansuel** [comment]
I need to know the WiFi interface present in the modem I suspect you don't
have guest WiFi at all...

Il giorno Mar 6 Nov 2018, 00:27 BreakSecurity <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment]
Tiscali have no guest wifi by default
[wireless.zip](https://github.com/Ansuel/tch-nginx-gui/files/2552111/wireless.zip)

**Comment by BreakSecurity** [comment]
Tiscali have no guest wifi by default... true it's not possible to add a button?

**Comment by FrancYescO** [comment]
Closing as this should be solved and the enchancement should be included in this issue https://github.com/Ansuel/tch-nginx-gui/issues/291
