### ISSUE TITLE
nginx error 500 TG789vac V2

### ISSUE THREAD

**Issue by johnyn2005** [Ansuel/tch-nginx-gui#295]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: tg789vac v2
Gui Version: latest stable gui

Description of problem: When i try to log in the gui it shows " 500 Internal Server Error
nginx "  The error.log in /tmp/log/nginx  shows : 2018/10/22 03:50:13 [error] 12265#0: *2 [lua] sessioncontrol.lua:79: get_datamodel_config(): failed to retrieve config: Connection refused, client: 192.168.1.5, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/"

**Comment by Ansuel** [comment]
Before the GUI upgrade it was working? 
Can you try to restart the modem?

**Comment by johnyn2005** [comment]
Well, i found out that i cant have both luci and your gui on the system ( https://github.com/nutterpc/tg-luci/issues/13 ), so, i uninstalled luci. Now it's loading the login.lp but it does not accept any of the admin or engineer credentials. Error log now shows : [lua] sessionmgr.lua:546: handleAuth(): Invalid login credentials, client: 192.168.1.35, server: localhost, request: "POST /authenticate HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/"

**Comment by FrancYescO** [comment]
factory reset the modem if you installed luci in the past, you must wait until a patch we need for luci to allow coexisting of luci and nginx webui

**Comment by johnyn2005** [comment]
After some trial and error , it appears that everything is working as it should. problem was some conflict i guess between root script sblocco.sh i use to unlock my modem initially and /init.d/rootdevice script. If i don't use the init.d script after installing gui everything works perfect.

**Comment by FrancYescO** [comment]
isn't clear what caused the conflict but i close this issue as it is resolved (and not directly GUI dependent)
