### ISSUE TITLE
theme dark/midnight fritz based

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#297]
Device Model: DGA ( DGA4132 )
Gui Version: 8.8.92

Description of problem:
On dark/midnight theme no diagnostics icons in main menu, only if you hoover on the icon displays
How to reproduce (if possible):

Media/Photos (if possible):
![schermata del 2018-10-23 10-08-14](https://user-images.githubusercontent.com/43514633/47345731-c523a780-d6ab-11e8-9fdb-a1557992e86b.png)

**Comment by dga4130-renato** [comment]
![schermata del 2018-10-23 10-12-00](https://user-images.githubusercontent.com/43514633/47345858-1af84f80-d6ac-11e8-960f-9153ea32a319.png)

**Comment by dga4130-renato** [comment]
ho sbagliato qualcosa

**Comment by FrancYescO** [comment]
probably fixed with https://github.com/Ansuel/tch-nginx-gui/pull/293

report fritz issue here https://github.com/Ansuel/tch-nginx-gui/issues/38
