### ISSUE TITLE
WiFi access need configuration change

### ISSUE THREAD

**Issue by ettoremazza** [Ansuel/tch-nginx-gui#300]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: DGA4130
Gui Version: 8.8.77
FW: AGTEF_1.2.0_001

a casa ho 30 device collegati in wifi, molti sono controlli di domotica, una intera serie (device PowaHome) non si è collegata al WiFi, ho scoperto che perchè si colleghino devo fare una qualunque modifica alla configurazione della rete WiFi (supportano solo 2.5GHz), poi dopo che si sono collegati posso rimettere a posto la modifica ed anche spegnere e riaccendere il WiFi, tutto funziona fino al reset del router.

**Comment by FrancYescO** [comment]
sicuro non sia semplicemente perché il wifi cambia di canale e quindi riescono a connettersi ?

**Comment by ettoremazza** [comment]
Guarda no, perchè se poi rimetto tutto come era anche se spengo e riaccendo il wifi si collegano, è solo dopo il reboot che non si collegano

**Comment by ettoremazza** [comment]
Seems solved on 8.9.57
