### ISSUE TITLE
Login screen on ssh change after every reboot

### ISSUE THREAD

**Issue by ettoremazza** [Ansuel/tch-nginx-gui#301]
Device Model: DGA4130
Gui Version: 8.8.77
FW: AGTEF_1.2.0_001

dopo ogni reboot via ssh, alla riconnessione in ssh, dopo gli ingredienti del cocktail, una riga degli hash (user & hash ?) sparisce, alla fine non compare nessuna delle righe che apparivano all'inizio.

Media/Photos (if possible):
https://www.dropbox.com/s/u2xznjfz5veevpq/Nuovo%20documento%20di%20testo.txt?dl=0

**Comment by nclmrc** [comment]
confermo anche con dga4132

**Comment by nclmrc** [comment]
@ansuel hai fatto qualche modifica con l ultima versione?
Adesso non lo noto più

**Comment by nclmrc** [comment]
O meglio da chi viene modificato?

**Comment by FrancYescO** [comment]
/etc/banner ... chi lo modifica (o meglio chi non lo fa uscire per la sua interezza) ... bho

**Comment by Ansuel** [comment]
Viene generato al primo reset e dovrebbe rimanere quello

Il Lun 29 Ott 2018, 03:02 Francesco M <notifications@github.com> ha scritto:

**Comment by nclmrc** [comment]
Ho visto che quando non esce fuori per intero se vedo il file in effetti è troncato. Ripristinato il file rom è tornato intero.

**Comment by nclmrc** [comment]
Sembrebbe risolto.
