### ISSUE TITLE
xDSL Driver for TG789vac V2

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#303]
We should include xDSL drivers for this model in the gui, 2 different versions I already found are A2pv6F039v2.d26q (FW 17.2 UNO) and A2pv6F039v2.d26m (FW 16.3 Tiscali)

**Comment by FrancYescO** [comment]
[A2pv6F039v2.d26q.zip](https://github.com/Ansuel/tch-nginx-gui/files/2521718/A2pv6F039v2.d26q.zip)

**Comment by lorenzocanale-LC** [comment]
In my modem there are 2 file, adsl_phy.bin and adsl_phy0.bin, do I need to copy both?

**Comment by FrancYescO** [comment]
looking at install script for other devices seems not

**Comment by FrancYescO** [comment]
implemented with https://github.com/Ansuel/tch-nginx-gui/commit/43bc842718fbd2938ed1a846f8b404181b960b6d
