### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by ghost** [Ansuel/tch-nginx-gui#304]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: DGA4132
Gui Version: 8.8.77

Description of problem:
Puoi inserire l'ultima versione della blacklist nella tua GUI? ho provato ad installarla manualmente e non funziona
How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
se non funziona perche' dovrebbe essere inserita ?

**Comment by Enrico9800** [comment]
magari lui ci riesce a farla funzionare.

**Comment by Ansuel** [comment]
dovresti chiedere sul punto a riguardo... comunque la gui usa lo script di installazione caricato sul server del creatore della blacklist quindi credo che andrebbe chiesto a lui di aggiornare...

attendo news a riguardo

**Comment by Enrico9800** [comment]
tutti dicono che c'è la versione 2.4

**Comment by Enrico9800** [comment]
io ho dovuto resettare il modem perchè forse non la ho installata correttamente

**Comment by FrancYescO** [comment]
si quando sono i risolti i problemi che possono avere le dev...

**Comment by FrancYescO** [comment]
per quanto io vedo dal sito di chi la ha sviluppata l'ultima versione della blacklist e' 2.1 http://blacklist.satellitar.it/

e come compatibilita' si riporta 

per il DGA4130: fino al FW 1.0.4
per il DGA4132: fino al FW 1.0.5

**Comment by Enrico9800** [comment]
questo è il fatto.. se si può inserire nella gui senza installarla tramite putty o telnet

**Comment by FrancYescO** [comment]
il punto e' che se non e' funzionante l'installazione tramite telnet di certo non possiamo metterlo tra le app installabili, e' da fixare alla fonte

**Comment by Ansuel** [comment]
dovresti convertire tutti gli address nella sezione voip e metterli ad ip e poi puoi usare tutti i dns che ti pare...

**Comment by Enrico9800** [comment]
Come? non so farlo

**Comment by Enrico9800** [comment]
> dovresti convertire tutti gli address nella sezione voip e metterli ad ip e poi puoi usare tutti i dns che ti pare... ma non è detto che funzioni, in linea teorica è così

quando rilasci l'aggiornamento della GUI stabile?

**Comment by FrancYescO** [comment]
Quando vedrai la notifica di aggiornamento

**Comment by Enrico9800** [comment]
> dovresti convertire tutti gli address nella sezione voip e metterli ad ip e poi puoi usare tutti i dns che ti pare... ma non è detto che funzioni, in linea teorica è così

Scusami per questa domanda.. ma hai il firmware per il TIM ONDA DN7000T?

**Comment by Enrico9800** [comment]
ansuel mi puoi rispondere?

**Comment by Ansuel** [comment]
ho cercato ma mi servono più informazioni su questo robo... 

produttore per esempio o info del genere...

**Comment by Enrico9800** [comment]
ONDA Communication SPA 
Model: DN7000T
Type: MF608
NMU: 463943HSDPA Wireless Access Terminal

**Comment by Enrico9800** [comment]
Versione Software modulo wireless | ITTIMWAP670M2V1.0.0B01
-- | --
Versione Software modulo controllo | ITTIMCRP670M2V1.0.0B01
Versione Software AP | ITTIMAPP670M2V1.0.0B01
Versione HardWare | P670M2-1.0.0

**Comment by Enrico9800** [comment]
se c'è anche il no brand per questo me lo passi, mi basta anche quello originale all'ultima versione

**Comment by Enrico9800** [comment]
se li metti ora su un file rar e lo carichi su mediafire o google drive mi posso sistemare questo modem

**Comment by Ansuel** [comment]
non so neanche come trovare il firm e mi chiedi il nobrand....

**Comment by Enrico9800** [comment]
su ilpuntotecnico un altro utente ti ha chiesto il firmware per questo modem e non lo hai trovato?

**Comment by Ansuel** [comment]
avevo cercato ma stesso risultato...

**Comment by Ansuel** [comment]
ma siete sicuri che esistono aggiornamenti per questo robo?

**Comment by Enrico9800** [comment]
si, ce il tasto "Aggiorna" e si deve scegliere il firmware manualmente

**Comment by Enrico9800** [comment]
su internet non si trova

**Comment by Enrico9800** [comment]
non è uscita la nuova GUI stabile?

**Comment by FrancYescO** [comment]
@Enrico9800 il pulsante per controllare gli aggiornamenti e' sulla GUI.

**Comment by Enrico9800** [comment]
non risultano nuove versioni

**Comment by FrancYescO** [comment]
non era poi cosi' difficile trovare la risposta da soli :)

**Comment by FrancYescO** [comment]
released blacklist 3.0
https://www.ilpuntotecnico.com/forum/index.php/topic,78288.msg242638.html#msg242638

**Comment by Enrico9800** [comment]
ancora nulla per la nuova blacklist sulla GUI? @Ansuel @FrancYescO

**Comment by FrancYescO** [comment]
È tutto nelle mani di chi l'ha sviluppata, e le risposte le hai già ricevute anche da parte sua
________________________________

**Comment by Enrico9800** [comment]
io voglio evitare di installarla manualmente per evitare di fare casini.. con la GUI DEV la blacklist integrata a quanto pare non fa sentire quel messaggio che li manda a quel paese.. fa ascoltare tipo il suono di occupato e basta.. @FrancYescO

**Comment by FrancYescO** [comment]
chiudo, le ultime versioni di blacklist dovrebbero installarsi correttamente da gui
