### ISSUE TITLE
Firmware upgrade removes GUI (and some settings)

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#31]
I did this twice today: I rooted new devices, brought them to to 1.0.3 in one way or the other (one device had 1.0.5 from factory, one 1.0.3), rooted them and installed the GUI via wget, tar and rootdevice force. Rebooted, configured everything to my liking. Then, I upgraded from 1.0.3 in bank_1 to 1.1.0 via the GUI.

Effect was always the same: Afterwards, I was back to TIM GUI and many settings were lost / set back to defaults. Luckily, root was not lost. Does a firmware upgrade always have to destroy the configuration settings?

**Comment by Ansuel** [comment]
for security reason (some settings change between version, every upgrade reset the modem) 
(if this is a problem just save /etc/config and restore it after a reset)

the upgrade process check for GUI.tar.bz2 in /root.
if it's present, the script apply it 

the upgare process of the GUI copy the new gui in root folder... manually installing it doesn't. Should i include the check to the rootdevice script? what do you think?

**Comment by meyergru** [comment]
Is the rootdevice script called every time on reboot? I.e. do you mean to re-apply the last GUI update in case a firmware update did override it? I think that would be a good idea, although not documenting it could be problematic - matter of fact I usually store the GUI.tar.bz2 to /root as well when I apply the mods initially.

**Comment by Ansuel** [comment]
the rootdevice script check only for root and other settings, doesn't check for the presence of the gui (you can have the script and the stock gui) 
the gui gets reinstalled in the update process of a new firmware and only there

**Comment by meyergru** [comment]
I just had this again: I had 1.0.3 on with the GUI and rooted, upgraded to 1.1.0 and afterwards the IP was back to 192.168.1.1, most settings and the GUI were gone (root was preserved, though). Oh, and /root was empty as well. So keeping GUI.tar.bz2 over a flash would not help.

What I also saw was this for the first call of "/etc/init.d/rootdevice force" (with GUI 7.7.6 on 1.0.3):

```
# /etc/init.d/rootdevice force
uci: Invalid argument
cat: can't open '/etc/crontabs/root': No such file or directory
uci: Parse error
Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

interface wan has no physdev or physdev has no suitable ip
mkdir: can't create directory '/overlay/bank_2': File exists
Unlocking /dev/mtd4 ...

Writing from /dev/mtd3 to /dev/mtd4 ...
#
```

This was followed by a reboot.

After having upgraded to 1.1.0 with lost settings, the next 'rootdevice force' gave:

```
# /etc/init.d/rootdevice force
cat: can't open '/etc/crontabs/root': No such file or directory
uci: Parse error
interface wan has no physdev or physdev has no suitable ip
```

Which is quite the same I usually see, but nevertheless scary because of the errors...

**Comment by Ansuel** [comment]
the error is just a problem with a uci settings that doesn't find where to apply (trying to find this as i'm too lazy to reset my modem.. ) 

can you try with the last dev? i changed a line in the upgrade script, now it should restore the gui file 

(also use sysupgrade command so we can see the log of the upgrade)

**Comment by meyergru** [comment]
This is minor, so closed...
