### ISSUE TITLE
Visualizzazione errata della GUI dai dispositivi mobile

### ISSUE THREAD

**Issue by umbertoB67** [Ansuel/tch-nginx-gui#310]
Device Model: MediaAccess TG789vac v2
Gui Version: 8.9.10

Description of problem:
La sezione "_Estensioni_" della GUI non è visualizzata correttamente dai dispositivi mobile. Nelle altre sezioni è presente un "a capo" tra le varie voci.

![image](https://user-images.githubusercontent.com/10993001/47619132-95293980-dadb-11e8-91df-55d5d731596a.png)

**Comment by umbertoB67** [comment]
Il problema persiste anche dopo l'ultimo aggiornamento.

**Comment by FrancYescO** [comment]
Non è ancora stato inserito negli aggiornamenti aspetta la prossima dev
________________________________
