### ISSUE TITLE
Improve English

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#311]
I am going to go and edit all of the modals and fix up any English problems.
Good example:

“Buttom” in the wifi card

**Comment by FrancYescO** [comment]
you have to change strings also in all .po files https://github.com/Ansuel/tch-nginx-gui/tree/master/decompressed/gui_file/www/lang or translation will be broken ... try to do all edits in just a single PR

**Comment by kevdagoat** [comment]
ok
