### ISSUE TITLE
stats issue

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#315]
Internet stats non riesce a recuperare l'indirizzo ip pppoe, che in effetti prende il modem.
![immagine](https://user-images.githubusercontent.com/38593316/47636571-15da4b00-db59-11e8-8591-ec37c2816001.png)

RISOLTO

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/47636620-43bf8f80-db59-11e8-8004-fd7dd0e5caf1.png)
![immagine](https://user-images.githubusercontent.com/38593316/47636635-54700580-db59-11e8-916d-fbe875b225c3.png)
traduzione REGISTRATO

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/47636669-75385b00-db59-11e8-8b73-374bc119ed50.png)
traduzione ATTIVO

**Comment by Ansuel** [comment]
dovrebbe essere fixato.

**Comment by nclmrc** [comment]
Con quale versione?

**Comment by Ansuel** [comment]
l'ultima il bug delle informazioni xdsl

**Comment by nclmrc** [comment]
Li segnali te gli altri issue?

**Comment by Ansuel** [comment]
si ci do un'occhiata e dico al traduttore che ci sono quelle stringhe da tradurre

**Comment by nclmrc** [comment]
Informazioni telefono non capisco come mai esce troncato

**Comment by Ansuel** [comment]
le magie del foglio di stile fatto a ca**o da me...

**Comment by nclmrc** [comment]
Anche attivo da ore minuti secondi sarebbe da tradurre

**Comment by nclmrc** [comment]
Sul "attivo da" c'è qualcosa di strano a volte viene in inglese altre in italiano. Da capire.
