### ISSUE TITLE
NO WAN-PPOE connection & Modem rewrittes /etc/config/network  after reboot

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#316]
Device Model: tg800vac firmware 16.3
GUI Version [ 8.9.25 ] 2018 

  

Description of problem: I cannot connect over ADSL with PPPoA+VC-MUX or PPPoE+LLC in IPV4,  DSLAM in ATM. I do not care about DHCP, nor IPOE [telstra default config is this one] nor IPV6.

- After a clean install of original telstra firmware 17.2 and 16.3:
the modem tries to use IPOE, but I enter my username and password for PPOE in the non-advanced GUI, the modem connects well to the internet, even after reboot. {I cannot choose between PPOE or PPOA though]

This GUI creates 
> config interface 'ppp'
> 	option proto 'pppoe'
> 	option metric '10'
> 	option keepalive '4,20'
> 	option iface6rd '0'
> 	option graceful_restart '1'
> 	option password 'XXXXXXXXXXX'
> 	option username 'XXXXXXXXXXXXXX'
> 	**option auto '1'**

- After  a clean install of firmware 16.3, then ansuel GUI Version [ 8.9.25 ] 2018,  the modem tries DHCP by default and it always fails, because it does not create the ''PPP'' interface

I do not use the wizard to set up my PPP connection, because when I try it the modem does not connect [creation of ''wan'' but not ''ppp'']

In the GUI, the ''advanced page'' for the PPP setup when PPOA is selected  is all empty [contrary to PPOE].  For PPOE, my settings about the change of DNS is reset, but the login+password remains.

SO I change manually the /etc/config/network with ''ipoe'' set to NOT start [auto= 0], ''ppp'' to start automatically at boot [auto=1] and some DNS changes for ''wan'' + NO ipv6 {I leave PPOE because currently I do not care much about PPOE versus PPOA]:

> config interface 'wan'
> 	option keepalive '4,20'
> 	option ifname 'atm_8_35'
> 	option username 'XXXXXXXXXXXXXXXXX'
> 	option iface6rd '0'
> 	option password 'XXXXXXXXXXXXXX'
> 	option metric '10'
> 	option graceful_restart '1'
> 	option proto 'pppoe'
> 	option auto '1'
> 	**option peerdns '0'
> 	list dns 'XXXXXXXXXXXXXX'**
> 	**option ipv6 '0'**
> 
> 
> config interface 'ppp'
> 	option proto 'pppoe'
> 	option metric '10'
> 	option keepalive '4,20'
> 	option iface6rd '0'
> 	option graceful_restart '1'
> 	option password 'XXXXXXXXXXX'
> 	option username 'XXXXXXXXXXXXXX'
> 	**option auto '1'**
> 
> config interface 'ipoe'
> 	option proto 'dhcp'
> 	option metric '1'
> 	option reqopts '1 3 6 43 51 58 59'
> 	option release '1'
> 	option iface6rd '0'
> 	option vendorid 'technicolor'
> 	option neighreachabletime '1200000'
> 	option neighgcstaletime '2400'
> 	option ipv6 '0'
> 	option ifname 'atm_8_35'
> 	**option auto '0'**

But after reboot,
 -  ''ipoe'' is set to start automatically again ''auto=1''
 - ''ppp'' is set to start manually [auto=0]
 - I lsoe my DNS config for ''wan'' and the line ''option ipv6 '0''' is removed
 
 This is the network file after a reboot [and this one connects to the internet of course] :
 

> config interface 'ppp'
> 	option proto 'pppoe'
> 	option metric '10'
> 	option keepalive '4,20'
> 	option iface6rd '0'
> 	option graceful_restart '1'
> 	option password 'XXXXXXXXXXXXXXX'
> 	option username 'XXXXXXXXXXXXXXXXXX'
> 	option auto '0'
> 	
> 	[ppp is still here so I still can connect to the internet]
> 
> 
> config interface 'ipoe'
> 	option proto 'dhcp'
> 	option metric '1'
> 	option reqopts '1 3 6 43 51 58 59'
> 	option release '1'
> 	option iface6rd '0'
> 	option vendorid 'technicolor'
> 	option neighreachabletime '1200000'
> 	option neighgcstaletime '2400'
> 	option ipv6 '1'
> 	option ifname 'atm_8_35'
> 	option auto '1'
> 	
> config interface 'wan'
> 	option keepalive '4,20'
> 	option ifname 'atm_8_35'
> 	option username 'XXXXXXXXXXXXXXXXX'
> 	option iface6rd '0'
> 	option password 'XXXXXXXXXXXXXXX'
> 	option metric '10'
> 	option graceful_restart '1'
> 	option proto 'pppoe'
> 	option auto '1'

	
	
With this dev version dated 29/10/2018, I cannot reach the telstra non-gui page [in order to go to broadband and set up the PPP connection]. THe old URL http://mygateway.gateway/telstra-modals/broadband.lp is a 404

**Comment by scotty03** [comment]
I have to ask why do you bother with the telstra gui? It is shit useless and I cant beleive people wanted that non advanced version page put back in.
Do your broadband and internet connection cards look like these?
https://imgur.com/a/hRsxpMM

**Comment by BreakSecurity** [comment]
#197 Read this should solve

**Comment by flywire** [comment]
> why do you bother with the telstra gui?

Because it is simple with help and has most of the functionality people need without getting lost in cards with complicated settings people don't understand. The real question is it works for thousands of Telstra customers so why isn't it working now?

@BreakSecurity - Can you flick [me](https://github.com/flywire) an email?

**Comment by Janaue** [comment]
well the telstra gui is simple and has zero bug. Also, it is the only one to create the PPP interface.

This night, the  modem lost the synchronization to the DSLAM, and again it changed my netowrk config. 
THe router was not rebooted.

The ''wan'' interface was set to DHCP once more and it lost my password+login and the DNS settings. The PPP interface and the IPOE interface were not changed, minus the auto start : PPP became auto=0 and IPOE auto=1]
In terms of LED: link LED = solid green, online LED = solid white.
THen I updated my network file and the two LEDs became solid green.

I do not understand why the modem forces DHCP.

I upload my pictures when ir works: when the modem overwrites the network file, the  Internet Access tile shows DHCP with a orange dot. THe xdsl parts never fails to synchronize. What fails is only the protocol for wan.
![sshot-185](https://user-images.githubusercontent.com/10972636/47698133-6e1f5480-dc0e-11e8-8b2d-d3d4263f0504.jpg)
![sshot-186](https://user-images.githubusercontent.com/10972636/47698134-6eb7eb00-dc0e-11e8-84f9-f5d36869889e.jpg)

**Comment by Janaue** [comment]
this is the log file at the time of the lost connection
![sshot-187](https://user-images.githubusercontent.com/10972636/47698479-cf93f300-dc0f-11e8-90b4-502e58a8d349.jpg)
[new 27.txt](https://github.com/Ansuel/tch-nginx-gui/files/2528190/new.27.txt)

**Comment by scotty03** [comment]
Well it must be an ADSL bug because I am on VDSL and I have none of these issues with setting up my connection from Ansuel GUI and it sticks and nothing changes. Same modem TG800vac and 16.3 firmware.
I don't bother with the Telstra GUI because I think it is shit and I refuse to use it and it has quite a few bugs believe me LOL

**Comment by Janaue** [comment]
Yeah I think there is a bug only for ADSL. Users on VDSL report that the modem works well.


THis is the log when it connects after  I manually edit my network file. I think I restarted twice with ''/etc/init.d/network restart'' because the first time I forgot to add my DNS for ''wan''

[new 288.txt](https://github.com/Ansuel/tch-nginx-gui/files/2528331/new.288.txt)

**Comment by Janaue** [comment]
It looks like it is wansensing which overwrites the file. I disabled it and rebooted and my file has not been changed.
I did


But this guy says 

> Need to disable wansensing…. wansensing changes the “wan” interface back to DHCP after link down/up…
https://www.crc.id.au/hacking-the-technicolor-tg799vac-and-unlocking-features/comment-page-1/

however my wansensing file still says

> config wansensing 'global'
> 	option enable '1'
> 	option autofailover 'readonly'
> 	option initmode 'L2Sense'
> 	option tracelevel '3'
> 	option l2type 'ADSL'
> 	option l3type 'L3PPP'

So I prefer to reboot once more and see if I need to set option enable '0', before closing the issue

**Comment by FrancYescO** [comment]
disabling wansing will probably break a lot of things.. patching is a better choice.. look at https://github.com/Ansuel/tch-nginx-gui/issues/258#issuecomment-431572177 and in general to `/etc/wansensing/L2EntryExit.lua` file to see how is acting

**Comment by Janaue** [comment]
Can you tell me what wansensing is and what those L2type and L3type, l2type, L3ppp mean.

**Comment by Ansuel** [comment]
we should modify wansensing to check for ADSL i think

dhcp is the default mode when no connection is autodetected... so there is a problem with wansensing not detecting the adsl up... i really think there is some hardcoded interface also in wansensing script..

**Comment by FrancYescO** [comment]
works well if you don't have to change connection mode, it's not a solution for the GUI

**Comment by FrancYescO** [comment]
@Janaue could you post here your `/etc/wansensing/L2EntryExit.lua` file

**Comment by Janaue** [comment]
Here is the file wansensing in my /overlay/bank_1 for tg800vac with firmware 16.3 and GUI Version [ 8.9.42 ] 2018

> config wansensing 'global'
> 	option enable '1'
> 	option autofailover 'readonly'
> 	option initmode 'L2Sense'
>     **option tracelevel '3'**
> 	**option l2type 'ADSL'**
> 	**option l3type 'L3PPP'** 
> 
> config L2State
> 	option name 'L2Sense'
> 	option entryexits 'L2EntryExit'
> 	option mains 'L2Main'
> 	option timeout '5'
> 
> config L3State
> 	option name 'L3Sense'
> 	option timeout '5'
> 	option entryexits 'L3EntryExit'
> 	option mains 'L3Main'
> 
> config L3State
> 	option name 'L3PPP'
> 	option timeout '60'
> 	option entryexits 'L3PPPEntryExit'
> 	option mains 'L3PPPMain'
> 
> config L3State
> 	option name 'L3DHCPSense'
> 	option timeout '5'
> 	option entryexits 'L3DHCPSenseEntryExit'
> 	option mains 'L3DHCPSenseMain'
> 
> config L3State
> 	option name 'L3DHCP'
> 	option timeout '300'
> 	option fasttimeout '10'
> 	option entryexits 'L3DHCPEntryExit'
> 	option mains 'L3DHCPMain'

the file wansensing in /overlay/bank_2 of the original telstra with firmware 16.3 is the same, but without the bold lines
>     **option tracelevel '3'**
> 	**option l2type 'ADSL'**
> 	**option l3type 'L3PPP'**

**Comment by Janaue** [comment]
Here is the file wansensing in my /overlay/bank_1 for tg800vac with firmware 16.3 and GUI Version [ 8.9.42 ] 2018

> config wansensing 'global'
> 	option enable '1'
> 	option autofailover 'readonly'
> 	option initmode 'L2Sense'
>     **option tracelevel '3'**
> 	**option l2type 'ADSL'**
> 	**option l3type 'L3PPP'** 
> 
> config L2State
> 	option name 'L2Sense'
> 	option entryexits 'L2EntryExit'
> 	option mains 'L2Main'
> 	option timeout '5'
> 
> config L3State
> 	option name 'L3Sense'
> 	option timeout '5'
> 	option entryexits 'L3EntryExit'
> 	option mains 'L3Main'
> 
> config L3State
> 	option name 'L3PPP'
> 	option timeout '60'
> 	option entryexits 'L3PPPEntryExit'
> 	option mains 'L3PPPMain'
> 
> config L3State
> 	option name 'L3DHCPSense'
> 	option timeout '5'
> 	option entryexits 'L3DHCPSenseEntryExit'
> 	option mains 'L3DHCPSenseMain'
> 
> config L3State
> 	option name 'L3DHCP'
> 	option timeout '300'
> 	option fasttimeout '10'
> 	option entryexits 'L3DHCPEntryExit'
> 	option mains 'L3DHCPMain'

the file wansensing in /overlay/bank_2 of the original telstra with firmware 16.3 is the same, but without the bold lines
>     **option tracelevel '3'**
> 	**option l2type 'ADSL'**
> 	**option l3type 'L3PPP'**

**Comment by Janaue** [comment]
this is /etc/wansensing/L2EntryExit.lua for tg800vac with firmware 16.3 and GUI Version [ 8.9.42 ] 2018 
```

local M = {}

function M.entry(runtime)
    local uci = runtime.uci
    local conn = runtime.ubus

    if not uci or not conn then
        return false
    end

    local x = uci.cursor()

    local currentstate = x:get("xdsl", "dsl0", "enabled")
    if currentstate ~= "1" then
        x:set("xdsl", "dsl0", "enabled", "1")
        x:commit("xdsl")
        os.execute("/etc/init.d/xdsl reload")
    end

    -- initialize ltebackup_delay_counter
    runtime.ltebackup_delay_counter = 0

    return true
end

function M.exit(runtime, l2type)
    local uci = runtime.uci

    if not uci then
        return false
    end

    -- restore factory defaults
    local x = uci.cursor()

    return true
end

return M

```

**Comment by FrancYescO** [comment]
looks like the wansensing on telastra is a little different and have different file for each connection type, could you post the full zip of `/etc/wansensing/`

**Comment by Janaue** [comment]
[wansensing.zip](https://github.com/Ansuel/tch-nginx-gui/files/2546043/wansensing.zip)
here are all the files /etc/wansensing/  for tg800vac with firmware 16.3 and GUI Version [ 8.9.52 ]

/etc/wansensing$ ls
L2EntryExit.lua
L2Main.lua
L3DHCPEntryExit.lua
L3DHCPMain.lua
L3DHCPSenseEntryExit.lua
L3DHCPSenseMain.lua
L3EntryExit.lua
L3Main.lua
L3PPPEntryExit.lua
L3PPPMain.lua

**Comment by flywire** [comment]
I think https://github.com/Ansuel/tch-nginx-gui/issues/114#issue-354256560 is related, same issue with Telstra TG799vac GUI Version 8.9.52.

Every two minutes in log:
`daemon.err    odhcp6c[2879]    Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)`

**Comment by Ansuel** [comment]
@Janaue can you test with latest version ?

**Comment by Janaue** [comment]
before uptadting the GUI to 


    /etc/init.d/wansensing enable
    /etc/init.d/wansensing start

wchich dropped the PPP connection, LED white, then it connected again, 2 LED green. Then I rebooted  

my netowrk file is changed for the wan part where it removes my DNS settings, and ipv6=0, but this time it keeps option auto '1'. For PPP it puts option auto '0', and for ipoe it puts 	option auto '1'


config interface 'ipoe'
	option proto 'dhcp'
	option metric '1'
	option reqopts '1 3 6 43 51 58 59'
	option release '1'
	option iface6rd '0'
	option vendorid 'technicolor'
	option neighreachabletime '1200000'
	option neighgcstaletime '2400'
	option ipv6 '1'
	option ifname 'atm_8_35'
	option auto '1'

config interface 'ppp'
	option proto 'pppoe'
	option metric '10'
	option keepalive '4,20'
	option iface6rd '0'
	option graceful_restart '1'
	option password 'XXXXXXXXXXXXXXX'
	option username XXXXXXXXXXXXXXX'
	option auto '0'



config interface 'wan'
	option ifname 'atm_8_35'
	option username 'XXXXXXXXXXXXXXXXXX'
	option iface6rd '0'
	option password 'XXXXXXXXXXXXXXX'
	option metric '10'
	option proto 'pppoe'
	option auto '1'
	
	
	
this config connects to the internet
	 
	
I changed my network file to what works : [so adding DNS and no ipv6], then I reboot and 3 led green, but the file network is again modified



config interface 'ipoe'
	option proto 'dhcp'
	option metric '1'
	option reqopts '1 3 6 43 51 58 59'
	option release '1'
	option iface6rd '0'
	option vendorid 'technicolor'
	option neighreachabletime '1200000'
	option neighgcstaletime '2400'
	option ipv6 '1'
	option ifname 'atm_8_35'
	option auto '1'

config interface 'ppp'
	option proto 'pppoe'
	option metric '10'
	option keepalive '4,20'
	option iface6rd '0'
	option graceful_restart '1'
	option password 'XXXXXXXXXXXXXXXX'
	option username 'XXXXXXXXXXXXXXXXXXXXXXX'
	option auto '0'

	config interface 'wan'
	option keepalive '4,20'
	option ifname 'atm_8_35'
	option username 'XXXXXXXXXXXXXXXXXXX'
	option iface6rd '0'
	option password 'XXXXXXXXXXXXXXXXXX'
	option metric '10'
	option graceful_restart '1'
	option proto 'pppoe'
	option auto '1'

**Comment by Ansuel** [comment]
actually the ppp interface should be removed and not used by the modem.... 

anyway can you update the problem ? or it's the same?

**Comment by FrancYescO** [comment]
@Janaue the only difference in the config files you posted are these value added in `wan` section
```
option keepalive '4,20'
option graceful_restart '1'
```
could you clarify what is changing (and does not have to) after a reboot?

**Comment by Janaue** [comment]
ok,
yes the two lines 

> option keepalive '4,20'
> option graceful_restart '1'

are added by the router.

for ''wan'' , The lines that I want to keep are

> 	option auto '1'
> 	option peerdns '1'
> 	list dns 'XXXXXXXXXXXXX'
> 	list dns '8.8.8.8'
> 	option ipv6 '0'

and it is possible, since I do not need ''ipoe'', disable ''ipoe'' at boot with '' option auto '0''' [the router always puts  option auto '1']

**Comment by Ansuel** [comment]
ummm yes ppp should not be used anyway but the modem anyway will check about dns and auto...

**Comment by Janaue** [comment]
I reseted the router, and this time I connected to the internet for the first time with the original telstra gui , instead of waiting after the Ansuel GUI.
Internet works well now, even after a reboot. But the rooter always remove

> 	option peerdns '1'
> 	list dns 'XXXXXXXXXXXXX'
> 	list dns '8.8.8.8'
> 	option ipv6 '0'

for wan, either after a reboot or after a restart of the XDSL driver.

I upload 3 files

- first file is original network config and wansensing with stock telstra firmware and gui
[wansensing telstra gui original no internet conenction yet.zip](https://github.com/Ansuel/tch-nginx-gui/files/2584204/wansensing.telstra.gui.original.no.internet.conenction.yet.zip)

[wansensing telstra gui original no internet conenction yet.txt](https://github.com/Ansuel/tch-nginx-gui/files/2584207/wansensing.telstra.gui.original.no.internet.conenction.yet.txt)
[network telstra gui original no internet conenction yet.txt](https://github.com/Ansuel/tch-nginx-gui/files/2584209/network.telstra.gui.original.no.internet.conenction.yet.txt)


- second file is when I enter my login and telstra create the Internet connection
[wansensing original telstra internet ok.zip](https://github.com/Ansuel/tch-nginx-gui/files/2584238/wansensing.original.telstra.internet.ok.zip)
[wansensing original telstra internet ok.txt](https://github.com/Ansuel/tch-nginx-gui/files/2584240/wansensing.original.telstra.internet.ok.txt)
[network original telstra internet ok.txt](https://github.com/Ansuel/tch-nginx-gui/files/2584244/network.original.telstra.internet.ok.txt)

- then third file is after I install GUI Version [ 8.9.58 ] 2018  
[wansensing ansuel gui 8.9.58 internet ok.zip](https://github.com/Ansuel/tch-nginx-gui/files/2584249/wansensing.ansuel.gui.8.9.58.internet.ok.zip)
[wansensing ansuel gui 8.9.58 internet ok.txt](https://github.com/Ansuel/tch-nginx-gui/files/2584250/wansensing.ansuel.gui.8.9.58.internet.ok.txt)
[network ansuel gui 8.9.58 internet ok.txt](https://github.com/Ansuel/tch-nginx-gui/files/2584252/network.ansuel.gui.8.9.58.internet.ok.txt)

**Comment by Ansuel** [comment]
try latest dev pls

**Comment by nclmrc** [comment]
Last gui update
Upgrade Script: Downloading GUI file...

Upgrade Script: Downloaded gui with hash: 64793bd99a275440f1899130961242fb
Upgrade Script: Dev branch detected... Checking for newer version in stable...

Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.09.60
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
/etc/rc.common: line 1: s/\..*//: not found
Upgrade Script: Upgrade Done

**Comment by Ansuel** [comment]
@nclmrc you don't have this problem right?

**Comment by nclmrc** [comment]
No

**Comment by Janaue** [comment]
okay so I did a reset the router again
remove on bank1  root by ansuel in ansuel gui
install firmware 16.3 telstra on bank2
delete overlay of bank1
install telstra gui on bank1, connect to the internet OK
install GUI Version [ 8.9.64 ] 2018 on bank1


xdsl LED is green, but login LEd is white. My logins are not erased though, so I do not understand why it cannot log in.

I replaced this failed network file of GUI Version [ 8.9.64 ] with the working network file of GUI Version [ 8.9.58 ] [see uploads in the message above] + my DNS settings for ''wan''

	option peerdns '1'
	list dns '8.8.8.8'
	option ipv6 '0'
	
then I reboot and the login LEd is green and my DNS settings are still here. SO that works, but it is odd that It cannot connect 
[network 8.9.64 login LED is white no internet.txt](https://github.com/Ansuel/tch-nginx-gui/files/2592573/network.8.9.64.login.LED.is.white.no.internet.txt)

**Comment by Janaue** [comment]
On a side note, it seems I have less errors about  Failed to send DHCPV6 message to ff02::1:2
```
	Line 2466: Sun Nov 18 08:02:19 2018 daemon.err odhcp6c[6195]: Failed to send DHCPV6 message to ff02::1:2 (Cannot assign requested address)
	Line 3508: Sun Nov 18 08:13:39 2018 daemon.err odhcp6c[4757]: Failed to send DHCPV6 message to ff02::1:2 (Cannot assign requested address)
	Line 3676: Sun Nov 18 08:13:52 2018 daemon.err odhcp6c[5980]: Failed to send DHCPV6 message to ff02::1:2 (Cannot assign requested address)
	Line 4796: Sun Nov 18 08:17:11 2018 daemon.err odhcp6c[6222]: Failed to send DHCPV6 message to ff02::1:2 (Cannot assign requested address)
	Line 5870: Sun Nov 18 08:25:52 2018 daemon.err odhcp6c[4784]: Failed to send DHCPV6 message to ff02::1:2 (Cannot assign requested address)
	Line 5985: Sun Nov 18 08:26:01 2018 daemon.err odhcp6c[5691]: Failed to send DHCPV6 message to ff02::1:2 (Cannot assign requested address)

```

before this message appears every 2 minutes

**Comment by Ansuel** [comment]
the dhcpv6 message can be ignored you just need to kill and disable the process... 

odhcp6c 

sooo this problem is solved?

**Comment by Janaue** [comment]
Yes it is good

**Comment by Janaue** [comment]
yeah it is ok

**Comment by flywire** [comment]
> the dhcpv6 message can be ignored you just need to kill and disable the process...

Why doesn't the gui do that?

**Comment by Ansuel** [comment]
thet process is need for ipv6 connection so disable it creates problem if someone configure ipv6 on his own

**Comment by flywire** [comment]
> it creates problem if someone configure ipv6 on his own

??? it is broken anyway - https://github.com/Ansuel/tch-nginx-gui/issues/114#issuecomment-416363965
> On openwrt on this old base it think it's quite broken...

How is the process killed (for testing)?
```
root@mygateway:~# pkill -x odhcp6c
-ash: pkill: not found
```

**Comment by Janaue** [comment]
if I let the original telstra gui create the PPPOE connection, then I update the ansuel GUI, I get back the XDSL graphics
