### ISSUE TITLE
Trasferimento di chiamata

### ISSUE THREAD

**Issue by umbertoB67** [Ansuel/tch-nginx-gui#319]
Sarebbe utile avere sul router una funzionalità come quella presente sulla Vodafone Station Revolution che consente di visualizzare lo stato del servizio e attivare/disattivare il trasferimento di chiamata nelle sue varie opzioni (sempre, dopo tot secondi, ecc.) direttamente dalla GUI senza, quindi, digitare nulla sul telefono.
Che ne pensate? Si potrebbe metterla in cantiere?
Grazie. Ciao.

**Comment by Ansuel** [comment]
sul telefono come funziona ? descrivi

**Comment by umbertoB67** [comment]
Dal telefono, tramite una specifica sequenza di tasti, posso attivare i vari trasferimenti di chiamata.
Qui trovi il dettaglio dei comandi per verificare/attivare/disattivare i vari servizi: https://assistenza.tiscali.it/internet-telefono/guida/trasferimento-di-chiamata/.
Secondo me i più importanti sono:
- Trasferimento   di chiamata non condizionato
- Trasferimento   di chiamata in caso di mancata risposta (circa 20/30 secondi - 5/6 squilli)
- Trasferimento   di chiamata in caso di occupato
- Disattivazione di tutti i trasferimenti di chiamata

Ciao.

**Comment by Ansuel** [comment]
le opzioni ci sono... tab servizi

**Comment by umbertoB67** [comment]
Se intendi qui non capisco come fare ad attivare o disattivare i vari tipo di trasferimento
![image](https://user-images.githubusercontent.com/10993001/47745342-bdec3300-dc83-11e8-8ba1-9357f201599c.png)

**Comment by FrancYescO** [comment]
almeno per la visualizzazione stato credo sia tecnicamente non fattibile, perche' il responso tiscali lo da con la voce automatica, quindi e' proprio il server sip a rispondere

**Comment by Ansuel** [comment]
da alcuni test interni reindirizzamento e altro è una cosa che gestisce il server sip dell'isp e non il modem...

la vodafone station quini fa semplicemente una chiamata nascosta con le numerazioni standard per attivare questi servizi... dovremmo indagare se possiamo inviare robe del genere noi...

**Comment by Enrico9800** [comment]
> da alcuni test interni reindirizzamento e altro è una cosa che gestisce il server sip dell'isp e non il modem...
> 
> la vodafone station quini fa semplicemente una chiamata nascosta con le numerazioni standard per attivare questi servizi... dovremmo indagare se possiamo inviare robe del genere noi...

Ma quando esce la nuova GUI Stabile? quelle DEV che c'erano sul sito vedo che sono sparite. come mai?

**Comment by FrancYescO** [comment]
@Enrico9800 la stable esce quando esce, le dev sono nella branch dev, smettila di chiedere.

**Comment by Enrico9800** [comment]
è gia 1 mese che non viene aggiornata

**Comment by FrancYescO** [comment]
e quindi?

**Comment by Enrico9800** [comment]
mi da un pò di problemi.

**Comment by FrancYescO** [comment]
perfetto segnalali e quando saranno risolti li vedrai risolti

**Comment by umbertoB67** [comment]
Ciao @Ansuel la chiusura è dovuta al fatto che è stata implementata questa funzionalità?
Grazie. Ciao.
