### ISSUE TITLE
Port Forwarding using IP

### ISSUE THREAD

**Issue by shin-01** [Ansuel/tch-nginx-gui#321]
It would be nice to allow port porwarding using IP address and not only MAC address. 

Adding a field with the IP, and let the user select if use IP or Mac Address for that specific rule would be perfect

**Comment by kevdagoat** [comment]
The problem with this is that as soon as you renew the dhcp lease the device will have a different IP address, that is why this doesn’t exist as a MAC address doesnt change.

**Comment by FrancYescO** [comment]
@kevdagoat you can set static DHCP lease or manually put a fixed ip on the device, but yes the idea to use MAC is because it allow to select a definded device independently from the IP assigned

**Comment by kevdagoat** [comment]
> you can set static DHCP lease or manually put a fixed ip on the device

I do realize that. It would be a lot easier just doing it for the mac though!

**Comment by Ansuel** [comment]
we can readd the ip option actually... and put an alert to advice to use mac box instead of ip.... 
The important thing for luci is to have one of them... 
@FrancYescO what do you think ?

**Comment by FrancYescO** [comment]
what about adding the IP field and validate if at least one of the IP or MAC is in?
