### ISSUE TITLE
Wiki and Future Ideas for this project.

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#322]
I cannot edit it?

@FrancYescO I think you are the only one who can because of your status of collaborator.

We really need to create an organisiation and use it to develop

**Comment by kevdagoat** [comment]
We most likely also want to start looking at automating code checking and to-do’s as I sometimes get lost when looking through stuff that needs to be fixed!

Stuff that I would like to see:

- [Diagnostics script for ease of issue reporting]

- [Good wiki, explaining how to write code for these modems that utilises transformer]

**Comment by FrancYescO** [comment]
are you sure you have not possiblity to ask for PR to https://github.com/Ansuel/tch-nginx-gui.wiki.git ?

**Comment by kevdagoat** [comment]
![image](https://user-images.githubusercontent.com/42062334/47779223-9654a380-dd33-11e8-9184-7598055eb2d5.png)

**Comment by FrancYescO** [comment]
also to me it gives 404, you have to use the link via git cli.

**Comment by kevdagoat** [comment]
*sigh*

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
will close for now
