### ISSUE TITLE
Message odhcp6c 	Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#323]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: tg800
Gui Version: GUI Version [ 8.9.37 ] 2018 Changelog

Description of problem:
I keep having this message in the log. From googling, I see it is a common error, but I think I do not have it on firmware 16.3 by telstra.
I do not use IPv6 either for the PPP connection of the LAN, no ipv6 enabled for the DHCP. so this is strange.

Do you have it too?

> 
> daemon.err | odhcp6c[5843] | Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)
> -- | -- | --
> 

here https://forum.openwrt.org/t/daemon-err-odhcp6c-failed-to-send-dhcpv6-message-to-ff02-1-2-permission-denied/4623/3
 
> 
> ff02::1:2 is a message sent to all DHCP servers and relay agents on the local network segment (defined in RFC 3315)
> Probably a router on the network is not able to respond properly. Changing this is the best solution. An other solution is below.
> 
> A solution to get rid of the message is to remove IPV6 from the wan.

but I already have disabled ipv6 for wan:

> 
> config interface 'wan'
> 	option ifname 'atm_8_35'
> 	option username 'XXXXXXXXXXXXXXX'
> 	option iface6rd '0'
> 	option password 'XXXXXXXXXXXXXXXXX'
> 	option metric '10'
> 	option proto 'pppoe'
> 	option auto '1'
> 	option peerdns '1'
> 	option ipv6 '0'
> 	list dns 'XXXXXXXXXXXX'
> 	list dns '8.8.8.8'
>

**Comment by kevdagoat** [comment]
We cannot remove this from the /etc/config/network because some people have working  IPv6 (eg. My TG799vac) and would like to keep it.

**Comment by kevdagoat** [comment]
If you want to stop it run:
/etc/init.d/odhcpd stop
/etc/init.d/odhcpd disable
