### ISSUE TITLE
Telnet TG799

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#326]
Found this: 
[telnet.zip](https://github.com/Ansuel/tch-nginx-gui/files/2533853/OneDrive-2018-10-31.zip)

Is a Telnet binary for TG799. Would you like an install script and pull request?

Edit: Thanks Suse10 if you are reading this.

**Comment by scotty03** [comment]
LOL the truth is out there.
thewacker21 strikes again this time with suse10's telnet script

**Comment by Ansuel** [comment]
can someone tell me if this works with tg800 or not? anyway will add this to the gui next update...

**Comment by scotty03** [comment]
> 
> 
> can someone tell me if this works with tg800 or not? anyway will add this to the gui next update...
> if i have permission...

Ansuel it works on a TG800vac if you use the busybox_telnet from the DGA4130 & DGA4132
The busybox_telnetd in the archive uploaded needs to be rename busybox_telnet and one other file needs to renamed to telnet and the install script needs to be edited to get rid of the 'd' on the end.
renamed & edited and the correct busybox_telnet file and it works perfect on the 789, 799 & 800 with the GUI installed and the system extras tile allows you to enable/disable
You don't need permission I am just blowing smoke up kevdagoats ass........It's an Australian thing :)

**Comment by Ansuel** [comment]
ahahaha anyway will install in another way... will use the same way i use for dga to add telnet

**Comment by scotty03** [comment]
Young boys never quite get Aussie humour but you will one day i promise.
Once you are old enough to drink maybe. Then again

**Comment by kevdagoat** [comment]
Or maybe they are too sensible :)

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
> just to confirm telnetd is a link to busybox right?
Yep

**Comment by scotty03** [comment]
Just explaining in case he wants to update now  manually. Will be good when
in GUI as standard

**Comment by flywire** [comment]
> ... strikes again this time with suse10's telnet script

trawling through posts to integrate features seems worthwhile to me.

**Comment by Ansuel** [comment]
added tell me if id does work
