### ISSUE TITLE
DebugHelper Script

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#327]
I am in the process of writing a debug log generator to make it easier for users to report bugs and issues.
I have so far 
- Device info
   - product name
   - friendly name
   - ISP
   - FW version
   - GUI Skin
- List of installed extras
- Errors in log
- Processes
- Config file list
- GUI install log

Do you have any more suggestions?

Sample output:
___________________________________CONFIG_________________________________________
Product Name: Technicolor TG
Friendly Name: Technicolor TG799vac
ISP Name: Telstra
FW Version: 16.3.7567-2521030-20170614084458-887a8c777ed8527277d7137ed9149816c889cf1d
GUI Skin: green
__________________________________LOG_________________________________________
Mon Oct 29 19:49:02 2018 daemon.err transformer: [wansensing] L2Main.check(timeout) throws error :/etc/wansensing/L2Main.lua:60: attempt to concatenate local 'mobile' (a nil value)
Mon Oct 29 19:49:02 2018 daemon.err transformer: [wansensing] stopped due error in scriptL2Main
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: /usr/bin/lua: /usr/lib/lua/wansensingfw/washelper.lua:110: assertion failed!
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: stack traceback:
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	[C]: in function 'assert'
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/usr/lib/lua/wansensingfw/washelper.lua:110: in function </usr/lib/lua/wansensingfw/washelper.lua:104>
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	(tail call): ?
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/usr/lib/lua/wansensingfw/l2wasmachine.lua:41: in function 'update'
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/usr/lib/lua/wansensingfw/init.lua:35: in function 'cb'
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/usr/lib/lua/wansensingfw/wasasync.lua:19: in function </usr/lib/lua/wansensingfw/wasasync.lua:19>
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	[C]: in function 'run'
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/usr/lib/lua/wansensingfw/wasasync.lua:86: in function 'start'
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/usr/lib/lua/wansensingfw/init.lua:172: in function 'start'
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	/sbin/wansensing.lua:20: in main chunk
Mon Oct 29 19:49:02 2018 daemon.err wansensing.lua[2820]: 	[C]: ?
Mon Oct 29 19:49:11 2018 daemon.err transformer: [wansensing] L2Main.check(timeout) throws error :/etc/wansensing/L2Main.lua:60: attempt to concatenate local 'mobile' (a nil value)
Mon Oct 29 19:49:11 2018 daemon.err transformer: [wansensing] stopped due error in scriptL2Main
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: /usr/bin/lua: /usr/lib/lua/wansensingfw/washelper.lua:110: assertion failed!
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: stack traceback:
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	[C]: in function 'assert'
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/usr/lib/lua/wansensingfw/washelper.lua:110: in function </usr/lib/lua/wansensingfw/washelper.lua:104>
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	(tail call): ?
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/usr/lib/lua/wansensingfw/l2wasmachine.lua:41: in function 'update'
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/usr/lib/lua/wansensingfw/init.lua:35: in function 'cb'
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/usr/lib/lua/wansensingfw/wasasync.lua:19: in function </usr/lib/lua/wansensingfw/wasasync.lua:19>
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	[C]: in function 'run'
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/usr/lib/lua/wansensingfw/wasasync.lua:86: in function 'start'
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/usr/lib/lua/wansensingfw/init.lua:172: in function 'start'
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	/sbin/wansensing.lua:20: in main chunk
Mon Oct 29 19:49:11 2018 daemon.err wansensing.lua[3254]: 	[C]: ?
Mon Oct 29 19:49:19 2018 daemon.err transformer: [wansensing] L2Main.check(timeout) throws error :/etc/wansensing/L2Main.lua:60: attempt to concatenate local 'mobile' (a nil value)
Mon Oct 29 19:49:19 2018 daemon.err transformer: [wansensing] stopped due error in scriptL2Main
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: /usr/bin/lua: /usr/lib/lua/wansensingfw/washelper.lua:110: assertion failed!
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: stack traceback:
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	[C]: in function 'assert'
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	/usr/lib/lua/wansensingfw/washelper.lua:110: in function </usr/lib/lua/wansensingfw/washelper.lua:104>
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	(tail call): ?
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	/usr/lib/lua/wansensingfw/l2wasmachine.lua:41: in function 'update'
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	/usr/lib/lua/wansensingfw/init.lua:35: in function 'cb'
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	/usr/lib/lua/wansensingfw/wasasync.lua:19: in function </usr/lib/lua/wansensingfw/wasasync.lua:19>
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	[C]: in function 'run'
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	/usr/lib/lua/wansensingfw/wasasync.lua:86: in function 'start'
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	/usr/lib/lua/wansensingfw/init.lua:172: in function 'start'
Mon Oct 29 19:49:19 2018 daemon.err wansensing.lua[3559]: 	[C]: ?
Mon Oct 29 19:49:25 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
Mon Oct 29 19:49:27 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
Mon Oct 29 19:49:28 2018 daemon.err transformer: [wansensing] L2Main.check(timeout) throws error :/etc/wansensing/L2Main.lua:60: attempt to concatenate local 'mobile' (a nil value)
Mon Oct 29 19:49:28 2018 daemon.err transformer: [wansensing] stopped due error in scriptL2Main
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: /usr/bin/lua: /usr/lib/lua/wansensingfw/washelper.lua:110: assertion failed!
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: stack traceback:
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	[C]: in function 'assert'
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/usr/lib/lua/wansensingfw/washelper.lua:110: in function </usr/lib/lua/wansensingfw/washelper.lua:104>
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	(tail call): ?
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/usr/lib/lua/wansensingfw/l2wasmachine.lua:41: in function 'update'
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/usr/lib/lua/wansensingfw/init.lua:35: in function 'cb'
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/usr/lib/lua/wansensingfw/wasasync.lua:19: in function </usr/lib/lua/wansensingfw/wasasync.lua:19>
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	[C]: in function 'run'
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/usr/lib/lua/wansensingfw/wasasync.lua:86: in function 'start'
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/usr/lib/lua/wansensingfw/init.lua:172: in function 'start'
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	/sbin/wansensing.lua:20: in main chunk
Mon Oct 29 19:49:28 2018 daemon.err wansensing.lua[3919]: 	[C]: ?
Mon Oct 29 19:49:37 2018 daemon.err transformer: [wansensing] L2Main.check(timeout) throws error :/etc/wansensing/L2Main.lua:60: attempt to concatenate local 'mobile' (a nil value)
Mon Oct 29 19:49:37 2018 daemon.err transformer: [wansensing] stopped due error in scriptL2Main
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: /usr/bin/lua: /usr/lib/lua/wansensingfw/washelper.lua:110: assertion failed!
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: stack traceback:
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	[C]: in function 'assert'
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/usr/lib/lua/wansensingfw/washelper.lua:110: in function </usr/lib/lua/wansensingfw/washelper.lua:104>
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	(tail call): ?
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/usr/lib/lua/wansensingfw/l2wasmachine.lua:41: in function 'update'
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/usr/lib/lua/wansensingfw/init.lua:35: in function 'cb'
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/usr/lib/lua/wansensingfw/wasasync.lua:19: in function </usr/lib/lua/wansensingfw/wasasync.lua:19>
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	[C]: in function 'run'
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/usr/lib/lua/wansensingfw/wasasync.lua:86: in function 'start'
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/usr/lib/lua/wansensingfw/init.lua:172: in function 'start'
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	/sbin/wansensing.lua:20: in main chunk
Mon Oct 29 19:49:37 2018 daemon.err wansensing.lua[4219]: 	[C]: ?
Mon Oct 29 19:49:45 2018 daemon.err transformer: [wansensing] L2Main.check(timeout) throws error :/etc/wansensing/L2Main.lua:60: attempt to concatenate local 'mobile' (a nil value)
Mon Oct 29 19:49:45 2018 daemon.err transformer: [wansensing] stopped due error in scriptL2Main
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: /usr/bin/lua: /usr/lib/lua/wansensingfw/washelper.lua:110: assertion failed!
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: stack traceback:
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	[C]: in function 'assert'
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	/usr/lib/lua/wansensingfw/washelper.lua:110: in function </usr/lib/lua/wansensingfw/washelper.lua:104>
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	(tail call): ?
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	/usr/lib/lua/wansensingfw/l2wasmachine.lua:41: in function 'update'
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	/usr/lib/lua/wansensingfw/init.lua:35: in function 'cb'
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	/usr/lib/lua/wansensingfw/wasasync.lua:19: in function </usr/lib/lua/wansensingfw/wasasync.lua:19>
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	[C]: in function 'run'
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	/usr/lib/lua/wansensingfw/wasasync.lua:86: in function 'start'
Mon Oct 29 19:49:45 2018 daemon.err wansensing.lua[4527]: 	/usr/lib/lua/wansensingfw/init.lua:172: in function 'start'
Mon Oct 29 19:49:46 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Mon Oct 29 19:49:46 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Mon Oct 29 19:49:46 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
Mon Oct 29 19:49:46 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
Mon Oct 29 19:49:50 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
Mon Oct 29 19:53:02 2018 daemon.err miniupnpd[6246]: could not open lease file: /var/upnp.leases
Wed Oct 31 18:49:18 2018 daemon.err nginx: 2018/10/31 18:49:16 [error] 5129#0: *23 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:20: attempt to index local 's' (a nil value)
	[string "internet-dhcp-routWed Oct 31 18:49:19 2018 daemon.err nginx: 2018/10/31 18:49:18 [error] 5129#0: *22 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:20: attempt to index local 's' (a nil value)
	[string "internet-dhcp-routWed Oct 31 18:49:20 2018 daemon.err nginx: 2018/10/31 18:49:19 [error] 5129#0: *24 lua entry thread aborted: runtime error: /usr/lib/lua/web/web.lua:20: attempt to index local 's' (a nil value)
Wed Oct 31 18:51:29 2018 daemon.err insmod: module is already loaded - technicolor_led
Wed Oct 31 18:51:48 2018 daemon.err procd: Failed to removed pidfile: /var/run/transformer.pid: 2 - No such file or directory
Wed Oct 31 18:51:50 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
Wed Oct 31 18:51:50 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
Wed Oct 31 18:51:59 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Wed Oct 31 18:52:00 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Wed Oct 31 18:52:00 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
Wed Oct 31 18:52:00 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
Wed Oct 31 18:52:01 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
Wed Oct 31 18:52:11 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
Wed Oct 31 18:52:11 2018 daemon.err watchdog-tch[6300]: cannot open none (errno = 2 = 'No such file or directory')
Wed Oct 31 18:52:12 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
Wed Oct 31 18:52:21 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Wed Oct 31 18:52:21 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
Wed Oct 31 18:52:21 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
Wed Oct 31 18:52:21 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
Wed Oct 31 18:52:23 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
 
__________________________________PROCESSES_________________________________________
  PID USER       VSZ STAT COMMAND
    1 root      1836 S    /sbin/procd
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    6 root         0 SW   [migration/0]
    7 root         0 SW   [migration/1]
    9 root         0 SW   [ksoftirqd/1]
   11 root         0 SW<  [khelper]
   68 root         0 SW   [sync_supers]
   70 root         0 SW   [bdi-default]
   72 root         0 SW<  [kblockd]
   80 root         0 SW   [khubd]
  101 root         0 SW   [skbFreeTask]
  102 root         0 SW   [bcmFapDrv]
  103 root         0 SW<  [bpm]
  121 root         0 SWN  [kswapd0]
  122 root         0 SW   [fsnotify_mark]
  124 root         0 SW<  [xfsalloc]
  125 root         0 SW<  [xfs_mru_cache]
  126 root         0 SW<  [xfslogd]
  127 root         0 SW<  [crypto]
  139 root         0 SW<  [kthrotld]
  157 root         0 SW   [mtdblock0]
  163 root         0 SW   [mtdblock1]
  168 root         0 SW   [mtdblock2]
  173 root         0 SW   [mtdblock3]
  178 root         0 SW   [mtdblock4]
  183 root         0 SW   [mtdblock5]
  188 root         0 SW   [mtdblock6]
  193 root         0 SW   [mtdblock7]
  206 root         0 SW<  [linkwatch]
  216 root         0 SW<  [deferwq]
  259 root         0 SWN  [jffs2_gcd_mtd2]
  388 root      1516 S    /sbin/ubusd
 1391 root      4600 S    /usr/sbin/cgrulesengd -n -Q -u root
 1499 root         0 SW   [bcmxtm_rx]
 1521 root         0 SW   [bcmFlwStatsTask]
 1535 root         0 SW   [fapGsoLoopBk]
 1536 root         0 SW   [kpAliveWatchdog]
 1538 root         0 SW   [bcmsw_rx]
 1579 root         0 SW   [bcmsw_timer]
 1581 root         0 SW   [bcmsw]
 1659 root         0 SW   [wl0-kthrd]
 1662 root         0 SW   [wfd0-thrd]
 1667 root         0 SW   [wl1-kthrd]
 1685 root         0 SW   [wfd1-thrd]
 2088 root      1588 S    logread -f
 2089 root      2020 S    lua /usr/bin/luasyslog
 2108 root         0 SW<  [led_shift_queue]
 2156 root      5516 S    /sbin/logd -S 4096
 2163 root      8340 S    /usr/bin/swmdk
 2226 root      2084 S    /usr/bin/bcmubusbridge
 2487 root     14756 S    hostapd -bund -p /var/run/hostapd.pid -e /tmp/hostapd.env
 2658 root         0 SW   [dsl0]
 2727 root      2100 S    /sbin/netifd
 2784 root      1984 S <  /usr/sbin/conntrackd -C /etc/conntrackd/conntrackd.conf
 2842 root      1880 S    /usr/sbin/crond -f -c /etc/crontabs -l 5
 2879 root      3336 S    /usr/sbin/cupsd -C /etc/cups/cupsd.conf -s /etc/cups/cups-files.conf
 2926 root      1528 S    /usr/bin/dhcpopassthrud
 3077 root         0 SW   [kTIMR]
 3078 root         0 SW   [kC000]
 3079 root         0 SW   [kEMX0]
 3087 root         0 SW   [kC002]
 3093 root         0 SW   [kC003]
 3094 root         0 SW   [kEMX1]
 3115 root      2724 S    lua /usr/bin/hostmanager.lua
 4148 root      1620 S    /usr/bin/mcsnooper
 4176 root      1788 S    /usr/bin/neighmd -m 0x7
 4698 root      6100 S N  /usr/sbin/smbd -D
 4708 root      6100 S N  /usr/sbin/smbd -D
 4750 root      2728 S    /usr/sbin/nmbd -D
 4919 root      2448 S    /usr/bin/igmpproxy
 5009 root      3408 S    /usr/sbin/minitr064d -f /var/etc/minitr064d.conf
 5038 root      1392 S    /sbin/mountd -f
 5123 root      3456 S    {lte-doctor-logg} /usr/bin/lua /usr/bin/lte-doctor-logger 5 1 /tmp/lte-doctor.db
 5345 root      3360 S    /usr/bin/mmdbd -p /etc/lasdb.db
 5353 root         0 SW<  [mmconnuser_netl]
 5354 root         0 SW   [mmswitchsock_w]
 5355 root         0 SW   [mmswitchsock_r]
 5364 root         0 SW   [mmtonegen]
 5529 root     40860 S    /usr/bin/mmpbxd -q -t 2 -p 75
 5539 root      2152 S    lua /usr/bin/led-fw-interface.lua
 5543 root         0 SW   [voice-aoRT]
 5544 root         0 SW   [voice-HTSK]
 5549 root         0 SW   [voice-HRTBEAT]
 5550 root         0 SW   [voice-VRGDISP]
 5551 root         0 SW   [voice-HCAS]
 5552 root         0 SW   [voice-ISTW]
 5553 root         0 SW   [voice-PSTN]
 5565 root         0 SW<  [dect]
 5595 root      2296 S    {status-led-even} /usr/bin/lua /sbin/status-led-eventing.lua
 5598 root      4380 S    {ledfw.lua} /usr/bin/lua /sbin/ledfw.lua
 5643 root      1188 S    odhcp6c -R -s /lib/netifd/dhcpv6.script -Nnone -P0 -S -r23 -r25 -t120 ptm0
 5644 root      1196 S    odhcpc -p /var/run/odhcpc-ptm0.pid -s /lib/netifd/dhcp.script -f -o -t 0 -i ptm0 -V techn
 5741 root      2868 S    {mobiled} /usr/bin/lua /usr/bin/mobiled
 5758 root      2296 S    {status-led-even} /usr/bin/lua /sbin/status-led-eventing.lua
 5951 root      1524 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10.0.0.138:22 -p 2001:8003:88a7:5e00:
 6130 nobody    1700 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.main -k -x /var/run/dnsmasq/dnsmasq.main.pid
 6131 nobody    1692 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.hotspot -k -x /var/run/dnsmasq/dnsmasq.hotspot
 6134 root      1696 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.main -k -x /var/run/dnsmasq/dnsmasq.main.pid
 6212 root      1876 S <  /usr/sbin/ntpd -n -N -l -S /usr/sbin/ntpd-hotplug -p 0.au.pool.ntp.org -p 1.au.pool.ntp.o
 6235 root     55436 S    nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf -g daemon off;
 6244 nobody   59748 S    nginx: worker process
 6246 root      3404 S    /usr/sbin/miniupnpd-igdv1 -f /var/etc/miniupnpd-tch.conf
 6254 root     37176 S    lua /usr/bin/transformer
 6300 root      1220 S    /usr/sbin/watchdog-tch -c /var/etc/watchdog.conf --foreground
 8774 root      1592 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10.0.0.138:22 -p 2001:8003:88a7:5e00:
 8804 root      1876 S    -ash
 8840 root      1592 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10.0.0.138:22 -p 2001:8003:88a7:5e00:
 9022 root      1876 S    -ash
 9049 root      1588 S    logread -f
10522 root      1592 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10.0.0.138:22 -p 2001:8003:88a7:5e00:
10528 root      1876 S    -ash
12669 root      1592 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 10.0.0.138:22 -p 2001:8003:88a7:5e00:
12675 root      1876 S    -ash
20526 root         0 SW   [kworker/1:0]
21135 root         0 SW   [kworker/0:3]
23694 root         0 SW   [kworker/u:0]
24955 root         0 SW   [kworker/0:0]
25130 root         0 SW   [kworker/u:1]
25169 root         0 SW   [kworker/1:2]
25685 root         0 SW   [flush-mtd-unmap]
25831 root         0 SW   [kworker/u:2]
25987 root      1872 S    {exe} ash /bin/debug
26029 root      1872 S    /bin/sh -c /sbin/trafficmon.lua
26030 root      1764 R    {trafficmon.lua} /usr/bin/lua /sbin/trafficmon.lua
26032 root      1872 R    ps
26033 root      1872 S    sh -c free | grep buffers: | tr -s ' ' | cut -d' ' -f 4
26035 root         0 RW   [grep]
26036 root      1784 R    tr -s  
26037 root      1124 R    cut -d  -f 4
 
__________________________________CONFIG FILE LIST_________________________________________
button
cwmpd
ddns
dhcp
dosprotect
downloaddiag
dropbear
env
ethernet
ethoam
fcctlsettings
firewall
hotspotd
igmpproxy
intercept
ipping
ipset
iqos
ledfw
ltedoctor
mcastsnooping
minidlna
minitr064d
mmdbd
mmdetectslic
mmpbx
mmpbxbrcmcountry
mmpbxbrcmdectdev
mmpbxbrcmfxonet
mmpbxbrcmfxsdev
mmpbxbrcmsi3226x
mmpbxinternalnet
mmpbxrvsipdev
mmpbxrvsipnet
mobiled
mountd
mounts
mwan
neighmon
network
parental
portmirror
power
pppoerelayd
printersharing
qos
samba
system
tod
traceroute
transformer
uploaddiag
upnpd
user_friendly_name
version
versioncusto
wanatmf5loopback
wanconfig
wansensing
watchdog
web
web_back
wifi_doctor_agent
wireless
wol
xdsl
xtm

**Comment by kevdagoat** [comment]
I have fiddled:
Output: 
[DebugHelper2018-11-01.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/2536746/DebugHelper2018-11-01.tar.gz)

**Comment by Ansuel** [comment]
the only problem is the config that can contain sensible data... a general sed rule with any password and username entry would work...

**Comment by kevdagoat** [comment]
At the moment the only data it pulls out of the config files is the version and product names.

**Comment by Ansuel** [comment]
when you are ready tell me and i will implement this... could be really helpfull

**Comment by kevdagoat** [comment]
Will be ready hopefully before monday

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
dev Mode output (doesn't run rootdevice):
[DebugHelper2018-11-03.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/2544719/DebugHelper2018-11-03.tar.gz)

Normal mode:
[DebugHelper2018nondev-11-03.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/2544722/DebugHelper2018-11-03.tar.gz)

Script (place in the /bin dir):
Remember to unzip.
[debug.zip](https://github.com/Ansuel/tch-nginx-gui/files/2544724/debug.zip)

**Comment by kevdagoat** [comment]
Confirmed all ready.
@Ansuel how do you want me to integrate it?

**Comment by Ansuel** [comment]
can you make a pr?

**Comment by Ansuel** [comment]
@kevdagoat yes pls
