### ISSUE TITLE
failed to upgrade to Update 8.9.41 

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#328]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: tg800
Gui Version: 8.9.37

Description of problem: the new update 8.9.41 is not applied. I need to do to
/etc/init.d/nginx enable
/etc/init.d/nginx restart

to get back to gui Gui Version: 8.9.37 [nginx seems disabled??]

here is the log file

**

> Thu Nov  1 06:38:08 2018 auth.info login[29990]: root login on 'pts/0'
> Thu Nov  1 06:38:13 2018 user.notice Upgrade Script: Downloaded gui with hash: ccd953ec4d73341fca0b6e786ab186f0
> Thu Nov  1 06:38:13 2018 user.notice Upgrade Script: Dev branch detected... Checking for newer version in stable...
> Thu Nov  1 06:38:18 2018 auth.info login[30022]: root login on 'pts/0'
> Thu Nov  1 06:38:28 2018 auth.info login[30046]: root login on 'pts/0'
> Thu Nov  1 06:38:38 2018 auth.info login[30073]: root login on 'pts/0'
> Thu Nov  1 06:38:39 2018 user.notice Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
> Thu Nov  1 06:38:39 2018 user.notice Upgrade Script: Stable version found: 8.08.77
> Thu Nov  1 06:38:39 2018 user.notice Upgrade Script: Dev version found: 8.09.41
> Thu Nov  1 06:38:39 2018 user.notice Upgrade Script: Stopping nginx...
> Thu Nov  1 06:38:39 2018 user.notice Upgrade Script: Cleaning www dir
> Thu Nov  1 06:38:39 2018 user.notice Upgrade Script: Extracting file...
> Thu Nov  1 06:38:48 2018 auth.info login[30161]: root login on 'pts/0'
> Thu Nov  1 06:38:52 2018 user.notice Upgrade Script: Copying file to permanent dir...
> Thu Nov  1 06:38:56 2018 user.notice Upgrade Script: Running rootdevice script
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: applying action on power:red
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:red with action none
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: setting brightness to 0
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: applying action on power:green
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:green with action none
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: setting brightness to 0
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: applying action on power:orange
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:orange with action none
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: setting brightness to 0
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: applying action on power:blue
> Thu Nov  1 06:38:56 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:blue with action none
> Thu Nov  1 06:38:56 2018 user.notice Upgrade Script: Upgrade Done
> Thu Nov  1 06:38:58 2018 auth.info login[30190]: root login on 'pts/0'
> Thu Nov  1 06:39:00 2018 cron.info crond[3106]: ignoring file 'root_gui' (no such user)

**

my root folder is full of files
![sshot-134](https://user-images.githubusercontent.com/10972636/47834967-069a0e00-dda2-11e8-8a81-f52841e2af6f.jpg)

when I get back on the old gui I see
![sshot-135](https://user-images.githubusercontent.com/10972636/47835106-92ac3580-dda2-11e8-8404-7f973f2eb412.jpg)

I tried to install the new GUI with the ''import button'', but it gets worse: I get error 500 or 403 when i try to reach an URl with a GUI, like 10.0.0.138 or http://mygateway.gateway/

> hu Nov  1 06:56:37 2018 user.notice Upgrade Script: Found file in /tmp dir... Except offline upgrade!
> Thu Nov  1 06:56:37 2018 user.notice Upgrade Script: Stopping nginx...
> Thu Nov  1 06:56:37 2018 user.notice Upgrade Script: Cleaning www dir
> Thu Nov  1 06:56:37 2018 user.notice Upgrade Script: Extracting file...
> Thu Nov  1 06:56:37 2018 user.notice Upgrade Script: Copying file to permanent dir...
> Thu Nov  1 06:56:37 2018 user.notice Upgrade Script: Running rootdevice script
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: applying action on power:red
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:red with action none
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: setting brightness to 0
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: applying action on power:green
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:green with action none
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: setting brightness to 0
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: applying action on power:orange
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:orange with action none
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: setting brightness to 0
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: applying action on power:blue
> Thu Nov  1 06:56:37 2018 daemon.debug ledfw[2302]: writing to /sys/class/leds/power:blue with action none
> Thu Nov  1 06:56:37 2018 user.notice Upgrade Script: Upgrade Done
> Thu Nov  1 06:56:38 2018 auth.info login[674]: root login on 'pts/0'
> Thu Nov  1 06:56:48 2018 auth.info login[688]: root login on 'pts/0'
> Thu Nov  1 06:56:58 2018 auth.info login[702]: root login on 'pts/0'
> Thu Nov  1 06:57:08 2018 auth.info login[716]: root login on 'pts/0'
> Thu Nov  1 06:57:18 2018 auth.info login[730]: root login on 'pts/0'
> Thu Nov  1 06:57:27 2018 daemon.err odhcp6c[5843]: Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)
> Thu Nov  1 06:57:28 2018 auth.info login[744]: root login on 'pts/0'
> Thu Nov  1 06:57:38 2018 auth.info login[758]: root login on 'pts/0'
> Thu Nov  1 06:57:48 2018 auth.info login[772]: root login on 'pts/0'
> Thu Nov  1 06:57:58 2018 auth.info login[786]: root login on 'pts/0'
> Thu Nov  1 06:58:00 2018 cron.info crond[3106]: USER root pid 800 cmd /sbin/trafficmon.lua
> Thu Nov  1 06:58:08 2018 auth.info login[802]: root login on 'pts/0'
> Thu Nov  1 06:58:18 2018 auth.info login[816]: root login on 'pts/0'
> Thu Nov  1 06:58:28 2018 auth.info login[830]: root login on 'pts/0'
> Thu Nov  1 06:58:38 2018 auth.info login[844]: root login on 'pts/0'
> Thu Nov  1 06:58:48 2018 auth.info login[858]: root login on 'pts/0'
> Thu Nov  1 06:58:58 2018 auth.info login[872]: root login on 'pts/0'
> Thu Nov  1 06:59:08 2018 auth.info login[888]: root login on 'pts/0'
> Thu Nov  1 06:59:18 2018 auth.info login[902]: root login on 'pts/0'
> Thu Nov  1 06:59:26 2018 daemon.err odhcp6c[5843]: Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)
> Thu Nov  1 06:59:28 2018 auth.info login[916]: root login on 'pts/0'
> Thu Nov  1 06:59:38 2018 auth.info login[930]: root login on 'pts/0'
> Thu Nov  1 06:59:48 2018 auth.info login[944]: root login on 'pts/0'
> Thu Nov  1 06:59:58 2018 auth.info login[958]: root login on 'pts/0'
> Thu Nov  1 07:00:00 2018 cron.info crond[3106]: USER root pid 972 cmd /usr/bin/thermalProtection
> Thu Nov  1 07:00:00 2018 cron.info crond[3106]: USER root pid 973 cmd /sbin/trafficmon.lua
> Thu Nov  1 07:00:08 2018 auth.info login[976]: root login on 'pts/0'
> Thu Nov  1 07:00:13 2018 authpriv.info dropbear[990]: Child connection from 10.0.0.91:13017
> Thu Nov  1 07:00:18 2018 auth.info login[991]: root login on 'pts/0'
> Thu Nov  1 07:00:28 2018 auth.info login[1005]: root login on 'pts/0'
> Thu Nov  1 07:00:38 2018 auth.info login[1019]: root login on 'pts/0'
> Thu Nov  1 07:00:38 2018 authpriv.warn dropbear[990]: Login attempt for nonexistent user from 10.0.0.91:13017
> Thu Nov  1 07:00:40 2018 authpriv.info dropbear[990]: Exit before auth: Disconnect received
> Thu Nov  1 07:00:46 2018 authpriv.info dropbear[1033]: Child connection from 10.0.0.91:13078
> Thu Nov  1 07:00:48 2018 auth.info login[1034]: root login on 'pts/0'
> Thu Nov  1 07:00:48 2018 authpriv.notice dropbear[1033]: Password auth succeeded for 'root' from 10.0.0.91:13078
> Thu Nov  1 07:00:49 2018 daemon.err procd: Failed to removed pidfile: /var/run/transformer.pid: 2 - No such file or directory
> Thu Nov  1 07:00:49 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
> Thu Nov  1 07:00:50 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
> Thu Nov  1 07:00:52 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
> Thu Nov  1 07:00:52 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
> Thu Nov  1 07:00:52 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
> Thu Nov  1 07:00:52 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
> Thu Nov  1 07:00:52 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
> Thu Nov  1 07:00:58 2018 auth.info login[1132]: root login on 'pts/0'
> Thu Nov  1 07:01:01 2018 daemon.err nginx: 2018/11/01 07:01:00 [error] 1131#0: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:109):2: module 'cards' not found:
> 	no field package.preload['cards']
> 	no file './cards.lua'
> 	no file '/usr/share/lua/cards.lua'
> 	no file '/usr/share/lua/cards/init.lua'
> 	no file '/usr/lib/lua/cards.lua'
> 	no file '/usr/lib/lua/cards/init.lua'
> 	no file '/usr/lib/lua/cards.lua'
> 	no file '/www/lua/cards.lua'
> 	no file '/usr/lib/lua/cards.so'
> stack traceback:
> coroutThu Nov  1 07:01:08 2018 auth.info login[1146]: root login on 'pts/0'
> Thu Nov  1 07:01:11 2018 daemon.err nginx: 2018/11/01 07:01:11 [error] 1131#0: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:109):2: module 'cards' not found:
> 	no field package.preload['cards']
> 	no file './cards.lua'
> 	no file '/usr/share/lua/cards.lua'
> 	no file '/usr/share/lua/cards/init.lua'
> 	no file '/usr/lib/lua/cards.lua'
> 	no file '/usr/lib/lua/cards/init.lua'
> 	no file '/usr/lib/lua/cards.lua'
> 	no file '/www/lua/cards.lua'
> 	no file '/usr/lib/lua/cards.so'
> stack traceback:
> coroutThu Nov  1 07:01:17 2018 daemon.err procd: Failed to removed pidfile: /var/run/transformer.pid: 2 - No such file or directory
> Thu Nov  1 07:01:17 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/DownloadDiagnostics.map ignored (...are/transformer/mappings/bbf/DownloadDiagnostics.map:269: attempt to call field 'clear_tr143_results' (a nil value))
> Thu Nov  1 07:01:17 2018 daemon.err transformer: /usr/share/transformer/mappings/bbf/UploadDiagnostics.map ignored (...share/transformer/mappings/bbf/UploadDiagnostics.map:276: attempt to call field 'clear_tr143_results' (a nil value))
> Thu Nov  1 07:01:18 2018 auth.info login[1185]: root login on 'pts/0'
> Thu Nov  1 07:01:19 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANDevice.WLANConfiguration.map ignored (...sformer/mappings/igd/LANDevice.WLANConfiguration.map:664: 'InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
> Thu Nov  1 07:01:19 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/LANInterfaces.WLANConfiguration.map ignored (...mer/mappings/igd/LANInterfaces.WLANConfiguration.map:588: 'InternetGatewayDevice.LANInterfaces.WLANConfiguration.{i}.InsecureOOBAccessEnabled': no setter)
> Thu Nov  1 07:01:19 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANIPConnection.map ignored (...gd/WANDevice.WANConnectionDevice.WANIPConnection.map:245: attempt to call field 'SetConnectionList' (a nil value))
> Thu Nov  1 07:01:19 2018 daemon.err transformer: /usr/share/transformer/mappings/igd/WANDevice.WANConnectionDevice.WANPPPConnection.map ignored (...d/WANDevice.WANConnectionDevice.WANPPPConnection.map:393: attempt to call field 'SetConnectionList' (a nil value))
> Thu Nov  1 07:01:20 2018 daemon.err transformer: /usr/share/transformer/mappings/rpc/pumadocsis.map ignored (/usr/share/transformer/mappings/rpc/pumadocsis.map:23: Not able to locate the ubus daemon)
> 
>
 to get back to GUI 8.9.37, I upload the good GUi to /tmp and command
bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf -
 /etc/init.d/transformer restart
/etc/init.d/nginx restart

**Comment by kevdagoat** [comment]
Looks like it didn’t run rootdevice script

**Comment by nclmrc** [comment]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: ccd953ec4d73341fca0b6e786ab186f0
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.09.41
Upgrade Script: Stopping nginx...
Command failed: Not found
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
/etc/rc.common: /etc/init.d/rootdevice: line 1027: apply_specific_TG800_package: not found
ash: 1: unknown operand
/etc/rc.common: /etc/init.d/rootdevice: line 1032: syntax error: unexpected "}"
Upgrade Script: Upgrade Done

**Comment by Ansuel** [comment]
fixed just run upgradegui
