### ISSUE TITLE
Another xDSL graph bug

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#330]
Another duplication of ranges in all graphs (QLN, SNR, Bits), exists up to 8.9.51:

![grafik](https://user-images.githubusercontent.com/17402664/47943796-36f3c080-def8-11e8-8840-7f50921387b3.png)

Here is a full range image with another range that is duplicated:

![grafik](https://user-images.githubusercontent.com/17402664/47943943-f8123a80-def8-11e8-9abf-2b113169d848.png)

**Comment by kevdagoat** [comment]
I have also noticed this bug

**Comment by Ansuel** [comment]
@meyergru i need this 5 file

xdslctl info --pbParams > /tmp/pbParams
xdslctl info --QLN > /tmp/pbParams
xdslctl info --SNR > /tmp/pbParams
xdslctl info --Hlog > /tmp/pbParams
xdslctl info --Bits> /tmp/pbParams

**Comment by meyergru** [comment]
Here you go...

[Bits.txt](https://github.com/Ansuel/tch-nginx-gui/files/2563827/Bits.txt)
[Hlog.txt](https://github.com/Ansuel/tch-nginx-gui/files/2563828/Hlog.txt)
[pbParams.txt](https://github.com/Ansuel/tch-nginx-gui/files/2563829/pbParams.txt)
[QLN.txt](https://github.com/Ansuel/tch-nginx-gui/files/2563830/QLN.txt)
[SNR.txt](https://github.com/Ansuel/tch-nginx-gui/files/2563831/SNR.txt)

**Comment by Ansuel** [comment]
ummm pbParams looks wrong can you post output of this?
xdslctl info --pbParams

**Comment by meyergru** [comment]
#xdslctl info --pbParams
xdslctl: ADSL driver and PHY status
Status: Showtime
Last Retrain Reason:    1
Last initialization procedure status:   0
Max:    Upstream rate = 43217 Kbps, Downstream rate = 260508 Kbps
Bearer: 0, Upstream rate = 42460 Kbps, Downstream rate = 254997 Kbps
Bearer: 1, Upstream rate = 0 Kbps, Downstream rate = 0 Kbps
Discovery Phase (Initial) Band Plan
US: (7,60) (871,1205) (1972,2771)
DS: (65,859) (1216,1961) (2793,7751)
Medley Phase (Final) Band Plan
US: (7,60) (871,1205) (1972,2771)
DS: (65,859) (1216,1961) (2793,7751)
VDSL Port Details               Upstream                Downstream
Attainable Net Data Rate:        43217 kbps             260508 kbps
Actual Aggregate Tx Power:      -   0.8 dBm                12.9 dBm
====================================================================================
VDSL Band Status        U0      U1      U2      U3      U4      D1      D2      D3
  Line Attenuation(dB):  2.8     12.9    18.9     N/A     N/A    7.8     17.0    32.5
Signal Attenuation(dB):  2.8     12.2    17.8     N/A     N/A    8.1     16.7    31.5
        SNR Margin(dB):  9.3     9.4     9.4      N/A     N/A    5.7     4.1     3.5
        TX Power(dBm):  -8.8    -2.6    -8.1      N/A     N/A   -1.2    -0.2     12.5
        kl0(dBx100):    180     180       N/A     N/A     N/A   608     636     711

**Comment by Ansuel** [comment]
Should be fixed
