### ISSUE TITLE
Add DSL uptime on xdsl stats

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#334]
Can you add the uptime of the DSL connection somewhere in the blank space, for instance where the green or red arrow is, in the form 
DSL Uptime X days X hours X minutes X seconds
PPP  Uptime: X days X hours X minutes X seconds
![sshot-161](https://user-images.githubusercontent.com/10972636/48138306-59912b00-e2a4-11e8-95ac-e6a08ad2324f.jpg)

**Comment by kevdagoat** [comment]
That’s already available under Cards > Broadband

**Comment by Janaue** [comment]
yes but it is not available on the diagnostics page so it does not show when I take a screenshot of the parameters of the line
