### ISSUE TITLE
xDSL infos shown when xDSL disconected

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#335]
8.9.52 DGA4132 1.2.0_001
xDSL is down but infos from the last sync are shown in card and modal

![image](https://user-images.githubusercontent.com/4574593/48167135-0b534a80-e2eb-11e8-81ee-a4ca541dc7d4.png)
![image](https://user-images.githubusercontent.com/4574593/48167149-173f0c80-e2eb-11e8-96ff-b59ffd30b05b.png)

**Comment by Ansuel** [comment]
Actually that option reports that the xdsl daemon is enabled not that the connection is up.

**Comment by FrancYescO** [comment]
yep, what i was reporting is that i have the DSLAM versione and Chipset that is impossible that is readed with xdsl down
