### ISSUE TITLE
js not inizialized when switching between cards/stats

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#337]
Rproduce: go to stats page, switch to cards with upper right button

the cards page will be correctly loaded but some js code will be not inizialized, this will cause for example no tooltip when hovering icons in Diagnostics card 
![image](https://user-images.githubusercontent.com/4574593/48185674-1089b700-e336-11e8-895f-ddad1e501a16.png)

probably putting a simple link instead of an ajax full-page load (with `?contentonly=true`) is the easiest fix

**Comment by kevdagoat** [comment]
I did actually notice this!

**Comment by Ansuel** [comment]
I need some feedback about this... needs some report on what doesn't work after 2 click of the switch button

**Comment by FrancYescO** [comment]
actually all looks good
