### ISSUE TITLE
Test Request: Decrypt Tool

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#338]
Can someone test this tool?

https://github.com/Ansuel/Config-Crypt-Decrypt-Tch-Modem-Utility

Follow the instruction pls

**Comment by kevdagoat** [comment]
I don’t have a Tim modem :(

**Comment by FrancYescO** [comment]
it's for technicolor in general not for tim.

**Comment by flywire** [comment]
What are the installation instructions?

**Comment by flywire** [comment]
Installation instructions:

1. Download zip (???)
2. Click _Config Decrypt-Crypt Tool.jar_

Fully functional - Differences:
```
CIPHERKEY=GW
SIGNATUREKEY=GW
...
system.config.export_unsigned='0'
...
system.config.export_plaintext='0'
system.config.import_plaintext='0'
...
system.config.import_unsigned='0'
```
1. Fiddly flicking between two cards to change settings and export/import config.
2. Would be nice to have a button to copy key to clipboard
4. Utility should have instructions - use _?_ icon.

**Comment by flywire** [comment]
I'd like to see a version for https://github.com/pedro-n-rocha/secr - binwalk is a problem under windows.

**Comment by lorenzocanale-LC** [comment]
I tested on my TG789vac v2 but it doesn't work it returns "Decryption error.Wrong key provided?"

**Comment by Ansuel** [comment]
what is the header detected?

**Comment by lorenzocanale-LC** [comment]
The log says "Deected a valid config file.
The file scanned is encrypted."

**Comment by lorenzocanale-LC** [comment]
In config info it says (BTW the space is too little and I can only see dots before infos)
BoardType: VANT-6
ProductName:MediaAccess TG
MAC:MyModemMacAddress
SerialNumber:MyModemSerialNumber
BuildVersion:17.2.0278.....
Must be signed:True
Must be crypted:True
IV:Detected

**Comment by r2munz** [comment]
Testing. Opened an issue on the repo
