### ISSUE TITLE
Traduzioni issues

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#339]
![screenshot_20181109-233534_chrome](https://user-images.githubusercontent.com/38593316/48291976-b7766c00-e478-11e8-84e7-56db41e7fa14.jpg)

**Comment by Enrico9800** [comment]
![cattura](https://user-images.githubusercontent.com/44716486/48294567-3c678280-e485-11e8-99cb-2f53aeb66bc8.PNG)
@Ansuel  @FrancYescO
