### ISSUE TITLE
Modem not reachable

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#340]
Device Model: TG789vac v2 FW UNO 17.2
Gui Version: 8.9.57

Description of problem: I had done the update to the last GUI 8.9.57 and everything was working, but after a reboot the modem is not reachable.

**Comment by Ansuel** [comment]
can you try to reset?  what do you mean not reachable?

**Comment by Ansuel** [comment]
if you reset and do nothing else can you access the modem ?

**Comment by lorenzocanale-LC** [comment]
Yes, with the original gui

**Comment by Ansuel** [comment]
original gui rooted right?

**Comment by lorenzocanale-LC** [comment]
Yes right

**Comment by FrancYescO** [comment]
try `cp /rom/etc/wansensing/* /etc/wansensing/` than reboot to see if its working

**Comment by Ansuel** [comment]
@lorenzocanale-LC can you try to update the gui and check if you have the same problem?

**Comment by lorenzocanale-LC** [comment]
I already have the last gui

**Comment by Ansuel** [comment]
force upgrade and reboot pls

**Comment by lorenzocanale-LC** [comment]
Ok, it worked, and I think I found the problem, it was in my configuration but I never noticed because of the wansensing changing the wan settings.

**Comment by Ansuel** [comment]
what was the problem ?

**Comment by lorenzocanale-LC** [comment]
I had my router IP set to 192.168.1.220 and my static wan IP to 192.168.1.221 so probably this messed up the firewall, I fixed the problem setting my router IP to 192.168.2.220
