### ISSUE TITLE
Driver xDSL

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#341]
puoi aggiungere dei nuovi driver xDSL? tipo quello del Fritzbox 7590?

**Comment by Enrico9800** [comment]
Il firmware ti va bene?

**Comment by Enrico9800** [comment]
https://ftp.avm.de/fritzbox/fritzbox-7590/italy/fritz.os/FRITZ.Box_7590.en-de-es-it-fr-pl-nl.154.06.84.image ecco il link del firmware

**Comment by Enrico9800** [comment]
@Ansuel https://www.mediafire.com/folder/vhh1bwj8x1z1y/DRIVER_xDSL_ASUS_e_FRITZBOX prova questo è di ivymike ce una cartella del 7591

**Comment by Ansuel** [comment]
bisognerebbe vedere che versione è... ma perchè ivy non riposta queste cose e le carica su mediafire :/

**Comment by Enrico9800** [comment]
c'è un metodo per collegare un telefono voip con ethernet? ho un aladino voip new ma è solo compatibile con modem alice e abbonamento alice voce .-.

**Comment by Enrico9800** [comment]
@Ansuel vanno bene quei driver?

**Comment by Ansuel** [comment]
non li ho ancora controllati

Il giorno dom 11 nov 2018 alle ore 16:52 Enrico9800 <
notifications@github.com> ha scritto:

**Comment by Enrico9800** [comment]
spero che vanno bene

**Comment by Enrico9800** [comment]
@Ansuel sicuramente riuscirai a farli funzionare, io ho provato a sostituirli tramite WinSCP e non ho trovato cambiamenti nella lista dei driver

**Comment by Ansuel** [comment]
sono già inclusi purtroppo nulla di nuovo :(
