### ISSUE TITLE
Command request

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#343]
i need this output from everybody...

hexdump -C /proc/rip/0120

**Comment by flywire** [comment]
[TelstraTG799vac.txt](https://github.com/Ansuel/tch-nginx-gui/files/2568923/TelstraTG799vac.txt)

**Comment by Janaue** [comment]
[tg800 hexdump .txt](https://github.com/Ansuel/tch-nginx-gui/files/2569009/tg800.hexdump.txt)

**Comment by scotty03** [comment]
[dga4132_hexdump.txt](https://github.com/Ansuel/tch-nginx-gui/files/2569089/dga4132_hexdump.txt)

**Comment by lorenzocanale-LC** [comment]
[dga4132_hexdump.txt](https://github.com/Ansuel/tch-nginx-gui/files/2569266/dga4132_hexdump.txt)

**Comment by Ansuel** [comment]
this is good and confirm my theory....
