### ISSUE TITLE
Friendly name MyRepublic TG789vac

### ISSUE THREAD

**Issue by scotty03** [Ansuel/tch-nginx-gui#344]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: MyRepublic TG789MYRvac v2 HP
Gui Version:8.9.45

Description of problem:No picture of modem on gateway card

How to reproduce (if possible): Need to add "MediaAccess TG789MYRvac v2 HP" as the friendly name to the gateway.001 card to get the tg789vac image up.

Media/Photos (if possible):

**Comment by flywire** [comment]
@scotty03 if `uci show env.var.variant_friendly_name` is blank for any of your gateways can you https://github.com/Ansuel/tch-nginx-gui/issues/274#issuecomment-437648039?

**Comment by scotty03** [comment]
Explain a bit better............That is about the footer this is about the gateway.001 card just needs 
"MediaAccess TG789MYRvac v2 HP" added as a variable for the myrepublic tg789 as that is it's friendly name.
All the rest are already listed as variables in the gateway.001 card and are correct on all my modems if that is what you are asking.

**Comment by kevdagoat** [comment]
Run:
`uci show env.var.prod_friendly_name`
and I will add.

**Comment by scotty03** [comment]
How can I make this clear? 
"MediaAccess TG789MYRvac v2 HP"
is the friendly name I have already edited gateway.001 here to make sure and it works.

**Comment by flywire** [comment]
> That is about the footer

I updated the comment I linked to. It is more than just the footer - I've been trying to tidy naming up across the devices; they don't all have variant_friendly_name. Gateway, Global Information, `Product Name Technicolor TG ( Technicolor TG799vac )` is pretty crappy too.

**Comment by scotty03** [comment]
Need to add this for the Myrepublic TG789

elseif ( variant == "MediaAccess TG789MYRvac v2 HP") then
model = "_TG789vac"
end

**Comment by scotty03** [comment]
> 
> 
> > That is about the footer
> 
> I updated the comment I linked to. It is more than just the footer - I've been trying to tidy naming up across the devices; they don't all have variant_friendly_name. Gateway, Global Information, `Product Name Technicolor TG ( Technicolor TG799vac )` is pretty crappy too.

I will fire them all up and see what I get and let you know tomorrow. Only fired the MYRrepublc one up for the hexdump for Ansuel as I have never used this one it is just a spare.

**Comment by flywire** [comment]
> Need to add this...

That code and a lot of other duplicate code could do with a tidy up which would be easier with a reliable `env.var.variant_friendly_name`.

**Comment by kevdagoat** [comment]
Done. This can be closed now.
