### ISSUE TITLE
More robust detection of model number.

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#346]
I think it would be good to implement a more robust model detection system (maybe in rootdevice?).

<b>Currently this is what is present:</b>

local variant = proxy.get("uci.env.var.prod_friendly_name")[1].value or ""
local model = nil

if  ( variant == "DGA4130" ) then
	model = "_AGTEF"
elseif ( variant == "DGA4132" ) then
	model = "_AGTHP"
elseif ( variant == "MediaAccess TG789vac v2" ) then
	model = "_TG789vac"
elseif ( variant == "Technicolor TG799vac" ) then
	model = "_TG799vac"
elseif ( variant == "Technicolor TG800vac" ) then
	model = "_TG800vac"
end

<b>What I would like to see</b>

local variant = proxy.get("uci.env.var.determined_product")[1].value or ""
local model = nil

if  ( variant == "DGA4130" ) then
	model = "_AGTEF"
elseif ( variant == "DGA4132" ) then
	model = "_AGTHP"
elseif ( variant == "TG789vac" ) then
	model = "_TG789vac"
elseif ( variant == "TG799vac" ) then
	model = "_TG799vac"
elseif ( variant == "TG800vac" ) then
	model = "_TG800vac"
end

**Comment by scotty03** [comment]
Need to add this for the Myrepublic TG789

elseif ( variant == "MediaAccess TG789MYRvac v2 HP") then
model = "_TG789vac"
end

**Comment by FrancYescO** [comment]
rootscript is a more "critical" script i don't think that these detection should be added in this script... adding if case in the gateway modal (or a global lua func if needed) it's a better practice in this case

**Comment by kevdagoat** [comment]
Most likely not too much of an issue
