### ISSUE TITLE
Modem non raggiungibile

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#349]
![cattura](https://user-images.githubusercontent.com/44716486/48444333-f156b380-e793-11e8-9c49-0dec3fcc7e30.PNG)
dopo che ho spento il modem dal bottone e l'ho riacceso non mi fa più accedere al pannello in nessun modo
GUI DEV 8.9.57 Modem: DGA4132

**Comment by Enrico9800** [comment]
@Ansuel

**Comment by Enrico9800** [comment]
@FrancYescO

**Comment by Ansuel** [comment]
/etc/init.d/nginx restart e dammi logread...

**Comment by Ansuel** [comment]
telnet? non hai nessun modo per accedere ? :/

**Comment by Enrico9800** [comment]
no .-.

**Comment by Enrico9800** [comment]
secondo me devi vedere nella GUI nella sezione DHCP o quello per entrare nel modem se ci sono errori..

**Comment by Ansuel** [comment]
il fatto è che senza accesso non si può neanche capire quale è il problema...

**Comment by Enrico9800** [comment]
@Ansuel ho resettato il modem, ho messo la gui, dal firmware 1.2.0_001 che avevo ho fatto il downgrade al 1.1.2, ho resettato di nuovo il modem ho flashato la gui e ora mi ha installato la 8.9.58 e sembra andare per ora, ho lasciato attivo SSH e telnet in caso succede di nuovo

**Comment by Enrico9800** [comment]
@Ansuel non rilasci altre GUI DEV?

**Comment by Enrico9800** [comment]
@Ansuel non c'è modo di separare i DNS di internet da quelli del VOIP?
