### ISSUE TITLE
Traduzione

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#351]
GUI 8.9.62
![cattura](https://user-images.githubusercontent.com/44716486/48663460-c53b7b00-ea90-11e8-938a-47ea0978d0ec.PNG)

**Comment by Enrico9800** [comment]
@Ansuel

**Comment by Enrico9800** [comment]
Sia Disabled che energtica vanno fixati

**Comment by Enrico9800** [comment]
@FrancYescO

**Comment by Enrico9800** [comment]
@Ansuel

**Comment by Enrico9800** [comment]
![48663460-c53b7b00-ea90-11e8-938a-47ea0978d0ec](https://user-images.githubusercontent.com/44716486/48667059-4bc27d80-eace-11e8-9448-55e3443b27b5.PNG)
disabled va convertito in Disabilitato e poi c'è lo stesso problema che un altro utente aveva segnalato @Ansuel @FrancYescO

**Comment by nclmrc** [comment]
Poi anche nel tab telefono, c'è qualcosa da sistemare
