### ISSUE TITLE
telstra gui is 404

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#354]
Device Model:  tg800
Gui Version: 8.9.64 and 8.9.65

Description of problem:

after install of telstra gui and going to http://10.0.0.138/telstra-gui.lp, it shows 404

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by lorenzocanale-LC** [comment]
Same on TG789vac V2 Gui version 8.9.64.

**Comment by Janaue** [comment]
it is ok on 8.9.66

**Comment by Janaue** [comment]
it is again 404 in 8.9.68

**Comment by kevdagoat** [comment]
Same problems

**Comment by Janaue** [comment]
404 on GUI Version [ 8.9.74 ] 2018

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/350#issuecomment-441443371

**Comment by FrancYescO** [comment]
should be solved
