### ISSUE TITLE
Info Led Red after GUI Update

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#357]
Device Model: TG789Vac V2
Gui Version:8.9.74

Description of problem: After Upgrading the GUI the Info LED goes Blue during the update (Very Cool) but after the update it becomes red and stay red, only way to fix is to reboot.

How to reproduce (if possible):Upgrade the GUI on TG789vac V2

**Comment by FrancYescO** [comment]
have you ever changed the eco led option? wait for the next dev to give feedback if is fixed (if https://github.com/Ansuel/tch-nginx-gui/commit/40b3636f2a33d1e8870b12b179ed583de63c48d3 helped) or in general wait for this issue get fully fixed https://github.com/Ansuel/tch-nginx-gui/issues/264

**Comment by lorenzocanale-LC** [comment]
Yes, I had set EcoLed to on. Eco Led, Info button and every led related things work perfect now, but the LED goes Red after a GUI update and doesn't go back green.

**Comment by FrancYescO** [comment]
@flywire with you comment https://github.com/Ansuel/tch-nginx-gui/issues/264#issuecomment-437725370 i've got that leds were working but only eco led was not working.. the restart work because it retrigger all events that allow leds to start (internet online wifi on etc)

**Comment by FrancYescO** [comment]
fixed with https://github.com/Ansuel/tch-nginx-gui/commit/cc553dfffa93da92f2930d4b46a7eb075d89f089

**Comment by flywire** [comment]
@FrancYescO - leds work but status button has no affect (ie does not turn off leds), [cc553df](https://github.com/Ansuel/tch-nginx-gui/commit/cc553dfffa93da92f2930d4b46a7eb075d89f089) not run yet.

**Comment by FrancYescO** [comment]
@flywire the status button should never turn OFF LEDs it should turn ON if turned OFF by the ECOled function (if all ok on modem after X milliseconds that you have set in the ECOled modal)

Please create a new issue if is still not working in this way on 799, or confirm that is working, we don't have this device and is pretty difficult for us to test

**Comment by kevdagoat** [comment]
Quick Q, how do I write a custom mapping for ledfw??

Sent from Mail for Windows 10

**Comment by flywire** [comment]
@FrancYescO - appreciate the info, it's hard to know how things are _meant_ to work without documentation. Existing issue is: https://github.com/Ansuel/tch-nginx-gui/issues/264.

I'm with @kevdagoat https://github.com/Ansuel/tch-nginx-gui/issues/264#issuecomment-431489804:
> What are relevant commands so I can debug without rebooting gateway?

**Comment by FrancYescO** [comment]
Reboot
________________________________

**Comment by FrancYescO** [comment]
yes but now will fix the issue, to confirm just try a forced upgrade after a reboot

**Comment by lorenzocanale-LC** [comment]
I have already tried, It didn't work

**Comment by FrancYescO** [comment]
strange... could you check if reconnecting internet the i led goes green?

**Comment by lorenzocanale-LC** [comment]
Yes it does! At least now I don't have to reboot, I only need to turn off and then on again the connection

**Comment by FrancYescO** [comment]
i close the issue as the bug is already solved but not in sync with the upgrade package just came back here to confirm is solved when you see the new update package :)
