### ISSUE TITLE
Change Web GUI password from SSH

### ISSUE THREAD

**Issue by mj84** [Ansuel/tch-nginx-gui#359]
Sorry to create an issue for this, but I have searched for a solution to my problem for quite a while.

I'm using a TIM DGA4132 with your cool software and somehow managed to loose my web GUI password for user admin.

I still have SSH access via root.

Is there a way to reset the admin password via SSH? I didn't find anything obvious, only that authentication is implemented through SRP which I am not familar with.

Device Model:  TIM DGA4132
Gui Version: 8.8.68 (i think)

Description of problem: password of admin user lost :/

How to reproduce (if possible): change password of admin user and forget it :(

Any help would be appreciated!

**Comment by FrancYescO** [comment]
this should set it to `admin`
```
config user 'usr_admin'
	option name 'admin'
	option role 'engineer'
	option password_reminder '0'
	option srp_verifier '27d5cc49530f8f1821f01cf7605b61645124e190e13e1defd6295d5160c0421ce0750c4b9324fb1a45ea805c94a0785f4ee9b15b7791bdda55c96536f684c246d845890627330ad4d689802057abfbc0db2d707e61f241a194369185a2d1d87127da527526359f991a62c31090d7541f24bab25e21880c53136241e3c9c552c53cdf66b8526262472b61cb5f21a227cbc64f7b7f7c7d0dda4b9214de024522a113acf5c6b33499f80e91474ffc4be2e351e32e178cb68fedefe2edee7d1f53078aa02e78760b89b50204b30a66d89e5aad3edce03e6a8eb4a36690d2614f05365d09a805222c33feabeae3f32c044745c68b1cd70adfebdb1b54e5b6efdc798d'
	option srp_salt 'cbee79d6'
```

**Comment by mj84** [comment]
Thanks, that did the trick, I could login successfully after a reboot.
But for some reason, I am receiving the following message, when trying to change my password:

> Password must contain at least 12 alphanumeric characters including both upper and lower case letters, at least one number and at least one special character

The password I am trying to set is this: `inioXb!YNjN~PH`
Any idea why the gui is complaining about this password?

**Comment by FrancYescO** [comment]
> at least one number
