### ISSUE TITLE
Traduzioni 

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#367]
https://github.com/Ansuel/tch-nginx-gui/issues/363 da sistemare stato all'interno di informazioni telefonia

**Comment by FrancYescO** [comment]
puoi postare screenshot? non capisco cosa manca

**Comment by nclmrc** [comment]
Registrered andrebbe tradotto con registrato

**Comment by nclmrc** [comment]
Mentre secondo me la scheda porte si dovrebbe chiamare interfacce visto che c'è pure la wifi

**Comment by nclmrc** [comment]
È stato sistemato?

**Comment by FrancYescO** [comment]
si aspetta prossima dev
