### ISSUE TITLE
Dsl stats card

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#368]
![20181202_183203](https://user-images.githubusercontent.com/38593316/49342898-2b172d80-f661-11e8-8804-2d3188320096.jpg)

**Comment by Enrico9800** [comment]
hai l'ultima versione DEV? vedi se ci sono aggiornamenti e fallo, a me compare il profilo 35b

**Comment by nclmrc** [comment]
Si io ho un adsl forse è per questo motivo

Inviato da Samsung Galaxy Note 8

Il 02 Dic 2018 18:38, "Enrico9800" <notifications@github.com> ha scritto:

hai l'ultima versione DEV? vedi se ci sono aggiornamenti e fallo, a me
compare il profilo 35b

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ansuel/tch-nginx-gui/issues/368#issuecomment-443525609>,
or mute the thread

**Comment by Enrico9800** [comment]
@Ansuel

**Comment by Enrico9800** [comment]
@FrancYescO

**Comment by FrancYescO** [comment]
Si il problema e' perche' sei in ADSL essendo quello il profilo VDSL, puoi dare il risultato di `transformer-cli get rpc.xdslctl.DslProfile`?

Comunque provvedo .a far sparire la riga quando non riesce a leggerlo ;)

**Comment by nclmrc** [comment]
Not found

**Comment by FrancYescO** [comment]
confermi risolto?

**Comment by nclmrc** [comment]
sempre not found

**Comment by FrancYescO** [comment]
controlla ora con 8.10.0

**Comment by Enrico9800** [comment]
non ce questa nuova versione

**Comment by Enrico9800** [comment]
@FrancYescO ce il comando SSH per installare la GUI dev dopo che si resetta il modem? vorrei installarla in modo pulita senza passare prima da quella stabile

**Comment by Enrico9800** [comment]
ho fatto da solo xD   curl -k https://repository.ilpuntotecnico.com/files/Ansuel/AGTEF/GUI_dev.tar.bz2 --output /tmp/GUI_dev.tar.bz2
bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf -
/etc/init.d/rootdevice force

**Comment by nclmrc** [comment]
fixato
