### ISSUE TITLE
xt_hashlimit.ko: unknown operand GUI 8.9.98

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#369]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 39098b4c7341f5cb68580266beecfe6d
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.09.98
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
ash: /lib/modules/3.4.11/xt_hashlimit.ko: unknown operand
Upgrade Script: Upgrade Done
root@DGA4132:~#

**Comment by Enrico9800** [comment]
pure a me da lo stesso errore.. però la gui funziona @Ansuel @FrancYescO

**Comment by Enrico9800** [comment]
da lo stesso errore. pure con ash: root: unknow operand. non e fixato @Ansuel ieri ho reinstallato tutto con putty. e lo da ancora

**Comment by FrancYescO** [comment]
@Enrico9800 che versione della GUI hai installato ?

**Comment by FrancYescO** [comment]
con quella versione e' risolto.
