### ISSUE TITLE
Versione GUI

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#370]
![cattura](https://user-images.githubusercontent.com/44716486/49396380-42c1e500-f739-11e8-8aca-06124b5e9e72.PNG)
![cattura1](https://user-images.githubusercontent.com/44716486/49396381-42c1e500-f739-11e8-85a7-62cf1fdd7b24.PNG)
mi si è aggiornata alla versione 8.10.4 e perchè quando faccio di nuovo verifica aggiornamenti mi da la 8.10.3

**Comment by FrancYescO** [comment]
riaggiorna
