### ISSUE TITLE
Timespan not correctly translated

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#371]
Come in allegato i tempi non sono tradotti.
![20181203_220722](https://user-images.githubusercontent.com/38593316/49401708-3bee9e80-f748-11e8-9536-ca1feb6c7609.jpg)

**Comment by Enrico9800** [comment]
@Ansuel @FrancYescO

**Comment by FrancYescO** [comment]
Sembra essere una cosa che non capita sempre (e non ho ancora capito bene quando lo fa)

@Enrico9800 puoi evitare di mandare messaggi vuoti solo per taggare... leggiamo comunque

**Comment by Enrico9800** [comment]
@FrancYescO perchè ogni volta che segnalo qualcosa neanche la vedete.

**Comment by FrancYescO** [comment]
e chi te lo dice che non la vediamo?

**Comment by FrancYescO** [comment]
dietro ogni cosa c'e' una motivazione... quando riusciamo a capirla sara' possibile risolvere 😁

**Comment by nclmrc** [comment]
Ci sono novità per questo bug? @Ansuel @FrancYescO

**Comment by FrancYescO** [comment]
Fixed in https://github.com/Ansuel/tch-nginx-gui/commit/bdebc0accbf79a6552ed9e7ce5f72b37171f76e9
