### ISSUE TITLE
Invalid Upgrade Version Message

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#374]
Telstra TG799vac GUI Version 8.10.7 2018

![wp_ss_20181205_0001](https://user-images.githubusercontent.com/11288701/49468237-72b3da00-f858-11e8-88cc-0f91d945ec28.png)

**Comment by FrancYescO** [comment]
should be okay just reupgrading

**Comment by Enrico9800** [comment]
Il problema non c'è più

**Comment by flywire** [comment]
@Enrico9800 https://github.com/Ansuel/tch-nginx-gui/issues/new?template=bug.md

> Device Model: 
> Gui Version:
