### ISSUE TITLE
Eco setting

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#375]
Nonostante metta

config ethernet 'ethernet'
        option eee '0'
        option autogreeen '0'
        option ethapd '0'

Queste opzioni a 1 da gui,  nel file rimangono a 0.

**Comment by nclmrc** [comment]
Inoltre adesso la scheda eco non è cliccabile dalla home

**Comment by nclmrc** [comment]
Carico un log, forse potrebbe essere d'aiuto 
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/2646468/log.txt)

**Comment by FrancYescO** [comment]
testato sia su un DGA4132 sia firmware 1.0.3 che 1.1.2 non riesco a riprodurre il problema, continuo a sospettare hai problemi di altra sorta sul tuo device.

riporta SEMPRE il dispositivo, firmware e versione gui.

**Comment by nclmrc** [comment]
ora sembra andare chiudo

**Comment by nclmrc** [comment]
in allegato la sequenza fatta dove si vede che i valori non vengono salvati

![immagine](https://user-images.githubusercontent.com/38593316/49640403-cddafd80-fa0d-11e8-9720-4f7b2916fd95.png)
![immagine](https://user-images.githubusercontent.com/38593316/49640430-dc291980-fa0d-11e8-8841-3abf13230cee.png)
![immagine](https://user-images.githubusercontent.com/38593316/49640455-ea773580-fa0d-11e8-9379-a3ebbb155e6e.png)
![immagine](https://user-images.githubusercontent.com/38593316/49640476-fa8f1500-fa0d-11e8-8e75-f174ae76bf3a.png)

**Comment by nclmrc** [comment]
Al riavvio i valori sono tornati tutti su off e non riesco a rimetterli su on

**Comment by FrancYescO** [comment]
continuo a essere convinto ci sia qualcosa nelle tue config che rompe queste impostazioni (e probabilmente molte altre) al riavvio insieme al grafico

**Comment by nclmrc** [comment]
Sinceramente sono partito da una situazione a pulito da poco tempo,  se mi dai i file indiziati posso fare un controllo.

**Comment by nclmrc** [comment]
anche questo semrerebbe risolto

**Comment by nclmrc** [comment]
si è ripresentato, non era legato al config web

**Comment by nclmrc** [comment]
con un ripristino da zero di tutto sembrebbe andare, aspetto a chiudere

**Comment by flywire** [comment]
> GUI Version 8.10.5 2018

@Janaue - version 8.10.25 (?). Yes, try after reboot.

**Comment by nclmrc** [comment]
@FrancYescO potresti passarmi il tuo file /etc/config/ethernet

grazie

**Comment by FrancYescO** [comment]
@nclmrc [ethernet.txt](https://github.com/Ansuel/tch-nginx-gui/files/2671671/ethernet.txt)
comunque io il problema continuo a non averlo c'e qualcosa che non va sul tuo dispositivo...

@Janaue use this issue to report anything wrong with leds https://github.com/Ansuel/tch-nginx-gui/issues/264

**Comment by nclmrc** [comment]
@FrancYescO sono partito da pulito ieri sera.

**Comment by FrancYescO** [comment]
infatti ho paura sia qualcosa hardware legato al dispositivo... nand che ha fatto troppe scritture e a volte si perde i salvataggi

**Comment by nclmrc** [comment]
sinceramente è abbastamza nuovo. comunque ultimamente i valori vengono salvati ma i valori al riavvio vengono ripristinati. sembra questa l'ultima analisi

**Comment by nclmrc** [comment]
anzi sembra ripristinarsi dopo un upgradegui

**Comment by FrancYescO** [comment]
ok confermo anch'io ora che almeno possiamo replicarlo e' piu' facile... tralaltro cio' sembra fa riavviare anche la connessione

**Comment by nclmrc** [comment]
@FrancYescO non è facile capire il problema quando si accavallano più cose in contemporanea

**Comment by nclmrc** [comment]
Con l'ultima gui le impostazioni sono sopravvissute sia dopo upgradegui sia riavvio

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/commit/a4b5c50f68eca36dd98e08d8cefef70cfd016e9c#commitcomment-31690670
