### ISSUE TITLE
ssh lan

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#377]
When SSH LAN is switched on, from the local laptop, it is impossible to resolve domain address connection under ssh.
If the connection comes from a device not connected to the dga4130 there is no problem.
If the SSH Lan  is set to off,from the local laptop connected to dga4130, SSH connections from external Domain are ok, and even from internal.
Example... SSH Lan on from local device type SSH domain.duckdns.org and you get connection refused. From other device works ok.
SSH Lan off, works on either internal or external device.

**Comment by FrancYescO** [comment]
domain resolution is not connected to ssh.

when SSH LAN is off if you cannot connect to SSH (using wan domain/ip or lan domanin/ip makes no difference) when the client is in the LAN is just a correct behaviour

**Comment by dga4130-renato** [comment]
So it's correctly working like that ?

**Comment by dga4130-renato** [comment]
I mean with the Lan switch on... Connects only if you type the internal 192.168.xxx.xxx .. using a dyndns it says connection refused

**Comment by FrancYescO** [comment]
thats because NAT loopback is disabled (and i don't know if there is a way to enable it)

**Comment by dga4130-renato** [comment]
Ok then it's worth to close the issue
