### ISSUE TITLE
Blacklist e aggiornamenti GUI Dev

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#378]
Se installo l'ultima versione della blacklist con i prossimi aggiornamenti della GUI rimane o devo fare sempre la procedura per reinstallarla?

**Comment by FrancYescO** [comment]
reinstalla quella che installerebbe la GUI

**Comment by Enrico9800** [comment]
Io vorrei mettere l'ultima versione non quella della gui. Si disinstalla se la gui si aggiorna?

**Comment by FrancYescO** [comment]
Non dovrebbe
________________________________

**Comment by Enrico9800** [comment]
Non vorrei che si incasina tutto e resettare il modem..

**Comment by FrancYescO** [comment]
Allora tieni quello che hai e aspetta le versioni stabili
________________________________
