### ISSUE TITLE
Password Root

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#380]
![cattura](https://user-images.githubusercontent.com/44716486/49704697-78257180-fc16-11e8-88a4-171cb0cb3f40.PNG)
ma è normale che con le GUI DEV la passowrd del root diventa non valida? io non ho cambiato nulla e mi da errore.

**Comment by Enrico9800** [comment]
@FrancYescO @Ansuel

**Comment by Enrico9800** [comment]
Come faccio ora?

**Comment by FrancYescO** [comment]
prova un aggiornamento forzato da gui. non ho idea di cosa ti abbia cambiato la password. ma se hai lasciato la password di default e hai abilitato l'accesso da WAN immaggino il primo bot capitato che si e' accorto del tuo router l'abbia fatto.

**Comment by FrancYescO** [comment]
... e se non va semplicemente resetta.

**Comment by Enrico9800** [comment]
Anche se lo resetto e metto di nuovo la GUI Dev ritorno punto a capo con questo problema. Io dico di fare un controllo alla GUI per la password del root

**Comment by Enrico9800** [comment]
@Ansuel
