### ISSUE TITLE
Eth port name

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#381]
C'è una duplicazione della porta numero 1

![immagine](https://user-images.githubusercontent.com/38593316/49819049-ade06c80-fd74-11e8-81de-cea5e5947163.png)

**Comment by nclmrc** [comment]
Per fare chiarezza la porta 4 corrisponde alla wan ethernet?

**Comment by FrancYescO** [comment]
direi che dipende dal dispositivo, sul 4132 si

**Comment by FrancYescO** [comment]
4

**Comment by FrancYescO** [comment]
si
