### ISSUE TITLE
Aggiornamento GUI

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#383]
![screenshot_20181212-022342](https://user-images.githubusercontent.com/44716486/49840749-0c2d3f80-fdb5-11e8-9f8b-90797ccb03f3.png)
Ho la 8.10.30 e quando vado a verificare se ci sono nuovi aggiornamenti mi da la 8.10.26 perché

**Comment by Enrico9800** [comment]
@FrancYescO

**Comment by Enrico9800** [comment]
A me risulta installata

**Comment by Ansuel** [comment]
Le versioni sono state resettare per pulizia
Forza aggiornamento

Il giorno Mer 12 Dic 2018, 11:45 Enrico9800 <notifications@github.com> ha
scritto:
