### ISSUE TITLE
Traduzioni Stats Telefonia

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#384]
Durante una chiamata in arrivo viene visualizzata la seduente stringa MMPBX_CALLSTATE_ALERTING, si potrebbe mettere  in arrivo, e quando si risponde attiva

**Comment by FrancYescO** [comment]
quando si risponde (in chiamata) non e' gia corretta?

**Comment by nclmrc** [comment]
Devo controllare

Inviato da Samsung Galaxy Note 8

Il giorno Mer 12 Dic 2018, 16:58 Francesco M <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
No esce questo 
MMPBX_CALLSTATE_CONNECTED

**Comment by FrancYescO** [comment]
se riesci puoi controllare anche mentre chiami (non quando la ricevi ma se fai partire tu una chiamata e sta ancora squillando e anche se quando rispondi sia ok)

**Comment by nclmrc** [comment]
Da siatemare solo in chiamata. In composizione e in corso va bene

**Comment by FrancYescO** [comment]
controlla se tutto ok

**Comment by nclmrc** [comment]
Ora si
