### ISSUE TITLE
Last gui 8.10.33

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#385]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 5696725eeed6fb5d7b18bd7bf8604da3
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.10.33
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
killall: status-led-eventing.lua: no process killed
/etc/rc.common: line 1: /sbin/status-led-eventing.lua: Permission denied
Upgrade Script: Upgrade Done
root@DGA4132:~#

**Comment by FrancYescO** [comment]
fixato https://github.com/Ansuel/tch-nginx-gui/commit/2a53d1836f573bd7b64c2af39295f91dd1e3cb9e

**Comment by nclmrc** [comment]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: ff16e65b4c0aeed02d121b1319e9016f
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.10.34
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
killall: status-led-eventing.lua: no process killed
Upgrade Script: Upgrade Done
root@DGA4132:~#

**Comment by FrancYescO** [comment]
si stiamo gia provvedendo..
