### ISSUE TITLE
Last GUI 8.10.38

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#386]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 7a326e4620e2d4647a9ab9a89b2b86d2
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.10.38
Upgrade Script: Stopping nginx...
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
/etc/rc.common: line 1: /usr/share/transformer/scripts/restart_leds.sh: Permission denied
Upgrade Script: Upgrade Done
root@DGA4132:~#

**Comment by FrancYescO** [comment]
solved with .39
