### ISSUE TITLE
Changelog in GUI

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#387]
Il numero di versione non è più cliccabile, non esce più il changelog
![immagine](https://user-images.githubusercontent.com/38593316/50043499-868be700-0075-11e9-93b4-e6be6cd7046e.png)

**Comment by FrancYescO** [comment]
risolto

**Comment by nclmrc** [comment]
@FrancYescO @Ansuel io fossi in voi rilascerei una stable visto che tutte le criticità si sono risolte. Così da concentrarsi su altre cose nel prossimo periodo.

**Comment by Ansuel** [comment]
@nclmrc si penso che in questi giorni rilasciamo stabile

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/commit/6bd4a1dc766b1af14b1a1f74fb5f2f3ab9f256c8 Fixed https://github.com/Ansuel/tch-nginx-gui/commit/b372a2933544a269b55517229026e6b504000c0c
> Snow over footer stops ability to swipe product name and version.
