### ISSUE TITLE
Inconsistent Card Item Style

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#389]
Consistent card layout would improve appearance (I suspect it is inconsistent with stock).

eg:
1.  Icon point markers - Devices has hanging paragraph but not Telephony, and Internet Access has both styles on same card
2.  QOS icon markers are not hanging indent
3.  Inconsistent spacing between items - Devices has gap, System Extras even larger gap but WAN Services has none

(btw - code style has inconsistent mix of spaces and various tab sizes)

**Comment by FrancYescO** [comment]
90% are stock (including bad codestyle)

the hanging paragraph of 1. are intended

**Comment by flywire** [comment]
Seems like issue noted and will be ongoing, I'll close it.
