### ISSUE TITLE
Ethernet port device names are unknown

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#390]
Telstra TG800vac GUI Version 8.10.60 2018

Description of problem: Ethernet port device names are unknown throughout gui. Fairly sure working Telstra TG800vac GUI Version 8.10.57 2018 https://github.com/Ansuel/tch-nginx-gui/issues/264#issuecomment-447553168

**Comment by flywire** [comment]
Telstra TG800vac GUI Version 8.10.60 2018

Stats:
Hostname | IPv4 | InterfaceType | SSID
Unknown-66:66:66:66:66:66 | 10.0.0.73 | Ethernet - 1

Devices:
Status | Hostname | IPv4 | IPv6 | MAC address | InterfaceType | Port | Connection Time | Lease time | Device Type | SSID |  
  | Unknown-66:66:66:66:66:66 | 10.0.0.73 |   | 66:66:66:66:66:66 | Ethernet | 1 | 4 hours 37 minutes 21 seconds | - | DesktopComputer

Telstra network map too.

**Comment by FrancYescO** [comment]
this is probably not connected to the latest changes, is an old bug that have something to do with DHCP if i'm not wrong (and probably also not a Custom GUI bug)

**Comment by flywire** [comment]
It was working yesterday (https://github.com/Ansuel/tch-nginx-gui/issues/264#issuecomment-447553168) and it isn't now.

**Comment by FrancYescO** [comment]
i know, from what i remember (@Ansuel explained in some old issue) was a pretty random thing, but i'll try to better understand what's wrong.

**Comment by FrancYescO** [comment]
ps. problably not same thing as this that got broken in some of the latest edits
![image](https://user-images.githubusercontent.com/4574593/50052737-0de66280-0129-11e9-85be-8616c6271cf2.png)

**Comment by flywire** [comment]
Telstra TG800vac GUI Version 8.10.63 2018 - Fixed

**Comment by FrancYescO** [comment]
@flywire do you see `nil` on link speed of **non-connected** lan device in telstra netmap?

**Comment by flywire** [comment]
Telstra TG800vac GUI Version 8.10.63 2018
```
LAN IP: 10.0.0.73
Device Name: HPi7
Link Speed: 1000 Mbps
```

**Comment by FrancYescO** [comment]
from how much time it got disconnected?

**Comment by flywire** [comment]
Rebooted and disconnected  - still shows speed.
