### ISSUE TITLE
rootdevice: line 1535: syntax error: unexpected "do" (expecting "then")

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#391]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: c793d22d425bd5f535cb8146eaed13c3
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.10.62
Upgrade Script: Stopping nginx...
Command failed: Not found
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
/etc/rc.common: /etc/init.d/rootdevice: line 1535: syntax error: unexpected "do" (expecting "then")
Upgrade Script: Upgrade Done
root@DGA4132:~#

**Comment by dga4130-renato** [comment]
dga4132, same here, and the router gui locks up.
logged into ssh and i got same result.

**Comment by flywire** [comment]
It's not fixed.

**Comment by FrancYescO** [comment]
what error do you get from rootdevice?

**Comment by flywire** [comment]
Not sure of version:  https://github.com/Ansuel/tch-nginx-gui/commit/1f4ea30269d0d4425431e0958b9a5176e0173d61#commitcomment-31692286

```
root@mygateway:~# /etc/init.d/rootdevice debug
/etc/rc.common: /etc/init.d/rootdevice: line 1535: syntax error: unexpected "do" (expecting "then")
root@mygateway:~#
```

**Comment by FrancYescO** [comment]
excecute `upgradegui` from ssh

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/391#issuecomment-447629903

**Comment by FrancYescO** [comment]
i see only rootdevice called not `upgradegui`

**Comment by flywire** [comment]
Requires manual `upgradegui` to Telstra TG800vac GUI Version 8.10.63 2018

```
root@mygateway:~# upgradegui


 █████╗ ███╗   ██╗███████╗██╗   ██╗███████╗██╗
██╔══██╗████╗  ██║██╔════╝██║   ██║██╔════╝██║
███████║██╔██╗ ██║███████╗██║   ██║█████╗  ██║
██╔══██║██║╚██╗██║╚════██║██║   ██║██╔══╝  ██║
██║  ██║██║ ╚████║███████║╚██████╔╝███████╗███████╗
╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚══════╝╚══════╝
(Modified Gui UpgradeScript)               (Christo)


Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: e618814f63171bd2366c8e4b4ac6855f
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: ab0eb541a6c76cbe5682af14211e0396
Upgrade Script: Stable version found: 8.08.77
Upgrade Script: Dev version found: 8.10.63
Upgrade Script: Stopping nginx...
Command failed: Not found
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
Upgrade Script: Upgrade Done
root@mygateway:~#
```

**Comment by FrancYescO** [comment]
unfortunately this is the only fix if something got broken in the rootdevice script (or if is setted for autoupgrade will be autofixed by cron with the new version)

**Comment by flywire** [comment]
Which commits/versions have this problem?
