### ISSUE TITLE
Config Exportation Failed DGA4132

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#392]
When trying to export configuration on DGA4132 1.1.2 on latest GUI 8.10.63 (But I never tried to export the configuration) GUI says: Exporting failed; please try again.

This is the log:
`daemon.err transformer[4753]: [ConfigCommon] Error: collect export data failed (/usr/lib/lua/transformer/shared/ConfigCommon.lua:414: bad argument #1 to 'next' (table expected, got nil))`

`daemon.err nginx: 2018/12/16 12:11:04 [error] 4809#0: *11 [lua] gateway-modal.lp"]:52: wait_for_completion(): Error on rpc.system.config.export. (state="Error", info="collect export data failed (&#47;usr&#47;lib&#47;lua&#47;transformer&#47;shared&#47;ConfigCommon.lua:414: bad argument #1 to &#39;next&#39; (table expected, got nil))")`

**Comment by flywire** [comment]
Telstra TG800vac GUI Version 8.10.63 2018 - works
System Extras: Export PlainText, Export UnSigned, Import PlainText, Import UnSigned - all on.

**Comment by lorenzocanale-LC** [comment]
I actually think is something related to DGA4132, because also on TG789vac V2 it works

**Comment by FrancYescO** [comment]
is something in the configs.. on mine 4132 1.1.2 is working...

**Comment by lorenzocanale-LC** [comment]
Ok then, i’ll figure it out
