### ISSUE TITLE
Exact path not found!

### ISSUE THREAD

**Issue by Enrico9800** [Ansuel/tch-nginx-gui#393]
![screenshot_20181217-023815](https://user-images.githubusercontent.com/44716486/50062028-ef25b180-01a4-11e9-95e2-d6ab5153bd65.png)
GUI 8.10.67

**Comment by FrancYescO** [comment]
ADSL?
`upgradegui` from terminal

**Comment by Enrico9800** [comment]
Ho la fibra e non risultano aggiornamenti nella gui

**Comment by FrancYescO** [comment]
`upgradegui` da ssh.

**Comment by lorenzocanale-LC** [comment]
I had same error, fixed with an upgradegui from SSH

**Comment by Rossano95** [comment]
Salve, ho anche io questo problema. Versione 8.10.86. Effettuato upgradegui da ssh. Cosa posso fare? Grazie

**Comment by FrancYescO** [comment]
`/etc/init.d/transformer restart` o comunque un riavvio del dispositivo dovrebbe risolvere ... nella maggior parte dei casi e' un problema momentaneo

**Comment by FrancYescO** [comment]
che versione hai del firmware? teoricamente basta solo aspettare un po dopo che la barra si completa...

**Comment by Rossano95** [comment]
La versione è 
AGTEF_1.0.3

Posso aggiornare in qualche modo? Senza avere problemi?

**Comment by Rossano95** [comment]
Le configurazioni non sono un problema. In pratica scarico questo e lo installo dalla gui? 
https://repository.ilpuntotecnico.com/files/Ansuel/AGTEF/AGTEF_1.1.2_CLOSED.rbi

Devo reinstallare la GUI poi?

**Comment by FrancYescO** [comment]
No dovrebbe restare tutto a parte le config

**Comment by Rossano95** [comment]
Ho aggiornato. Ho settato tutto come prima e funziona bene. Grazie per il tuo tempo
