### ISSUE TITLE
Link in scheda app

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#395]
Ci sarebeb da sistemare i link nella scheda app. alcuni puntano all'indirizzo privato del modem altri ricavano dal browser la stringa di navigazione. Visto che funziona applicherei lo stesso metodo sia a xupnp sia luci gui.

![immagine](https://user-images.githubusercontent.com/38593316/50096443-ff2aa900-0217-11e9-91ab-091aa1fad1e8.png)

**Comment by FrancYescO** [comment]
luci e xupnp sono su una porta diversa quindi non si puo' applicare lo stesso metodo, c'e bisogno anche di una regola del firewall per renderli accessibili esternamente...

**Comment by nclmrc** [comment]
Va bene anche per la lan, nel caso.

Inviato da Samsung Galaxy Note 8

Il giorno Lun 17 Dic 2018, 20:15 Francesco M <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment]
non ho capito che intendi.. per la lan gia' prende l'ip del modem

**Comment by bovirus** [comment]
Credo sarebbe meglio usare nei post la lingua inglese.

**Comment by nclmrc** [comment]
Adesso mi sembrano sistemate le stringhe. Chiudo
