### ISSUE TITLE
Christmas tree CPU usage

### ISSUE THREAD

**Issue by SamuelePilleri** [Ansuel/tch-nginx-gui#404]
Merry Christmas everyone! 🎄 

Today I almost fainted when I saw my modem leds singing their Christmas carols and thought I got hacked for a second. Then I realized it was an [easter](https://github.com/Ansuel/tch-nginx-gui/blob/9d11ab1633015b5f79e80b08067e1e4897fd67b1/decompressed/base/etc/init.d/rootdevice#L1534) [egg](https://github.com/Ansuel/tch-nginx-gui/blob/9d11ab1633015b5f79e80b08067e1e4897fd67b1/decompressed/gui_file/etc/christmas_tree.sh) in Christmas time and laughed on it. 😂 

However, I must note that this little treat brings CPU usage very high: if you don't want to end up on the naughty list I think you better remove it or leave it as an opt-in feature in the web UI. 😉 

Cheers! 👋

**Comment by SamuelePilleri** [comment]
You're right, but if you check your uptime you'll notice the difference; mine reached ≈1.7 and dropped back to ≈0.2 when I killed it.

**Comment by FrancYescO** [comment]
script should be stopped now on all devices.

**Comment by SamuelePilleri** [comment]
I've investigated the problem, which I hope won't happen next Christmas.

Apparently, the cause is reading from `/dev/urandom` which is very CPU-bound **in kernel mode** (that's why `top` won't show high CPU usage).

To reproduce:

```bash
$ time dd if=/dev/urandom of=/dev/null bs=1MB count=1024
1024+0 records in
1024+0 records out
1024000000 bytes (1.0 GB, 977 MiB) copied, 1.87978 s, 545 MB/s

real	0m1.951s
user	0m0.000s
sys	0m1.891s

$ time dd if=/dev/zero of=/dev/null bs=1MB count=1024
1024+0 records in
1024+0 records out
1024000000 bytes (1.0 GB, 977 MiB) copied, 0.22851 s, 4.5 GB/s

real	0m0.284s
user	0m0.000s
sys	0m0.234s
```

To verify (with christmas_tree.sh running): ![With christmas_tree.sh running](https://user-images.githubusercontent.com/13276940/51060517-48400400-15f0-11e9-8108-fbe898bd87e7.PNG)

To verify (without christmas_tree.sh running): ![Without christmas-tree.sh runnning](https://user-images.githubusercontent.com/13276940/51060550-6574d280-15f0-11e9-9e63-47d0e873f44f.PNG)

For the future, given the poor hardware, I would suggest double-checking before using `/dev/*random`: the reason is entropy ([Wikipedia](https://en.wikipedia.org/wiki//dev/random)).

Also, as the encyclopedia states, `/dev/*random` shouldn't be trusted blindly when it comes to crypto for mainly two reasons:
 1. In the case of routers, the bootup state is predictable and the available supply of entropy from the environment may be limited;
 2. Linux kernel versions older than 4.8 (DGA 4132 - the newest hardware targeted by this project - runs on 3.4) are vulnerable to an attack described by Daniel Bernstein and reported on the same page.

I haven't checked, but it seems to me unlikely that patches have been backported to the old kernel version we are running, so I wouldn't trust it.

**Comment by kevdagoat** [comment]
Hmm very interesting!

**Comment by FrancYescO** [comment]
nice research, the "trust" is something that can be really ignored for turning on off leds :D.

the point is that what was needed for the christmas script is just a random 1/0, probably the function can be replaced with something like (that idk if is less cpu hungry)
`$(awk -v min=0 -v max=10 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')`

**Comment by SamuelePilleri** [comment]
I've tried that AWK script in a simple for loop and, as suspected, the output isn't very random (always the same number or two different sets at most); I believe it's because it reinitializes the seed every time it runs.

Yet AWK is a good hint: if needed, one could either try to tune that or use [vim](https://vi.stackexchange.com/a/9845).

Do you think it's possible to install [shuf](https://openwrt.org/packages/pkgdata/coreutils-shuf)? I've tried that on my machine and it seems to run in costant time ever with very big ranges.

**Comment by SamuelePilleri** [comment]
A year passed by and this little thing is still there. Can we can this to be removed? Do you accept PRs regarding this?

As a workaround, one can issue the following commands through SSH:
```sed -i '/christmas_tree/d' /etc/crontabs/root
killall christmas_tree.sh
/usr/share/transformer/scripts/restart_leds.sh``
