### ISSUE TITLE
Debug Report

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#406]
Nella Tab **"Funzioni extra di sistema"**, la funzione **"Debug Report - Generate"** sembra non riesca a completare l'esecuzione del processo e "gira" all'infinito

**Comment by Ghost9090** [comment]
@FrancYescO @Ansuel

**Comment by kevdagoat** [comment]
$ Mon Dec 31 20:53:43 2018 daemon.err nginx: 2018/12/31 20:53:43 [error] 3257#0: *51 lua entry thread aborted: runtime error: [string "/modals/system-modal.lp"]:335: attempt to index local 'f' (a nil value)
stack traceback:
coroutine 0:
        [string "/modals/system-modal.lp"]:335: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 10.0.0.139, server: localhost, request: "POST /modals/system-modal.lpMon Dec 31 20:54:00 2018 cron.info crond[2842]: USER root pid 31620 cmd /sbin/trafficmon.lua
