### ISSUE TITLE
Creating custom maps for LedFW

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#408]
I would like to try and create a custom map that Flashes the dect:green light on a TG797n v3 while paging.

Ubus output (1st press of page button):
{ "mmpbxbrcmdect.paging": {"alerting":true} }

Ubus output (2nd press of button):
{ "mmpbxbrcmdect.paging": {"alerting":false} }

Help please :)

**Comment by FrancYescO** [comment]
take a look to the /etc/ledfw/statemachines.lua file

**Comment by kevdagoat** [comment]
I have :)
