### ISSUE TITLE
Time Format in stats page

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#409]
Orario del sistema è in questo formato
A-M-G. Si potrebbe mettere G-M-A

**Comment by Ghost9090** [comment]
@FrancYescO @Ansuel

**Comment by nclmrc** [comment]
@Ansuel puoi sistemarlo nella prossima stable? Grazie

**Comment by nclmrc** [comment]
Semmai mettendo prima pure l'ora

**Comment by FrancYescO** [comment]
Comunque sarebbe da fare in base alla lingua, non tutti utilizzano la data nel formato italiano

**Comment by Ansuel** [comment]
mha sarebbe un pò esagerata come roba ahahhahaha
