### ISSUE TITLE
Enhancement Request: support for DNS over TLS / HTTPS

### ISSUE THREAD

**Issue by berna1995** [Ansuel/tch-nginx-gui#411]
It would be nice, for privacy reasons, being able to support DoT (DNS over TLS) and DoH (DNS over HTTPS).

**Comment by FrancYescO** [comment]
we should check if official owrt packages are compatible

**Comment by kevdagoat** [comment]
I had a quick peek, not really worth installing extra packages.

Sent from Mail for Windows 10

**Comment by berna1995** [comment]
What do you mean?

**Comment by berna1995** [comment]
I see.

**Comment by kevdagoat** [comment]
We will still look in to it for you :)

**Comment by kevdagoat** [comment]
Looks like this may not be possible on older models as the space is running out

**Comment by kevdagoat** [comment]
Ok will look into implementing this. It would be impossible to replace dnsmasq because we would have to rework all of the transformer mappings

**Comment by nutterthanos** [comment]
@kevdagoat have you looked into this yet?

**Comment by kevdagoat** [comment]
I have had a quick look, 168 and above can use the opkg openwrt generic repo 138 and below will need some custom work done :(

**Comment by nutterthanos** [comment]
the 63138 will need work because its a arm cortex a9 chip not a mips chip.

**Comment by kevdagoat** [comment]
Err, yes? That’s why I said 138

Sent from Mail for Windows 10

**Comment by Ansuel** [comment]
Not related to the gui...

You can apply guide for openwrt if package are supported for the model.
