### ISSUE TITLE
Add Aria2/Transmission/amule installation on not DGA devices

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#415]
"Pacchetto sharing" is a good starting point to adapt all
https://www.ilpuntotecnico.com/forum/index.php/topic,77981.msg237906.html#msg237906

**Comment by flywire** [comment]
What are Aria2, Transmission and amule?

**Comment by FrancYescO** [comment]
Actually some apps are only compatible with DGA devices

For Aria2/Transmission/amule in particular the user in the post already made all patches and assured that are installable so we just need to merge the work to get it installable from Extensions modal (like what we made for LuCI)

These are all applications for P2P
________________________________

**Comment by nutterpc** [comment]
TRansmission already built, Aria2 almost done, amule i'll do when i get back from the gym. Which I'm about to head off to

**Comment by FrancYescO** [comment]
Did you tested if the packages made for the 789 (or DGA for the TG800) are working?
________________________________

**Comment by nutterpc** [comment]
Amule doesn't exist for the 799. It's not listed in Chaos Chalmer repo

And no, not yet, only just built them, I'm about to head out for a few hours

**Comment by nutterpc** [comment]
I've been able to finalise Transmission + it's dependencies
Doing Aria2 atm. Amule doesn't exist for Chaos Chalmer so can't do it

Currently they exist in a new repo i created (private) till i finish working on them

**Comment by FrancYescO** [comment]
i was just asking if the already built packages are working on 799/800 you can find these here under different branch https://github.com/FrancYescO/sharing_tg789/tree/amule

**Comment by nutterpc** [comment]
Well I'll make the repo public later today if someone wants to test them for me

I don't do much filesharing now anymore

**Comment by kevdagoat** [comment]
Was wondering how this was going :)

**Comment by FrancYescO** [comment]
have someone tested https://github.com/Ansuel/tch-nginx-gui/issues/415#issuecomment-455915421 ?

**Comment by FrancYescO** [comment]
Closing as it is implemented on TG789.

open a new issue if someone want to port apps to more devices.
