### ISSUE TITLE
Bridge not connected

### ISSUE THREAD

**Issue by monreal** [Ansuel/tch-nginx-gui#421]
Device Model: DGA4132 
Gui Version: 8.10.72 2018

Description of problem:
After update to GUI 8.10.x the "Broadband" card only shows the following:

```
Bridge Mode Active
@ Bridge not connected
```
The bridge seems to work however as my router is connected and internet works fine.

How to reproduce (if possible):
Update to 8.10, log in.

Media/Photos (if possible):
![screenshot from 2019-01-05 09-41-12](https://user-images.githubusercontent.com/54005/50722353-14378100-10ce-11e9-8fde-4f89f85049dd.png)

**Comment by FrancYescO** [comment]
You updated from the older stable version that was set in bridge mode?
Could you share your /etc/config/network file?

**Comment by FrancYescO** [comment]
please give also the output of the command `transformer-cli get uci.wansensing.global.l2type`

**Comment by monreal** [comment]
> You updated from the older stable version that was set in bridge mode?
Correct. I could see the outgoing/incoming speeds there until I upgraded GUI to the new version.

> Could you share your /etc/config/network file?
[network.txt](https://github.com/Ansuel/tch-nginx-gui/files/2730519/network.txt)

> please give also the output of the command transformer-cli get uci.wansensing.global.l2type
uci.wansensing.global.l2type [string] = 
(seems to be empty)

**Comment by monreal** [comment]
Thanks - when will this patch make it into a release?
