### ISSUE TITLE
Spoofing Versione

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#422]
Potete trovare il metodo di non resettare lo spoofing versione ogni volta che la GUI si aggiorna? Ogni volta la devo impostare io. Dalla 1.2.0_001 ritorna su 1.1.2

**Comment by Ansuel** [comment]
la 1.1.2 è l'ultima versione stabile sui server tim quindi... non vedo la necessità di settarne una più vecchia
