### ISSUE TITLE
LED settings issue

### ISSUE THREAD

**Issue by adryx92** [Ansuel/tch-nginx-gui#43]
When LED settings are changed, they won't apply. You can verify it simply changing a setting (the "eco led" switch or the timeout value), closing the "Gateway" dialog and then reopening it.

Besides the wrong field values, I'm not able to turn LEDs back on.

**Comment by Ansuel** [comment]
restoring led value would require restart or the modem or a restart of the wifi and the network device...

**Comment by adryx92** [comment]
Ok, I've just updated the firmware and it now works. I think the issue was relatet to that.
It can be interesting to hide in the HTML features that are not compatible with old firmwares.

**Comment by Ansuel** [comment]
should be fixed with this ca239971d8685be5354425c0a8ee3cfa0fe27ca7
