### ISSUE TITLE
GUI Password ist Default after Reboot

### ISSUE THREAD

**Issue by towatai** [Ansuel/tch-nginx-gui#433]
When I change my GUI password it is also written to /config/web.  If I restart the router, the file is default again and the password is the well-known "Admin".  The whole thing is only so after a fallback from 1.1.0 to 1.0.3 (5GHz WLAN problems).  I already reinstalled the firmware and the GUI.  As GUI version I tried the stable as well as the newest beta.

here are my LOG-File
https://pastebin.com/4nBNbSC4

**Comment by FrancYescO** [comment]
please report gui versions used, you should try 1.1.2 firmware

**Comment by towatai** [comment]
as already mentioned in the initial text, I installed the current stable as well as the current BETA as GUI. These were loaded via the menu inside the GUI as well as manually. I wouldn't like to go to version 1.1.2 because 1.0.3, except for the password problem, works fine for me and I prefer to have a rooted version on both benches. you never know what this is good for ;-)

**Comment by FrancYescO** [comment]
hard to know what was your "current" if someone is looking issue time after.

have you tried a factory reset that gui reinstall to know if the problem still happens?

**Comment by towatai** [comment]
thats a good point! thanks for the thought-provoking impulse. the GUI version I have currently running is 8.11.35. 
no, i haven't tried a factory reset yet, but i'll try it once the days. i'll get back to you and report back. thank you for the help!

**Comment by meyergru** [comment]
I do not know if I have the same issue, but today, when I installed 8.11.49 and rebooted afterwards, my root passwd for SSH access was reset to default.

**Comment by towatai** [comment]
No, not the Same Problem. My Password for entering the GUI gets reset to Default after a reboot. My SSH Password ist not affected. Independent of GUI version.

**Comment by FrancYescO** [comment]
something strange around this issue, i've also got my root password resetted to root, but this is not happening on each reboot

**Comment by towatai** [comment]
Even if it took a bit longer, here's the info that the problem was solved with the update to version 2.0.0.
Thanks to all involved
