### ISSUE TITLE
English Optimisations #2

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#437]
Would like to start the second batch of English optimisations.

Could I please have people help me update the various translations or could someone suggest a program for editing po files?

Here’s a few:
![8a0d2727-8a1f-428f-ad4c-4fc43ed9cecc](https://user-images.githubusercontent.com/42062334/51446572-e77e9d00-1d4e-11e9-8785-c0997e075eb8.png)
![a8641895-63ba-441c-988a-65c76a9415b4](https://user-images.githubusercontent.com/42062334/51446573-e8173380-1d4e-11e9-88d5-63f742afbc3d.png)

**Comment by FrancYescO** [comment]
when editing English strings in source .lp files you have to replace also the msgid strings in .po files under /lang folder

**Comment by bovirus** [comment]
@kevdagoat 

You can edit using POEdit (sugegsted) or any editor compatible with text file coded as UTF-8
At what language are you interested?
Or do you want to create a new language?
If you want to create a new language I can provide you the master language file that you can revise.

**Comment by kevdagoat** [comment]
All I will be doing is fixing any English mistakes within the modals.

**Comment by bovirus** [comment]
@kevdagoat 

If you have to edit .lp (modals) file please use editor like Notepad++ compatible with UTF-8.
Post the PR with changes and I will made the arrangement on language files.

**Comment by kevdagoat** [comment]
Ok. That’s exactly what I have been using.
If you want I can write you a list of all the changes

**Comment by bovirus** [comment]
As you like.

You can make a PR with all changes and I will check that.

I saw that you have a fork of Ansuel GUI.

https://github.com/kevdagoat/tch-nginx-gui

What's are the difference about Ansuel GUI?

If you like I can pass your my dos batch to normalize language file.

Please send me an email to bovirus at gmail.com (when you will send me your email I will delete my email reference by the post) and I will send you back the files.

**Comment by kevdagoat** [comment]
That fork is all of the commits I have ever done. You have one too.

Please do. I will email you now

**Comment by bovirus** [comment]
I suggest you to synchronize your repository with Ansuel repository because it seems that you didn't apply a lot of changes in your repository (the latest commit in your repository is on 03.11.2018)

**Comment by kevdagoat** [comment]
Just about to delete and refork 


Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
In the process of doing it now.

Latest changes:
``` -------------/www/cards----------------------

(005_LAN.lp)
	netmask --> Mask 


-------------/www/snippets-------------------


(tabs-internet.lp)
	Ip Extras --> IP Extras
	Flow Cache Option --> Flow Cache
	Dos Protect Option --> DoS Protect


-------------/www/docroot/modals-------------

(applications-modal.lp)
	Luci --> LuCI 
	Telstra is --> Telstra GUI is 


(broadband-modal.lp)
	Wansensing set the connection mode automatically. --> WanSensing sets the connection mode automatically.
	After saving the changes the connection option will be shown. --> After saving the changes the connection options will be shown.
	Wansensing State --> WanSensing State
	
	
(contentsharing-modal.lp)
	Samba Filesharing --> SMB/CIFS Filesharing
	Samba name --> SMB/CIFS name
	Samba workgroup --> SMB/CIFS workgroup
	Samba description --> SMB/CIFS description
	It is recommended to use the USB in the 2.0 standard. The use of USB in 3.1 standard can remarkably affect the Wi-Fi performance at 2.4 Ghz band. --> It is recommended to use USB2.0 standard. The use of USB3.1 standard can badly affect the Wi-Fi performance of the 2.4 Ghz band.
	Hard Disk Info --> Attached Drive Info
	USB 3.1 Enabled --> USB3.1 enabled
	DLNA Enabled --> DLNA enabled
	
	
(device-modal.lp)
	DesktopComputer --> Desktop Computer
	InterfaceType --> Type
	
	
(diagnostics-connection-modal.lp)
	IP Version 4 Address --> IPv4 Address
	IP Version 6 Address --> IPv6 Address
	
	
(diagnostics-tcpdump-modal.lp)
	tcpdump --> TCPDump
	Downloading tcpdump file, please wait... --> Downloading TCPDump file, please wait...
	Tcpdump Log: --> TCPDump Log:
	1. Max Packet Number Recommened is dynamic and not accurate value (assume to use half of free memory). --> 1. Max recommened Packet Number is dynamic (uses half of free memory) and may not be accurate.
	2. Acceleration disabled during tcpdump on platforms which supports flow cache! --> 2. Hardware offload disabled during capture on platforms with flow cache!
	3. 'Download' invalid if nothing captured. --> 3. 'Download' will be invalid if nothing was captured.
	4. 'Clean' captured file to reduce memory consumption. --> 4. 'Clean' will clean captured file to reduce memory consumption.
	
	
(eco-modal.lp)
	Turning on Ethernet power saving features can cause extra latency --> Turning on Eco features can cause major latency.
	Cpu Wait --> CPU Wait
	Cpu Speed --> CPU Speed
	Led Settings --> LED Settings

(fast-cache-option-modal.lp)
	MCast --> Multicast
	MCast-Learn --> Multicast-Learn
	L2tp --> L2TP
	Only Ipv4 --> Only IPv4
	Only Ipv6 --> Only IPv6 
	Ipv4/Ipv6 --> IPv4/IPv6 
	Flow Cache Option --> Flow Cache
```

**Comment by kevdagoat** [comment]
Is taking a while because i am documenting all of the changes

**Comment by bovirus** [comment]
If you want post a list with all changes and make a PR for the new .lp file.

If you want I can (having the changes list ) make the changes on language files.

**Comment by kevdagoat** [comment]
I honestly dont have the time nor translation skills to do po lists. The changes are above so far

**Comment by bovirus** [comment]
@kevdagoat 

Sorry for my misunderstanding.
One time that you make a PR with all your your .lp files changes it's enough a list you did before. Ex.

-------------/www/cards----------------------
(005_LAN.lp)
	netmask --> Mask 

-------------/www/snippets-------------------
(tabs-internet.lp)
	Ip Extras --> IP Extras
	Flow Cache Option --> Flow Cache
	Dos Protect Option --> DoS Protect

etc.

**Comment by kevdagoat** [comment]
All done
