### ISSUE TITLE
Incoerenza porta eth

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#438]
Ho abilitato la porta wan come lan. Questa la situazione:

root@DGA4132:~# cat /etc/config/ethernet

config port 'eth0'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth1'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth2'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth3'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config port 'eth4'
        option enable '1'
        option speed 'auto'
        option duplex 'full'
        option wan '1'

config port 'eth5'
        option enable '1'
        option speed 'auto'
        option duplex 'full'

config mapping
        option port 'eth5'
        option wlan_remote '1'

config globals 'globals'
        option eth4lanwanmode '1'

root@DGA4132:~#

Vedo option eth4lanwanmode '1' . Non dovrebbe essere eth3 la porta wan/lan ?

**Comment by FrancYescO** [comment]
con eth4lanwanmode a 1 la porta fisica 4 e' eth3 
con eth4lanwanmode a 0 la porta fisica 4 e' eth4

non ho capito da quello che hai riportato l'incoerenza dov'e'

**Comment by nclmrc** [comment]
ma la porta eth4 non è l'sfp? in teoria potrei avere due wan una eth e una sfp.

**Comment by FrancYescO** [comment]
quando la sfp e' attiva eth4lanwanmode deve essere settato a 1 appunto per non andare in conflitto con la sfp

**Comment by FrancYescO** [comment]
Ti ripeto eth4 NON e' l'sfp o almeno, anche facendo riferimento a quello di cui abbiamo discusso nel topic sopra, non in modo diretto.

i naming delle interfacce su firmware TIM non li abbiamo messi noi...

**Comment by nclmrc** [comment]
mi sembra ci cia molta confusione in merito

https://github.com/Ansuel/tch-nginx-gui/issues/381

**Comment by FrancYescO** [comment]
la confusione e' semplicemente nel fatto che la eth4 e' sia la porta fisica LAN4 che l'SFP

**Comment by nclmrc** [comment]
Ma se metto la porta wan/lan in WAN vedo sempre l'eth3. Cosa è quel punto l'eth3?

**Comment by FrancYescO** [comment]
Rapportandola alle porte fisiche esterne del modem, Niente.

eth3 viene usata solo quando quella porta è usata come LAN
________________________________
