### ISSUE TITLE
Traduzione 

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#439]
Nelle impostazione Wifi sezione punto di accesso va corretto "mdoo di sicurezza"

**Comment by Ghost9090** [comment]
@FrancYescO @Ansuel

**Comment by FrancYescO** [comment]
@bovirus

**Comment by bovirus** [comment]
@Ghost9090 

Grazie della segnalazione.
La stringa verrà corretta nella prossima build.

Consiglio di postare i feedback nella discussione indicata da @FrancYescO
