### ISSUE TITLE
Call exit mapping

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#44]
The select on Call exit mapping doesn't work.

**Comment by nclmrc** [comment]
![screenshot_20180428-074843](https://user-images.githubusercontent.com/38593316/39392590-b346fc58-4ab8-11e8-95d0-376b7ce10297.jpg)

**Comment by Ansuel** [comment]
non ho capito cosa non funziona ahaha

**Comment by nclmrc** [comment]
Non funziona la spunta sul Call mapping in uscita

**Comment by Ansuel** [comment]
fixed in latest dev
