### ISSUE TITLE
No validation for QoS entries

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#444]
I can create a blank entry just by pressing "Add new rule" and the + button

**Comment by kevdagoat** [comment]
Proof, @wuseman style :)
![ezgif com-crop](https://user-images.githubusercontent.com/42062334/52120676-0850c780-2658-11e9-8e16-0e75757f86a4.gif)

**Comment by Ansuel** [comment]
fixing in progress...
