### ISSUE TITLE
odhcpd enable at boot

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#445]
é normale che il servizio odhcpd sia abilitato al boot? mi ricordavo che era stato disabilitato.

**Comment by Ansuel** [comment]
il problema col dhcp dovrebbe essere stato fixato...

**Comment by nclmrc** [comment]
Vedevo nei log qualche riferimento a odhcpd e ho visto che è abilitato al
boot.

Inviato da Samsung Galaxy Note 8

Il giorno Mar 29 Gen 2019, 17:01 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by Ansuel** [comment]
eh si nelle ultime dev è stato ristabilito
