### ISSUE TITLE
Traduzione a metà

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#447]
GUI: 8.11.56.
perchè ora la gui è mezza inglese e mezza italiana?

**Comment by Ghost9090** [comment]
![1](https://user-images.githubusercontent.com/44716486/51991949-6e005080-24ac-11e9-9d01-dfd8de225c9c.png)
![2](https://user-images.githubusercontent.com/44716486/51991950-6e005080-24ac-11e9-845c-cab4afbdeaff.png)
![3](https://user-images.githubusercontent.com/44716486/51991953-6e005080-24ac-11e9-9cb1-f1692599b24b.png)
![4](https://user-images.githubusercontent.com/44716486/51991954-6e98e700-24ac-11e9-8b3e-a600ea3a5330.png)
![5](https://user-images.githubusercontent.com/44716486/51991955-6e98e700-24ac-11e9-8c84-dfadbe01e609.png)
![6](https://user-images.githubusercontent.com/44716486/51991957-6e98e700-24ac-11e9-9a69-97df78b1edf7.png)
![7](https://user-images.githubusercontent.com/44716486/51991958-6e98e700-24ac-11e9-9b7b-d64ef22e45f1.png)
![8](https://user-images.githubusercontent.com/44716486/51991960-6f317d80-24ac-11e9-9852-589588920668.png)
![9](https://user-images.githubusercontent.com/44716486/51991962-6f317d80-24ac-11e9-880e-6e03f08818c2.png)
![10](https://user-images.githubusercontent.com/44716486/51991963-6f317d80-24ac-11e9-9137-ae718b33465d.png)
![11](https://user-images.githubusercontent.com/44716486/51991965-6fca1400-24ac-11e9-9461-a7dcac92698b.png)
tutte le parti in inglese

**Comment by Ghost9090** [comment]
@FrancYescO @kevdagoat

**Comment by FrancYescO** [comment]
se ne sta gia' occupando @bovirus

**Comment by Ghost9090** [comment]
Io per sicurezza ho segnalato

**Comment by bovirus** [comment]
@Ghost9090 

Grazie della segnalazione.

È stata fatta una pesante revisione delle stringhe in inglese.
Ora appena posso sistemo le stringhe it/de e uppo le modifiche.

**Comment by Ghost9090** [comment]
Verifica pesante anche per le stringhe in italiano?

**Comment by bovirus** [comment]
@Ghost9090 

Non più di tanto.
L'autore della modifica in inglese mi ha postato l'elenco dei file/stringhe modificate.
Va modificato sia nei template che nei file it/ de la stringa originale inglese (msgid nei file .po) per avere la corrispondenza con il nuovo codice.

Entro stasera (massimo domani mattina dovrebbe essere a posto).

C'è un gran lavoro di tutti dietro questa GUI.

L'autore della traduzione tedesca ha completato la traduzione.
Poi io ho allienato tutto.

Quindi giustamente qualcuno ha notato che le frasi originali in inglese talvolta erano non appropriate e le ha sistemate.

Ora dobbiamo solo sistemare alcune cose e tutto tornerà a posto.

**Comment by Ghost9090** [comment]
![cattura](https://user-images.githubusercontent.com/44716486/52018103-9b1f2400-24e9-11e9-92c0-dd784fa577aa.PNG)
ecco un altra parte da tradurre

**Comment by bovirus** [comment]
Ghost9090

Grazie delle segnalazioni.

Ho caricato una nuova PR.

Aspetta che venga fatto il merge e poi per favore segnala qui se c'è qualcosa da corregere.

**Comment by Ghost9090** [comment]
controllo tutta la GUI anche con le impostazioni avanzate per sicurezza, dopo che c'è l'aggiornamento

**Comment by Ghost9090** [comment]
![1](https://user-images.githubusercontent.com/44716486/52059962-8edbab00-256b-11e9-8d24-2326c0e8f4d0.PNG)
![2](https://user-images.githubusercontent.com/44716486/52059967-8f744180-256b-11e9-90ac-1d9fbbe9d447.PNG)
![3](https://user-images.githubusercontent.com/44716486/52059968-900cd800-256b-11e9-8317-817635ecd903.PNG)
![4](https://user-images.githubusercontent.com/44716486/52059969-900cd800-256b-11e9-96a8-e005c760b922.PNG)
![5](https://user-images.githubusercontent.com/44716486/52059970-900cd800-256b-11e9-9c29-48bafaec20d5.PNG)
![6](https://user-images.githubusercontent.com/44716486/52059971-90a56e80-256b-11e9-8d53-10dc5f1cd236.PNG)
![7](https://user-images.githubusercontent.com/44716486/52059972-90a56e80-256b-11e9-9994-6062678ca1d5.PNG)
![8](https://user-images.githubusercontent.com/44716486/52059973-90a56e80-256b-11e9-8f00-a0f77a210075.PNG)
![9](https://user-images.githubusercontent.com/44716486/52059975-90a56e80-256b-11e9-80a5-969f59103921.PNG)
![10](https://user-images.githubusercontent.com/44716486/52059976-90a56e80-256b-11e9-8011-5e78df808396.PNG)
![11](https://user-images.githubusercontent.com/44716486/52059978-913e0500-256b-11e9-8ca0-9d139e25a0be.PNG)
![12](https://user-images.githubusercontent.com/44716486/52059979-913e0500-256b-11e9-90af-58878291e9aa.PNG)
anche in QoS e Dettagli xDSL va tradotto qulcosa @bovirus

**Comment by Ghost9090** [comment]
![13](https://user-images.githubusercontent.com/44716486/52060843-5fc63900-256d-11e9-8c95-44bf70b81360.PNG)
![14](https://user-images.githubusercontent.com/44716486/52060844-5fc63900-256d-11e9-958e-3c6ba63e96fb.PNG)
![15](https://user-images.githubusercontent.com/44716486/52060845-5fc63900-256d-11e9-915f-acc5fb87ae5f.PNG)
@bovirus

**Comment by Ghost9090** [comment]
![52018103-9b1f2400-24e9-11e9-92c0-dd784fa577aa](https://user-images.githubusercontent.com/44716486/52062076-1d522b80-2570-11e9-8e05-6d45334a93d9.PNG)

**Comment by Ghost9090** [comment]
![1](https://user-images.githubusercontent.com/44716486/52062229-673b1180-2570-11e9-8ac2-dedfaabed6d4.PNG)
![2](https://user-images.githubusercontent.com/44716486/52062233-6904d500-2570-11e9-8e6e-294c8e4cf822.PNG)

**Comment by Ghost9090** [comment]
@bovirus

**Comment by kevdagoat** [comment]
Looks like my English pr broke it

**Comment by bovirus** [comment]
@kevdagoat 

I'm working on it....

**Comment by Ghost9090** [comment]
Ok appena esce l'aggiornamento con il fix verifico tutto @bovirus

**Comment by Ghost9090** [comment]
![screenshot_20190201-111337](https://user-images.githubusercontent.com/44716486/52116875-93a76a00-2612-11e9-8223-361751dc4a43.png)
Dopo aggiornamento 8.11.60 @FrancYescO  @bovirus

**Comment by FrancYescO** [comment]
manda manda `logread -l30` quando hai questi errori.

**Comment by Ghost9090** [comment]
BusyBox v1.23.2 (2018-10-13 01:44:13 UTC) built-in shell (ash)

  _______              __           __              __
 |_     _|.-----.----.|  |--.-----.|__|.----.-----.|  |.-----.----.
   |   |  |  -__|  __||     |     ||  ||  __|  _  ||  ||  _  |   _|
   |___|  |_____|____||__|__|__|__||__||____|_____||__||_____|__|
                 N E X T   G E N E R A T I O N   G A T E W A Y
 --------------------------------------------------------------------
 NG GATEWAY SIGNATURE DRINK
 --------------------------------------------------------------------
  * 1 oz Vodka          Pour all ingredients into mixing
  * 1 oz Triple Sec     tin with ice, strain into glass.
  * 1 oz Orange juice
 --------------------------------------------------------------------

Product: vbnt-s
Release: Cyan (17.3.c)
Version: 17.3.c.0349-8041022-20190110095504-d96cab359f20d67aef464859849f1d49123a7bf0

Bootloader: 17.19.1062-0000000-20170512080206-5bebd9fb97718f93b20bca231a620df630da9918

root@modemtim:~# logread -l30
Fri Feb  1 11:41:42 2019 daemon.info odhcpd[3066]: Using a RA lifetime of 0 seconds on wl0_1
Fri Feb  1 11:41:42 2019 daemon.notice odhcpd[3066]: Failed to send to ff02::1%wl0_1 (Operation not permitted)
Fri Feb  1 11:42:00 2019 cron.info crond[3088]: USER root pid 26183 cmd /sbin/trafficdata.lua
Fri Feb  1 11:42:40 2019 daemon.info dnsmasq-dhcp[25142]: DHCPDISCOVER(br-lan) 10:13:31:25:0b:c2
Fri Feb  1 11:42:40 2019 daemon.info dnsmasq-dhcp[25142]: DHCPOFFER(br-lan) 192.168.1.50 10:13:31:25:0b:c2
Fri Feb  1 11:42:40 2019 daemon.info dnsmasq-dhcp[25142]: DHCPREQUEST(br-lan) 192.168.1.50 10:13:31:25:0b:c2
Fri Feb  1 11:42:40 2019 daemon.info dnsmasq-dhcp[25142]: DHCPACK(br-lan) 192.168.1.50 10:13:31:25:0b:c2 TG234-AP-250BC3
Fri Feb  1 11:42:44 2019 daemon.info dnsmasq-dhcp[25142]: DHCPDISCOVER(br-lan) 192.168.1.225 00:23:ae:8b:6f:04
Fri Feb  1 11:42:44 2019 daemon.info dnsmasq-dhcp[25142]: DHCPOFFER(br-lan) 192.168.1.225 00:23:ae:8b:6f:04
Fri Feb  1 11:42:44 2019 daemon.info dnsmasq-dhcp[25142]: DHCPREQUEST(br-lan) 192.168.1.225 00:23:ae:8b:6f:04
Fri Feb  1 11:42:44 2019 daemon.info dnsmasq-dhcp[25142]: DHCPACK(br-lan) 192.168.1.225 00:23:ae:8b:6f:04 DESKTOP-NPR0LU4
Fri Feb  1 11:43:21 2019 daemon.info odhcpd[3066]: Using a RA lifetime of 0 seconds on br-lan
Fri Feb  1 11:43:21 2019 daemon.notice odhcpd[3066]: Failed to send to ff02::1%br-lan (Operation not permitted)
Fri Feb  1 11:44:45 2019 daemon.err nginx: 2019/02/01 11:44:43 [error] 25414#0: *43 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:46 2019 daemon.err nginx: 2019/02/01 11:44:45 [error] 25414#0: *44 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:47 2019 daemon.err nginx: 2019/02/01 11:44:46 [error] 25414#0: *45 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:48 2019 daemon.err nginx: 2019/02/01 11:44:47 [error] 25414#0: *46 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:49 2019 daemon.err nginx: 2019/02/01 11:44:48 [error] 25414#0: *42 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:50 2019 daemon.err nginx: 2019/02/01 11:44:49 [error] 25414#0: *47 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:52 2019 daemon.err nginx: 2019/02/01 11:44:50 [error] 25414#0: *48 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:53 2019 daemon.err nginx: 2019/02/01 11:44:52 [error] 25414#0: *49 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:44:54 2019 daemon.err nginx: 2019/02/01 11:44:53 [error] 25414#0: *50 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:45:00 2019 cron.info crond[3088]: USER root pid 26282 cmd /sbin/trafficdata.lua
Fri Feb  1 11:45:12 2019 daemon.err nginx: 2019/02/01 11:45:09 [error] 25414#0: *51 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in functioFri Feb  1 11:45:39 2019 daemon.info odhcpd[3066]: Using a RA lifetime of 0 seconds on wl1_1
Fri Feb  1 11:45:39 2019 daemon.notice odhcpd[3066]: Failed to send to ff02::1%wl1_1 (Operation not permitted)
Fri Feb  1 11:45:54 2019 daemon.info odhcpd[3066]: Using a RA lifetime of 0 seconds on wl0_1
Fri Feb  1 11:45:54 2019 daemon.notice odhcpd[3066]: Failed to send to ff02::1%wl0_1 (Operation not permitted)
Fri Feb  1 11:46:05 2019 authpriv.info dropbear[26302]: Child connection from 192.168.1.225:49787
Fri Feb  1 11:46:10 2019 authpriv.notice dropbear[26302]: Password auth succeeded for 'root' from 192.168.1.225:49787

@FrancYescO

**Comment by bovirus** [comment]
Gli errori ricorrenti sono

[string "015_tod.lp"]:77: in function 'content'

[string "cards.lp"]:33: in function 'content'

Ma mi sembra che non ho modificato nessuno di questi due file.

Se la cosa è complicata @FrancYescoO ripristina la versione precedente e vediamo cosa è successo.

**Comment by FrancYescO** [comment]
ho fatto un revert perche' non ne uscivo e non ho il tempo ora di guardare meglio, magari andiamo per pezzi, magari prova anche le modifiche prima localmente prima di pushare

**Comment by Ghost9090** [comment]
@nclmrc già ho messo lo screenshot che lo deve tradurre.

**Comment by Ghost9090** [comment]
@bovirus novità per tutti i Fix per la lingua?

**Comment by bovirus** [comment]
@Ghost9090 

È stata appena fatto un merge della mia PR con alcuni fix.
Buona parte delle stringhe dovrebbero essere a posto.
Ci stiamo ancora lavorando sopra.
Io lavoro sulle stringhe delle lingue.
Francyesco sul codice sorgente.

**Comment by FrancYescO** [comment]
La maggior parte delle stringhe segnalate qui dovrebbe essere tradotta ora nella versione dev, l'unica problematica e' "Wireless Control rules defined" ... se e' sfuggito altro risegnalare qui https://github.com/Ansuel/tch-nginx-gui/issues/407

**Comment by Ghost9090** [comment]
@bovirus ora è tutto apposto?

**Comment by bovirus** [comment]
@Ghost9090 

Dovrebbe essere tutto a posto.
