### ISSUE TITLE
GUI inaccessible when using bridge mode

### ISSUE THREAD

**Issue by monreal** [Ansuel/tch-nginx-gui#449]
I just updated to 8.11.49 using the new commands from README.md as mentioned in issue 441. Everything looked good until:

...
www/lang/it-it/web-framework-tch.po
www/lang/it-it/webui-tim.po
www/lang/it-it/webui-mobiledongle.po
www/lang/it-it/webui-voice.po
www/lang/it-it/webui-qos.po
www/lang/it-it/webui-printersharing.po
Root Script: Rooting in progress...
Command failed: Not found
Command failed: Not found

I can log into the web UI but as soon as I click on "Cards" I get "The connection was reset".

I am now unsure if I just have to reboot the device or if something went really wrong (see the "Command failed: Not found" above) and rebooting would result in a bricked or not-rooted device...

**Comment by monreal** [comment]
BTW the bridge seems to work so I have internet access ATM so I just keep it running for now. Hope you can give me advice soon.

**Comment by FrancYescO** [comment]
we need output of `logread -l30` few moments after you get "The connection was reset"

**Comment by krypton-x** [comment]
I also get the connection reset error with version 8.11.53. It occurs if the DGA4132 is in bridge mode and wansensing is set to disabled. As soon as I change "option enable" to 1 in /etc/config/wansensing the error disappears.
logread: https://pastebin.com/jaBsYhvi

**Comment by monreal** [comment]
Pretty much the same here: https://pastebin.com/7zZdn7nk

**Comment by monreal** [comment]
Pretty much the same here: https://pastebin.com/7zZdn7nk

**Comment by FrancYescO** [comment]
could you check with latest build?

**Comment by monreal** [comment]
Well, actually not the same but I still cannot get to cards. There is no longer any error when rooting:

---
www/lang/it-it/webui-wizard.po
www/lang/it-it/webui-telstra.po
www/lang/it-it/web-framework-tch.po
www/lang/it-it/webui-tim.po
www/lang/it-it/webui-mobiledongle.po
www/lang/it-it/webui-voice.po
www/lang/it-it/webui-qos.po
www/lang/it-it/webui-printersharing.po
Root Script: Rooting in progress...
---

But after clicking cards I now get "Secure Connection Failed" with the following logread: https://pastebin.com/eB2q3PYZ

**Comment by monreal** [comment]
Here: https://pastebin.com/Hdusep4a

**Comment by Ansuel** [comment]
still can't reproduce the bug... 

@monreal pls trigger the bug and grap a logread as soon as you can

**Comment by krypton-x** [comment]
I tried to figure out under what circumstances the bug occurs and did the following :

Reset the device to defaults and installed gui 8.11.74.
Enable bridge mode in the internet access tab and change vlan notation to "dot" in the broadband tab.
Until now it works as expected but if wansensing is set to disabled the error appears.
With vlan notation set to "device" the error never appeared.

The gui gets working again if the /etc/config/wansensing it edited as described before.

Thanks for your work ansuel

**Comment by monreal** [comment]
> still can't reproduce the bug...
> 
> @monreal pls trigger the bug and grap a logread as soon as you can

https://pastebin.com/FV5Dr27L this is as soon as the error page shows up in the browser

**Comment by monreal** [comment]
> The gui gets working again if the /etc/config/wansensing it edited as described before.

If I set config wansensing enable to 1 the cards view still does not work for me but the start page has more cards, some DSL statistics for example.

Do I have to reboot the modem? Now that the rooting process does no longer show any error, I guess it is safe to try?

**Comment by Ansuel** [comment]
@monreal can you give me output of 
transformer-cli get uci.network.interface.@wan.ifname

**Comment by monreal** [comment]
> @monreal can you give me output of
> transformer-cli get [uci.network.interface.@wan.ifname](mailto:uci.network.interface.@wan.ifname)

root@modemtim:~# transformer-cli get uci.network.interface.@wan.ifname
uci.network.interface.@wan.ifname [string] = wanptm0

**Comment by FrancYescO** [comment]
could you check last dev build?

**Comment by monreal** [comment]
> could you check last dev build?

Just by running the commands from README.md, right? In that case, it still does not work :(
https://pastebin.com/rqNsCGjk

**Comment by FrancYescO** [comment]
logread still show the same error?

but how your modem is getting to internet if is in bridge mode?

**Comment by monreal** [comment]
I posted the logread above.
I connect to the internet by Opnsense.

**Comment by FrancYescO** [comment]
i need logread after the last update... you confirm that you are on 8.11.84?

**Comment by krypton-x** [comment]
> 
> 
> could you check last dev build?

I tested with 8.11.84 and the error doesn't appear anymore with the configuration described before. Thank you.

@monreal 

> Just by running the commands from README.md, right? 

No, with the command in the readme the stable build gets installed. You need to install the new dev build (8.11.84) from here: https://github.com/Ansuel/gui-dev-build-auto

Either upload the dev build manually to the router or replace the link in the readme with: https://github.com/Ansuel/gui-dev-build-auto/raw/master/GUI_dev.tar.bz2

**Comment by monreal** [comment]
> No, with the command in the readme the stable build gets installed
Well, as the URL contains "gui-dev-build-auto" I assumed this was the URL for the dev builds...

Alright, after installing the dev build I can finally load the cards view again and the bridge shows as connected. Nice!

I had some errors while running /etc/init.d/rootdevice force, though:

uci: Entry not found
uci: Entry not found
Root Script: Rooting in progress...
Command failed: Not found
Command failed: Not found

Finally, the GUI still shows "8.11.49" at the bottom, is that normal or is my installation still broken somehow?

**Comment by monreal** [comment]
> i was asking how the DGA gets to internet (as in bridge modem will have no internet access)
Default route and DNS set to the Opnsense box (LAN1 interface) which NATs to the internet.

**Comment by FrancYescO** [comment]
probably they wan't appear anymore but we need the output of  /etc/init.d/rootdevice **debug** instead of force to debug uci: Entry not found / Command failed: Not found

open a new issue if you manage to get these errors running with the debug flag

**Comment by monreal** [comment]
Alright, thanks a lot @FrancYescO !
