### ISSUE TITLE
Empty_Response

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#456]
GUI 8.11.64
![cattura](https://user-images.githubusercontent.com/44716486/52165289-08f06900-26ff-11e9-830c-05bf9c17d631.PNG)

**Comment by Ghost9090** [comment]
@FrancYescO di nuovo lo stesso problema

**Comment by FrancYescO** [comment]
E di nuovo non posti il logread :D
________________________________

**Comment by Ghost9090** [comment]
--------------------------------------------------------------------
 NG GATEWAY SIGNATURE DRINK
 --------------------------------------------------------------------
  * 1 oz Vodka          Pour all ingredients into mixing
  * 1 oz Triple Sec     tin with ice, strain into glass.
  * 1 oz Orange juice
 --------------------------------------------------------------------

Product: vbnt-s
Release: Cyan (17.3.c)

Bootloader: 17.19.1062-0000000-20170512080206-5bebd9fb97718f93b20bca231a620df630da9918

root@modemtim:~# logread -l30
Sat Feb  2 15:32:12 2019 authpriv.info dropbear[14084]: Exit (root): Exited normally
Sat Feb  2 15:32:15 2019 authpriv.info dropbear[14005]: Exit (root): Exited normally
Sat Feb  2 15:32:28 2019 authpriv.info dropbear[14089]: Child connection from 5.188.87.49:38528
Sat Feb  2 15:32:29 2019 authpriv.notice dropbear[14089]: Password auth succeeded for 'root' from 5.188.87.49:38528
Sat Feb  2 15:32:29 2019 authpriv.info dropbear[14089]: Exit (root): Exited normally
Sat Feb  2 15:32:31 2019 authpriv.info dropbear[14071]: Exit (root): Error reading: Connection reset by peer
Sat Feb  2 15:32:33 2019 daemon.info odhcpd[10586]: Using a RA lifetime of 0 seconds on br-lan
Sat Feb  2 15:32:33 2019 daemon.notice odhcpd[10586]: Failed to send to ff02::1%br-lan (Operation not permitted)
Sat Feb  2 15:32:34 2019 authpriv.info dropbear[14092]: Child connection from 192.168.1.225:52170
Sat Feb  2 15:32:35 2019 authpriv.info dropbear[14093]: Child connection from 5.188.87.54:35696
Sat Feb  2 15:32:35 2019 authpriv.notice dropbear[14093]: Password auth succeeded for 'root' from 5.188.87.54:35696
Sat Feb  2 15:32:36 2019 authpriv.info dropbear[14093]: Exit (root): Exited normally
Sat Feb  2 15:32:39 2019 authpriv.notice dropbear[14092]: Password auth succeeded for 'root' from 192.168.1.225:52170
Sat Feb  2 15:32:58 2019 authpriv.info dropbear[14105]: Child connection from 62.112.11.90:41834
Sat Feb  2 15:32:59 2019 authpriv.notice dropbear[14105]: Password auth succeeded for 'root' from 62.112.11.90:41834
Sat Feb  2 15:33:00 2019 cron.info crond[3095]: USER root pid 14106 cmd /sbin/trafficdata.lua
Sat Feb  2 15:33:03 2019 authpriv.info dropbear[14092]: Exit (root): Exited normally
Sat Feb  2 15:33:08 2019 authpriv.info dropbear[14111]: Child connection from 109.248.9.105:61170
Sat Feb  2 15:33:08 2019 authpriv.info dropbear[11507]: Exit (root): Error reading: Connection reset by peer
Sat Feb  2 15:33:09 2019 authpriv.notice dropbear[14111]: Password auth succeeded for 'root' from 109.248.9.105:61170
Sat Feb  2 15:33:09 2019 authpriv.info dropbear[14111]: Exit (root): Exited normally
Sat Feb  2 15:33:15 2019 authpriv.info dropbear[14114]: Child connection from 5.188.87.53:62618
Sat Feb  2 15:33:16 2019 authpriv.notice dropbear[14114]: Password auth succeeded for 'root' from 5.188.87.53:62618
Sat Feb  2 15:33:16 2019 authpriv.info dropbear[14114]: Exit (root): Exited normally
Sat Feb  2 15:33:21 2019 authpriv.info dropbear[11869]: Exit (root): Idle timeout
Sat Feb  2 15:33:26 2019 authpriv.info dropbear[14117]: Child connection from 192.168.1.225:52174
Sat Feb  2 15:33:26 2019 authpriv.info dropbear[14118]: Child connection from 5.188.86.211:48718
Sat Feb  2 15:33:27 2019 authpriv.notice dropbear[14118]: Password auth succeeded for 'root' from 5.188.86.211:48718
Sat Feb  2 15:33:27 2019 authpriv.info dropbear[14118]: Exit (root): Exited normally
Sat Feb  2 15:33:30 2019 authpriv.notice dropbear[14117]: Password auth succeeded for 'root' from 192.168.1.225:52174

**Comment by Ghost9090** [comment]
@FrancYescO ma non fate le prove per vedere se funziona prima di metterle online?

**Comment by Ansuel** [comment]
@Ghost9090 si chiamano dev per un motivo...

comunque non va bene come log :(

**Comment by Ghost9090** [comment]
@Ansuel per il log che ti serve che comando devo usare?
