### ISSUE TITLE
GUI problem

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#457]
Con la versione 8.11.64 quando clicco su schede non si apre e esce questo nel log:
root@DGA4132:~# logread -f
Sat Feb  2 18:59:05 2019 daemon.err nginx: 2019/02/02 18:59:04 [error] 2771#0: *                                                                                        16 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad                                                                                         argument #1 to 'format' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        [string "015_tod.lp"]:77: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function

**Comment by FrancYescO** [comment]
duplicata https://github.com/Ansuel/tch-nginx-gui/issues/456
