### ISSUE TITLE
Aggiornamento firmware fallito. (Codice errore: 9)

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#462]
Aggiornando il firmware all'ultima versione esce questo errore.

**Comment by nclmrc** [comment]
log per esteso:
Mon Feb  4 17:45:41 2019 daemon.info dnsmasq-dhcp[11578]: DHCPINFORM(br-lan) 192.168.1.142 9c:d2:1e:fb:ea:19
Mon Feb  4 17:45:41 2019 daemon.info dnsmasq-dhcp[11578]: DHCPACK(br-lan) 192.168.1.142 9c:d2:1e:fb:ea:19 LENOVO
Mon Feb  4 17:46:06 2019 user.notice cwmpd: rollback(record, 0) TMO=300 ROLLBACK_TO=bank_1
Mon Feb  4 17:46:06 2019 user.notice cwmpd: setting rollback_to to bank_1
Mon Feb  4 17:46:06 2019 daemon.crit sysupgrade[12282]: Sysupgrade failed: File is corrupted
Mon Feb  4 17:46:20 2019 daemon.err transformer[11624]: [rpc.system.fwupgrade.] Error: File is corrupted

**Comment by Ansuel** [comment]
quale firmware e con che gui ?

**Comment by nclmrc** [comment]
Firmware 2.0.0. GUI 8.11.83.

Inviato da Samsung Galaxy Note 8

Il giorno Lun 4 Feb 2019, 18:02 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by dga4130-renato** [comment]
confermo il bug. tramite luci funziona, peccato che poi perde le impostazioni e luci e' impossibile da reinstallare.

**Comment by Ansuel** [comment]
FUC*ING PROBLEM DIE.... 5 HOURS OF MY LIFE WASTED FOR A PERMISSION IN /TMP
