### ISSUE TITLE
GUi-Box Text is missing (beta 1.11.90)

### ISSUE THREAD

**Issue by towatai** [Ansuel/tch-nginx-gui#463]
If the language is set to German, the current DEV (1.11.90) does not display a text in the GUI box. Everything works in English. Router Firmware 2.0.0

**Comment by towatai** [comment]
Found another GUI-Bug. Broadband -> Show Advanced -> WanSensing State Text is missing when language is set to German.

**Comment by FrancYescO** [comment]
it's the same for all untranslated strings, we must manage the .po files in a standard way (avoid replacing strings if empty), or wait for @meyergru that will complete latest translations :)

**Comment by meyergru** [comment]
With the old .MO files, that was the standard behaviour. It is helpful if there can be empty translatation in the .PO files, since then the translators just have to fill in the blanks instead of looking for untranslated strings (which can be added automatically). However, the way it is now, empty translations result in empty strings.

**Comment by Ansuel** [comment]
@meyergru thx for notice that... will add an exception for empty translation!

**Comment by meyergru** [comment]
Fine. And if someone regularly adds the new empty strings to the .PO files in the repo, I will translate those from time to time. In the meantime, the original texts will be shown for untranslated strings (i.e. after @Ansuel is done).

**Comment by Ansuel** [comment]
@meyergru  can you give me some example where the text is empty just to test if my modification works.

**Comment by meyergru** [comment]
Just look at the end of https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/www/lang/de-de/webui-core.po , the new strings are being added there. One example is "NotPresent", but I do not know where that is to look at.

**Comment by Ansuel** [comment]
checked with wansensing state... this should be fixed now

**Comment by Ansuel** [comment]
@meyergru can you test this if is fixed?

**Comment by meyergru** [comment]
Alas, I cannot. I am in bridge mode with 8.11.85, so the "check for upgrade" does nothing. And since the GUI upgrade has moved to a page that is not linked anywhere, I can neither access the manual GUI upgrade nor upgrade automatically.

**Comment by Ansuel** [comment]
Click ansuel
Explore my repository and tch auto build

**Comment by Ansuel** [comment]
what do you mean?

**Comment by meyergru** [comment]
Previously, the GUI upgrade function was on the Gateway page. It is no more. The upgrade page is not linked anywhere in the GUI menus, unless a pending upgrade is detected - which can never be in bridge mode.

That way, I cannot access the firmware upgrade modal and thus, not upgrade even manually.

**Comment by Ansuel** [comment]
!!... a new card was introduced recently... with the gui option... thx for the report will add to the whitelist

**Comment by meyergru** [comment]
Can I access it directly via an URL with parameters?

**Comment by Ansuel** [comment]
if you want you can put the tar.bz file (with name GUI or GUI_dev) in /tmp and then run upgradegui

**Comment by meyergru** [comment]
Tried that and it did a downgrade to 8.11.49...

**Comment by meyergru** [comment]
Interesting. Worked on the second try with nothing else changed... ???

**Comment by meyergru** [comment]
Now I got it. In the downgraded 8.11.49, the upgrade is still on the gateway page. So I could use 8.11.97 for a manual upgrade.

I can see english texts now in the german version, so I suspect the fix works.
