### ISSUE TITLE
Error in GUI in Cards view

### ISSUE THREAD

**Issue by asaoner** [Ansuel/tch-nginx-gui#464]
Device Model: 
Gui Version: 8.11.88
DGA4132
Firmware 1.1.1
Description of problem: When I log into GUI with my router's IP, I obtain as default the statistics page.
If I change the view clicking on Cards button I receive an error: 

_

> La pagina non funziona
> 192.168.0.1 non ha inviato dati.
> ERR_EMPTY_RESPONSE_

_

How to reproduce (if possible):
![annotazione 2019-02-05 143937](https://user-images.githubusercontent.com/47356170/52276993-e99e4980-2953-11e9-9ccf-ca2b2578ba1c.jpg)

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
output of `logread -l30 ` few seconds after the error

**Comment by asaoner** [comment]
root@modemtim:~# logread -l30
Sat Feb  2 11:22:59 2019 daemon.info odhcpd[5690]: Using a RA lifetime of 0 sec                                                onds on br-lan
Sat Feb  2 11:22:59 2019 daemon.notice odhcpd[5690]: Failed to send to ff02::1%                                                br-lan (Operation not permitted)
Sat Feb  2 11:23:09 2019 daemon.info odhcpd[5690]: Using a RA lifetime of 0 sec                                                onds on wl0_1
Sat Feb  2 11:23:09 2019 daemon.notice odhcpd[5690]: Failed to send to ff02::1%                                                wl0_1 (Operation not permitted)
Sat Feb  2 11:24:00 2019 cron.info crond[3021]: USER root pid 29771 cmd /sbin/t                                                rafficdata.lua
Sat Feb  2 11:24:07 2019 kern.warn kernel: [61900.817000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2
Sat Feb  2 11:25:20 2019 kern.warn kernel: [61974.156000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=306 TOS=0x00 PREC=0x00 TTL=4 ID=0 DF PROTO=UDP SPT=                                                35836 DPT=1900 LEN=286
Sat Feb  2 11:25:20 2019 kern.warn kernel: [61974.175000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=306 TOS=0x00 PREC=0x00 TTL=4 ID=0 DF PROTO=UDP SPT=                                                35836 DPT=1900 LEN=286
Sat Feb  2 11:25:20 2019 kern.warn kernel: [61974.195000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=315 TOS=0x00 PREC=0x00 TTL=4 ID=0 DF PROTO=UDP SPT=                                                35836 DPT=1900 LEN=295
Sat Feb  2 11:25:20 2019 kern.warn kernel: [61974.215000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=315 TOS=0x00 PREC=0x00 TTL=4 ID=0 DF PROTO=UDP SPT=                                                35836 DPT=1900 LEN=295
Sat Feb  2 11:25:20 2019 kern.warn kernel: [61974.234000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=370 TOS=0x00 PREC=0x00 TTL=4 ID=0 DF PROTO=UDP SPT=                                                35836 DPT=1900 LEN=350
Sat Feb  2 11:26:07 2019 kern.warn kernel: [62021.699000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2
Sat Feb  2 11:26:22 2019 daemon.info odhcpd[5690]: Using a RA lifetime of 0 sec                                                onds on wl1_1
Sat Feb  2 11:26:22 2019 daemon.notice odhcpd[5690]: Failed to send to ff02::1%                                                wl1_1 (Operation not permitted)
Sat Feb  2 11:27:00 2019 cron.info crond[3021]: USER root pid 29809 cmd /sbin/t                                                rafficdata.lua
Sat Feb  2 11:27:19 2019 daemon.info odhcpd[5690]: Using a RA lifetime of 0 sec                                                onds on br-lan
Sat Feb  2 11:27:19 2019 daemon.notice odhcpd[5690]: Failed to send to ff02::1%                                                br-lan (Operation not permitted)
Sat Feb  2 11:28:19 2019 kern.warn kernel: [62153.130000] dosprotect rpfilter d                                                rop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:1d:17:08:00 SRC=192.168.1.                                                252 DST=239.255.255.250 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2
Sat Feb  2 11:28:20 2019 daemon.info odhcpd[5690]: Using a RA lifetime of 0 sec                                                onds on wl0_1
Sat Feb  2 11:28:20 2019 daemon.notice odhcpd[5690]: Failed to send to ff02::1%                                                wl0_1 (Operation not permitted)
Sat Feb  2 11:30:00 2019 cron.info crond[3021]: USER root pid 29865 cmd /sbin/t                                                rafficmon.lua
Sat Feb  2 11:30:00 2019 cron.info crond[3021]: USER root pid 29866 cmd /sbin/t                                                rafficdata.lua
Sat Feb  2 11:30:17 2019 daemon.err nginx: 2019/02/02 11:30:17 [error] 25912#0:                                                 *141 lua entry thread aborted: runtime error: [string "002_broadband_bridge.lp                                                "]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:18 2019 daemon.err nginx: 2019/02/02                                                 11:30:17 [error] 25912#0: *143 lua entry thread aborted: runtime error: [strin                                                g "002_broadband_bridge.lp"]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:18 2019 daemon.err nginx: 2019/02/02                                                 11:30:18 [error] 25912#0: *144 lua entry thread aborted: runtime error: [strin                                                g "002_broadband_bridge.lp"]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:18 2019 daemon.err nginx: 2019/02/02                                                 11:30:18 [error] 25912#0: *145 lua entry thread aborted: runtime error: [strin                                                g "002_broadband_bridge.lp"]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:24 2019 daemon.err nginx: 2019/02/02                                                 11:30:23 [error] 25912#0: *146 lua entry thread aborted: runtime error: [strin                                                g "002_broadband_bridge.lp"]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:24 2019 daemon.err nginx: 2019/02/02                                                 11:30:24 [error] 25912#0: *147 lua entry thread aborted: runtime error: [strin                                                g "002_broadband_bridge.lp"]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:24 2019 daemon.err nginx: 2019/02/02                                                 11:30:24 [error] 25912#0: *148 lua entry thread aborted: runtime error: [strin                                                g "002_broadband_bridge.lp"]:45: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "002_broadband_bridge.lp"]:45: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "002_broadband.lp"]:19: in function 'content'
        /usr/lib/lua/web/lp.lua:171: in function 'include'
        [string "cards.lp"]:33: in function 'content'
        /usr/lib/lua/web/lSat Feb  2 11:30:25 2019 kern.warn kernel: [62278.847                                                000] dosprotect rpfilter drop IN=br-lan OUT= MAC=01:00:5e:7f:ff:fa:a6:91:b1:24:                                                1d:17:08:00 SRC=192.168.1.252 DST=239.255.255.250 LEN=32 TOS=0x00 PREC=0xC0 TTL                                                =1 ID=0 DF PROTO=2

**Comment by asaoner** [comment]
And yes I'm in Bridge Mode.

**Comment by FrancYescO** [comment]
can you say exactly what you made to configure it in bridge mode?

you'll probably solve settings the error by setting these values in the network file
config interface 'wan'
option proto '**bridge**'
option demand '0'
option ifname '**ptm0.835**'

but we need to replicate what you have done to get this configuration (and avoid that this will happen again..)

**Comment by asaoner** [comment]
I didn't touch anything. If I try to use an old GUI version I don't have any issue.
The Bridge mode was been set from Ansuel GUI a lot o previous version ago..

**Comment by FrancYescO** [comment]
so, just fix as i sayd in 11 minutes ago

**Comment by asaoner** [comment]
BTW.. What is the value in highlighted red? Thanks

![annotazione 2019-02-05 180858](https://user-images.githubusercontent.com/47356170/52290817-3ba19800-2971-11e9-9844-1cfa6d64f728.jpg)

**Comment by asaoner** [comment]
It works thanks!

**Comment by FrancYescO** [comment]
connections established throught the modem
