### ISSUE TITLE
Unknow Operand e altri errori

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#465]
Ultima GUI DEV 
![cattura](https://user-images.githubusercontent.com/44716486/52340291-b15c4100-2a0f-11e9-8067-5b525c7add87.PNG)

@Ansuel @FrancYescO

**Comment by Ansuel** [comment]
ma hai connessione internet?

**Comment by Ghost9090** [comment]
Si

**Comment by Ghost9090** [comment]
Installo la GUI sempre tramite internet

**Comment by Ansuel** [comment]
e perchè vedo che la installi manualmente... comunque mi serve rootdevice debug

**Comment by Ghost9090** [comment]
Come te lo mando? Mi dai il comando?

**Comment by FrancYescO** [comment]
/etc/init.d/rootdevice debug

**Comment by Ghost9090** [comment]
root@modemtim:~# /etc/init.d/rootdevice debug
Root Script: Rooting in progress...
Root Script: Apply specific device file...
Root Script: DGA device detected!
Root Script: Extracting custom-ripdrv-specificDGA.tar.bz2 ...
Root Script: Extracting telnet_support-specificDGA/TG800.tar.bz2 ...
Root Script: Extracting upgrade-pack-specificDGA.tar.bz2 ...
Root Script: Extracting upnpfix-specificDGA.tar.bz2 ...
Root Script: Extracting dlnad_supprto-specificDGA.tar.bz2 ...
Root Script: Extracting wgetfix-specificDGA.tar.bz2 ...
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Stopping nginx
Root Script: Checking if we are on TIM configuration
Root Script: Unlocking web interface if needed
Root Script: Check variant_friendly_name set
Root Script: Check and cleanup
Root Script: Remove default dns
Root Script: Purify wan
Root Script: Fix dns bug
ash: 1: unknown operand
Root Script: Enable dlnad
Root Script: Fix Sysupgrade
Root Script: Check orig config
Root Script: Restore original mapper
Root Script: Transformer lib check
Root Script: Remove https check
Root Script: Check css presence
Root Script: Check if dnsmasq is names as we need it for the webui
Root Script: Check driver setting
Root Script: Check Dropbear config file
Root Script: Check ddns directory
Root Script: Check eco param
Root Script: Enable new upnp
Root Script: Sync dhcp configuration for new webui
Root Script: Create gui type in config
Root Script: Add new web option
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
Root Script: Moving aria2 dir
Root Script: Creating new option for led definition
Root Script: Old build detected, moving wansensing file
Root Script: Checking downgrade limitation bit
Root Script: Checking opkg conf
Root Script: Creating and checking real version
Root Script: Creating new wol implementation
Root Script: Sync new xdsl option
Root Script: Creating utility simbolic link
Root Script: Clean old script
Root Script: Adding fast cache options
Root Script: Reworking sfp interface in network...
Root Script: Reinstalling telstra gui if needed...
Root Script: Checking if wan_mode option exist...
Root Script: Inizialize and start dosprotect...
Root Script: Checking if intercept is enabled and disabling it if on...
Root Script: Trying to clean wansensing script from hardcoded interface...
Root Script: Disabling coredump function...
Root Script: Restoring nginx additional option if needed...
Root Script: Setting root flag
Root Script: Reset unlock bit
Root Script: Disable reboot after crash, this gives race condition...
Root Script: Save root password if modified
Root Script: Setting dropbear settings
Root Script: Restarting dropbear
Root Script: Doing various check and generating hash...
Root Script: Update branch detected: DEV
Root Script: Updating GUI in /root folder from /tmp
Root Script: Detected upgrade!
Root Script: Old GUI hash: df8bd62f0f2f04ef4306ed214ee51d37
Root Script: New GUI hash: df8bd62f0f2f04ef4306ed214ee51d37
Root Script: Resetting version info...
Root Script: Add checkversion to cron...
Root Script: Apply modification
Root Script: Restart power init
Root Script: Restarting dnsmasq
Root Script: Process done.
Root Script: Checking if ISP is detected...
Root Script: TIM ISP detected, finding CWMP server...
Root Script: CWMP Server detected: https://regman-mon.interbusiness.it:10800/acs/
Root Script: Restarting transformer
Root Script: Restarting nginx...
Root Script: Trafficmon inizialization
Root Script: Resetting cwmp and watchdog
root@modemtim:~#


@Ansuel @FrancYescO

**Comment by FrancYescO** [comment]
questi errori dovrebbero risultare tutti corretti ora
