### ISSUE TITLE
Band Steering

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#467]
Ma la funzione del band steering è stata rimossa dalla GUI?

**Comment by FrancYescO** [comment]
no

**Comment by nclmrc** [comment]
Come mai non lo vedo?

**Comment by nclmrc** [comment]
Devo aver perso la configurazione originale sovrascrivendo il file wireless. Potresti passarmi la parte relativa al band steering. Grazie

**Comment by nclmrc** [comment]
Dovrei aver risolto. Ho visto la configurazione da rom.
config wifi-bandsteer 'bs0'
        option policy_mode '5'
        option monitor_window '5'
        option sta_comeback_to '5'
        option debug_flags '3'
        option rssi_threshold '-60'
        option rssi_5g_threshold '-80'

**Comment by nclmrc** [comment]
comunque cda GUI da dei valori in percentuale ma in realtà sono valori in dbm
option rssi_threshold '-60'
option rssi_5g_threshold '-80'

**Comment by FrancYescO** [comment]
si ricordo bene che l'opzione per il bandsteer compare in base a se trova o meno quelle impostazioni nel config, riguardo il threshold e' visualizzato in % ma dovrebbe "convertirlo" in dbm

**Comment by nclmrc** [comment]
@FrancYescO in realtà 60 e 80 sono i valori in percentuale da gui che ritrovo nella configurazione in dbm. Andrebbe corretta la GUI.

**Comment by putipower** [comment]
non mi funziona piu' la soglia del band steering.praticamente non salva il valore impostato,ne a 2.4 che a 5ghz.il resto delle impostazioni wifi sono modificbili e salvabili.

**Comment by nclmrc** [comment]
@Ansuel ci puoi dare un occhio a questa correzione da apportare alla GUI? Grazie

**Comment by Ansuel** [comment]
@nclmrc puoi riassumermi ?

**Comment by nclmrc** [comment]
@Ansuel il problema è nella configurazione soglie da GUI. Il valore da GUI è in percentuale mentre in realtà vedendo la configurazione è in dbm.

**Comment by nclmrc** [comment]
ma secondo voi c'è una corrispondenza nei valori in percentuale? @FrancYescO @Ansuel

**Comment by nclmrc** [comment]
Molto spesso che torno a controllare lo trovo disabilitato nonostante l'avessi lasciato attivato.

**Comment by FrancYescO** [comment]
in che senso una corrispondenza? attualmente i valori in % equivalgono ai db... ma si arriva a fare tipo -10db che e' assolutamente inutile come cosa

in ogni caso sembra continuino a toccare roba a riguardo questo bandsteering anche nelle beta, quindi c'e qualcosa che non convince nemmeno loro...

**Comment by nclmrc** [comment]
Ma quale la formula matematica che associa percentuale a db?

**Comment by FrancYescO** [comment]
non c'e alcuna formula, come ti dicevo prima tutt'ora la % equivale ai db, e' tutto molto stupido

**Comment by nclmrc** [comment]
Infatti la percentua

**Comment by FrancYescO** [comment]
in un interfaccia utente e' inutile far vedere i db al massimo come dici e' da fare una formula matematica che converte, ma fin quando non fanno pace e lo fixano almeno sui firmware ufficiali (quello slider lo hanno completamente rimosso attualmente...) batterci la testa forse e' superfluo

**Comment by nclmrc** [comment]
@Ansuel @FrancYescO  casualmente vedo che non mi funziona, entro e lo trovo disabilitato. Sinceramente da quando l'ho attivato mi è successo 4-5 volte. Una cosa sono certo non si disabilita al riavvio.
