### ISSUE TITLE
Local network

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#47]
In local network is not more possible to set the network for wifi-guest.

**Comment by Ansuel** [comment]
This should fix this 1d7478c5905ed41167d8744045be48b719bdd3b4

**Comment by nclmrc** [comment]
@Ansuel for the moment no

**Comment by Ansuel** [comment]
@nclmrc can you explain me where is the problem? i can modify ip addres for wifi guest in local network

**Comment by nclmrc** [comment]
I can't modify ip for Wi-Fi guest. 
![screenshot_20180505-075241](https://user-images.githubusercontent.com/38593316/39660180-a94397c6-5039-11e8-89ef-7384feedceff.png)

**Comment by nclmrc** [comment]
Now it's broken after login

**Comment by Ansuel** [comment]
What do you mean?

**Comment by nclmrc** [comment]
From 7.12.3, I have this screen.

**Comment by Ansuel** [comment]
nha just fixed use /usr/share/transformer/scripts/upgradegui.sh

**Comment by nclmrc** [comment]
I have always the problem on setting of Wi-Fi guest.

**Comment by nclmrc** [comment]
Mi puoi spiegare con quale metodologia aggiorni la versione dev o stabile? Grazie

**Comment by Ansuel** [comment]
per ora sto aggiornando entrambe

**Comment by Ansuel** [comment]
comunque mi spieghi la zona che non riesci a modificare? io da rete locale l'ip posso modificarlo di tutte e 3

**Comment by nclmrc** [comment]
A me è sparita la barra blu a sinistra dove vedo le tre tipologie di rete

**Comment by Ansuel** [comment]
ah non l'avevo notato o.o

**Comment by Ansuel** [comment]
posami contenuto di dhcp e file network

**Comment by nclmrc** [comment]
Ti ho mandato un messaggio privato sul ilpuntotecnico

**Comment by nclmrc** [comment]
È un Po complicata la mia rete se hai dubbi chiedi pure.

**Comment by Ansuel** [comment]
ho notato, sto cercando di immaginare dove inceppa...

**Comment by Ansuel** [comment]
mi serve output di questocomando transformer-cli get rpc.network.interface.

**Comment by nclmrc** [comment]
root@corsignano:~# transformer-cli get rpc.network.interface
ERROR   invalid exact path rpc.network.interface
root@corsignano:~#

**Comment by Ansuel** [comment]
il punto ahahah

**Comment by nclmrc** [comment]
root@corsignano:~# transformer-cli get rpc.network.interface.
ERROR   get(rpc.network.interface.@., dnsserver2_query) failed: ...share/transformer/mappings/rpc/network.interface.map:535: bad argument #1 to 'concat' (table expected, got string)
stack traceback:
        [C]: in function 'concat'
        ...share/transformer/mappings/rpc/network.interface.map:535: in function 'getDnsServers'
        ...share/transformer/mappings/rpc/network.interface.map:726: in function <...share/transformer/mappings/rpc/network.interface.map:724>
        [C]: in function 'xpcall'
        /usr/lib/lua/transformer/navigation.lua:169: in function 'get_parameter_value'
        /usr/lib/lua/transformer/navigation.lua:207: in function 'get'
        /usr/lib/lua/transformer/api.lua:190: in function </usr/lib/lua/transformer/api.lua:181>
        [C]: in function 'pcall'
        /usr/lib/lua/transformer/api.lua:36: in function 'do_pcall'
        /usr/lib/lua/transformer/api.lua:88: in function </usr/lib/lua/transformer/api.lua:86>
        (tail call): ?
        /usr/bin/transformer:178: in function '?'
        /usr/bin/transformer:460: in function </usr/bin/transformer:443>
        [C]: in function 'pcall'
        /usr/bin/transformer:483: in function </usr/bin/transformer:466>
        [C]: in function 'run'
        /usr/bin/transformer:506: in function </usr/bin/transformer:494>
        [C]: in function 'pcall'
        /usr/bin/transformer:517: in main chunk
        [C]: ?

**Comment by Ansuel** [comment]
ecco il problema, la strana configurazione del network fa fallire il mapper

**Comment by nclmrc** [comment]
Ho un dhcp server che fa anche da dns sul raspberry e avevo messo l ip del raspberry nella sezione per fare usare al tim hub quel dns

**Comment by Ansuel** [comment]
Messo versione dovrebbe andare... In pratica non piaceva quell' option DNS siccome doveva essere un list... Ho aggiunto un check che verifica se è un valore unico ;) ora dovrebbe andare

**Comment by nclmrc** [comment]
Grande funziona. Per il call mapping hai capito che può essere?

**Comment by nclmrc** [comment]
Si è ripresentato lo stesso problema.  Questa volta non ci sono errori in transformer.

**Comment by Ansuel** [comment]
Quale sarebbe il problema?

**Comment by nclmrc** [comment]
È risparita la gestione delle reti guest

**Comment by nclmrc** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/47#issuecomment-386803049

**Comment by Ansuel** [comment]
a me vengono correttamente visualizzate

**Comment by nclmrc** [comment]
Questa volta questo comando a differenza della scorsa volta non mi da errore
transformer-cli get rpc.network.interface.

**Comment by nclmrc** [comment]
Hai qualche prova da farmi fare?

**Comment by Ansuel** [comment]
si puoi passarmi il file? così testo col tuo direttamente? elimina eventuali password e nomi utenti

**Comment by nclmrc** [comment]
https://pastebin.com/ueqnaTAu

**Comment by Ansuel** [comment]
Riapri se hai ancora il problema

**Comment by FrancYescO** [comment]
Su 789 Firmware Tiscali c'é lo stesso problema... immagino perché manchino proprio i pezzi riguardo le reti guest nella configurazione stock, perché con il firmware UNO sembra tutto ok
