### ISSUE TITLE
Io non ho capito come si installa

### ISSUE THREAD

**Issue by umbz** [Ansuel/tch-nginx-gui#470]
Non si capisce come si deve installare 
tg789 vac versione 1.0.8 tim rootata tramite procedura indicata. (entro in telnet e ssh)

il curl sul router non e' riconosciuto come comando menchemeno bzcat , quindi dove lo devo lanciare? 

grazie
UmbZ

**Comment by Ansuel** [comment]
torna a leggere bene le guide... devi cambiare firmware sul modem...

**Comment by umbz** [comment]
Ah ok ma se leggo sul readme di GitHub dice di sbloccare e poi installare :/

**Comment by Ansuel** [comment]
il modem agtot è speciale nasce con un firmware diverso e vecchio...
