### ISSUE TITLE
upgradegui errore controllo ISP

### ISSUE THREAD

**Issue by 123aezakmi123** [Ansuel/tch-nginx-gui#475]
L'aggiornamento della GUI (dev) rimane bloccato molti minuti su
`Root Script: TIM ISP detected, finding CWMP server...`
Avendo Wind dopo l'attesa restituisce
`Root Script: CWMP Server detected: None`

Anche modificando il file `/etc/config/modgui` e con `uci set modgui.var.isp="Other"`
continua a rilevare TIM

**Comment by FrancYescO** [comment]
hai impostato i dati della pppoe su quello di wind?

**Comment by 123aezakmi123** [comment]
Con l'aggiornamento al FW 2.0.0 mi ero dimenticato di impostarli, colpa mia
Grazie
