### ISSUE TITLE
Can't recover DSLAM Version

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#478]
GUI: 8.12.5
Modem: DGA4132

![cattura](https://user-images.githubusercontent.com/44716486/52539805-a2182300-2d82-11e9-8fa3-8513b413349e.PNG)

@Ansuel @FrancYescO

**Comment by FrancYescO** [comment]
perche' c'e' un driver settato diverso dal visualizzato? comunque e' probabilmente un'incompatibilita' tra il modulo kernel e quel driver.

l'xDSL si sincronizza?

**Comment by Ghost9090** [comment]
Si la portante si vede

**Comment by Ghost9090** [comment]
@FrancYescO  e poi la telegestione senza motivo si disattiva e non me la fa più attivare capita molte volte

**Comment by FrancYescO** [comment]
lo fa con tutti i driver xdsl o solo con quello che tieni caricato?

**Comment by Ghost9090** [comment]
lo faceva con tutti

**Comment by xes** [comment]
Issue happens after ANY reboot. 
Re-applying or updating the same GUI fixes the error. 
After GUI update/install, xdsl card shows all the information without the error. 

Are we missing any variable/path init on boot?

**Comment by FrancYescO** [comment]
Missing version, firmware and model.
________________________________

**Comment by xes** [comment]
FrancYescO:  but this happens with any GUI 8.13.* (so far), firmware 2.0.0 and 1.1.2 on DGA 4132

**Comment by Kherby** [comment]
This also happens on my DGA4132 @9.1.53-dev and fw 2.0.0... Is there any fix?

**Comment by Ansuel** [comment]
service transformer restart 

Does this fix the problem?

**Comment by Kherby** [comment]
@Ansuel 
Yes, it does....
