### ISSUE TITLE
web GUI empty + SSH not responding

### ISSUE THREAD

**Issue by boynet7000** [Ansuel/tch-nginx-gui#480]
Device Model: Technicolor 789vac2, firmware UNO (Mint v17.2) on bank 1, bank 2 empty
Gui Version: dev 8.12.3
configuration: bridge via ethernet WAN port, modem IP fixed
Description of problem: using this GUI, tiles in web gui disappeared after setting up the "bridge mode" via web gui. SSH no more responding. PC on lan port still can't access to internet, but without webUI, I don't know how to continue configuration.... (I'm not good in SSH or directly altering config files)

After hard reset, I installed the "stable" 8.11 version and managed to set it up.
But:
error with "Export configuration" button
modem seem not to sync date&time with NTP server

**Comment by Ansuel** [comment]
news?

**Comment by boynet7000** [comment]
tiles ok also with "stable" GUI v9.x
error in exporting configuration: fixed follwoing a post on a forum (don't konw if I can write forum name, ecc.)
NTP not working: in reply to another issue, I was told it is normal bescause modem doesn't see internet in bridge mode as I'm using WAN port.

Actually, my Technicolor is working as an access point giving internet to wireless and ethernet connected devices. This is the only configuration I managed to set up...

Is it possibile to "tell" Tecnicolor that internet is available via WAN port? The gateway, DHCP server, ecc. are on the same network (192.168.1.x).

**Comment by FrancYescO** [comment]
If you want the technicolor stay on the same subnet don't use the wan port, connect it lan-lan, disable DHCP and manually set a gateway to allow the gateway to get internet


Ps. Feel free to post forum link.
