### ISSUE TITLE
Enhancement Mappa Dispositivi

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#481]
![immagine](https://user-images.githubusercontent.com/38593316/52634286-19ef6600-2ec7-11e9-91a5-f6d96586f6b6.png)
si potrebbero mettere le scritte in bianco per vederle meglio?

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/52634394-676bd300-2ec7-11e9-9691-c4300158b12b.png)
per i dispositivi cablati si potrebbe mettere la negoziazione della porta ethernet. grazie

**Comment by bovirus** [comment]
@nclmrc 

Essendo le due richieste diverse dovresti secondo me aprire per la seconda un ticket diverso.
La negoziazione della velocità della porta ethernet è solitamente automatica.

**Comment by nclmrc** [comment]
si però la gui non ricava il valore, dovrebbe essere 100 invece vedo 0

**Comment by nclmrc** [comment]
ora  cliccando i dispositivi wireless non visualizzo più i dettagli

**Comment by nclmrc** [comment]
@Ansuel potresti guardare anche questa nelle prossime stable? Grazie

**Comment by Ansuel** [comment]
@nclmrc puoi riassumere i problemi ?

**Comment by nclmrc** [comment]
Sono primcipalmente 3. Il colore del testo è molto simile a quello di background. Per i dispositivi ethernet la speed è 0 invece della negoziazione porta. Per quelli Wifi se vengono cliccati non si apre il dettaglio.

**Comment by nclmrc** [comment]
@Ansuel Sono principalmente 3. Il colore del testo è molto simile a quello di background. Per i dispositivi ethernet la speed è 0 invece della negoziazione porta. Per quelli Wifi se vengono cliccati non si apre il dettaglio.

**Comment by nclmrc** [comment]
@Ansuel per il colore del testo su sfondo scuro andrebbe messo bianco. Con altri temi si vede correttamente.

**Comment by Ansuel** [comment]
riguardo la speed c'è da indagare perchè c'è  un bug subdolo dietro... (funziona di tanto in tanto)

**Comment by nclmrc** [comment]
I dispositivi in Wifi si vedono. Ma il colore ancora è scuro su sfondo scuro

**Comment by nclmrc** [comment]
Per la speed a me esce sempre 0

**Comment by nclmrc** [comment]
![Screenshot_20190316-200101_Chrome](https://user-images.githubusercontent.com/38593316/54480249-6e6b6580-4826-11e9-88cf-61dadd8d8e67.jpg)

**Comment by Ansuel** [comment]
ora dovrebbe andar bene... rimane solo il problema della speed che ogni tanto rompe...

**Comment by nclmrc** [comment]
Nella versione mobile il problema del colore è rimasto.

**Comment by nclmrc** [comment]
E i colleghi eth hanno sempre speed = 0

**Comment by FrancYescO** [comment]
ma quella visualizzazione non e' solo per i dispositivi wireless  come fai a guardarci quelli eth ?

**Comment by nclmrc** [comment]
Ci clicco sopra

**Comment by nclmrc** [comment]
Problema colore mobile risolto.  Manca solo speed Ethernet.

**Comment by nclmrc** [comment]
ora mi esce 0 anche per i dispositivi in 5ghz
