### ISSUE TITLE
Driver change script

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#482]
Vi funziona la funzionalità di cambio driver da GUI?

**Comment by Ghost9090** [comment]
A me sembra che non cambia nulla..

**Comment by Ghost9090** [comment]
Cambio il driver e di solito si dovrebbe disconnettere la linea e poi agganciarsi di nuovo..  e non lo fa

**Comment by nclmrc** [comment]
Si è rotta nelle ultime GUI

**Comment by Ghost9090** [comment]
@FrancYescO @Ansuel

**Comment by Ansuel** [comment]
si può avere un logread di dopo la pressione del tasto ?

**Comment by nclmrc** [comment]
Avevo già provato io, lo strano non intercetta niente.

**Comment by nclmrc** [comment]
Spero di esserti stato utile.

**Comment by Ansuel** [comment]
Testa se puoi

**Comment by nclmrc** [comment]
Funziona!!!

**Comment by Ansuel** [comment]
bene
