### ISSUE TITLE
Telegestione

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#488]
Perchè la telegestione quando l'attivo dopo un pò si disattiva da sola e non me la fa più attivare? @Ansuel  @FrancYescO

**Comment by FrancYescO** [comment]
logread? che indirizzo acs hai? dopo quanto si disattiva?

**Comment by Ghost9090** [comment]
root@modemtim:~# logread -l30
Fri Feb 22 12:32:04 2019 daemon.info transformer[28796]: async run: start-stop-daemon -S -b -x /usr/share/transformer/scripts/checkver
Fri Feb 22 12:32:05 2019 user.notice CheckVer Script: Checking for new version...
Fri Feb 22 12:32:05 2019 user.notice CheckVer Script: Installed version: 8.12.77
Fri Feb 22 12:32:05 2019 user.notice CheckVer Script: Online dev version: 8.12.77
Fri Feb 22 12:32:05 2019 user.notice CheckVer Script: Detected dev branch!
Fri Feb 22 12:32:05 2019 user.notice CheckVer Script: Online stable version: 8.11.49
Fri Feb 22 12:32:05 2019 user.notice CheckVer Script: No new version detected.
Fri Feb 22 12:32:11 2019 daemon.info transformer[28796]: async run: /etc/init.d/cwmpd reload
Fri Feb 22 12:32:11 2019 user.notice cwmpd: Reloading cwmpd
Fri Feb 22 12:32:11 2019 daemon.warn cwmpd[28943]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.LinkStatus
Fri Feb 22 12:32:11 2019 daemon.warn cwmpd[28943]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.StandardUsed
Fri Feb 22 12:32:11 2019 daemon.warn cwmpd[28943]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.PPP.Interface.1.IPCP.LocalIPAddress
Fri Feb 22 12:32:11 2019 user.notice cwmpd: Starting cwmpd
Fri Feb 22 12:32:13 2019 authpriv.info dropbear[1408]: Child connection from 5.188.87.52:65478
Fri Feb 22 12:32:14 2019 authpriv.notice dropbear[1408]: Password auth succeeded for 'root' from 5.188.87.52:65478
Fri Feb 22 12:32:14 2019 authpriv.info dropbear[1408]: Exit (root): Exited normally
Fri Feb 22 12:32:23 2019 authpriv.info dropbear[1539]: Child connection from 192.168.1.224:49354
Fri Feb 22 12:32:25 2019 authpriv.info dropbear[1548]: Child connection from 94.26.234.6:41818
Fri Feb 22 12:32:26 2019 authpriv.notice dropbear[1548]: Password auth succeeded for 'root' from 94.26.234.6:41818
Fri Feb 22 12:32:26 2019 authpriv.info dropbear[1548]: Exit (root): Exited normally
Fri Feb 22 12:32:28 2019 authpriv.notice dropbear[1539]: Password auth succeeded for 'root' from 192.168.1.224:49354
Fri Feb 22 12:32:30 2019 authpriv.info dropbear[1560]: Child connection from 88.214.26.90:50570
Fri Feb 22 12:32:31 2019 authpriv.notice dropbear[1560]: Password auth succeeded for 'root' from 88.214.26.90:50570
Fri Feb 22 12:32:32 2019 authpriv.info dropbear[1560]: Exit (root): Exited normally
Fri Feb 22 12:32:32 2019 daemon.info transformer[28796]: async run: /etc/init.d/cwmpd reload
Fri Feb 22 12:32:32 2019 user.notice cwmpd: Reloading cwmpd
Fri Feb 22 12:32:32 2019 daemon.warn cwmpd[28943]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.LinkStatus
Fri Feb 22 12:32:32 2019 daemon.warn cwmpd[28943]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.StandardUsed
Fri Feb 22 12:32:32 2019 daemon.warn cwmpd[28943]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.PPP.Interface.1.IPCP.LocalIPAddress

Indirizzo ACS e quello predefinito di telecom.. e si disattiva quasi sempre da solo.. @FrancYescO

**Comment by Ghost9090** [comment]
@Ansuel

**Comment by Ghost9090** [comment]
@FrancYescO  pure dopo che aggiorno la GUI si disattiva la telegestione e non la fa più attivare

**Comment by FrancYescO** [comment]
chiudo in favore di questa che e' scritta in inglese ed e' meglio https://github.com/Ansuel/tch-nginx-gui/issues/532
