### ISSUE TITLE
8.12.22

### ISSUE THREAD

**Issue by putipower** [Ansuel/tch-nginx-gui#489]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

Device Model: dga4132
Gui Version:8.12.22

Description of problem: non funziona aggiornamento automatico da gui,provenendo da 8.12.13 .si apre la barra avanzamento ma non procede.caricandolo a mano funziona.

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by nclmrc** [comment]
non funziona il pulsante salva su tutte le schede che ho provato

**Comment by Ghost9090** [comment]
@Ansuel @FrancYescO

**Comment by nclmrc** [comment]
continua a non funzionare il pulsante salva in alcune schede come rete locale, funzioni extra ecc
