### ISSUE TITLE
Visual bug on application card

### ISSUE THREAD

**Issue by berna1995** [Ansuel/tch-nginx-gui#49]
Hi there,
i got a visual bug in the application card, no matter what GUI style i choose and no matter which browser i use.
GUI version: 7.12.12, AGTEF_1.0.3.

![blue](https://user-images.githubusercontent.com/4492170/39921988-44fe8576-551d-11e8-856a-e36bc06ea6bb.JPG)
![fritz](https://user-images.githubusercontent.com/4492170/39921989-45182a62-551d-11e8-9f2f-e60423367c6a.JPG)

**Comment by Ansuel** [comment]
fixed 1498a1d02872b599e33894a5be8958c94c60f291 clean cache if it doesn't show
