### ISSUE TITLE
Wifi tx power level

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#492]
It would be great to have control over Wifi tx power level settings. 
Would it be possible?

Usually when coverage is not an issue, I always limit Wifi power levels. 
In these devices i can't find a setting for this.

**Comment by kevdagoat** [comment]
It already exists.

**Comment by xes** [comment]
Into GUI? 

Since there are two possibilities:
- setting is not so easy find (and not present in wifi card)
- into my device is not visible for some reason.

Could you be so kind to point me where "it already exist"?

**Comment by kevdagoat** [comment]
It is present in latest GUI in wifi card

**Comment by xes** [comment]
Sorry, but with a DGN 4132 (firmware 1.1.2)  and GUI 8.12.39 i don't have that setting.

Using command line, 
wl -a wl0 txpwr
reports a weird default of ~ 1500mW (!!!)

setting:  
wl -a wl0 txpwr 15

seems to accept to set it at 15mW, but obviously it should be better to manage it via GUI.

Maybe there are other ways to set or check it. Any suggestion is welcome.

**Comment by towatai** [comment]
I dont have that Option too.. dga4132, FW 2.0.0, dev GUI 8.12.71

**Comment by kevdagoat** [comment]
Ok.
@FrancYescO Has this been removed, disabled when bandsteering is on or is it just me confirming the stock GUI with this one

**Comment by kevdagoat** [comment]
Looks to be fixable. There is a mapping available:

tch-nginx-gui/decompressed/gui_file/usr/share/transformer/mappings/rpc/wireless.radio.map:
‘’’
tx_power_adjust = {
                access = "readWrite",
                type = "string",
        },
‘’’

**Comment by kevdagoat** [comment]
Will look into this over next few days

**Comment by kevdagoat** [comment]
Code is there: 
```outputpower = gVIES(wifipower), -- if the parameter is not included, it does not matter, this validation function will never be called
```
