### ISSUE TITLE
Error 403 e BUG Aggiornamento

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#494]
![cattura](https://user-images.githubusercontent.com/44716486/53106596-adfaa680-3533-11e9-8882-9f9f70cd1e10.PNG)
![cattura1](https://user-images.githubusercontent.com/44716486/53106597-adfaa680-3533-11e9-8f3b-30b0fb75c778.PNG)

Foto 1: è normale che a ogni aggiornamento dopo che scarica la gui dopo 2 secondi compare questo?
Foto 2: Mi dice che c'è un aggiornamento ma se vado dentro le Impostazione GUI non ne trova @Ansuel

**Comment by Ghost9090** [comment]
con la 8.12.56 l'errore 403 è scomparso @Ansuel

**Comment by Ghost9090** [comment]
però sembra dare un altro problema.. rimane fisso su "Resetting cwmp and watchdog"

**Comment by Ghost9090** [comment]
ti devo dare il logread? @Ansuel

**Comment by Ghost9090** [comment]
[LOGREAD GUI.txt](https://github.com/Ansuel/tch-nginx-gui/files/2885507/LOGREAD.GUI.txt)
vedi se ti è utile.. @Ansuel

**Comment by Ghost9090** [comment]
[LOGREAD GUI.txt](https://github.com/Ansuel/tch-nginx-gui/files/2885537/LOGREAD.GUI.txt)
@Ansuel ecco quello completo

**Comment by putipower** [comment]
@ansuel confermo che rimane fermo dopo tutta l installazione su "Resetting cwmp and watchdog"
se aggiorno pagina torna al login e l'aggiornamento è andato a buon fine

**Comment by Ghost9090** [comment]
@putipower  
![cattura](https://user-images.githubusercontent.com/44716486/53108419-49414b00-3537-11e9-87d6-2534c168bc21.PNG) il problema è che se uno fa controlla aggiornamenti compare sempre questo.. @Ansuel

**Comment by Ghost9090** [comment]
@Ansuel anche se hai provato a fixare quel "Not Started" continua a rimanere così

**Comment by putipower** [comment]
aggiornando a .57 e' ricomparso 403 forbidden appena inizia aggiornamento

**Comment by Ghost9090** [comment]
[LOGREAD GUI.txt](https://github.com/Ansuel/tch-nginx-gui/files/2885620/LOGREAD.GUI.txt)
@Ansuel

**Comment by Ansuel** [comment]
VI STATE CALMI PER FAVORE -.-

**Comment by Ghost9090** [comment]
almeno devi essere contento di quelli che ti dicono i problemi..

**Comment by Ansuel** [comment]
non è essere contento o non contento...
sono quasi 20 messaggi in meno di mezz'ora calmatevi...

attendete e basta... reportare lo stesso problema 20 volte di certo non velocizza le cose

**Comment by Ansuel** [comment]
riguardo errore 403 si sta ancora indagando...

**Comment by Ghost9090** [comment]
gli altri sono riparati?

**Comment by Ansuel** [comment]
si

**Comment by nclmrc** [comment]
Upgrade Script: Downloading GUI file...
Upgrade Script: Downloaded gui with hash: 33848e4c96defac208bc7f446ad29d8f
Upgrade Script: Dev branch detected... Checking for newer version in stable...
Upgrade Script: Downloaded stable gui with hash: d3aa2bd723cfc77ca0606293f882c3ec
Upgrade Script: Stable version found: 8.11.49
Upgrade Script: Dev version found: 8.12.66
Upgrade Script: Cleaning www dir
Upgrade Script: Extracting file...
Upgrade Script: Copying file to permanent dir...
Upgrade Script: Running rootdevice script
Root Script: Rooting in progress...
Root Script: Apply specific device file...
Root Script: DGA device detected!
Root Script: Extracting custom-ripdrv-specificDGA.tar.bz2 ...
Root Script: Extracting telnet_support-specificDGA/TG800.tar.bz2 ...
Root Script: Extracting upgrade-pack-specificDGA.tar.bz2 ...
Root Script: Extracting upnpfix-specificDGA.tar.bz2 ...
Root Script: Extracting dlnad_supprto-specificDGA.tar.bz2 ...
Root Script: Extracting wgetfix-specificDGA.tar.bz2 ...
Root Script: StateMachine tar md5sum: 61eb9c3195f8a6c0111a867457cd9f67
Root Script: StateMachine md5sum: 61eb9c3195f8a6c0111a867457cd9f67
Root Script: Removing specific file and resuming root process...
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Unlocking web interface if needed
Root Script: Check variant_friendly_name set
Root Script: Check and cleanup
Root Script: Remove default dns
Root Script: Purify wan
Root Script: Fix dns bug
Root Script: Enable dlnad
Root Script: Fix Sysupgrade
Root Script: Check orig config
Root Script: Restore original mapper
Root Script: Transformer lib check
Root Script: Remove https check
Root Script: Check css presence
Root Script: Check if dnsmasq is names as we need it for the webui
Root Script: Check driver setting
Root Script: Check Dropbear config file
Root Script: Check ddns directory
Root Script: Check eco param
Root Script: Enable new upnp
Root Script: Sync dhcp configuration for new webui
Root Script: Create gui type in config
Root Script: Add new web option
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
Root Script: Moving aria2 dir
Root Script: Creating new option for led definition
Root Script: LedEventing new md5sum: c042d83ecde3331471f0a6802b46cd91
Root Script: LedEventing md5sum: c042d83ecde3331471f0a6802b46cd91
Root Script: Old build detected, moving wansensing file
Root Script: Checking downgrade limitation bit
Root Script: Checking opkg conf
Root Script: Creating and checking real version
Root Script: Creating new wol implementation
Root Script: Sync new xdsl option
Root Script: Creating utility simbolic link
Root Script: Clean old script
Root Script: Adding fast cache options
Root Script: Reworking sfp interface in network...
Root Script: Reinstalling telstra gui if needed...
Root Script: Checking if wan_mode option exist...
Root Script: Inizialize and start dosprotect...
Root Script: Checking if intercept is enabled and disabling it if on...
Root Script: Trying to clean wansensing script from hardcoded interface...
Root Script: Disabling coredump function...
Root Script: Restoring nginx additional option if needed...
::sysinit:/etc/init.d/rcS S boot
::shutdown:/etc/init.d/rcS K shutdown
::askconsolelate:/bin/login
Root Script: Setting root flag
Root Script: Reset unlock bit
Root Script: Save root password if modified
Root Script: Setting dropbear settings
Root Script: Restarting dropbear
Root Script: Doing various check and generating hash...
Root Script: Update branch detected: DEV
Root Script: Updating GUI in /root folder from /tmp
Root Script: Detected upgrade!
Root Script: Old GUI hash: 33848e4c96defac208bc7f446ad29d8f
Root Script: New GUI hash: 33848e4c96defac208bc7f446ad29d8f
Root Script: Resetting version info...
Root Script: Add checkversion to cron...
Root Script: Apply modification
Root Script: Restarting dnsmasq if needed...
Root Script: Checking if ISP is detected...
Root Script: Trafficmon inizialization
Root Script: Resetting cwmp and watchdog
Root Script: Process done.
Root Script: Restarting transformer
Root Script: Stopping nginx
Root Script: Restarting nginx...
Upgrade Script: Upgrade Done
root@DGA4132:~#

**Comment by nclmrc** [comment]
Non capisco perché cosa succede quando clicco sull'ingranaggio quando viene proposto un nuovo aggiornamento perché perdo per qualche istante la pagina web del modem .  Non appare più in alto la scheda aggiorna.

**Comment by Ansuel** [comment]
non ci ho capito nulla

**Comment by nclmrc** [comment]
Esce questo errore Wed Feb 20 21:58:32 2019 kern.warn kernel: [23219.486000] FCACHEfc_query_fdb ERROR: net_fdb_p<0xd4e264e0> key<0x3003> fdb_p<0x  (null)>
Wed Feb 20 21:58:32 2019 kern.warn kernel: [23219.501000] FCACHEfc_query_fdb ERROR: net_fdb_p<0xd4e264e0> key<0x3003> fdb_p<0x  (null)>

**Comment by Ansuel** [comment]
spiega meglio il problema...

**Comment by nclmrc** [comment]
Con l'ultimo aggiornamento se trova una nuova versione della GUI non esce più la scheda aggiorna in alto. Confermi?

**Comment by nclmrc** [comment]
Mi sembra che quando clicco su controlla aggiornamenti non si limita a cercare gli aggiornamenti.

**Comment by Ansuel** [comment]
che non esce il bottone è un bug 

quando si clicca il bottone fa la medesima azione

**Comment by nclmrc** [comment]
Ora dopo il login il browser dice empty response

**Comment by Ansuel** [comment]
aggiorna da console... già fixato

**Comment by nclmrc** [comment]
Questo cè sempre
Wed Feb 20 21:58:32 2019 kern.warn kernel: [23219.486000] FCACHEfc_query_fdb ERROR: net_fdb_p<0xd4e264e0> key<0x3003> fdb_p<0x (null)>
Wed Feb 20 21:58:32 2019 kern.warn kernel: [23219.501000] FCACHEfc_query_fdb ERROR: net_fdb_p<0xd4e264e0> key<0x3003> fdb_p<0x (null)>

**Comment by nclmrc** [comment]
Prima controlla aggiornamenti faceva scomparire il popup dell'aggiornamento.

**Comment by nclmrc** [comment]
Il pulsante aggiorna ancora non cè

**Comment by Ansuel** [comment]
il pulsante aggiorna esce se c'è una nuova versione disponibile

**Comment by nclmrc** [comment]
Ora dopo un riavvio alcune cose si sono sistemate da sole. Possibile prima che cliccando su controllla aggiornamenti ci fosse un refresh della pagina?

**Comment by FrancYescO** [comment]
si ora non e' piu necessario

**Comment by nclmrc** [comment]
ok mi torna che il popup non va via con controlla aggiornamenti, ma con un refresh

**Comment by nclmrc** [comment]
Ora non appare più.

**Comment by putipower** [comment]
passando a .77  e' comparso errore 403 forbidden appena si lancia aggiornamento.si risolve con un refresh.

**Comment by bovirus** [comment]
Avete provato con le ultime? Esempio 87?

**Comment by putipower** [comment]
si con la .87 mi si blocca con errore 403.aspetto che finisca di lampeggiare il modem,poi faccio refresh e compare login

**Comment by bovirus** [comment]
Se non dovesse funzionare fai come me.

Scarica la build 88 (sistemato problema doppia stringa in webui-core.po in it e de).
Se non riesci ad accedere alla GUi usa WinSCP e ricarica la build 88 con il solito sistema (file in /tmp - apertuira prompt e comandi).
La GUI tornerà operativa.

**Comment by putipower** [comment]
ho aggiornato da gui a .88.solito errore 403.non mi serve accedere da shell,basta fare un refresh della pagina e mi compare il login con la .88 installata

**Comment by Ghost9090** [comment]
![cattura](https://user-images.githubusercontent.com/44716486/53287196-d9220780-3778-11e9-9cae-d171d9a77cd6.PNG)
@bovirus questo va tradotto

**Comment by giulio63** [comment]
Device Model: TIM HUB DGA-4132
Firmware 2.0.0
Gui Version: 8.12.91

Descrizione del problema :

Al termine degli ultimi aggiornamenti, si ha  **"503 Service Temporarily Unavailable - nginx"** . facendo rifare l'aggiornamento da ssh si risolve, ma andrebbe corretto

**Comment by FrancYescO** [comment]
rilevate ancora problemi?

**Comment by Ghost9090** [comment]
@FrancYescO https://github.com/Ansuel/tch-nginx-gui/issues/512

**Comment by FrancYescO** [comment]
e cosa c'entra qui? se c'e' un issue aperta per una cosa e' inutile che scrivi in un'altra dove non c'entra nulla.
e come ti abbiamo fatto gia' notare, puoi anche smettere di taggare a muzzo.

**Comment by giulio63** [comment]
a me dopo gli ultimissimi aggiornamenti non da più problemi . ( Firmware 2.0.0 e Gui Dev ultima versione disponibile ) Grazie

**Comment by putipower** [comment]
nessun problema di installazione con firmware 2.0.1-001
grazie

**Comment by Ghost9090** [comment]
503 Service Temporarily Unavailable
nginx e come al solito sto errore non viene mai risolto. @FrancYescO

**Comment by Ansuel** [comment]
Al solito.....................

Il Lun 25 Feb 2019, 11:12 Ghost9090 <notifications@github.com> ha scritto:

**Comment by giulio63** [comment]
contrordine....non so cosa con precisione cosa sia cambiato negli ultimi aggiornamenti, ma per aggiornarsi alla versione 8.13.7 , al termine da' nuovamente il messaggio

**503 Service Temporarily Unavailable - nginx**

ed aggiornandola da ssh si sistema tutto

**Comment by FrancYescO** [comment]
quando da 503 potete dare un output del comando `free`? quando da 403 basta sempre un refresh della pagina giusto?

**Comment by giulio63** [comment]
non so se sia utile, adesso che l'ho aggiornata manualmente da ssh comunque ecco l'output del comando **free** : 
root@modemtim:~# **free**
                     total           used             free       shared      buffers
Mem:        484296       314992       169304                0        18584
-/+ buffers:                  296408       187888
Swap:                 0                  0                 0

**Comment by putipower** [comment]
giulio scusa se ti ricapita provi a fare refresh della pagina del browser dopo che ha smesso di lampeggiare il modem?quando mi dava quell'errore non ho mai aperto ssh,solo aggiornato browser e compare login con aggiornamento perfettamente eseguito.
ho aggiornato a 13.7 e non mi ha dato problemi,

**Comment by giulio63** [comment]
credo di averlo fatto prima di utilizzare l'ssh , ma se ricapita lo faccio sicuramente e riferisco qui. grazie

**Comment by putipower** [comment]
ho in uso 2 dga4132 uno fa da modem router il secondo e' su wan e lo accendo all'occorrenza.sul primo nessun problema all'aggiornamento a 13.8 il secondo errore 403
risultato shell free durante aggiornamento del secondo modem
/$ free
             total         used         free       shared      buffers
Mem:        484296       286060       198236            0        15400
-/+ buffers:             270660       213636
Swap:            0            0            0
/$ free
             total         used         free       shared      buffers
Mem:        484296       288472       195824            0        15400
-/+ buffers:             273072       211224
Swap:            0            0            0
/$ free
             total         used         free       shared      buffers
Mem:        484296       291984       192312            0        15400
-/+ buffers:             276584       207712
Swap:            0            0            0
/$ free
             total         used         free       shared      buffers
Mem:        484296       289112       195184            0        15400
-/+ buffers:             273712       210584
Swap:            0            0            0
/$ free
             total         used         free       shared      buffers
Mem:        484296       294068       190228            0        15400
-/+ buffers:             278668       205628
Swap:            0            0            0
/$ free
             total         used         free       shared      buffers
Mem:        484296       286456       197840            0        15400
-/+ buffers:             271056       213240
Swap:            0            0            0
/$ free
             total         used         free       shared      buffers
Mem:        484296       286228       198068            0        15400
-/+ buffers:             270828       213468
Swap:            0            0            0

confermo che basta un refresh del browser per avere login con gui installata

**Comment by Ghost9090** [comment]
![screenshot_20190227-003534_chrome](https://user-images.githubusercontent.com/44716486/53454502-b9fcd180-3a27-11e9-80e4-05b972fbbcdc.jpg)
In un tab manca la scritta @Ansuel

**Comment by Ansuel** [comment]
i'm really trying to reproduce this but i can't find a way to do it...

can  someone post a logread after the error?

**Comment by Ghost9090** [comment]
Eh?

**Comment by putipower** [comment]
sul modem primario nessun problema di aggiornamento,il secondario ad ogni aggiornamento da errore 403
logread
Thu Feb 28 10:19:34 2019 daemon.info transformer[3220]: async run: start-stop-daemon -S -b -x /usr/share/transformer/scripts/upgradegui GuiRequest
Thu Feb 28 10:19:35 2019 user.notice Upgrade Script: Downloading GUI file...
Thu Feb 28 10:19:37 2019 user.notice Upgrade Script: Downloaded GUI with hash: e1c589c1e57e7b10fde498f23729bca0
Thu Feb 28 10:19:37 2019 user.notice Upgrade Script: Dev branch detected... Checking for newer version in stable...
Thu Feb 28 10:19:39 2019 user.notice Upgrade Script: Downloaded stable GUI with hash: d3aa2bd723cfc77ca0606293f882c3ec
Thu Feb 28 10:19:39 2019 user.notice Upgrade Script: Stable version found: 8.11.49
Thu Feb 28 10:19:39 2019 user.notice Upgrade Script: Dev version found: 8.13.16
Thu Feb 28 10:19:39 2019 user.notice Upgrade Script: Cleaning www dir
Thu Feb 28 10:19:41 2019 daemon.err nginx: 2019/02/28 10:19:41 [error] 4222#0: *4 directory index of "/www/docroot/" is forbidden, client: 192.168.2.159, server: localhost, request: "GET / HTTP/1.1", host: "192.168.2.1", referrer: "http://192.168.2.1/"
Thu Feb 28 10:19:41 2019 daemon.err nginx: 2019/02/28 10:19:41 [error] 4222#0: *8 directory index of "/www/docroot/" is forbidden, client: 192.168.2.159, server: localhost, request: "GET / HTTP/1.1", host: "192.168.2.1"
Thu Feb 28 10:19:42 2019 user.notice Upgrade Script: Extracting file...
Thu Feb 28 10:19:47 2019 kern.warn kernel: [  509.649000] dosprotect rpfilter drop IN=eth4 OUT= MAC=01:00:5e:00:00:fb:d8:1d:72:33:ae:b1:08:00 SRC=192.168.1.26 DST=224.0.0.251 LEN=89 TOS=0x00 PREC=0x00 TTL=255 ID=57995 PROTO=UDP SPT=5353 DPT=5353 LEN=69 MARK=0x8000000 
Thu Feb 28 10:19:48 2019 kern.warn kernel: [  510.652000] dosprotect rpfilter drop IN=eth4 OUT= MAC=01:00:5e:00:00:fb:d8:1d:72:33:ae:b1:08:00 SRC=192.168.1.26 DST=224.0.0.251 LEN=89 TOS=0x00 PREC=0x00 TTL=255 ID=63102 PROTO=UDP SPT=5353 DPT=5353 LEN=69 MARK=0x8000000

**Comment by Ghost9090** [comment]
![screenshot_20190228-194519_chrome](https://user-images.githubusercontent.com/44716486/53590207-8938ab80-3b91-11e9-8511-e12cb7c08a4d.jpg)
Dopo l'ultimo aggiornamento rimane così @Ansuel

**Comment by FrancYescO** [comment]
come si comporta ora con gli upgrade ?

**Comment by Ghost9090** [comment]
Ora va

**Comment by putipower** [comment]
oggi per la prima volta l'aggiornamento sul secondario in wan è andato bene.però mi ha dato errore il modem,ma forse è dipeso dal fatto che avevo dato il comando sudo sysctl -w vm.drop_caches=3 per liberare memoria

**Comment by Ghost9090** [comment]
![screenshot_20190301-183446_chrome](https://user-images.githubusercontent.com/44716486/53655557-c748d480-3c50-11e9-8f27-3e306da696a9.jpg)
Ultima gui dev. Dopo che accedo al modem @Ansuel @FrancYescO

**Comment by Ansuel** [comment]
@Ghost9090 ho fixato l'errore del qos... spero abbia letto su forum o altro come fixare quell'errore

**Comment by Ghost9090** [comment]
@Ansuel non è possibile creare uno script che permette di eliminare i file della gui e la installa tramite aggiornamento in maniera pulita?

**Comment by Ansuel** [comment]
??? E cosa pensi faccia lo script di aggiornamento

**Comment by Ghost9090** [comment]
@Ansuel perché vedo che la password del root continua a cambiarsi da sola senza motivo..

**Comment by Ghost9090** [comment]
![screenshot_20190303-140351_chrome](https://user-images.githubusercontent.com/44716486/53695540-3f340d80-3dbd-11e9-8d8f-cd9660113394.jpg)
Non si vede più il carico della cpu

**Comment by Ghost9090** [comment]
@Ansuel

**Comment by Ghost9090** [comment]
Per la questione password del root che cambia da sola?

**Comment by Ghost9090** [comment]
Sto notando che parecchie volte quando la Gui si aggiorna si blocca verso la fine e compare questo errore 
![screenshot_20190303-164452_chrome](https://user-images.githubusercontent.com/44716486/53697648-d73cf180-3dd3-11e9-8f5a-b62fed9afe85.jpg)
