### ISSUE TITLE
Comandi riavvio ed esporta in scheda gateway non funzionano (GUI 8.12.67)

### ISSUE THREAD

**Issue by McClodde** [Ansuel/tch-nginx-gui#496]
Device Model:  DGA4132
Gui Version: 8.12.67

Description of problem:
Comandi riavvio ed esporta in scheda gateway non funzionano

How to reproduce (if possible):
Dopo aggiornamento a ultima gui sviluppatore

**Comment by Ansuel** [comment]
da me funzionano entrambi

**Comment by McClodde** [comment]
Ho forzato il riaggiornamento dell'interfaccia, l'export è tornato a funzionare, ma il riavvio no. Appare la finestra Riavvia Dispositivo, se premo su OK non fa nulla. Vorrei riavviare per vedere se si sistema, con che comando posso riavviare da shell?

**Comment by Ansuel** [comment]
nha non si sistema... sono io che sto facendo test grazie per la segnalazione!

**Comment by McClodde** [comment]
Se può servire, mi è arrivata la segnalazione di un nuovo aggiornamento : 8.12.70 l'ho installato, funziona l'export ma non ancora il riavvio, se premo su OK non si riavvia.

**Comment by Ansuel** [comment]
sisi fixato aspetta prossimo aggiornamento funziona tutto ;)
