### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#50]
Nelle ultime versioni della 7.12 hai fatto qualche modifica al CSS?

**Comment by Ansuel** [comment]
forse una perchè?

**Comment by nclmrc** [comment]
Nella versione mobile le schede vanno non si vedono per intero

**Comment by nclmrc** [comment]
La trasformazione da esadecimale a decimale vorrebbe fatta solo su dslam broadcom?

**Comment by Ansuel** [comment]
non chiedere troppe robe insieme... comunque per ora l'ho settata solo su dslam broadcom siccome non so se per gli altri la transformazione è uguale... (mi puoi dire come è la versione per gli altri? )

puoi mettere screen della versione mobile?

**Comment by nclmrc** [comment]
![screenshot_20180512-184325](https://user-images.githubusercontent.com/38593316/39959623-7b344b60-5614-11e8-8cfd-63972036fe40.png)
![screenshot_20180512-184206](https://user-images.githubusercontent.com/38593316/39959624-80f82dd2-5614-11e8-94d5-c894e5116bb6.png)

**Comment by nclmrc** [comment]
Comunque la codifica penso sia 13.8.7

**Comment by Ansuel** [comment]
AH! ALLORA è DIVERSA DAI BROADCOM!

**Comment by Ansuel** [comment]
puoi testare l'ultima dev ora dovrebbe essere visualizzata bene la versione del firmware

**Comment by nclmrc** [comment]
Si grazie. Rimane ancora in parte il problema della scheda fonia

**Comment by adryx92** [comment]
Entro a gamba tesa, dato che si parla di CSS. 
Ieri provavo a disabilitare degli switch (nello specifico nella sezione di port forwarding) da browser mobile (sia Chrome che FF su Android) e gli switch non si muovevano. Anche provando con visualizzazione sito desktop non cambiava nulla.

**Comment by Ansuel** [comment]
leggere non è di casa...
(scritto in blu nella sezione)
**Per disabilitare le Regole della Mappatura Porte, modifica la regola sulla destra e poi usa l'interruttore sulla sinistra.**

**Comment by adryx92** [comment]
Pardon, non essendo stilato benissimo, non si vedeva l'alert.

**Comment by nclmrc** [comment]
Noto il problema su diverse schede e sotto schede.
![screenshot_20180516-235758](https://user-images.githubusercontent.com/38593316/40146362-871b852a-5965-11e8-968f-901641411be1.png)
