### ISSUE TITLE
Spoof setting variable changed to 1.1.2 after GUI dev update (checked with TIM app)

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#507]
Tested on GUI dev build 88 (tested and also on previous)

When you update the GUI dev the Spoof settings variable was reset to the value of 1.1.2.
Es. set the Spoof setting variable via TIM app to 2.0.0, then update GUI dev.
At reboot the spoof setting variable get from TIM app seems to be set to 1.1.2
Tested it with TIM app.

The Spoof setting variable shouldn't be changed after a GUI dev update.

Please check and fix if it's possible. Thanks.

**Comment by FrancYescO** [comment]
Should be fixed with https://github.com/Ansuel/tch-nginx-gui/commit/f6dff6cfeeaeb11c5cd2a79e21983a1d876eb0bb (and https://github.com/Ansuel/tch-nginx-gui/commit/f153133bac42e34ad67384bee837e04bdf9209af)
