### ISSUE TITLE
Formattazione campi in tab Gateway troncati invece che in unica riga

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#508]
Device Model: TIM HUB DGA-4132
Gui Version: 8.12.88

Descrizione del problema :

Nella tab **Gateway** 

in **Informazioni globali** -  **Versione bootloader**

ed in

**Informazioni banco** - **Versione attiva** e **Versione passiva**

i valori sono troncati anzichè essere su un unica riga

**Comment by bovirus** [comment]
@giulio63 

Puoi per favore allegare uno screenshot?

**Comment by giulio63** [comment]
@bovirus 
Vedo che già è stato corretto con uno degli aggiornamenti del 23/02. ( le 3 stringhe erano troncate e non su unica riga ) . Grazie
