### ISSUE TITLE
xDSL graphics throw error if not connected

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#51]
When you call up xDSL graphics while DSL is not connected, the busy animation goes on forever.

logread gives multiple errors like this:

```
Sun May 13 15:56:59 2018 daemon.err transformer[6706]: [truncated] getter(rpc.xdslctl., HlogScanBand) threw an error: /usr/share/transformer/mappings/rpc/xdslctl.map:291: attempt to compare number with nil
stack traceback:
        /usr/share/transformer/mappings/rpc/xdslctl.map:291: in function </usr/share/transformer/mappings/rpc/xdslctl.map:275>
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/lua/transformer/navigation.lua:169: in function 'get_parameter_value'
        /usr/lib/lua/transformer/navigation.lua:207:Sun May 13 15:56:59 2018 daemon.err transformer[6706]: [truncated] getter(rpc.xdslctl., HlogUs1) threw an error: /usr/share/transformer/mappings/rpc/xdslctl.map:291: attempt to compare number with nil

...

stack traceback:
        /usr/share/transformer/mappings/rpc/xdslctl.map:300: in function </usr/share/transformer/mappings/rpc/xdslctl.map:275>
```

**Comment by Ansuel** [comment]
can you test latest dev?

**Comment by meyergru** [comment]
With 7.13.18, there is now an error message in the GUI and this logread output:

```
Sun May 13 22:07:10 2018 daemon.err transformer[13316]: [truncated] getter(rpc.xdslctl., Us1BandInitial) threw an error: /usr/share/transformer/mappings/rpc/xdslctl.map:273: attempt to use a closed file
stack traceback:
        [C]: in function 'close'
        /usr/share/transformer/mappings/rpc/xdslctl.map:273: in function </usr/share/transformer/mappings/rpc/xdslctl.map:248>
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/lua/transformer/navigation.lua:169: in function 'get_parameter_value'
        /usr/lib/lua/transforSun May 13 22:07:10 2018 daemon.err nginx: 2018/05/13 22:07:10 [error] 13306#0: *9 lua entry thread aborted: runtime error: [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:24: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:24: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.168.10.97, server: localhost, request: "GSun May 13 22:07:12 2018 daemon.notice wansensing: (L2Sense) runs L2Main.check(timeout)
```

**Comment by Ansuel** [comment]
try now

**Comment by meyergru** [comment]
Now there are no log errors, but the waiting popup keeps spinning:

![grafik](https://user-images.githubusercontent.com/17402664/39971512-8ee7a394-56fc-11e8-90d9-a9a482257248.png)

**Comment by Ansuel** [comment]
https://www.youtube.com/watch?v=PGNiXGX2nLU

anyway... 

give me the browser log... it should point to some javascript error

**Comment by meyergru** [comment]
Correct:

![grafik](https://user-images.githubusercontent.com/17402664/39971663-1d5e4a90-56ff-11e8-9271-5cb7e33c0cb9.png)

**Comment by Ansuel** [comment]
click on more information... on the right it should see something clickable with #:

**Comment by meyergru** [comment]
![grafik](https://user-images.githubusercontent.com/17402664/39971682-87f5d79c-56ff-11e8-988f-4cd9f11f8db4.png)

**Comment by Ansuel** [comment]
can you give me the output of this 

transformer-cli get rpc.xdslctl.HlogScanBand

**Comment by meyergru** [comment]
Sure, without DSL connection, it is:

```
rpc.xdslctl.HlogScanBand [string] = 4094
```

Interesting, with a DSL connection, that gives:

```
rpc.xdslctl.HlogScanBand [string] = 4096
```

**Comment by Ansuel** [comment]
ok try now  without and with dsl

**Comment by meyergru** [comment]
Did you upload a new GUI_dev.tar.bz2? It still is 7.13.19?

**Comment by Ansuel** [comment]
check now

**Comment by meyergru** [comment]
Without DSL still spinning and this Javascript error (no logread entries):

![grafik](https://user-images.githubusercontent.com/17402664/39972032-014ec0ac-5707-11e8-8080-9bac7ab71012.png)

**Comment by Ansuel** [comment]
now should be good

**Comment by meyergru** [comment]
Nope:

![grafik](https://user-images.githubusercontent.com/17402664/39972082-0f1b858e-5708-11e8-98a2-6dacf1b95b7d.png)

**Comment by Ansuel** [comment]
are you able to give me the javascript of the graph ? 

should be something like

```
var SNRlen = SNRChart.data.datasets[0].data.length;
var BitsLen = BitsChart.data.datasets[0].data.length;
```

**Comment by meyergru** [comment]
How can I do that? I have tried Firefox Inspector Watch Expression, but that says:

SNRChart.data.datasets[0].data.length: "TypeError: SNRChart.data is undefined"

**Comment by meyergru** [comment]
Oh, with Chrome I got this:

![grafik](https://user-images.githubusercontent.com/17402664/39972223-e95f3acc-570a-11e8-9474-5e99cc0a779d.png)

And when I follow the link:

![grafik](https://user-images.githubusercontent.com/17402664/39972225-034fd5b8-570b-11e8-8eff-40d8759b7d27.png)

**Comment by Ansuel** [comment]
try now

**Comment by Ansuel** [comment]
(anyway i'm modifying something so if the graph doesn't go with connection you know why...

**Comment by meyergru** [comment]
7.13.22:

Works without DSL (empty graphs).

Error with DSL:

![grafik](https://user-images.githubusercontent.com/17402664/39972316-d7f2fd08-570c-11e8-8346-bc5d3e6f8f4b.png)

No Javacript error, but logread:

```
Mon May 14 00:20:36 2018 daemon.err nginx: 2018/05/14 00:20:36 [error] 7760#0: *8 lua entry thread aborted: runtime error: [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:28: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:28: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.168.7.2, server: localhost, request: "GET Mon May 14 00:21:31 2018 daemon.err nginx: 2018/05/14 00:21:30 [error] 7760#0: *10 lua entry thread aborted: runtime error: [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:28: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:28: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.168.7.2, server: localhost, request: "GETMon May 14 00:22:40 2018 authpriv.info dropbear[7875]: Child connection from 192.168.7.2:56312
Mon May 14 00:22:40 2018 authpriv.notice dropbear[7875]: Pubkey auth succeeded for 'root' with key md5 71:fc:e6:9e:b1:33:9a:b0:05:55:a9:d2:3d:7b:d7:29 from 192.168.7.2:56312
Mon May 14 00:23:45 2018 daemon.err nginx: 2018/05/14 00:23:45 [error] 7760#0: *12 lua entry thread aborted: runtime error: [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:28: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:28: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.168.7.2, server: localhost, request: "GET
```

**Comment by Ansuel** [comment]
yes yes ignore for now ;) i'm making some change the qln and hlog miss some data

**Comment by meyergru** [comment]
While you are at the graphs: The last one with the bits is scrollable and has a different width than all the others. Because it is scaled out like that, it also has gaps between some bars.

**Comment by Ansuel** [comment]
well limitation of the library that i use.... if i set a lower width the data disappear.

**Comment by Ansuel** [comment]
anyway now it should work

**Comment by meyergru** [comment]
It works now with DSL connected, but with DSL off still spinning:

![grafik](https://user-images.githubusercontent.com/17402664/39980550-c9a42584-574c-11e8-8691-3d1cd23b5195.png)

![grafik](https://user-images.githubusercontent.com/17402664/39980575-ec882cc6-574c-11e8-91cf-81fd253740da.png)

I once had an error in PHP, when I output a boolean - matter-of-fact it showed that 'true' is represented by '1' but false not by '0', but by ''. So I had to use $var ? '1' : '0'.

**Comment by meyergru** [comment]
Wait! 

I have bad news and good. First the bad:

There is another bug when DSL is connected which I have never noticed because of the wide Bits graph: A few of the graphs (namely HLog and QLN) have duplicated data from sample frequency #2800 upwards:

![grafik](https://user-images.githubusercontent.com/17402664/40010566-70f248e0-57a5-11e8-9ee4-b8416b1f0ff2.png)

![grafik](https://user-images.githubusercontent.com/17402664/40010659-ae862b86-57a5-11e8-8450-0176ff64af46.png)

The data is truncated at the same frequency for SNR and Bits graphs:

![grafik](https://user-images.githubusercontent.com/17402664/40010698-d41a0f98-57a5-11e8-9491-984c8ac600c9.png)

![grafik](https://user-images.githubusercontent.com/17402664/40010723-e8104e54-57a5-11e8-864f-ed936e164ed2.png)

I believe there are errors in xdslctl.map where the band ranges are calculated.


Now for the good news:

Apart from the truncated data, I have found a way to synchronize and shorten the Bits graph. Just use a 'line' chart with the same definitions as the first three charts and then fill the area. This is done like so:

```
var bits_ctx = document.getElementById("BitsChart").getContext("2d");\
        var BitsChart = new Chart(bits_ctx, {\
    type: "line",\
    data: {labels: labelLegend,\
        "datasets":[{"data":['); ngx.print(Bits); ngx.print('],\
        "pointBackgroundColor": pointBackgroundColor,\
        "backgroundColor":"#CCFFFF",\
        "lineTension":0.1,\
        "pointBorderWidth":"0.6",\
        "pointRadius":"0.6",\
        "fill":"start",\
    }]},\
    options: {\
                maintainAspectRatio: false,\
        scales: {\
            yAxes: [{\
                ticks: {\
                    beginAtZero:true,\
                }\
            }]\
        },\
                spanGaps:false,\
                showLines:true,\
                pointStyle:"cross",\
                legend: {display: false},\
                animation: {\
            duration: 0,\
        },\
        hover: {\
            animationDuration: 0,\
        },\
        responsiveAnimationDuration: 0,\
    }\
});\
```

And looks like this:

![grafik](https://user-images.githubusercontent.com/17402664/40012407-dc53bd1c-57aa-11e8-9076-29be73b5468b.png)

I also think that SNRlen and BitsLen should always be equal, so the whole 'backgroundColor' array could be removed if you make that change and correct the duplication band error.

**Comment by Ansuel** [comment]
you have 35b right?

**Comment by Ansuel** [comment]
can you paste here 

xdslctl info --pbParams

**Comment by meyergru** [comment]
```
xdslctl: ADSL driver and PHY status
Status: Showtime
Last Retrain Reason:    0
Last initialization procedure status:   0
Max:    Upstream rate = 40631 Kbps, Downstream rate = 132532 Kbps
Bearer: 0, Upstream rate = 40631 Kbps, Downstream rate = 109342 Kbps
Bearer: 1, Upstream rate = 0 Kbps, Downstream rate = 0 Kbps
Discovery Phase (Initial) Band Plan
US: (28,60) (871,1205) (1972,2771)
DS: (65,859) (1216,1961) (2793,3943)
Medley Phase (Final) Band Plan
US: (28,60) (871,1205) (1972,2771)
DS: (65,859) (1216,1961) (2793,3943)
VDSL Port Details               Upstream                Downstream
Attainable Net Data Rate:        40631 kbps             132532 kbps
Actual Aggregate Tx Power:      -   0.2 dBm                12.7 dBm
====================================================================================
VDSL Band Status        U0      U1      U2      U3      U4      D1      D2      D3
  Line Attenuation(dB):  3.0     12.9    19.9     N/A     N/A    8.6     17.9    27.7
Signal Attenuation(dB):  3.0     12.5    18.9     N/A     N/A    9.6     17.7    27.7
        SNR Margin(dB):  9.2     9.3     9.3      N/A     N/A    13.2    12.2    12.1
        TX Power(dBm):  -10.1   -2.0    -6.5      N/A     N/A    8.8     7.6     7.1
        kl0(dBx100):    180     180       N/A     N/A     N/A   673     681     719
```

**Comment by meyergru** [comment]
Nope. The Bits bins should end at ~4000 (that graph is from a similar connection with a Fritzbox):

![grafik](https://user-images.githubusercontent.com/17402664/40013459-dfa7f106-57ad-11e8-9e75-be134838e8d6.png)

**Comment by Ansuel** [comment]
anyway i don't really like the blue background... we should find a way to color it..

**Comment by meyergru** [comment]
You can do it, but not with truncation. If you use "backgroundColor: pointBackgroundColor", the result is broken at this time. I think this is because of different lengths of arrays.

**Comment by Ansuel** [comment]
notice the same thing...  actually, i should find a way to split all the graph

**Comment by meyergru** [comment]
I think the sheer amount of samples is what limits the bar chart type?

**Comment by Ansuel** [comment]
try this version and tell me what you see

**Comment by meyergru** [comment]
Oh, I have another idea: If you separate the dataset into upstream and downstream, you could overlay them and use one coloring for each set!!! That way, you would need no color attributes per data point, but only per set!

**Comment by Ansuel** [comment]
yhea could work... but i can't find a way to show the data one after another.... (as i don't really like to fill the start of the data of Nan) 

i think that this is the only way... 

create 2 dataset... gonna be a lot of code to create the right dataset :(  but is doable

**Comment by meyergru** [comment]
7.14.2: Still truncated / duplicated values and white background below Bits graph, but sometimes switches to transparent when cursor moves.

**Comment by Ansuel** [comment]
ok now we have 2 datasets one fro us band and one for ds

**Comment by Ansuel** [comment]
nope

**Comment by Ansuel** [comment]
if it works well you will love this... 

hope for the best now it on the repo ;)

**Comment by meyergru** [comment]
Nice, even the "DSL disconnected" bug is gone!

Two problems remain:

1. Still the wraparound / duplicate values at #2983:
![grafik](https://user-images.githubusercontent.com/17402664/40017563-07eb2ac8-57ba-11e8-92fe-4ec892de7f5f.png)

2. A little slow (neglegible).

**Comment by Ansuel** [comment]
transformer-cli get rpc.xdslctl.Us1BandFinal

transformer-cli get rpc.xdslctl.Us3BandFinal

transformer-cli get rpc.xdslctl.Ds3BandFinal

**Comment by meyergru** [comment]
I'd say they are as expected:

```
# xdslctl info --pbParams
xdslctl: ADSL driver and PHY status
Status: Showtime
Last Retrain Reason:    0
Last initialization procedure status:   0
Max:    Upstream rate = 40631 Kbps, Downstream rate = 131144 Kbps
Bearer: 0, Upstream rate = 40631 Kbps, Downstream rate = 109342 Kbps
Bearer: 1, Upstream rate = 0 Kbps, Downstream rate = 0 Kbps
Discovery Phase (Initial) Band Plan
US: (28,60) (871,1205) (1972,2771)
DS: (65,859) (1216,1961) (2793,3943)
Medley Phase (Final) Band Plan
US: (28,60) (871,1205) (1972,2771)
DS: (65,859) (1216,1961) (2793,3943)
VDSL Port Details               Upstream                Downstream
Attainable Net Data Rate:        40631 kbps             131144 kbps
Actual Aggregate Tx Power:      -   0.2 dBm                12.8 dBm
====================================================================================
VDSL Band Status        U0      U1      U2      U3      U4      D1      D2      D3
  Line Attenuation(dB):  3.0     12.9    19.9     N/A     N/A    8.6     17.9    27.7
Signal Attenuation(dB):  3.0     12.5    19.0     N/A     N/A    9.6     17.7    27.7
        SNR Margin(dB):  9.2     9.2     9.3      N/A     N/A    13.1    11.5    11.7
        TX Power(dBm):  -10.1   -2.0    -6.5      N/A     N/A    8.8     7.6     7.1
        kl0(dBx100):    180     180       N/A     N/A     N/A   673     681     719
# transformer-cli get rpc.xdslctl.Us1BandFinal
rpc.xdslctl.Us1BandFinal [string] = 60
# transformer-cli get rpc.xdslctl.Us3BandFinal
rpc.xdslctl.Us3BandFinal [string] = 2771
# transformer-cli get rpc.xdslctl.Ds3BandFinal
rpc.xdslctl.Ds3BandFinal [string] = 3943
```

**Comment by Ansuel** [comment]
transformer-cli get rpc.xdslctl.HlogDs4
transformer-cli get rpc.xdslctl.HlogUs4

this?

**Comment by meyergru** [comment]
```
#transformer-cli get rpc.xdslctl.HlogDs4
rpc.xdslctl.HlogDs4 [string] =
#transformer-cli get rpc.xdslctl.HlogUs4
rpc.xdslctl.HlogUs4 [string] =
```

Both empty

**Comment by meyergru** [comment]
Does this help?

```
# transformer-cli get rpc.xdslctl.HlogUs1 | tr -cd ',' | wc -c
61
root@napoli:~# transformer-cli get rpc.xdslctl.HlogUs2 | tr -cd ',' | wc -c
346
root@napoli:~# transformer-cli get rpc.xdslctl.HlogUs3 | tr -cd ',' | wc -c
810
root@napoli:~# transformer-cli get rpc.xdslctl.HlogDs1 | tr -cd ',' | wc -c
799
root@napoli:~# transformer-cli get rpc.xdslctl.HlogDs2 | tr -cd ',' | wc -c
756
root@napoli:~# transformer-cli get rpc.xdslctl.HlogDs3 | tr -cd ',' | wc -c
3943
```

I think the last one is strange?

**Comment by Ansuel** [comment]
O_O wtf !

**Comment by Ansuel** [comment]
transformer-cli get rpc.xdslctl.Ds3BandInitial ?

**Comment by meyergru** [comment]
#transformer-cli get rpc.xdslctl.Ds3BandInitial
rpc.xdslctl.Ds3BandInitial [string] = 2793
#transformer-cli get rpc.xdslctl.Ds3BandFinal
rpc.xdslctl.Ds3BandFinal [string] = 3943

**Comment by Ansuel** [comment]
OWWW OK I KNOW THE PROBLEM!

**Comment by Ansuel** [comment]
now should be good

**Comment by meyergru** [comment]
logread error:

```
Mon May 14 22:03:40 2018 daemon.err nginx: 2018/05/14 22:03:40 [error] 20453#0: *6 lua entry thread aborted: runtime error: [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:86: unexpected symbol near 'then'
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/lib/lua/web/lp.lua:77: in function 'compile'
        /usr/lib/lua/web/lp.lua:153: in function 'load'
        /usr/lib/lua/web/web.lua:203: in function 'getContentRenderer'
        /usr/lib/lua/web/web.lua:240: in function 'process'
        content_by_lua(nginx.conf
```

**Comment by Ansuel** [comment]
my bad fixed

**Comment by meyergru** [comment]
If it was the superfluous "and" in line 86, then it is fixed...

**Comment by Ansuel** [comment]
yes it was that ahhaha

**Comment by meyergru** [comment]
A huge step forward for mankind:

![grafik](https://user-images.githubusercontent.com/17402664/40020815-5ce47c74-57c3-11e8-8040-693e0cd5221b.png)

**Comment by Ansuel** [comment]
now pls check if it's the same of the one provided from dslstats or other graph

**Comment by meyergru** [comment]
Awesome, Ansuel! Good night...

**Comment by meyergru** [comment]
The "BandPlaCondition" part is obsolete.

**Comment by Ansuel** [comment]
??? explain pls

**Comment by Ansuel** [comment]
notice that... :) now i will try to move the generation of the graph from lua to javascript

**Comment by meyergru** [comment]
Do you think that is faster? Probably, because then you have a desktop CPU...

One thing is also that there are 32 rpcs, each of which has a turnaround overhead. When I do this, you can see it:

```
# time transformer-cli get rpc.xdslctl.HlogDs3 >/dev/null
real    0m 0.17s
user    0m 0.02s
sys     0m 0.01s
```

There is only 0.03s CPU time, but 0.17s in order to get the data via rpc.

If you decompose the bands in Javascript, there would only be 5 rpcs(one to get the band limits and 4 for each data series).

**Comment by Ansuel** [comment]
at least with javascript i can generate the datasets after all the rpc data loads (and also the page) with settimeout

but you are right... we should find a way to speed up also that...  would be good to underestand what is the real slowdown in the process...  (and i think is the compilation of the lua page)

**Comment by meyergru** [comment]
In that case, it would also be good to combine the data at the topmost Javascript level in order to save the raw number of Lua calls (either by Javascript callbacks to Lua or by Lua calling rpcs, which are Lua again.

I saw that you snip off the header lines of the "xdslctl info" via "sed -n"  in the rpc code. That implies one more process fork per call. It would be better to do this by language means (i.e. skip n lines after file opening).

**Comment by Ansuel** [comment]
ummm made some changes, any idea to optimize it even more, just tell me ?

**Comment by meyergru** [comment]
It is now at ~8s instead of ~10s. I think you could only shave off another 4 seconds by actually calling each graph rpc only once instead of 8 times. As I said, each call is ~0.17s in the backend.

You would have to do the band separation all in the frontend in Javascript.

**Comment by Ansuel** [comment]
umm also i found another slow down... 

i call the same data over and over again... like 30 times... could be that the problem.

**Comment by meyergru** [comment]
That is what I said. 8 bands * 4 graphs data = 32 calls * 0.17s = 5s. If you do it only 4 times and separate the band in Javascript, you should save ~4s.

**Comment by Ansuel** [comment]
ummm not talking about that... but about us and bs band for the for cicle

**Comment by meyergru** [comment]
Yes, I know. That is what I meant. 8 times for all bands times 4 different graphs.

**Comment by Ansuel** [comment]
try this version any improvement?

**Comment by Ansuel** [comment]
try this

**Comment by meyergru** [comment]
3.2s!

**Comment by Ansuel** [comment]
make more test pls... this result it's too strange

**Comment by meyergru** [comment]
3287ms when clicking on dianostics-xdsl-graphics-modal.lp. Around 6s until it's displayed.

**Comment by Ansuel** [comment]
see changes, i was requsting the same thing every time like an idiot...

**Comment by meyergru** [comment]
Subjectively, it is fast enough now. It is a diagnostic function after all - no need to animate it ;-)

**Comment by Ansuel** [comment]
only problem is underestand why is offset of 3-4 value...

**Comment by meyergru** [comment]
I have seen the code but did not understand it. I know, though, that it fixes the wraparound/cutoff problem at 2800.

**Comment by nclmrc** [comment]
Anche io ho quest'errore
![screenshot_20180516-235743](https://user-images.githubusercontent.com/38593316/40146430-bdccd31c-5965-11e8-81e3-cbfc17a42dab.png)

**Comment by meyergru** [comment]
Yup, I did not try with DSL connection yet. logread shows:

```
Thu May 17 00:06:11 2018 daemon.err transformer[29861]: [truncated] getter(rpc.xdslctl., Ds1ScannedBand) threw an error: /usr/share/transformer/mappings/rpc/xdslctl.map:301: attempt to index local 's' (a nil value)
stack traceback:
        /usr/share/transformer/mappings/rpc/xdslctl.map:301: in function 'xdslband'
        /usr/share/transformer/mappings/rpc/xdslctl.map:328: in function </usr/share/transformer/mappings/rpc/xdslctl.map:323>
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/lib/lua/transformer/navigation.luThu May 17 00:06:11 2018 daemon.err nginx: 2018/05/17 00:06:11 [error] 29851#0: *13 lua entry thread aborted: runtime error: [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:12: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "/modals/diagnostics-xdsl-graphics-modal.lp"]:12: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: 192.168.10.97, server: localhost, request: "Thu May 17 00:06:13 2018 daemon.notice wansensing: (L2Sense) runs L2Main.check(timeout)
```

**Comment by Ansuel** [comment]
? explain better

**Comment by meyergru** [comment]
The same error as initially: When DSL is not connected, the error above is shown on the GUI. Reason being that now you use a string to hold the parsed line for the band limits. And this is NULL with no connection, giving that logread error.

This is an error introduced by the refactorings for speed.

**Comment by Ansuel** [comment]
actually the error is about another thing 
try this version

**Comment by meyergru** [comment]
7.14.35 worked fine, so we can close this now.
