### ISSUE TITLE
Impossibile accedere al changelog

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#510]
Device Model: TIM HUB DGA-4132
Firmware 2.0.0
Gui Version: 8.12.91

Descrizione del problema :

Nel link in basso dove c'e' il link nel numero versione della Gui, non si ha più l'elenco storico del **changelog**, ma gira a vuoto all'infinito.

P.S. :  Quando era accessibile, ultimamente riportava la stessa versione di Gui per gli ultimi 2 gruppi di aggiornamenti (  8.10 mi sembra )

**Comment by FrancYescO** [comment]
fixed in https://github.com/Ansuel/tch-nginx-gui/commit/5a1344492383f5348f5fa8bac43649dabc0ec578
