### ISSUE TITLE
Scripts English Optimisation

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#511]
It is most likely a good idea to optimise the English in rootdevice.
Will have to do it in one night as rootdevice is updated very frequently

**Comment by FrancYescO** [comment]
i'll wait for a PR, don't need to take an open issue :)

**Comment by kevdagoat** [comment]
Just alerting

**Comment by FrancYescO** [comment]
ps. if you can take a look at all the new strings in gateway/modgui/extra modals, probably the english needs to be a little redefined

**Comment by FrancYescO** [comment]
take in mind that also when conflicts happens when are strings it's very easy to fix

**Comment by kevdagoat** [comment]
Ok will do that to

**Comment by kevdagoat** [comment]
Where is that located??
