### ISSUE TITLE
Skin e Traduzione

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#512]
![cattura](https://user-images.githubusercontent.com/44716486/53293079-80308e80-37cd-11e9-9dcb-ba4e50038d86.PNG)
1) Check Complete va tradotto
2) come mai quella barra che ho sottolineato ora si trova più a sinistra invece di stare tutta a destra come prima? @Ansuel @bovirus @FrancYescO

**Comment by putipower** [comment]
@bovirus se passo il puntatore del mouse sul pulsante aggiorna che compare quando c'è un aggiornamento il testo che compare è in inglese

**Comment by bovirus** [comment]
@putipower 
Che stringa di testo compare in inglese?

**Comment by putipower** [comment]
ora non la vedo piu ma c'era la spiegazione su come fare ad aggiornare.

**Comment by bovirus** [comment]
Probabilmente la stringa (che ho dientifiocato) dovrebbe essere

"Go to the gateway tab and click on the Update button, to autoupgrade to the new GUI."

L'ho aggiunta per la prossima build.

**Comment by Ghost9090** [comment]
@bovirus puoi sistemare tu la posizione della barra che ho sottolineato visto che nessuno lo risolve?

**Comment by Ansuel** [comment]
nessuno...................

**Comment by bovirus** [comment]
@Ghost9090 

Ansuel se ne sta occupando....

**Comment by Ansuel** [comment]
@bovirus in realtà sto lavorando allo script per automatizzare le traduzioni... penso che entro oggi riesco a rilasciare... mi manca solo pulizia del po ed ho finito

riguardo la barra si fixa in un attimo quindi non disperiamoci pls

**Comment by putipower** [comment]
https://ibb.co/TBJZdrf a me sembra ordinata

**Comment by Ansuel** [comment]
probabilmente è un problema solo con gli schermi ENORMI

**Comment by Ghost9090** [comment]
@putipower con il portatile sembra.. ma non con un pc fisso.

**Comment by putipower** [comment]
pc inchiodato altro che fisso.schermo lcd 17'

**Comment by Ghost9090** [comment]
@putipower il mio è da 27
