### ISSUE TITLE
Eco settings are reset on every GUI upgrade

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#52]
Every time I install a new GUI version, the eco settings on the Gateway tab are reset (e.g. Ethernet EEE is off afterwards).

**Comment by Ansuel** [comment]
yes some option cause increase of ms... if you want i can include an option to disable this check

**Comment by meyergru** [comment]
Which check? I don't understand what you mean by "increase of ms"?

I would assume that these settings are in some kind of /etc/config/* file and that some of these settings are set to default by the upgrade process?

**Comment by Ansuel** [comment]
ummm we found out that these 3 option gives extra lag 

in the rootdevice script i set them to off

**Comment by meyergru** [comment]
Ah, I see. No, if it is for a good reason that you reset it, then fine...

**Comment by meyergru** [comment]
But I thought that the processor "auto" setting caused lag? That setting is chosen, though.

And Ethernet EEE should not cause this? It is just that for shorter connections, there is less power applied to the ethernet cabling?

That is, logically, exactly these chosen defaults should cause even greater lag?

**Comment by meyergru** [comment]
Bump? Am I right? Are the defaults optimized like so?

**Comment by Escart94** [comment]
Defaults settings are optimized like that.
Tell us If we can close the issue.

**Comment by meyergru** [comment]
O.K., then.

**Comment by Kherby** [comment]
So Optimized Default settings are everything set to OFF but CPU Wait ON and CPU Speed = Auto ?

**Comment by Escart94** [comment]
You're right.
I'm going to close the issue.
