### ISSUE TITLE
nginx restart 

### ISSUE THREAD

**Issue by towatai** [Ansuel/tch-nginx-gui#522]
Device Model: DGA4132
FW Version: 2.0.0
Gui Version: 8.13.5

since the 8.13.4 version i always have to restart the nginx process manually after the gui-update. otherwise i get an error as soon as i want to access the gui via my browser.
the error occurred after the update to 8.13.4 as well as after the update to 8.13.5

**Comment by Ansuel** [comment]
What?

Il Lun 25 Feb 2019, 11:38 towatai <notifications@github.com> ha scritto:

**Comment by towatai** [comment]
sorry, i clicked the button to create the post too fast. update is already there

**Comment by Ansuel** [comment]
8.13 ???
How do you update the gui?

**Comment by Ansuel** [comment]
Can you tell me the error?
403 or 503?

**Comment by towatai** [comment]
Using the Update button in the GUI Settings menu. Error was 503 IF I remember correctly.  Unfortunately I forgot to make a screenshot.

**Comment by kevdagoat** [comment]
Will most likely need to add:
`/etc/init.d/nginx restart` (or reload) into https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/usr/share/transformer/scripts/upgradegui

**Comment by FrancYescO** [comment]
@kevdagoat there is already tha rootdevice script that take care about it, but something is not working as it should..

**Comment by kevdagoat** [comment]
Ok. Will have a look tomorrow

**Comment by FrancYescO** [comment]
we are managing this issue in https://github.com/Ansuel/tch-nginx-gui/issues/494
