### ISSUE TITLE
Telephony Info status

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#523]
Inside stats page, under "Telephony Info".
Status description and translation is pretty weird and misleading:
in english there is: 

Status: registered
Line State: Idle

in italian we have:

Stato: Registrato
Stato linea: Non attivo

I would suggest to fix translations and tags using:

Line status: registered
Call status: idle

Stato linea: Registrato
Stato chiamata: inattivo 

Then, as enhancement request, it would be great to show the phone number while in call.

**Comment by kevdagoat** [comment]
Ok then, will fix the first part
