### ISSUE TITLE
Complete support for TG789vac Xtream 35B

### ISSUE THREAD

**Issue by matteone2** [Ansuel/tch-nginx-gui#529]
Product: vbnt-f_fastweb_r16-2-a
Release: Jade (16.2)
Version: 16.2.7825-3401001-20170627171140-bca18a9e967f024980744d0bdc5476712638e931
( 16.2.7825-3401002-20170627172939_FW_212_MOS_TG789vacXtream )
versione GUI:  DEV 8.13.4

Ciao,
ho fatto un po' di prove con la GUI dev installata sul TG789vac Xtream 35B di Fastweb, aprendo le card una per una ed annotando eventuali problemi di visualizzazione o errori segnalati nel log. di seguito il riepilogo.

"Statistiche" 
nessun errore nei log

"Gateway"
nessun errore nei log

"Impostazioni GUI"
nessun errore nei log

"Banda Larga"
nessun errore nei log

"Accesso Interner"
nessun errore nei log

"Wireless"
Impiega un sacco di tempo a caricare e poi appare incompleta. Nei log ho questo

nginx [error] 5807#0: *19 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #7 to 'format' (string expected, got no value)
stack traceback:
coroutine 0:
        [C]: in function 'format'
        /usr/lib/lua/web/taint.lua:280: in function 'format'
        /usr/lib/lua/web/ui_helper.lua:685: in function '?'
        [string "/modals/wireless-modal.lp"]:1070: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 10.89.89.153, server: localhost, request: "GET /modals/wireless-modal.lp HTTP/1.1", host: "10.89.89.7", referrer: "http://10.89.89.7/cards.lp"

"Rete locale"
Non riesce a caricare la pagina. Nei log ho questo

[truncated] getter(rpc.network.interface.@., ifname) threw an error: /usr/lib/lua/transformer/mapper/nwcommon.lua:471: attempt to index local 'ubusStatus' (a nil value)
stack traceback:     
        /usr/lib/lua/transformer/mapper/nwcommon.lua:471: in function </usr/lib/lua/transformer/mapper/nwcommon.lua:469>   (tail call): ?  
        [C]: in function 'xpcall'       
        /usr/lib/lua/transformer/navigation.lua:157: in function 'get_parameter_value'     
        /usr/lib/lua/transformer/navigation.lua:195: in function 'get'     
        /usr/lib/lua/transformer/api.lua:104: in function </usr/lib/lua/transformer/api.lua:101>  [C]: in function 'pcall'         
        /usr/lib/lua/transformer/api.lua:24: in function 'do_pcall'     
        /usr/lib/lua/transformer/api.lua:77: in function </usr/lib/lua/transformer/api.lua:75>     (tail call): ?  
        /usr/bin/transformer:126: in function '?'  /usr/bin/transformer:370: in function </usr/bin/transformer:354>        
        [C]: in function 'pcall'   /usr/bin/transformer:393: in function </usr/bin/transformer:376>        
        [C]: in function 'r

nginx [error] 5807#0: *26 lua entry thread aborted: runtime error: [string "/modals/ethernet-modal.lp"]:676: bad argument #1 to 'band' (number expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'band'
        [string "/modals/ethernet-modal.lp"]:676: in function 'calculateDHCPStartAddress'
        [string "/modals/ethernet-modal.lp"]:1129: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 10.89.89.153, server: localhost, request: "GET /modals/ethernet-modal.lp HTTP/1.1", host: "10.89.89.7", referrer: "http://10.89.89.7/cards.lp"

"Dispositivi"
nessun errore nei log

"Servizi WAN"
nessun errore nei log, ma nella pagina appare un warning:

Exact data not found in this paths:
Key ddns_password : uci.ddns.service.@myddns_ipv4.password

"Firewall"
nessun errore nei log

"QOS"
nessun errore nei log

"Telefonia"
nessun errore nei log, a meno di selezionare "servizio" in tal caso segnala
"si è verificato un errore interno del server". nei log ho questo

nginx [error] 5807#0: *29 lua entry thread aborted: runtime error: [string "/modals/mmpbx-service-modal.lp"]:586: attempt to index local 'tableFirstRow' (a nil value)
stack traceback:
coroutine 0:
        [string "/modals/mmpbx-service-modal.lp"]:586: in function 'addTableHeader'
        [string "/modals/mmpbx-service-modal.lp"]:718: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 10.89.89.153, server: localhost, request: "GET /modals/mmpbx-service-modal.lp HTTP/1.1", host: "10.89.89.7", referrer: "http://10.89.89.7/cards.lp"

Da tenere presente che questo router ha un firmware "MOS" quindi in teoria la parte VoIP potrebbe essere stata disattivata da Fastweb

"Diagnostica"
nessun errore nei log

"Estensioni"
nessun errore nei log, ma temo che Luci, Amule, Transmission ed Aria2 abbiano problemi
a funzionare data la necessità di specifihe opzioni di compilazione (vedi Thread della compilazione OpenWrt
su ilpuntotecnico). Inoltre lo spazio in overlay è veramente poco.

"Assistenza remota"
nessun errore nei log

"Mobile"
nessun errore nei log

"Mobile 3G/4G" 
forse va tolta, potrebbe essere legata alla card precedente ?

"Gestione modem"
Non riesce a caricare la pagina. Nei log ho questo

nginx [error] 5807#0: *39 lua entry thread aborted: runtime error: [string "/modals/usermgr-modal.lp"]:39: attempt to concatenate field 'legacy_salt' (a nil value)
stack traceback:
coroutine 0:
        [string "/modals/usermgr-modal.lp"]:39: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 10.89.89.153, server: localhost, request: "GET /modals/usermgr-modal.lp HTTP/1.1", host: "10.89.89.7", referrer: "http://10.89.89.7/cards.lp"

"Condivisione contenuti"
nessun errore nei log

"Condivisione stampante"
nessun errore nei log

"Controllo genitori"
nessun errore nei log

"IP Extra"
nessun errore nei log

"Pianificazione"
nessun errore nei log

"Impostazioni relay"
nessun errore nei log

"Impostazioni Eco"
nessun errore nei log

"Telegestione CWMP" 
Non riesce a caricare la pagina. Nei log ho questo

[truncated] getter(rpc.network.interface.@., ifname) threw an error: /usr/lib/lua/transformer/mapper/nwcommon.lua:471: attempt to index local 'ubusStatus' (a nil value)
stack traceback:     
        /usr/lib/lua/transformer/mapper/nwcommon.lua:471: in function </usr/lib/lua/transformer/mapper/nwcommon.lua:469>   (tail call): ?  
        [C]: in function 'xpcall'       
        /usr/lib/lua/transformer/navigation.lua:157: in function 'get_parameter_value'     
        /usr/lib/lua/transformer/navigation.lua:195: in function 'get'     
        /usr/lib/lua/transformer/api.lua:104: in function </usr/lib/lua/transformer/api.lua:101>  [C]: in function 'pcall'         
        /usr/lib/lua/transformer/api.lua:24: in function 'do_pcall'     
        /usr/lib/lua/transformer/api.lua:77: in function </usr/lib/lua/transformer/api.lua:75>     (tail call): ?  
        /usr/bin/transformer:126: in function '?'  /usr/bin/transformer:370: in function </usr/bin/transformer:354>        
        [C]: in function 'pcall'   /usr/bin/transformer:393: in function </usr/bin/transformer:376>        
        [C]: in function 'r

nginx [error] 8773#0: *21 lua entry thread aborted: runtime error: [string "/modals/cwmpconf-modal.lp"]:90: attempt to index a nil value
stack traceback:
coroutine 0:
        [string "/modals/cwmpconf-modal.lp"]:90: in function 'content'
        /usr/lib/lua/web/web.lua:249: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 10.89.89.153, server: localhost, request: "GET /modals/cwmpconf-modal.lp HTTP/1.1", host: "10.89.89.7", referrer: "http://10.89.89.7/cards.lp"

"Funzioni Extra di sistema"
nessun errore nei log

"Helper NAT"
nessun errore nei log

"Configurazione xDSL"
nessun errore nei log

**Comment by zi0Black** [comment]
Aggiungo qui per non aprire un'altra Issuee!

Gui Version: 8.13.92 (beta/dev)
Firmware: 16.2.7825-3401002-20170627172939_FW_212_MOS_TG789vacXtream

I get the following errors in the GUI:

```
Exact data not found in this paths: 
Key radius_account_secret : uci.wireless.wifi-radius-server.@ap0_acct0.secret
Key wep_key : rpc.wireless.ap.@ap0.security.wep_key
Key wpa_psk : rpc.wireless.ap.@ap0.security.wpa_psk_passphrase
Key radius_authent_secret : uci.wireless.wifi-radius-server.@ap0_auth0.secret
Key wps_enabled : rpc.wireless.ap.@ap0.wps.admin_state
Key bspeer_wpa_psk_key : uci.wireless.wifi-ap.@ap1.wpa_psk_key
Key security : rpc.wireless.ap.@ap0.security.mode
Key ddns_password : uci.ddns.service.@myddns_ipv4.password
```

"/modals/usermgr-modal.lp" card give **500**:

```
2019/03/13 18:19:47 [error] 4845#0: *120 lua entry thread aborted: runtime error: [string "/modals/usermgr-modal.lp"]:39: attempt to concatenate field 'legacy_salt' (a nil value)
stack traceback:
coroutine 0:
        [string "/modals/usermgr-modal.lp"]:39: in function 'content'
        /usr/lib/lua/web/web.lua:264: in function 'process'
        content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 192.168.1.70, server: localhost, request: "GET /modals/usermgr-modal.lp HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/cards.lp"
```

**Comment by matteone2** [comment]
Gli errori "exact data not found" li ho avuti anch'io la prima volta che ho installato la GUI, poi mi è rimasto solo "Key ddns_password : uci.ddns.service.@myddns_ipv4.password" , gli altri mi sono spariti ma non so  dire perchè

**Comment by kevdagoat** [comment]
Looks like the legacy_salt parameter in the config is not set

**Comment by zi0Black** [comment]
> Gli errori "exact data not found" li ho avuti anch'io la prima volta che ho installato la GUI, poi mi è rimasto solo "Key ddns_password : [uci.ddns.service.@myddns_ipv4.password](mailto:uci.ddns.service.@myddns_ipv4.password)" , gli altri mi sono spariti ma non so dire perchè

Voglio provare a rifare il flash e vedere se risolve! (Ti ricordi come si fa lo swich del banco di memoria attivo?)

**Comment by matteone2** [comment]
c'è il comando switchover, oppure se vuoi avere pieno controllo di quello che succede fai un 
echo bank_X > /proc/banktable/active 
(dove X è 1 o 2 a seconda del banco desiderato), seguito da reboot

PS:
occhio che la GUI non abbia abilitato il "force bank 1"

**Comment by zi0Black** [comment]
Dove vedo se c'è abilitato "force bank 1"?

**Comment by matteone2** [comment]
Nella card "Sytem Extras" ,  switch "Bank Check" . Lì c'è anche il pulsante per fare switchover.  PS: Per questo genere di problematiche conviene aprire thread sul forum ilpuntotecnico.com e laciare qui su github la sola segnalazione bug.

**Comment by viaggio32** [comment]
In Accesso internet non è possibile configurare la connessione come PPPoE routed
Nella GUI
Exact data not found in this paths: 
Key uci_wan_password : uci.network.interface.@wan.password

Da logread: https://pastebin.com/enHLqVkg

Inoltre non funzionano le statistiche PPP: Exact path not found!

**Comment by Fabi0Z** [comment]
Confermo gli errori per la scheda riguardante il WiFi

**Comment by FrancYescO** [comment]
qualcuno riesce a fare lo stesso report come primo commento di questa issue (modal aperte con relativo errore nei log se esce) possibilmente con ultimo fw [16.2.8706_FW_214_IAD_TG789vacXtream.rbi](https://anonfile.com/VeWeof2fn5/16.2.8706_FW_214_IAD_TG789vacXtream_rbi) (che sembra essere quello che da meno problemi) e ultima gui dev

**Comment by viaggio32** [comment]
Ultima gui dev e ultimo firmware:

Scheda "Modem"
Tutto ok, nessun errore nei log

Scheda "Gui"
Tutto ok, nessun errore nei log

Scheda "Banda Larga"
Tutto ok, il log si popola solo in caso di switch tra i tipi di connessione, nessun errore.

Scheda "Accesso Internet"
Impossibile impostare il tipo di connessione PPPoE Routed (errore nella GUI Exact data not found in this paths: Key uci_wan_password : uci.network.interface.@wan.password), log: https://pastebin.com/hteAy7UQ

Scheda "WiFi"
Non si apre, log: https://pastebin.com/LkjVq2Qz (Potrebbe non essere corretto, fatemi sapere come rifarlo)

Scheda "Rete locale"
Tutto ok, nessun errore nei log

Scheda "Dispositivi"
Tutto ok, nessun errore nei log

Scheda "Servizi WAN"
Tutto ok, nessun errore nei log

Scheda "Firewall"
Tutto ok, nessun errore nei log

Scheda "QOS"
Tutto ok, nessun errore nei log

Scheda "Telefonia"
Tutto ok, nessun errore nei log. Non ho provato ad aggiungere un account

Scheda "Diagnostica"
Tutto ok, nessun errore nei log

**Comment by FrancYescO** [comment]
puoi postare il risultato di questo comando
`transformer-cli get uci.network.interface.@wan.password`
se da not found, esegui `uci set network.wan.password='password'` e prova a ridarlo, se ancora not found, esegui `uci commit network` e vedi se va insieme alla modal per il pppoe

servirebbe poi il risultato di `transformer-cli get rpc.wireless.` (se vuoi censura password wifi o mac..)

e il log una decina di secondi dopo aver dato `/etc/init.d/transformer restart`

**Comment by viaggio32** [comment]
`transformer-cli get uci.network.interface.@wan.password` da
`ERROR   invalid exact path uci.network.interface.@wan.password`, anche dopo aver eseguito `uci set network.wan.password='password'` e `uci commit network`. Elenco dei comandi: https://pastebin.com/89cKCwwP
L'errore rimane anche da GUI.

Log di `transformer-cli get rpc.wireless.`: https://pastebin.com/9d98tQme
Log dopo `/etc/init.d/transformer restart`: https://pastebin.com/pCk05dMQ

Spero ci sia tutto

**Comment by FrancYescO** [comment]
controlla la situazione ora..

**Comment by viaggio32** [comment]
Prima cosa che ho notato: ora compare l'immagine del router!

Scheda "Accesso  internet": Stesso errore `Exact data not found in this paths: Key uci_wan_password : uci.network.interface.@wan.password` log: https://pastebin.com/aZfkEhGw

Scheda "WiFi": Ora si apre e vengono visualizzate diverse informazioni; manca tutta la parte relativa alla radio 5G (che anche secondo i LED è spenta, forse si può accendere da shell?) e ci sono alcuni errori mostrati nella GUI: https://snipboard.io/CVKnr9.jpg
Non funziona la pagina di pianificazione, log: https://pastebin.com/JsqmbxP9

Comunque un grande passo avanti, grazie!

**Comment by FrancYescO** [comment]
Postami sempre il log dopo  /etc/init.d/transformer restart 

Il wifi 5ghz oltre allo stato dei led sei sicuro sia realmente spento?

**Comment by viaggio32** [comment]
Log dopo il restart: https://pastebin.com/AJuqtqbf

Confermo, il wifi 5ghz è realmente spento

**Comment by FrancYescO** [comment]
metti (sostituisci) questo file https://raw.githubusercontent.com/FrancYescO/tch_firmware_extracted/AGTHP_1.1.2/usr/lib/lua/transformer/typecheck.lua 
in `/usr/lib/lua/transformer/typecheck.lua` 
se il modem e' connesso dovrebbe bastare `curl -k https://raw.githubusercontent.com/FrancYescO/tch_firmware_extracted/AGTHP_1.1.2/usr/lib/lua/transformer/typecheck.lua --output /usr/lib/lua/transformer/typecheck.lua`

dopodiche' dai `/etc/init.d/transformer restart` e dimmi se compaiono gli stessi errori nella pagina wifi o internet

**Comment by viaggio32** [comment]
Tutto uguale, ti lascio il log dopo il restart: https://pastebin.com/Ejbb2HbC
Ho provato anche a riavviare il router, stessi errori

**Comment by FrancYescO** [comment]
stessa prova anche con questo file https://raw.githubusercontent.com/FrancYescO/tch_firmware_extracted/AGTHP_1.1.2/usr/lib/lua/transformer/mapper/uci_1to1.lua
in
`/usr/lib/lua/transformer/mapper/uci_1to1.lua`

**Comment by viaggio32** [comment]
Dopo aver caricato il nuovo file non mi si apre più la scheda accesso internet, log: https://pastebin.com/HQgxT2Ag

Dopo un riavvio non mi si carica più la gui: `Error 500 : INTERNAL_SERVER_ERROR`
log: https://pastebin.com/tHxhy8xR

**Comment by FrancYescO** [comment]
prova a rimpiazzare tutta la cartella https://github.com/FrancYescO/tch_firmware_extracted/archive/AGTHP_1.1.2.zip

prendi tutta `/usr/lib/lua/transformer` e mettila sul modem nella stessa posizione
