### ISSUE TITLE
Security topic: Someone is listening...

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#53]
When you start up the device under the following conditions:

1. not connected to DSL
2. disabled DHCP
3. static IP and route to the "real" router

there will be another IP allocated in your network via DHCP under the name of ModemTIM-XXXXXX. It reacts to PINGs and has a MAC that is 3 higher than the MAC of br-lan (so obviously, this belongs to the device somehow).

There is an open TCP port of 49152, which is UPNP. 

Neither the IP nor the MAC nor the port is present under the OpwenWRT Linux. It seems like there is a separate TCP stack active, probably the DSL CPE chip. I have seen such designs, where you can actually telnet into the CPE and issue commands. However, it should never allocate an IP from the LAN, should it?

Is that only a glitch when there is no DHCP on the device itself or is that IP visible all the time? I cannot check this, as I cannot use the device as a router.

**Comment by Ansuel** [comment]
it's just the quantenna chip that comunicate with eth5 

it's a shitty implementation... the 5ghz wifi is a complete separate system with own uboot and gets ip address and all that things.

**Comment by meyergru** [comment]
O.K., understood. Not an issue of the GUI and I guess we can do nothing much about it, although it is a probable security issue: Perhaps one could control the 5 GHz WLAN by this from the LAN side.

**Comment by meyergru** [comment]
I just read a tip regarding this: remove eth5 from the lan bridge and the problem is gone:

In /etc/config/network:

```
config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '64'
        option force_link '0'
        option ipv6 '0'
        option ifname 'eth0 eth1 eth2 eth3 **eth5**'
        option pppoerelay '<set by script>'
        option ipaddr '192.168.1.1'
```

**Comment by Ansuel** [comment]
yes and you lose 5ghz connection... can't see the problem...

**Comment by meyergru** [comment]
In bridge mode? I see, WiFi could theoretically be enabled, but is useless then anyway. Matter-of-fact, in that mode, there are DHCP client requests against the MSAN.

**Comment by Kherby** [comment]
Should defently be done in Bridge Mode... Who needs wifi when using the device in Bridge Mode ?
If someone is using Wifi to gather stats/access the GUI 2.4GHz should be enough or even better because of the range limitation of 5GHz...

**Comment by meyergru** [comment]
The Wifi card could also be removed for bridge mode...

**Comment by Ansuel** [comment]
ummm lan5 can be removed from the gui anyway ....

**Comment by meyergru** [comment]
Right. Should be an implicit setting (e.g. when 5Ghz is enabled).

**Comment by nclmrc** [comment]
Any update?

**Comment by kevdagoat** [comment]
Sounds a bit unrealistic to me...

**Comment by kevdagoat** [comment]
@meyergru can you close this now?
