### ISSUE TITLE
cwmpd respawning

### ISSUE THREAD

**Issue by diekmanu** [Ansuel/tch-nginx-gui#532]
Device Model: 
Gui Version: 8.11 (Stable) / Firmware 2.0.0 / DGA4132

Description of problem:
Hi guys, 

I disabled the cwmpd daemon using /etc/init.d/cmpd stop/disable

The corresponding linkings in /etc./rc.d get removed. So far so good...

netstat -tlpn / ps  shows no entry for cwmpd after that.

But after a while the cwmpd daemon respawns. I'm really not sure, what is happening here...

Perhaps watchdog-tch is involved in restarting the daemon...?

The uci state for cwmpd is set to '0' => Disabled.

How to reproduce (if possible):

Stop/Disable the daemon and wait...

Media/Photos (if possible):

**Comment by kevdagoat** [comment]
Please specify your model of modem.

Try this:
/etc/init.d/autoreset stop
/etc/init.d/autoreset disable

**Comment by diekmanu** [comment]
DGA4132 / xDSL: A2pvfbH043k

The mentioned script is not available in my /etc/init.d...?

It seems that this gets periodically triggered by transformer under "/usr/share/transformer/commitapply/uci_cwmpd.ca"

Can this be avoided / is cwmpd really needed for foreign ISPs?

**Comment by Ansuel** [comment]
@diekmanu what action do you do ? commitapply triggers only on set of the transform set so... i need to know what settings you change in the gui to check what trigger it.

**Comment by diekmanu** [comment]
Nothing at all. The GUI / no browser is opened. Nothing is changed at the commandline. 
cwmpd just rises from the dead...;-)

The log entries start with "/etc/init.d cwmpd reload" when this happens. So my first guess was...this was initiated by transformer => uci_cwmpd.ca

Will cwmpd restart when the wan interface goes up/down??

**Comment by kevdagoat** [comment]
Ok was just making sure it wasn’t one of the newer Telstra Smartmodems

**Comment by diekmanu** [comment]
> root@timhub:~# logread | grep cwmpd
Thu Feb 28 18:25:27 2019 user.notice cwmpd: Reloading cwmpd
Thu Feb 28 18:25:27 2019 user.notice cwmpd: Starting cwmpd
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: PROT_TRACE: ConnectionRequestURL updated to http://:0/pCd8IMrqj2drbQtb
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: APP_TRACE: [plugins] registered '/usr/lib/cwmpd/libtransferplugin.so'
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.LinkStatus
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.StandardUsed
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.PPP.Interface.1.IPCP.LocalIPAddress
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: APP_TRACE: [plugins] registered '/usr/lib/cwmpd/libuciplugin.so'
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: TRANSFER: init transfer API
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: pushapi_load_forcedactives - set forcedactive success -  path: Device.ManagementServer.ConnectionRequestURL
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: pushapi_load_forcedactives - set forcedactive success -  path: Device.DSL.Line.1.LinkStatus
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: pushapi_load_forcedactives - set forcedactive success -  path: Device.DSL.Line.1.StandardUsed
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: pushapi_load_forcedactives - set forcedactive success -  path: Device.PPP.Interface.1.IPCP.LocalIPAddress
Thu Feb 28 18:25:28 2019 daemon.warn cwmpd[15893]: CWMPUCI: pushapi_load_forcedactives - set forcedactive success -  path: Device.DeviceInfo.X_TELECOMITALIA_IT_Unlocked
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: TRANSFORMER_PROXY: cwmp_softwareversion_changed -- SoftwareVersion changed = false
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: TRANSFORMER_PROXY: Received shutdown command, shutting down the listening thread!
Thu Feb 28 18:25:28 2019 daemon.info cwmpd[15893]: SCHEDULEINFORM: cwmp_scheduleInform_completeinit - Time Synced!
Thu Feb 28 18:25:34 2019 user.notice cwmpd: Reloading cwmpd
Thu Feb 28 18:25:34 2019 daemon.warn cwmpd[15893]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.LinkStatus
Thu Feb 28 18:25:34 2019 daemon.warn cwmpd[15893]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.DSL.Line.1.StandardUsed
Thu Feb 28 18:25:34 2019 daemon.warn cwmpd[15893]: CWMPUCI: cwmp_config_load_forcedinforms - set forcedinform success -  path: Device.PPP.Interface.1.IPCP.LocalIPAddress
Thu Feb 28 18:25:34 2019 user.notice cwmpd: Starting cwmpd
Thu Feb 28 18:25:34 2019 daemon.err cwmpd[15893]: CDUS_TRACE: cwmp_changedustateapi_flush CURRENTLY NOT IMPLEMENTED


This happens when the PPP connection drops. So I guess when you disable cwmpd the association/monitoring of these interfaces should be removed too.

**Comment by diekmanu** [comment]
So removing the execution bit from /etc.init.d/cwmpd seems to be the only solution at the moment?
I hope this won't break anything important.

**Comment by FrancYescO** [comment]
try disabling wansensing

**Comment by Ansuel** [comment]
@diekmanu can you give me watchdog configuration ?
