### ISSUE TITLE
Non si configura più il Wifi 2.4G

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#533]
Device Model: TIM HUB DGA-4132
Firmware 2.0.0
Gui Version: 8.13.9

nelle ultime versioni della Gui, nella tab Wireless per il 2.4G non viene più visualizzata l'area ( giorni fa veniva visualizzata EU invece di IT ) e non memorizza alcuna variazione ( tipo Ampiezza Canale, Intervallo breve protezione, etc ) mentre per il 5G non ci sono problemi

**Comment by FrancYescO** [comment]
personalmente ho EU sulla 2.4 e IT sulla 5

comunque puoi controllare se con l'ultima dev il bug e' ancora presente?

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/53695675-dc437600-3dbe-11e9-957c-bf5f9fcf3737.png)

**Comment by FrancYescO** [comment]
dovrei aver risolto anche questa sicuro sia l'ultima versione ?!

**Comment by nclmrc** [comment]
8.13.40.

**Comment by giulio63** [comment]
con la 8.13.40 continuo ad avere i problemi segnalati in questa issue, inoltre da poco ho anche io il messaggio d'errore 

Exact data not found in this paths: 
Key wps_button_handler : uci.button.button.@wps.handler

**Comment by FrancYescO** [comment]
.41

**Comment by giulio63** [comment]
con la 8.13.41 risolto per il messaggio d'errore che è scomparso e nella tab modem è tornato il valore del cpu load.
il problema riguardo il 2.4g rimane solo a me forse :-(  non so se c'entra il firmware aggiornato

**Comment by nclmrc** [comment]
@giulio63 provato a fare visualizza opzioni avanzate?

**Comment by giulio63** [comment]
ho il firmware AGTHP_2.0.1_002. nel 2.4G non visualizza l'area ed ignora le altre variazioni tipo ampiezza canale rimane sempre a 20 anche se la modifico in 20/40
ho aggiunto l'opzione manualmente per avere sempre attiva la visualizzazione di opzioni avanzate

**Comment by nclmrc** [comment]
prova a postare il file /etc/config/wireless

**Comment by giulio63** [comment]
ecco il mio attuale  /etc/config/wireless

config wifi 'global'
	option station_history_persistent '0'
	option station_history_save_delay '24'
	option wfa_model_name 'AGHP'
	option wfa_friendly_name 'Modem TIM'
	option wifi_analyzer_disable '0'

config wifi-device 'radio_2G'
	option type 'broadcom'
	option standard 'bgn'
	option rateset '1(b) 2(b) 5.5(b) 6 9 11(b) 12 18 24 36 48 54'
	option ht_security_restriction '1'
	option sgi '1'
	option cdd '0'
	option frame_bursting '0'
	option interference_mode 'auto'
	option interference_channel_list '1 2 3 4 5 6 7 8 9 10 11 12 13'
	option acs_config_file '/etc/wireless_acs.conf'
	option acs_state 'selecting'
	option acs_trace_level '0'
	option acs_chanim_tracing '0'
	option acs_traffic_tracing '0'
	option acs_policy '6'
	option acs_rescan_delay '180'
	option acs_channel_fail_lockout_period '28800'
	option acs_monitor_action 'policy'
	option acs_tx_traffic_threshold '50'
	option acs_rx_traffic_threshold '50'
	option acs_traffic_sense_period '5'
	option acs_interference_span '2'
	option acs_channel_monitor_period '5'
	option tx_power_adjust '+1'
	option tx_power_overrule_reg '1'
	option acs_rescan_period '86400'
	option acs_rescan_delay_policy 'notraffic'
	option acs_rescan_delay_max_events '999'
	option state '0'
	option country 'IT'
	option channelwidth 'auto'
	option channel '9'

config wifi-iface 'wl0'
	option device 'radio_2G'
	option mode 'ap'
	option state '1'
	option network 'lan'
	option reliable_multicast '0'
	option uapsd '0'
	option ssid '**********'

config wifi-ap 'ap0'
	option iface 'wl0'
	option state '1'
	option public '1'
	option ap_isolation '0'
	option station_history '1'
	option max_assoc '0'
	option security_mode 'wpa2-psk'
	option supported_security_modes 'none wep wpa2-psk wpa-wpa2-psk'
	option pmf 'disabled'
	option pmksa_cache '1'
	option wps_state '1'
	option wps_w7pbc '1'
	option wps_credentialformat 'passphrase'
	option wsc_state 'configured'
	option wps_ap_setup_locked '1'
	option acl_mode 'disabled'
	option acl_registration_time '60'
	option trace_modules ' '
	option trace_level 'some'
	option display_connected_devices '1'
	option wep_key '*************'
	option wps_ap_pin '*********'
	option wpa_psk_key '*****************'
	option bandsteer_id 'off'

config wifi-radius-server 'ap0_auth0'
	option state '0'
	option port '1812'
	option priority '3'
	option secret '***************'

config wifi-radius-server 'ap0_acct0'
	option state '0'
	option port '1813'
	option priority '3'

config wifi-device 'radio_5G'
	option type 'quantenna'
	option country 'IT'
	option channel 'auto'
	option standard 'anac'
	option state '1'
	option rateset '6(b) 9 12(b) 18 24(b) 36 48 54'
	option ht_security_restriction '1'
	option sgi '1'
	option cdd '1'
	option ldpc '1'
	option txbf '1'
	option acs_allowed_channels '36 40 44 48 52 56 60 64 100 104 108 112'
	option mumimo '0'
	option channelwidth 'auto'

config wifi-iface 'wl1'
	option device 'radio_5G'
	option mode 'ap'
	option state '1'
	option network 'lan'
	option reliable_multicast '1'
	option uapsd '0'
	option ssid '********'

config wifi-ap 'ap1'
	option iface 'wl1'
	option state '1'
	option public '1'
	option ap_isolation '0'
	option station_history '1'
	option max_assoc '0'
	option security_mode 'wpa2-psk'
	option pmf 'disabled'
	option pmksa_cache '1'
	option wps_state '1'
	option wps_w7pbc '1'
	option wsc_state 'configured'
	option wps_ap_setup_locked '1'
	option acl_mode 'disabled'
	option acl_registration_time '60'
	option trace_modules ' '
	option trace_level 'some'
	option supported_security_modes 'none wpa2-psk wpa-wpa2-psk'
	option display_connected_devices '1'
	option wep_key '*********'
	option wps_ap_pin '************'
	option wpa_psk_key '****************'
	option bandsteer_id 'off'

config wifi-radius-server 'ap1_auth0'
	option state '0'
	option ip '0.0.0.0'
	option port '1812'
	option priority '3'
	option secret '*********************'

config wifi-bandsteer 'bs0'
	option policy_mode '5'
	option monitor_window '5'
	option sta_comeback_to '5'
	option debug_flags '3'
	option rssi_5g_threshold '-80'
	option rssi_threshold '-60'

config wifi-iface 'wl0_1'
	option device 'radio_2G'
	option mode 'ap'
	option state '0'
	option network 'wlnet_b_24'
	option reliable_multicast '0'
	option uapsd '0'
	option ssid 'Ospiti-*******'

config wifi-ap 'ap2'
	option iface 'wl0_1'
	option state '0'
	option public '1'
	option ap_isolation '1'
	option station_history '1'
	option max_assoc '0'
	option security_mode 'wpa2-psk'
	option supported_security_modes 'none wep wpa2-psk wpa-wpa2-psk'
	option pmf 'disabled'
	option pmksa_cache '1'
	option wps_state '0'
	option wps_w7pbc '1'
	option wsc_state 'configured'
	option wps_ap_setup_locked '1'
	option acl_mode 'disabled'
	option acl_registration_time '60'
	option trace_modules ' '
	option trace_level 'some'
	option display_connected_devices '1'
	option wep_key '***********'
	option wpa_psk_key '*****************'
	option wps_ap_pin '**********'

config wifi-radius-server 'ap2_auth0'
	option state '0'
	option port '1812'
	option priority '3'
	option secret '*******************'

config wifi-radius-server 'ap2_acct0'
	option state '0'
	option port '1813'
	option priority '3'
	option supported_security_modes 'none wpa2-psk wpa-wpa2-psk'

config wifi-iface 'wl1_1'
	option device 'radio_5G'
	option mode 'ap'
	option state '0'
	option vlan_id '3'
	option network 'wlnet_b_5'
	option reliable_multicast '0'
	option uapsd '0'
	option ssid 'Ospiti***********'

config wifi-ap 'ap3'
	option iface 'wl1_1'
	option state '0'
	option public '1'
	option ap_isolation '1'
	option station_history '1'
	option max_assoc '0'
	option security_mode 'wpa2-psk'
	option supported_security_modes 'none wpa2-psk wpa-wpa2-psk'
	option pmf 'disabled'
	option pmksa_cache '1'
	option wps_state '0'
	option wps_w7pbc '1'
	option wsc_state 'configured'
	option wps_ap_setup_locked '1'
	option acl_mode 'disabled'
	option acl_registration_time '60'
	option trace_modules ' '
	option trace_level 'some'
	option display_connected_devices '1'
	option wep_key '**************'
	option wpa_psk_key '****************'
	option wps_ap_pin '***********'

**Comment by FrancYescO** [comment]
@giulio63 utilizzi il bandsteering? sembrava ero riuscito ad riprodurre il problema ma ora sembra salvarmi tutto correttamente... non riesci nemmeno a cambiare il nome della rete ad esempio?

**Comment by giulio63** [comment]
@FrancYescO no non utilizzo il bandsteering, ma in questi giorni ho provato ad abilitarlo/disabilitarlo ma senza cambiare la mia situazione. ho provato adesso a cambiare il nome della rete e me la fa subito !!! in pratica oltre a non visualizzare il campo "Area" non mi fa fare variazioni nel gruppo "Inferfaccia" della tab Wireless. se è colpa del firmware mi auguro che nel prossimo si risolva. volevo evitare di tornare indietro per non rischiare di avere altri problemi

**Comment by FrancYescO** [comment]
quindi il nome della rete riesci a cambiarlo?
il firmware non c'entra, ho anche io il 2.0.0 e riesco a configurare tutto

**Comment by giulio63** [comment]
si riesco a cambiare il nome della rete, ma ho voluto aggiornare al 2.0.1_002 , anche tu o sei col 2.0.0 ufficiale ? puo' creare problemi mettere il firmware precedente ma ufficiale ? ( la 2.0.0 )

**Comment by FrancYescO** [comment]
tra 2.0.0 e le beta 2.0.1 cambia poco quindi sono intercambiabili, ma ti ripeto il firmware influisce poco.

controlla se e' cambiato qualcosa con la .44 anche se non ho capito quali opzioni non riesci a cambiare ho provato anche a switchare tra 20 e 20/40 mhz e anche li mi sembra tutto ok

**Comment by giulio63** [comment]
temo di doverci rinunciare, visto che a parità di situazione con te, io mi ritrovo così : 

Nella tab wireless - sezione 2.4G

Non visualizza "Area"

non riesco a modificare :

Standard
Canale
Ampiezza canale
Intervallo breve protezione
Diversità ritardo-ciclico
Codice blocco spaziatura temporale
Burst frame

in pratica non memorizza nessuna variazione in questi campi ed apparentemente l'ampiezza canale rimane a 20Mhz . solo per sfizio, c'e' un comando ( forse del gruppo uci ) per verificare la reale configurazione da ssh ?

**Comment by nclmrc** [comment]
@Giulio nella 2.4 metti EU e ricarica.

**Comment by nclmrc** [comment]
@giulio63 inoltre vedo che hai la 2.4 off
option state '0'

**Comment by giulio63** [comment]
RISOLTO ;-) grazie @nclmrc 
ed a tutti scusate per la scocciatura

**Comment by giulio63** [comment]
non se sia corretto che l'area del 2.4G sia su EU ma adesso posso variare tutto. grazie ancora a tutti

**Comment by nclmrc** [comment]
@giulio63 se rimetti EU non rifunziona? perchè inizialmente non avevo visto quello 0

**Comment by giulio63** [comment]
adesso funziona tutto ma ho messo sia option state al valore 1 che l'area ad "EU" .
mi sembrava strano che non fosse a "IT" come per il 5G ma visto che funziona forse non mi faccio piu' troppe domande ;-)

**Comment by FrancYescO** [comment]
a me salva e la tengo messa ad EU quindi il problema non e' sicuramente solo li
