### ISSUE TITLE
Error 200 : HTTP_OK 

### ISSUE THREAD

**Issue by McClodde** [Ansuel/tch-nginx-gui#535]
Device Model: dga4132
Latest DEV

Errore
Error 200 : HTTP_OK dga4132

Questo è il messaggio che appare dopo l'aggiornamento da GUI. Il riavvio del modem non ha risolto il problema.

Come faccio a ripristinare l'interfaccia?

Grazie!

**Comment by Ansuel** [comment]
si attendi un attimo, il fix l'abbiamo già fatto... per aggiustare da putty 

upgradegui

**Comment by Ansuel** [comment]
@McClodde puoi aggiornare ora dovrebbe andar bene

**Comment by McClodde** [comment]
Aggiornato via shell, tutto è tornato funzionante. Grazie per il gran lavoro!
