### ISSUE TITLE
GUI Mobile

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#536]
Chiedevo se era possibile, visto che siamo arrivati quasi alla perfezione, se era possibile migliorare la visualizzazione dell'Ossido della rete Wifi.
Grazie

**Comment by Ansuel** [comment]
è in programma però mi devo studiare un pò di css

**Comment by nclmrc** [comment]
![Screenshot_20190313-000434_Chrome](https://user-images.githubusercontent.com/38593316/54242117-be46e580-4523-11e9-88f2-a30a7147e60e.jpg)
Per i collegamenti ethernet non dovrebbe apparire l'SSID

**Comment by nclmrc** [comment]
E poi come si puoi vedere dal precedente screenshot andrebbero ricentrate le schede

**Comment by nclmrc** [comment]
Ma l'icona del telefono quando non ci sono chiamate in corso non dovrebbe essere grigia? Adesso è verde.

**Comment by FrancYescO** [comment]
Bug, succede solo se la lingua non è inglese.

**Comment by nclmrc** [comment]
È rimasto da rimuovere l'SSID in caso di collegamenti cablati

**Comment by nclmrc** [comment]
L'SSID se possibile andrebbe rimosso anche da elenco dispositivi nella scheda dispositivi.

**Comment by FrancYescO** [comment]
ma.. e' la colonna di una tabella come facciamo a rimuovere solo per quelli cablati!?

**Comment by nclmrc** [comment]
Pensavo facendo un IF era possibile.

**Comment by Ansuel** [comment]
@FrancYescO si può però rimarrebbe spazio e si romperebbe... l'idea è rendere la targhetta vuota così che non si visualizza sul mobile...

**Comment by FrancYescO** [comment]
![image](https://user-images.githubusercontent.com/4574593/54479669-6fe55f80-481f-11e9-9673-b4c7e4c44c23.png)

se facciamo sparire la colonna SSID poi come li visualizziamo quelli wireless?

**Comment by Ansuel** [comment]
In mobile intendo dove ogni casella ha la targhetta

Il Sab 16 Mar 2019, 19:13 Francesco M <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
@nclmrc altro?

**Comment by nclmrc** [comment]
Nella versione mobile è rimasto questo problema del colore. 
https://github.com/Ansuel/tch-nginx-gui/issues/481

**Comment by nclmrc** [comment]
E poi secondo nella scheda internet, l uptime della connessione lo metterei nel sistema in internazionale come per le altre lingue.

**Comment by Ansuel** [comment]
@nclmrc che intendi nel sistema in internazionale?

**Comment by nclmrc** [comment]
D h m s

Inviato da Samsung Galaxy Note 8

Il Mar 19 Mar 2019, 19:05 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
E poi toglierei le unite di misura nell'orario di sistema. Generalmente si usano per indicare un tempo di uptime
