### ISSUE TITLE
Last dev

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#54]
With the last it's all broken. 

root@corsignano:~# upgrade-dev
Connecting to repository.ilpuntotecnicoeadsl.com (87.118.80.190:80)
bin/
bin/busybox_telnet
etc/
etc/config/
etc/config/dlnad_orig
etc/config/dropbear_new
etc/config/ipping
etc/config/telnet_orig
etc/config/watchdog
etc/config/web_unlock
etc/config/wol_orig
etc/crontabs/
etc/crontabs/root_gui
etc/ddns_new/
etc/ddns_new/services
etc/ddns_new/services_ipv6
etc/fwdassist.sh
etc/hotplug.d/
etc/hotplug.d/iface/
etc/hotplug.d/iface/50-miniupnpd
etc/hotplug.d/iface/99-wol
etc/init.d/
etc/init.d/dlnad
etc/init.d/miniupnpd
etc/init.d/mobiled
etc/init.d/power
etc/init.d/rootdevice
etc/init.d/telnet
etc/init.d/trafficmon
etc/init.d/wol
etc/init.d/xdsl
etc/nginx/
etc/nginx/fastcgi_params
etc/nginx/koi-utf
etc/nginx/koi-win
etc/nginx/mime.types
etc/nginx/naxsi_core.rules
etc/nginx/nginx.conf
etc/nginx/win-utf
etc/opkg/
etc/opkg/distfeeds.conf
etc/opkg.conf_16.3
etc/opkg.conf_17.3
etc/rc.d/
etc/rc.d/S94rootdevice
etc/ssl/
etc/ssl/certs/
etc/ssl/certs/578d5c04.0
etc/ssl/certs/aee5f10d.0
etc/ssl/certs/AGprivkey.key
etc/ssl/certs/d6d84089.0
etc/ssl/certs/rootTLC-CA.cer
etc/ssl/openssl.cnf
etc/ssl/private/
etc/uci-defaults/
etc/uci-defaults/99-miniupnpd
etc/wansensing/
etc/wansensing/L2Main.lua
etc/wireless_acs.conf
lib/
lib/libCdsObjects.so
lib/upgrade/
lib/upgrade/platform.sh
root/
root/ripdrv.ko
sbin/
sbin/sysupgrade
sbin/trafficdata.lua
sbin/trafficmon.lua
usr/
usr/bin/
usr/bin/dlnad
usr/bin/openssl
usr/bin/rtfd
usr/bin/sysupgrade-safe
usr/lib/
usr/lib/cwmpd/
usr/lib/cwmpd/transfers/
usr/lib/cwmpd/transfers/switchover.sh
usr/lib/cwmpd/transfers/upgrade.sh
usr/lib/libcrypto.so.1.0.0
bzcat: bunzip error -3
tar: short read
Segmentation fault (core dumped)
Root Script: Disable watchdog
Root Script: Start rooting
Root Script: Stopping nginx and transformer
Root Script: Checking if we are on TIM configuration
Root Script: Unlocking web interface if needed
Root Script: Check and cleanup
Root Script: Remove default dns
Root Script: Purify wan
Root Script: Fix dns bug
Root Script: Enable dlnad
Root Script: Fix Sysupgrade
Root Script: Check orig config
Root Script: Trafficmon inizialization
Root Script: Restore original mapper
Root Script: Transformer lib check
Root Script: Remove https check
Root Script: Check css presence
Root Script: Check if dnsmasq is names as we need it for the webui
Root Script: Check driver setting
Root Script: Check Dropbear config file
Root Script: Check ddns directory
Root Script: Check eco param
Root Script: Enable new upnp
Root Script: Sync dhcp configuration for new webui
Root Script: Create gui type in config
Root Script: Add new web option
Root Script: New DHCPRelay Option
Root Script: Disable trace from igmpproxy
Root Script: Moving aria2 dir
Root Script: Creating new option for led definition
Root Script: Old build detected, moving wansensing file
Root Script: Checking downgrade limitation bit
Root Script: Checking opkg conf
Root Script: Creating and checking real version
Root Script: Creating new wol implementation
Root Script: Sync new xdsl option
Root Script: Setting root flag
Root Script: Disable reboot after crash, this gives race condition...
Root Script: Save root password if modified
Root Script: Setting dropbear settings
Root Script: Doing various check and generating hash...
Root Script: Sync version
Root Script: Apply modification
Root Script: Restart power init
Root Script: Restarting dropbear
Root Script: Restarting dnsmasq
Root Script: Process done.
Root Script: Restarting transformer
Root Script: Waiting transformer to start for 20 seconds
Root Script: Restarting nginx
Root Script: Restarting transformer a second time cause it's just shit...
sh: can't kill pid 13040: No such process
Root Script: Resetting cwmp and watchdog

**Comment by meyergru** [comment]
Yes, the file is only 1.1 MByte instead of 3.5.

**Comment by Ansuel** [comment]
The admin are migrating the server
Think that's why

Il Gio 17 Mag 2018, 08:32 meyergru <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
@meyergru ok i restored the file and i fixed a stupid problem

 also as i'm lazy... in your opinion, make a link to the upgrade script would be good?

**Comment by meyergru** [comment]
Which link? I don't understand?

**Comment by Ansuel** [comment]
i mean a simbolic link

**Comment by meyergru** [comment]
That would not hurt ;)
