### ISSUE TITLE
CUPS Web Server blocked by firewall rule9

### ISSUE THREAD

**Issue by Dark4Codrutz** [Ansuel/tch-nginx-gui#540]
Device Model: DGA4132
**Firmware: 2.0.0**
Gui Version: 9.0.20 (bug present on older aswell)

Description of problem: 
CUPS web server toggle starts the server but the webpage is not working (time-out)

How to reproduce (if possible):
Enable Printer Sharing and Web Interface. 
Navigate to 192.168.1.1:631

Things I've tried but didn't solved:
I've checked the cupsd.conf file and seems fine to me: having WebInterface Yes and Allow from 192.168.1.0/24 in there but it still doesn't allow me to access it's web interface.
I've also tried stopping the service and restart it with service cupsd stop and start, no errors but still the same result.

[**Workaround**](https://github.com/Ansuel/tch-nginx-gui/issues/540#issuecomment-473689152)

**Comment by Ansuel** [comment]
news on this?

**Comment by Dark4Codrutz** [comment]
Not at all. I haven't tried messing around with .config files too much in fear to break things further.

**Comment by Dark4Codrutz** [comment]
Preferisci inglese per il multinational, o vabene anche italiano ?

**Comment by Dark4Codrutz** [comment]
Is CUPS working for you ?
Maybe is broken only on my side ..
Much appreciated to know

**Comment by kevdagoat** [comment]
Maybe do a full factory reset and flash of an older firmware

**Comment by kevdagoat** [comment]
@Dark4Codrutz Can you please run:
```cat /etc/config/firewall``` and post the output?

**Comment by Dark4Codrutz** [comment]
sure thing
https://pastebin.com/CKL269iQ

**Comment by Dark4Codrutz** [comment]
From it I see this :
```
config rule 'rule9'
        option name 'Deny-CUPS-lan'
        option src 'lan'
        option proto 'tcp'
        option dest_port '631'
        option family 'ipv4'
        option target 'DROP'
```
which doesn't seem right
I previously tried to add a Port Forward for 631 with the modem MAC (as it doesn't allow me to do it for 192.168.1.1) but didn't worked. I deleted the rule since.

**Comment by Dark4Codrutz** [comment]
> Maybe do a full factory reset and flash of an older firmware
> …

I'm considering doing a factory reset.
Will it remove root if I use Modem->Factory Defaults option ?

**Comment by FrancYescO** [comment]
no, root is removed only with the unroot button under modgui modal

**Comment by Dark4Codrutz** [comment]
I've done the Factory Defaults reset, but CUPS webpage is still not working. 
Also the firewall config is the same (except for personal rules) including those rule9 and rule10 previously posted here

**Comment by FrancYescO** [comment]
does remove rule9 (and restarting firewall) fix the CUPS interface?

**Comment by Dark4Codrutz** [comment]
### Workaround
Deleting rule9 block from /etc/config/firewall and reloading the service with `service firewall reload` fixes the issue and the webpage shows up at 192.168.1.1:631 as expected
```
config rule 'rule9'
        option name 'Deny-CUPS-lan'
        option src 'lan'
        option proto 'tcp'
        option dest_port '631'
        option family 'ipv4'
        option target 'DROP'
```

**Comment by Dark4Codrutz** [comment]
Can this be automated by the script associated with the toggle in the UI ?
Maybe with a better firewall management than mine. I don't know linux so well, but maybe there is a way to simple override rule9 instead.

**Comment by FrancYescO** [comment]
yep will be included in future release...

**Comment by stuzzica** [comment]
io non riesco a far funzionare CUPS e nel firewall non risulta bloccato e la pagina da EDGE non risulta visibile 
DGA4131fwb con Ansuel Gui 9.5.56
nella gui la condivisione risulta essere attiva e la stampante e stata riconosciuta ma non so come aggiungerla su windows -_- 
![Immagine](https://user-images.githubusercontent.com/53705618/79976079-5c81da80-849c-11ea-9abd-267a97feab72.jpg)

**Comment by FrancYescO** [comment]
che firmware? e che errore? io con il 18 riesco ad aprirla senza problemi..
