### ISSUE TITLE
Duplicate fields when using "Always show advanced options"

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#543]
![immagine](https://user-images.githubusercontent.com/38593316/53726983-73680680-3e6f-11e9-9db7-292224c53edf.png)

**Comment by nclmrc** [comment]
ho visto è così in tutte le schermate, anche per esempio in DLNA. da capire se è voluto o un errore

**Comment by FrancYescO** [comment]
sembra sia collegato al fatto di utilizzare l'opzione "Always show advanced options"
