### ISSUE TITLE
Strange symbols in "Interfaces" part of "Stats" page

### ISSUE THREAD

**Issue by monreal** [Ansuel/tch-nginx-gui#545]
Device Model: DGA4132
Gui Version: 8.13.56

Description of problem: Strange symbols in "Interfaces" part of "Stats" page

How to reproduce (if possible): just open Web UI

Media/Photos (if possible):

![screenshot from 2019-03-04 12-22-58](https://user-images.githubusercontent.com/54005/53731082-f5f5c380-3e79-11e9-93f7-f871ca97ef03.png)

**Comment by FrancYescO** [comment]
clear browser cache

**Comment by monreal** [comment]
That worked, thanks a lot
