### ISSUE TITLE
Setting to disable all effects

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#546]
Even if most part of user, use super fast browsers on super updated hardware... 
Someone still has obsolete browsers on pretty slow hardware.  And, since it's just a router... 

Please give the possibility to globally disable all the effects, animations and cards popups to allow to manage the router also using old hardware/browsers. Thanks!

**Comment by Ansuel** [comment]
i add an option to disable most of them

**Comment by xes** [comment]
thank you very much. 
..But still cards loading animation in every rectangle seems to slow down a lot. 
It's just me?

**Comment by Ansuel** [comment]
We are doing some test about it... We also notice some delay in the loading and we are searching the cause. In the next stable will not be there anyway so...

**Comment by FrancYescO** [comment]
Closing as this got implemented
