### ISSUE TITLE
Errore dopo aggiornamento Interfaccia

### ISSUE THREAD

**Issue by McClodde** [Ansuel/tch-nginx-gui#548]
Device Model:  dga4132
Gui Version:  8.13.57 DEV

Description of problem:
Dopo l'aggiornamento (fatto via upgradegui senza errori) e dopo la pagina di accesso non vengono visualizzate le schede; il messaggio è: "La pagina non funziona 192.168.1.1 non ha inviato dati.
ERR_EMPTY_RESPONSE"

Grazie.

**Comment by Ansuel** [comment]
riaggiorna da putty
