### ISSUE TITLE
8.13.58 DEV interfaccia non funzionante

### ISSUE THREAD

**Issue by McClodde** [Ansuel/tch-nginx-gui#549]
Device Model: dga4132
Gui Version: 8.13.58 DEV

Description of problem:
Dopo l'aggiornamento (fatto via upgradegui senza errori) e dopo la pagina di accesso non vengono visualizzate le schede; il messaggio è: "La pagina non funziona 192.168.1.1 non ha inviato dati.
ERR_EMPTY_RESPONSE"

Rifatto aggiornamento da putty, ma l'errore permane.

Grazie!

**Comment by Ansuel** [comment]
si scusa... c'erano 2 errori... ora va
