### ISSUE TITLE
aggiornamenti

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#553]
Device Model: dga4132
Gui Version: 8.13.64

Description of problem:
dalla pagina principale statistiche il pulsante aggiornamenti non funziona, mentre dal menu schede va benissimo.

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/542
