### ISSUE TITLE
Nginx error log

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#559]
2019/03/07 14:12:28 [error] 5508#0: *5 lua entry thread aborted: runtime error: /usr/lib/lua/web/lp.lua:175: bad argument #1 to 'setfenv' (integer expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'setfenv'
	/usr/lib/lua/web/lp.lua:175: in function 'include'
	/usr/lib/lua/web/web.lua:188: in function 'exit'
	/usr/lib/lua/web/web.lua:257: in function 'process'
	content_by_lua(nginx.conf:163):4: in function <content_by_lua(nginx.conf:163):1>, client: ***.***.***.***, server: localhost, request: "POST /ajax/cpuload.lua?auto_update=true HTTP/1.1", host: "dga4132.ddns.net", referrer: "http://dga4132.ddns.net/cards.lp"

**Comment by FrancYescO** [comment]
quando appare?

**Comment by nclmrc** [comment]
l'ho trovato scorrendo nei log, sinceramente non so dirti quando è apparso.

**Comment by Dark4Codrutz** [comment]
hai ancora quel tipo di error nei log ?

Potresti confermarmi se il file /usr/sbin/nginx pesa 554KB oppure pesa 1,2MB ?

**Comment by FrancYescO** [comment]
nelle versioni > 2.1.0 il binario di nginx non viene rimpiazzato quindi deve essere quello di 500 e dispari kb
