### ISSUE TITLE
Background when reload page

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#561]
![immagine](https://user-images.githubusercontent.com/38593316/54075810-fdff9a00-42a3-11e9-97d2-1affc723218b.png)

**Comment by Ghost9090** [comment]
@FrancYescO @Ansuel

**Comment by FrancYescO** [comment]
qual e' il problema? il tempo di caricamento delle informazioni nella card?

**Comment by nclmrc** [comment]
prima di caricare l'immagine, di sottofondo cìè una stringa "gateway"

**Comment by FrancYescO** [comment]
e' il normale comportamento del browser, viene visualizzato il testo che l'immagine rappresenta durante il caricamento di quest'ultima

**Comment by nclmrc** [comment]
capito, prima non lo faceva
