### ISSUE TITLE
CWMP disabled. Really?

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#566]
Even if cwmp is disabled on gui, service cwmp is running and listening and port 7170 that looking at the firewall is in fact open.

Chain zone_wan_input (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 4372  223K MMPBX      all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 4214  215K input_wan_rule  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* !fw3: user chain for input */
    3   180 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:7170 /* !fw3: ubus:cwmpd[cwmpd] rule 1 */

**Comment by kevdagoat** [comment]
Could you please give us some more info!

It really helps

**Comment by xes** [comment]
Sorry, you are right... 
DGA 4132 
FW 2.0.0
GUI dev 8.13.71

..after a few days of uptime, no idea if triggered by any dsl resync/disconnect, cwmp card still shows disabled while service is running and port 7170 is reachable from outside.

Maybe it could be useful add into cards about CWMP and Remote assistance the realtime status of related firewall ports. 
This would produce an immediate feedback if anything goes wrong showing when service is (should) be disabled while ports are still opened on iptables.

**Comment by putipower** [comment]
95.239.xxx.xx is responding on port 7170 ().

**Comment by putipower** [comment]
@Ansuel @FrancYescO cosa ne pensate?si può fare in modo di chiudere questa porta e magari aggiungere un controllo come diceva @xes ?
grazie

**Comment by Ghost9090** [comment]
@FrancYescO  @Ansuel anche perché l'accesso remoto con app mytim non funziona anche se c'è l'indirizzo del campo giusto. Continua a dare sempre modem spento

**Comment by Ghost9090** [comment]
![20190313_154015](https://user-images.githubusercontent.com/44716486/54287667-63a29d80-45a6-11e9-8e4b-08a3764291a7.jpg)
![Screenshot_20190313-153921_Chrome](https://user-images.githubusercontent.com/44716486/54287677-6a311500-45a6-11e9-92fd-443d6f0d1822.jpg)

**Comment by kevdagoat** [comment]
Could you please post a debug dump :) 

System Extras > Generate Debug file (dont have exact name)

**Comment by Ghost9090** [comment]
Me? @kevdagoat

**Comment by kevdagoat** [comment]
Sorry wrong issue :D

**Comment by xes** [comment]
Sincerely, which feedback is still needed?

Any ppp reconnect triggers a cwmpd reload/restart:

Sun Mar 24 00:08:55 2019 user.notice pppoe-relay-hotplug: Interface wan ifup
Sun Mar 24 00:08:55 2019 user.notice cwmpd: Reloading cwmpd

At the moment i fixed it adding into /etc/init.d/cwmpd a good "exit 0" after start_service() and reload_service().

**Comment by diekmanu** [comment]
Or just remove the e(x)ecute rights for cwmpd in /etc.init.d

**Comment by Ansuel** [comment]
modifiy the init.d or remove the exe is not a solution... is just a workaround for a specific problem.

**Comment by diekmanu** [comment]
Yep, but no one wants this port open to the outside world. At least not when this is not a requirement by your ISP.

There were a lot of security concerns regarding TR-069 / CWMP in the past. Don't know if this has been addressed/fixed. So this is something you guys need to figure out. It seems to be related to wansensing  like @FrancYescO mentioned. But I have no time to dig any further at the moment.

**Comment by FrancYescO** [comment]
just continue here https://github.com/Ansuel/tch-nginx-gui/issues/566
