### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by rizlas** [Ansuel/tch-nginx-gui#567]
When clicking on Advanced -> Sign Out, the loaded page will be blank and not the login one.

Note: title of page remains gateway and not Login

Gui version: 8.11.49

**Comment by Ansuel** [comment]
can't reproduce this

**Comment by kevdagoat** [comment]
Clear browser cache

**Comment by rizlas** [comment]
Tried with empty cache, different browser (Chrome or Firefox both latest version available) and different device. Same result. In network tab i cant see any call to login page.

**Comment by FrancYescO** [comment]
also me cannot reproduce... page is blank or gray? is there something in the page source (try to save the page with ctrl+s and upload here ... see if is there some error in logread)

**Comment by rizlas** [comment]
Blank page..

`
<!DOCTYPE HTML>
<html lang="it-it">
  <head>
    <title>Gateway</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="UTF-8">
    <meta name="CSRFtoken" content="fdd5c2eaca0f8a79caa28c8a7321d18e778c2f0f8bd39319e9917895b59c97c7">
    <meta name="Advanced" content="">
	<link href="/css/font-awesome-all-5.7.2.css?version=9.0.14" rel="stylesheet">
    <link href="/css/gw.css?version=9.0.14" rel="stylesheet">
	<link id="theme_skin" rel="stylesheet" href="/theme/green/style.css?version=9.0.14">
	<link rel="shortcut icon"    type="image/x-icon"   href="/img/favicon.ico"    />
    <link href="/css/responsive.css?version=9.0.14" rel="stylesheet">
	
    <link rel="stylesheet" href="/css/aos.css?version=9.0.14" >
	<script src="/js/jquery.min.js?version=`

**Comment by kevdagoat** [comment]
Are you on latest GUI version?
Have you installed LuCI?

**Comment by kevdagoat** [comment]
Oh and what gateway model?

**Comment by rizlas** [comment]
No luci
Latest gui
TG789V2

**Comment by FrancYescO** [comment]
Firmware?
"Latest GUI" too vague

Still cannot find a way to reproduce the issue

**Comment by kevdagoat** [comment]
Reproduced:
TG799vac GUI 9.0.87
- No Internet Access
- From Stats page

logread: 
```
 daemon.err nginx: 2019/04/06 18:29:23 [error] 15779#0:                                                                                              *64 lua entry thread aborted: runtime error: /usr/lib/lua/web/sessioncontrol.lua                                                                                             :443: attempt to call ngx.redirect after sending out the headers
stack traceback:
coroutine 0:
        [C]: in function 'ngx_redirect'
        /usr/lib/lua/web/sessioncontrol.lua:443: in function 'redirect'
        [string "header.lp"]:40: in function 'content'
        /usr/lib/lua/web/lp.lua:176: in function 'include'
        [string "/gateway.lp"]:32: in function 'content'
        /usr/li
```

Image:
![image](https://user-images.githubusercontent.com/42062334/55668266-18746580-589a-11e9-8ec4-d2364e270976.png)

**Comment by Ansuel** [comment]
Finally fixed
