### ISSUE TITLE
Quantità regole mappatura porte errata 

### ISSUE THREAD

**Issue by brusarp** [Ansuel/tch-nginx-gui#580]
Device Model: DGA4132 2.0.0
Gui Version: 9.0.14

Description of problem:
Il numero di regole di mappatura porte visualizza solo le unità (ne ho 11 e mostra 1, se ne ho 12 mostra 2)

How to reproduce (if possible):
Creare abbastanza regole da superare la decina

Media/Photos (if possible):
![Scheda ](https://user-images.githubusercontent.com/14950532/54495893-ca96be00-48e8-11e9-8726-807a215a7787.JPG)
![Scheda2](https://user-images.githubusercontent.com/14950532/54495894-ca96be00-48e8-11e9-9022-166c941e5fb7.JPG)

**Comment by FrancYescO** [comment]
Cannot reproduce..

![image](https://user-images.githubusercontent.com/4574593/54498294-c9c05500-4905-11e9-82d5-d99b58fd5a40.png)
![image](https://user-images.githubusercontent.com/4574593/54498296-d17ff980-4905-11e9-96ea-c14c9b4052a1.png)

**Comment by FrancYescO** [comment]
lo fa solo con lingua italiana..
