### ISSUE TITLE
Grafici monitoraggio traffico 

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#584]
C'è qualcosa che non va nei grafici. Almeno quelli delle reti wireless sono tutti uguali tra loro.

**Comment by Ansuel** [comment]
@nclmrc puoi mettere degli screen ? da me sono diversi

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/54615829-0784c100-4a5f-11e9-87de-44fc57f37605.png)
![immagine](https://user-images.githubusercontent.com/38593316/54615873-19fefa80-4a5f-11e9-8de6-5ec91f907cd3.png)

**Comment by nclmrc** [comment]
la parte verde è uguale @Ansuel

**Comment by FrancYescO** [comment]
confermo, anche sul wifi ospiti che ho sempre tenuto spento ho il grafico verde uguale
