### ISSUE TITLE
In "Grafico statistiche Modem" non ci sono dati visualizzati

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#586]
Device Model:  DGA4132
Gui Version   :  Dev 9.0.32
Firmware      :  AGTHP_2.0.1_002

Description of problem :

Nella Tab "Gestione modem" , in "Grafico statistiche Modem", sia "Grafico uso CPU" che "Grafico memoria libera" sono completamente vuoti

**Comment by nclmrc** [comment]
Sono novità aggiunte nell'ultima versione.?

**Comment by Ansuel** [comment]
in teoria si dovrebbe riavviare il modem... non abbiamo messo il riavvio del servizio per non eliminare le statistiche

**Comment by giulio63** [comment]
confermo, riavviandolo il grafico viene valorizzato. grazie

**Comment by nclmrc** [comment]
Ma che funzionalità è questa?

Inviato da Samsung Galaxy Note 8

Il Mar 19 Mar 2019, 23:29 giulio63 <notifications@github.com> ha scritto:

**Comment by FrancYescO** [comment]
grafico utilizzo cpu e memoria
