### ISSUE TITLE
IP Extras - DNS settings disappearing (cosmetic)

### ISSUE THREAD

**Issue by matteone2** [Ansuel/tch-nginx-gui#587]
Device Model: DGA4130
Gui Version: 9.0.14
Firmware : Cyan 17.3.c   (AGTEF_2.0.0)

Description of problem: 
if I manually configure LAN DNS , then all DNS settings disappear inside "IP Extras" card. 
Issue is only cosmetic, all settings are retained correctly.

How to reproduce (if possible):
uci set network.lan.dns='1.1.1.1'

then go to GUI -> "IP Extras" and scroll down to see DNS settings -> empty table

Now, if i run
uci delete network.lan.dns

then go to GUI -> "IP Extras" and scroll down to see DNS settings -> table comes back

LOGREAD
----------
daemon.err transformer[3179]: [truncated] getter(rpc.network.interface.@., dnsserver2_query) threw an error: ...share/transformer/mappings/rpc/network.interface.map:535: bad argument #1 to 'concat' (table expected, got string)
stack traceback:
        [C]: in function 'concat'
        ...share/transformer/mappings/rpc/network.interface.map:535: in function 'getDnsServers'
        ...share/transformer/mappings/rpc/network.interface.map:726: in function <...share/transformer/mappings/rpc/network.interface

**Comment by Ansuel** [comment]
the dns needs to be a list not a unique string.

use all_list
