### ISSUE TITLE
Firmware upgrade not working TG789vac Xtream 35b (with solution)

### ISSUE THREAD

**Issue by matteone2** [Ansuel/tch-nginx-gui#588]
Device Model: TG789vac Xtream 35B - Fastweb (vbnt-f)
Gui Version: DEV 9.0.32
Version: Jade 16.2 
(16.2.7825-3401001-20170627171140_FW_212_IAD_TG789vacXtream)

Description of problem:
Firmware update not working, both from GUI and from command line

How to reproduce:
(GUI)
"Modem" Card -> Update firmware -> Hangs on "rebooting" and never completes

(Command line)
If you try to manually update via "sysupgrade" you get:
/sbin/sysupgrade: .: line 3: can't open '/lib/functions/system.sh'

Solution:
Copy the following file from DGA4130/4132 
/rom/lib/functions/system.sh
and put in /lib/functions/  of  TG789vac Xtream 35b

**Comment by kevdagoat** [comment]
Just need to add system.sh to the package.

@matteone2 Can you post the file so I can do it?

**Comment by matteone2** [comment]
Here it is:

[system.zip](https://github.com/Ansuel/tch-nginx-gui/files/3010880/system.zip)

File is taken from DGA4132, firmware AGTHP 2.0.0

**Comment by kevdagoat** [comment]
Sorry I meant: /lib/functions/system.sh
