### ISSUE TITLE
Analizzatore Wifi

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#589]
Ma l'analizzatore wireless (nella scheda wireless) che faceva la scansione delle reti wireless, con l'ultimo firmware 2.0.0 è stato tolto?

**Comment by Ansuel** [comment]
a me viene mostrato correttamente

**Comment by FrancYescO** [comment]
anche io notavo era scomparso.. solo su 789 e' ancora li

**Comment by Ansuel** [comment]
provo a resettare

**Comment by nclmrc** [comment]
che firmware hai @Ansuel ?

**Comment by Ansuel** [comment]
2.0.1
