### ISSUE TITLE
NTP not working

### ISSUE THREAD

**Issue by boynet7000** [Ansuel/tch-nginx-gui#594]
[DebugHelper2019-03-23-1104.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/2999245/DebugHelper2019-03-23-1104.tar.gz)

Device Model: Technicolor TG789vac V2

Gui Version: any from 8.11, actually 9.0.46

Description of problem: when starting (reboot or power up) NTP does't sync. I have to opern telnet and set time manually

How to reproduce (if possible):
Modem configured as Bridge
3 NTP server: 193.204.114.105, ntp1.inrim.it, 0.it.pool.btp.org.
Time zone set Europe/Rome, Time zone taken from net.

**Comment by FrancYescO** [comment]
if the modem is configured as bridge means that have no interne so how ntp could work?!

coult you please also give the output of this SSH command
`transformer-cli get uci.network.interface.@wan.ifname`

**Comment by boynet7000** [comment]
this is the output:
uci.network.interface.@wan.ifname [string] = eth4

modem receives internet via ethernet "wan" port and correctly gives internet to devices connected to other ethernet ports and to its 2.4 & 5GHz wireless. I also can log-in using PC on the LAN.

Setting it as bridge is my error?

**Comment by FrancYescO** [comment]
whats the IP/subnet of the main router? who is the DHCP?

probably what you need is DHCP or Static IP mode, bridge is used when you have a device on the LAN side that connects to internet
