### ISSUE TITLE
Aggiornamento GUI automatici

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#596]
@Ansuel mi sa che non funziona l'aggiornamento automatico. A l'ora fissata non mi ha installato l aggiornamento.

**Comment by FrancYescO** [comment]
io ho un 789 con firmware tiscali e gui stable senza che toccassi nulla (e con l'aggiornamento automatico attivo) da settimane ora e' correttamente alla 9.0.49

**Comment by nclmrc** [comment]
mi è successo stamani per  la prima volta. pootrebbe essere stata un'eccezione

**Comment by nclmrc** [comment]
È successo anche stamani

**Comment by Ansuel** [comment]
news?

**Comment by nclmrc** [comment]
Domani se ci sono aggiornamenti nella notte ti faccio sapere

**Comment by nclmrc** [comment]
@Ansuel non mi fa più l'aggiornamento automatico alle 7

**Comment by nclmrc** [comment]
Ho controllato non c'è nessun crontab inserito

**Comment by nclmrc** [comment]
@Ansuel provato anche a modificare l'ora per forzare la scrittura nel crontab ma non ha funzionato

**Comment by FrancYescO** [comment]
Appena provato anche io, su quello dove si aggiorna il crontab c'e, ma impostato l'autoupgrade su uno "nuovo" non viene aggiunto il crontab
