### ISSUE TITLE
Aggiornamento odhcpd

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#597]
Visto che nelle ultime versioni hanno implementato alcune configurazioni e risolto dei bug si potrebbe aggiornarlo direttamente dalla GUI? 
L'aggiornamento proposto è questo:
odhcpd - 2017-07-04-f0d78e7ebfa785fd6037e1f1f711d6c382450c3b - 2017-12-22-7aa2594c5a127d92fa8f04328ac7b43e595bcaa7

**Comment by FrancYescO** [comment]
non so se e' cosa giusta rimpiazzare di default pacchetti preinstallati.. a che bug/configurazioni ti riferisci nello specifico?

**Comment by nclmrc** [comment]
Ci sono dei Fix per ipv6. Il problema la versione che è nel repo è buggata pure quella.
