### ISSUE TITLE
Servizio DDNS "NO-IP.COM" non aggiorna

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#600]
con l'aggiunta della possibilità di avere più servizi DDNS ho provato ad aggiungere NO-IP. 
Non si aggiorna mai e da' il messaggio "Aggiornamento : Nessun errore ricevuto dal server".
Provando i servizi DynDns.org  e DynDns.it funziona senza problemi. 
Probabilmente hanno cambiato la url di aggiornamento dell'IP ?

**Comment by Ansuel** [comment]
Fixed*

**Comment by giulio63** [comment]
non so se il problema è solo mio ma NO-IP.com continua a non aggiornarsi pur stando con la gui dev 9.0.55 ed avendo fatto ripartire diverse volte il router.
Nel file di log ho visto :  
ddns.myddns_ipv6=service
 130202       : verbose mode  : 0 - run normal, NO console output
 **130202  WARN : No update_url found/defined or no update_script found/defined! - TERMINATE**
 130202  WARN : PID '9352' exit WITH ERROR '1' at 2019-03-24 13:02

ed il file ha il nome **myddns_ipv6.log** pur avendo **l'IPV6 disabilitato**

**Comment by Ansuel** [comment]
ho fixato il messaggio non il problema....

**Comment by giulio63** [comment]
nel file **/etc/config/ddns**  ho rinominato nella sezione del servizio **No-Ip.com** nelle opzioni

**option interface**   e   **option ip_network**   da 'wan6' a **'wan'**

ed impostato  **option use_ipv6 '0'**

e sembra funzionare

non capisco dove abbia preso l'informazione che debba essere ipv6 che è disattivato mentre per gli altri 2 servizi non si crea il problema

**Comment by Ansuel** [comment]
nessun mistero o cose magiche...

semplicemente di default ci sono 2 configurazioni una ipv4 e una ipv6.
