### ISSUE TITLE
Syslog forward

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#603]
Device Model: DGA4132
Firmware: 2.0.0
Gui Version: 9.0.58

Description of problem:
![syslog](https://user-images.githubusercontent.com/3456902/54914065-6da49480-4ef4-11e9-9859-fddef299dbf1.png)

Section should be named "Syslog forward"  or "Syslog server"
If you enable the Filter switch, the label of syslog server changes from "IP" to "Filter IP" and the forward does not work. (i think it should be "syslog server ip address")

In the situation described by the image, syslog forward doesn't works.
(is it correct? Maybe i can't understand the logic)

**Comment by kevdagoat** [comment]
Hmm, will look into this tomorrow

**Comment by giulio63** [comment]
you've tried this software ?  http://maxbelkov.github.io/visualsyslog/

**Comment by xes** [comment]
Thanks..

Shouldn't  "Port" remain near the server setting also when filters are enabled?
Is it correct that with filters enabled (but empty) no message will be sent to the syslog server?
