### ISSUE TITLE
GUI flat?

### ISSUE THREAD

**Issue by adryx92** [Ansuel/tch-nginx-gui#604]
Ciao, stavo smanettando un attimo sul mio scolapasta e ho pensato di metter mano al CSS per avere un'interfaccia più moderna e flat. A qualcuno può interessare approfondire la questione?

Qui una immagine illustrativa: https://www.dropbox.com/s/b2tc1s4ybi0630o/Annotazione%202019-03-26%20000251.jpg?raw=1

**Comment by Ansuel** [comment]
implementare un tema non è troppo difficile ;)

**Comment by adryx92** [comment]
No, infatti. Ci ho giocato una mezz'ora l'altra sera :)

Vedo cosa riesco a combinare nei prossimi giorni. 

Intanto complimenti per il progettone.

**Comment by Ansuel** [comment]
per fare un tema è molto easy comunque

apri win scp i css sono in /www/docroot/theme/nome_tema/nonricordonome.css

volendo puoi modificare un tema già esistente e poi fai una pr o fai te

**Comment by FrancYescO** [comment]
Chiudo e attendiamo la PR o news qui

**Comment by adryx92** [comment]
Ciao, ci ho lavorato un po' e la sto usando tranquillamente sul mio router. Non e' perfetta ma una base c'e'.
