### ISSUE TITLE
Correzioni GUI

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#607]
Per favore postate qui le richeiste di correzione della GUI

**- GUI 9.0.61**

![Snap5](https://user-images.githubusercontent.com/1262554/55000608-293bf600-4fd3-11e9-9618-e73045f7eb87.jpg)

Vicino a "Versione firmware" non dovrebbe essere visualizzata la versione del firmware e non come ora la versione del driver?

**Comment by FrancYescO** [comment]
E' meglio avere issue diverse si si fa riferimento a problemi diversi.
Siamo nella modal xDSL quindi e li si fa riferimento alle informazioni generali per l'appunto della dsl

**Comment by bovirus** [comment]
Secondo me la scritta "Versione firmware" in questo contesto è fuorviante.

**Comment by giulio63** [comment]
nella tab "Servizi WAN" riguardo la nuova funzionalità di poter gestire più servizi DDNS credo sia corretto rinominare sia fuori che dentro la tab, la scritta DynDns ( che è il nome di un servizio DDNS ) con il termine corrispondente al tipo di serivizio : DDNS
