### ISSUE TITLE
Gui versione mobile

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#61]
Rimane sempre la barra di selezione dei tab di sinistra in primo piano.

**Comment by nclmrc** [comment]
Anche con le ultime release ho lo stesso problema

**Comment by nclmrc** [comment]
Anche con l'ultima.

**Comment by nclmrc** [comment]
![screenshot_20180706-220918_chrome](https://user-images.githubusercontent.com/38593316/42398268-7cfacb60-8169-11e8-9583-403bc14c3024.jpg)

**Comment by nclmrc** [comment]
Problema persiste

**Comment by nclmrc** [comment]
The bar doesn't close never

**Comment by Escart94** [comment]
We're going to check It soon, thanks for the feedback.

**Comment by Ansuel** [comment]
Dovrebbe essere fixata con l'ultima versione

**Comment by nclmrc** [comment]
Mi dispiace ma non è ancora risolto

**Comment by nclmrc** [comment]
Ora rimane il problema con chrome che non si scorre la pagina fino in fondo per arrivare ai bottoni salva e chiudi.
