### ISSUE TITLE
Wifi Guest

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#611]
Come mai pur essendo disabilitata la rete Wifi guest a 5Ghz me la trovo inserita nella routing table? Mentre la 2.4 guest anch'essa disabitata non la vedo? Fino a qualche versione precedente erano entrambe nella routing table, ma visto che sono disabitate si possono inserire solo al momento che vengono attivate le rispettive reti.

root@DGA4132:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         46.182.152.1    0.0.0.0         UG    0      0        0 pppoe-wan
5.43.239.0      10.56.17.1      255.255.255.0   UG    0      0        0 pppoe-voip
10.8.0.0        192.168.1.1     255.255.255.0   UG    0      0        0 br-lan
10.56.0.0       10.56.17.1      255.255.0.0     UG    0      0        0 pppoe-voip
10.56.17.1      0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-voip
46.182.152.1    0.0.0.0         255.255.255.255 UH    0      0        0 pppoe-wan
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 br-lan
192.168.10.0    0.0.0.0         255.255.255.0   U     0      0        0 eth4
192.168.168.128 0.0.0.0         255.255.255.128 U     0      0        0 wl1_1
239.0.0.0       0.0.0.0         255.0.0.0       U     0      0        0 br-lan
root@DGA4132:~# ping 192.168.168.129
PING 192.168.168.129 (192.168.168.129): 56 data bytes
64 bytes from 192.168.168.129: seq=0 ttl=64 time=0.359 ms
64 bytes from 192.168.168.129: seq=1 ttl=64 time=0.566 ms
64 bytes from 192.168.168.129: seq=2 ttl=64 time=0.574 ms
^C
--- 192.168.168.129 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.359/0.499/0.574 ms
root@DGA4132:~# ping 192.168.168.1
PING 192.168.168.1 (192.168.168.1): 56 data bytes
^C
--- 192.168.168.1 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
root@DGA4132:~#

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/55138618-302e4a00-5134-11e9-83a6-31742535568f.png)

**Comment by FrancYescO** [comment]
io non ho mai attivato le reti guest nella routing table ho solo la `wlnet_b_24`

**Comment by nclmrc** [comment]
Io ho la 5.2. Prima avevo entrambe.

**Comment by nclmrc** [comment]
Adesso ok
