### ISSUE TITLE
Band Steering

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#613]
Abilitando o disabilitando le reti guest il band steering si disattiva

**Comment by nclmrc** [comment]
succede anche se viene disabilitata una delle due rete primarie

**Comment by FrancYescO** [comment]
> succede anche se viene disabilitata una delle due rete primarie

il che e' giusto

**Comment by nclmrc** [comment]
Però le guest, sinceramente non dovrebbero avere a che fare con il band
steering

Inviato da Samsung Galaxy Note 8

Il Gio 28 Mar 2019, 20:14 Francesco M <notifications@github.com> ha scritto:

**Comment by FrancYescO** [comment]
si infatti li probabilmente c'e qualcosa che non va... a dire il vero non dovrebbe nemmeno permettere di disattivare una radio se il bandsteering e' abilitato

**Comment by nclmrc** [comment]
@Ansuel Le impostazioni del band steering mi si modificano senza fare niente. Si disattiva e cambiano le soglie. Nello script upgradegui ce qualcosa?

**Comment by Ansuel** [comment]
che io sappia no

**Comment by nclmrc** [comment]
Qualunque modifica faccia alle impostazioni wireless il band steering si resetta. Ieri sera ho provato la nuova funzione della potenza in uscita e me l'ha fatto.

**Comment by nclmrc** [comment]
ad esempio se attivo il band steering, la potenza in uscita delal ghz mi viene impostato automaticamente a -6dbm quando prima era invece a +6dbm, se la rimposto a +6dbm mi si disattiva il bandsteering

**Comment by nclmrc** [comment]
Hai capito qualcosa @Ansuel?

**Comment by nclmrc** [comment]
Inoltre se modifico le soglie si disabilita all'istante il band steering

**Comment by FrancYescO** [comment]
Hai provato con le ultime versioni? Cosa ti si resetta nello specifico?

**Comment by nclmrc** [comment]
Si disattiva il band steering quando si modificano le soglie o la potenza
della 5ghz

Inviato da Samsung Galaxy Note 8

Il Sab 13 Lug 2019, 13:45 Francesco M <notifications@github.com> ha scritto:
