### ISSUE TITLE
Selected gui causes '404 Not Found'

### ISSUE THREAD

**Issue by amaridev** [Ansuel/tch-nginx-gui#615]
Hi, I might need a little help. Probably more of a user issue than a bug.

I was switching between the styles in the web gui to choose one. When I selected the Fritz gui, the web interface got non accessible. Nginx is showing 404 from now on. 

How do I get the webgui back to a working state via ssh? I didn't root the device myself, so I am not very familiar with the system and what config files are gui related. 

Thanks.

**Comment by Ansuel** [comment]
upgradegui from ssh

**Comment by amaridev** [comment]
Wow, this was helpful. Thank you very much 👍
