### ISSUE TITLE
Enable DHCP wan not working

### ISSUE THREAD

**Issue by steguerrini** [Ansuel/tch-nginx-gui#616]
Device Model: TG789vac V2
Gui Version: 9.0.49
Firmware: Uno v17.2

Description of problem:
Dopo una installazione pulita della GUI, settando l'opzione "DHCP routed", viene sempre restituito l'errore "La richiesta non puo essere eseguita a causa di un errore" quando si tenta di attivare tale modalità.
Tuttavia è possibile abilitare tale opzione utilizzando il comando 'uci set network.wan.auto=1'.
Il problema persiste anche con la dev version attuale.

Avevo una installazione precedente (v.9.011 stabile aggiornata da una precedente 8.11), in cui questo problema non sussisteva (forse a causa di un qualche settaggio ereditato dalla precedente versione?

How to reproduce (if possible):
- Install the GUI
- Set Internet mode to "DHCP routed"
- Click on the enable button

**Comment by FrancYescO** [comment]
`logread` da ssh quando compare l'errore

Posta anche uno zip di debug report che generi dalla card extra

**Comment by FrancYescO** [comment]
@steguerrini please provide infos
