### ISSUE TITLE
Gui sottosopra

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#617]
Device Model: dga4132
Gui Version: 9.0.84

Description of problem:
 Gui sottosopra

How to reproduce (if possible):

Media/Photos (if possible):
![Schermata del 2019-04-01 19-50-50](https://user-images.githubusercontent.com/43514633/55348602-d9b86700-54b7-11e9-9c31-ab847a2e3146.png)

**Comment by Dark4Codrutz** [comment]
haha benvenuto al pesce d'aprile di Ansuel xD
