### ISSUE TITLE
Problem with certain kinds of IPv6 packets (Hurricane Electric IPv6 Tunnel)

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#62]
There are problems with lost packets to the HE IPv6 tunnel endpoint, even in bridge mode.

This has been discussed here:

https://www.onlinekosten.de/forum/showthread.php?p=2439539#post2439539

There is a cure for that behaviour, namely setting:

```
fcctl disable
fcctl config --mcast 0
```

Which disables some aspects of then proprietary Broadcom "Flow Cache" feature that causes these drops.

Maybe you could add a preference checkbox ("Disable Flow Cache to support IPv6 tunneling") for this which applies those settings on every startup.

**Comment by Kherby** [comment]
+1 Please add this, so the settings will be applied on every startup...
Will probably save some people from headaches !

**Comment by meyergru** [comment]
You can test the current settings with 'fcctl status', it seems they are applied immediately.

I have disabled the feature completely by doing this in /etc/rc.local:

```
fcctl disable
fcctl config --l2tp 0
fcctl config --gre 0
fcctl config --ipv6 0
fcctl config --mcast 0
fcctl config --mcast-learn 0
```

I have seen no negative effects to this, however, I do not use HE. Another user from Onlinekosten Forum found this solution to his problem.

**Comment by Ansuel** [comment]
ummm i should add this option somewhere... any idea where? (i mean in the gui... adding all this function is not that hard..)

**Comment by meyergru** [comment]
The logical place would be broadband or gateway, since it works in bridge mode.

I think it is a hardware feature, I would place it in Gateway.

**Comment by Ansuel** [comment]
i'm adding it to ip advanced with a new tab...

**Comment by Ansuel** [comment]
added option in ip extra

**Comment by meyergru** [comment]
Works fine, but two the feature is called "Flow Cache", not "Fast Cache".
