### ISSUE TITLE
All ways advanced not working

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#620]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: tg799vac
Gui Version:9.0.87

Description of problem:
When enabling “always show advanced” and refreshing the page, advanced is still not shown. Even on different computers and tabs

How to reproduce (if possible):

Media/Photos (if possible):
Always advanced on:
![255ED1DD-85C4-445E-9839-DBE8EC16A10A](https://user-images.githubusercontent.com/42062334/55545827-a0266c80-5700-11e9-956a-e904be9b7b9a.jpeg)

Not advanced mode:
![8EDA5D2E-0AE4-4A41-80D1-11F1603DE711](https://user-images.githubusercontent.com/42062334/55545871-bcc2a480-5700-11e9-9915-a1ca63c44c62.jpeg)

**Comment by FrancYescO** [comment]
workingforme
![image](https://user-images.githubusercontent.com/4574593/55649885-7d6d8400-57e4-11e9-8f4b-2ae41a904eb9.png)

**Comment by kevdagoat** [comment]
Ok will retry

**Comment by kevdagoat** [comment]
No luck
Same on both my tg799s

**Comment by FrancYescO** [comment]
browser used?

**Comment by kevdagoat** [comment]
Chrome Latest
