### ISSUE TITLE
Completely disable DSL activity

### ISSUE THREAD

**Issue by andreagdipaolo** [Ansuel/tch-nginx-gui#624]
It would be nice being able to disable completely DSL even from the "XDSL Configuration" card. 
Right now I'm on ETH WAN with automatic recognition disabled and i cannot shut down DSL, which keeps trying to detect a DSL signal.

**Comment by kevdagoat** [comment]
GUI version?
Modem model number?

**Comment by andreagdipaolo** [comment]
I'm currently on DEV GUI 9.0.90 
TG788vn v2
But that's not a bug, that's a suggestion for a new feature, so it's valid everywhere.

**Comment by kevdagoat** [comment]
Ok tks

**Comment by kevdagoat** [comment]
@andreagdipaolo

Post the output of

ls /etc/init.d

**Comment by andreagdipaolo** [comment]
`bcm-device-nodes      conntrackd            dnsmasq               hostapd               log                   mwan                  portmirror            redirecthelper        swmdk                 trafficmon            wol
bcmubusbridge         cron                  done                  hostmanager           mcsnooper             neighm                power                 restore               sysctl                transformer           xdsl
boot                  cupsd                 dosprotect            igmpproxy             miniupnpd-tch         network               pppoe-relay           rootdevice            sysctl-tch            umount                xinetd
brcm_kthrd_prios      cwmpd                 dropbear              install-ipks          mldproxy              nginx                 pppoe-relay-tch       rtfd                  sysfixtime            usbmode               xtm
bulkdata              cwmpdboot             ethernet              intercept             mmpbxd                ngwfdd                pre-mwan              samba                 syslog_fwd            wansensing
cgconfig              ddns                  ethoam                ipset                 mobiled               odhcpd                prozone               samba-nmbd            sysntpd               warmboot
cgevent               dhcpopassthrud        fcctlsettings         iqos                  mountd                phypower              qos                   softswitch            system                watchdog-tch
cgred                 dhcpsnooper           firewall              led                   mud                   pinholehelper         ra                    sscert                telnet                wfa-testsuite-daemon
cgroup_rt_processes   dlnad                 fseventd              ledfw                 mvfs                  platform-gpl          random_seed           sudo                  tod                   wifi-doctor-agent
root@OpenWrt:~#
`

**Comment by kevdagoat** [comment]
Try:
/etc/init.d/xdsl stop
/etc/init.d/xdsl disable

If that doesnt work, go to Broadband >> Show advanced, Uncheck WanSensing and manually select Ethernet WAN

**Comment by andreagdipaolo** [comment]
I believe you're not getting the main purpose of this issue. 
I spoke with Francesco weeks ago and I'm suggesting to add the option to the GUI. 
If I wanted to disable it from CLI I could already. 
P.S. unchecking wansensing doesn't kill DSL, it still detects the absence of line every now and then.

**Comment by kevdagoat** [comment]
Ok. Did you manually set the connection mode? It then should say “xDSL Disabled”?

**Comment by andreagdipaolo** [comment]
It only says "WAN ETH Connesso" in the third card

**Comment by kevdagoat** [comment]
Did you click on “Show Advanced “ in the top right corner of the card.

Please post screenshot

**Comment by andreagdipaolo** [comment]
![image](https://user-images.githubusercontent.com/49479876/57719759-c1279900-7680-11e9-9422-7dd258d30fd0.png)
I enabled the "always show advanced" setting weeks ago. 
But I believe since the opening of this issue someone worked on that and it seems gone. b light doesn't blink anymore every now and then. 
But I noticed it when ETH was disconnected and I can't try now.

**Comment by Ansuel** [comment]
Option added
