### ISSUE TITLE
Rebase list for new firmware based on kernel 4.1

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#626]
First:
- [x] Clean rootdevice script to only root the device 
- [x] Adds various check for kernel compatibility
- [x] Push emergency release to stable to fix brick with the new version

Then we can continue with:
- [x] Check for new lxc container if creates problem
- [x] Rework web libs
- [x] Rework mapping
- [x] Rework web 
- [x] Fix the bugs.......................... (with a lots of points)

**Comment by kevdagoat** [comment]
Why to only root the device?

**Comment by Ansuel** [comment]
rootdevice should only unlock and set root password

the other commands should be moved to another script and called after that if the user request it...
The rooting process is universal for every modem... the custom script instead can cause problems

**Comment by kevdagoat** [comment]
Sounds like a good idea

**Comment by nutterthanos** [comment]
How is compatibility going with any firmware based on kernel 4.1?

**Comment by Ansuel** [comment]
works fine except for the exstension (opkg package)

**Comment by nutterthanos** [comment]
Ok how about the emergency release to stable to fix brick with new version?

**Comment by Ansuel** [comment]
still not done :( pretty busy for university exams

**Comment by nutterthanos** [comment]
Ok

**Comment by nutterthanos** [comment]
So what is the fix for?

**Comment by nutterthanos** [comment]
@Ansuel Why change the root password in the script when we already had to change to ssh into the gateway’s?

**Comment by Ansuel** [comment]
@nutterthanos what do you mean ?

**Comment by nutterthanos** [comment]
You said about rootdevice should only unlock and set root password.

**Comment by Ansuel** [comment]
the script is used also when you upgrade the firmware so... they are just additional check

**Comment by nutterthanos** [comment]
Ok

**Comment by Ghost9090** [comment]
@Ansuel quando rilasci la versione stabile con tutti i fix?

**Comment by nutterthanos** [comment]
It should happen soon like when @Ansuel is happy with all the fixes from the master repo and it does not have many bugs in it with the current features.

**Comment by Ghost9090** [comment]
Ancora la gui non è compatibile con il firmware 2.1.0?
