### ISSUE TITLE
telegestione dga 4132

### ISSUE THREAD

**Issue by putipower** [Ansuel/tch-nginx-gui#629]
salve ragazzi
non riesco ad attivare la telegestione,dalla pagina principale della gui non mi attiva lo switch,se entro e lo attivo lo salva ma non sembra attivarsi
potete aiutarmi?
grazie
https://ibb.co/85D6gVy
AGTHP_2.0.1_003 Versione GUI 9.1.6

**Comment by Ghost9090** [comment]
Pure a me lo stesso problema @FrancYescO @Ansuel

**Comment by FrancYescO** [comment]
Bug grafico inserito con il merge, probabilmente la televisione è già attiva
________________________________

**Comment by putipower** [comment]
il problema e' che non vedo traccia che e' attivo da gestione modem--->visualizzatore eventi
e da mytim mi vede un sercomm!!!!

**Comment by putipower** [comment]
@FrancYescO quale e' la giusta versione da impostare nello spoof?conviene impostarlo a mano o lasciare fare allo spoof di comunicare a cwmp l ultima versione dello script root?considera che devo partire per qualche settimana,e non vorrei che succedesse qualcosa in mia assenza
grazie

**Comment by Dark4Codrutz** [comment]
GUI: 9.1.6
Confermo di avere lo stesso problema. Ora, oltre al bug grafico, l'app MyTim Fisso sembra non riconoscere i parametri del modem.
Per esempio nella scheda wifi dell'app mi fa vedere solo il 2.4GHz con <unkown ssid>.
Tutte le altre opzioni sono sparite, tranne scheda Wifi che non funziona e scheda Dispostivi Collegati che ancora rileva bene, tra cui non funziona più la scheda Linea Internet da dove potevo facilmente vedere l'indirizzo IP per accedere da remoto.
Soprattutto l'accesso remoto a sé non funziona più nell'applicazione. Quindi tutto l'utilizzo di CWMP da parte dei utenti è broken.

**Comment by Dark4Codrutz** [comment]
ecco un log 
https://gist.github.com/Dark4Codrutz/1f0a55750050cc2c2c1ed5742ab2e994

**Comment by Ghost9090** [comment]
@Ansuel

**Comment by Ansuel** [comment]
il problema è stato fixato (quello dello switch)

**Comment by Ghost9090** [comment]
@ansuel è per il fatto che il modem non è raggiungibile da remoto per leggere i dati e altro?

**Comment by Ansuel** [comment]
da me funziona... quindi o è un problema di versione impostata male nello spoof o di indirizzo sbagliato

**Comment by Ghost9090** [comment]
Io l'ho sempre lasciato di default e mytim fisso mi dice modem spento. Pure lo spoofing della versione. Sia in manuale che in automatico

**Comment by Ansuel** [comment]
riguardo l'indirizzo del cwmp? e che versione ti mostra?

**Comment by Ghost9090** [comment]
Lo spoofing la 2.0.0 come hai impostato tu. L'indirizzo è https://regman-mon.interbusiness.it:10800/acs

**Comment by Ansuel** [comment]
quell'indirizzo lo puoi aprire?

**Comment by Ghost9090** [comment]
Se lo apro con chrome mi da DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Ghost9090** [comment]
Magari hai la lista completa degli indirizzi acs che usa la tim per controllare da remoto il modem?

**Comment by Ansuel** [comment]
si c'è ma se hai i dns diversi da quelli telecom è ovvio che non funziona

**Comment by Ghost9090** [comment]
Per forza quelli loro devo usare?

**Comment by Ansuel** [comment]
o quello o li aggiungi

**Comment by Ghost9090** [comment]
@ansuel sei in grado di implementare la base dect sul tim hub? Sarebbe molto utile

**Comment by Dark4Codrutz** [comment]
Con l'ultima versione della GUI (9.1.43) confermo che l'app Tim funziona normalmente, anche in remoto.

Chiudere la issue ?
