### ISSUE TITLE
exported config files lacks "users" name&password

### ISSUE THREAD

**Issue by boynet7000** [Ansuel/tch-nginx-gui#633]
Device Model: Tg789vac v2 - configured as bridge
Gui Version: various from stable v9.0.49 + dev 9.x.xx

Description of problem: don't konw if it a bug or it is intended, but files created with GUI "export configuration" button, miss the USERs datas, Name&Password not only my personal but also "admin" and "root"

**Comment by kevdagoat** [comment]
What’s wrong with that :)

It is for if a hacker manages to get access to your gateway web GUI, they can’t change the root pw and stuff it up entirely

**Comment by nutterthanos** [comment]
that can’t happen as long as the gateway is not accessible on http or https on the internet.

**Comment by FrancYescO** [comment]
this should be a default tch behaviour as exporting (and reimporting) this data in the past allowed privilege escalation
