### ISSUE TITLE
GUI Skin Fritz!Box broken

### ISSUE THREAD

**Issue by SushiTee** [Ansuel/tch-nginx-gui#638]
Device Model: DGA 4132
Gui Version: 9.0.49
Browser: Chome 74.0.3729.131

Fritz!Box skin is more or less broken. It works well on 1920x1080 in full screen but another resolution breaks it. On higher resolutions the popup windows are moved down (see screenshot 1). 

Doing the following (changing top to 5%) fixes it for me.
```
@media screen and (min-height: 1025px) and (min-width: 768px)
.modal.fade.in {
    top: 5%;
}
```

If you have lower resolutions the main content overlaps the navigation column on the right. In some cases the main content is even in front of the navigation column. Just have a look on the screenshots.

To see all the issues just play around with the browser zoom (CTRL+Plus | CTRL+Minus).

<img width="1499" alt="1" src="https://user-images.githubusercontent.com/293612/57568129-789f7f80-73e3-11e9-9d5b-c6cb1f41b40f.png">
<img width="1499" alt="2" src="https://user-images.githubusercontent.com/293612/57568131-80f7ba80-73e3-11e9-83cf-7ed030fb73d9.png">
<img width="1499" alt="3" src="https://user-images.githubusercontent.com/293612/57568135-8ead4000-73e3-11e9-9d79-d0725aa3c39d.png">
<img width="1499" alt="4" src="https://user-images.githubusercontent.com/293612/57568136-92d95d80-73e3-11e9-8941-83ea6cc7eabb.png">

**Comment by kevdagoat** [comment]
Try clearing cache

@ansuel @francyesco What has happened to the project?

**Comment by SushiTee** [comment]
Already did. Also happens with Firefox and on two different devices. Happens with 9.1.16, too.

Well there are a lot of other places where things are messed up with that skin but especially the issue of screenshot 1 is annoying because you cannot reach the "close" or "save" button.

**Comment by Ansuel** [comment]
can you tell me the resolution ?

**Comment by SushiTee** [comment]
General settings:
- screen resolution: 3000 x 2000
- 150% zoom in windows display settings (not browser zoom)
- browser uses whole screen width

Screenshot 1:
- No browser zoom (100%)
- DevTools of browser reports: 1983.330 x 1151.330

All other screenshots:
- browser zoom: 125%
- DevTools of browser reports: 1586.670 x 907.773

**Comment by Ansuel** [comment]
@SushiTee can you test latest dev  ?

**Comment by SushiTee** [comment]
The issue with on screenshot 1 seems to be fixed. The issues on screenshot 2 to 4 with 125% zoom are still there. the statistics page still overlaps the navigation.

I think I got what is creating the problem.

The table with connected devices doesn't only show the IPv4 addresses in the IPv4 column but aslo the IPv6 addreses. Due to the length of the string for the IPv6 addresses the table grows too wide. This makes the total width of the statistics page too wide.

**Comment by Ansuel** [comment]
my bad i tested only for card page and not for statistics

**Comment by SushiTee** [comment]
Statistic page is still not fixed in 9.1.29. See my last comment about the string length of IPv6 strings.

**Comment by Ansuel** [comment]
New on this ? @SushiTee

**Comment by SushiTee** [comment]
On desktop it seems to be fine now. On mobile device it's unusable though.

Screenshots taken on statistics page with iPhone SE:

portrait:
![IMG_3559](https://user-images.githubusercontent.com/293612/61083703-ada07080-a42c-11e9-9df8-391e925acda4.PNG)

landscape:
![IMG_3560](https://user-images.githubusercontent.com/293612/61083708-af6a3400-a42c-11e9-831f-6942affdee69.PNG)

**Comment by kevdagoat** [comment]
Could you try with safari?

**Comment by SushiTee** [comment]
looks exactly the same.

**Comment by FrancYescO** [comment]
fixed https://github.com/Ansuel/tch-nginx-gui/commit/6187d6ceb679aa666e0068f173ee3b699d9be6b0
