### ISSUE TITLE
Midnight dark

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#64]
Nel tema midnight Dark, manca il riepilogo in fondo con crediti versione gui e changelog.

**Comment by nclmrc** [comment]
Il problema si presenta solo nella versione mobile.

**Comment by 9anSan5** [comment]
In realtà il problema persiste anche nella versione desktop del tema dark/white

**Comment by nclmrc** [comment]
Yes I confirm on gui mobile and desktop

**Comment by Ansuel** [comment]
Fixed c4622966e4b4d3ec2a72b7754c66939be737c37e
