### ISSUE TITLE
unable to access "wifi scheduling"

### ISSUE THREAD

**Issue by boynet7000** [Ansuel/tch-nginx-gui#640]
Device Model: Technicolor TG789vac v2
Gui Version: 9.1.24

Description of problem:
trying to access to "pianificazione wireless" (=wifi scheduling, in English UI, I think...) under "wireless", I obtain this error: "Si è verificato un errore interno del server. Contatta l´amministratore"

How to reproduce (if possible):
TG789 in bridge mode

[DebugHelper2019-05-13-1613.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3173303/DebugHelper2019-05-13-1613.tar.gz)

**Comment by Ansuel** [comment]
can you post the tod config file ?

**Comment by boynet7000** [comment]
yes. Please tell me where the "tod config file" is and/or how cai I obtain it.

**Comment by Ansuel** [comment]
/etc/config/tod give me this file

**Comment by kevdagoat** [comment]
Run cat /etc/config/tod

**Comment by boynet7000** [comment]
here it is:
[tod.zip](https://github.com/Ansuel/tch-nginx-gui/files/3176309/tod.zip)
