### ISSUE TITLE
Support for a file manager in web gui?

### ISSUE THREAD

**Issue by nutterthanos** [Ansuel/tch-nginx-gui#644]
I wonder if there was like a file manager in this gui?

**Comment by kevdagoat** [comment]
Well, that would be possible, but the constant polling of changes and loading of it would be very slow and may wear out the NAND flash.

I think a more achievable goal would be a WebCLI, so you can browse the file system using the CLI.

**Comment by Ghost9090** [comment]
@kevdagoat why don't you create the base dect for all technicolor modems including those from TIM?

**Comment by FrancYescO** [comment]
No builtin filemanager..
i think you could find something that is working with openwrt/luci (ie https://github.com/giaulo/luci-app-filebrowser) , but you should test by yourself

**Comment by FrancYescO** [comment]
@Ghost9090 Stop asking random things in random issues.
DECT requires dedicated hardware that there isn't in DGA4132.

**Comment by nutterthanos** [comment]
Ok then i guess i will just have to something else on github or google for one.
