### ISSUE TITLE
GUI 9.1.31 - GUI fix requests

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#645]
@Ansuel 
@FrancYescO 

Trovati alcuni problemi nella build 9.1.31.
vedi screenshoot

![TIM-GUI_9 1 31-01](https://user-images.githubusercontent.com/1262554/57782320-4451f900-772c-11e9-903d-9dd4d82d846e.jpg)
**Save on USB** va aggiunto alle stringhe da tradurre

![TIM-GUI_9 1 31-02](https://user-images.githubusercontent.com/1262554/57782335-4b790700-772c-11e9-9751-94ec39e10245.jpg)
**Idle** non è tradotto

![TIM-GUI_9 1 31-03](https://user-images.githubusercontent.com/1262554/57782345-52077e80-772c-11e9-8273-49b9bcdb48d1.jpg)
Errore. Vedi messaggio.

![TIM-GUI_9 1 31-04](https://user-images.githubusercontent.com/1262554/57782352-57fd5f80-772c-11e9-83da-d394e1a0df03.jpg)
Errore. Vedi messaggio.

Inoltre nell ultime stringhe aggiunte (stringhe contenti "Isp") secondo me "Isp" va modificato in "ISP"

**Comment by nclmrc** [comment]
Anche in firewall ci sono delle nuove cose. @Ansuel ho provato ad abilitare o disabilitare lo stealth ma non mi sembra cambi niente nelle configurazioni.

**Comment by bovirus** [comment]
@Ansuel 
@FrancYescO 

Potete fissare per favore le stringhe nel file sorgente

Aggiungere "Save on USB"
Modificare "Isp" in "ISP"
Modificare "Ghz" in "GHz"
Modificare "Step Duration(ms):" in "Step Duration (ms):"

Grazie.

@nclmrc 
@Ghost9090

Qui troverete per quanto possibile aggiornato il firmware con le traduzioni applicate

https://drive.google.com/open?id=16k567aSrnqDZA5SOmi_sCeGPi7IkwCfZ

**Comment by Ghost9090** [comment]
novità per questi fix? @Ansuel @bovirus

**Comment by bovirus** [comment]
Quella è il link della mia build temporanea che ho suato fino a che Ansuel avevo fatto il merge della traduzione.

Ora nella build ufficilale la traduzione al 99.9% dovrebbe essere aggiornata.
