### ISSUE TITLE
Enhancement Firmware Update

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#646]
Is it possible to add a check for the firmware version before an update to check if it is compatible with the GUI or not?

**Comment by kevdagoat** [comment]
Exactly what sysupgrade does when you try to update the firmware

**Comment by FrancYescO** [comment]
basically not as the only way to test if the GUI is working is installing it.
Is impossibile for us to know modification they made and if will work on future/unknown firmwares

**Comment by lorenzocanale-LC** [comment]
What I was thinking is maybe a banner to warn a normal user that the version (like 18.3) has not been tested and decide to continue or not
