### ISSUE TITLE
GUI doesn't display the gateway image

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#649]
Device Model: TG789vac V2 FW UNO 17.2 
Gui Version: 9.1.43

Description of problem: GUI doesn't display the gateway image

Photos:
<img width="287" alt="Schermata 2019-05-17 alle 19 22 01" src="https://user-images.githubusercontent.com/44505255/57945208-84a2aa00-78d9-11e9-873a-77d0cf6ddcbc.png">

**Comment by Ansuel** [comment]
i need this

transformer-cli get uci.env.var.prod_friendly_name

**Comment by lorenzocanale-LC** [comment]
MediaAccess TG789vac v2
