### ISSUE TITLE
TG789vac V2  UNO.uk - inconsistent xtm interface naming

### ISSUE THREAD

**Issue by ElectricFighter** [Ansuel/tch-nginx-gui#651]
I'm having issues while trying to connect this modem to TIM network through ADSL2+. It looks like the GUI is unable to set some parameters and, even if the modem manage to establish xDSL connection, it's impossible to get PPPoE to work and it's stuck on "connecting" with a red led blinking.

When reading the info under Broadband and Internet Access what I get is "Path not found" for the data regarding VP/VC and PPPoE statistics as shown here. 

![image](https://user-images.githubusercontent.com/20916176/57977035-ec96e480-79ee-11e9-9ee5-f4e42c3e9080.png)

![image](https://user-images.githubusercontent.com/20916176/57977037-03d5d200-79ef-11e9-9127-ea6712eb2513.png)

I tried both stable and dev version of the GUI and at the moment I'm on version 9.1.45 with UNO Firmware 17.2

I also noticed that the configuration wizard is unable to set the values of VPI and VCI and I had to manually change those in the /etc/config/xtm file to have them set correctly (now also shown as default when opening the wizard)

**Comment by Ansuel** [comment]
mi devi postare la conf network e xtm

**Comment by ElectricFighter** [comment]
Ecco qui, il file network editato solo per coprire il numero usato come user per PPPoE
[xtm.zip](https://github.com/Ansuel/tch-nginx-gui/files/3194724/xtm.zip)
[network.zip](https://github.com/Ansuel/tch-nginx-gui/files/3194725/network.zip)

**Comment by Ansuel** [comment]
in xtm cambia in atmwan

**Comment by ElectricFighter** [comment]
Sembra funzionare tutto, avessi saputo prima che era quello non avrei aperto l'issue.
Possibile che sia settato male/diversamente sul fw base di UNO? L'unica modifica fatta al file xtm prima di questo sono stati i valori di VPI e VCI, che dal wizard venivano poi letti

**Comment by Ansuel** [comment]
l'interfaccia in network eta atmwan e in xtm era atm0 questo era il problema

**Comment by FrancYescO** [comment]
Firmware and model.

**Comment by FrancYescO** [comment]
check in install script / allow lua to work with both naming reference must be done to avoid this behaviour?

**Comment by nutterthanos** [comment]
@ElectricFighter Have you tryed latest dev?

**Comment by nutterthanos** [comment]
@FrancYescO the install script does nothing to the xtm or network file.

**Comment by FrancYescO** [comment]
I know, that's why this issue is still open

**Comment by nutterthanos** [comment]
Wow this issue is still open after 2 months I thought this has been fixed already.
