### ISSUE TITLE
GUI auto update doesn't work.

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#654]
GUI auto update doesn't work.

**Comment by kevdagoat** [comment]
Logread? Debug report? Modem info?

**Comment by nclmrc** [comment]
DGA4132. I have a cronjob at 7A.M.

**Comment by Kherby** [comment]
Does the manuell Update via "Check Update" work? It does work for me as I just updated from 9.1.53 to 9.1.54 via "Check Update" from GUI.

**Comment by nclmrc** [comment]
check ver from gui:

Fri May 24 13:44:38 2019 daemon.crit nginx: 2019/05/24 13:44:38 [crit] 8732#0: *18 [lua] lp.lua:77: compile(): [string "/modals/modgui-modal.lp"]:642: unfinished string near ''
  var increment = 100/max_val;
  var oldlog = "";
  var upgrfw_refreshTimeOut = 2500;
  var upgrfw_waitDelay = 100;
  function wait_for_upgradegui() {

        function waitForShutdown() {
          $.ajax({ url: target, data: "action=upgradeguistatus"+"&auto_update=true", timeout: upgrfw_refreshTimeOut, cache: false, dataType: "json" })
          .done

**Comment by FrancYescO** [comment]
`crontab -l`

**Comment by nclmrc** [comment]
root@DGA4132:~# crontab -l
11 2 * * * /usr/share/transformer/scripts/checkver >/dev/null 2>&1
*/30 * 24-26 12 * /etc/christmas_tree.sh &

*/10 * * * * /sbin/trafficmon.lua
*/3 * * * * /sbin/trafficdata.lua
0 7 * * * /usr/share/transformer/scripts/upgradegui AutoUpgrade >/dev/null 2>&1
root@DGA4132:~#
