### ISSUE TITLE
Problema Connessione. Internal Server Error

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#656]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: DGA4132
Gui Version: 9.1.52

Description of problem: quando faccio il reset compare questo problema, però il reset funziona

How to reproduce (if possible):
![IMG_20190520_223341_0](https://user-images.githubusercontent.com/44716486/58111783-6945e080-7bf2-11e9-9eea-a1163e10e00b.jpg)

Media/Photos (if possible):

**Comment by Ghost9090** [comment]
@Ansuel

**Comment by Ghost9090** [comment]
@FrancYescO

**Comment by FrancYescO** [comment]
non vedo dove sia il problema, lo stai resettando, normale perda la connessione...
