### ISSUE TITLE
transformer does not load xdsl mapper on boot

### ISSUE THREAD

**Issue by Kherby** [Ansuel/tch-nginx-gui#658]
Device Model: DGA4130, FW: 2.0.0
Gui Version: 9.1.53-dev

Description of problem:  After GUI upgrade (9.0.49-stable to 9.1.53-dev) I could see the correct informations but since the first reboot there are no more information/stats available. Another reboot couldn't fix the problem either so I think something is broken here.

How to reproduce (if possible): Reboot the device after GUI Upgrade and click on xDSL Config.

Media/Photos (if possible): https://imgur.com/IWAfWcW

**Comment by Kherby** [comment]
Workaround:  service transformer restart
https://github.com/Ansuel/tch-nginx-gui/issues/478#issuecomment-494765130
Hopefully this problem can be fixed in future GUI versions...

**Comment by Kherby** [comment]
@Ansuel 
Updated to 9.1.54 via "Check Update" and rebooted my modem afterwards.
Still the same problem with the xDSL Config Card and on top I can't access the "GUI Settings Card" anymore as It keep saying "Processing >> loading..." but nothing happens.
A downgrade to 9.1.53 fixed the problem with the GUI Settings Card.

**Comment by FrancYescO** [comment]
is this still valid?
