### ISSUE TITLE
ISP_Detected: Valore non valido

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#659]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: DGA4132
Gui Version: 9.1.53

Description of problem: dopo che modifico username e password su accesso a internet da questo errore però la modifica la salva

How to reproduce (if possible):

Media/Photos (if possible): 
![Cattura](https://user-images.githubusercontent.com/44716486/58204261-3d068e80-7cdc-11e9-8861-7a41b1f7acc1.PNG)

**Comment by Ghost9090** [comment]
@Ansuel

**Comment by Ansuel** [comment]
tranformer-cli get uci.modgui.

**Comment by lorenzocanale-LC** [comment]
Same error.
Output transformer-cli get uci.modgui.: 
uci.modgui.app.transmission_webui [string] = 0
uci.modgui.app.telstra_webui [string] = 0
uci.modgui.app.xupnp_app [string] = 0
uci.modgui.app.luci_webui [string] = 0
uci.modgui.app.blacklist_app [string] = 0
uci.modgui.app.amule_webui [string] = 0
uci.modgui.app.aria2_webui [string] = 0
uci.modgui.gui.gui_version [string] = 9.1.54
uci.modgui.gui.gui_hash [string] = 8f1bd7604b65e070633e66d14743cf2d
uci.modgui.gui.gui_skin [string] = green
uci.modgui.gui.outdated_ver [string] = 0
uci.modgui.gui.gui_animation [string] = 1
uci.modgui.gui.update_branch [string] = dev
uci.modgui.gui.autoupgrade_hour [string] = 0
uci.modgui.gui.autoupgradeview [string] = none
uci.modgui.gui.randomcolor [string] = 0
uci.modgui.gui.firstpage [string] = stats
uci.modgui.gui.new_ver [string] = Unknown
uci.modgui.gui.autoupgrade [string] = 0
uci.modgui.var.ppp_realm_ipv6 [string] = *******@alice6.it
uci.modgui.var.version_spoof_mode [string] = disabled
uci.modgui.var.encrypted_pass [string] = ******
uci.modgui.var.isp_autodetect [string] = 0
uci.modgui.var.ppp_mgmt [string] = 
uci.modgui.var.isp [string] = Other
uci.modgui.var.bank_check [string] = 1
uci.modgui.var.driver_version [string] = A2pvfbH043g
uci.modgui.var.ppp_realm_ipv4 [string] =
