### ISSUE TITLE
Barra laterale scorrimemto homepage

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#66]
Non vedo più la barra di scorrimento laterale

**Comment by Escart94** [comment]
Puoi indicare su quale skin impostata?

**Comment by nclmrc** [comment]
Fritx e dark sicuramente

**Comment by Escart94** [comment]
Che versione della GUI hai? Io vedo tutte le scrollbar su tutte le skin. 
Prova un refresh della cache del browser con CTRL+F5.

**Comment by nclmrc** [comment]
Ultima 8.1.6

**Comment by Escart94** [comment]
Il problema si verifica solo nel tuo caso, ti consiglio di effettuare altri test. 
(anche riapplicare la GUI manualmente)

**Comment by Ansuel** [comment]
@nclmrc hai per caso aggiornato il firmware?

puoi provare ad aggiornare la gui ?

**Comment by nclmrc** [comment]
No sempre 1.1.0. Provato.

**Comment by nclmrc** [comment]
Risolto
