### ISSUE TITLE
nsc wifi

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#660]
![immagine](https://user-images.githubusercontent.com/38593316/58325758-10ad5800-7e2b-11e9-93ab-e423528b6025.png)
questa funzionalità non mi funziona

Fri May 24 13:50:49 2019 daemon.info transformer[8675]: async run: /usr/share/transformer/scripts/check_ecoled.sh
Fri May 24 13:50:49 2019 daemon.info transformer[8675]: async run: /usr/share/transformer/scripts/restart_leds.sh
Fri May 24 13:50:49 2019 daemon.err insmod: module is already loaded - technicolor_led

**Comment by FrancYescO** [comment]
Specifica cosa fa... il led resta accceso anche senza client connesso con l'opzione messa ad off ?

**Comment by nclmrc** [comment]
Rimane spento anche con client connessi

**Comment by FrancYescO** [comment]
Sia 2.4 che 5? di che firmware e dispositivo stiamo parlando?

Posta un output di `ps x | grep led`

**Comment by nclmrc** [comment]
Entrambi.
root@DGA4132:~# ps | grep led
 1503 root      2532 S    {status-led-even} /usr/bin/lua /sbin/status-led-eventin
 1506 root      4144 S    {ledfw.lua} /usr/bin/lua /sbin/ledfw.lua
 8340 root      1964 S    lua /usr/bin/led-fw-interface.lua
14100 root      1720 S    grep led
root@DGA4132:~#

Ma dovrebbe funzionare anche con ecoled attivato

**Comment by FrancYescO** [comment]
No, se è attivo ecoled è giusto che stia spento (ammenocche non si preme il pulsante info per mostrare lo "stato completo")
________________________________

**Comment by nclmrc** [comment]
Ok ci provo.

**Comment by nclmrc** [comment]
Ho provato con nessun dispositivo sulla 2.4 e si accende lo stesso

**Comment by Ansuel** [comment]
@nclmrc ciao puoi riprovare con l'ultima dev?

**Comment by nclmrc** [comment]
ho riprovato, se attivato non succede niente
