### ISSUE TITLE
Support for iiNet/Technicolor TG789V3

### ISSUE THREAD

**Issue by nutterthanos** [Ansuel/tch-nginx-gui#663]
Would love to see support for this modem.
It looks like the same as the TG789V2 except it comes with a Broadcom 63138 (maybe)
And based on homeware 18.3.

**Comment by kevdagoat** [comment]
Pls give dd dump and logread of GUI installation

**Comment by nutterthanos** [comment]
Uh i don’t have that modem and its not mine.

**Comment by nutterthanos** [comment]
> Pls give dd dump and logread of GUI installation
> […](#)

How to do that?

**Comment by kevdagoat** [comment]
https://hack-technicolor.readthedocs.io/en/latest/Resources/#backuprestore-bit-for-bit

**Comment by nutterthanos** [comment]
Also i can’t do it today could try on weekend.

**Comment by kevdagoat** [comment]
Ok

**Comment by nutterthanos** [comment]
Also how much space does the GUI alone take up?

**Comment by FrancYescO** [comment]
Firmware download? Board name?

**Comment by nutterthanos** [comment]
No firmware to download and board name VBNT-1.

**Comment by FrancYescO** [comment]
I have one of this but I need a dump or better an RBI firmware to install, actually is on a 10.x version not based on openwrt

**Comment by nutterthanos** [comment]
How to do dump?

**Comment by kevdagoat** [comment]
*sigh*

https://hack-technicolor.readthedocs.io/en/latest/Resources/#backuprestore-bit-for-bit

**Comment by nutterthanos** [comment]
Sorry didn’t see you said about that already

**Comment by kevdagoat** [comment]
That’s ok 👍 just reminding

**Comment by nutterthanos** [comment]
Also I just bricked my second modem with the tg789v3 with red light then reboot 3 times then red status light flashes forever.

**Comment by kevdagoat** [comment]
TFTP flash time. Did it have the GUI installed??

**Comment by nutterthanos** [comment]
Nope the GUI was not installed and it was running kernel 4.1.38 sand it has about 18.7MB of free space for anything compared to a DJN2130 with about 90MB of space on bank 1.

**Comment by nutterthanos** [comment]
So maybe no support for it then?

**Comment by nutterthanos** [comment]
I wouldn’t keep my hopes up for this device considering that it has like only 18MB free space for anything.

**Comment by FrancYescO** [comment]
18mb are enough to have the custom gui working and some personalization (788 and 789vac V2 are pretty the same)

But an RBI or firmware dump (that I don't know if is possible to write from a 10.x firmware) is needed.

What's the complete firmware version?
________________________________

**Comment by Ansuel** [comment]
well as log as the 2 firmware have the same encryption key the can be installed as they are packed in the same way

**Comment by nutterthanos** [comment]
> What's the complete firmware version?

18.3.0157-3-2-1-CRF905

**Comment by kevdagoat** [comment]
You know where iinet stores their cwmp update firmware?

If you have another device, please run:

cat /etc/cwmpd.db

Should give you some hints

**Comment by nutterthanos** [comment]
No hints at all.

**Comment by kevdagoat** [comment]
Factory reset and redo until successful

**Comment by nutterthanos** [comment]
Does it normally appear in the file like 5 mins after first boot after factory reset?

**Comment by kevdagoat** [comment]
Only when it goes for a fw update.

**Comment by nutterthanos** [comment]
Does the infomation stored in it about a new version stay after the firmware update?

**Comment by kevdagoat** [comment]
No

**Comment by nutterthanos** [comment]
Well how do i pick up where it downloads the file from then?

**Comment by nutterthanos** [comment]
I’m adding a bank dump of the TG789V3 now.

**Comment by nutterthanos** [comment]
Is this gui supported on kernel 4.1.38 now?

**Comment by Ansuel** [comment]
Except for extension ( custom compiled opkg) it does work as it's based on new base 18.3

**Comment by FrancYescO** [comment]
@nutterthanos news for a dump/rbi firmware?

**Comment by kevdagoat** [comment]
@Francyesco https://github.com/kevdagoat/hack-technicolor/commit/d0e56be5bc62287b02369d1d8721346e9ec23f91

Sent from Mail for Windows 10

**Comment by nutterthanos** [comment]
Well the dump is there but no rbi firmware anywhere to be seen.

**Comment by nutterthanos** [comment]
@kevdagoat only bank 1 is there since the bank 2 folder in /overlay has changed to work.

**Comment by kevdagoat** [comment]
@nutterthanos bank one is fine?

**Comment by nutterthanos** [comment]
Well i would think yes since mtd dump is dumping from the rom with the squashfs filesystem not the actual bank which is the overlayfs partition with jffs2 filesystem.

**Comment by nutterthanos** [comment]
> bank one is fine?

Yes

**Comment by nutterthanos** [comment]
the OpenSSL packages that are on Ansuel/GUI-ipk are working fine on this device. But don’t know about luci yet will try the packages and use parts of the script from nutterpc/tg-luci.

**Comment by nutterthanos** [comment]
The iiNet TG789V3 got a updated firmware see http://mirror.internode.on.net/pub/internode-support/hardware/tg789/firmware/

**Comment by nutterthanos** [comment]
Any Progress in getting support for this Gateway?

**Comment by FrancYescO** [comment]
we just have to know whats wrong with actual installation...

how much free space after root? `df -h`

**Comment by nutterthanos** [comment]
you mean how much free space after root? df -h after install of GUI?

**Comment by nutterthanos** [comment]
[opkg.txt](https://github.com/Ansuel/tch-nginx-gui/files/4326856/opkg.txt)

**Comment by nutterthanos** [comment]
root@dsldevice:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                18.8M     18.8M         0 100% /rom
/dev/mtdblock2           31.1M      9.4M     21.7M  30% /overlay
overlay                  31.1M      9.4M     21.7M  30% /
root@dsldevice:~#

**Comment by FrancYescO** [comment]
> you mean how much free space after install of GUI?

so you already tried the installation? it's still not clear....

**Comment by nutterthanos** [comment]
> so you already tried the installation? it's still not clear....
i still have not tried to install it yet

**Comment by FrancYescO** [comment]
so you just have to try as it can just work as is.
make sure you have both banks bootable before installation

**Comment by nutterthanos** [comment]
find /proc/banktable -type f -print -exec cat {} ';'
/proc/banktable/active
bank_1
/proc/banktable/booted
bank_1
/proc/banktable/inactive
bank_2
/proc/banktable/bootedoid
5bf68e3acf98533425d8f181
/proc/banktable/notbooted
bank_2
/proc/banktable/notbootedoid
Unknown/proc/banktable/activeversion
18.3.0157-3141013-20181122120842-6303d86730b74ac4713ff0fe9bae10b656f96671
/proc/banktable/passiveversion 
Unknown

**Comment by nutterthanos** [comment]
Root Script: Installing in progress...
Root Script Start rooting
Root Script Setting root flag
Root Script Reset unlock bit
Root Script Save root password if modified
Root Script Setting & Enabling Dropbear SSH Server
Root Script Restarting Dropbear SSH Server
Root Script Executing /etc/modgui_scripts/01_prereq.sh
Root Script Disabling watchdog...
Root Script Checking Free RAM...
Root Script Executing /etc/modgui_scripts/02_specific.sh
Root Script Checking opkg feeds...
Root Script Executing /etc/modgui_scripts/03_various.sh
Root Script Enabling hardware serial console...
Root Script Fixing sysupgrade if needed...
Root Script Restoring and enabling few transformer mappers...
md5sum: can't open '/rom/usr/share/transformer/mappings/device2/Device.map': No such file or directory
md5sum: can't open '/usr/share/transformer/mappings/device2/Device.map': No such file or directory
Root Script Creating custom GUI utils symlinks...
Root Script Add checkversion to cron...
Root Script Executing /etc/modgui_scripts/04_config.sh
Root Script Check original config
Root Script Unlocking web interface if needed
Root Script Check if variant_friendly_name set
Root Script Remove https check
Root Script Check driver setting
Root Script Check Dropbear config file
Root Script Check eco paramaters
Root Script Create GUI type in config
Root Script Add new web options
Root Script New DHCPRelay Option
Root Script Suppressing wansensing logs
Root Script Create new option for led definitions
Root Script Creating and checking real version
Root Script Implementing WoL
Root Script Apply new xDSL options
Root Script Adding fast cache options
Root Script Checking if wan_mode option exists...
Root Script Checking DoSprotect kernel modules...
Root Script Enabling and starting DoSprotect service...
Root Script Checking mobiled libs...
Root Script Adding missing mobiled scripthelpers lib...
mv: can't rename '/tmp/scripthelpers.lua': No such file or directory
md5sum: can't open '/rom/etc/init.d/mobiled': No such file or directory
md5sum: can't open '/etc/init.d/mobiled': No such file or directory
Root Script Checking if intercept is enabled and disabling if it is...
Root Script Disabling coredump reboot...
Root Script Restoring nginx additional options if needed...
/etc/rc.common: /etc/modgui_scripts/04_config.sh: line 638: /rom/etc/uci-defaults/tch_0080-nginx: Permission denied
Root Script Adding missing voicednd rule if needed
Root Script Doing various checks and generating hashes...
Root Script Update branch detected: STABLE
Root Script: Detected low flash space device...
Root Script GUI hash set: f4d6992ba9f8d56ceacafe21b286361d
Root Script Resetting version info...
Root Script Decrypting any encrypted password present in config
Root Script Executing /etc/modgui_scripts/05_app.sh
Root Script Trafficmon inizialization
Root Script Move Aria2 dir
Root Script Reinstalling Telstra GUI if needed...
Root Script Executing /etc/modgui_scripts/06_network.sh
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
IspConfigHelper Restarting dnsmasq if needed...
Root Script Adding ipoe in network config...
Root Script Removing default loopback DNS Servers...
Root Script Purify WAN network config...
Root Script Fix DNS bug, make sure odhcp is enabled
Root Script Enabling odhcpd on boot
Root Script Checking and fixing dnsmasq daemon naming...
Root Script Sync DHCP configuration for new GUI
Root Script Attempt to clean the wansensing script from hardcoded interfaces...
Root Script Cleaning cups firewall rule...
Root Script Apply CVE 2019-11477 workaround
Root Script Checking atmdevice interface naming...
Root Script Restarting dnsmasq if needed...
Root Script Executing /etc/modgui_scripts/99_postreq.sh
Root Script Applying modifications
Root Script Resetting cwmp and watchdog
Root Script Process done.
Root Script Restarting transformer
Root Script Stopping nginx
Root Script Restarting nginx...
Root Script Restarting nginx...
Root Script Restarting nginx...
Root Script Restarting nginx...
Root Script Restarting nginx...

**Comment by FrancYescO** [comment]
Try renaming /etc/nginx/nginx.conf to /etc/nginx/ui_server.conf after install

**Comment by nutterthanos** [comment]
but i thought nginx.conf is needed

**Comment by nutterthanos** [comment]
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (2: No such file or directory)
lol of course

**Comment by nutterthanos** [comment]
this is a permalink to the include directive in nginx.conf
https://github.com/Ansuel/tch-nginx-gui/blob/ba81e28cf60c3eadc4d14458dbecedd9caa8029f/decompressed/gui_file/etc/nginx/nginx.conf#L62

**Comment by nutterthanos** [comment]
does someone here have that file by default on your modem?

**Comment by FrancYescO** [comment]
you can get it from /rom folder

**Comment by nutterthanos** [comment]
nope still does not exist

**Comment by nutterthanos** [comment]
you could even look at my bank dumps in repo nutterthanos/VBNT1 and it won't be there

**Comment by nutterthanos** [comment]
lol found it under /overlay/bank_2/etc/nginx/

**Comment by nutterthanos** [comment]
ok gui has loaded

**Comment by FrancYescO** [comment]
upload here that file, pretty strange that i have the same include and no ui_server.conf file but is just working

**Comment by nutterthanos** [comment]
lol github hates .conf
https://gofile.io/d/CkufZI

**Comment by nutterthanos** [comment]
i also got a newer firmware on bank_2 but can't seem to login at all with ssh as root

**Comment by FrancYescO** [comment]
18.3.0442 is here https://github.com/FrancYescO/tch_firmware_extracted/tree/vbnt-1_18.3.0442-ver3.4.1-CRF981-3141011

**Comment by nutterthanos** [comment]
lol free memory is 5MB

**Comment by nutterthanos** [comment]
oh you also extracted it

**Comment by FrancYescO** [comment]
are you using stable 9.5.38?

**Comment by nutterthanos** [comment]
i'll also provide debug zip
https://gofile.io/d/lOwJX8

**Comment by nutterthanos** [comment]
lol led stats are broken
https://gyazo.com/45229dc78345655117826a1b68a646f6

**Comment by FrancYescO** [comment]
hmm why? internet led is not blinking?

**Comment by nutterthanos** [comment]
lol no

**Comment by nutterthanos** [comment]
also iptv is no existent on this modem and why does broadband say NETDEV? and some other leds?

**Comment by FrancYescO** [comment]
netdev means that the led will follow network activity from some interface, probably is just blinking too fast and the GUI is just updating slower
there is a led called iptv, probably unused
i see nothing wrong in this page

if you used the GUI to update to the latest firmware there was probably a bug that have not setted correctly the password to root, this is probably already fixed in the dev version, but pay attention that starting from version 9.5.60 we autoapply optimal bank planning: booted bank will be moved to bank2 and bank1 erased and used as overlay

we should have to just understand better why you have issues whit ui_server.conf file

**Comment by nutterthanos** [comment]
well i used sysupgrade over ssh

**Comment by FrancYescO** [comment]
if you want give a try to the dev version, first make sure you have no /proc/rip/0122 or /proc/rip/0123 file, than update to dev version, reboot if asked, than update the firmware.

if anything goes wrong but you have installed latest dev, use tftp to restore, ad you should are on OBP https://hack-technicolor.readthedocs.io/en/latest/Recovery/#recovering-gateways-on-optimal-bank-plan

**Comment by nutterthanos** [comment]
well would have the gui install nuked the newer firmware that i installed on bank_2?

**Comment by FrancYescO** [comment]
if you are on bank1, and you install the dev GUI all will be moved to bank2 after a reboot.

if you have /proc/rip/0122 or /proc/rip/0123 you must take care of your rooting status as if you mess this up you will have no downgrade possibility after installing the latest firmware.

**Comment by nutterthanos** [comment]
nope both /proc/rip/0122 /proc/rip/0123 are not there which is good

**Comment by nutterthanos** [comment]
yep i just installed dev version

**Comment by nutterthanos** [comment]
welp i think something went wrong but don't have access to gateway

**Comment by nutterthanos** [comment]
dev version broke something

**Comment by FrancYescO** [comment]
So what happened after the reboot?

**Comment by nutterthanos** [comment]
well i think it might have started bootlooping?

**Comment by FrancYescO** [comment]
Does it go in TFTP mode after sometime or just bootloop non-stop?
Does it reboot 3 time fast (3xfailboot) after turning on?

after checking these things try using the reset button at different times, if is still not came alive use TFTP to restore the firmware

**Comment by nutterthanos** [comment]
never mind it just bugged itself but still works

**Comment by nutterthanos** [comment]
now what still runs dev version 9.5.80

**Comment by FrancYescO** [comment]
```
uci set web.usr_admin.srp_verifier='27d5cc49530f8f1821f01cf7605b61645124e190e13e1defd6295d5160c0421ce0750c4b9324fb1a45ea805c94a0785f4ee9b15b7791bdda55c96536f684c246d845890627330ad4d689802057abfbc0db2d707e61f241a194369185a2d1d87127da527526359f991a62c31090d7541f24bab25e21880c53136241e3c9c552c53cdf66b8526262472b61cb5f21a227cbc64f7b7f7c7d0dda4b9214de024522a113acf5c6b33499f80e91474ffc4be2e351e32e178cb68fedefe2edee7d1f53078aa02e78760b89b50204b30a66d89e5aad3edce03e6a8eb4a36690d2614f05365d09a805222c33feabeae3f32c044745c68b1cd70adfebdb1b54e5b6efdc798d'
uci set web.usr_admin.srp_salt='cbee79d6'
uci commit web
```
should set password to admin.

so it's ok to close this issue?

**Comment by nutterthanos** [comment]
Maybe?

**Comment by nutterthanos** [comment]
@FrancYescO it did not set password to admin

**Comment by nutterthanos** [comment]
![image](https://user-images.githubusercontent.com/50470661/97669718-a6471f80-1ad4-11eb-9919-564e8ddbd985.png)

**Comment by nutterthanos** [comment]
this is my current df -h 
![image](https://user-images.githubusercontent.com/50470661/97670168-967c0b00-1ad5-11eb-944f-6174c7b23520.png)

**Comment by FrancYescO** [comment]
Looks good, have you installed latest GUI version?

**Comment by nutterthanos** [comment]
yes

**Comment by nutterthanos** [comment]
Actually i can't install luci at  all because it uses a script from this https://github.com/nutterpc/tg-luci which installs packages that don't work on the cpu in this gateway

**Comment by FrancYescO** [comment]
it is arm? check if the DGA install is okay

**Comment by nutterthanos** [comment]
yes its arm

**Comment by FrancYescO** [comment]
basically, for arm you can use dga install, mips 789.

unfortunately there is no way to know that is working if no1 test it :D

actually with last dev version, in the wrost case a TFTP install is enought to restore the gateway

**Comment by nutterthanos** [comment]
well i have no wan connection

**Comment by FrancYescO** [comment]
You do not have an ethernet cable with internet?

Just set broadband to ethernet and internet to DHCP .. sharing the pc wifi Is just adding more difficulty, but should be also possible with a little of googling..

**Comment by nutterthanos** [comment]
well no home internet

**Comment by nutterthanos** [comment]
well when i connect ethernet cable between wan port on gateway and lan port on laptop green wan light comes on but not internet light

**Comment by FrancYescO** [comment]
post a debug tar and possibly your /etc/config/network file.

are you able to open internet card?

this is an example on how to share internet connection to another network card https://www.tomshardware.com/how-to/share-internet-connection-windows-ethernet-wi-fi

but you should use the wan port of the modem, and allow both internet connection and a way to access the modem GUI is a bit tricky, problably you can achive this setting the bridge mode in internet card, but we should first fix the not opening of the broadband card: please open new issue for this with attached what ive asked for.

**Comment by nutterthanos** [comment]
Current discusion is in #1001

**Comment by nutterthanos** [comment]
yes i can open internet card

**Comment by nutterthanos** [comment]
weirdly enough i have red status light
