### ISSUE TITLE
Problem static route outside gateway ip

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#664]
Quando inserisco una rotta statica mi escono gli errori:
"impossibile usare l'indirizzo di rete"
"l'ip non appartiene alla stessa subnet del gateway"

**Comment by FrancYescO** [comment]
Posta un esempio di quello che stai inserendo

**Comment by nclmrc** [comment]
10.8.0.0/24 192.168.1.1

**Comment by Ansuel** [comment]
@nclmrc ciao puoi postarmi uno screen ?

**Comment by nclmrc** [comment]
![Screenshot_20190705-233127_Chrome](https://user-images.githubusercontent.com/38593316/60746045-20b56d00-9f7d-11e9-812a-b1eea928b0b1.jpg)

**Comment by nclmrc** [comment]
@Ansuel ti ho messo lo screenshot

**Comment by Ansuel** [comment]
@nclmrc considera che è errato scrivere 10.8.0.0 ma andrebbe scritto 10.8.0.0/24

**Comment by nclmrc** [comment]
La barra 24, la specifichi con la subbet mask, la logica è quella dell' ip route di cisco

**Comment by Ansuel** [comment]
si quindi non devi scrivere solo l'ip ma anche la subnet

**Comment by nclmrc** [comment]
Avevo fatto così io

Inviato da Samsung Galaxy Note 8

Il Dom 7 Lug 2019, 17:12 Ansuel Smith <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
vedendo dallo screen è sbagliato comunque fammi sapere se funziona che so curioso

**Comment by nclmrc** [comment]
Funziona adesso, io comunque in precedenza le avevo importate con il file network
