### ISSUE TITLE
Nome utente o password non validi

### ISSUE THREAD

**Issue by maurotella** [Ansuel/tch-nginx-gui#665]
Alla pagina di acceso mi chiede ovviamente user e password. Qualsiasi cosa inserisco mi dice non validi. Naturalmente ho già provato con quella di default 'admin' : codice sul retro del router, 'root':'root' ma niente. Ho già provato (varie volte) a resettare ma niente.

**Comment by kevdagoat** [comment]
admin:admin

**Comment by Ansuel** [comment]
@maurotella quindi???

**Comment by maurotella** [comment]
Scusate, mi sono dimenticato di rispondere!
Comunque admin:admin funziona grazie!
