### ISSUE TITLE
Can release be made based on a different criteria ?

### ISSUE THREAD

**Issue by Dark4Codrutz** [Ansuel/tch-nginx-gui#667]
Not an issue but more of an concerning question:
Is it really necessary to build a new release with every single commit ?

**Comment by Ansuel** [comment]
Well they are pre release so... No actual release but I can set that only stable release are pushed this way...

**Comment by nutterthanos** [comment]
Also in case something goes wrong with the commit or file change or anything it is easier to fix or something I think.
