### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#679]
Device Model: DGA4131
Gui Version: 9.1.96

Description of problem: The browser doesn't do anything when "save" is clicked, the router log shows nothing, while the browser console report the error attached
Media/Photos (if possible):
<img width="1440" alt="Schermata 2019-07-02 alle 12 43 01" src="https://user-images.githubusercontent.com/44505255/60506825-081c2d00-9cc7-11e9-8319-baee9af78020.png">

**Comment by Ansuel** [comment]
where is this problem?

**Comment by lorenzocanale-LC** [comment]
Eco card

**Comment by lorenzocanale-LC** [comment]
Actually every card is giving me this problem

**Comment by Ansuel** [comment]
reset cache that function doesn't exist in the js

**Comment by lorenzocanale-LC** [comment]
I reseted the cache and I'm still having problem, trying another browser doesn't work either 
<img width="1440" alt="Schermata 2019-07-02 alle 13 07 37" src="https://user-images.githubusercontent.com/44505255/60508317-89c18a00-9cca-11e9-9127-62beae6c7afd.png">

**Comment by Ansuel** [comment]
i fixed this yesterday but i never pushed the fix... i feel so stupid...

**Comment by lorenzocanale-LC** [comment]
Ehm... now I can't even open the cards 😂
<img width="1440" alt="Schermata 2019-07-02 alle 13 29 24" src="https://user-images.githubusercontent.com/44505255/60509693-e1152980-9ccd-11e9-8bd7-ae4948eb2bd6.png">
<img width="1440" alt="Schermata 2019-07-02 alle 13 29 39" src="https://user-images.githubusercontent.com/44505255/60509694-e1152980-9ccd-11e9-9161-9ab7fda2789c.png">
