### ISSUE TITLE
tx_power_adjust: Invalid value

### ISSUE THREAD

**Issue by Melix19** [Ansuel/tch-nginx-gui#686]
Device Model: DGA4132 TIM
Gui Version: 9.2.7 dev

Description of problem:
pressing save inside 5Ghz Wi-Fi popup produces an error saying "tx_power_adjust: Invalid value".

Media/Photos:
![image](https://user-images.githubusercontent.com/23530586/60539625-708dfd00-9d0d-11e9-8d7c-0bcc89a7fd46.png)

**Comment by kevdagoat** [comment]
Hmmm interesting.

I just added this feature to the GUI.

**Comment by FrancYescO** [comment]
Confirmed, only happens with values <0dBm.

**Comment by kevdagoat** [comment]
Must be because your modems don’t support tx below 0dbm

**Comment by FrancYescO** [comment]
Nope, the issue is in the validator that accept only positive numbers.
________________________________

**Comment by kevdagoat** [comment]
Hmm, interesting.

On Telstra modems, you can set anywhere between +6dBm and -30dBm

(limited by hardware)

**Comment by Ansuel** [comment]
should be good now?
