### ISSUE TITLE
Broadband card doesn't show stats in bridge mode

### ISSUE THREAD

**Issue by denosys** [Ansuel/tch-nginx-gui#688]
Device Model: DGA4132 / VBNT-S
Gui Version: 9.0.49 stable

Description of problem: The broadband card doesn't show any statistics about the line like down/up speed, attenuation, power, snr and so on when the modem is configured in bridge mode.

**Comment by kevdagoat** [comment]
Please use latest DEV and report back

**Comment by FrancYescO** [comment]
in broadband mode set connection type (and not bridge) than in internet modal select bridge, than should be okay,
