### ISSUE TITLE
Two "WAN-Port LAN Mode" problems

### ISSUE THREAD

**Issue by meyergru** [Ansuel/tch-nginx-gui#69]
There is this setting in "Local Network" card:

![grafik](https://user-images.githubusercontent.com/17402664/42410219-4c5b90e8-81e6-11e8-905c-d7146259f9df.png)

Presumably, this should make eth4 (SFP) a normal LAN port. It apparently affects the config setting **uci.ethernet.globals.eth4lanwanmode**. However, what is does **not** do is change this section in /etc/config/network:

```
config interface 'sfp'
        option proto 'static'
        option ifname 'eth4'
        option ipaddr '192.168.2.2'
        option netmask '255.255.255.0'
```

That has two implications:

1. eth4 always has the IP 192.168.2.2 and the bridging seems unchanged, too. I wonder how the eth4 port can be part of the LAN that way. **uci.ethernet.globals.eth4lanwanmode** does a lot of things, but probably not what it was intended to do.

2. I thought that enabling that setting would be also a remedy to the problem that 192.168.2.0/24 can never be chosen for the LAN ip range in that it would remove the IP adress from that interface, but it is not for the reasons given above.

**Comment by Ansuel** [comment]
so what you suggest to do? 

i need to change eth4 and add it to the lan bridge but what about the ipaddr i should add an exception to the lan modal to automatically change the ipaddr of the sfp part automatically...

**Comment by meyergru** [comment]
I think it should be like this:

- with WAN-Port mode off, the IP assignment should be removed and the port must be added to the bridge
- with WAN-Port mode on, an IP must obviously be assigned and eth4 must be removed from the LAN bridge.

Thus, any IP address range could be used unless WAN-Port LAN Mode is on. However, switching back could be difficult if 192.168.2.0/24 has been assigned to the LAN while LAN Mode was off. That could only be fixed by choosing a free IP range automatically (say, 192.168.(X+1).0/24 if 192.168.X.0/24 is used by LAN.

**Comment by Ansuel** [comment]
Can you test the new stable? 
i should have fixed this 2 problems...

**Comment by meyergru** [comment]
Woa. Something bad happened... I tried 8.6.23 via manual upgrade. The bar went all the way to the right but then the GUI did no reappear as usual.

The modem was offline (i.e. not pingable) and stays like that after a reboot. I it not reachable via the IP I had assigned to it nor via 192.168.1.1. I can see the firewall messages via the serial console.

I have not managed to do a factory reset by using the little reset hole - pressed >= 30 seconds, nothing happened.

I even reflashed 1.1.0 by pressing reset. Afterwars, the GUI comes up (I can see the Ansuel Logo in the serial console), but no network connectivity. It seems like the br-lan is configured to no adress at all.

**Comment by Ansuel** [comment]
FK .... can you menage to take the network config?

**Comment by meyergru** [comment]
The only thing I can do is log the whole booting process and append it here - but I do not see which IP range is assigned there.

[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/2197990/log.txt)

Is there a special way to do a factory reset with the DGA4132?

**Comment by meyergru** [comment]
What I found interesting was this log entry:

```
[   57.257000] dosprotect rpfilter drop IN=br-lan OUT= MAC= SRC=192.168.10.29 DST=224.0.0.22 LEN=48 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2 MARK=0x9800
```

Because the SRC address is the IP that was assigned to the modem. It looks like the firewall eats its own packets.

**Comment by Ansuel** [comment]
to reset with system loaded push for 7 second the reset button and release

**Comment by meyergru** [comment]
Ah, so not 30 seconds?

**Comment by Ansuel** [comment]
that ip addres should be the sfptag new interface

**Comment by Ansuel** [comment]
7 second and release wait some time and it should autoreboot....

something in serial console should appear...

**Comment by meyergru** [comment]
I think that the factory reset has taken place - the WiFi LEDs are on now (and I disabled both WiFis before). Now, the modem is reachable via 192.168.1.1 again.

The GUI is "503 Service Temporarily Unavailable", I can login via SSH.

Should I reinstall the GUI?

**Comment by Ansuel** [comment]
ummm yes...   anyway keep the wifi enabled...

so we cans till access the modem with it :)  

Think we need to make some test to track down what went wrong...

**Comment by meyergru** [comment]
Maybe it would be nice if the rootdevice script would show the network config on the console - that would bother nobody but provide a nice way to see what the result of any modifications is? I just added that manually.

And now I see what went wrong: the sfptag interface is assigned 192.168.10.1/24. So there was a collision with my home IP range.

**Comment by Ansuel** [comment]
owww!
 so that was the problem...

then i should add a check for that...

i found in the script some documentation about the sfp interface and i found that you can create it in 2 way...


sfp and sfptag 

sfptag use 192.168.10.1 as ip and i changed it to workaround the problem of the local modem...

think i need to find a better way for this...

**Comment by meyergru** [comment]
Yup, that's a problem: We need disjoint IP ranges for WAN, LAN and SFP but have to make sure that they do not collide with networks in use. The only way I can see fit is to have a default assignment first and let the user decide on any of these...

**Comment by Ansuel** [comment]
think i will solve this problem this way...

move sfp to sfptag (and check if that ip is not used... if it is, allocate the ip +1 ) 

then on the lan card show some alert or just create an entities to set the sfp local ip...

**Comment by meyergru** [comment]
Yes, but the problem was not with the manual config anyway - I cannot choose 192.168.10.29 as the validation sees the collision. The problem in my case was that the GUI upgrade made the same mods and did not see the collision.

**Comment by Escart94** [comment]
The problem is what OpenWRT will assign the IP anyway, without considering If isn't used.
So this isn't a good possibilty honestly...I think that the best way to bypass this problem is to switch It to SFPTag and check If the 192.168.10.1/24 class is already used.

**Comment by meyergru** [comment]
I see - with most other Linux variants, you can have an interface named but leave out the IP address and netmask, for example, when you need the interface for bridging only.

I now understand that there is no "proto 'none'" in OpenWRT, so that giving an ipaddr seems mandatory - but you could use an IPv6 instead. For example, the FE80 LL address would work. But choosing a subsequent free IPv4 range is fine and follows the same pattern I initially suggested.

**Comment by Ansuel** [comment]
can you test this dev?

i added a check to the sfp conversion and also in the lan card i added an option to actually set the local ip of the sfp interface...

**Comment by Ansuel** [comment]
Use ipv6 address would be very good... but the sfp scripts comunicate with the sfp module with telnet and because of this use ipv6 is not possible...  (i don't think telnet support ipv6...)

**Comment by meyergru** [comment]
Works. Just one small glitch: When I changed the status of the "WAN-Port LAN-Modus" from off to on, I got an error saying that the SFP port IP must not be in the SFP range. Probably because this effectively tries to set the SFP IP address to itself while the only changed item was another one.

**Comment by Ansuel** [comment]
ok thx...

**Comment by Ansuel** [comment]
@meyergru can you tell me the exact message?

**Comment by meyergru** [comment]
SFP IP should not be in sfptag IP Range

But it must be modular, as "IP Range" is translated to "IP Bereich" on my machine.

**Comment by Ansuel** [comment]
try now

**Comment by meyergru** [comment]
8.6.30 still hash that behavior. You can easily try it: Switch the WAN port mode to the other value of what it was and try to save. Then the validation fails. I think it is because you check the SFP IP against ANY other interface IP, including itself.

**Comment by Ansuel** [comment]
i can't test cause i don't have tim hub and i don't have also any modem ahahha

**Comment by meyergru** [comment]
😲

**Comment by Ansuel** [comment]
anyway this version now should be good...

**Comment by meyergru** [comment]
+1

**Comment by meyergru** [comment]
Ups... I just found that turning LAN mode off does not change /etc/config/network at all? How can it be associated/disassociated from the bridge, then? What am I missing?

**Comment by Ansuel** [comment]
Can you check sfptag interface in the network file? It should move eth4 from there to the lan bridge

**Comment by meyergru** [comment]
As I said: I toggled the setting back and forth and the /etc/config/network did not change one bit. Both say always:

```
config interface 'sfptag'
        option proto 'static'
        option ifname 'eth4'
        option netmask '255.255.255.0'
        option ipaddr '192.168.111.2'
```

That only changes when I alter the IP address.

**Comment by Ansuel** [comment]
so when you change ip addr (and the switch is on)  eth4 goes to br-lan right?

**Comment by meyergru** [comment]
No, only the IP changes. ifname stays the same.

**Comment by meyergru** [comment]
Retested with 8.6.55: Still no change on button toggle.

**Comment by Ansuel** [comment]
check with this latest version

**Comment by meyergru** [comment]
Still no change. Toggling the setting does not change the sfptag section.

**Comment by Ansuel** [comment]
Can you check the ethernet config?

**Comment by meyergru** [comment]
How? Anything apart from /etc/config/network?

**Comment by Ansuel** [comment]
The ethernet config file

**Comment by meyergru** [comment]
Yup, that changes eth4lanwanmode from 0 to 1 and back:

```
config globals 'globals'
        option eth4lanwanmode '0'
```

```
config globals 'globals'
        option eth4lanwanmode '1'
```

**Comment by Ansuel** [comment]
Also if possible give me the log after the switch 
It should execute a script...

**Comment by meyergru** [comment]
I get this:

```
Jul 29 11:46:21 | daemon.err | transformer[26780] | async exec of '/etc/init.d/ethernet  reload ; /usr/share/tranformer/scripts/check_wan.sh' failed exit code=127
-- | -- | -- | --
Jul 29 11:46:19 | kern.warn | kernel | [1102636.516000] Cross Bar MUX Config : Internal Port 02 maps to External Port 00 <reg_val : 0x00000012>
Jul 29 11:46:19 | kern.warn | kernel | [1102636.507000] Cross Bar MUX Config : Internal Port 01 maps to External Port 02 <reg_val : 0x00000012>
Jul 29 11:46:19 | kern.warn | kernel | [1102636.497000] Cross Bar MUX Config : Internal Port 00 maps to External Port 02 <reg_val : 0x0000000a>
Jul 29 11:46:19 | kern.warn | kernel | [1102636.490000] Unused MUX Internal Port#1 connects to Crossbar External Port#2
Jul 29 11:46:19 | kern.warn | kernel | [1102636.483000] Unused MUX Internal Port#0 connects to Crossbar External Port#2
```

**Comment by Ansuel** [comment]
Fixed

**Comment by pianoquintet** [comment]
Hi, I have been posting on this issue in the ilpuntotecnico forum but the discussion here seems to be specifically focussed on what I am trying to solve, so here you go:

I own a DGA4132, with rooted firmware 1.2.0 and Ansuel's latest stable GUI, connected to a TIM FTTH network through an SFP module.  The GUI shows the Broadband Connection as "down" or "unknown" even though it is up and working fine, and the GUI keeps feezing for 60 seconds at every refresh of the general page. I have determined that the reason is that the modem is unable to communicate with the SFP over telnet, as it expects to do, and freezes until the 60s timout is reached.  The reason I suspect it cannot communicate over telnet with the SFP is that no interface exists that has assigned to it the purported IP address of 192.168.10.1.

Below is the output of ifconfig:

`bcmsw     Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:412877 errors:0 dropped:0 overruns:0 frame:0
          TX packets:464799 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:116189672 (110.8 MiB)  TX bytes:137724182 (131.3 MiB)
          Base address:0xffff

br-lan    Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          inet addr:192.168.30.1  Bcast:192.168.30.255  Mask:255.255.255.0
          inet6 addr: fe80::a691:b1ff:fea7:3490/64 Scope:Link
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:955391 errors:0 dropped:0 overruns:0 frame:0
          TX packets:981563 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:525984273 (501.6 MiB)  TX bytes:616985780 (588.4 MiB)

eth0      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:653887 errors:0 dropped:9 overruns:0 frame:0
          TX packets:694477 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:453042788 (432.0 MiB)  TX bytes:523162916 (498.9 MiB)


eth1      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:524903 errors:0 dropped:0 overruns:0 frame:0
          TX packets:538666 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:183634501 (175.1 MiB)  TX bytes:188939537 (180.1 MiB)


eth2      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:22256 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29274 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4041833 (3.8 MiB)  TX bytes:8962424 (8.5 MiB)


eth3      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1155 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14465 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:207317 (202.4 KiB)  TX bytes:5488939 (5.2 MiB)


eth4      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:739218 errors:0 dropped:0 overruns:0 frame:0
          TX packets:710139 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:577545390 (550.7 MiB)  TX bytes:490590483 (467.8 MiB)

eth5      Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:33706 errors:0 dropped:10 overruns:0 frame:0
          TX packets:40208 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4465972 (4.2 MiB)  TX bytes:21237704 (20.2 MiB)


lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:215 errors:0 dropped:0 overruns:0 frame:0
          TX packets:215 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:18613 (18.1 KiB)  TX bytes:18613 (18.1 KiB)

pppoe-wan Link encap:Point-to-Point Protocol
          inet addr:95.237.XXX.XXX  P-t-P:192.168.100.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:733004 errors:0 dropped:0 overruns:0 frame:0
          TX packets:683738 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3
          RX bytes:556144019 (530.3 MiB)  TX bytes:462449143 (441.0 MiB)

waneth4   Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          inet6 addr: fe80::a691:b1ff:fea7:3490/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:26671 errors:0 dropped:0 overruns:0 frame:0
          TX packets:38813 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:7478086 (7.1 MiB)  TX bytes:9366684 (8.9 MiB)

wl0       Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          inet6 addr: fe80::a691:b1ff:fea7:3491/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13869 errors:0 dropped:0 overruns:0 frame:20417
          TX packets:25721 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2331080 (2.2 MiB)  TX bytes:12856227 (12.2 MiB)
          Interrupt:92

wl0_1     Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          inet addr:192.168.168.1  Bcast:192.168.168.127  Mask:255.255.255.128
          inet6 addr: fe80::a491:b1ff:fea7:3492/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10241 errors:0 dropped:28 overruns:0 frame:20417
          TX packets:13868 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1469962 (1.4 MiB)  TX bytes:11850441 (11.3 MiB)

wl1_1     Link encap:Ethernet  HWaddr XX.XX.XX.XX.XX.XX
          inet addr:192.168.168.129  Bcast:192.168.168.255  Mask:255.255.255.128
          inet6 addr: fe80::a691:b1ff:fea7:3490/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:478 (478.0 B)`

Below is also the content of /etc/config/network:

`config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'none'
        option default_ps '0'

config device 'waneth4'
        option type '8021q'
        option name 'waneth4'
        option macaddr 'XX.XX.XX.XX.XX.XX'
        option ifname 'eth4'
        option vid '835'
        option ipv6 '1'

config device 'wanptm0'
        option type '8021q'
        option name 'wanptm0'
        option macaddr 'XX.XX.XX.XX.XX.XX'
        option ifname 'ptm0'
        option vid '835'
        option ipv6 '1'

config interface 'wan'
        option auto '1'
        option proto 'pppoe'
        option demand '0'
        option username 'CP1839XXXXXXXXXXXXXX@00000.agcombo.unica'
        option password 'alicenewag'
        option macaddr 'XX.XX.XX.XX.XX.XX'
        option peerdns '1'
        option reqopts '1 3 6 15 33 42 51 121 249'
        option keepalive_adaptive '0'
        option dns_metric '0'
        option ifname 'waneth4'
        option ipv6 '1'

config config 'config'
        option wan_mode 'pppoe'

config interface 'wwan'
        option auto '1'
        option proto 'mobiled'
        option session_id '0'
        option profile '1'

config interface 'wan6'
        option proto 'dhcpv6'
        option reqopts '12 21 22 23 24 25 31 56 64 67 82 83'
        option noslaaconly '1'
        option iface_464xlat '0'
        option dns_metric '20'
        option ifname '@wan_ipv6'
        option auto '1'

config interface 'sfptag'
        option proto 'static'
        option netmask '255.255.255.0'
        option ipaddr '192.168.10.1'

config interface 'lan'
        option type 'bridge'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '64'
        option force_link '0'
        option pppoerelay '<set by script>'
        option ipaddr '192.168.30.1'
        option ifname 'eth0 eth1 eth2 eth3 eth4 eth5'
        option ipv6 '1'

config switch 'bcmsw'
        option reset '1'
        option enable_vlan '0'
        option qosimppauseenable '0'
        option jumbo '0'

config interface 'wlnet_b_24'
        option proto 'static'
        option ip6assign '64'
        option ip6hint '1'
        option netmask '255.255.255.128'
        option ipaddr '192.168.168.1'
        option ifname 'wl0_1'
        option force_link '0'
        option name XXXXXXXXXX-27735185'
        option ipv6 '1'

config interface 'wlnet_b_5'
        option proto 'static'
        option ip6assign '64'
        option ip6hint '2'
        option netmask '255.255.255.128'
        option ipaddr '192.168.168.129'
        option ifname 'wl1_1'
        option force_link '0'
        option name XXXXXXX-27735185'
        option ipv6 '1'

config device 'wlnet_b_5eth5'
        option type '8021q'
        option name 'wl1_1'
        option enabled '1'
        option ifname 'eth5'
        option vid '3'
        option ipv6 '1'

config interface 'public_lan'
        option ifname '@lan'
        option proto 'static'
        option ipaddr '0.0.0.0'
        option netmask '0.0.0.0'
        option auto '0'
        option disabled_info 'proto=static,ip=0.0.0.0,mask=255.255.255.248'
        option ipv6 '1'

config interface 'wan_ipv6'
        option auto '0'
        option proto 'pppoe'
        option demand '0'
        option password 'IPV6@alice6'
        option macaddr 'XX.XX.XX.XX.XX.XX'
        option ipv6 '1'
        option peerdns '1'
        option keepalive_adaptive '0'
        option dns_metric '0'
        option ifname 'wanptm0'
        option username 'CP1839XXXXXXXXXX@alice6.it'
        option metric '10'

config interface 'ipoe'
        option proto 'dhcp'
        option metric '1'
        option reqopts '1 3 6 43 51 58 59'
        option release '1'
        option neighreachabletime '1200000'
        option neighgcstaletime '2400'
        option ipv6 '1'

config route '499C3B5XXXXXXXXXXXXXXXXXXX’
        option gateway '192.168.30.131'
        option metric '1'
        option target '10.9.1.0'
        option netmask '255.255.255.0'
        option interface 'lan'

config route '268D60F6XXXXXXXXXXXXXXXXXXXX’'
        option interface 'lan'
        option netmask '255.255.255.0'
        option gateway '192.168.30.131'
        option target '10.8.5.0'
        option metric '1'

config route '74BE19320A6XXXXXXXXXXXXXXXX'
        option interface 'lan'
        option target '10.8.2.0'
        option netmask '255.255.255.0'
        option metric '1'
        option gateway '192.168.30.131'

config route '2DE16850DXXXXXXXXXXXXXXXXXXXX'
        option target '192.168.1.0'
        option metric '1'
        option interface 'lan'
        option gateway '192.168.30.131'
        option netmask '255.255.255.0'

config route 'AA088892XXXXXXXXXXXXXXXXXXXX'
        option netmask '255.255.255.0'
        option gateway '192.168.30.131'
        option metric '1'
        option target '192.168.70.0'
        option interface 'lan'

config route 'EAC5A96XXXXXXXXXXXXXXXX'
        option gateway '192.168.30.131'
        option netmask '255.255.255.0'
        option metric '1'
        option target '192.168.50.0'
        option interface 'lan'

config route '84440989DXXXXXXXXXXXXXX'
        option gateway '192.168.30.131'
        option netmask '255.255.255.0'
        option target '192.168.254.0'
        option metric '1'
        option interface 'lan'`

I suspect this situation may be due to some misconfiguration of the bridging.  I am posting the current configuation, which comes as the default after a factory reset of the modem: [https://ibb.co/x24kRH8](url).

If I attempt to edit it I am given these choices, among which eth5, which is currently selected, does not even appear: [https://ibb.co/hKX8j3g](url)

Any leads would be much appreciated. 

Thank you.
