### ISSUE TITLE
File corrupted

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#691]
File corrupted, aggiornamento da 9.2.13 a 9.2.16
![Screenshot_20190703-193136_Chrome](https://user-images.githubusercontent.com/44716486/60612640-63364880-9dc9-11e9-80f9-63bb7b43ffbb.jpg)

@Ansuel

**Comment by nclmrc** [comment]
Comfermo

**Comment by nclmrc** [comment]
Se caricato manualmente funziona.
