### ISSUE TITLE
dev build - Compatibility with TIM HUB firmware 2.1.xxx

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#693]
The latest dev build are fully compatible with TIM HUB firmware 2.1.xxx?

Then if the dev build are fully compatible with firmware 2.1.xxx can I update from firmware 2.0.xxx to 2.1.xxx?

**Comment by Ansuel** [comment]
no you need to wait for stable as on upgrade only the stable package is saved

**Comment by bovirus** [comment]
I wrote this because someone on Hardware Upgrade forum use firmware 2.1.xxx and I need this confirm.

**Comment by FrancYescO** [comment]
all builds >9.0.16 are compatible (do not cause bootloop) with firmwares >=2.1.0 (that are still beta..)

actually upgrading a device with Custom GUI already installed is not possible (will cause bootloop)

it should be possible if:
- first install of the custom GUI was made directly with a version >9.0.16
- a factory reset is done during firmware upgrade

**Comment by bovirus** [comment]
@FrancYescO 
When you report

actually upgrading a device with Custom GUI already installed is not possible (will cause bootloop)

it means

actually upgrading a device with Custom GUI **_(version lower than 9.10.16)_** already installed is not possible (will cause bootloop)

then using a firmware update (2.1.xx) from Custom GUI to avoid bootloop the user should select a reset option after firmware update?

**Comment by FrancYescO** [comment]
No, all depends with what version the **first install** of Custom GUI was made, if was installed offline or online, and the **current stable version** no matter what version is currently installed... a little too complicated to explain

Actually the safest way to updagrade actually should be:
factory reset > install latest custom gui dev version offline > install 2.1.0 firmware with factory reset > install lastest dev custom gui

**Comment by SamuelePilleri** [comment]
Provided that 9.2 has made it to stable, is it safe to upgrade now? What procedures are known not to cause a bootloop? Also, just to avoid compatibility issues, which firmware version are you using in dev? Thank you.

**Comment by FrancYescO** [comment]
Upgrade is safe once a new stable version is out.

details in my previous comments.

**Comment by Ansuel** [comment]
If you have installed the new stable you can upgrade safely to new firmware 

Dev is based on 2.1.0_005

**Comment by SamuelePilleri** [comment]
Ok, I've tried to upgrade the GUI (and only the GUI, firmware version is stil 2.0.1) and this is what I get when I try to access the cards page.

![Cards](https://user-images.githubusercontent.com/13276940/61174934-8f12b480-a5a7-11e9-8ae4-c21e108ab23a.png)

Already tried to selectively restart nginx and transformer, as well as rebooting the router. Any suggestion? Should I open a separate issue?

**Comment by FrancYescO** [comment]
Try issuing `upgradegui` from ssh

**Comment by SamuelePilleri** [comment]
That fixed it, thank you.

**Comment by marxx6** [comment]
@FrancYescO i'm not currently able to flash any fw version < 2.1.0 . When trying to flash e.g. 1.0.3 (i tried even others) the modem downloads the file and then reboots immediately. Pressing and releasing the reset switch while booting didn't make any effort at the moment. Any idea?

**Comment by FrancYescO** [comment]
that's pretty strange the TFTP flashing should be ever possible, the alternative is to try [failboot method](https://hack-technicolor.readthedocs.io/en/stable/Recovery/#crazy-power-switching) and hope the inactive bank is able to boot

btw the important thing is were you got the GUI package as the one on ilpuntotecnico repository is old and incompatible with latest firmwares...

**Comment by marxx6** [comment]
I've used this one: https://github.com/Ansuel/gui-dev-build-auto/blob/master/GUI.tar.bz2

Tried again a few times. Flash of 2.2.0 works, any previous version not.

**Comment by marxx6** [comment]
@FrancYescO I have soldered the serial interface. On Bank 1 the modem runs in a kernel panic. On Bank 2 gets online for a few seconds than says "rebooting device" (or something like that) and reboots. 
When trying to flash via TFTP i get

```
Entering BOOT-P mode (reason: BUTTON_PUSH )                         
BOOTP Reply received
Local IP:        192.168.1.4
BOOTP Server IP: 192.168.1.64
TFTP Server IP:  192.168.1.64
Filename:        AGTHP_1.1.2_CLOSED.rbi
TFTP started
*** 26392 kB received ***
TFTP finished
BLI is incompatible with this platform
Resetting the gateway
```

anything I can try to save the router?

**Comment by FrancYescO** [comment]
start it in bank2 than use AFG to send it (as fast as possible once go online) an `mtd erase rootfs_data `

**Comment by marxx66** [comment]
I tried setting a static IP address to my laptop and booting the router on Bank 2 two times and both times the router wasn't online enough to be reachable at 192.168.1.1 . Attached bootlog (i let it run for a while)
[DGA4132_bootlog.txt](https://github.com/Ansuel/tch-nginx-gui/files/3635904/DGA4132_bootlog.txt)

**Comment by FrancYescO** [comment]
the router is doing a complete boot when the bootloader starts the `SW Version          : 17.3.c.0349-8041022-20190110095504` your only way to recover this device is to send ASAP when SSH or WebUI is reachable before it reboots the erase command as said in https://github.com/Ansuel/tch-nginx-gui/issues/693#issuecomment-531393379

**Comment by marxx66** [comment]
Even after the bridge is set up the router won't become reachable. 
```
ssh: connect to host 192.168.1.1 port 22: No route to host
```
My computer has a fixed address and the interface is up.

**Comment by marxx66** [comment]
@FrancYescO i tried connecting to the wireless instead of the wired network. Here the router becomes reachable for a few seconds but when trying to ssh i get
```
$ ssh root@192.168.1.1 mtd erase rootfs_data 
ssh: connect to host 192.168.1.1 port 22: Connection refused
```

even the webgui won't become available

**Comment by FrancYescO** [comment]
have you tried to see if the web interface become avaiable at least for a little time? in this case AFG can help you to send the commands tricking the webui

another try is to press the reset button to trigger a reset (oviusly ever when booting in bank2, the kernel panic in bank1 will give no chance) keep an eye to the serial interface to know the right moment to press the reset button 

ah and also... keep pressing enter while on serial, there is the possibility that you can use the shell via console

**Comment by marxx66** [comment]
@FrancYescO thanks a lot! I finally did it. The way was to boot on bank 2, press the reset button, wait "/overlay/bank_2 marked to be reset to factory default" (or something like that) and then rebooting another time in failboot on bank 2. The bank is reset and the modem works again.

Thank you so much!

**Comment by FrancYescO** [comment]
if the modem is booting in bank2 be sure to delete /overlay/bank_1 (or install the GUI while in bank2 that will copy all in bank1) otherwise you still have the hidden kernel panic under bank1
