### ISSUE TITLE
Upgradegui

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#694]
Upgrade Script: Downloading GUI file...
Upgrade Script: ERROR: File corrupted!!!
Upgrade Script: ERROR: Removing upgrade file and aborting.
root@DGA4132:~#

**Comment by kevdagoat** [comment]
Most likely due to mismatched checksum. 

Please run the install commands again and it should fix the issue

**Comment by nclmrc** [comment]
ok
