### ISSUE TITLE
Da Gui 9.2.14 non si riesce ad aggiornare alle versioni successive 

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#697]
Device Model:  DGA4132
Gui Version: 9.2.14

Da Gui 9.2.14 non si riesce ad aggiornare alle versioni successive ( credo che siamo alla 9.2.31 ) e facendo "Forza aggiornamento" rimane sulla scritta "Requested"

Se eseguo "upgradegui" da ssh, ho questo messaggio d'errore ed esce subito al prompt  :  

**/usr/sbin/upgradegui: line 352: syntax error: unexpected end of file (expecting "fi")**

**Comment by Ansuel** [comment]
devi aver avuto proprio fortuna a beccare l'unica versione buggata stata su per 3 minuti :////

comunque aggiorna manualmente come si stessi facendo lo sblocco la prima volta

**Comment by giulio63** [comment]
cioè ? non con **upgradegui**  da ssh ? perchè così non và

**Comment by Ansuel** [comment]
perchè è esattamente quello script che è rotto in quella versione

**Comment by giulio63** [comment]
con quale comando si può aggiornare manualmente nella mia situazione ? grazie

**Comment by Ansuel** [comment]
Ti ho già scritto come fare..  leggi su

Il Gio 4 Lug 2019, 19:18 giulio63 <notifications@github.com> ha scritto:

**Comment by Ansuel** [comment]
@giulio63 risolto ?

**Comment by giulio63** [comment]
dopo aver scaricato l'ultima versione della gui, ed averla messa nella directory /tmp ho usato il comando **bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force**
ed ho potuto aggiornare alla 9.2.32
grazie !
