### ISSUE TITLE
5GHz Output Power displayed wrong

### ISSUE THREAD

**Issue by towatai** [Ansuel/tch-nginx-gui#699]
Device Model: DGA4132 / FW 2.0.1
Gui Version: 9.2.32

5GHz output power value is always displayed on -6dBm after saving, closing AND open the wireless menu again.
in the /etc/config/wireless menu, the previously set value has been saved correctly.
A reboot didn't help.

[DebugHelper2019-07-04-2331.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3360538/DebugHelper2019-07-04-2331.tar.gz)

**Comment by kevdagoat** [comment]
Try clearing browser cache.

If not, run:

transformer-cli get rpc.wireless.radio.radio_5G.tx_power_adjust

(Untested command but it may not work)

**Comment by towatai** [comment]
Clearing my browser cache doesn´t work and the command gives me a "invalid path rpc.wireless.radio.radio_5G."
the 2,4GHz Slider works fine. it´s only @ the 5GHz Slider that displays the wrong value when you reload the 5GHz Menu.

**Comment by kevdagoat** [comment]
Try replacing radio_5G with radio_2G and rerun

It appears that the method for setting tx power is only for the 2g radio as all of the 5g paths are hard coded

**Comment by towatai** [comment]
looks like this. at least the 2,4GHz network is changeable and therefore an enrichment :-) THANKS for your help

**Comment by Ansuel** [comment]
looks like hostapd (the program that setup wifi) delete the uci entities... Probably a limitation of the quantenna driver
