### ISSUE TITLE
Errore statistiche dsl

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#702]
Le statistiche non sono veritiere essendo i valori del giorno più alti di quelli del trimestre. 
![Screenshot_20190705-151637_Chrome](https://user-images.githubusercontent.com/38593316/60724981-32285600-9f38-11e9-81a4-8c257c07315a.jpg)

**Comment by Ansuel** [comment]
purtroppo non ci possiamo fare molto... è roba buggata broadcom
