### ISSUE TITLE
Pianificazione Wireless GUI Anteprima 9.2.37

### ISSUE THREAD

**Issue by yhcim86** [Ansuel/tch-nginx-gui#703]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: 
Gui Version: 9.2.37 AGTEF 4130 TIM VDSL 200/20 TIM

Description of problem: Non si riesce a programmare lo spegnimento del wifi nella relativa tab, dice: Si è verificato un errore interno del server.
Contatta l´amministratore

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by Ansuel** [comment]
mi serve l'errore da logread  o ancora meglio un debug report

**Comment by yhcim86** [comment]
Ansuel ciao ora sono al mare domattina ti posto tutto ma mi dici come fare con i comandi che mi hai dato e dove te li devo uppare??? 
Hai una mail così te li invio lì?
Poi vorrei chiederti una cortesia fuori da questo problema.
Grazie mille

**Comment by Ansuel** [comment]
Cards >> System Extras >> Debug Report ti scarica uno zip e lo trascini qua

email: ansuelsmth@gmail.com

**Comment by yhcim86** [comment]
Se ti lascio l'indirizzo dinamico ci accedi e poi lo scarichi automaticamente perché da browser di Android non me lo fa scaricare lo zip.
Se ti va bene alla tua mail mando i dati di accesso per il mio modem.
Grazie mille

**Comment by yhcim86** [comment]
Ti ho mandato una mail con quello che mi hai chiesto.
Mia mail: yhcim86@hotmail.com
Grazie mille fammi sapere

**Comment by Ansuel** [comment]
attendo riscontro

**Comment by yhcim86** [comment]
Ok problema risolto ora c'è la pianificazione del WiFi ottimo grazie mille
