### ISSUE TITLE
File corrupted

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#704]
Upgrade Script: Downloading GUI file...
Upgrade Script: ERROR: File corrupted!!!
Upgrade Script: ERROR: Removing upgrade file and aborting.
root@DGA4132:~#

**Comment by giulio63** [comment]
ho visto che se si sceglie nella tab "Impostazioni GUI" il canale "Anteprima" invece di "Sviluppatore" l'aggiornamento non da' errore, mentre rimanendo sulla "Sviluppatore" va' in errore in ogni modo ( forza aggiornamento, upgradegui da ssh)
