### ISSUE TITLE
Error while saving changes Wifi

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#705]
Device Model: DGA4131
Gui Version: 9.2.37

Description of problem: When trying to change from off to on "Bypass Reg Domain Power Rule"  the card reports "Error while saving changes". 
Logread reports:  ```Sat Jul  6 09:27:33 2019 daemon.err nginx: 2019/07/06 09:27:32 [error] 4541#0: *27 [lua] post_helper.lua:154: handleQuery(): setObject failed on rpc.wireless.radio.@radio_5G.tx_power_overrule_reg: 9008 tx_power_overrule_reg is not writable, client: 192.168.3.2, server: localhost, request: "POST /modals/wireless-modal.lp?radio=radio_5G&iface=wl1 HTTP/1.1", host: "192.168.3.1", referrer: 
"http://192.168.3.1/cards.lp"```

**Comment by kevdagoat** [comment]
Sigh, looks like this functionality will be removed in a future version because of the errors it has caused.

It appears that the transformer path is not writable on your modem

**Comment by towatai** [comment]
as already noted in my bugreport by kev it looks like the 5GHz is incompatible with this settings and they are unchangeable. 2,4GHz instead works like a Charm :-) IF, THEN please only remove the relevant points from the 5GHz WLAN.

**Comment by lorenzocanale-LC** [comment]
Actually my 5GHz is compatible. The output power switch can be modified and it works, only the tx_power_overrule_reg cannot be modified in the gui, but it can be modified on the config file.
