### ISSUE TITLE
Unable to set DMZ host address

### ISSUE THREAD

**Issue by laterizi** [Ansuel/tch-nginx-gui#706]
Device Model: DGA ( DGA4132 )
Software version: AGTHP_2.1.0_005
Gui Version: 9.2.39

Description of problem:
In the card "WAN services", tab "DMZ", isn't possible to set the DMZ IP host address. When insert the IP address or when select the suggested IP, in the "Destination IP" field appear the selected address. After pressing the "Save" button, the IP address disappear. In the facts, the DMZ doesn't work.

How to reproduce (if possible):
 - go to card "WAN services"
 - select "DMZ"
 - write the desired IP address in "Destination IP"
 - Enable the DMZ
 - Click the "Save" button
 - the IP address disappear from "Destination IP" field
 - test the DMZ, doesn't work

![0001](https://user-images.githubusercontent.com/52614292/60762930-e5dd3300-a069-11e9-886b-1e0456be252f.PNG)
![0002](https://user-images.githubusercontent.com/52614292/60762894-3b651000-a069-11e9-97cc-d5e6a29ce674.PNG)
[DebugHelper2019-07-07-0325.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3365208/DebugHelper2019-07-07-0325.tar.gz)

**Comment by kevdagoat** [comment]
Could you please post /etc/config/firewall?

**Comment by laterizi** [comment]
Ok, thank you for the answer. The requested firewall file is attached to this message.

[firewall.zip](https://github.com/Ansuel/tch-nginx-gui/files/3365530/firewall.zip)

**Comment by kevdagoat** [comment]
It appears that the firewall rule is there but no IP has been defined.

**Comment by laterizi** [comment]
Exact! This Is the problem. In the GUI, in the "Destination IP" field, i set the desired IP address, but the config file isn't updated. I suppose Is a bug of card.
