### ISSUE TITLE
Unable to set 5GHz guest network SSID

### ISSUE THREAD

**Issue by laterizi** [Ansuel/tch-nginx-gui#707]
Device Model: DGA ( DGA4132 )
Software version: AGTHP_2.1.0_005
Gui Version: 9.2.39

Description of problem: in the card "wireless", select the 5GHz network SSID and attempt to modify the SSID name. When press "Save" button, the GUI release the error "Some parameters failed validation tx_power_adjust: Invalid value.". Refreshing the page, the SSID is unchanged.

How to reproduce (if possible):
 - go to "Wireless" card
 - select the guest 5GHz SSID
 - change the SSID in the "Network Name (SSID)" field
 - click to "Save" button
 - the GUI release the error ""Some parameters failed validation tx_power_adjust: Invalid value."
 - go to home page
 - go to "Wireless" card
 - check the guest 5GHz SSID, isn't changed 

[DebugHelper2019-07-07-0325.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3365214/DebugHelper2019-07-07-0325.tar.gz)

**Comment by kevdagoat** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/699

**Comment by laterizi** [comment]
Hi kevdagoat, thank you for your answer.
I've read the linked post, but i haven't find a valid solution to my problem. Can you explain this, please?

Thanks in advance!
