### ISSUE TITLE
DynDNS: error "ERROR : Exact path not found!"

### ISSUE THREAD

**Issue by laterizi** [Ansuel/tch-nginx-gui#709]
Device Model: DGA ( DGA4132 )
Software version: AGTHP_2.1.0_005
Gui Version: 9.2.42

Description of problem: In my configuration there is a noip.com account activated for one host to manage to solve the address.
All seems to work properly, but in the card "WAN services", in "DynDNS" tab, appear an error "ERROR : Exact path not found!".

Media/Photos (if possible):
![Cattura](https://user-images.githubusercontent.com/52614292/60769486-a4cc3980-a0d0-11e9-9a69-364b1a35c984.PNG)

[DebugHelper2019-07-07-1601.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3365704/DebugHelper2019-07-07-1601.tar.gz)

**Comment by Ansuel** [comment]
you are 100% NOT on gui  9.2.42  that page doesn't exist...

**Comment by laterizi** [comment]
Ok, from posted DebugHelper:

___________________________________DEVICE INFO_________________________________________
Product Name: DGA
Friendly Name: DGA4132
ISP Name: TIM
FW Version: AGTHP_2.1.0_005
DSL Version: A2pvfbH043k
GUI Skin: green
GUI Version: 9.2.42
GUI Hash: f73f4eebd0c372d9ab117114c7598ddc
GUI Branch: dev
GUI First Page: stats
GUI Random Colour disabled
-----List of Installed Extensions-----
--------------------------------------

**Comment by Ansuel** [comment]
yes redo the update

**Comment by laterizi** [comment]
Ok, problem solved: another update make by WinSCP seems to correct the issue, but is still present the #707 bug.
