### ISSUE TITLE
DLNA

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#71]
In my network, I don't see the DLNA server of DGA4132

**Comment by Escart94** [comment]
Have you done the 8.4.1 GUI update? 
Which firmware are you using?

**Comment by nclmrc** [comment]
Yes. I have 1.1.0

Il Sab 14 Lug 2018, 11:18 Escart94 <notifications@github.com> ha scritto:

**Comment by nclmrc** [comment]
Now work. I dont update firmware

**Comment by Escart94** [comment]
Thanks for your feedback, I'm closing the issue.
