### ISSUE TITLE
Custom DNS not working

### ISSUE THREAD

**Issue by hereCOMESlappy** [Ansuel/tch-nginx-gui#711]
Device Model:  MediaAccess TG789MYRvac v2 HP
Gui Version: 9.0.49

Description of problem:
The device is using the DNS from my ISP. But if I try and enter Cloudflare DNS 1.1.1.1 it does not work when I run the diagnostic test it says that the first DNS is failing and the second on (my ISP one) works.

How to reproduce (if possible):
Add Cloudflare DNS 1.1.1.1 as a DNS server

If I set the DNS on the clients locally so on MacBook or iPhones, it can use 1.1.1.1 as DNS just fine. It is only the gateway that is not liking 1.1.1.1 to be used.

**Comment by kevdagoat** [comment]
Please update to latest dev

**Comment by hereCOMESlappy** [comment]
Fixed in 9.2.59 Stable and 9.2.60 Dev
