### ISSUE TITLE
No Device Image

### ISSUE THREAD

**Issue by hereCOMESlappy** [Ansuel/tch-nginx-gui#712]
Device Model: TG789vac MY
Gui Version: 9.2.60 (Dev)

Description of problem: Image of device is missing and 'Time of Day' card is messed up

How to reproduce (if possible):

Media/Photos (if possible):

<img width="239" alt="image" src="https://user-images.githubusercontent.com/44932282/60958757-3d212300-a34a-11e9-923c-c78f11e5a7a5.png">
<img width="267" alt="image" src="https://user-images.githubusercontent.com/44932282/60958796-52964d00-a34a-11e9-9222-80492f1b0e3d.png">

**Comment by hereCOMESlappy** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/44932282/60959024-c9cbe100-a34a-11e9-895a-602a74363325.png">
Also Internet Access always has a on/off toggle switch that is always off even when my internet is on and it won't turn on

**Comment by kevdagoat** [comment]
Please run:
```
uci get env.var.prod_friendly_name
```
And post

Sent from Mail for Windows 10

From: Lappy
Sent: Wednesday, 10 July 2019 5:38 PM
To: Ansuel/tch-nginx-gui
Cc: Subscribed
Subject: [Ansuel/tch-nginx-gui] No Device Image (#712)

Device Model: TG789vac MY
Gui Version: 9.2.60 (Dev)
Description of problem: Image of device is missing and 'Time of Day' card is messed up
How to reproduce (if possible):
Media/Photos (if possible):

**Comment by hereCOMESlappy** [comment]
Hello result is:

MediaAccess TG789MYRvac v2 HP
