### ISSUE TITLE
Internal server error at SIP configuration

### ISSUE THREAD

**Issue by technicoloruser** [Ansuel/tch-nginx-gui#713]
[DebugHelper2019-07-10-2134.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3379141/DebugHelper2019-07-10-2134.tar.gz)

Device Model: DGA4132
Gui Version: 9.2.60

Description of problem: When I try to add a SIP network entry, an "Interal Server Error" is displayed.

How to reproduce (if possible): Add a SIP network and press the add button

Media/Photos (if possible):
![grafik](https://user-images.githubusercontent.com/52760011/60999170-ca6c7380-a35a-11e9-87b3-7922bc5d09db.png)

relevant log output:
Wed Jul 10 21:28:04 2019 daemon.err transformer: Set failed on mmpbxrvsipnet.voiceA9AFF84EE82AC5A2C105C4D899A4D122.nil = network: nil
Wed Jul 10 21:28:05 2019 daemon.err nginx: 2019/07/10 21:28:04 [error] 20606#0: *122 lua entry thread aborted: runtime error: [string "/modals/mmpbx-global-modal.lp"]:239: attempt to concatenate local 'tempindex' (a nil value)
stack traceback:
coroutine 0:
        [string "/modals/mmpbx-global-modal.lp"]:239: in function 'onAdd'
        /usr/lib/lua/web/post_helper.lua:635: in function 'handleTableQuery'
        [string "/modals/mmpbx-global-modal.lp"]:283: in function 'content'
        /usr/lib/lua/web/web.lua:264: in function 'proc

**Comment by Ansuel** [comment]
Can you post your mmpbxrvsipnet config file ?

**Comment by technicoloruser** [comment]
I followed the configuration guide from: https://www.onlinekosten.de/forum/showthread.php?p=2418800#post2418800

config mmpbxrvsipnet 'global'
	option trace_level '2'
	option radvision_trace_level '0'

config syslog 'syslog'
	option registration '1'
	option call_signalling '1'
	option syslog_priority '6'
	option hide_user_identity '0'
	option log_sip_message '0'

config network 'sip_net'
	option user_friendly_name 'SIP network'
	option cac '-1'
	option transparent_soc_transmission '0'
	option interface 'wan'
	option local_port '5060'
	option domain_name 'tel.t-online.de'
	option primary_registrar_port '5060'
	option secondary_proxy_port '0'
	option transport_type 'UDP'
	option escape_hash '1'
	option escape_star '0'
	option control_qos_field 'dscp'
	option control_qos_value '40'
	option realtime_qos_field 'dscp'
	option realtime_qos_value '40'
	option from_anonymous_handling 'withheld'
	option sip_over_ipv6 '0'
	option rtp_local_port_min '16384'
	option rtp_local_port_max '32767'
	option user_param_value 'phone'
	option include_sip_instance '1'
	option waiting_time_for_registration_on_400_or_503_respon se '60'
	option hide_serial_number '1'
	option use_domain_in_contact '0'
	option use_domain_in_via '0'
	option update_support '1'
	option sdp_direction_attribute_media_level_only '1'
	option stick_to_outbound_proxy '1'
	option registration_delay '5'
	option enable_re_register_on_cancel_timeout '1'
	option rport_in_via '1'
	option optimized_authentication '1'
	option repeat_ringing_interval '0'
	option re_register_on_403 '0'
	option check_ttl_for_dns_record '1'
	option dns_query_timeout '5000'
	option sip_message_max_size '4096'
	option switch_back_to_primary_proxy_timer '0'
	option conference_release_call_after_transfer '0'
	option disconnect_on_bye_response '1'
	option cancel_invite_timer '64000'
	option dnd_response '486'
	option early_media_detection '0'
	option hide_userinfo_and_port_in_subscription_request '0'
	option user_agent 'Technicolor / VBNT-S / AGTHP_1.0.3 / AGTHP_1.0.3'
	option primary_registrar 'tel.t-online.de'
	option primary_proxy_port '5060'
	option primary_proxy 'tel.t-online.de'

config profile 'sip_profile_0'
	option network 'sip_net'
	option user_name '03514207063'
	option uri '03514207063'
	option display_name '03514207063'
	option password '14334180'
	option enabled '1'

config profile 'sip_profile_1'
	option network 'sip_net'
	option enabled '0'
	option password 'line1'
	option user_name 'line1'
	option uri 'line1'

config profile 'sip_profile_2'
	option network 'sip_net'
	option enabled '0'
	option password 'line2'
	option user_name 'line2'
	option uri 'line2'

**Comment by technicoloruser** [comment]
I followed the configuration guide from: https://www.onlinekosten.de/forum/showthread.php?p=2418800#post2418800

config mmpbxrvsipnet 'global'
	option trace_level '2'
	option radvision_trace_level '0'

config syslog 'syslog'
	option registration '1'
	option call_signalling '1'
	option syslog_priority '6'
	option hide_user_identity '0'
	option log_sip_message '0'

config network 'sip_net'
	option user_friendly_name 'SIP network'
	option cac '-1'
	option transparent_soc_transmission '0'
	option interface 'wan'
	option local_port '5060'
	option domain_name 'tel.t-online.de'
	option primary_registrar_port '5060'
	option secondary_proxy_port '0'
	option transport_type 'UDP'
	option escape_hash '1'
	option escape_star '0'
	option control_qos_field 'dscp'
	option control_qos_value '40'
	option realtime_qos_field 'dscp'
	option realtime_qos_value '40'
	option from_anonymous_handling 'withheld'
	option sip_over_ipv6 '0'
	option rtp_local_port_min '16384'
	option rtp_local_port_max '32767'
	option user_param_value 'phone'
	option include_sip_instance '1'
	option waiting_time_for_registration_on_400_or_503_respon se '60'
	option hide_serial_number '1'
	option use_domain_in_contact '0'
	option use_domain_in_via '0'
	option update_support '1'
	option sdp_direction_attribute_media_level_only '1'
	option stick_to_outbound_proxy '1'
	option registration_delay '5'
	option enable_re_register_on_cancel_timeout '1'
	option rport_in_via '1'
	option optimized_authentication '1'
	option repeat_ringing_interval '0'
	option re_register_on_403 '0'
	option check_ttl_for_dns_record '1'
	option dns_query_timeout '5000'
	option sip_message_max_size '4096'
	option switch_back_to_primary_proxy_timer '0'
	option conference_release_call_after_transfer '0'
	option disconnect_on_bye_response '1'
	option cancel_invite_timer '64000'
	option dnd_response '486'
	option early_media_detection '0'
	option hide_userinfo_and_port_in_subscription_request '0'
	option user_agent 'Technicolor / VBNT-S / AGTHP_1.0.3 / AGTHP_1.0.3'
	option primary_registrar 'tel.t-online.de'
	option primary_proxy_port '5060'
	option primary_proxy 'tel.t-online.de'

config profile 'sip_profile_0'
	option network 'sip_net'
	option user_name '*******'
	option uri '*******'
	option display_name '*******'
	option password '*******'
	option enabled '1'

config profile 'sip_profile_1'
	option network 'sip_net'
	option enabled '0'
	option password 'line1'
	option user_name 'line1'
	option uri 'line1'

config profile 'sip_profile_2'
	option network 'sip_net'
	option enabled '0'
	option password 'line2'
	option user_name 'line2'
	option uri 'line2'

**Comment by Ansuel** [comment]
@technicoloruser ok you have an error in the config file

line 35

you have 

option waiting_time_for_registration_on_400_or_503_respon se '60'

IT MUST BE

option waiting_time_for_registration_on_400_or_503_response '60'

also i have registred with your number sorry... about it will delete the info

**Comment by technicoloruser** [comment]
I should have looked at the copied config more thoroughly. Thanks for you help and sorry for wasting our time.
