### ISSUE TITLE
isp_detected: Invalid value

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#714]
Tiscali 16.3 789vac GUI Version 9.2.67
![image](https://user-images.githubusercontent.com/4574593/61013470-03b8d980-a383-11e9-802e-948a165c155f.png)

When saving on internet modal

**Comment by nutterthanos** [comment]
Well why does the image have the isp dectected when it has the error?

**Comment by kevdagoat** [comment]
@nutterthanos Most likely defaulting to that ISP

**Comment by nutterthanos** [comment]
@kevdagoat well lucky it did otherwise you would have to manually set the isp.

**Comment by kevdagoat** [comment]
Hahaha yeah

Sent from Mail for Windows 10

**Comment by nutterthanos** [comment]
It’s trying to read it using uci.modgui.var.isp.

**Comment by kevdagoat** [comment]
Interesting...
@FrancYescO Could you run:
```
transformer-cli get uci.modgui.var.isp
```

**Comment by nutterthanos** [comment]
Oh it was wrong in the internet-modal.lp

**Comment by kevdagoat** [comment]
Hahaha
