### ISSUE TITLE
led spenti dopo upgrade a 2.1.0

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#717]
Device Model: dga4132
Gui Version:9.2.80

Description of problem:led spenti
Dopo aver aggiornato alla gui stabile 9.2.56 ho eseguito l'aggiornamento del firmware all 2.0.1.005
ed e' andato tutto bene, se non reinserire la password di default, dopodiche ho aggiornato la gui alla 9.2.80 e tutti i led si sono spenti.
Ho spento ed acceso di nuovo il router ma i led sono tutti off, e il led eco disabilitato.

Media/Photos (if possible):
![Schermata del 2019-07-14 12-41-27](https://user-images.githubusercontent.com/43514633/61182540-f3c82080-a634-11e9-95e6-9e12fb9a09e9.png)
![Schermata del 2019-07-14 12-41-46](https://user-images.githubusercontent.com/43514633/61182543-fa569800-a634-11e9-88c2-ef1d39b82019.png)

**Comment by FrancYescO** [comment]
esegui `/usr/share/transformer/scripts/restart_leds.sh` ... succede qualcosa?

**Comment by dga4130-renato** [comment]
niente
root@modemtim:~# /usr/share/transformer/scripts/restart_leds.sh
killall: ledfw.lua: no process killed
root@modemtim:~# 

led spenti

**Comment by dga4130-renato** [comment]
Ho fatto il downgrade alla stabile ma non ha fatto differenza .

**Comment by dga4130-renato** [comment]
Leds_test.sh li accende tutti.

**Comment by lorenzocanale-LC** [comment]
Prova questo comando e dopo riavvia
`cp /rom/usr/lib/lua/ledframework/ubus.lua /usr/lib/lua/ledframework/ubus.lua`
L'unico file che cambia tra stable e dev riguardo i led nel DGA4132 dovrebbe essere questo

**Comment by dga4130-renato** [comment]
oot@modemtim:~# cp /rom/usr/lib/lua/ledframework/ubus.lua /usr/lib/lua/ledframe
work/ubus.lua
cp: can't stat '/rom/usr/lib/lua/ledframework/ubus.lua': No such file or directory
root@modemtim:~#

**Comment by FrancYescO** [comment]
esegui `/sbin/status-led-eventing.lua ` appaiono errori ?

**Comment by dga4130-renato** [comment]
no. si blocca li fino a ctrl+c

**Comment by FrancYescO** [comment]
/etc/init.d/ledfw restart

**Comment by dga4130-renato** [comment]
/etc/init.d/ledfw restart
avevo gia provato anche questo... poco fa'

**Comment by FrancYescO** [comment]
non succede niente dopo il restart?

**Comment by dga4130-renato** [comment]
root@modemtim:~# /usr/share/transformer/scripts/restart_leds.sh
killall: ledfw.lua: no process killed

**Comment by dga4130-renato** [comment]
sempre spenti. 
strano perche' con led test si accendono e poi se rilanci qualsiasi restart stanno spenti

**Comment by FrancYescO** [comment]
prova ad eseguire ledfw.lua

**Comment by dga4130-renato** [comment]
root@modemtim:~# ledfw.lua
/usr/bin/lua: /usr/lib/lua/ledframework/ubus.lua:4: module 'syslog' not found:
	no field package.preload['syslog']
	no file './syslog.lua'
	no file '/usr/share/lua/syslog.lua'
	no file '/usr/share/lua/syslog/init.lua'
	no file '/usr/lib/lua/syslog.lua'
	no file '/usr/lib/lua/syslog/init.lua'
	no file './syslog.so'
	no file '/usr/lib/lua/syslog.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/ledframework/ubus.lua:4: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/ledframework/init.lua:5: in main chunk
	[C]: in function 'require'
	/sbin/ledfw.lua:4: in main chunk
	[C]: ?
root@modemtim:~#

**Comment by dga4130-renato** [comment]
Il bello che l'ho fatto su due modem diversi ed il risultato e' stato lo stesso su entrambi, quindi non un caso.

**Comment by FrancYescO** [comment]
posta qui il file `/sbin/ledfw.lua`

dopo prova ad eseguire `cp /rom/sbin/ledfw.lua /sbin/ledfw.lua` e vedi se si aggiusta il restart

**Comment by dga4130-renato** [comment]
root@modemtim:~# cat /sbin/ledfw.lua
#!/usr/bin/lua
local setmetatable,assert,pcall,setfenv,loadfile = setmetatable,assert,pcall,setfenv,loadfile

local lf = require('ledframework')
local helper = require('ledframework.ledhelper')

-- load and run a script in the provided environment
-- returns the modified environment table
function run(scriptfile)
    local env = setmetatable({}, {__index=helper})
    assert(pcall(setfenv(assert(loadfile(scriptfile)), env)))
    setmetatable(env, nil)
    return env.stateMachines, env.patterns
end

local ledconfig, patternconfig = run('/etc/ledfw/stateMachines.lua')

lf.start(ledconfig, patternconfig)

root@modemtim:~#

**Comment by dga4130-renato** [comment]
cp /rom/sbin/ledfw.lua /sbin/ledfw.lua
cp: '/rom/sbin/ledfw.lua' and '/sbin/ledfw.lua' are the same file

**Comment by lorenzocanale-LC** [comment]
Visto che nel firmware 2.1.0 non è presente io proverei 
`rm /usr/lib/lua/ledframework/ubus.lua`

**Comment by dga4130-renato** [comment]
o al limite un rename ?

**Comment by dga4130-renato** [comment]
ops. copia e incolla ho cancellato
e ora ?

**Comment by lorenzocanale-LC** [comment]
/usr/share/transformer/scripts/restart_leds.sh

**Comment by dga4130-renato** [comment]
root@modemtim:~# /usr/share/transformer/scripts/restart_leds.sh
killall: ledfw.lua: no process killed
root@modemtim:~#

**Comment by lorenzocanale-LC** [comment]
Se provi adesso a fare ledfw.lua che dice?

**Comment by dga4130-renato** [comment]
root@modemtim:~#  ledfw.lua
/usr/bin/lua: /usr/lib/lua/ledframework/init.lua:5: module 'ledframework.ubus' not found:
	no field package.preload['ledframework.ubus']
	no file './ledframework/ubus.lua'
	no file '/usr/share/lua/ledframework/ubus.lua'
	no file '/usr/share/lua/ledframework/ubus/init.lua'
	no file '/usr/lib/lua/ledframework/ubus.lua'
	no file '/usr/lib/lua/ledframework/ubus/init.lua'
	no file './ledframework/ubus.so'
	no file '/usr/lib/lua/ledframework/ubus.so'
	no file '/usr/lib/lua/loadall.so'
	no file './ledframework.so'
	no file '/usr/lib/lua/ledframework.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/ledframework/init.lua:5: in main chunk
	[C]: in function 'require'
	/sbin/ledfw.lua:4: in main chunk
	[C]: ?
root@modemtim:~#

**Comment by lorenzocanale-LC** [comment]
cp /rom/etc/ledfw/stateMachines.lua /etc/ledfw/stateMachine.lua
e dopo aggiorna di nuovo all'ultima dev così rimette il file ubus

**Comment by dga4130-renato** [comment]
Se non fosse che domani sti beoti della tim vengono a riparare la fibra non mi interesserebbe nulla x due led, ma sono sicuro che se vedono tutto spento minimo dicono come al solito... e' rotta la scheda madre. dipende dal router... il bello anche su quello di scorta. dopo l'upgrade alla stabile gui andava. poi il firm, e andava. poi l'upgrade alla develop, e li e' successo il tutto... non ricordo bene ma mi pare che finche' era tutto accesso era ok poi ricaricando la config che ovviamente ha provocato il reset i led sono stati sempre spenti.
l'altro router non ho ricaricato la config, ma l'ho spento. ed in pratica riacceso i led erano ovviamnete spenti.
questa un po' la cronostoria x farvi capire.....

**Comment by FrancYescO** [comment]
confermami sia tutto ok..

**Comment by dga4130-renato** [comment]
Root Script: Executing /etc/modgui_scripts/02_specific.sh
Root Script: Applying specific model fixes...
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 165: can't open /usr/lib/lua/ledframework/ubus.lua: no such file
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 165: can't open /usr/lib/lua/ledframework/ubus.lua: no such file
sed: /usr/lib/lua/ledframework/ubus.lua: No such file or directory
Root Script: StateMachine tar md5sum: cabb07035260e2b404c00c8aec73a312
Root Script: StateMachine md5sum: cabb07035260e2b404c00c8aec73a312
Unsupported parameter [set]
error
Root Script: Removing fixes and resuming root process...
Root Script: Executing /etc/modgui_scripts/03_various.sh
Root Script: Fix Sysupgrade
Root Script: Restore original mapper

**Comment by dga4130-renato** [comment]
led spenti

**Comment by lorenzocanale-LC** [comment]
cp /rom/etc/ledfw/stateMachines.lua /etc/ledfw/stateMachine.lua e poi riesegui upgradegui così dovrebbe estrarti il file ubus.lua

**Comment by lorenzocanale-LC** [comment]
Perché dovresti metterlo manualmente, visto che te l'ho fatto rimuovere, mi dispiace, ho sbagliato

**Comment by dga4130-renato** [comment]
ok speriamo... in corso....

**Comment by dga4130-renato** [comment]
Root Script: Disable watchdog
Root Script: Executing /etc/modgui_scripts/02_specific.sh
Root Script: Applying specific model fixes...
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 165: can't open /usr/lib/lua/ledframework/ubus.lua: no such file
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 165: can't open /usr/lib/lua/ledframework/ubus.lua: no such file
sed: /usr/lib/lua/ledframework/ubus.lua: No such file or directory
Root Script: StateMachine tar md5sum: cabb07035260e2b404c00c8aec73a312
Root Script: StateMachine md5sum: cabb07035260e2b404c00c8aec73a312
Unsupported parameter [set]
error
Root Script: Removing fixes and resuming root process...

**Comment by dga4130-renato** [comment]
led spenti...

**Comment by lorenzocanale-LC** [comment]
curl -k https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/modular/ledfw_support-specificDGA.tar.bz2 --output /tmp/ledfw_support-specificDGA.tar.bz2
bzcat /tmp/ledfw_support-specificDGA.tar.bz2 | tar -C / -xvf -

**Comment by lorenzocanale-LC** [comment]
E poi fai upgrade gui

**Comment by dga4130-renato** [comment]
senza riavvio ?

**Comment by lorenzocanale-LC** [comment]
Non dovrebbe essere necessario

**Comment by dga4130-renato** [comment]
root@modemtim:~# /etc/init.d/ledfw restart
killall: ledfw.lua: no process killed
root@modemtim:~# /usr/share/transformer/scripts/restart_leds.sh
root@modemtim:~# 

ripartiti

**Comment by dga4130-renato** [comment]
Root Script: Executing /etc/modgui_scripts/02_specific.sh
Root Script: Applying specific model fixes...
Root Script: StateMachine tar md5sum: cabb07035260e2b404c00c8aec73a312
Root Script: StateMachine md5sum: cabb07035260e2b404c00c8aec73a312
Unsupported parameter [set]
error
Root Script: Removing fixes and resuming root process...
Root Script: Executing /etc/modgui_scripts/03_various.sh

**Comment by dga4130-renato** [comment]
ma questo procedimento sara' inttrodotto nella nuova dev ? o devo fare tutto manualemente anche sull'altro modem ?

**Comment by lorenzocanale-LC** [comment]
> Root Script: Executing /etc/modgui_scripts/02_specific.sh
> Root Script: Applying specific model fixes...
> Root Script: StateMachine tar md5sum: cabb07035260e2b404c00c8aec73a312
> Root Script: StateMachine md5sum: cabb07035260e2b404c00c8aec73a312
> Unsupported parameter [set]
> error
> Root Script: Removing fixes and resuming root process...
> Root Script: Executing /etc/modgui_scripts/03_various.sh

Questo penso che sia il bug di cui parlano 
https://github.com/Ansuel/tch-nginx-gui/issues/715

**Comment by lorenzocanale-LC** [comment]
> ma questo procedimento sara' inttrodotto nella nuova dev ? o devo fare tutto manualemente anche sull'altro modem ?

In teoria nell'altro non dovresti avere problemi perché non hai rimosso l'ubus.lua

**Comment by dga4130-renato** [comment]
quindi la soluzione e' quella che ho apportato io ?

**Comment by FrancYescO** [comment]
l'ubus.lua viene riscritto dalla gui, non ci dovrebbe bisogno di far altro se non aggiornare all'ultima dev e al massimo lanciare lo script di restart led.

**Comment by lorenzocanale-LC** [comment]
Si ma se il file StateMachine era stato precedentemente installato da una versione vecchia l'ubus.lua non viene estratto

**Comment by dga4130-renato** [comment]
non e' andata.. ho fatto upgradegui e poi restart led ma non vaì.. adesso sono sul 4132 di backup
e sto facendo le stesse cose dell'altro....

**Comment by dga4130-renato** [comment]
ed infatti e' partito

**Comment by dga4130-renato** [comment]
ok, tutto fatto, ho scambiato di nuovo i router..e va tutto bene. grazie 100000 speriamo facciano un fix
