### ISSUE TITLE
Specific.sh Behavior

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#718]
https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/etc/modgui_scripts/02_specific.sh

> ledfw_extract() {
> 	if [ -f "/tmp/ledfw_support-specific$1.tar.bz2" ]; then
> 		stateMachine_tar_md5=$(bzcat /tmp/ledfw_support-specific$1.tar.bz2 | tar xf - stateMachines.md5sum -O | awk '{ print $1 }')
> 		stateMachine_md5=$(md5sum /etc/ledfw/stateMachines.lua | awk '{ print $1 }' )
> 		logger_command "StateMachine tar md5sum: $stateMachine_tar_md5"
> 		logger_command "StateMachine md5sum: $stateMachine_md5"
> 		if [ "$stateMachine_tar_md5" ] && [ "$stateMachine_tar_md5" != "$stateMachine_md5" ]; then
> 			logger_command "Extracting ledfw_support-specific$1.bz2 ..."
> 			/usr/share/transformer/scripts/restart_leds.sh
> 			bzcat "/tmp/ledfw_support-specific$1.tar.bz2" | tar -C / -xf -
> 		fi

In the ledfw_extract function should also be added a check to verify if ubus.lua is different, otherwise it won't be extracted

**Comment by FrancYescO** [comment]
already noted is just junk code...

**Comment by Ansuel** [comment]
Why closed ? Did you test the commit?

**Comment by lorenzocanale-LC** [comment]
No, I thought you tested 😂

**Comment by lorenzocanale-LC** [comment]
Looks like it extracted the file, but it didn't restart the leds

**Comment by lorenzocanale-LC** [comment]
Also you should add a logger_command just to understand if and what file it overwrites. Tested twice, it looks like the script changed the ubus file even with the statusMachines.lua file from the GUI, so it should work, but it doesn't trigger the restart_leds script

**Comment by Ansuel** [comment]
They should be restarted?

Il Lun 22 Lug 2019, 16:10 Lorenzo <notifications@github.com> ha scritto:

**Comment by lorenzocanale-LC** [comment]
If I understood the script correctly they should restart if any file of the is extracted, am I wrong?

**Comment by Ansuel** [comment]
Ok try restore original file from /rom and check if they gets updated

**Comment by lorenzocanale-LC** [comment]
Yes, that is indeed what I tried and It worked

**Comment by Ansuel** [comment]
Yes if any file is replaced the function return 1 and the restart led
script is triggered

Il Lun 22 Lug 2019, 16:20 Ansuel Smith <ansuelsmth@gmail.com> ha scritto:

> Ok try restore original file from /rom and check if they gets updated
>

**Comment by lorenzocanale-LC** [comment]
Ok, then this part of the script doesn't work, because the file was copied but the script didn't get triggered
