### ISSUE TITLE
ddns

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#719]
dga4132
gui sviluppatore.
sembra che sebbene aggiorni correttamente il servizio ddns non sia raggiungibile da assistenza remota con il ddns
mentre con l'ip che viene visualizzato sulla casella assistenza remota funzioni bene.
ho tentato con due serizi ddns

**Comment by FrancYescO** [comment]
il ddns viene aggiornato? qual e' l'errore visualizzato da browser?

**Comment by dga4130-renato** [comment]
Non trova l'indirizzo. Ne duckdns ne noip

**Comment by FrancYescO** [comment]
cosa significa non trova l'indirizzo?!
dalla pagina DDNS lo stato aggiornamento cosa mostra?

**Comment by dga4130-renato** [comment]
Ora funziona ..forse un problema con noip come segnalato nell'altro ticket. Ed un mix di confusione . Scusami ancora.
