### ISSUE TITLE
VALORE NON VALIDO (DDNS)

### ISSUE THREAD

**Issue by yandew** [Ansuel/tch-nginx-gui#72]
![image](https://user-images.githubusercontent.com/22414976/42723312-ca5bb430-875b-11e8-87e9-572d64bebe18.png)
fino all'ultimo update andava, ieri aggiorno all'ultima versione e non va più la configurazione ddns O:

**Comment by Escart94** [comment]
We're going to check the issue, thanks for reporting this.

**Comment by Escart94** [comment]
Fixed in 5d32a5a6189f17123f2dfda176b58f93326cdd1e
