### ISSUE TITLE
Help Wanted: Bugs in new unified ui

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#724]
I have pushed a new ui. Can you test and report here problems?

**Comment by lorenzocanale-LC** [comment]
First of all it looks Wonderfull. That being said some of the names from the left menu are not in line <img width="252" alt="Schermata 2019-07-19 alle 20 37 36" src="https://user-images.githubusercontent.com/44505255/61557739-4f474380-aa65-11e9-84dc-2c00dff32448.png"> and it would be better to scroll manually the left menu instead of going down automatically when pointing with the mouse

**Comment by Ansuel** [comment]
can you tell me the resolution ? 

Problem with scrolling is that i hate the really big scroll bar... and scrollbar customizzation is still far from standard...

**Comment by lorenzocanale-LC** [comment]
Full screen safari on a 2880 x 1800 MacBook, I don't if this information is enough for the resolution.

**Comment by Ansuel** [comment]
the bug was my fault as i already fixed it but didn't include it in the commit

**Comment by lorenzocanale-LC** [comment]
Internet Access is still not in line

**Comment by lorenzocanale-LC** [comment]
In the wireless tab voices aren't visible until pointing them
<img width="252" alt="Schermata 2019-07-20 alle 09 31 43" src="https://user-images.githubusercontent.com/44505255/61575834-455b2a00-aad1-11e9-82c0-bac5d96aa361.png">

**Comment by Ansuel** [comment]
@lorenzocanale-LC THX NICE FIND!

**Comment by lorenzocanale-LC** [comment]
<img width="389" alt="Schermata 2019-07-20 alle 17 28 59" src="https://user-images.githubusercontent.com/44505255/61580563-ebc81f00-ab13-11e9-910e-67af3f9d5ce8.png">
Cancel bigger than save

**Comment by Ansuel** [comment]
fixed

**Comment by FrancYescO** [comment]
Improvements:
- little bigger font in side menu
- pointer icon when hovering side menu icon (as you can click everywhere to have the modal opened)
- hide header (on the right of the technicolor logo) when a modal is opened
- remove the bottom arrow just treat side menu as "scrollable"
- change logo background color?

Bugs:
- a little glitchy on iphone landscape resolution:
![image](https://user-images.githubusercontent.com/4574593/61585800-fb238880-ab64-11e9-9ab1-d872f93f3c28.png)
- on mobile, the "background page" will result as scrollable (you'll see the page under the trasparent header)
- on mobile, advanced (upper right) menu will go under the modal when opened

**Comment by FrancYescO** [comment]
bianco su bianco
![image](https://user-images.githubusercontent.com/4574593/62424952-e18e4f00-b6d5-11e9-860e-cedaae143fe6.png)

**Comment by Dark4Codrutz** [comment]
Can't select and save the theme on latest GUI.
After selecting the theme on the drop menu it automatically loads it and the save button disappears.
Next time I load/reload the page it reverts to latest saved theme option.

**Comment by FrancYescO** [comment]
9.3.82?
________________________________

**Comment by Dark4Codrutz** [comment]
Was on 9.3.81 but I just updated and **yes** same behavior

**Comment by FrancYescO** [comment]
Cannot reproduce... From from skin you are trying to change? Screen resolution?

Try clearing browser cache
________________________________

**Comment by nclmrc** [comment]
In mobile version the save button is no more present.

**Comment by nclmrc** [comment]
@Ansuel dopo aver aggiornato all'ultima versione da GUI, completato l'aggiornamento ho dovuto fare diversi refresh affinché tornasse la schermata di login. Prima era venuta la schermata di login tutta decentrata con i caratteri sparsi, poi dopo altri refresh era venuta la schermata di login di quella viola, infine è tornata quella unificata.

**Comment by nclmrc** [comment]
Quest'ultima cosa ho fatto caso, lo fa con tutte le GUI però sembra sia apparsa da quando ho abilitato l' HTTPS

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/63211844-02ef3200-c0fd-11e9-9a58-bb853005f0d9.png)

**Comment by nclmrc** [comment]
fatte un pò di prove, occorre sempre il refresh dopo un logout o un upgrade della gui per tornare alla schermata di login

**Comment by FrancYescO** [comment]
Non capisco, senza fare il refresh in che schermata sei?!

**Comment by nclmrc** [comment]
Dopo aver fatto un un'aggiornamento devi rifare il login, ma non arrivi
direttamente a quella schermata

Inviato da Samsung Galaxy Note 8

Il Dom 18 Ago 2019, 12:40 Francesco M <notifications@github.com> ha scritto:

**Comment by nclmrc** [comment]
@FrancYescO possibile che con la .94 sia cambiato qualcosa? adesso sembra andare
