### ISSUE TITLE
Pulsante Salva Funzioni Extra Sistema 

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#727]
Il pulsante Salva non funziona

**Comment by Ansuel** [comment]
Modificando quale impostazione?

Il Sab 20 Lug 2019, 22:17 Niccolò Marchi <notifications@github.com> ha
scritto:

**Comment by nclmrc** [comment]
Le opzioni importa e esporta.

Inviato da Samsung Galaxy Note 8

Il Sab 20 Lug 2019, 22:22 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by FrancYescO** [comment]
hai provato a ricaricare la pagina o fare logout/login e vedere se lo fa ancora?

**Comment by nclmrc** [comment]
Avevo provato ieri sera e non funzionava. Stamani va.
