### ISSUE TITLE
GUI - Dubbi su alcune stringhe sorgenti/traduzioni italiane

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#729]
@Ansuel  
@FrancYescO 

msgid "Single Rx Chain"
msgstr "Singola antenna RX"

Qui si parla di canale o di antenna WiFi?
Se si parla di antenmna è giusto l'italiano antenna e l'inglese dovrebbe essere "Single RX antenna"
O si parla di canale l'inglese è giusto e l'italiano potrebbe essere " Singolo canale RX".

msgid "Error. Reset the Rule!"
msgstr "Errore. Re-imposta la regola!"

In questo contesto più che "Reset" forse non è più giusto per l'inglese "Re-set"?

**Comment by FrancYescO** [comment]
Non si sa di che si parla perché non è una funzione documentata.
Personalmente per questo motivo nemmeno la tradurrei... Ma dubito parliamo di canale dato che per quello c'è la selezione dei MHz

Per quanto riguarda reset a me non piace proprio l'impostazione della frase inglese ma nel dubbio va bene re-set

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/commit/0c33a12d30c31c0872db13267ed0c66068da417a
