### ISSUE TITLE
Luci

### ISSUE THREAD

**Issue by 9anSan5** [Ansuel/tch-nginx-gui#73]
Can't enter in the luci ui. It returns me instantaneously connection failes (connessione non riuscita)

**Comment by nclmrc** [comment]
Prova a disinstallare e disinstallare luci da gui.

**Comment by 9anSan5** [comment]
Ho provato una miriade di volte anche riavviando a mano il servizio uhttpd.

**Comment by Kherby** [comment]
Same here. I'm using bridge mode... Does the initial Luci installation require a working internet connection?

**Comment by Alex2610** [comment]
I have the same issue with Luci or other similar apps (xupnp, aria...) i get: "Connection refused". 
Also mentioned in another issue
