### ISSUE TITLE
Unable to set default route

### ISSUE THREAD

**Issue by monreal** [Ansuel/tch-nginx-gui#731]
Device Model: DGA4132
Gui Version: 9.3.0

Description of problem: After upgrading firmware from 1.1.0 to 2.0.0 my previously manually set default route is gone and the GUI does not allow me to set it, as it does not allow a mask of 0.0.0.0

Using the CLI I was able to set the default route using "route add default gw 192.168.1.2 br-lan" but I guess this is not reboot-safe so I would really appreciate if the GUI would allow it (again)

How to reproduce (if possible): try to add default route

**Comment by Ansuel** [comment]
yes tell me the route you are trying to set in the gui ;)

**Comment by monreal** [comment]
![image](https://user-images.githubusercontent.com/54005/61595134-9e22e380-abf3-11e9-8512-c2e14e2aabc6.png)

The screenshot is taken from my documentation. Some GUI / firmware combination allowed me to set it. Now the GUI says "0.0.0.0" is an invalid mask.

**Comment by Ansuel** [comment]
try use 0.0.0.0/0 as destination

**Comment by monreal** [comment]
Still says "Invalid netmask."

**Comment by monreal** [comment]
Confirmed fixed. Thanks a lot!
