### ISSUE TITLE
Unable to set DNS-Servers (Bridge mode)

### ISSUE THREAD

**Issue by monreal** [Ansuel/tch-nginx-gui#734]
Device Model: DGA4132
Gui Version: 9.3.11

Description of problem: The "IP Extras" card lists the interfaces and three columns for DNS servers but does not allow to actually set anything. Maybe this is due to the modem being used in bridge mode. However I need to set a DNS server for LAN. Right now I always have to ssh into the modem and call a script to alter /etc/resolv.conf

**Comment by nutterthanos** [comment]
No your not supposed to be able to edit dns servers in bridge mode.

**Comment by monreal** [comment]
Well, I am very well aware of how a bridge works however in order to update the modem I need DNS on the management interface (which in this case is LAN).

**Comment by nutterthanos** [comment]
Maybe just remove the check for bridge mode code?

**Comment by monreal** [comment]
Turning off bridge mode won't work for me as I need my OpnSense appliance to initiate the connection.

I can attach a screenshot later. However the problem is simple to explain: there are no text boxes and no save button

**Comment by Ansuel** [comment]
@monreal in last dev i addes what you request  tell me if it's what you needed

**Comment by monreal** [comment]
> @monreal in last dev i addes what you request tell me if it's what you needed

Seem to do the trick! At least on the console I get DNS resolution now without tempering with resolv.conf manually. Waiting for the next dev release to test if I can install updated using the web UI now.

**Comment by Ansuel** [comment]
@monreal didn't understand the last part

**Comment by monreal** [comment]
I was now able to update to 9.3.34 using the GUI, so all is working perfectly fine now. Thanks a lot!!
