### ISSUE TITLE
Volendo aggiornare il firmware dalla AGTHP_2.0.1 alla AGTHP_2.1.0 ho l'errore Aggiornamento firmware fallito. (Codice errore: 9)

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#736]
Device Model: DGA4132
Gui Version:  9.3.14

Description of problem:

Volendo aggiornare il firmware dalla AGTHP_2.0.1 alla **AGTHP_2.1.0** ho l'errore Aggiornamento firmware fallito. **(Codice errore: 9)**

**Comment by Ansuel** [comment]
@giulio63 fai questo comando

ls -la /

**Comment by giulio63** [comment]
ecco l'output del comando     ls -la /

drwxr-xr-x    1 root     root             0 Jul 24 23:41 .
drwxr-xr-x    1 root     root             0 Jul 24 23:41 ..
-rwxr-xr-x    1 root     root             0 Jan 11  2019 .init_enable_core
drwxr-xr-x    1 root     root             0 Jul 25 23:35 bin
drwxr-xr-x    3 root     root             0 Apr 17 16:52 cgroups
drwxr-xr-x    2 root     root             3 Jan 11  2019 custo
drwxr-xr-x    4 root     root             0 Jul 24 23:41 dev
drwxr-xr-x    1 root     root             0 Jul 25 23:36 etc
drwxr-xr-x    4 root     root             0 Apr 17 16:52 home
drwxr-xr-x    1 root     root             0 Jul 25 22:23 lib
drwxrwxrwx    1 root     root             0 Apr 17 16:55 mnt
drwxr-xr-x    4 root     root            37 Jan 12  2019 opt
drwxr-xr-x    4 root     root             0 Jan  1  1970 overlay
dr-xr-xr-x  134 root     root             0 Jan  1  1970 proc
drwxr-xr-x    1 root     root             0 Jul 24 23:40 qtn
drwxr-xr-x   19 root     root           295 Apr 18 18:08 rom
drwxr-xr-x    1 root     root             0 Jul 26 00:25 root
drwxr-xr-x    1 root     root             0 Jul 25 23:35 sbin
-rw-------    1 root     root           550 May  1 12:00 shadow_old
dr-xr-xr-x   12 root     root             0 Jan  1  1970 sys
drwxr-xr-x   27 root     root             0 Jul 26 00:25 tmp
drwxr-xr-x    1 root     root             0 Jan  1  2018 usr
lrwxrwxrwx    1 root     root             4 Apr 18 18:08 var -> /tmp
drwxr-xr-x   10 root     root             0 Jul 25 23:35 www

**Comment by Ansuel** [comment]
@giulio63 puoi provare a riavviare il modem ?

**Comment by giulio63** [comment]
Ansuel, ti ringrazio, dopo più di un riavvio sono riuscito finalmente ad aggiornare firmware e gui all'ultima disponibile.
Avevo letto che c'erano problemi con le estensioni ma nel mio caso adesso c'e' solo Telstra installabile e non so se è normale.
altra cosa importante : nella tab "Funzioni extra di sistema" non è più presente la possibilità di abilitare telnet e nè risulta abilitato mentre SSH si
