### ISSUE TITLE
UI unificata problemi

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#738]
![immagine](https://user-images.githubusercontent.com/38593316/61947720-46df9300-afa6-11e9-9e01-00f9a6f99023.png)

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/61947828-80180300-afa6-11e9-9ab6-2cbbf597fcc6.png)
non carica le statistiche

**Comment by FrancYescO** [comment]
ref https://github.com/Ansuel/tch-nginx-gui/issues/724
