### ISSUE TITLE
Funzionamento Led stato

### ISSUE THREAD

**Issue by yhcim86** [Ansuel/tch-nginx-gui#739]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: AGTEF 4130
Gui Version: 9.3.26

Description of problem: Se matto il tasto dei led abilitato su risparmio energetico mi si spegnono tutti i led anche quello del power che rimaneva verde prima, anche da gui sulla verifica dei led fa la stessa cosa.
Se lo riattivo si accendono i vari led internet broadband ma quello del power no.
In più non va il tasto per abilitare i led del wifi solo quando questi ultimi sono connessi alla radio corrispondente. 
Attualmente è su off se lo metto a on e salvo ritorna su off automaticamente.
In più non è possibile aggiungere un tasto nella gui che simuli la pressione del tasto fisico info???

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
versione firmware, tipo di connessione e se posti il pacchetto di debug tanto meglio

**Comment by yhcim86** [comment]
Ciao allora ho su come versione la 2.0.0 connessione fibra ftcc con TIM 200/20Mega.
Ho attualmente la Gui 9.3.41 ed in parte il problema sembra risolto cioè se attivo lo switch eco led nella tab relativa e poi mi porto nella tab diagnostica x verificare i led come si comportano rimane acceso solo il led power al 100%.
Questo comportamento sembra essere corretto, se invece spengo lo switch eco led si riaccendono i led voip, internet, Ethernet e broadband al 100%; dunque anche questa situazione credo sia giusta (solo il led Ethernet va ad intermittenza solo quando c'è effettivo traffico dunque sembra ok anche questo specifico funzionamento).
Ora c'è il problema con lo switch NSC WiFi che se messo a OFF o a ON comunque rimane ad OFF e crea questa problematica: quando lo switch eco led è a OFF e i led sono accesi cioè power, broadband, ethernet, voip non sono accesi i due led delle due radio Wifi sia 2.4Mhz che 5Ghz dunque non si capisce se la radio wifi è accesa o no anche se non ci sono collegati nessun client.
Potete verificare quest'ultima casistica??
In più avevo mandato ad Ansuel un debug non so se l'ha letto mi chiedo se lo volessi mettere qui come si fa???
[DebugHelper2019-08-04-1804.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3465064/DebugHelper2019-08-04-1804.tar.gz)

**Comment by FrancYescO** [comment]
se guardi lo stato dei led da interfaccia potrebbe non essere affidabile, e' una funzione nuova e ho appena corretto un po di bug a riguardo.

riguardo wifi nsc io riesco a modificare tranquillamente lo stato dello switch da interfaccia, lo stato dei led non riesco a controllare in questo ma ti chiedo di controllarne il comportamento guardando i led fisici e non dalla card di diagnostica

**Comment by yhcim86** [comment]
Riguardo l'interfaccia dei l3d da cui è comodo x me che abito al 2 piano e il modem è in taverna da mio padre e non posso sempre disturbarlo x andare a vedere il modem.
Per quanto riguarda wifi NCS a me non funziona cambia stato appena lo metti da off a on poi faccio chiudi finestra in fondo alla stessa, la gui fa un refresh e se rivado a vedere lo stato del WiFi NCS lo ritrovo a off.
Cmq prima dell'aggiornamento 9.3.34 i led e le varie problematiche che ti ho esposto funzionavano a dovere. 
Magari puoi fare una verifica sulle versioni precedenti alla 9.3.34 cosa è cambiato da allora ad ora.
Sempre disponibile a farti un video.
