### ISSUE TITLE
Scrollbar not present in GUI

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#74]
In the gui home page the scrolling bar on the right is not present.

**Comment by Escart94** [comment]
Which skin are you using? Can you make a screenshot? 
Thanks.

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/42735927-f81d4de6-885c-11e8-9ba9-703edca0419d.png)
preciso nelle skin midnight e fritz

**Comment by nclmrc** [comment]
accade solo con chrome

**Comment by Ansuel** [comment]
hai già provato a pulire cache vero?

**Comment by nclmrc** [comment]
si ora lo fa anche con firefox

**Comment by Ansuel** [comment]
@Takenfal idee?
