### ISSUE TITLE
Assenza/impossibilità di accedere al router in telnet dopo aggiornamento Firmware/GUI

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#741]
Device Model:  DGA4132
Gui Version:   9.3.26
Firmware :   AGTHP_2.1.0

Description of problem:

Dopo aver aggiornato all'ultima versione disponibile di Firmware/GUI , nella tab "Funzioni extra di sistema" non è più presente la possibilità di abilitare telnet e nè risultava già abilitato mentre SSH si

Ho provato ad installarlo manualmente con questi comandi  : 

wget -P /tmp http://repository.ilpuntotecnico.com/files/Ansuel/AGTEF/modular/telnet_support-specificDGA.tar.bz2

bzcat /tmp/telnet_support-specificDGA.tar.bz2 | tar -C / -xvf -
ln -s /bin/busybox_telnet /usr/sbin/telnetd
cp /etc/config/telnet_orig /etc/config/telnet

inserito/modificato   **option enable '1'**   nel file **/etc/config/telnet**

ed attivato il servizio Telnet con i comandi :  

**/etc/init.d/telnet enable**
**/etc/init.d/telnet start**

Alla fine di queste attività, nella GUI è comparsa nuovamente la sezione per attivare il Telnet ed ho verificato che anche il file di configurazione avesse l'opzione impostata ad "1" ma l'accesso tramite Telnet continua a non essere abilitato.

**Comment by nutterthanos** [comment]
Did the telnet server crash? check with ps.

**Comment by giulio63** [comment]
con ps non risulta attivo il processo del telnet.
il file /usr/sbin/telnetd   esiste
nel file di log della gui non ho messaggi di errore .
Non so se solo io ho questi problemi con gli ultimi aggiornamenti

**Comment by nutterthanos** [comment]
Yep i would would try using strace /etc/init.d/telnet enable and strace /etc/init.d/telnet enable to see what happens?

**Comment by giulio63** [comment]
Yes, I've already tried many times, but in the forum answer that with the last firmware the extensions are not more supported and strange thing for me that also Telnet it's an extension !!!  but SSH works
p.s. : what firmware/gui you've now ? Pherpaps I must downgrade to 2.0.1. firmware

**Comment by nutterthanos** [comment]
Why did you close it eg new update fixed it?

**Comment by giulio63** [comment]
now I'm with the latest beta release of firmware; the AGTHP_2.2.0_001 and Ansuel now works to have again the support for estensions with this version. at moment not works yet with my router, I hope that very soon will be fully supported

**Comment by giulio63** [comment]
anche con le ultime versioni della Gui Dev 3.3.40 il problema rimane sia per il telnet che per le altre estensioni
