### ISSUE TITLE
Error 503: Unknow Service Not available

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#743]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: DGA4132
Gui Version: Last DEV

Description of problem: non mi fa accedere alla gui del modem, rimane cosi anche dopo i 20 secondi che dice.

How to reproduce (if possible):

Media/Photos (if possible): 
![Cattura](https://user-images.githubusercontent.com/44716486/62088940-517c7f80-b267-11e9-8c50-1d0af8b94424.PNG)

@Ansuel @FrancYescO

**Comment by kevdagoat** [comment]
Logread please

**Comment by Ghost9090** [comment]
Command?

**Comment by Ghost9090** [comment]
@kevdagoat

**Comment by kevdagoat** [comment]
Yep

**Comment by Ghost9090** [comment]
Now working
