### ISSUE TITLE
Voip Messagenet 

### ISSUE THREAD

**Issue by Ghost9090** [Ansuel/tch-nginx-gui#744]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model:  DGA4132
Gui Version: 9.3.27

Description of problem: perché non si riesce a configurare il voip di messagenet? Ho inserito tutti i parametri e nel tab telefonia mi dice solo telefonia abilitata e non mi dice se ci sono account in registrazione o meno

How to reproduce (if possible):

Media/Photos (if possible):

@Ansuel

**Comment by Ghost9090** [comment]
Nessuno sa come risolvere?

**Comment by Ghost9090** [comment]
@Ansuel

**Comment by FrancYescO** [comment]
Sbagli qualcosa nella configurazione. Messagenet non c'entra nulla e funziona
