### ISSUE TITLE
La GUI appare incompleta/difettosa

### ISSUE THREAD

**Issue by webmst** [Ansuel/tch-nginx-gui#746]
Salve,
ho appena caricato la GUI ultima versione come da istruzioni dopo aver ottenuto l'accesso root al mio router, un TG789vac XSTREAM 35b.

Tentando l'accesso, compare la corretta schermata di login che invita a digitare nome utente e password ma, completata l'autenticazione, non appare alcun menu, solo il logo technicolor sulla sx e alcuni pulsanti utente della GUI nella parte dx dello schermo ("configurazione guidata", "schede", selezione lingua e "admin/avanzate") i quali non attivano oltretutto alcuna funzione.

Ho riprovato a ricaricare la GUI senza ottenere alcuna variazione.

Cosa posso fare per rendere funzionale la GUI?

Allego immagine dello schermo.
![image](https://user-images.githubusercontent.com/13507204/62143415-3f92ef00-b2f0-11e9-92b5-6b4c6b09e4fd.png)

**Comment by Ansuel** [comment]
Serve un logread

Il Mar 30 Lug 2019, 17:36 webmst <notifications@github.com> ha scritto:

**Comment by webmst** [comment]
Grazie dell'aiuto Ansuel,
allego l'output del comando logread
[logread.txt](https://github.com/Ansuel/tch-nginx-gui/files/3448093/logread.txt)
(considera attuali le date memorizzate, anche se il router riporta il 25/6/17)

**Comment by dnsound** [comment]
Ciao, 
succede anche a me con il vecchio fw fastweb v 7825; dopo aver flashato il router prova un update con cwmp, si dovrebbe aggiornare all'ultima versione fw 8706 e funziona la gui (in parte, la scheda wifi non va ancora)

**Comment by webmst** [comment]
@dnsound 
in effetti sul mio vecchio router dismesso ho una v7825 ma come faccio ad aggiornare il router se non ho più la linea Fastweb attiva?

**Comment by webmst** [comment]
@dnsound 
in effetti sul mio vecchio router dismesso ho una v7825 ma come faccio ad aggiornare il router se non ho più la linea Fastweb attiva?

**Comment by viaggio32** [comment]
Ciao a tutti,
Confermo anche io lo stesso errore sullo stesso modem, il mio logread è su https://pastebin.com/DRXfWJSj

**Comment by FrancYescO** [comment]
giusto per conferma, tutti quelli che hanno il problema hanno versione 7825 ? o c'e qualcuno con anche 8706 in errore?

quelli che hanno la 7825 lo tengono collegati ad una linea fastweb? (e quindi non hanno mai ricevuto ufficialmente l'aggiornamento?!)

**Comment by viaggio32** [comment]
confermo 7825 (credo IAD, con la GUI originale facevo il login con l'username fastweb).
Non ho una linea fastweb, non saprei quindi come aggiornare a versioni successive.

**Comment by FrancYescO** [comment]
@dnsound riesci a postare la versione per esteso del firmware 8706 ? abbiam bisogno dell'rbi cosi tagliamo la testa al toro potendo aggiornare tutti quelli vecchi

**Comment by webmst** [comment]
@FrancYescO 
la v7825 è stata l'ultima prima che il router venisse sostituito dal nuovo router Fastgate, quindi non so se Fastweb ha una versione più aggiornata del firmware sul server ACS (di cui esisterebbero almeno due versioni: MOS e IAD)

**Comment by FrancYescO** [comment]
https://anonfile.com/VeWeof2fn5/16.2.8706_FW_214_IAD_TG789vacXtream_rbi

piazzatelo in /tmp e installate con sysupgrade

**Comment by viaggio32** [comment]
con la versione 8706 la gui si carica correttamente, rimangono alcuni bug nelle varie impostazioni

**Comment by FrancYescO** [comment]
riportateli man mano qui se non sono gia riportati https://github.com/Ansuel/tch-nginx-gui/issues/529

**Comment by jtommy** [comment]
@FrancYescO la issue è chiusa da anni ma il problema con questo firmware rimane. La UI dopo la login mostra solo i pulsanti in alto e quindi non è utilizzabile. 
Nello specifico io avrei bisogno di impostare la Wan con i parametri del provider e basta, con un tuo supporto potrei farlo da ssh.

**Comment by FrancYescO** [comment]
Non vale la pena investire tempo per risolvere il problema avendo il firmware più nuovo che risolve

**Comment by jtommy** [comment]
@FrancYescO dove si trova?

**Comment by FrancYescO** [comment]
[16.2.8706_FW_214_IAD_TG789vacXtream.rbi.zip](https://github.com/Ansuel/tch-nginx-gui/files/13900819/16.2.8706_FW_214_IAD_TG789vacXtream.rbi.zip)
