### ISSUE TITLE
IPv6 Error on TG789vac v2

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#749]
Device Model:  TG789vac v2 Firmware UNO 17.2
Gui Version: 9.3.34

Description of problem:
The log of my TG789vac V2 Firmware UNO 17.2 is full of these notice and error:
```
Sat Aug  3 17:19:14 2019 daemon.info odhcpd[3046]: Using a RA lifetime of 0 seconds on br-lan
Sat Aug  3 17:19:14 2019 daemon.notice odhcpd[3046]: Failed to send to ff02::1%br-lan (Operation not permitted)
Sat Aug  3 17:19:27 2019 daemon.err odhcp6c[25489]: Failed to send DHCPV6 message to ff02::1:2 (Operation not permitted)

```
Additionally when opening lan card this error shows up in the log:
```
Sat Aug  3 17:20:48 2019 daemon.err transformer[9695]: [truncated] getter(rpc.network.interface.@., ipv6uniqueglobaladdr) threw an error: /usr/lib/lua/tch/inet.lua:128: attempt to call upvalue 'inet_ntop' (a nil value)
stack traceback:
	/usr/lib/lua/tch/inet.lua:128: in function </usr/lib/lua/tch/inet.lua:123>
	(tail call): ?
	...share/transformer/mappings/rpc/network.interface.map:272: in function 'load_ipv6_addresses'
	...share/transformer/mappings/rpc/network.interface.map:286: in function 'get_address'
```
And the IPv6 dot is always orange even if IPv6 should be disabled.

**Comment by FrancYescO** [comment]
probably fixed with https://github.com/Ansuel/tch-nginx-gui/commit/9d38a0a002794f939d196240135c339830350e37 could you check?

**Comment by lorenzocanale-LC** [comment]
What should be fixed? This error doesn't show up anymore

```
Sat Aug  3 17:20:48 2019 daemon.err transformer[9695]: [truncated] getter(rpc.network.interface.@., ipv6uniqueglobaladdr) threw an error: /usr/lib/lua/tch/inet.lua:128: attempt to call upvalue 'inet_ntop' (a nil value)
stack traceback:
	/usr/lib/lua/tch/inet.lua:128: in function </usr/lib/lua/tch/inet.lua:123>
	(tail call): ?
	...share/transformer/mappings/rpc/network.interface.map:272: in function 'load_ipv6_addresses'
	...share/transformer/mappings/rpc/network.interface.map:286: in function 'get_address'
```

But the IPv6 dot is still orange, and these error are still there:
```
Sat Aug 10 01:51:59 2019 daemon.info odhcpd[4115]: Using a RA lifetime of 0 seconds on br-lan
Sat Aug 10 01:51:59 2019 daemon.notice odhcpd[4115]: Failed to send to ff02::1%br-lan (Operation not permitted)
Sat Aug 10 01:52:15 2019 daemon.info odhcpd[4115]: Using a RA lifetime of 0 seconds on br-guest
Sat Aug 10 01:52:15 2019 daemon.notice odhcpd[4115]: Failed to send to ff02::1%br-guest (Operation not permitted)
```
Are those normal?

**Comment by FrancYescO** [comment]
Yep I was asking for the error...

Idk exactly how is managed ipv6 (finding no way to change it in GUI..), but I have similar logs on 788vn and on local network card it show ipv6 assigned with green dot, your orange dot is the one on local network modal? (If I'm not wrong, if enable will also appear on the internet modal that is obviously related to WAN connection..)

**Comment by hereCOMESlappy** [comment]
Hello, I have IPv6 working on my TG789v2 HP with 9.4.2

However it is not displaying any DHCPv6 leases even tho my devices are being issued IPv6 addresses the leases do not show in the GUI see picture:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/44932282/63338920-1f9e9a80-c387-11e9-9942-ebc02bb9a6ad.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/44932282/63338962-3218d400-c387-11e9-81e7-349d584ee52c.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/44932282/63339000-452ba400-c387-11e9-8335-ddd51507c1f7.png">

**Comment by FrancYescO** [comment]
@hereCOMESlappy please upload a dump of your firmware:
execute `dd if=/dev/mtd3 of=/tmp/mtd3` than take the mtd3 file (around 45MB) from /tmp folder of the modem and upload it here

just in case, (after deleting mtd3 from /tmp otherwise you will probably go out of RAM) do the same for mtd4 `dd if=/dev/mtd3 of=/tmp/mtd3`

**Comment by hereCOMESlappy** [comment]
Ok yep the MyRepublic one on that site is what I have yep

**Comment by Ansuel** [comment]
should be fixed
