### ISSUE TITLE
Non si riesce piu' a disattivare momentaneamente una regola di port forwarding

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#752]
@Ansuel , @FrancYescO 

Device Model:  DGA4132
Gui Version:  9.3.37
Firmware : AGTHP_2.2.0_001

Nel tab Servizi Wan , in "Inoltro porte" non si riesce piu' a disattivare momentaneamente una regola .
Come sempre ho clickato sulla destra sulla voce modifica e dopo
sulla sinistra portando lo switch da ON ad OFF e confermato sulla destra su applica ma non accetta piu' l'indirizzo MAC inserito  e non permette di disattivare la regola

**Comment by FrancYescO** [comment]
![image](https://user-images.githubusercontent.com/4574593/62424884-28c81000-b6d5-11e9-95ab-f6b495d49110.png)
piu' in generale sembra non si riesca nemmeno ad aggiungere una regola per mac address, il validatore non accetta neanche quelli validi

**Comment by Ansuel** [comment]
Stesso firmware?

Il Dom 4 Ago 2019, 16:32 Francesco M <notifications@github.com> ha scritto:

**Comment by giulio63** [comment]
@Ansuel  io con l'ultima beta, AGTHP_2.2.0_001 , tu utilizzi una versione più recente ?

**Comment by Ansuel** [comment]
No

Il Dom 4 Ago 2019, 16:44 giulio63 <notifications@github.com> ha scritto:

**Comment by FrancYescO** [comment]
AGTHP_2.0.1_001

**Comment by Ansuel** [comment]
Il mac è lungo 12 caratteri non 10

**Comment by giulio63** [comment]
ma i miei indirizzi mac sono da 12 e funzionanti, ma non riesco a disabilitarli se non editando il file manualmente

![image](https://user-images.githubusercontent.com/42684977/62428898-6b0a4500-b707-11e9-8b8b-708a6a7b57c1.png)

**Comment by FrancYescO** [comment]
quando passi sopra con il mouse che messaggio di errore appare ?

**Comment by giulio63** [comment]
**" Devi specificare un indirizzo IP o un MAC "**

adesso ho provato anche ad inserirne una nuova , stessa situazione, non accetta il mac address  e sembra voglia anche il campo di ip remoto che non è mai servito

ma se edito il file /etc/firewall accetta la modifica e la disattiva.

p.s.: non vorrei dover tornare al firmware stabile precedente, anche il problema con wget/opkg che non mi fa installare niente

**Comment by giulio63** [comment]
@Ansuel , forse dovrebbe essere riaperta ed imposta come bug nuovamente. il problema è presente sia in fase di inserimento di nuove regole che di disattivazione temporanea, ma probabilmente solo con la versione beta del firmware. Ci sono comandi in ssh che possono essere utili ? oppure stasera mando comunque un logread per capire se alcuni warnings possono essere utili per migliorare la situazione. Grazie

**Comment by FrancYescO** [comment]
Posta un pacchetto debughelper che fai dalla modal extra

**Comment by giulio63** [comment]
[DebugHelper2019-08-05-2155.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3469165/DebugHelper2019-08-05-2155.tar.gz)

Non se può essere di aiuto o se sia un problema specifico dell'ultimo firmware

**Comment by FrancYescO** [comment]
![Aug-06-2019 08-14-15 gif sb-b63a32fa-Xm3mzX](https://user-images.githubusercontent.com/4574593/62515367-67b7ac00-b822-11e9-95d2-94bf37b9f815.gif)
dal debug non vedo errori, ho aggiornato a 2.2.0_001 giusto per provare ma a me continua .a funzionare bene...

**Comment by giulio63** [comment]
mi viene il dubbio che sia rovinato il mio file . dove posso trovare quello di default pulito ?
voglio vedere se sostituendolo e reinserendole continuo ad avere il problema

**Comment by FrancYescO** [comment]
`cp /rom/config/firewall /etc/config/firewall`
e al massimo esegui anche upgradegui dopo

**Comment by FrancYescO** [comment]
al massimo salvati anche il vecchio che capiamo se era li il problema

**Comment by giulio63** [comment]
per un momento ho pensato che mancasse una parte fondamentale del firmware, invece c'era un piccolo errore nel percorso del file firewall originale, che si trova in   :
/rom/etc/config  
per cui il comando corretto è :  
**cp /rom/etc/config/firewall /etc/config/firewall**

**Comment by giulio63** [comment]
ma l'importante è che sono riuscito a capire dov'era il problema, infatti appena messo il file originale ha ripreso a funzionare. dopo brevi test incrociati ho capito che gli dava fastidio una regola che avevo inserito manualmente e non da Gui, che in questo firmware se presente, da fastidio a tutta la sezione inoltro porte ,,che comunque e' strano, ed eliminandola funziona tutto nuovamente

**Comment by giulio63** [comment]
in pratica molto tempo fa avevo messo una regola manuale ( che non ha mai funzionato bene tra l'altro , ma non dava fastidio alle altre ) . volevo avere l'accesso da web da esterno per cui volevo che la porta 80 fosse accessibile dall'esterno sulla porta 8083, ma non riconosceva mai l'utenza :  

config userredirect 'userredirectE7AC'
	option enabled '1'
	option src_dport '8083'
	option dest 'lan'
	option src 'wan'
	option dest_port '80'
	option name 'http 80'
	option family 'ipv4'
	option target 'DNAT'
	list proto 'tcpudp'
	option _key '1944F70F5FE32C752648EC5F61D81A29'

non so se sia normale che ci sia il campo "option key" che provando a creare una nuova regola non viene inserito

In realta' il lavoro di quella regola viene svolto meglio nella tab "Assistenza remota" anche se non con l'utenza admin.

Non so se si può  correggere quella mia regola che crea fastidi se presente ;-)
 Grazie

**Comment by giulio63** [comment]
in realtà non riconosce l'utenza admin per collegarsi in remoto.
P.S.: ho voluto provare a reinserire la regola mettendo come MAC ADDRESS quello del router e non mi ha dato i problemi che avevo negli ultimi giorni, ma rimane l'impossibilità a collegarsi come admin da remoto. Rimane sempre la possibilità di utilizzare "Assistenza remota" con utenza "assist"
