### ISSUE TITLE
Le estensioni non funzionano anche dopo essere state installate con l'ultima versione della Gui Dev 9.3.40

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#753]
@Ansuel , @FrancYescO

Device Model:  DGA4132
Gui Version:  9.3.40
Firmware  :   AGTHP_2.2.0_001

Descrizione del problema :

Le estensioni non funzionano anche dopo essere state installate con l'ultima versione della Gui Dev 9.3.40 ( apparentemente vengono installate ma poi nessuna funziona. solo Telstra funziona )

Credo che il problema possa essere dovuto a **repository / opkg / wget** che almeno sul  mio router non sembra risolto pur avendolo resettato di recente

Nei topic del forum non ho letto di persone a cui le estensioni funzionino o no per cui non so se sia un problema solo del mio router

In Impostazioni Gui ho sempre il messaggio fisso dove non mi permette di effettuare modifiche o avere dettagli maggiori dello stato attuale  :  

**App specifica**
Un'app specifica è un pacchetto che aggiunge funzionalità al modem come supporto telnet o correzioni al pacchetto predefinito
Stato
**App specifica già installata**

e nessuna traccia del **telnet**, credo che le porte delle varie estensioni non siano aperte

Vorrei sapere almeno se si tratta di un anomalia generale

**Comment by giulio63** [comment]
@Ansuel , @FrancYescO
credo sia lo stesso problema di opkg segnalato per il firmware 2.0.0   : 

https://github.com/Ansuel/tch-nginx-gui/issues/662

e che nella descrizione sembra si sarebbe dovuta risolvere con l'ultimo firmware con la Gui Dev 9.3.34  

**apps: install openssl in DGA modem to fix wget with no ssl support**

ma almeno nel mio caso non si e' risolto ed il file  **/etc/opkg.conf**  contiene :  

dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
arch all 100
arch arm_cortex-a9 200
arch arm_cortex-a9_neon 300
src/gz chaos_calmer_base https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base
src/gz chaos_calmer_packages https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/packages 
src/gz chaos_calmer_luci https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/luci              
src/gz chaos_calmer_routing https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/routing    
src/gz chaos_calmer_telephony https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/telephony
src/gz chaos_calmer_core https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/target/packages

**Comment by Ansuel** [comment]
questo file opkg è corretto ed è come dovrebbe presentarsi
