### ISSUE TITLE
Problem utillzzo Wget-Opkg-Openssl

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#754]
Device Model:  DGA4132
Gui Version:  9.3.48
Firmware  :   AGTHP_2.2.0_001

non viene accettato il comando Wget e quindi non installa i pacchetti.

ed il comando opkg update  da' questo output

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/Packages.gz
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/packages/Packages.gz
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/packages/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/luci/Packages.gz
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/luci/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/routing/Packages.gz
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/routing/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/telephony/Packages.gz
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/telephony/Packages.gz

Downloading https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/target/packages/Packages.gz
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
*** Failed to download the package list from https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/target/packages/Packages.gz

Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VANTW/packages/Packages.gz
wget: server returned error: HTTP/1.1 404 Not Found
*** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VANTW/packages/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/packages/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/luci/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/routing/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/telephony/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/target/packages/Packages.gz, wget returned 1.
 * opkg_download: Failed to download http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VANTW/packages/Packages.gz, wget returned 1.

**Comment by Ansuel** [comment]
il problema è altrove dobbiamo ancora indagare. (per i più esperti per qualche oscuro motivo non si installa il pacchetto specifico con il fix di questo esatto problema)

**Comment by martgras** [comment]
After I had upgraded somehow openssl was missing
I fixed it by installing openssl from the command line
Note: wget fails because openssl is not setup correctly therefore use curl

```
mkdir /tmp/openssl
cd /tmp/openssl
curl "https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/libopenssl_1.0.2t-1_arm_cortex-a9_neon.ipk" --output libopenssl_1.0.2t-1_arm_cortex-a9_neon.ipk 
curl "https://raw.githubusercontent.com/Ansuel/GUI_ipk/kernel-4.1/base/openssl-util_1.0.2t-1_arm_cortex-a9_neon.ipk" --output openssl-util_1.0.2t-1_arm_cortex-a9_neon.ipk                 

opkg install --noaction libopenssl_1.0.2t-1_arm_cortex-a9_neon.ipk openssl-util_1.0.2t-1_arm_cortex-a9_neon.ipk

cd ~
rm -r /tmp/openssl
```

**Comment by andree93** [comment]
> il problema è altrove dobbiamo ancora indagare. (per i più esperti per qualche oscuro motivo non si installa il pacchetto specifico con il fix di questo esatto problema)

Continuo ad  avere questo problema, anche con l'ultima versione del firmware e della gui. Non riesco ad aggiornare i pacchetti con opkg e ad installarne di nuovi. Ho provato ad installare il pacchetto wget_1.17.1-1_brcm63xx-tch.ipk ma mi viene detto che l'architettura non è quella corretto. A niente è servito installare i file libopenssl_1.0.2t-1_arm_cortex-a9_neon.ipk e  openssl-util_1.0.2t-1_arm_cortex-a9_neon.ipk

**Comment by FrancYescO** [comment]
se ti dice che l'architettura non è corretta o non hai l'ultmi firmware stable o stai installando sul dispositivo sbagliato.
