### ISSUE TITLE
opkg non funziona dopo update firmware tg789vac xtream 35b v8706

### ISSUE THREAD

**Issue by webmst** [Ansuel/tch-nginx-gui#756]
Salve a tutti,
dopo aver eseguito l'upgrade del firmware v8706 su un tg789vac xtream 35b con il file indicato da @FrancYescO  nell'issue #746 ho notato  che il comando 'opkg' non funziona più.

Infatti eseguendo 'opkg update' viene segnalato errore in quanto l'impostazione dei repository è scorretta.

Il mio opkg.conf contiene:

`src/gz attitude_adjustment http://downloads.openwrt.org/attitude_adjustment/12.09.1/brcm63xx-tch/VANTW/packages
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
arch all 100
arch brcm63xx 200
arch brcm63xx-tch 300
`
Qualcuno mi sa indicare i corretti riferimenti?

**Comment by FrancYescO** [comment]
...perchè prima andava?
poi che ci sia VANTW nel tuo opkg mi sembra alquanto strano... puoi controllare quello in /rom/etc/opkg.conf

**Comment by webmst** [comment]
Ciao @FrancYescO e grazie della risposta.

Ti ho ricostruito la sequenza di eventi per inquadrare la casistica; non avevo ancora provato opkg in precedenza su questo router e ho pensato che funzionasse con lo stock firmware v7825 che ho appena sostituito.

Tuttavia non ho mai modificato a mano il mio file opkg.conf e la copia in rom è quasi identica, differisce solo nella parte terminale, mancando delle sole linee con la direttiva 'arch'.

E' ovvio che stavo verificando la possibilità di installare pacchetti aggiuntivi (cosa che dovrebbe interessare a tutti qui), come su ogni buon router basato su openwrt ed ho aperto l'issue per accertarmi che il gestore pacchetti non puntasse ad un repository che possa sostituire scorrettamente i file eventualmente modificati dalla GUI.

In ogni caso, concorderai che - sebbene tch-nginx-gui miri a fornire una GUI estesa di gestione del dispositivo - essa costituisca anche uno o più script che vanno a modificare il funzionamento del sistema, ossia che occorra fare in modo che dopo la sua installazione opkg vada a puntare ad un eventuale repository personalizzato o venga disabilitato per evitare che l'utente attivi accidentalmente un rovinoso update.

Fammi sapere la tua opinione in merito.

**Comment by FrancYescO** [comment]
è giusto quello che dici, il problema è che stare dietro a tutti i dispositivi è un bel po complicato (soprattutto senza averli nemmeno sottomano)

dato che hai titolato la issue "opkg non funziona dopo update" ho immaginato la colpa fosse appunto l'update, al contrario che non ci sia mai stato un feed disponibile per questo dispositivo è molto più probabile

tralaltro l'obbiettivo della GUI è farla funzionare appunto da interfaccia web, avere opkg funzionante ma soprattutto con pacchetti attendibili, richiede un lavoro ad-hoc su ogni dispositivo, non a caso tutte le app testate e funzionanti vengono proposte come installabili solo da interfaccia ... e in ogni caso la sicurezza non c'è mai... non è un software commerciale :D 

per tornare alla issue: c'è da provare se con i feed originali, o con quelli costruiti per i DGA qualcosa si installa, ma di fare un opkg upgrade per ora non sognarlo nemmeno

**Comment by webmst** [comment]
Concordo con quello che scrivi, tuttavia sia analizzando la strada giá fatta dal progetto in poco tempi sia dalle richieste per future funzioni, la strada è giá tracciata: opkg dovrá essere reso funzionale, proprio per cercare di standardizzare, come per la GUI universale
