### ISSUE TITLE
GUI - Change string "gui" in "GUI"

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#757]
@Ansuel 
@FrancYescO 

_**Modifica stringa "gui" in "GUI"**_

Per favore come avete già fatto per altre stringhe cambiate nelle stringhe sorgenti il testo "**_gui_**" in "_**GUI**_"

--- frase non trovata nel codice sorgente. Serve ancora? 

msgid "Don't report any bug, this is a custom **_gui_**! Some bugs could not be related to the current beta firmware."
in
msgid "Don't report any bug, this is a custom **_GUI_**! Some bugs could not be related to the current beta firmware."

--- File www/docroot/modals/modgui-modal.lp

msgid "Resetting to default **_gui_**, please wait..."
in
msgid "Resetting to default **_GUI_**, please wait..."

--- File www/docroot/modals/gateway-modal.lp

msgid "Check this to only root the modem after the firmware is installed.<br/>After this you had to reinstall the **_gui_**.<br/>Expect the web interface to be broken after the upgrade"
in
msgid "Check this to only root the modem after the firmware is installed.<br/>After this you had to reinstall the **_GUI_**.<br/>Expect the web interface to be broken after the upgrade"

_**Funzionalità spostate in diversa scheda**_

Alcune funzionalità sembra siano state spostate dalla scheda Gateway alla scheda GUI e quindi alcune stringhe andrebbero modificate

--- File www/docroot/gateway-snippets/header.lp

msgid "Go to the **gateway** tab and click on the Update button, to autoupdate to the new GUI."
in
msgid "Go to the **GUI** tab and click on the Update button, to autoupdate to the new GUI."

--- File www/docroot/gateway-snippets/header.lp

msgid "Go to the **_gateway_** tab and click on the Update button, to autoupgrade to the new GUI."
in
msgid "Go to the **_gateway_** tab and click on the Update button, to autoupgrade to the new GUI."

Non vedo la necessità di due frasi diverse.
Visto che praticamente dicono lo stessa cosa si potrebbero usare al stessaa frase (a voi al scelta quale usare) per etrambe le situazioni.

**Comment by FrancYescO** [comment]
scrivi se ti accorgi di disaccostamenti, soprattutto di formattazione tra stringhe inglesi e tradotte, cerchiamo di tenere tutto unificato.

**Comment by bovirus** [comment]
@FrancYescO 

Grazie. Ho visto le modifiche.
