### ISSUE TITLE
Function "Reset config to Factory" broken

### ISSUE THREAD

**Issue by lorenzocanalelc** [Ansuel/tch-nginx-gui#758]
When using this function the GUI just breaks, after first loging this is what the GUI looks like 
<img width="1440" alt="Schermata 2019-08-08 alle 00 57 02" src="https://user-images.githubusercontent.com/44505255/62663408-9d21de00-b977-11e9-9421-fdd7deb285b1.png">

**Comment by kevdagoat** [comment]
Clear cache. If not, run ls /www/cards and ls /www/docroot/modals

**Comment by FrancYescO** [comment]
Firmware and gui version

**Comment by lorenzocanale-LC** [comment]
DGA4130 2.2.0_001 Gui 9.3.66 I tried to clear cache no results, after that I resetted to make it work again, but I remember I did it some time ago on another device (TG789vac v2) with another GUI version and the result was the same

**Comment by FrancYescO** [comment]
should be partially fixed with https://github.com/Ansuel/tch-nginx-gui/commit/f37e9bb5e187a1206500053145469e50098a5243

the gui should be visible after reset but there will be a strange "mix" with stock GUI and some missing cards

**Comment by Ansuel** [comment]
can this be tested?

**Comment by lorenzocanale-LC** [comment]
Unfortunately I don't have any Technicolor modem to test right now.

**Comment by lorenzocanale-LC** [comment]
So, I know that I lot went on in the meantime (And I was expecting this function not to work), but again with DGA4132, GUI 9.6.14, the Same Function "Reset config to Factory" not only doesn't work, but it make unaccessible the Modem (DHCP off, not reachable at the default IP and Wifi name set on "SET_BY__SCRIPT"), maybe you should just remove this function

**Comment by Ansuel** [comment]
Thx for the report... Yes the reset function needs to be fixed
