### ISSUE TITLE
Pulsante WPS

### ISSUE THREAD

**Issue by yhcim86** [Ansuel/tch-nginx-gui#76]
Con la versione 8.5.0 e Firmware 1.1.1 non funziona il pulsante WPS fisico nel router invece quello virtuale nella sezione Wireless si.
è possibile farlo rifunzionare o se si vuole limitare il suo uso per sicurezza mettere uno swich che abilita il pulsante fisico del WPS in qualche tab è possibile?
Oppure ho io problemi al pulsante ma mi ricordo che una volta avevo resettato il modem e con gui TIM il pulsante funzionava a dovere

**Comment by Ansuel** [comment]
puoi darmi l'output di questo ?

uci show button

**Comment by yhcim86** [comment]
Ansuel buonasera dove lo do quel comando mi spieghi come e tutti i passi che devo seguire???
Grazie mille

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by yhcim86** [comment]
root@modemtim:~# uci show button
button.reset=button
button.reset.button='BTN_0'
button.reset.action='released'
button.reset.handler='rtfd'
button.reset.min='5'
button.reset.max='30'
button.eco=button
button.eco.button='BTN_1'
button.eco.action='released'
button.eco.handler='wifionoff.sh'
button.eco.min='3'
button.eco.max='8'
button.acl=button
button.acl.button='BTN_1'
button.acl.action='released'
button.acl.handler='acl_button_pressed.sh'
button.acl.min='8'
button.acl.max='20'
button.dect_paging=button
button.dect_paging.button='BTN_2'
button.dect_paging.action='released'
button.dect_paging.handler='ubus call mmpbxbrcmdect.paging toggle'
button.dect_paging.min='0'
button.dect_paging.max='3'
button.dect_registration=button
button.dect_registration.button='BTN_2'
button.dect_registration.action='released'
button.dect_registration.handler='ubus call mmpbxbrcmdect.registration open'
button.dect_registration.min='3'
button.dect_registration.max='30'
button.info=button
button.info.button='BTN_1'
button.info.action='released'
button.info.handler='logger INFO button pressed ; ubus send infobutton '\''{"state":"active"}'\'''
button.info.min='0'
button.info.max='3'
button.wps=button
button.wps.button='BTN_4'
button.wps.action='released'
button.wps.handler='wps_button_pressed.sh'
button.wps.min='0'
button.wps.max='3'
button.ua_register=button
button.ua_register.button='BTN_4'
button.ua_register.action='released'
button.ua_register.handler='logger INFO ua_register pressed ; ubus send button '\''{ "wps" : "pressed" }'\'''
button.ua_register.min='0'
button.ua_register.max='5'

Ecco quello che mi chiedevi Ansuel

**Comment by yhcim86** [comment]
root@modemtim:~# uci show button
button.reset=button
button.reset.button='BTN_0'
button.reset.action='released'
button.reset.handler='rtfd'
button.reset.min='5'
button.reset.max='30'
button.eco=button
button.eco.button='BTN_1'
button.eco.action='released'
button.eco.handler='wifionoff.sh'
button.eco.min='3'
button.eco.max='8'
button.acl=button
button.acl.button='BTN_1'
button.acl.action='released'
button.acl.handler='acl_button_pressed.sh'
button.acl.min='8'
button.acl.max='20'
button.dect_paging=button
button.dect_paging.button='BTN_2'
button.dect_paging.action='released'
button.dect_paging.handler='ubus call mmpbxbrcmdect.paging toggle'
button.dect_paging.min='0'
button.dect_paging.max='3'
button.dect_registration=button
button.dect_registration.button='BTN_2'
button.dect_registration.action='released'
button.dect_registration.handler='ubus call mmpbxbrcmdect.registration open'
button.dect_registration.min='3'
button.dect_registration.max='30'
button.info=button
button.info.button='BTN_1'
button.info.action='released'
button.info.handler='logger INFO button pressed ; ubus send infobutton '''{"state":"active"}''''
button.info.min='0'
button.info.max='3'
button.wps=button
button.wps.button='BTN_4'
button.wps.action='released'
button.wps.handler='wps_button_pressed.sh'
button.wps.min='0'
button.wps.max='3'
button.ua_register=button
button.ua_register.button='BTN_4'
button.ua_register.action='released'
button.ua_register.handler='logger INFO ua_register pressed ; ubus send button '''{ "wps" : "pressed" }''''
button.ua_register.min='0'
button.ua_register.max='5'

Ecco quello che mi chiedevi Ansuel

Fatemi sapere degli aggiornamenti che fate e se vi serve altro.
Grazie mille

Michele Marinelli

________________________________
Da: Escart94 <notifications@github.com>
Inviato: lunedì 16 luglio 2018 03:42
A: Ansuel/tch-nginx-gui
Cc: yhcim86; Mention
Oggetto: Re: [Ansuel/tch-nginx-gui] Pulsante WPS (#76)


@yhcim86<https://github.com/yhcim86>
You need to download PUTTY client and use the SSH connection in order to access to the modem BusyBox.
The username and password are root/root, after login, you can copy & paste the command "uci show button" or simpy write it into the console - after doing this please copy the output code here.

**Comment by FrancYescO** [comment]
Ho appena testato su DGA4132 1.2.0 e 789v2 UNO 17.2 e a me il pulsante WPS sembra funzionare... o per lo meno dopo averli premuti ha iniziato a lampeggiare arancione (e poi rosso) la luce WPS

possiamo considerare il bug risolto?

**Comment by FrancYescO** [comment]
puoi provare ad eseguire da terminale `wps_button_pressed.sh`? dopo che premi il pulsante WPS non accade niente sul led?

quindi stai provando su DGA4130 1.1.1  e GUI 8.7.2?

**Comment by yhcim86** [comment]
Sì sto provando su questo dispositivo.
X la prova ora sono a pranzo questa sera faccio la prova.
Il comando dove lo inserisco?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by FrancYescO** [comment]
Ti colleghi al modem in ssh con putty o quello che sia e lo esegui

**Comment by FrancYescO** [comment]
a me nel momento in cui premo il pulsante su accende il led WPS...mi rimane da pensare é un problema solo dei 4130 se non addirittura solo il tuo pulsante non funzionante...puoi dare le ultime righe del comando `logread` dopo che premi il pulsante? magari troviamo qulacosa lí...

**Comment by yhcim86** [comment]
Buongiorno oggi nel pomeriggio ti mando tutto l'occorrente.
Mi ricordo che con la guida stock Tim il pulsante fisico nel modem va.
Ho fatto delle prove ieri sera e ho visto che se premo il pulsante virtuale nella gui sezione wireless il wps parte solo se lo swich virtuale è su on.
Se lo metto a off non va da gui ma da linea di comando va sempre.
Ditemi voi
Saluti Michele

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by Ansuel** [comment]
puoi darci i log dopo che hai premuto il tasto? e che tasto premi ? ho collegato il mio agtef e il tasto wps funziona correttamente

**Comment by yhcim86** [comment]
Ansuel ho visto che hai chiuso la richiesta io torno alle nove a casa se vuoi ti do il log dimmi come faccio. Cmq premo il tasto laterale sulla sx guardando il modem dal davanti dove ci sono i led

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by Ansuel** [comment]
quale dei due tasti ?

**Comment by Ansuel** [comment]
che ne sono due devi premere quello più verso i connettori

**Comment by yhcim86** [comment]
Appena torno alle 9 ci provo subito e ti mando un messaggio. Grazie mille io nn sapevo che ce ne è 2!!!

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by yhcim86** [comment]
Ansuel mi scuso davvero non ci avevo fatto caso dei 2 pulsanti. Premendo quello da te indicato il wps funziona a dovere. La mia domanda ma quello verso i led che funzione ha ed è collegato alla scheda madre del modem???
Grazie mille e davvero scusami ancora.
Michele

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
