### ISSUE TITLE
Non si connette piu' alla GUI in https ma solo in http (connessione non protetta)

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#760]
Device Model:  DGA4132
Gui Version:  Dev 9.3.72
Firmware :  AGTHP_2.2.0_001

Descrizione del problema :

Volendosi collegare alla GUI ( indirizzo standard  192.168.1.1 ) non consente più la connessione protetta https, ( ho provato sia con Chrome che Firefox ) mentre lo consentiva fino alle versioni della GUI rilasciate ieri 08/08/2019

E non memorizza più la password, sembra un problema di certificato non  valido (sembrava installato sul router e non in locale) . Ho provato ad esportarlo ed installarlo ma continua il problema.  L'attuale certificato è valido dal 29/07/2019  al 26/07/2029 !

**Comment by Ansuel** [comment]
Prova l'ultima dev

**Comment by giulio63** [comment]
ma sono già con l'ultima dev ( la 9.3.72 ) reinstallata più volte. ho aggiunto anche il sito come sito attendibile in proprietà internet di windows 10

**Comment by Ansuel** [comment]
aspetta che si pubblica la nuova versione 3-4 minuti e aggiorna

**Comment by giulio63** [comment]
con la 9.3.73 non mi da più errore sul certificato, mi fa memorizzare la password, ma la connessione rimane "non sicura" . ho provato con diversi browser anche ripulendo la cache , ma con tutti ho la stessa situazione. Non mi ricordo se fosse così anche prima. Ed ho ancora impostato il sito come sito attendibile e fatto ripartire il router. forse deve rimanere così

**Comment by Ansuel** [comment]
O installi il certificato come radice di sistema o continuerà a darti non
sicuro (se sei in https) perché il certificato è self-signed

Il Sab 10 Ago 2019, 16:07 giulio63 <notifications@github.com> ha scritto:

**Comment by giulio63** [comment]
Adesso il certificato si trova in "Autorità di certificazione radice attendibili" , è giusto sia così ?

**Comment by Ansuel** [comment]
Credo ma considera che appena aggiorni firmware cambia il certificato
Ti dà tanto fastidio quel non sicuro ?

Il Sab 10 Ago 2019, 16:39 giulio63 <notifications@github.com> ha scritto:

**Comment by giulio63** [comment]
considerando che allora il problema si ripresenterebbe ad ogni aggiornamento di firmware meglio non farsene un problema in effetti ;-)  grazie per tutti gli aggiornamenti e fix vari
