### ISSUE TITLE
Il changelog non risulta aggiornato ( GUI dev 9.3.72 )

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#761]
Device Model: DGA4132
Gui Version: Dev 9.3.71
Firmware : AGTHP_2.2.0_001

Descrizione del problema :

Il changelog non risulta aggiornato , mentre nella descrizione del rilascio delle versioni 9.3.70 e 9.3.71 doveva esserlo ( ho provato anche cambiando in"Anteprima" e "Stabile" e rifacendo l'aggiornamento

**Comment by Ansuel** [comment]
??? posti uno screen del changelog

**Comment by giulio63** [comment]
nel changelog , di novità rispetto a tutte le precedenti ho solo questa aggiunta : 

9.3     Aggiunto supporto alle app
          Nuova skin unificataMiglioramnti e bugfix vari

9.2     Rebase su nuova base
          Vari rework agli script per una esecuzione più efficente
          Vari fix ai bug presenti nelle versioni precedenti
          E' ora possibile dare priorità ad un dispositivo specifico rispetto a tutta la rete (Tab Gestione 
          Dispositiv)
         Aggiunte nuove funzioni di aggiornamento e possibilità di selezionare l'isp manualmenteAltri 
         miglioramenti che sinceramente non ricordo

pensavo ci dovesse essere tutto o quasi della descrizione presente nel rilascio della dev 9.3.71 anche se sarebbe stato enorme considerando che ci stati tanti miglioramenti

Quindi non è detto che sia un errore quello che si vede nel changelog

**Comment by FrancYescO** [comment]
Facci tu una lista :grin:

**Comment by Ansuel** [comment]
Il fatto è che facciamo le modifiche e poi al momento della stabile ci
viene difficile ricordarci tutto

Il Sab 10 Ago 2019, 16:14 giulio63 <notifications@github.com> ha scritto:

**Comment by giulio63** [comment]
Avete perfettamente ragione ;-) avendo fatto quella lista nella descrizione della 9.3.71 avevo pensato che voleste aggiungere qualcosa in più nel changelog e credevo ci fosse stato qualche problema nel mio aggiornamento, ma tutto ok se quello che vedo è corretto, si può chiudere ;-)
