### ISSUE TITLE
Unable to change skin / Always GUI Update available

### ISSUE THREAD

**Issue by ndi123** [Ansuel/tch-nginx-gui#762]
Device Model: DGA4132
Gui Version: 9.3.73

After firmware upgrade to 2.1.0 with GUI 9.3.71 i am unable to change the skin. GUI also always says that there is an update and i can not see the installed version number. After upgrade to 9.3.73 there is no change. Log says that the stylesheet could not be found (does not look into the right subdirectory):

Sat Aug 10 14:46:10 2019 daemon.err nginx: 2019/08/10 14:46:10 [error] 24531#0: *23 open() "/www/docroot/theme/style.css" failed (2: No such file or directory), client: 192.168.1.223, server: localhost, request: "GET /theme//style.css?version= HTTP/1.1", host: "192.168.1.1", referrer: "https://192.168.1.1/"

[upgrade.log](https://github.com/Ansuel/tch-nginx-gui/files/3488830/upgrade.log)

![grafik](https://user-images.githubusercontent.com/34609222/62821953-4128a680-bb7d-11e9-873e-a0f0d01eb213.png)

![grafik](https://user-images.githubusercontent.com/34609222/62821993-aa101e80-bb7d-11e9-8bca-fcf8f223062a.png)

**Comment by White191094** [comment]
Anche io appena aggiornato alla release stabile della GUI e alla AGTHP 2.1.0 successivamente ho lo stesso problema. La sezione "Impostazioni GUI" non tiene salvate le modifiche appena clicco su SALVA. E quindi di conseguenza non riesco a personalizzare la GUI. Risolvi Ansuel. Grazie. 👍

**Comment by FrancYescO** [comment]
Should be fixed with https://github.com/Ansuel/tch-nginx-gui/commit/293a098e822f42979ffb02ba37b42fc3a89a1abd

Could you confirm updating?

**Comment by ndi123** [comment]
> 
> 
> Should be fixed with [293a098](https://github.com/Ansuel/tch-nginx-gui/commit/293a098e822f42979ffb02ba37b42fc3a89a1abd)
> 
> Could you confirm updating?

Yeah, it's working again.
