### ISSUE TITLE
Aggiornamento Gui ultima versione dev 9.3.77

### ISSUE THREAD

**Issue by yhcim86** [Ansuel/tch-nginx-gui#764]
A me su AGTEF firmware 2.0.0 non si istalla la gui dev. 9.3.77 da errore quando vado a cliccare il pulsante aggiorna: Downloading GUI file...
ERROR: Removing upgrade file and aborting.
Striscia da verde mentre fa il download a rossa quando da questo errore.
Provato anche con il comamdo upgradegui da ssh ma da lo stesso errore.
Sono fermo alla 9.3.76 e mi da che c'è un aggiornamento disponibile la gui

**Comment by giulio63** [comment]
prova in "Impostazioni GUI" a cambiare momentaneamente il "canale aggiornamento" a "stabile" . a me con lo stesso messaggio di errore, cosi' ha funzionato. consiglio il comando "upgradegui"

**Comment by yhcim86** [comment]
Edit:

Passato da gui sviluppatore a gui stabile e si è aggiornato correttamente alla 9.3.77 e poi rimesso in sviluppatore non mi trova più l'aggiornamento dunque sembra che lo ha caricato giustamente.
Ora mi trovo su gui dev 9.3.77 praticamente l'ultima rilasciata.

**Comment by yhcim86** [comment]
Si può chiudere la issue grazie
