### ISSUE TITLE
Missing modem image on DJA0231 (VCNT-A) in Modem Tile

### ISSUE THREAD

**Issue by gavindi** [Ansuel/tch-nginx-gui#765]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: 
Gui Version: 9.3.77

Description of problem: Missing Router Image from modem tile.

How to reproduce (if possible): Load the interface

Media/Photos (if possible):

![image896-3-5](https://user-images.githubusercontent.com/940596/62981498-ba214a00-be6c-11e9-905e-72dea1c0435b.png)
Here are some images that can be used:
![smart-modem-gen-2](https://user-images.githubusercontent.com/940596/62981568-dde49000-be6c-11e9-948c-b2d2d5192c06.png)
![1564709310221](https://user-images.githubusercontent.com/940596/62981581-e76df800-be6c-11e9-8cd4-1f0339a8beb3.jpg)
![1558928633914](https://user-images.githubusercontent.com/940596/62981584-eb017f00-be6c-11e9-8ee0-10713e4a1580.png)

**Comment by gavindi** [comment]
Hi,
The image is still missing. From the logfile:
Mon Aug 19 05:13:58 2019 daemon.err nginx: 2019/08/19 05:13:57 [error] 17896#0: *179 open() "/www/docroot/img/gateway_nil.webp" failed (2: No such file or directory), client: 10.0.0.35, server: localhost, request: "GET /img/gateway_nil.webp HTTP/1.1", host: "10.0.0.1", referrer: "https://10.0.0.1/cards.lp"

**Comment by FrancYescO** [comment]
need result of `uci show env` ... not really necessary but censure parts of serial/keys/mac/whatyouwant

**Comment by gavindi** [comment]
Here you go:
env.var=envvars
env.var.company_name='Technicolor'
env.var.prod_friendly_name='Technicolor DJA0231'
env.var.CONF_VERSION='CRF947'
env.var.logfilter='ALL'
env.var.variant_friendly_name='DJA0231'
env.var.prod_name='Technicolor'
env.var.prod_number='DJA0231'
env.var.ssid_prefix='Telstra'
env.var.embedded_mobile='EG06'
env.var.rtfds='0'
env.var.landing_page='1'
env.var.oui='A491B1'
env.var.hardware_version='VCNT-A'
env.var.prod_description='Technicolor Internet Gateway Device'
env.var.friendly_sw_version_activebank='18.1.c.0347-2881005-20190523153008-6a3ef3910786bea2dc5eba30be662c1e240c5fa8'
env.var.friendly_sw_version_passivebank='18.1.c.0241-2881004-20181109140419-004fc7a5f443fe4084606825e60e10b08d78dc20'
env.var.local_eth_mac='xxxxxxxxxxxxx'
env.var.local_wifi_mac='xxxxxxxxxxxxx'
env.var.banksize='157024256'
env.var.serial='CP1844RAA64'
env.var._provisioning_code='Telstra'
env.var.ssid_mac_postfix_r0='C6CFDD'
env.var.default_key_r0_s0='xxxxxxxxxxxxx'
env.var.default_wep_key_r0_s0='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r0_s0='xxxxxxxxxxxxx'
env.var.default_key_r0_s1='xxxxxxxxxxxxx'
env.var.default_wep_key_r0_s1='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r0_s1='xxxxxxxxxxxxx'
env.var.default_key_r0_s2='xxxxxxxxxxxxx'
env.var.default_wep_key_r0_s2='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r0_s2='xxxxxxxxxxxxx'
env.var.default_key_r0_s3='xxxxxxxxxxxxx'
env.var.default_wep_key_r0_s3='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r0_s3='xxxxxxxxxxxxx'
env.var.ssid_mac_postfix_r1='C6CFE5'
env.var.default_key_r1_s0='xxxxxxxxxxxxx'
env.var.default_wep_key_r1_s0='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r1_s0='xxxxxxxxxxxxx'
env.var.default_key_r1_s1='xxxxxxxxxxxxx'
env.var.default_wep_key_r1_s1='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r1_s1='xxxxxxxxxxxxx'
env.var.default_key_r1_s2='xxxxxxxxxxxxxx'
env.var.default_wep_key_r1_s2='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r1_s2='xxxxxxxxxxxxx'
env.var.default_key_r1_s3='xxxxxxxxxxxxx'
env.var.default_wep_key_r1_s3='xxxxxxxxxxxxx'
env.var.default_wps_ap_pin_r1_s3='xxxxxxxxxxxxx'
env.var.bootloader_version='18.09.1075-0000000-20180301100247-8fbfe36621ec8467ca5d05b5508d44d40df8d772'
env.var.bootloader_oid='5a97cfc3835b67358c787a03'
env.var.provisioning_code='Telstra'
env.var.unlockedstatus='0'
env.rip=ripcontent
env.rip.eth_mac='xxxxxxxxxxxxx'
env.rip.wifi_mac='xxxxxxxxxxxxx'
env.rip.usb_mac='xxxxxxxxxxxxx'
env.rip.chip_id='005CB733'
env.rip.variant_id='TE'
env.rip.pba_tocom='3782004A'
env.rip.fia='L1'
env.rip.factory_id='CP'
env.rip.company_id='TMBB'
env.rip.board_mnemonic='VCNT-A'
env.rip.factory_date='181114'
env.rip.product_id='0'
env.rip.serial='1844RAA64'
env.rip.modem_access_code='xxxxxxxxxxxxx'
env.rip.sfp='0'
env.rip.sw_flag='E1'

**Comment by gavindi** [comment]
As of 9.3.96, still not working but it seems closer to being correct.
![Modem-DJA0231](https://user-images.githubusercontent.com/940596/63233108-571b2300-c271-11e9-9caf-23ad7047c1fc.png)

**Comment by nutterthanos** [comment]
The file is there but it’s not displaying the image.

**Comment by gavindi** [comment]
Mon Aug 19 13:01:45 2019 daemon.err nginx: 2019/08/19 13:01:44 [error] 19985#0: *780 open() "/www/docroot/img/gateway_DJA0231.webp" failed (2: No such file or directory), client: 10.0.0.35, server: localhost, request: "GET /img/gateway_DJA0231.webp HTTP/1.1", host: "10.0.0.1", referrer: "https://10.0.0.1/cards.lp"

**Comment by nutterthanos** [comment]
Should be fixed now just a typo with the image files having spaces.

**Comment by gavindi** [comment]
Confirmed fixed. Thanks.
