### ISSUE TITLE
Newline needed in Internet Access tile between WAN4 & WAN6 

### ISSUE THREAD

**Issue by gavindi** [Ansuel/tch-nginx-gui#766]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: DJA0231 (VCNT-A) - But also seen in TG800VAC & TG799VAC
Gui Version: 9.3.77 and others

Description of problem: There is no newline after uptime. WAN6 IP directly continues on.

How to reproduce (if possible):Load the interface

Media/Photos (if possible):
![rect941-1](https://user-images.githubusercontent.com/940596/62981758-7b3fc400-be6d-11e9-819e-109afa2c28b6.png)

**Comment by gavindi** [comment]
An unexpected consequence on this is now the IPv6 statue is mostly off the tile and can't been seen. I don't know what is better. :/
![Internet Access](https://user-images.githubusercontent.com/940596/63122557-65a3d900-bfea-11e9-905c-28974b305dc8.png)

**Comment by FrancYescO** [comment]
i suposed that this could happen but i don't see other solution more than removing some info...
