### ISSUE TITLE
cannot activate NCS wifi / GUI logouts after 30sec / missing update button - Gui 9.3.86 AGTEF 2.1.0

### ISSUE THREAD

**Issue by yhcim86** [Ansuel/tch-nginx-gui#769]
Vi linko per far prima il post su il punto tecnico adsl: 

@Ansuel  e @FrancYescO  con un upradegui da putty la gui sembra essere migliorata.

Nella prima Tab è ricomparso il form per il riavvio pianificato e anche l'aggiornamento software.
Rimane il problema che dopo circa 30 secondi la Gui ti butta fuori e bisogna riaccedere alla stessa tramite login e password.
Problema dei led se attivo il pulsante led eco si spegnono i led eccetto il power che resta verde fisicamente e sia sulla tab diagnostica led.
Se lo disattivo mi si riaccendono tutti i led compresi quelli della radio wifi 2,4 e 5ghz e gli altri sia fisicamente che da tab diagnostica.
Non funziona ancora il tasto NCS WIFI se messo a on e fatto salva al refresh della gui te lo ritrovi a off e la funzione non viene svolta sia fisicamente sui led del modem che sia sulla tab diagnostica della gui parte led.
Numero errato regole Wifi nella tab pianificazione mi da 3 regole pianificazione wireless ma invece ce n'è solo una che lascia attive le radio 2,4 e 5Ghz dalle 8.30 di mattino alle 23.30 di sera di tutti i giorni.
Provato a cancellare la regola e a ricrearla fa sempre la stessa cosa di prima.
Mi dite cosa volete un logred come faccio a farlo?
Volete un zip debug???
Fatemelo sapere anche dove devo mandarlo.
[DebugHelper2019-08-14-1804.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3502216/DebugHelper2019-08-14-1804.tar.gz)

**Comment by dga4130-renato** [comment]
confermo la disconnessione per inattivita. dga4132 AGTHP_2.2.0_001 gui 9.3.87. circa 30 secondi

**Comment by FrancYescO** [comment]
Servono i passi per riprodurre perché a me con succede...

-accedete
-restate fermi sulla pagina statistiche 30 secondi (ci son restato un minuto...)
-torna da solo al login?

**Comment by dga4130-renato** [comment]
tema red. pagina statistiche. 27 secondi

**Comment by yhcim86** [comment]
Buon giorno e buon ferragosto io ho il tema viola ma comunque stessa cosa di renato. 
Io sto anche nella pagina delle caselle senza fare niente e dopo un po di secondi ecco che ti butta fuori e riappare la pagina di login.
Fa questo problema anche accedendo in assistenza cioè come utente assist
Ora ti carico il Conf francyesco e poi ti metto il link qui
Mandami la tua mail per favore

**Comment by yhcim86** [comment]
Ecco il config che mi hai richiesto Francesco.
C'è anche un Bug sulla pianificazione Wifi che ti spiego dopo se vuoi ok???
[config AGTEF 2.1.0 GUI 9.3.87 Michele.zip](https://github.com/Ansuel/tch-nginx-gui/files/3504927/config.AGTEF.2.1.0.GUI.9.3.87.Michele.zip)

**Comment by dga4130-renato** [comment]
ho un altro dga4132 con firm 2.1. ho fatto ypgradegui da shell. questo e' l'errore.
Root Script: Applying specific model fixes...
Unknown package 'busybox_telnet'.
Package libopenssl (1.0.2o-1) installed in root is up to date.
Unknown package 'openssl-util'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for busybox_telnet found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package busybox_telnet.
 * pkg_hash_fetch_best_installation_candidate: Packages for openssl-util found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package openssl-util.
cp: can't stat '/tmp/telnet_orig': No such file or directory
Root Script: Removing ripdrv and resuming root process...

poi l'ho aggiornato a 2.2.0 e l'errore e' andato a posto. liscio come l'olio

**Comment by dga4130-renato** [comment]
Visto che luci non disconnette ho pensato che se faccio un login e aspetto il logout catturo il system log, se puo' servire.


Thu Aug 15 11:34:50 2019 daemon.err nginx: 2019/08/15 11:34:50 [error] 31215#0: *43 [lua] session.lua:217: POST without CSRF token, client: 192.168.0.2, server: localhost, request: "POST /authenticate HTTP/1.1", host: "192.168.0.1", referrer: "http://192.168.0.1/"
Thu Aug 15 11:34:57 2019 daemon.info odhcpd[5859]: Using a RA lifetime of 0 seconds on wl1_1
Thu Aug 15 11:34:57 2019 daemon.notice odhcpd[5859]: Failed to send to ff02::1%wl1_1 (Permission denied)
Thu Aug 15 11:35:27 2019 daemon.info odhcpd[5859]: Using a RA lifetime of 0 seconds on wl0_1
Thu Aug 15 11:35:27 2019 daemon.notice odhcpd[5859]: Failed to send to ff02::1%wl0_1 (Permission denied)

**Comment by dga4130-renato** [comment]
Nella configurazione ho trovato questi due valori, la tempistica concide, circa 30 sec....

web_back.default.timeout='30'
web_back.default.backOffMethod='exponential'
web_back.assistance=sessionmgr
web_back.assistance.passpath='/password'
web_back.assistance.loginpath='/login.lp'
web_back.assistance.salt_seed='B11F69E9'
web_back.assistance.users={'usr_assist'}
web_back.assistance.timeout='30'

**Comment by yhcim86** [comment]
Ragazzi ecco il link della configurazione chiesto: https://mega.nz/#!X8F3XACK!d_R4fppBivXoTRbiGUkjAfFOhpOH08PNBPis0BQ6NEE

Cosi potete meglio vedere cosa c'è che non va

**Comment by dga4130-renato** [comment]
Ho eseguito il downgrade alla 9.3.77 stabile ed il timeout e' scomparso.
tornando alla 9.3.89 il problema si ripresenta.

**Comment by gavindi** [comment]
I'm experiencing the same here. Downgrading fixes it. going back to dev and the problem reoccurs.

**Comment by FrancYescO** [comment]
culprit of logouts is this commit https://github.com/Ansuel/tch-nginx-gui/commit/063f66f3dcd139faac194aac500beb813446f6e4 (GUI >=9.3.83)... investigating...

**Comment by FrancYescO** [comment]
@yhcim86 fammi sapere se ora wifi nsc funziona...

**Comment by yhcim86** [comment]
Ciao ho verificato il funzionamento e ora va bene però devi invertire il funzionamento dello switch perchè la funzione NSC WiFi a on accende i led dei canali wifi anche se nessun client è collegato alle stesse; invece mettendolo a off accende il led relativo alla wifi utilizzata dal client dunque o modifichi la descrizione del tasto oppure inverti la funzione on- off.
Puoi aggiungere un tasto virtuale che simula la pressione del tasto info fisico del modem nella Gui?
In più riguardo al buttare fuori l'utente dalla giu sei riuscito a darci un occhio??

**Comment by FrancYescO** [comment]
gentilmente teniamo problemi e funzionalita' diverse in issue diverse altrimenti non ci capiamo piu' nulla.

l'argomento dello switch NSC e' gia' stato affrontato, il comportamento e' un po contorto ma e' cosi che deve funzionare, e' anche spiegato nel banner poco sopra nell'interfaccia.

riguardo il tod wifi gia' c'e' una issue aperta https://github.com/Ansuel/tch-nginx-gui/issues/730 quindi si parla li di tutti i problemi a riguardo.

il resto verra' affrontato e risolto in seguito

**Comment by yhcim86** [comment]
Accende i led Wi-Fi se almeno un client è connesso alla radio corrispondente.
NSC WiFi on/off

Mi sembra si che sia contorto ma la descrizione allora è sbagliata perchè se lo metto a on mi accende tutti i led indifferentemente se lo metto a off fa quello che deve fare.
Si potrebbe cambiare la descrizione scrivendo:
Se a OFF esegue la funzione "Accende i led Wi-Fi se almeno un client è connesso alla radio corrispondente"
Se a ON esegue la funzione "Accende i led Wi-Fi indistintamente da chi è connesso alla radio corrispondente"
Credo che cosi chi vuole usarlo almeno capisce come va messo lo switch.
Grazie mille per le altre issue te le scrivo distintamente che dici?

**Comment by gavindi** [comment]
As of 9.3.93, the GUI no longer times out after 30sec. Good work! :)

**Comment by FrancYescO** [comment]
Closing this issue as major of bugs got fixed.

@yhcim86 aprine altre divise (o magari aggregati a questa generica https://github.com/Ansuel/tch-nginx-gui/issues/650) se vuoi proporre altro..
