### ISSUE TITLE
Unable to save Local Network settings DGA4131

### ISSUE THREAD

**Issue by binc0** [Ansuel/tch-nginx-gui#772]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:
[DebugHelper2019-08-16-1635.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3510047/DebugHelper2019-08-16-1635.tar.gz)
</b>

Device Model: DGA4131FWB
Gui Version: 9.3.89

Description of problem: Unable to save Local Network settings Error 500

How to reproduce : Go to Local Network settings and change IP or something else and Save.

**Comment by FrancYescO** [comment]
the debug zip was made after the error 500 appeared?

try to put here a result of logread -l50, after triggering the error

**Comment by binc0** [comment]
Yes



**Results:**
Fri Aug 16 19:19:59 2019 daemon.info odhcpd[3446]: Using a RA lifetime of 1800 seconds on br-lan
Fri Aug 16 19:20:00 2019 cron.info crond[2430]: USER root pid 7337 cmd /usr/bin/thermalProtection
Fri Aug 16 19:20:17 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:20:44 2019 daemon.err nginx: 2019/08/16 19:20:44 [error] 19245#0: *162 [lua] session.lua:217: POST without CSRF token, client: 10.0.0.149, server: localhost, request: "POST /authenticate HTTP/1.1", host: "10.0.0.1", referrer: "http://10.0.0.1/"
Fri Aug 16 19:21:17 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:21:47 2019 kern.warn kernel: [113988.094000] dhd_wait_pend8021x: TIMEOUT
Fri Aug 16 19:22:17 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:22:38 2019 daemon.warn odhcpd[3446]: A default route is present but there is no public prefix on wl0_2 thus we don't announce a default route!
Fri Aug 16 19:22:38 2019 daemon.info odhcpd[3446]: Using a RA lifetime of 0 seconds on wl0_2
Fri Aug 16 19:22:38 2019 daemon.notice odhcpd[3446]: Failed to send to ff02::1%wl0_2 (Operation not permitted)
Fri Aug 16 19:23:17 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:24:17 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:24:38 2019 daemon.notice odhcpd[3446]: Got DHCPv6 request
Fri Aug 16 19:25:00 2019 cron.info crond[2430]: USER root pid 8742 cmd /usr/bin/thermalProtection
Fri Aug 16 19:25:18 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:26:18 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:27:13 2019 daemon.info odhcpd[3446]: Using a RA lifetime of 1800 seconds on br-lan
Fri Aug 16 19:27:18 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:27:53 2019 daemon.warn odhcpd[3446]: A default route is present but there is no public prefix on wl0_2 thus we don't announce a default route!
Fri Aug 16 19:27:53 2019 daemon.info odhcpd[3446]: Using a RA lifetime of 0 seconds on wl0_2
Fri Aug 16 19:27:53 2019 daemon.notice odhcpd[3446]: Failed to send to ff02::1%wl0_2 (Operation not permitted)
Fri Aug 16 19:28:18 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:29:18 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)
Fri Aug 16 19:29:40 2019 daemon.err nginx: 2019/08/16 19:29:40 [error] 19245#0: *168 [lua] session.lua:217: POST without CSRF token, client: 10.0.0.149, server: localhost, request: "POST /authenticate HTTP/1.1", host: "10.0.0.1", referrer: "http://10.0.0.1/"
Fri Aug 16 19:29:50 2019 daemon.err nginx: 2019/08/16 19:29:49 [error] 19245#0: *168 lua entry thread aborted: runtime error: [string "/modals/ethernet-modal.lp"]:863: attempt to index a nil value
stack traceback:
coroutine 0:
	[string "/modals/ethernet-modal.lp"]:863: in function '?'
	/usr/lib/lua/web/content_helper.lua:565: in function 'validateObject'
	/usr/lib/lua/web/post_helper.lua:123: in function 'handleQuery'
	[string "/modals/ethernet-modal.lp"]:1071: in function 'content'
	/usr/lib/lua/web/web.lFri Aug 16 19:30:00 2019 cron.info crond[2430]: USER root pid 16245 cmd /usr/bin/thermalProtection
Fri Aug 16 19:30:00 2019 cron.info crond[2430]: USER root pid 16246 cmd /usr/bin/bulkdata transfer profile_1 profile_2
Fri Aug 16 19:30:10 2019 daemon.info transformer[19068]: async run: /etc/init.d/dnsmasq restart
Fri Aug 16 19:30:10 2019 daemon.info transformer[19068]: async run: /usr/share/transformer/scripts/generate-debug-file.sh dev
Fri Aug 16 19:30:10 2019 user.notice DebugHelper: DebugHelper Started!
Fri Aug 16 19:30:10 2019 user.notice DebugHelper: Removing directory /tmp/DebugHelper-* to prevent duplicates
Fri Aug 16 19:30:10 2019 user.notice DebugHelper: Creating dir
Fri Aug 16 19:30:10 2019 user.notice DebugHelper: Gathering device info...
Fri Aug 16 19:30:10 2019 user.notice DebugHelper: Scanning for log errors...
Fri Aug 16 19:30:11 2019 user.notice DebugHelper: Listing processes...
Fri Aug 16 19:30:11 2019 user.notice DebugHelper: Scanning /etc/config directory...
Fri Aug 16 19:30:11 2019 user.notice DebugHelper: Dev Mode. Not running rootdevice
Fri Aug 16 19:30:11 2019 user.notice DebugHelper: Tarring File...
Fri Aug 16 19:30:11 2019 user.notice DebugHelper: All Done! Zipped file can be found in /tmp/DebugHelper2019-08-16-1930.tar.gz
Fri Aug 16 19:30:11 2019 daemon.info transformer[19068]: async run: /usr/share/transformer/scripts/check_leases; /etc/init.d/miniupnpd-tch restart ;
Fri Aug 16 19:30:12 2019 user.debug syslog: getlanaddrsfrominterface - ifname=br-lan ip=10.0.0.1 mask=255
Fri Aug 16 19:30:12 2019 daemon.notice miniupnpd[16660]: Reloading rules from lease file
Fri Aug 16 19:30:12 2019 daemon.err miniupnpd[16660]: could not open lease file: /var/upnp.leases
Fri Aug 16 19:30:12 2019 daemon.notice miniupnpd[16660]: HTTP listening on port 5000
Fri Aug 16 19:30:12 2019 daemon.notice miniupnpd[16660]: Listening for NAT-PMP traffic on port 5351
Fri Aug 16 19:30:19 2019 daemon.notice [18464]: [mobiled] (WaitingForDevice) runs WaitingForDevice-Main.check(timeout, 1)

**Comment by binc0** [comment]
It does not work yet

### Debug file:
[DebugHelper2019-08-21-1834.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3526316/DebugHelper2019-08-21-1834.tar.gz)

**Comment by FrancYescO** [comment]
Could you confirm is working when disabling ipv6?

**Comment by binc0** [comment]
I'm able to disable ipv6 but it still doesen't work.
