### ISSUE TITLE
In Diagnostica-Stato Led, 3 voci hanno lo stato sempre in "Netdev"

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#773]
Device Model: DGA4132
Gui Version: 9.3.91
Firmware : AGTHP_2.2.0_001

Descrizione del problema : 

Nella Tab **Diagnostica**, in **Stato Led**, 3 voci hanno lo stato sempre in **"Netdev"** e non passano mai allo stato "off" o "on" come gli altri led : 

**wireless**
**internet**
**ethernet**

p.s.: sul modem le indicazioni dei led risultano correttamente visualizzate

**Comment by FrancYescO** [comment]
e' voluto, serve ad indicare che quei led sono collegati allo scambio di traffico su qualche interfaccia.
