### ISSUE TITLE
In Diagnostica - Servizio velocità non effettua il test

### ISSUE THREAD

**Issue by giulio63** [Ansuel/tch-nginx-gui#774]
Device Model: DGA4132
Gui Version: 9.3.91
Firmware : AGTHP_2.2.0_001

Descrizione del problema : 

Nella tab **DIiagnostica**,  **Servizio velocità** non effettua il test

**Comment by FrancYescO** [comment]
come lo hai testato? credo ci sia bisogno di qualche client installato su altro device per provare..

**Comment by giulio63** [comment]
non ho trovato info su questo servizio e non capivo se era una funzionalità dell'ultimo firmware o una vostra aggiunta. pensavo che fosse necessaria qualche impostazione particolare o che volesse qualche indirizzo server particolare ( ho provato l'indirizzo ip di siti siti utilizzati per il controllo della velocità tipo speedcheck.org ), ma non sapevo di client specifici su altri device. voi l'avete testato in qualche modo o sapete di forum/topic sull'argomento ? Grazie

**Comment by FrancYescO** [comment]
e' un'aggiunta di TIM/Technicolor, da quel poco che ho visto sembra il tutto funziona tramite tr143 ora se ci sia un server funzionante non ne ho idea..

**Comment by giulio63** [comment]
ok. ti ringrazio per la risposta e direi che si può chiudere l'issue, sperando in futuro di avere qualche altra informazione sull'argomento. Grazie
