### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#775]
![Screenshot_20190817-112908_Chrome](https://user-images.githubusercontent.com/38593316/63209633-a4698a00-c0e3-11e9-95d5-41ea286715da.jpg)
Nelle schede il pulsante aggiorna è visibile x metà.

**Comment by FrancYescO** [comment]
fixed https://github.com/Ansuel/tch-nginx-gui/commit/6187d6ceb679aa666e0068f173ee3b699d9be6b0
