### ISSUE TITLE
Dropouts

### ISSUE THREAD

**Issue by hereCOMESlappy** [Ansuel/tch-nginx-gui#781]
Do the Dev versions lately increase the xDSL modem power or something by chance?

I have noticed that my sync is higher, however it seems to come at a cost to stability I am having a lot of dropouts with Dev I have reverted to Stable for now

**Comment by FrancYescO** [comment]
nothing changed on xDSL side from GUI...

**Comment by hereCOMESlappy** [comment]
Ok very strange
