### ISSUE TITLE
WiFi Client (not a bug) (Question)

### ISSUE THREAD

**Issue by spokosjr** [Ansuel/tch-nginx-gui#782]
Model: TG788vn v2
Version: 9.3.77
I don't seem to find how i can use the router as a wifi client to connect to another AP.

**Comment by spokosjr** [comment]
If the internal wifi card cant act as a client, would it be possible to connect a usb wifi adapter and use that as a client?

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/777#issuecomment-522338375
