### ISSUE TITLE
SIP Network interface

### ISSUE THREAD

**Issue by spokosjr** [Ansuel/tch-nginx-gui#783]
Device Model: TG788vn v2
Gui Version:9.3.77

Description of problem: When making any changes to a sip network the mmpbxrvsipnet.sip_net.interface changes back to wan even though i used "uci set mmpbxrvsipnet.sip_net.interface=lan"

How to reproduce (if possible): use command "uci set mmpbxrvsipnet.sip_net.interface=lan" then "uci commit" then make any changes to the sip network thtough the gui and last use uci "get mmpbxrvsipnet.sip_net.interface"

Also it would be nice if you could add a dropdown to each sip network so that the interfaces it is using can be changed right from the gui.

**Comment by FrancYescO** [comment]
In my previous tests on other hardware this option was just ignored, mmpbx will use any interface that allow to reach the voip server ... Have you seen any noticeable change when setting the correct interface?

**Comment by spokosjr** [comment]
It wont register until i change the interface
