### ISSUE TITLE
Aria2 not working

### ISSUE THREAD

**Issue by itsmylife44** [Ansuel/tch-nginx-gui#786]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here: 
[DebugHelper2019-08-25-1607.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3538198/DebugHelper2019-08-25-1607.tar.gz)
</b>

Device Model: 
Gui Version: 9.3.77
Versione software
AGTHP_2.0.1
Versione bootloader
17.19.1062-0000000-20170512080206-5bebd9fb97718f93b20bca231a620df630da9918

Description of problem:
Hi , i tried to install aria2 on the DGA ( DGA4132 )
webui is running fine , but it seems he is not applied the settings . 
so it seems the problem is from aria2c 

How to reproduce (if possible):

Media/Photos (if possible):

![rpc](https://user-images.githubusercontent.com/34112129/63651194-93a7bc80-c752-11e9-9773-7c62e373616b.PNG)
![opkg](https://user-images.githubusercontent.com/34112129/63651198-95718000-c752-11e9-91a6-0336da909eb8.PNG)
![luci](https://user-images.githubusercontent.com/34112129/63651199-96a2ad00-c752-11e9-873e-009c32f105b2.PNG)
![conf](https://user-images.githubusercontent.com/34112129/63651203-986c7080-c752-11e9-8ae9-225f007c9a19.PNG)

EDIT : after some research & testing , it seems the .ipk file ist not more compatible with the current system .  

The file in the repo : aria2_1.33.0-1_brcm63xx-tch is broken , i tried the prev version : aria2_1.18.7-1_brcm63xx-tch and its working , but without bittorrent support .

**Comment by FrancYescO** [comment]
Can you be more specific with "is not more compatible" any error show up on install? From what repo you've downloaded both versions?

**Comment by itsmylife44** [comment]
version aria2_1.33.0-1_brcm63xx-tch 

is no more compatible like this : 
aria2c: symbol 'EVP_cast5_cbc': can't resolve symbol

aria2c: symbol 'EVP_bf_cbc': can't resolve symbol

this is the ipk from roleo rep of https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz


version aria2_1.18.7-1_brcm63xx-tch i found it on other github rep , its working but without torrent modul

**Comment by itsmylife44** [comment]
Update : 

i updated the DGA ( DGA4132 ) on last firmware 
AGTHP_2.2.0_001

and now all is working fine
