### ISSUE TITLE
Rebase on Firmware 2.2.0 (fix IPv6)

### ISSUE THREAD

**Issue by tjeh** [Ansuel/tch-nginx-gui#788]
I have successfully installed 2.2.0 (on DGA4132) via Ansuel GUI. Prior to the GUI modification I noticed that i.e. they have a working IPv6 in PPPoe.

So how do we get the ball rolling on the rebase?

**Comment by FrancYescO** [comment]
so with 2.2.0 the modem connect the WAN in both ipv4 and ipv6 (TIM?) out of the box? are you sure this was not happening on 2.1.0 or other 2.0.0> firmware?

**Comment by tjeh** [comment]
I cant speak to other version as I went straight to 2.2.0. For me the issue is, that 2.2.0 TIM allows IP6@WAN whereas 2.2.0 TIM + GUI strangely does not.

I did check (git comparison on unpacked squash image) 1.0.3 TIM vs 2.2.0 TIM and they made noumerus changes to files.

Whats the base firmware for the GUI modifications?

**Comment by Ansuel** [comment]
Can you pls give me more info? A ipv6 test?

Il Mar 27 Ago 2019, 15:38 tjeh <notifications@github.com> ha scritto:

**Comment by FrancYescO** [comment]
Basically is 2.0.0, but if usefull/needed also other things from other firmware are taken...

Do you confirm also from, ie https://test-ipv6.com/ you get all tests passed?

**Comment by tjeh** [comment]
ok so while messing around I managed to get the following "zombie" mode for my DGA4132:

1. recieved device with `1.1.0` stock **TIM GUI**
2. downgraded via  CSRF token / Postman to `1.0.3_closed`
3. rooted device (without firmware flash)
4. installed **Ansuel GUI** manually
5. rebooted (waiting for Bank2 to Bank1 copy to complete)
6. once everything settled, deleted `/root/GUI.tar.gz`
7. upgrade to `2.2.0_closed` via **Ansuel GUI** (checking `delete config` and `root only`)
8. now I have a `2.2.0` stock **TIM GUI**, rooted `root/root`, with WebGUI access `admin/admin`

I guess this would be now a good start to apply the only the necessary `fixes` to:
- disable: CWMP, any callbacks to e.g TIM, any unwanted users (`/etc/passwd`...)
- enable: bridge mode, elevate admin to (tech or whatever is the highest auth level)

If these modifications are done on a `*.patch` level (rather than replacing the ie. `*.lua` files), this might make things easier to apply your modifications on other (as in ie. DGA4310, ...) firmware images / or future updated firmware images?

**Comment by FrancYescO** [comment]
4130 and 4132 have very little difference so yes a patch file with a designed starting firmware can be enought but lot of files integrated in the repo (init.d, transformer mappers upgrade scripts etc..) to port these where they are missing (GUI installed on older firmware/totally different devices)

if you want a "clean" starting point to compare dirs for a rebase you could just extract rbi (https://github.com/FrancYescO/tch_firmware_extracted/tree/AGTEF_2.2.0_001) or look at the /rom folder on your device than compare with the content of this repo (and if you find equal files, is just to be sure these will be ported on all devices/firmwares where this GUI will be installed)

**Comment by stuzzica** [comment]
sono due selettori separati uno attiva ipv6 ovvero fornisce una parte di esso e il secondo effettua la connessione ipv6 alla rete

**Comment by Ansuel** [comment]
Can someone test with non rooted modem and tim isp if ipv6 works (post a screen of the gui and of ipv6.test.com result )

**Comment by stuzzica** [comment]
avrei voluto che si potesse disattivare completamente IPV6 e nel caso di utilizzo che non ci siano problemi tipo col mio TV che dice internet mancante se attivo IPV6 
ma sembrano problemi difficili a quanto pare

**Comment by Ansuel** [comment]
nono ipv6 si può disattivare facilmente... solo devo capire quale magia fanno per farlo funzionare... perchè da me manualmente non va

**Comment by stuzzica** [comment]
veramente IPV6 sembra funzionare se lo attivo e vado anche in internet O.o il browser che uso è edge chromium che lo supporta IPV6

**Comment by stuzzica** [comment]
il brutto e che smette di funzionare il Telefono -_- e quindi e inutile per adesso IPV6

**Comment by stuzzica** [comment]
![Immagine1](https://user-images.githubusercontent.com/53705618/64896513-63cc4480-d680-11e9-90a6-07b1fa406546.jpg)
![Immagine2](https://user-images.githubusercontent.com/53705618/64896514-63cc4480-d680-11e9-9f0e-145f3cf16fc7.jpg)
![Immagine3](https://user-images.githubusercontent.com/53705618/64896516-63cc4480-d680-11e9-8e36-c42bb6643090.jpg)
stato attuale all'attivazione IPV6 O_o

**Comment by Ansuel** [comment]
si ma con gui custom o normale!!!!

**Comment by Ansuel** [comment]
sto chiedendo con modem non rootato capito ?

**Comment by stuzzica** [comment]
Ah ok

Il sab 14 set 2019, 00:01 Ansuel Smith <notifications@github.com> ha
scritto:

**Comment by stuzzica** [comment]
e la tua GUI Ansuel scusa non avevo letto bene

**Comment by FrancYescO** [comment]
duplicate https://github.com/Ansuel/tch-nginx-gui/issues/879
