### ISSUE TITLE
opkg update failed

### ISSUE THREAD

**Issue by itsmylife44** [Ansuel/tch-nginx-gui#789]
Device Model: DGA ( DGA4132 )

last dev version : Versione GUI 9.4.7

Description of problem:
cant do opkg update , it seems rep of  

`http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VANTW/packages/Packages.gz, wget returned 1.`

is not found

How to reproduce (if possible):

Media/Photos (if possible):
![image](https://user-images.githubusercontent.com/34112129/63773957-8cacb580-c8dc-11e9-9efe-c5175942d5a6.png)

**Comment by Ansuel** [comment]
The others repo gets updated correctly
