### ISSUE TITLE
Aggiornamento gui disponibile 

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#79]
Nonostante abbia aggiornato all'ultima versione rimane la notifica dell' aggiornamento disponibile. 
Ho visto hai fatto qualche modifica allo script di upgradegui. Sia per il download, sia per l'upgrade stesso. Potresti spiegarcele.  Grazie

**Comment by Escart94** [comment]
What version are you seeing in the footer? And what version are you trying to install? Thanks.

**Comment by nclmrc** [comment]
6.8.22

**Comment by Escart94** [comment]
Fixed in b5b7e86e2ccbb6ab9497075bcc9f1fd86cd605b1
Thanks for reporting.
