### ISSUE TITLE
Upgrade GUI from GUI card doesn't work

### ISSUE THREAD

**Issue by bandit400** [Ansuel/tch-nginx-gui#793]
Software Version: AGTHP_2.2.0_001
GUI Version: 9.4.18

Trying to verify the version of GUI available online, the process continues without ever ending.
Trying to update by uploading the file from the PC, the process fails without visible errors.
The update via SSH ends without any problems.

[DebugHelper2019-08-31-2109.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3562759/DebugHelper2019-08-31-2109.tar.gz)

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/790#issuecomment-526471853

**Comment by bandit400** [comment]
@FrancYescO , excuse me if I insist, but if there is a button for update and it doesn't work, the solution cannot be to update in another way. It's only another workaround and nothing else. 

And, however, there is still the problem of procedure for checking a new version: by pressing the check button, the check for a new version of GUI continues without ever ending.

**Comment by FrancYescO** [comment]
misunderstanding, fixed https://github.com/Ansuel/tch-nginx-gui/issues/795

**Comment by lorenzocanale-LC** [comment]
I'm still having trouble upgrading from the GUI button, only way to upgrade is "upgradegui" from ssh, when upgrade GUI button is trigger the log reports 
`async run: start-stop-daemon -S -b -x /usr/share/transformer/scripts/wrapper.sh "/usr/share/transformer/scripts/upgradegui GuiRequest"`
But nothing happens, the gui says "In Progress"
