### ISSUE TITLE
Firefox 68.0.2, error 503 after Sign Out

### ISSUE THREAD

**Issue by bandit400** [Ansuel/tch-nginx-gui#794]
Software Version: AGTHP_2.2.0_001
GUI Version: 9.4.18

When using Firefox 68.0.2, after pressing the "Sign out" button, you will be asked to retransmit the data.
When the retransmission is confirmed, a tab with "error 503" appears.

Clearing the cache does not solve the problem.

[DebugHelper2019-08-31-2109.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3562808/DebugHelper2019-08-31-2109.tar.gz)

**Comment by bandit400** [comment]
Software Version: AGTHP_2.2.0_001
GUI Version: 9.4.22

Using Firefox 68.0.2, the proble is still present:

 - Advanced -> Sign out
 - Firefox ask to retransmit the data, press Resend
 - for a very short time appear a card with "error 500 - internal server error"
 - appear the log in page

or 

 - Advanced -> Sign out
 - Firefox ask to retransmit the data, press Cancel
 - appear a card with "error 500 - internal server error", press Go Back
 - appear the log in page

[DebugHelper2019-09-02-0958.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3565008/DebugHelper2019-09-02-0958.tar.gz)

**Comment by SamuelePilleri** [comment]
I've had pretty much the same problem for a while now, also Firefox user.
