### ISSUE TITLE
manca tasto ipv6

### ISSUE THREAD

**Issue by stuzzica** [Ansuel/tch-nginx-gui#796]
ho notato che nella gui di Ansuel nella sezione Accesso internet vi è la mancanza di un tasto di selezione presente invece nella gui tim facende riferimento al IPV6 e tale tasto figurerebbe tra il selettore del NAT e dove inserire il Nome utente

in questo caso non essendoci questa opzione nella finestra della rete locale figura IPV6 non assegnato invece di IPV6 disattivato (mi e successo di mettere il firmware tim e aver disattivato IPV6 dalla schermata Acceso Internet e nell'aggiornare la gui non l'ho potuto piu attivare)

**Comment by FrancYescO** [comment]
con quale firmware? probabilmente è lo stesso selettore che invece si trova nell'area rete locale...
comunque se ne stava parlando già qui https://github.com/Ansuel/tch-nginx-gui/issues/788

**Comment by stuzzica** [comment]
in tutti i firmware ce quel doppio tasto perche hanno funzioni separate
