### ISSUE TITLE
"Cards" sometime doesn't open

### ISSUE THREAD

**Issue by itsmylife44** [Ansuel/tch-nginx-gui#798]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[DebugHelper2019-09-02-2306.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3567100/DebugHelper2019-09-02-2306.tar.gz)

nginx error log : 
[error.log](https://github.com/Ansuel/tch-nginx-gui/files/3567096/error.log)

Device Model: 
DGA ( DGA4132 )
Gui Version: last dev version

Description of problem:
sometimes if i want to open "cards" is not open , i need to change from "IT" to "ENG" and than it works .

**Comment by FrancYescO** [comment]
probably caused by https://github.com/Ansuel/tch-nginx-gui/issues/795

**Comment by FrancYescO** [comment]
Please confirm this is not happening now, or in general is not happening if you don't click check update

**Comment by dga4130-renato** [comment]
Ciao. Succede anche a me già da un paio di versioni fa almeno. Sembra si blocca su schede o statistiche. Se selezioni sta in attesa x sempre. Poi ricarichi la pagina e riparte regolare . Se esci e rientri stesso problema. Strano.

**Comment by FrancYescO** [comment]
lo fa anche con le ultime versioni?

**Comment by dga4130-renato** [comment]
Si. Già da qualche versione imdietto

**Comment by itsmylife44** [comment]
Dopo controllo anche io .

**Comment by dga4130-renato** [comment]
buffo. non sempre succede. terro' sott'occhio e vedro' meglio....

**Comment by dga4130-renato** [comment]
sembra che il problema si verifichi dopo aver selezionato controlla aggiornamenti, o direttamente dopo aver aggiornato. tra l'altro ho aggiornato adesso ed ho notato che spesso la finestra dell'aggiornamento non compare sebbene lo stia gia' facendo. ricaricando la pagina infatti si vede che ha installato la versione nuova.....naturalmente dopo aver atteso che abbia terminato, altrimenti la pagina del router non compare. (ovviamente)

**Comment by nclmrc** [comment]
Notato anche io #795

Inviato da Samsung Galaxy Note 8

Il Gio 5 Set 2019, 23:06 dga4130-renato <notifications@github.com> ha
scritto:

**Comment by dga4130-renato** [comment]
succede indistintamente dalla lingua selezionata.

**Comment by nclmrc** [comment]
log:
`Fri Sep  6 00:05:20 2019 daemon.err nginx: 2019/09/06 00:05:20 [error] 7408#0: *88 lua entry thread aborted: runtime error: [string "009_extensions.lp"]:42: attempt to compare number with userdata stack traceback: coroutine 0:      [string "009_extensions.lp"]:42: in function 'content'  /usr/lib/lua/web/lp.lua:176: in function 'include'      /www/docroot/ajax/get_card.lua:18: in function 'content'        /usr/lib/lua/web/web.lua:264: in function 'process'     content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 192.168.1.4, server: localhost, request: "GET /ajax/get_card.lua?modal=/modals/applications-modal.lp HTTP/1.1", host: "dga4132.home", referrer: "https://dga4132.home/"`

**Comment by itsmylife44** [comment]
anche con le ultime versioni continua a farlo .. anche dopo aver levato l'aggiornamento automatico .

**Comment by itsmylife44** [comment]
ok sembra che si sia risolto ..
adesso c'è un altro problema , e penso sia la scheda delle estensioni . 

![image](https://user-images.githubusercontent.com/34112129/64388112-6b676a00-d03e-11e9-986a-60365c59e304.png)

**Comment by dga4130-renato** [comment]
Se premi controlla aggiornamenti e poi su schede e/o statistiche di inchioda .

**Comment by itsmylife44** [comment]
> Se premi controlla aggiornamenti e poi su schede e/o statistiche di inchioda .

vero . confermo
