### ISSUE TITLE
xDSL Graphics Empty DGA4131FWB

### ISSUE THREAD

**Issue by garis** [Ansuel/tch-nginx-gui#800]
Hi.

Product Vendor: Technicolor
Product Name: MediaAccess DG ( MediaAccess DGA4131FWB )
Software Version: 17.2.0412-2141001-20181215141731
GUI Version: 9.3.77

When I go Diagnostics -> xDSL Graphics all the graphs (DSL Hlog, DSL QLN, DSL SNR, DSL Bits) are empty. I tried leave it there for a bit since I know collecting those time of information can take a while but I didn't noticed any change

Also (but tell me if I need to open another issue), is it normal that `opkg update` search on a link that doesn't exists?
The command results in:

root@OpenWrt:~# opkg update
Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTJ/packages/Packages.gz
wget: server returned error: HTTP/1.1 404 Not Found
*** Failed to download the package list from http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTJ/packages/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx-tch/VBNTJ/packages/Packages.gz, wget returned 1.

Media/Photos (if possible):
![image](https://user-images.githubusercontent.com/13544227/64198532-b93a7180-ce88-11e9-91fb-74e120c8db7e.png)

[DebugHelper2019-09-03-2018.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3570880/DebugHelper2019-09-03-2018.tar.gz)

**Comment by Ansuel** [comment]
need this command from putty

transformer-cli get rpc.xdslctl.

**Comment by garis** [comment]
> need this command from putty
> 
> transformer-cli get rpc.xdslctl.

root@OpenWrt:~# transformer-cli get rpc.xdslctl.
rpc.xdslctl.Us2ScannedBand [int] = 
rpc.xdslctl.HlogUs3 [string] = 
rpc.xdslctl.DslamPort [string] = 
rpc.xdslctl.DslamVersion [string] = 
rpc.xdslctl.Ds4Final [int] = 
rpc.xdslctl.Us2Final [int] = 
rpc.xdslctl.Ds2ScannedBand [int] = 
rpc.xdslctl.HlogUs1 [string] = 
rpc.xdslctl.HlogDs3Split1 [string] = 
rpc.xdslctl.QLNDs4 [string] = 
rpc.xdslctl.Us4Final [int] = 
rpc.xdslctl.Ds3Initial [int] = 
rpc.xdslctl.QLNDs3Split1 [string] = 
rpc.xdslctl.SNRDs1 [string] = 
rpc.xdslctl.Us4Initial [int] = 
rpc.xdslctl.Ds3Final [int] = 
rpc.xdslctl.Ds2Initial [int] = 
rpc.xdslctl.HlogDs4 [string] = 
rpc.xdslctl.Us1ScannedBand [int] = 
rpc.xdslctl.Us3Initial [int] = 
rpc.xdslctl.Ds4ScannedBand [int] = 
rpc.xdslctl.SNRUs4 [string] = 
rpc.xdslctl.Us2Initial [int] = 
rpc.xdslctl.Us3Final [int] = 
rpc.xdslctl.Ds1ScannedBand [int] = 
rpc.xdslctl.SNRUs3 [string] = 
rpc.xdslctl.DslProfile [string] = 
rpc.xdslctl.Us4ScannedBand [int] = 
rpc.xdslctl.SNRUs2 [string] = 
rpc.xdslctl.BitsDs4 [string] = 
rpc.xdslctl.BitsDs3Split2 [string] = 
rpc.xdslctl.Us1Final [int] = 
rpc.xdslctl.HlogUs4 [string] = 
rpc.xdslctl.BitsUs3 [string] = 
rpc.xdslctl.SNRDs2 [string] = 
rpc.xdslctl.Ds4Initial [int] = 
rpc.xdslctl.BitsDs3Split1 [string] = 
rpc.xdslctl.Ds3ScannedBand [int] = 
rpc.xdslctl.BitsDs1 [string] = 
rpc.xdslctl.DslamVersionRaw [string] = 
rpc.xdslctl.SNRDs3Split1 [string] = 
rpc.xdslctl.DslamSerial [string] = 
rpc.xdslctl.QLNDs1 [string] = 
rpc.xdslctl.SNRDs3Split2 [string] = 
rpc.xdslctl.DslMode [string] = VDSL2 Annex B
rpc.xdslctl.DslamChipset [string] = 
rpc.xdslctl.BitsUs1 [string] = 
rpc.xdslctl.Us3ScannedBand [int] = 
rpc.xdslctl.QLNUs4 [string] = 
rpc.xdslctl.QLNUs3 [string] = 
rpc.xdslctl.UsBandNumber [int] = 
rpc.xdslctl.QLNUs2 [string] = 
rpc.xdslctl.QLNDs3Split2 [string] = 
rpc.xdslctl.QLNUs1 [string] = 
rpc.xdslctl.BitsDs2 [string] = 
rpc.xdslctl.Ds1Initial [int] = 
rpc.xdslctl.HlogDs1 [string] = 
rpc.xdslctl.SNRScanBand [string] = 
rpc.xdslctl.HlogDs2 [string] = 
rpc.xdslctl.QLNDs2 [string] = 
rpc.xdslctl.BitsUs4 [string] = 
rpc.xdslctl.SNRDs4 [string] = 
rpc.xdslctl.QLNScanBand [string] = 
rpc.xdslctl.HlogScanBand [string] = 
rpc.xdslctl.HlogUs2 [string] = 
rpc.xdslctl.HlogDs3Split2 [string] = 
rpc.xdslctl.SNRUs1 [string] = 
rpc.xdslctl.BitsUs2 [string] = 
rpc.xdslctl.BitsScanBand [string] = 
rpc.xdslctl.Us1Initial [int] = 
rpc.xdslctl.DsBandNumber [int] = 
rpc.xdslctl.Ds1Final [int] = 
rpc.xdslctl.Ds2Final [int] =

**Comment by Ansuel** [comment]
xdslctl info --show

Il Mer 4 Set 2019, 19:56 garis <notifications@github.com> ha scritto:

**Comment by garis** [comment]
root@OpenWrt:~# xdslctl info --show
xdslctl: ADSL driver and PHY status
Status: Showtime
Last Retrain Reason:    0
Last initialization procedure status:   0
Max:    Upstream rate = 9182 Kbps, Downstream rate = 36976 Kbps
Bearer: 0, Upstream rate = 9182 Kbps, Downstream rate = 35363 Kbps
Bearer: 1, Upstream rate = 0 Kbps, Downstream rate = 0 Kbps
Link Power State:       L0
Mode:                   VDSL2 Annex B
VDSL2 Profile:          Profile BrcmPriv1
TPS-TC:                 PTM Mode(0x0)
Trellis:                U:ON /D:ON
Line Status:            No Defect
Training Status:        Showtime
                Down            Up
SNR (dB):        6.4             6.3
Attn(dB):        29.8            0.0
Pwr(dBm):        14.5            7.4

                        VDSL2 framing
                        Bearer 0
MSGc:           -6              -6
B:              227             227
M:              1               1
T:              0               0
R:              10              12
S:              0.2051          0.7898
L:              9285            2431
D:              16              4
I:              238             240
N:              238             240
Q:              16              4
V:              6               0
RxQueue:                18              18
TxQueue:                6               6
G.INP Framing:          18              18
G.INP lookback:         6               6
RRC bits:               24              24
                        Bearer 1
MSGc:           90              58
B:              0               0
M:              2               2
T:              2               2
R:              16              16
S:              10.6667         16.0000
L:              24              16
D:              1               1
I:              32              32
N:              32              32
Q:              0               0
V:              0               0
RxQueue:                0               0
TxQueue:                0               0
G.INP Framing:          0               0
G.INP lookback:         0               0
RRC bits:               0               0

                        Counters
                        Bearer 0
OHF:            0               0
OHFErr:         19              23
RS:             923494768               1360004313
RSCorr:         38343           4399
RSUnCorr:       0               0
                        Bearer 1
OHF:            16720498                16785203
OHFErr:         11              0
RS:             100322615               67140813
RSCorr:         160             18
RSUnCorr:       16              0

                        Retransmit Counters
rtx_tx:         1118            671
rtx_c:          793             372
rtx_uc:         98              1742

                        G.INP Counters
LEFTRS:         0               4
minEFTR:        35351           9179
errFreeBits:    144760304               37599611

                        Bearer 0
HEC:            0               0
OCD:            0               0
LCD:            0               0
Total Cells:    1084749829              0
Data Cells:     371954970               0
Drop Cells:     0
Bit Errors:     0               0

                        Bearer 1
HEC:            0               0
OCD:            0               0
LCD:            0               0
Total Cells:    0               0
Data Cells:     0               0
Drop Cells:     0
Bit Errors:     0               0

ES:             8               7
SES:            0               2
UAS:            30              30
AS:             268564

                        Bearer 0
INP:            55.00           53.00
INPRein:        0.00            0.00
delay:          0               0
PER:            0.00            0.00
OR:             0.01            0.01
AgR:            35441.05        9201.85

                        Bearer 1
INP:            2.50            4.00
INPRein:        2.50            4.00
delay:          0               0
PER:            16.06           16.06
OR:             47.81           31.87
AgR:            47.81   31.87

Bitswap:        27736/27782             39873/39873

**Comment by garis** [comment]
Out of curiosity I tried the latest version 9.4.29 and it's working, the graphs are showing up the line statistics.

**Comment by garis** [comment]
> Out of curiosity I tried the latest version 9.4.29 and it's working, the graphs are showing up the line statistics.

I talked to soon, now it doesn't show the graphs anymore.

**Comment by FrancYescO** [comment]
try issuing `/etc/init.d/transformer restart` than look at graphs, also report back a logread few seconds later the restart

**Comment by garis** [comment]
> try issuing `/etc/init.d/transformer restart` than look at graphs, also report back a logread few seconds later the restart

`/etc/init.d/transformer restart` solves the problem and the graphs are working even hours later.
Anyhow it seems the problem starts with every boot/reboot.

logread output in the file.
[logs.txt](https://github.com/Ansuel/tch-nginx-gui/files/3579860/logs.txt)

**Comment by Ansuel** [comment]
can you test with latest gui ?

**Comment by garis** [comment]
Seems solved now. After a reboot with the GUI Version 9.4.58 the graphs are showing up without the `transformer restart`.
