### ISSUE TITLE
Internet Dropouts

### ISSUE THREAD

**Issue by Thashiznets** [Ansuel/tch-nginx-gui#801]
Device Model: MediaAccess TG789MYRvac v2 HP 
Gui Version: 9.4.28

Description of problem: Internet is dropping out many times per day

I contacted my ISP (Aussie Broadband) and they say that they can't see any disconnections, they say that it must be the modem itself having a problem.

These dropouts only started occurring sometime in the 9.3.x GUI versions.

Line stats: 
<img width="359" alt="Screen Shot 2019-09-05 at 3 43 23 pm" src="https://user-images.githubusercontent.com/2297007/64314977-1c94e280-cff4-11e9-88dc-94fea7747784.png">

**Comment by Thashiznets** [comment]
I think xDSL modem driver must have changed or something as well because only getting 13.7 up now before was about 14.2, can get 13.9 using a different driver in the list.

**Comment by Thashiznets** [comment]
Getting more with the TP-Link Archer driver or the Telstra TG799 driver whereas before the TG789 driver was delivering even better upstream rate!! What has happened? Wrong driver being selected for TG789?

<img width="359" alt="Screen Shot 2019-09-05 at 4 46 15 pm" src="https://user-images.githubusercontent.com/2297007/64318187-d2642f00-cffc-11e9-8da2-4a317554422f.png">

**Comment by FrancYescO** [comment]
first thing you must try is to restore the stock xdsl driver
`rm -r /overlay/bank_1/etc/adsl/` than reboot
than if still happening you must understand what kind of drop it is.. for example could you ping/open webui during the internet drop?

**Comment by Thashiznets** [comment]
Ok I will try restore the stock driver.

Yes I can load the gui the local network is fine just the VDSL is saying Disconnected and have to wait for it to connect again

**Comment by FrancYescO** [comment]
if the VDSL link just drop there is not much we can do here, it's probably a "physical" issue with your twisted-pair.

just try with the stock driver but i think is something that the ISP should care about (lying if they cannot see a link drop..)

**Comment by Thashiznets** [comment]
Yes that's my conclusion as well. Nothing abnormal in logs. Thanks.
