### ISSUE TITLE
GUI 9.4.43 - Riporta versione 9.4.43-d9df194c

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#807]
La versione GUI 9.4.4.3 riporta all'interno come numero versione GUI-9.4.43-d9df194c.

Perché versione GUI-9.4.43-**_d9df194c_** ?

**Comment by Ansuel** [comment]
come vedi quel codice fa riferimento all'id del commit su github

**Comment by bovirus** [comment]
Le precedenti avevano solo la versione senza l'ID del commit.
D'ora in poi il numero versione sarà così?

**Comment by FrancYescO** [comment]
si

**Comment by bovirus** [comment]
Scusa ma non capisco la necessita nel numero versione dell'info sul commit.

**Comment by Ansuel** [comment]
bhe è utile per capire a quale commit fa riferimento

**Comment by bovirus** [comment]
Io personalmente non ne vedo l'utilità se non rischiare di creare dubbi su chi legge l'info versione.
fate voi.
