### ISSUE TITLE
xDSL Driver can't be switched

### ISSUE THREAD

**Issue by Thashiznets** [Ansuel/tch-nginx-gui#808]
Device Model: TG789MYRvac HP v2
Gui Version: 9.4.43

Description of problem: Can't select xDSL driver

Debug Log error.log shows it referencing null variable
[DebugHelper2019-09-07-1628.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3586313/DebugHelper2019-09-07-1628.tar.gz)

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/commit/da4d9431b42e1b44e2441e3c906cc8f304693e0a

**Comment by nclmrc** [comment]
@FrancYescO su DGA4132 adesso non riesco a modificare il driver

**Comment by Thashiznets** [comment]
The 9.4.44 totally killed my modem when I switched driver, it went into a constant reboot loop I had to factory reset

**Comment by FrancYescO** [comment]
@Thashiznets what driver have you set? btw should be fixed with https://github.com/Ansuel/tch-nginx-gui/commit/6b972903e79e17da4934c3b044798f3212f3c729

**Comment by Thashiznets** [comment]
I had set the TP-Link archer that starts with B at the too of the list for my TG789MYRvac HP v2 I am re-rooting and install latest dev release again will let you know hw it goes

**Comment by nclmrc** [comment]
@FrancYescO ok adeso va. Grazie

**Comment by Thashiznets** [comment]
I was able to switch driver in 9.4.45

**Comment by Thashiznets** [comment]
It is still switching fine but it says this error I don't know if that is a concern? Because it still works

xdslctl: xdslCtl_GetObjectValue error

**Comment by FrancYescO** [comment]
just a "standard error", ignore it
