### ISSUE TITLE
DoS options not working on TG789vac v2 

### ISSUE THREAD

**Issue by Digitalone1** [Ansuel/tch-nginx-gui#809]
Device Model: TG789vac v2
Gui Version: 9.3.77

Description of problem:
In IP Extras > DoS Protect, cannot enable **Enabled** protect and **Rp Filter** options.

Tried to generate a debug report, but it takes too long.

**Comment by FrancYescO** [comment]
already fixed in dev, these options should not be here on this device.

**Comment by Digitalone1** [comment]
Sorry, I don't get it. 

DoS protect should not be on the 798vac GUI? Why?

I managed to solve giving `cp dosprotect_orig dosprotect` and `/etc/init.d/dosprotect enable`.

**Comment by FrancYescO** [comment]
no kernel modules for this device that will make it work.

**Comment by Digitalone1** [comment]
@FrancYescO so it's not working also if I enable it?

**Comment by FrancYescO** [comment]
nope, as i sayd there is no kernel module for these func on this device.
