### ISSUE TITLE
System Extras panel is broken

### ISSUE THREAD

**Issue by Thashiznets** [Ansuel/tch-nginx-gui#810]
TG789MYRvac v2 HP

<img width="285" alt="Screen Shot 2019-09-07 at 8 16 48 pm" src="https://user-images.githubusercontent.com/2297007/64473620-7b04c100-d1ac-11e9-9638-72420c7a7646.png">

I did fresh install of 9.4.44 and 9.4.45 and both do the same thing System Extras just looks lie that. It works if you click it but on the cards page always is undefined

[DebugHelper2019-09-07-2014.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3586493/DebugHelper2019-09-07-2014.tar.gz)
Attached debug logs

**Comment by Ansuel** [comment]
reopen the gui and give me a logread

**Comment by Thashiznets** [comment]
I factiory reset to 9.2.56 and updated from there it fixed
