### ISSUE TITLE
Porta dslam 

### ISSUE THREAD

**Issue by yhcim86** [Ansuel/tch-nginx-gui#814]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: agtef 4130 2.1.0
Gui Version: 9.4.56 sviluppatore

Description of problem: nella sezione statistiche che vi si entra con il 2° tasto in alto a dx nella sezione informazioni xdsl è apparso il seriale del dslam ed è una bella cosa ma è scomparsa la voce che diceva a quale porta sono attestato nello stesso dslam.
Potete reinserire questa informazione?
Grazie mille

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
Probabilmente è stato aggiornato il tuo DSLAM, le informazioni che si riescono a visualizzare cambiano in base al firmware di quest'ultimo.

**Comment by Ansuel** [comment]
@yhcim86 la porta la leggevamo per un bug del firmware sul dslam... hanno finalmente fixato a quanto pare ahhaha

**Comment by yhcim86** [comment]
Però la versione del dslam è sempre la stessa 192.22 dunque se avessero aggiornato il firmware da remoto suppongo doveva cambiare anche il numero di versione non credi?? 
Ma è successo solo a me oppure anche altri cabinet in Italia hanno avuto questo aggiornamento??

**Comment by FrancYescO** [comment]
i cabinet vengono aggiornati sempre "a caso", anche la lettura della versione tempo fa ci eravamo accorti poteva essere non affidabile...

comunque ho appena controllato su un'utenza che ricordavo aveva una versione DSLAM molto vecchia (qualcosa tipo 192.57) e oggi ho visto ha la 192.22 (sempre che sia giusta quella letta) e si legge anche il seriale (ma erano mesi che non la guardavo non so quando sia avvenuto l'upgrade, sicuro più di 6 giorni che è l'uptime attuale da quando è stato riavviato)

**Comment by yhcim86** [comment]
No no avevo sempre la .22 sicuro.
Ma scusa la versione software non incrementa xké come hai fatto un esempio invece va a decrementare il contatore della versione.
Ma tu sei anche un tecnico Tim perché hai potuto vedere la versione software del dslam che facevi in esempio???

**Comment by FrancYescO** [comment]
mi stai facendo venire il dubbio fosse 191.57 in ogni caso non era .22 la versione DSLAM viene comunicata dal DSLAM nel collegamento alcuni modem come i fritz la mostrano chiaramante anche con i firmware ufficiali

l'esempio l'ho fatto semplicemente per dire che avevo notato anche io un DSLAM aggiornato o per lo meno su cui hanno cambiato il firmware...
