### ISSUE TITLE
GUI - Normalizzazione termini/ritorni a capo

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#816]
@Ansuel @FrancYescO 

Secondo me andrebbero fatte alcune modifiche nella GUI nelle stringhe sorgenti (e se necessario di conseguenza nelle stringhe tradotte).

msgid "Reset the modem to original GUI. Some config will be preserved. Modem will still be rooted. To access from ssh use the old password or root"

In questa stringa 
- "ssh" andrebbe modificato in "SSH" 
- per una buona lettura sarebbe stato meglio usare i ritorni a capo (<br/>)

Nelle varie stringhe nei file .po il ritorno a capo viene indicato con

<br>
<br/>
<br />

Credo sia opportuno scegliere una solo di queste modalità e usare sempre quella sia nelle stringhe sorgenti che tradotte.

Grazie.

**Comment by FrancYescO** [comment]
fammi un esempio di stringe usate in modi diversi \n <br> e il normale accapo hanno usi diversi e probabilmente sono da lasciare in quel modo

**Comment by bovirus** [comment]
@FrancYescO 

Prova  a fare un ricareca in webui-core.po e negli altri 

_- comando "br  \" (con spazio in mezzo)_

file webui-core.po righe 345-346-389-349 nel codice br c'è uno spazio

**- comando "br" nel file**

web-framework-tch.po
webui-core.po
webui-parental.po
webui-printersharing.po
webui-telstra.po

**_- comando "br\" nel file_**

web-framework-tch.po
webui-core.po
webui-contentsharing.po
webui-mobiled.po
webui-mobieldongle.po
webui-parental.po
webui-voices.-po
webui-printersharing.po
webui-wizard.po

Qui ci cono più file coinvolti e quindi credo sia giusto usare questa sintassi "bt/" come la predefinita.

Troverai varie sintassi per il codice br tra caratteri < >
Il significato è sempre quello di un ritorno a capo ma con sintassi diversa.

Propongio di cambiare 

- "br /" in "br/" nei file indicati
- "br" in "br/" nei file indicati

in modo da avere una unica sintassi "br/" in tutti i file

**Comment by FrancYescO** [comment]
una buona quantità sono stati inseriti solo nella traduzione italiana, il che è sbagliato perchè causa disallineamenti di formattazione tra italiano e lingua originaria..
Appena possibile faccio un controllo ma tenderò a rimuoverli tutti quelli che non sono presenti nella lingua originale.
Quelli che non sono di stringhe inserite da noi li lascerò come source originale

**Comment by bovirus** [comment]
@FrancYescO 

**_Ti chiedo cortesemente di non rimuovere nulla nella lingua italiana!!!!_**

Perchè secondo me l'interfaccia italiana è **_molto più chiara e comprensibile_** di quella inglese che paragrafi multipli sulla stesa linea.

Quella italiana ha i paragrafi su linee singole in modo che si evidenziano le cose e le si rendono più comprnesibili.

La mia richeista era un'altra.

L'interfccia inglese è in alcuni fatta veramente maie con standard diversi caso per caso.

La mia richeista non è **_quelal di toccare le stringhe italiane_** ma quella di normalizzare nel sorgente le stringhe 

"br" in "br/"
"br /" in "br/" 

Grazie. Ciao.

**Comment by FrancYescO** [comment]
La formattazione deve seguire quella inglese, se i paragrafi sono su una riga su quella inglese o si cambia anche l'inglese o si tiene "sbagliato" anche l'italiano, la formattazione deve essere coerente e soprattutto non cambiarla nei file .po

Poi siamo liberi di cambiarla la formattazione basta che non si faccia nei .po ma nel sorgente.

Personalmente poi in molti casi non mi piace nemmeno vedere tutti quegli accapo preferisco siano affiancati i paragrafi..

**Comment by bovirus** [comment]
@FrancYescO 

Quello che ho chiesto è infatti di cambiare le stringhe nel sorgente e nelle stringhe in inglese.

Per esperienza personale e di altri traduttori (a livello professionale) è dimotsrtato che le frasi troppo lunghe su paragrafi unici tendono a sviare l'attenzione (focus) di chi legge che perde il filo del discorso.

Per questo quando si illustrano info su più righe si consiglia sempre per rendere evidenti di spezzare i paragrafi su linee separate.

**_La mia richeista è di modificare l'inglese (non l'italiano)._**

**Comment by FrancYescO** [comment]
Non sto discutendo su come è stata cambiata la formattazione, puo essere anche meglio, ma **una traduzione che non rispetta la formattazione originale è sbagliata**.

quindi se avrò tempo di guardare anche alla normalizzazione in ogetto mi limiterò a correggere gli errori attualmente presenti nella traduzione che noto

**Comment by bovirus** [comment]
Per favore non agiamo sulle stringhe della traduzione italiana  ma sui file sorgentie e le stringhe ingelsei.

Se sei d'accordo proporrò man mano le varie modifiche dei file sorgenti/stringhe sorgenti per normalizzare la traduzione sull'esempio delle stringhe italiane.

**Comment by FrancYescO** [comment]
discuss continue in the PR https://github.com/Ansuel/tch-nginx-gui/pull/821
