### ISSUE TITLE
Where do i edit the LED file?

### ISSUE THREAD

**Issue by evox225** [Ansuel/tch-nginx-gui#825]
i would like to edit the Power LED to green instead of it been red

https://i.imgur.com/CDEcjlE.png    that's what i want to edit so it displays green on power

Product Name
MediaAccess TG ( MediaAccess TG789MYRvac v2 HP )

GUI Version 9.4.70-184d06d3

**Comment by Ansuel** [comment]
you need to modify the state machine in /etc/ledfw

**Comment by evox225** [comment]
> 
> 
> you need to modify the state machine in /etc/ledfw

thanks that worked perfectly found the line and changed it then rebooted now shows grren. 

I do have another question how can i change the DHCP Lease time in internet access i would like to change the lease expire time to a few months ahead if its possible. https://i.imgur.com/D0m4A0w.png

**Comment by Ansuel** [comment]
you can't change that... is something set by your isp

**Comment by evox225** [comment]
> 
> 
> you can't change that... is something set by your isp

thanks for the information
