### ISSUE TITLE
Bug connessione a singhiozzo su ultimo fw 2.2.0-001

### ISSUE THREAD

**Issue by atfreddy** [Ansuel/tch-nginx-gui#833]
Talvolta la connessione si "blocca", come se andasse a singhiozzo. Ho notato che giocando con le impostazioni del firewall il problema sparisce ma purtroppo il problema si è ripresentato in un secondo momento. Succede in concomitanza all'errore riportato su visualizz. eventi:

daemon.notice | odhcpd[3258] | Failed to send to ff02::1%wl1_1 (Permission denied)

Su impostaz del firewall, risposta a tutti i ping e Modo stealth (sia ipv4 che ipv6) se messi su on e salvate le impostaz., ritornano su off.

Ho provato a reinstallare la GUI ma non ho risolto niente. Aggiungo info debug sotto:

Product Name: DGA
Friendly Name: DGA4130
ISP Name: TIM
FW Version: AGTEF_2.2.0_001
DSL Version: A2pvbH042u
GUI Skin: green
GUI Version: 9.4.70-184d06d3
GUI Hash: 8355d0c38d975d7ab6979a873c7fce6f
GUI Branch: stable
GUI First Page: cards
GUI Random Colour enabled
-----List of Installed Extensions----- none

Versione attiva 18.3.0385-3161005-20190711143038-051b604082da49324e8e6936a77cb879fb76b4e8

--------------------------------------

**Comment by FrancYescO** [comment]
probably the issue is the xDSL driver you're using.

**Comment by atfreddy** [comment]
Uso quello dell'agtef 1.0.4
Ho provato anche con agtef 1.1.0
Come nota che ho dimenticato di inserire, ho il wifi totalmente spento

**Comment by FrancYescO** [comment]
resetta quello di default e controlla se hai ancora problemi

**Comment by atfreddy** [comment]
L'errore daemon.notice | odhcpd[3258] | Failed to send to ff02::1%wl1_1 (Permission denied) lo fa uguale, per la connessione, mi serve tempo per fare dei tests.
Una domanda: ipv6 funziona? Perchè ho provato ad abilitarlo ma non risolve nè l'ipv6 ne i dns ed in più Prefisso IPv6 da sempre 'Exact path not found!'

**Comment by FrancYescO** [comment]
l'errore odhcp ignoralo non c'entra nulla

ipv6 dovrebbe funzionare ma aspettavamo feedback per capire, non avendo tim io non posso far prove

**Comment by atfreddy** [comment]
Se vi interessa, ho tim. IPV6 non è mai funzionato. Sono riuscito a farlo funzionare (rilasciando un ip valido) manualmente ma non mi prende/aggancia i DNS. Ho provato con la gui a metterli manualmente ma niente, mi dice connesso ma non viene dato un indirizzo ip e nessun prefisso ipv6 viene rilasciato.

**Comment by FrancYescO** [comment]
`uci set network.globals.ula_prefix='fd10:1f21:8549::/48'; uci commit network` prova a dare questo comando (quel prefisso indirizzo è casuale e avrebbe dovuto generarlo il firmware stesso) e vedi se assegna i vari ipv6

**Comment by atfreddy** [comment]
Il problema non è tanto quello. Il problema è che se si abilita ipv6, il router rilascia ipv4 ma non aggancia nessun dns, ne ipv4 ne ipv6. Sembra un problema di configurazione errata di routing. Avete da passarmi qualche comando da eseguire (o script) per fare debug approfondito? Fatemi sapere.

**Comment by atfreddy** [comment]
Ho fatto un reset totale e riflashato gui e fw. Allora ipv6 su TIM funziona ma occorre fare modifiche: mtu a 1280, user e pass sono quelle già messe nei files di cfg: CP1720TAZAN-101331@alice6.it e IPV6@alice6 (nota: connessione pppoe è dual stack); ci mette qualche attimo (5/10 secondi) prima di funzionare. Come dns ho messo quelli di CF. Fatto questo, si naviga correttamente (testipv6.com da 10/10) ma con latenza in molti casi di molto superiore.  Spero di essere stato utile in qualche modo, saluti.
