### ISSUE TITLE
Unable to set Encapsulation VCMUX, the Encapsulation field maintain LLC setting

### ISSUE THREAD

**Issue by bandit400** [Ansuel/tch-nginx-gui#834]
Hardware Version: VBNT-S
Software Version: AGTHP_2.1.0
GUI Version: 9.4.70-184d06d3

The Encapsulation field cannot be set; when the VCMUX value is set then the Save button is pressed, when the Broadband tab is reopened the field is always set to LLC.

The anomaly is reproduced as follows:
Go to tab 'Broadband' -> set the fields as follow:

  Broadband type
    WAN Sensing State OFF
    Mode ADSL2+
  Internet VPC
    VP 8
    VC 35
    Encapsulation VCMUX

Press the 'Save' button
Reopen the 'Broadband' tab
The 'Encapsulation' field is 'LLC'

[DebugHelper2019-09-14-1730.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3640234/DebugHelper2019-09-14-1730.tar.gz)

**Comment by Ansuel** [comment]
can you give me config file network and xtm ?

**Comment by bandit400** [comment]
Ok Ansuel, 

the requested files are attached to this message.
in the network file there's two networks that aren't present in my setup:

`config interface 'wlnet_b_24'
	option proto 'static'
	option ip6assign '64'
	option ip6hint '1'
	option netmask '255.255.255.128'
	option ipaddr '192.168.168.1'
	option ifname 'wl0_1'
	option force_link '0'
	option name 'Ospiti-TIM-19572449'
	option ipv6 '0'

config interface 'wlnet_b_5'
	option proto 'static'
	option ip6assign '64'
	option ip6hint '2'
	option netmask '255.255.255.128'
	option ipaddr '192.168.168.129'
	option ifname 'wl1_1'
	option force_link '0'
	option name 'Ospiti-TIM-19572449'
	option ipv6 '0'`

It's correct? Excuse me if my questions are trivial... :-)

[xtm - network.zip](https://github.com/Ansuel/tch-nginx-gui/files/3641120/xtm.-.network.zip)

**Comment by bandit400** [comment]
Working with Firefox 69.0.1 (64 bit). Bug present with Chrome 72.0.3626.96 (32bit). The bug is not always repeatable.

**Comment by bandit400** [comment]
Yes, with Firefox seems to work always . Sometimes Chrome fail to set the field at the desired value.

Now, i've tried multiple times, but i can't reproduce the error with Chrome. Nothing is changed. I don't understand what happen.

Sorry Ansuel for your wasted time if this bug submission end with a false warning.

**Comment by bandit400** [comment]
Ok , it's my fault: when i set my ISP, TIM, the GUI select automatically LLC and not VCMUX. With the ISP manual setup, the GUI maintain VCMUX or LLC setting.
I associated this malfunction with Chrome, but it was a bad evaluation.

I close this bug because the problem does not exist.
