### ISSUE TITLE
Enable Telephone Functions when using Bridge Mode

### ISSUE THREAD

**Issue by Flole998** [Ansuel/tch-nginx-gui#84]
I request an option that allows me to use the Telephone functions while the modem is in bridge mode. It should use the Loopback connection to connect to my locally running Asterisk Server.

It would be great if you could introduce that simple option!

**Comment by Flole998** [comment]
As I wrote: 
> It should use the Loopback connection to connect to my locally running Asterisk Server.

I am using the DGA as a PBX and as a Modem. So the Modem itself is an SIP Server (with 2 Phone Ports), but now I can not use the 2 Phone Ports, even though technically I should be able to.

**Comment by kevdagoat** [comment]
Just put it in voice mode and manually edit in a dsl bridge outlined here: 
https://www.crc.id.au/hacking-the-technicolor-tg799vac-and-unlocking-features/#mozTocId332679

**Comment by Flole998** [comment]
I already modified it to show all cards to me. For me this is "fixed", but I would still consider this as being an issue.

**Comment by kevdagoat** [comment]
You might want to close it for now and I will add a todo list to the repo.
