### ISSUE TITLE
DJA0231 GUI version 9.4.94-da43de07 fails to update.

### ISSUE THREAD

**Issue by Anach** [Ansuel/tch-nginx-gui#840]
Attempting manual or automatic update via the web interface from 9.4.94-da43de07 to 9.4.97 does not complete. No errors are given via the web interface. Update window does not progress passed "IDLE". After rebooting the device, "Check Update" does not show any version beyond 9.4.95, and still fails to update.

With the "Check Update" not being reliable, ans sometimes not completing, I wonder if this is an issue connecting to the update server in the last couple days? I can't really tell much from the GUI, and the "IDLE" message doesn't timeout. How do I perform a GUI update via CLI?

**Comment by Janaue** [comment]
same situation with the dga4132. and the local update trough the gui says ''update failed''

**Comment by Ansuel** [comment]
Update from webuu was broken in recent build
Use upgradegui now it's fixed

Il Lun 30 Set 2019, 14:01 Janaue <notifications@github.com> ha scritto:

**Comment by Anach** [comment]
> 
> 
> same situation with the dga4132. and the local update trough the gui says ''update failed''

Same.

> Update from webuu was broken in recent build Use upgradegui now it's fixed

Thanks. I had no idea what the CLI command was until now.

**Comment by Janaue** [comment]
the upgradegui does not work on 9.4.94-da43de07 , it says on the .94 version:
Update available! Version: 9.4.97
The modem has been updated to version 9.4.94-da43de07 successfully

**Comment by Anach** [comment]
> 
> 
> the upgradegui does not work on 9.4.94-da43de07 , it says on the .94 version:
> Update available! Version: 9.4.97
> The modem has been updated to version 9.4.94-da43de07 successfully

 I had the same message initially during the webui update, but the CLI update worked fine. Did you try again after that message, or try a reboot and try again?

**Comment by Janaue** [comment]
after this message I used the usual command 
bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf -
/etc/init.d/rootdevice force

**Comment by Ansuel** [comment]
not the right way to update

Il giorno mar 1 ott 2019 alle ore 17:06 Janaue <notifications@github.com>
ha scritto:

**Comment by Anach** [comment]
> 
> 
> after this message I used the usual command
> bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf -
> /etc/init.d/rootdevice force
> 
> I try to avoid reboots.

I like to avoid reboots too, especially as it resets my wifi name and password each time. However, I just rebooted and typed 'upgradegui' in the CLI and it updated fine.

**Comment by Ansuel** [comment]
@Anach can you pls open an issue with the wifi and password problem ?
