### ISSUE TITLE
telnet is missing

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#844]
I have DGA4132 GUI Version 9.4.99-bce43c6b with firmware AGTHP_2.0.1_003. I do not have the option to enable telnet. Only SSH and syslog are shown. How do I install telnet now ?

**Comment by BluePlum127** [comment]
Try GUI Settings & Utility >> Install Specific App Online or Upload Specific App via https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/modular/upgrade-pack-specificDGA.tar.bz2

**Comment by Janaue** [comment]
i clicked on the button to get the apps online, it shows a new window with ''idle written'' but nothing happens. then there is written ''Specific App are already Installed'' and there is no button to check online the apps again nor even the possibility to install them through a URL ''Upload Specific App via ''

**Comment by Janaue** [comment]
I resetted the routeur and this time I tried the offline install of telnet_support-specificDGA.tar.bz2

I get in red 'Update failed. Please try again.'' 


I also tried 
```
bzcat /tmp/telnet_support-specificDGA.tar.bz2 | tar -C / -xvf -
ln -s /bin/busybox_telnet /usr/sbin/telnetd
cp /etc/config/telnet_orig /etc/config/telnet

Edit the file /etc/config/telnet and set option enable '1'
 

/etc/init.d/telnet enable
/etc/init.d/telnet start
```

but telnet is not working on firmware 2.1.0 of DGA4132 GUI Version 9.4.99-bce43c6b. This method works on lower firmwares though. The green button for says ''telnet enabled'', but from windows i cannot access telnet.

**Comment by Janaue** [comment]
as i said here https://github.com/Ansuel/tch-nginx-gui/issues/837#issuecomment-542168833
i installed the upgrade package which includes telnet and then it still did not start with 

/etc/init.d/telnet enable
/etc/init.d/telnet start

so I went in the GUI to ''Init Management'' and restarted telnet by clicking on the button

**Comment by BluePlum127** [comment]
I can confirm that after resetting fw 2.0.0 telnet is missing and installing "telnet_support-specificDGA.tar.bz2" + enable in GUI doesn't work.

@Janaue 
I can't find "Init Management" in my GUI. How exactly can I get telnet to work?

**Comment by Janaue** [comment]
@BluePlum127 ok after my lack of gui after a reboot, i erased everything to start fresh
so first my usual config is bank_1 is active (to use tftp if something goes wrong) and booted (because I am okay with modding bank1). My pb was that the bank1 did not boot (orange led) and even when I managed to go to bank2, i could not erase the /overlay/bank1 [no response in wscp]. 

First remove the internet cord.  I managed to get
-firmware 1.0.3 on both banks + root with autoflashgui [ddns advanced method]
-bank1 is active and booted and rooted
then on bank1 I install manually the 9.4.99 gui with 
bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice debug
-then in the GUI, i update to firmware 2.1.0+ check the ''root only after upgrade'' and ''remove config file'' in card ''Modem''
-then the GUI is missing a few cards, like xdsl, so I again do this
bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice debug

at this points, i have firmware 2.1.0 and all cards in the gui.

Now for telnet, I go here 
https://github.com/Ansuel/gui-dev-build-auto/tree/master/modular
and see that the little pack for telnet is for
telnet_support-specificDGA.tar.bz2 	[DEV] Version: 9.3.25 Commit: Ansuel/tch-nginx-gui@8b59acb 

so I choose 
upgrade-pack-specificDGA.tar.bz2 	[DEV] Version: 9.4.99 Commit: Ansuel/tch-nginx-gui@bce43c6 

and on windows, I untar it, then I upload the FOLDER upgrade-pack-specificDGA to /tmp/ on the routeur. With WSCP, I modify the permission of the file ''setup.sh'' in ''/tmp/upgrade-pack-specificDGA'' to be executed by everybody and in putty I run the command
cd /tmp/upgrade-pack-specificDGA
/setup.sh
then in the gui with card ''System Extras'', I enable telnet [green dot]. At this point there is still no telnet enabled. SO I reboot and I then telnet is enabled on firmware 2.1.0 with gui  9.4.99

In card ''Management'' you can go to "Init Management"  and see ''telnetd'' this is the stuff I restarted yesterday, but today a  simple reboot is enough.

**Comment by BluePlum127** [comment]
Damn this sounds kinda complicated... ;)

I've got working telnet back by installing an older GUI version (8.1.11-stable) and then returning back to the latest stable GUI (9.4.70). For some reason version 9.4.99 never worked (empty response or no cards) on my DGA4132 (fw 2.0.0).
I do have 1.0.3 on my second bank so I might start from the scratch as well and flash 2.1.0 on bank1 but the last time I've used the autoflash tool it was very confusing. Don't you think it will work to flash 2.1.0 over 2.0.0 with those two options ticked and then install the latest dev gui + upgrade-pack-specificDGA.tar.bz2 [DEV]?

**Comment by Janaue** [comment]
yes if you already have the custom GUI, you go directly for the update to 2.1.0 with the two options checked, then you install the upgrade pack.

**Comment by crazycorndog** [comment]
i have the very same issue after upgrading my dga4132 to 2.2.0 and installing GUI Version 9.5.38-ba81e28c

i already tried 
> I tried the offline install of telnet_support-specificDGA.tar.bz2
> 
> ```
> bzcat /tmp/telnet_support-specificDGA.tar.bz2 | tar -C / -xvf -
> ln -s /bin/busybox_telnet /usr/sbin/telnetd
> cp /etc/config/telnet_orig /etc/config/telnet
> 
> Edit the file /etc/config/telnet and set option enable '1'
>  
> 
> /etc/init.d/telnet enable
> /etc/init.d/telnet start
> ```
> 
> but telnet is not working on firmware 2.1.0 of DGA4132 GUI Version 9.4.99-bce43c6b. This method works on lower firmwares though. The green button for says ''telnet enabled'', but from windows i cannot access telnet.

and 

> as i said here [#837 (comment)](https://github.com/Ansuel/tch-nginx-gui/issues/837#issuecomment-542168833)
> i installed the upgrade package which includes telnet and then it still did not start with
> 
> /etc/init.d/telnet enable
> /etc/init.d/telnet start
> 
> so I went in the GUI to ''Init Management'' and restarted telnet by clicking on the button. Now telnet works.
> 
> Can the upgrade package be included in the dev release, instead of manually installing it ?

even after a full restart telnet is still not working :(

unfortunately the application i need to use only supports telnet

any suggestions?

**Comment by crazycorndog** [comment]
i now installed upgrade-pack-specificDGA.tar.bz2 via setup.sh (from within that package) and now telnet works
