### ISSUE TITLE
GUI - String "active" (ex. xxx rules active) not useful

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#846]
@Ansuel 
@FrancYescO 

For me the suffix "active" on many settings on main windows is not useful.

Because there no x item active and x items not actiive Then 

"x rules active"

for me could be

"x rules"

**Comment by FrancYescO** [comment]
need specific refs, if these are from the stock technicolor GUI, i'm for taking it as is

**Comment by bovirus** [comment]
As I mentioned there are un.significant "defiend" or "active" text in the conetxt of the function.
There is not active or not active or defined and not defiend features.
Just how may ex. number of rules etc.

Take the webui-core.po.
Make a search on it with "active" or "defined"
this the result.

- msgid "<strong %s>%d UPnP</strong> rule is active"
- msgid_plural "<strong %s>%d UPnP</strong> rules are active"
- 
- msgid "<strong %s>%d Access Control</strong> rule defined"
- msgid_plural "<strong %s>%d Access Control</strong> rule defined"
- 
- msgid "<strong %s>%d Wireless Time Control</strong> rule defined"
- msgid_plural "<strong %s>%d Wireless Time Control</strong> rule defined"
- 
- msgid "<strong %s>%d port forwarding</strong> rule is defined"
- msgid_plural "<strong %s>%d port forwarding</strong> rules are defined"
- 
- msgid "<strong>%d</strong> IPv4 rule(s) defined<br>" -> br is not need
- 
- msgid "<strong>%d</strong> IPv6 rule(s) defined"
- 
- msgid "<strong %s>%d Wireless Control</strong> rule defined"
- msgid_plural "<strong %s>%d Wireless Control</strong> rules defined"
- 
- msgid "<strong %s>%d DoNotDisturb Control</strong> rule defined"
- msgid_plural "<strong id=\"todcard_timeofday\" %s>%d DoNotDisturb Control</strong> rules defined"

word at the end like "active" or "defined" are not useful and make a text longer without add important info.

**Comment by FrancYescO** [comment]
these rules can be inserted (defined) and than disabled, so the active word is just to say that we are referring the count only to the active rules ignoring the count on disabled, for me is just correct as is

**Comment by bovirus** [comment]
It could be true for "active" (if you can enabled/disabled).

Not for functions "defined". There aren't function "not defined".

Otherwise "defined" term is not right and should be changed in" active".

**Comment by FrancYescO** [comment]
defined = counting row inserted (defined)
active = counting only inserted row that are enabled

In my opinion no mod needed..
