### ISSUE TITLE
Update from GUI doesn't work on TG789vac V2

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#847]
Device Model: TG789vac V2
Gui Version: 9.4.97

Description of problem: I'm unable to update the GUI from the GUI itself the card gets stuck on Idle...
I can update only via ssh.
Ssh logread gives :
```
Sat Oct  5 13:44:30 2019 daemon.info transformer[3262]: async run: for pid in $(pgrep -f start-stop-daemon -S -b -x /usr/share/transformer/scripts/wrapper.sh "/usr/share/transformer/scripts/upgradegui GuiRequest"); do logger terminating :  $pid && kill -KILL $pid;done
Sat Oct  5 13:44:30 2019 daemon.info transformer[3262]: async run: start-stop-daemon -S -b -x /usr/share/transformer/scripts/wrapper.sh "/usr/share/transformer/scripts/upgradegui GuiRequest"

```

**Comment by boynet7000** [comment]
It happens on my configuration also: modems works normally (routes traffic, wifi, etc) but updating process doesn't proceed
It happened also with elrder "dev" gui version >70 (sorry, don't remeber which version...)

**Comment by lorenzocanale-LC** [comment]
Still present on 9.5.0, the problem doesn't occur on DGA4132

**Comment by FrancYescO** [comment]
Probably related https://github.com/Ansuel/tch-nginx-gui/issues/836.

**Comment by boynet7000** [comment]
present also on GUI v9.5.2
no error updating via SSH

**Comment by lorenzocanale-LC** [comment]
Present also on DGA4131FWB GUI v9.5.11

**Comment by Cossey** [comment]
Just wanted to confirm that this also happens my router too `TG789MYRvac v2`

**Comment by Ansuel** [comment]
Can someone describe the problem in a better way ?

**Comment by FrancYescO** [comment]
fixed in https://github.com/Ansuel/tch-nginx-gui/commit/214965664d9770fcfd51c0940078a2f0e0b74c55
