### ISSUE TITLE
DGA4131FWB gone

### ISSUE THREAD

**Issue by fnkap** [Ansuel/tch-nginx-gui#848]
Device Model: DGA 4131 FWB
Gui Version: Latest stable

Description of problem: I rebooted the modem, and it's now bricked. There's only a white light on, no life signs, reset button doesn't work.

How to reproduce (if possible): I just updated the GUI

**Comment by FrancYescO** [comment]
Console log needed, probably is an hardware problem, I just have one in the same situation will just bootloop when loading the 5GHz driver and from what I know is a common issue

**Comment by fnkap** [comment]
Can I recover it in some way?

**Comment by kevdagoat** [comment]
Most likely not sadly

**Comment by FrancYescO** [comment]
Mine booted for some time after putting hot air on the 5ghz chip, but is unstable
