### ISSUE TITLE
Voice over IP not registering

### ISSUE THREAD

**Issue by mattodinaturas** [Ansuel/tch-nginx-gui#849]
Device Model: AGTHP Tim Hub
Gui Version: 9.4.70 (latest stable)

Description of problem: Although static IP WAN is configured and the system recognises the presence of internet connection, VoIP (configured with online service, not Telecom Italia's landline) doesn't even try to register. The VoIP dab doesn't say neither "1 line registered" nor "1 line not registered", it simply doesn't try to connect to Messagenet's service

How to reproduce (if possible): try to register a VoIP line

**Comment by kevdagoat** [comment]
Run: 
/etc/init.d/mmpbxd restart

Then post the results of this command:
logread

**Comment by FrancYescO** [comment]
`logread` After mmpbxd restart and screenshot of configs.

**Comment by mattodinaturas** [comment]
https://pastebin.com/06b9AZ6Y

**Comment by mattodinaturas** [comment]
![IMG_20191011_143733_678](https://user-images.githubusercontent.com/30673373/66651993-cb9c8d80-ec34-11e9-97c0-57f608732834.jpg)
![IMG_20191011_143735_022](https://user-images.githubusercontent.com/30673373/66652009-d22b0500-ec34-11e9-8603-dd69ba74949b.jpg)

**Comment by FrancYescO** [comment]
Why 5061 in primary proxy port?!

Phone lines tab screenshot is just useless if you censored all fields

Try to just reset cwmp to get the config from tr069..

**Comment by mattodinaturas** [comment]
It's the right port on Messagenet VoIP
It's censored because they're my user and psw. Do you seriously want them?
I don't understand, I'm a novice

**Comment by mattodinaturas** [comment]
Ok I see. Probably you didn't understood that this isn't Telecom Italia's landline provided VoIP but it's an online service that provides VoIP. I don't have landline at home

**Comment by FrancYescO** [comment]
I'm not asking for the full credentials just a part is ok to understand they are correct, but censoring the full fields there is no way to know what you have inserted

Messagenet have no proxy port 5061 is just a backup port of the primary registrar, you should set this value to 0.

**Comment by lorenzocanale-LC** [comment]
Firnware version? I had the same problem with firmware 2.2.0_002 which was solved with 2.2.0_003

**Comment by mattodinaturas** [comment]
i've done some tests and even by flashing other firmware I face that problem. I didn't test with 2.2.0_003 because I don't find it in the repository

**Comment by FrancYescO** [comment]
i can assume is not a firmware nor a GUI issue but just a configuration issue.

just reset and start over from a clean config, you can also try to configure the VoIP using the stock "sblocco" function as this will unlock the telephony part

**Comment by mattodinaturas** [comment]
i tried MANY times to start over from a clean configuration

**Comment by FrancYescO** [comment]
So you are reiterating the same config error.

Here more info if you want, i'm sure that messagenet is working on this device.

https://www.ilpuntotecnico.com/forum/index.php?topic=80592.0
