### ISSUE TITLE
nginx doesn't restart after reboot

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#85]
nginx doesn't restart after reboot

**Comment by Escart94** [comment]
What do you mean? This is impossible, just wait for It.

**Comment by nclmrc** [comment]
The service nginx doesnt running

**Comment by nclmrc** [comment]
yes manually

**Comment by Escart94** [comment]
If there is any error you can check It through the console.
Anyway I think that this is your fault, maybe you have changed something in the configuration, because It's impossibile that nginx doesn't run automatically.

Please reset your modem and check It again.

**Comment by nclmrc** [comment]
i do /etc/init.d/nginx enable
now start at boot, yesterday i have update nginx to the last version

**Comment by Escart94** [comment]
If you change something you can't do an issue here, this is not the purpose of this GitHub.
You can post here Issue of the original GUI file, If you apply some change we are not responsible for your fault.
I'm closing this right now.

**Comment by nclmrc** [comment]
in the gui file there's the last same nginx version, i only update it from opkg.

Thanks
