### ISSUE TITLE
best firmware version under 2.0 for dga4132

### ISSUE THREAD

**Issue by Janaue** [Ansuel/tch-nginx-gui#850]
I would like to try a firmware version like 1.0.3 up to 1.2.0 on the dga4132 because sometimes on firmware 2.0.1 and ansuel gui  [DEV] Version: 9.4.99  I cannot connect to the router via LAN at 192.168.1.1. Internet is down too from windows, but not according to the router [all LEDs are green].

I installed [DEV] Version: 9.4.99 on firmware 1.0.3 but ALL my LEDs are OFF., even tough ''eco led'' is OFF. even when i enable eco LED and press the info button i get all my LEDs OFF.
On wifi card, I only see wifi APs about the 2,4 ghz, nothing about the 5ghz.

on firmware 1.2.0 with  [DEV] Version: 9.4.99 , ''telephony'' fails to stop for instance and all my LEDS are OFF too.

So:
-What is the best firwmare (any version) compatible with Ansuel GUI for the dga4132 ?
-What is the best firwmare (version under 2.0) compatible with Ansuel GUI for the dga4132 ?

**Comment by FrancYescO** [comment]
GUI is ever developed and tested with newest firmware, so using a version >= 2.1.0 (aka latest stable firmware, look at changelog baseline) is the best choice.

Maintaining the back-compatibility with all firmwares is in the scope of GUI but obviously we have no way (time) to test on all firmware on each release, and obviously the priority is having it working on the newest firmware

ie LED not working is actually a bug of the GUI if you use 1.0.3 firmware

**Comment by Janaue** [comment]
here they say firmware 2.10 does not work with your GUI


Le versioni aggiornate del firmware (v 2.0.0 ->) vanno caricate escusivamente via GUI mod by Ansuel pena la perdita del root.

> 
> Attenzione: caricando il firmware 2.1.0.xxx e successivi si perdono le funzionalità della GUI mod!!!
> Il firmware più recente compatibile con la GUI mod è il firmware 2.0.1.003.

https://www.hwupgrade.it/forum/archive/index.php/t-2870856.html


from firmware 1.0.3, can I install firmware AGTHP_2.2.0_002_CLOSED.rbi with your GUI and keep root ? what should I do to reset config file after updating a new firmware ?

**Comment by Janaue** [comment]
In ''GUI Settings & Utility'' I have 3 options to reset and in ''MODEM
'' i have 3 options again 
<img width="859" alt="sshot-323" src="https://user-images.githubusercontent.com/10972636/66757912-76af8000-ee9d-11e9-8c5f-2b0edc9e7d6a.png">
<img width="400" alt="sshot-324" src="https://user-images.githubusercontent.com/10972636/66757930-816a1500-ee9d-11e9-8574-33d655599e4f.png">

**Comment by FrancYescO** [comment]
The post you referenced is just not updated (@bovirus please update)

All these resets are for different things as described above.

**Comment by Janaue** [comment]
so which reset is good for a clean   update of firmware and installing gui?

**Comment by FrancYescO** [comment]
The one with reset button (same of the one in gateway page)

________________________________

**Comment by Janaue** [comment]
to upgrade from 1.0.3 to 2.1.0, should i check ''remove config file with upgrade'' and ''root only modem after upgrade''  then install the GUI with

>  bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice debug

**Comment by FrancYescO** [comment]
Check both than manually reinstall GUI
________________________________

**Comment by BluePlum127** [comment]
So is it advised to upgrade to 2.1.0? I'm on 2.0.0 and had to reset my modem today (bridge mode). Now telnet isn't working anymore and I wonder if it will work again with 2.1.0?

**Comment by FrancYescO** [comment]
idk if telnet is fixed, but as explained above using latest stable firmware is the better choice

**Comment by BluePlum127** [comment]
I'm only using my DGA in bridge mode and I need telnet support for DSL stats. Hopefully telnet support will be added back soon. Its realy weird that telnet wasn't there anymore after I reset to defaults with 2.0.0. It must be a GUI related problem as it always worked fine before with 2.0.0 and I haven't installed anything than the mod GUI. I'm confused.

**Comment by FrancYescO** [comment]
probably got broken during specif package rework, btw you can just use ssh...

**Comment by BluePlum127** [comment]
I'm using DSLstats 6.5 and afaik there is no ssh support for this (it's the only reason why I do need telnet).

Anyway I've fixed telnet by downgrading the GUI to version 8.1.11-stable (GUI was broken after the downgrade) and than I went back to 9.4.70-stable. Now telnet is working as before with 9.4.70-stable!
The latest dev gui doesn't seem to work with fw 2.0.0 (GUI was broken and I couldn't do the upgrade over the 9.4.70 GUI).

To be honest I'm a bit scared to go up to fw 2.1.0 as I don't know if the old GUI version with working telnet will break something on this fw version. Please add back working telnet support like with 8.1.11-stable, it's really essential for some people.

**Comment by FrancYescO** [comment]
telnet issue still opened here https://github.com/Ansuel/tch-nginx-gui/issues/844
