### ISSUE TITLE
Error in file system-modal.lp

### ISSUE THREAD

**Issue by bandit400** [Ansuel/tch-nginx-gui#856]
GUI Version 9.4.99-bce43c6b

In file system-modal.lp:

row 302...

`if action == "system_trasnfer_bank_1" then`

...should be...

`if action == "system_transfer_bank_1" then`

row 649...

`return resetreboot($("#transfer-bank1-msg"), $(this), "system_trasnfer_bank_1");\`

...should be...

`return resetreboot($("#transfer-bank1-msg"), $(this), "system_transfer_bank_1");\`

**Comment by kevdagoat** [comment]
Create a PR then?!

**Comment by FrancYescO** [comment]
@kevdagoat is right, pretty stupid to open this as an issue 🤪

**Comment by bandit400** [comment]
Uhm. Ok, sorry for this.

**Comment by FrancYescO** [comment]
Do not close as is still an issue 😄

**Comment by FrancYescO** [comment]
fixed in https://github.com/Ansuel/tch-nginx-gui/commit/5ef12049f69f5a058b740d73b036672a3164c069
