### ISSUE TITLE
Don't try on TG-797n v3

### ISSUE THREAD

**Issue by gamesover** [Ansuel/tch-nginx-gui#857]
Since it will brick the router -_-

Please don't ask me how I know that :cry:

**Comment by kevdagoat** [comment]
Yes exactly. I have tried this before and have survived

**Comment by gamesover** [comment]
@kevdagoat thanks for your confirmation.

Since the readme has statement **(and probably not only)**, it sounds it encourages people to try to new models. Probably we can have a list to highlight those models confirmed it will not work. So it may save some unnecessary bricks ;)

It has a line **789vac v1/2/3, 799vac, 800vac and 797n v3 Any ISP: https://hack-technicolor.rtfd.io** in readme. Thus, it is really very easy for people to try on **797n v3**

**Comment by FrancYescO** [comment]
If you want a hope that this will be fixed. Firmware version and install log as debug needed, is pretty sure that you can recover the device with a reset and/or failboot to switch bank.

**Comment by gamesover** [comment]
@FrancYescO thanks for your feedback. I tried to reset a couple of times. But no luck. I can power on, the lan1 light is on if the network cable is inserted. However, the router is refused to auto assign me an ip now. 

ifconfig show the below info
```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:87:c5:63:74  txqueuelen 0  (Ethernet)
```

I manual reset my ip to be 10.0.0.238 and router is 10.0.0.138(previous router ip), no luck.
cannot ping 10.0.0.138 either.

failboot is too trouble to me https://hack-technicolor.readthedocs.io/en/stable/Recovery/#crazy-power-switching. Sorry

**Comment by kevdagoat** [comment]
That is for your docker instance: `docker0`

Sent from Mail for Windows 10

**Comment by gamesover** [comment]
My bad, copied wrong info. Below it is, no ip now.
```
enp4s0f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ea84:c014:b5f0:33b4  prefixlen 64  scopeid 0x20<link>
        ether a8:1e:84:80:6c:a1  txqueuelen 1000  (Ethernet)
        RX packets 325740  bytes 46982685 (46.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 292809  bytes 39086430 (39.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by FrancYescO** [comment]
When the modem started to be unresponsive? Already tried just a reset with button in different moments?
________________________________

**Comment by gamesover** [comment]
After I run `/etc/init.d/rootdevice force`, lots of errors reported. Then I cannot open `10.0.0.138` at browser any more. But my ssh session is still connected. So I decided to power off and power on, this time the modem has no ip assigned to my pc. I cannot ping `10.0.0.138` as described above. I press reset button for 1min, only `eco` button light cycle. This is a bit diff exp. I never try to reset this router before since I just bought it 1 day ago. For other routers, I remember when I reset, all lights including lans and wan lights cycle. This modem currently only one `eco` light cycle after pressing reset for 1 min long. That is diff from https://crowdsupport.telstra.com.au/t5/Modems-Hardware/technicolor-TG797n-v3-lock-out/td-p/423703

**Comment by FrancYescO** [comment]
Serial output is the only hope to know what's going on and can help you to unbrik with the "crazy power switching"

**Comment by gamesover** [comment]
@FrancYescO Thanks so much for your replies. Don't worry. It is a very cheap modem from gumtree. Sorry, I cannot offer any helpful log for you to analyse.
