### ISSUE TITLE
How to install LUCI after installing this tch-nginx-gui?

### ISSUE THREAD

**Issue by gamesover** [Ansuel/tch-nginx-gui#858]
I am a bit confused. Given tch-nginx-gui is running at port 80, if another openwrt LUCI gui is installed, it will be running at port 81? May I ask how to install the LUCI gui? Thank you all.

**Comment by kevdagoat** [comment]
Go to the GUI and click Extensions

**Comment by gamesover** [comment]
Thank you @kevdagoat . Let me find a cheap modem in gumtree first ;)

**Comment by FrancYescO** [comment]
Will run on port 9080 by default, as shown in extensions after the install
