### ISSUE TITLE
Some new installation issues

### ISSUE THREAD

**Issue by ppolce70** [Ansuel/tch-nginx-gui#859]
Hello,
first of all congratulations for the work you are doing.

I have a Technicolor - TG789VAC v2 supplied by Tiscali with stock firmware version 16.3.

I installed the GUI, the following messages were displayed during installation:
- "Root Script: Installing in progress ..."
- "Root Script: Detected low flash space device ..."

what worries me is the second, could it have caused an incorrect installation?
At the end of the installation the "GUI.tar.bz2" file is no longer present in / tmp, but I find it in / root, can I delete it?

When using the GUI the following anomalies occur:

- a card remains in the Loading status and displays the "Error 0undefined" message, the card in question should be "System Extras"
- if I use the export function of the configuration the result is negative and the message "Exporting failed; please try again.". I attach log ([log.txt](https://github.com/Ansuel/tch-nginx-gui/files/3821579/log.txt))
- when I log out the message "Connection issue: error" is displayed

Thanks

**Comment by FrancYescO** [comment]
Replied on https://www.ilpuntotecnico.com/forum/index.php/topic,77988.msg256797.html#msg256797

Duplicated of https://github.com/Ansuel/tch-nginx-gui/issues/836

**Comment by ppolce70** [comment]
Hy,
I don't understand why the issue was closed.

Some of the reported problems are not solved.

Thanks.

Best regards,


________________________________
Da: Francesco M <notifications@github.com>
Inviato: venerdì 8 novembre 2019 01:34
A: Ansuel/tch-nginx-gui <tch-nginx-gui@noreply.github.com>
Cc: ppolce70 <ppolce@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [Ansuel/tch-nginx-gui] Some new installation issues (#859)


Closed #859<https://github.com/Ansuel/tch-nginx-gui/issues/859>.

**Comment by FrancYescO** [comment]
The only valid report of 0undefine is duplicated

The export failure is configuration-related and I'm sure was working on a clean tiscali firmware config

**Comment by ppolce70** [comment]
I don't know what is meant by "clean tiscali firmware config", the only customization done through Tiscali GUI, before installing the GUI in question, is the addition of some port forwarding.

Thanks.

Best regards


________________________________
Da: Francesco M <notifications@github.com>
Inviato: venerdì 8 novembre 2019 08:39
A: Ansuel/tch-nginx-gui <tch-nginx-gui@noreply.github.com>
Cc: ppolce70 <ppolce@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [Ansuel/tch-nginx-gui] Some new installation issues (#859)


The only valid report of 0undefine is duplicated

The export failure is configuration-related and I'm sure was working on a clean tiscali firmware config

**Comment by FrancYescO** [comment]
So probably are port forwardings to break the export :D and no, deleting it will probably not revert the config to the stock state

If you want you can try to temporarily remove config files from /etc/config and search for the one(s) causing the export issue

**Comment by ppolce70** [comment]
OK, but if I use the CLI command "sysupgrade -b / tmp / backup - $ {HOSTNAME} - $ (date +% F) .tar.gz" do I get the same result?

I tried and the operation ended successfully.

Thank you very much

________________________________
Da: Francesco M <notifications@github.com>
Inviato: venerdì 8 novembre 2019 10:19
A: Ansuel/tch-nginx-gui <tch-nginx-gui@noreply.github.com>
Cc: ppolce70 <ppolce@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [Ansuel/tch-nginx-gui] Some new installation issues (#859)


So probably are port forwardings to break the export :D and no, deleting it will probably not revert the config to the stock state

If you want you can try to temporarily remove config files from /etc/config and search for the one(s) causing the export issue

**Comment by FrancYescO** [comment]
As said on the forum, this kind of backup is the one of openwrt that you can reach from the modgui modal

Is not the same as the one in the Gateway modal that is the stock technicolor backup
