### ISSUE TITLE
impossibile entrare nella card accesso internet

### ISSUE THREAD

**Issue by stuzzica** [Ansuel/tch-nginx-gui#860]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[DebugHelper2019-11-09-1050.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/3827139/DebugHelper2019-11-09-1050.tar.gz)

Device Model: GUI DGA4132 con firmware  AGTHP_2.2.0_004
Gui Version: 9.5.1

Description of problem: se provo a entrare nella card Accesso Internet per modificare il tipo di connessione rimane in caricamento infinito ma ho allegato la foto del problema che si riscontra

How to reproduce (if possible): da quando ho aggiornato alla gui 9.5.0 e anche se torno ad altre vecchie rimane sempre questo problema

Media/Photos (if possible):
![Immagine](https://user-images.githubusercontent.com/53705618/68526974-10721d80-02e2-11ea-99ec-2f978262d80d.jpg)

**Comment by stuzzica** [comment]
per entrare nella card va messo l'accesso internet ad off

**Comment by FrancYescO** [comment]
che tipo di connessione hai configurato?

**Comment by stuzzica** [comment]
wan ethernet e accesso internet tramite DHCP

**Comment by stuzzica** [comment]
risolto

**Comment by FrancYescO** [comment]
Cosa hai fatto e quando si verificava il problema?

**Comment by stuzzica** [comment]
si e risolto da solo aggiornando la gui dalla 9.5.1 alla 9.5.2 e io non ho fatto nulla
