### ISSUE TITLE
possible to edit led brightness?

### ISSUE THREAD

**Issue by EvoxOG** [Ansuel/tch-nginx-gui#862]
i want to edit the brightness for the LEDs so they are not at 100% where would i edit this?

**Comment by FrancYescO** [comment]
Depends on hardware, from what i know only on DGA4131 this is possible
https://hack-technicolor.readthedocs.io/en/stable/Resources/#leds
values go from 0 to 255

**Comment by EvoxOG** [comment]
> 
> 
> Depends on hardware, from what i know only on DGA4131 this is possible
> https://hack-technicolor.readthedocs.io/en/stable/Resources/#leds
> values go from 0 to 255

thanks that link helps a lot i did just turn them all off, for now, I see there is no command listed for brightness tho ***unless i have to edit the end of this line?  echo 1 > /sys/class/leds/power:green/brightness <<< with either 0 or 255***  would editing the max brightness or brightness in /sys/class/leds be possible without breaking anything

**Comment by FrancYescO** [comment]
0 is off, 255 is max brightness

Any value in the middle should edit the brightness but practically on unsupported hardware any value >=1 means just "on"
