### ISSUE TITLE
GUI dev 9.5.1 - GUI blank

### ISSUE THREAD

**Issue by bovirus** [Ansuel/tch-nginx-gui#863]
@FrancYescO 
@Ansuel

Device Model: DGA4132
Gui Version: (original): 9.4.99
Gui version (upgrade): 9.5.1

GUi updated via web gui.

No error during update.

After that I log in the webui (with admin/admin) i got a blank web page (tested witH Chrome/Firefox).

If I tried to login with WiNSCP with root/root I got an error (error 127 - it seems that tlenet server is not enable in the modem.

How can do 

To check if SSH is enabled in the modem?
To renable GUI?

Can I reset the modem? How can do that?
What's happen after reset?

Thanks.

**Comment by FrancYescO** [comment]
Winscp does not connect to telnet but to the SCP protocol, telnet   should be manually enabled in system extra 

You should try with putty if is not respond on port 22

Reset will maintain only root

**Comment by bovirus** [comment]
@FrancYescO 

Problem fixed.

I had to copy the tar.bz file in /tmp and run WiNSCP command

**_bzcat /tmp/GUI_dev.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force_**

At the end the script didn't finish itself but show this error

**Root Script: Installing in progress...
ash: !=: argument expected
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
Invalid ISP**

But the GUI now is on again.

Why this happen many times problem when you upgrade the GUI via webUI?

Why instead these command 

**bzcat /tmp/xxxx.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force**

seems works fine always?

**Comment by FrancYescO** [comment]
cannot understand the problem, `/etc/init.d/rootdevice debug` when installing needed

**Comment by bovirus** [comment]
@FrancYescO 

Is not the first time that I got this problem updating GUI mod via web UI.

And anytime the use of WiNSCP and command explained solve the problem.

Then the requests are these: 

- what are the commands used for upgrade via webui?

- What are the differences between the commands used in the upgrade via webui and the command sent telnet SSH client like WinSCP?

Can I use teh command

bzcat /tmp/xxxx.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force debug

(combining "force" and adding "debug" at the end as you mentioned)?

**Comment by FrancYescO** [comment]
Force and debug do the same things, debug is just more verbose

GUI is using `upgradegui` command to do the upgrade, and basically do the same things..
________________________________

**Comment by bovirus** [comment]
Then the command to have **_force_** and **_debug message_** is

bzcat /tmp/xxxx.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice debug

What's the name and path od debug log?

It's strange that **_upgradegui_** is similar has command operation, but **_upgradegui_** doesn't wirk well as the epxlicit command via telnet SSH

bzcat /tmp/xxxx.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force

that instead works fine every time.

**Comment by FrancYescO** [comment]
If something is not working as intended error messages appear on screen so a full log after issuing upgradegui is needed
