### ISSUE TITLE
Return to old TIM Firmware on reboot

### ISSUE THREAD

**Issue by Piket564** [Ansuel/tch-nginx-gui#865]
Hi,
i think i'm missing something, once I reboot the router it hangs up and does not allow access to the Ansuel GUI again, resetting it back to the TIM firmware.
Is there still any command to copy bank_1 to bank_2 or vice versa?

**Comment by FrancYescO** [comment]
if you have not disabled bank check (system extra) and you install GUI in bank2 firmware and config will be cloned to bank1

**Comment by Piket564** [comment]
> if you have not disabled bank check (system extra) and you install GUI in bank2 firmware and config will be cloned to bank1

I think that i've not disabled bank check, but I've used `dd ` to copy `bank_1` to `bank_2`
is that correct?
Anyway I don't think I can use it, since I can't use it with Vodafone, the voip doesn't interest me, but PPP doesn't connect correctly.
xDSL gives me connect, and show stats about download speed and upload speed

**Comment by FrancYescO** [comment]
You just have to setup the ppp accordly https://www.vodafone.it/portal/Aziende/Partita-IVA/Supporto/ADSL-e-Rete-Fissa/Station-e-altri-dispositivi/Vodafone-Modem-Libero/Parametri-di-configurazione

**Comment by Piket564** [comment]
> You just have to setup the ppp accordly https://www.vodafone.it/portal/Aziende/Partita-IVA/Supporto/ADSL-e-Rete-Fissa/Station-e-altri-dispositivi/Vodafone-Modem-Libero/Parametri-di-configurazione

Thanks, the problem is fixed and the modem now works correctly.
