### ISSUE TITLE
Can I reinstall this modified gui after installing compiled LUCI by myself?

### ISSUE THREAD

**Issue by gamesover** [Ansuel/tch-nginx-gui#866]
Hi, I have 2 TG-789. 

One was installed this modified GUI. Works perfectly.
The other was installed compiled LUCI by myself according to last part of https://alastair.d-silva.org/technicolor-tg789vac-v2-root-access. 

For the 2nd compiled LUCI by myself TG-789, I don't know why the wifi connection become very weak. 5G only has 6M/s and 2.4G has 1M/s. Basically, I cannot access to internet by 2nd modem.

Can I reinstall this modifiy GUI to 2nd compiled LUCI by myself TG-789? 

If you can see some obvious issues, I won't do that.
If you are not sure, I'd like to have a try. Since currently this modem is almost unuseable.  

Thanks for your advice ^^

**Comment by FrancYescO** [comment]
there is an already built luci for this device https://github.com/nutterpc/tg-luci (installable from extensions)

assuming you do the right patches (idk what these are) you can install your compiled packages
