### ISSUE TITLE
L'interfaccia web diventa lenta ed è impossibile utilizzarla

### ISSUE THREAD

**Issue by tecufanujacu** [Ansuel/tch-nginx-gui#868]
Device Model: TIM HUB DGA4132
Gui Version: 9.5.1-5ef12049 / 9.5.2-de8e2015
Firmware version : AGTHP_2.2.0_004

Descrizione del problema :

Installazione pulita senza estensioni installate.
Improvvisamente, senza alcun motivo apparente, l'interfaccia web diventa lentissima, non riesce a caricare completamente le schede, carica all'infinito. 
In tutto questo il router continua a funzionare senza problemi e per ripristinare il normale funzionamento dell'interfaccia web devo riavviare da ssh.
Mentre avevo il problema ho anche aggiornato all'ultima gui disponibile nel canale sviluppo, terminata l'installazione dell'aggiornamento il problema era ancora presente.

Quando il problema si presenta, se provo ad entrare nel percorso 192.168.1.1/cards.lp, allora ricevo l'errore:

Elaborazione
Problema connessione: error

**Comment by FrancYescO** [comment]
controlla con `top` se c'e qualcosa che sta occupando risorse.

**Comment by tecufanujacu** [comment]
È stata la prima cosa che ho fatto, ma dal top non si evince nulla di particolare, non sembra ci siano processi che stiano lavorando in modo anomalo, anche l'uptime infatti sembra regolare.

Non è possibile leggere un syslog o qualche log più approfondito?

Faccio inoltre una domanda che poco c'entra con questo problema, mi servirebbe veramente tanto il pacchetto haproxy, purtroppo ho visto che nei repository questo pacchetto non è presente.
L'ho trovato invece in questo (tuo) repository:
https://github.com/FrancYescO/789vacv2_opkg
ma purtroppo non si riesce ad installare.
Ti chiedo, se posso, quel repository non funziona perché il mio firmware base è 2.x? È incompatibile con i nuovi firmware? Sai se ci sono dei repository funzionanti oltri quelli di Ansuel? Oppure sai indicarmi come e dove recuperare il pacchetto haproxy?

**Comment by FrancYescO** [comment]
L'unica è chiedere ad @Ansuel che ce lo compili nella nuova repo

**Comment by tecufanujacu** [comment]
Spero che @Ansuel possa compilare haproxy per i nuovi firmware.

Per quanto riguarda il problema dell'interfaccia ho modo di debuggarlo?
Per un syslog devo per forza inoltrarlo ad un altro dispositivo? Non posso avere il syslog sul router stesso?

**Comment by FrancYescO** [comment]
Basta dare `logread` da terminale.
________________________________

**Comment by tecufanujacu** [comment]
Grazie mille, avevo provato il logread -f ma non riportava nulla.
Comunque sia quando il browser carica a vuoto le pagine dell'interfaccia web, nel logread non riportano nulla.

Sono l'unico ad avere questo problema con l'interfaccia web?

Intanto mi sembra di aver capito che il problema si presenta sempre dopo aver visualizzato la lista dei dispositivi wifi connessi.

**Comment by FrancYescO** [comment]
Potrebbe essere un problema dell'ultimo firmare io sto usando ancora _002 e ancora non ho visto le differenze con i successivi

**Comment by tecufanujacu** [comment]
Appena ho tempo faccio il downgrade per installare l'ultimo firmware stabile 2.1.0 ed all'ultima gui Ansuel stabile 9.4.70.

Abuso per l'ultima volta della tua pazienza, posso fare il downgrade del firmware direttamente dalla gui ed a downgrade completato installare la gui stabile da ssh?
Sul forum ho letto di problemi di compatibilità tra il firmware 2.1.0 e la gui Ansuel stabile che possono brickare il dispositivo, ho capito male o si parlava di vecchie versione della gui stabile?
Rischio qualcosa facendo il downgrade all'ultimo firmware stabile e se dopo installo l'ultima gui stabile?
Scusami ancora per le tante domande e grazie per la pazienza.

**Comment by FrancYescO** [comment]
Si parla di versioni vecchie.
Se fai downgrade (ma anche in generale quando cambi firmware) resetta sempre le config.

**Comment by nclmrc** [comment]
Io sono sulla ultima gui e con firmware 2.1.0, però ho riscontrato questi errori:
 Nov 20 05:33:15 2019 daemon.err transformer[3279]: async exec of '/etc/init.d/hostapd reload && ubus send config "{'reload':'wireless'}" ;' failed exit code=1
Wed Nov 20 05:33:15 2019 daemon.info transformer[3279]: async run: /etc/init.d/network reload ;
Wed Nov 20 05:33:16 2019 daemon.info transformer[3279]: async run: /etc/init.d/network reload
Wed Nov 20 05:33:16 2019 daemon.info transformer[3279]: async run: /etc/init.d/hostapd reload && ubus send config "{'reload':'wireless'}" ;
Wed Nov 20 05:33:22 2019 daemon.err transformer[3279]: async exec of '/etc/init.d/hostapd reload && ubus send config "{'reload':'wireless'}" ;' failed exit code=1
Wed Nov 20 05:33:44 2019 daemon.err nginx: 2019/11/20 05:33:40 [error] 4455#0: *15 lua entry thread aborted: runtime error: [string "/modals/wireless-modal.lp"]:146: bad argument #1 to 'ipairs' (table expected, got nil) stack traceback: coroutine 0:        [C]: in function 'ipairs'       [string "/modals/wireless-modal.lp"]:146: in function 'content'    /usr/lib/lua/web/web.lua:268: in function 'process'       content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 192.168.1.2, server: localhost, request: "GET /modals/wireless-modal.lp HTTP/1.1", host: "dga4132.home", referrer: "http://dga4132.home/cards.lp"

**Comment by FrancYescO** [comment]
Il problema è ancora presente con 2.2.0? Riuscite a capire cosa lo causa?

**Comment by putipower** [comment]
avevo letto di questo problema ma non mi era mai successo fino a qualche giorno fa,le uniche variabili nel mio caso sono state l'aggiornamento a gui successive a 9.5.3 le lucine di natale e un carico sopra le 10 periferiche connesse contemporaneamente.la gui diventa lenta e inutilizzabile,da shell risponde normalmente,e uso cpu e' come sempre.ora sono tornato a 9.5.3 e sembra funzionare.se si ripresenta lo faro presente
grazie

**Comment by tecufanujacu** [comment]
> Il problema è ancora presente con 2.2.0? Riuscite a capire cosa lo causa?

Si, ancora presente con la 2.2.0, basta entrare in Dispositivi > Assistente Wi-Fi e l'interfaccia diventa inutilizzabile.
Lo stesso problema è stato riportato anche sul forum da un utente che ha anche catturato un log:
https://www.ilpuntotecnico.com/forum/index.php/topic,81461.msg257598.html#msg257598
e confermo di avere anche io lo stesso errore nel log.

**Comment by nclmrc** [comment]
I dispositivi wifi a 5ghz vengono visualizzati come eth6
![20200103_224429](https://user-images.githubusercontent.com/38593316/71751116-cb4e1000-2e7a-11ea-9943-5c9586d26e91.jpg)

**Comment by nclmrc** [comment]
Confermo che nei log si presentono sempre gli errori legati alla wireless

**Comment by FrancYescO** [comment]
Quell'errore in logread immagino compaia aprendo la pagina wireless e non "Assistente Wi-Fi", e a me non appare comunque

Allo stesso modo dopo aver aperto la pagina "Assistente Wi-Fi", riesco tranquillamente ad usare l'interfaccia

insomma non riesco a riprodurre nessuno dei problemi (sono su  GUI 9.5.10 fw AGTEF_2.2.0_001)

Forse dipende dai dispositivi connessi/disconnessi (io ho solo un pc in wifi) da se si usa l'interfaccia in LAN o WiFi, insomma bisogna identificare meglio il problema da cosa e' causato perche' a me non si verifica

**Comment by tecufanujacu** [comment]
L'errore non lo vedi col logread, ma nel log del webserver, quindi lo vedi con un:
tail -f /var/log/nginx/error.log

ed il problema si presenta entrando in Dispositivi > Assistente Wi-F, non aprendo la pagina Wireless.

Il problema è presente con i seguenti firmware:
AGTHP_2.1.0
AGTHP_2.2.0_004
AGTHP_2.2.0

e con la gui stable e dev.

Il problema si presenta accedendo al router sia via cavo che via wifi.

**Comment by FrancYescO** [comment]
Quindi il problema si verifica solo con quelle versioni di firmware oppure con altre non hai avuto modo di provare?

Quanti dispositivi wifi hai connessi? Su che banda e di che tipologia? (Tutte info che compaiono in assistente wifi insomma)

Hai provato a vedere se riavviando qualche servizio tipo network si riprende? Ad ora l'unico modo che hai trovato per farlo riprendere è un riavvio?

**Comment by tecufanujacu** [comment]
Non so se si verifica anche con altri firmware dato che non ho avuto modo di provarli.
Nella mia rete ho diversi dispositivi wifi, ma mai più di 10, quasi tutti utilizzano la banda a 2.4 e 4 sono sempre connessi:
3 dispositivi utilizzano funzionalità 802.11n 1x1 WMM 40MHz SGI20 SGI40 AMPDU
1 dispositivo utilizza funzionalità 802.11n 1x1 WMM SGI20 SGI40 AMPDU

Ho provato a riavviare diversi servizi tra cui network ed nginx ma senza successo, l'unico modo che ho per farlo riprendere è un riavvio da ssh.

Ho inoltre notato che il processo wl0-kthrd resta sempre in esecuzione impiegando dal 3% al 5% di cpu.

**Comment by FrancYescO** [comment]
Puoi fare una prova spegnendo prima la 2.4ghz e poi la 5 e vedere se il problema si presenta sempre aprendo la pagina dell'assistente wifi?

**Comment by tecufanujacu** [comment]
Ok, test effettuato, situazione di partenza:
- banda 2.4 e 5 entrambe accese
- 4 dispositivi collegati sulla banda a 2.4
- nessun dispositivo collegato sulla banda a 5

Spengo la banda a 5, resta attiva la sola banda a 2.4 con i 4 dispositivi collegati, provo a replicare il problema e non si presenta.

Riaccendo la banda a 2.4, spengo la banda a 5, nessun dispositivo collegato, provo a replicare il problema e non si presenta.

Riaccendo anche la banda a 5, quindi entrambe le bande sono nuovamente accese con 4 dispositivi nuovamente collegati sulla banda a 2.4, provo a replicare il problema e si presenta.

**Comment by FrancYescO** [comment]
Usi per caso la rete ospiti?

**Comment by tecufanujacu** [comment]
Assolutamente no, rete ospiti disattivate.
Uso però il band Steering, quindi appena posso ho intenzione di ripetere il test dopo aver disattivato il band Steering.

**Comment by FrancYescO** [comment]
In effetti io non ho il problema ma non ho toccato mai nulla nella pagina wifi, il problema potrebbe verificarsi in seguito a qualche opzione attivata (o forse anche in seguito ad un semplice salvataggio)

**Comment by nclmrc** [comment]
Anche io sono nella tua stessa situazione e ho il band steering. Ho impostato inoltre entrambe le reti come US.

**Comment by FrancYescO** [comment]
Io ho abilitato il bandsteering ma continuo a non avere il problema, o per lo meno non si verifica senza dispositivi wifi connessi

**Comment by nclmrc** [comment]
@FrancYescO come ti spieghi quell eth6 nei lista dispositivi quando capita il problema?

**Comment by FrancYescO** [comment]
Quello penso sia un comportamento standard, il wifi 5ghz sui DGA è collegato ad una eth6 virtuale

**Comment by tecufanujacu** [comment]
@FrancYescO, ma di default il band Steering è disabilitato? Non ricordo.
@nclmrc, anche a te il problema si presenta solo quando sono attive entrambe le bande? Puoi effettuare lo stesso test che ho descritto nel commento [571636471](https://github.com/Ansuel/tch-nginx-gui/issues/868#issuecomment-571636471)? Giusto per avere la certezza che non è stato un caso.

**Comment by FrancYescO** [comment]
È disabilitato ma con i nomi delle reti uguali... Non vorrei che è un bug della GUI il visualizzarlo disattivato

**Comment by FrancYescO** [comment]
Chiudo in favore di questa che e' in inglese e con gia tutti i dettagli necesari per la risoluzione https://github.com/Ansuel/tch-nginx-gui/issues/868
