### ISSUE TITLE
[Idea] Power Adjustment

### ISSUE THREAD

**Issue by realindiahotel** [Ansuel/tch-nginx-gui#869]
Is it possible to allow adjusting the power level of the VDSL modem?

For some reason my upstream dropped from 8.6dB to 7.7dB and my speed is 2 Mbit/s slower upstream now. Would like to crank the power back up to 8.6dB

**Comment by FrancYescO** [comment]
SNR is negotiated on DSLAM side, actually looks there is no way to tweak the SNR margin with a broadcom chipset.

**Comment by realindiahotel** [comment]
> SNR is negotiated on DSLAM side, actually looks there is no way to tweak the SNR margin, client side, with a broadcom chipset.

I have broadcom chipset is it possible to tweak?

**Comment by FrancYescO** [comment]
No.
