### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#87]
La skin verde a differenza della viola e blu è più ottimizzata almeno per quanto riguarda la versione mobile. Centratura perfetta e freccia per andare in vetta e in fondo con un click.  È possibile replicare lo schema nelle altre?
Grazie

**Comment by Escart94** [comment]
We'll check It, thanks for the report!

**Comment by nclmrc** [comment]
Ho visto sono state sistemate. Manca solo la viola.

**Comment by nclmrc** [comment]
Molto bella la nuova gui dark red, possibile farla in altre tonalità al posto del rosso?

**Comment by Ansuel** [comment]
la maggior parte dei problemi con le varie skin sono stati risolti. La skin è ancora WIP se hai suggerimenti o altro dimmi pure. Che altri colori vorresti ?

**Comment by nclmrc** [comment]
Io replicherei la verde celeste e la viola

**Comment by nclmrc** [comment]
Andrebbe fissata la centratura della skin viola per la versione mobile. Come avviene correttamente nella verde e blu.
