### ISSUE TITLE
Two cards show error when in bridge mode

### ISSUE THREAD

**Issue by crazycorndog** [Ansuel/tch-nginx-gui#871]
Device Model: DGA4132
Firmware: AGTHP_1.1.0
Gui Version: 9.4.70-184d06d3

Description of problem: When in bridge mode then two cards show an error on the Dashboard/Overview. One is Broadband (shows Error 0undefined) which I can access successfully when I click on it. The other is, I guess, Internet (shows Error 500undefined) which gives me Error 500 when I try to access it.

How to reproduce (if possible): switch into bridge mode

Media/Photos (if possible): https://imgur.com/5PDzVO2.png

logread is attached
[logread.log](https://github.com/Ansuel/tch-nginx-gui/files/3872688/logread.log)

**Comment by FrancYescO** [comment]
What have you selected to bridge? Have you used bridge mode from internet or broadband card? 

Post `/etc/config/network` file

**Comment by crazycorndog** [comment]
I have used mode switch from broadband card (a while ago).
gzipped network file attached[network.gz](https://github.com/Ansuel/tch-nginx-gui/files/3874742/network.gz)

**Comment by Ansuel** [comment]
@crazycorndog why you created the interface dslbridge? Anyway I added more checks to the code... But your config is totally wrong... You removed the wan interface

**Comment by crazycorndog** [comment]
Yes, in bridge mode i dont need any wan interface and the dslbridge interface is only for the ppp session (connected to the wan interface of my router). This way i still have normal access to the device itself (dslstats) and an interface solely for the ppp session separated from the rest of the network.
