### ISSUE TITLE
optimal bank planning

### ISSUE THREAD

**Issue by BRFud** [Ansuel/tch-nginx-gui#872]
Hello,

I have a TG799vac and have followed the advice given at **hack-technicolor.readthedocs.io** including the [advice for optimal bank planning](https://hack-technicolor.readthedocs.io/en/stable/Hack%20Type%201&2/#bank-planning-without-firmware-upgrade), which leaves me with an empty bank_1.

However, then after installing **tch-nginx-gui** I see that the script `/etc/init.d/rootdevice` notices that bank_1 is empty and restores it. I'm wondering why the **tch-nginx-gui** seems to be incompatible with the advice for optimal bank planning, and wondering if it is safe to disable the `check_bank()` routine in `/etc/init.d/rootdevice` ?

learning as I go so any advice on this appreciated!

**Comment by FrancYescO** [comment]
Not incompatible you just have to disable bank check under system extra.

Closing as basically duplicated of https://github.com/Ansuel/tch-nginx-gui/issues/514
