### ISSUE TITLE
Mac address blacklisting only applies to one access point and not the other without extra input 2.4GHz-5GHz

### ISSUE THREAD

**Issue by EvoxOG** [Ansuel/tch-nginx-gui#873]
in the wireless settings we can blacklist mac addresses I blacklisted a mac address but this block only applies to 2.4GHz if the device switches to 5GHz they are unblocked from the network so i have to block it in 5GHz as well i would like an option added next to the blacklist mac address option to also blacklist from 5GHz without doing the extra input for 5GHz

**Comment by FrancYescO** [comment]
I think is just intended to work in this way as you can block a device on a single radio allowing it to forcely use the other band
