### ISSUE TITLE
Remote assistance not available in Tim Hub

### ISSUE THREAD

**Issue by giacar** [Ansuel/tch-nginx-gui#874]
Hi, I have Tim Hub DGA4132 with root and the last gui version installed. I want to access to router settings from outside through the remote assistance, when I go to menu, it's disabled but there not exists a way to open its settings and enable it, why?
  
Ciao ho il tim hub con l'ultima versione della gui installata. Vorrei accedere da rete esterna al pannello del router tramite l'assistenza remota, quando vado sulle schede essa è disabilitata ma non c'è nessun modo per aprire le impostazioni ed attivarla, come mai?

![immagine](https://user-images.githubusercontent.com/34303206/70376657-82eb1300-190b-11ea-8264-b39d736a95a2.png)

**Comment by FrancYescO** [comment]
Se clicchi sulla scheda non succede nulla? Prova a dare il comando `upgradegui` da ssh

**Comment by giacar** [comment]
> Se clicchi sulla scheda non succede nulla? Prova a dare il comando `upgradegui` da ssh

Per la sessione ssh nome utente è admin e password l'access key giusto?

**Comment by giacar** [comment]
Comunque cliccando sulla scheda non succede nulla come se non ci fossero impostazioni disponibili.

**Comment by FrancYescO** [comment]
root/root credenziali ssh default

**Comment by giacar** [comment]
> root/root credenziali ssh default

Grazie mille, ora si è sbloccato e sono riuscito a configurare tutto, inoltre ho nuove funzioni che prima non avevo. Un'ultima domanda, se attivo la ssh da remoto la password è quella usata dalla gui?

**Comment by giacar** [comment]
@FrancYescO Nulla preferisco non attivarlo per questioni di sicurezza...

**Comment by FrancYescO** [comment]
La password ssh è differente da quella della GUI si cambia con `passwd` da ssh, se non ne hai necessità evita proprio di esporlo su WAN.
