### ISSUE TITLE
Cannot enable Band Steering for TG789 

### ISSUE THREAD

**Issue by gamesover** [Ansuel/tch-nginx-gui#875]
Device Model: MediaAccess TG789MYRvac v2 HP
Gui Version:
GUI Version 9.4.70-184d06d3
Description of problem:
I've already set the same `SSID`, `Security Mode`, `Wireless Password`, `WPS` for 2.4/5 GHz.
After I tried to enable `Band Steering Enabled` for 2.4G, it reports error 
```
Some parameters failed validation
bsid: Please configure wifi-bandsteer bs0 first!
```

At 5G wifi interface, I cannot enable `Band Steering Enabled` since it shows `off` and nowhere to enable it.

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
do you have bandsteering functionality on stock firmware?

is there a block like this in your `/etc/config/wireless` file?
```
config wifi-bandsteer 'bs0'
        option rssi_threshold '-40'
        option rssi_5g_threshold '-80'
        option policy_mode '5'
```

**Comment by gamesover** [comment]
No, no such `bs0` exist in `/etc/config/wireless`.

Is it still possible to enable `Band Steering`? Does it need a special hardware supports?

**Comment by FrancYescO** [comment]
Add manually the block I've posted, on 789 should be possible to enable it but idk if there are some more software parts needed other than just the config part..

**Comment by gamesover** [comment]
@FrancYescO Thanks so much. I added the block to the end of `/etc/config/wireless`. It sounds it works now.
