### ISSUE TITLE
LED impazziti su DGA4132 

### ISSUE THREAD

**Issue by SoteraMarco** [Ansuel/tch-nginx-gui#876]
Salve a tutti. A distanza di un anno, da quando uso questo modem con questa fantastica GUI, mi è apparso un bug bizzarro e del tutto a tema con lo spirito natalizio di questi giorni. In pratica il mio TIM HUB DGA4132 con la GUI alla versione 9.4.70-184d06d3, in quando i led sono impazziti e si accendono e spengono a tempi random di nell'ordine di minuti, di ogni colore senza nessuna logica dopo un tempo random dopo un riavvio sia software che hardware, anche se il modem svolge le sue funzioni internet, voip... normalmente. Il problema mi è comparso sin dal firmware AGTHP_2.1.0, e credendolo un bug ho tentato un aggiornamento alla AGTHP_2.2.0, ma senza risultati. Ho pure reinstallato la GUI e nada e infine ho provato a resettare le configurazioni da zero e sia con un backup di qualche giorno fa, ma nada, il problema persiste. 
Nelle impostazioni ECO ed è come è come è sempre stato ovvero LED sempre in funzione senza spegnimento in caso di inattività, e modificando questi parametri non cambia nulla.
Non so più cosa fare per ovviare a questa "modalità discoteca" e per vedere finalmente lo stato reale del modem
Allego un video della situazione.

![ezgif-6-27c69d3b4baa](https://user-images.githubusercontent.com/47932432/71390057-10627e80-25ff-11ea-9a78-1c3f60749114.gif)

Soluzioni?

**Comment by White191094** [comment]
Anche a me da stanotte. Mi sa che sia voluto come effetto natalizio. Vediamo se rispondono i programmatori.

**Comment by Luca2103** [comment]
Mi ha fatto prendere un colpo anche a me.
Sono entrato in ssh nel modem, c'è una riga nello schedulatore crontab interessante
"*/30 * 24-26 12 * /etc/christmas_tree.sh &"
in sostanza dal 24 al 26 dicembre lancia uno script che butta valori random dentro ai file delle luci creando quell'effetto natalizio.
Tipico easter egg

**Comment by FrancYescO** [comment]
a chi non piace il natale da ssh
```
sed -i '/christmas_tree/d' /etc/crontabs/root
killall christmas_tree.sh
/usr/share/transformer/scripts/restart_leds.sh
```
altrimenti smettera' il 26

**Comment by DjDiabolik** [comment]
> a chi non piace il natale da ssh
> 
> ```
> sed -i '/christmas_tree/d' /etc/crontabs/root
> killall christmas_tree.sh
> /usr/share/transformer/scripts/restart_leds.sh
> ```
> 
> altrimenti smettera' il 26

@FrancYescO Il problema è che, anche con l'attuale versione della GUI se ricordo bene una volta che lo script s'avvia il 24 poi il 26 non viene killato...

Intanto mi segno i comandi e se è cosi proverò a killare a mano i PID che credo posso ottenere col PS tramite ssh.... poi c'è da riavviare i LED....

**Comment by DjDiabolik** [comment]
root@modemtim:/etc/crontabs# killall christmas_tree.sh
killall: christmas_tree.sh: no process killed

E cmq a riconferma di quando detto...... ciò che è detto qua sopra è ad oggi errato....

Oggi siamo il 26 e tale file .sh è bello li ancora in esecuzione senza un domani!!

Il comando killall non killa nulla.... e lo stesso file .sh non è più nella lista del crontab... ma c'è qualche problema perchè il processo non si autoelimina...

Se è cosi buggato togliamolo direttamente......... altrimenti va fixato.

**Comment by FrancYescO** [comment]
Quanto detto prima è corretto, oggi è 26: è normale non killi una fava.

**Comment by DjDiabolik** [comment]
Se si esegue appunto /etc/christmas_tree.sh.... esattamente oggi da questo output:
Date not correct cleaning and exiting...
killall: christmas_tree.sh: no process killed

e lo stesso file è questo:
```
#!/bin/sh

if [ "$(date +'%m%d')" != "1224" ] && [ "$(date +'%m%d')" != "1225" ]; then
    echo "Date not correct cleaning and exiting..."
        sed -i '/christmas_tree/d' /etc/crontabs/root
        sh -c "sleep 2 && /usr/share/transformer/scripts/restart_leds.sh &"
    killall christmas_tree.sh
    exit
fi

if [ "$( ps | grep -c 'christmas_tree.sh')" -gt "3" ]; then
    echo "Already running, exiting..."
    exit
fi

trap "kill 0" SIGINT

randd(){
        grep -m1 -ao '[1-7]' /dev/urandom | head -n1
}

powerOnOffRandom(){
        while [ 1 ]; do
                rand=$(randd)
                echo 255 > "$1"/brightness
                echo powering up "$1" for $rand seconds
                sleep $(( $rand - 1 ))
                echo 0 > "$1"/brightness
                sleep $(( $rand - 1 ))
        done
}

for filename in /sys/class/leds/*; do
        ( powerOnOffRandom "$filename" ) &
done

wait

```

Appunto il comando viene si tolto dal cron.. ma poi nulla viene killato nulla... perchè di fatto il killall non funziona.... ma invece il comando è attivo in almeno 20 modi differenti...
 ```
9708 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9713 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9714 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9715 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9716 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9718 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9719 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9720 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9722 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9723 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9724 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9725 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9727 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9728 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9731 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9732 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9733 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9734 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9736 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9737 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9739 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9740 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9742 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9743 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9745 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9747 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9748 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9749 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9751 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9752 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9754 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9756 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9757 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9795 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9797 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9799 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9800 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9801 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9802 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9803 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9804 root      3392 S    /bin/sh /etc/christmas_tree.sh
 9805 root      3392 S    /bin/sh /etc/christmas_tree.sh

```

C'è da riparare sta cosa....

**Comment by DjDiabolik** [comment]
> Quanto detto prima è corretto, oggi è 26: è normale non killi una fava.

Quindi avrebbe dovuto fermarsi il 27 ? @FrancYescO ero sicuro di aver letto solo 24 e 25.....

Cmq sia se poi il killall non killa i PID credo che il problema rimanga cmq..... vediamo ora cmq io non ho più la regola cron (forse perchè con qualche comando l'ho eliminata definitivamente o questa ritorna se io riavvio il router ?)

**Comment by mscuttari** [comment]
Stesso problema con firmware AGTHP_2.3.5_001 e GUI 9.7.6-2ebc4a41.
Ho eliminato regola e file.

**Comment by DjDiabolik** [comment]
> Stesso problema con firmware AGTHP_2.3.5_001 e GUI 9.7.6-2ebc4a41. Ho eliminato regola e file.

Che poi problema.... sarebbe pure una cosa simpatica se l'intera cosa funzionasse a dovere..... ma è cmq il killall che non killa il processo e quindi va in errore.
Ci sarebbe da rivedere il file .sh magari per eseguire il PS identificando i PID del processo relativo al christmastree.sh e quindi eliminare i processi tramite pid direttamente col kill normale.
Anche se non ho capito perchè ma avevo almeno una 40ina di processi relativa al (o meglio dire ai come sopra indicato) christmastree.sh come se il processo fosse avviato più e più volte quando invece i processi dovrebbero essere al massimo uno cioè quello in esecuzione il 24 e che poi dovrebbe killarsi il 26.
E quel processo che poi resta attivo dovrebbe essere poi lo stesso che si dedica a far funzionare e lampeggiare i led a mò di albero di natale....

**Comment by FrancYescO** [comment]
Perché probabilmente non funziona più nemmeno il grep sui nuovi firmware. Poco male non cade il mondo per qualche luce che lampeggia, se volete fare un PR si pulisce tutto altrimenti poi si vedrà

**Comment by DjDiabolik** [comment]
> Perché probabilmente non funziona più nemmeno il grep sui nuovi firmware. Poco male non cade il mondo per qualche luce che lampeggia, se volete fare un PR si pulisce tutto altrimenti poi si vedrà

un PR sta per ? Io potrei provare a fare un nuovo o rivedere quella parte.. il grep funziona come puoi vedere dagli incolla postati qua sopea ho già provato tramite ssh :)
Ho anche ottenuto la sola lista dei PID.....

Una cosa non so... come posso eventualmente triggherare quel file sh senza aspettare il prossimo dicembre 2025? Sapresti suggerirlo ?

**Comment by DjDiabolik** [comment]
a PR.. Pull Request...

Allora posso fare un backup di quel file.. poi se non sbaglio posso modificarlo al volo con un client SFTP o SCP.... devo rinfrescarmi la memoria :) Ormai è da una vita che uso solo il DGA4132 a mò di access point (collegato ad uno switch di rete con a monte una ftth vodafone per la cronaca) che non ho nemmeno più aggiornato il suo firmware per assurdo...

**Comment by DjDiabolik** [comment]
@FrancYescO non mi ritrovo più i programmi.... devo fare un grande remember.... in SFTP non va.... come si accede al contenuto per modificare o salvare i file interni ?
Ho riprovato con WinSCP ma se io metto le credenziali che si usano per la GUI va in errore.......... la stessa cosa se uso quelle che funzionano invece per accedere tramite SSH...... devo rinfrescarmi le idee...

Poi dopo di questo posso provare a salvare questo christmastree.sh e darci una vista, comodamente da windows anche tramite Notepad++.....

*EDIT*
OK Trovato.. WinSCP protocollo SCP porta 22... indirizzo ip ovviamente il suo e credenziali root/root... Sono dentro..
Ora mi salvo il christmastree.sh e ci do una vista.

*EDIT 2*
Allora dovrei aver ricreato correttamente la regola cron... 
```
11 2 * * * /usr/share/transformer/scripts/checkver >/dev/null 2>&1
*/30 * 24-26 12 * /etc/christmas_tree.sh &
```

Se ho capito questa significa che..
Il primo è il check dell'aggiornamento della gui stessa
il secondo invece dal 24 al 26 Dicembre ogni 30 minuti lui avvia il file christmastree.sh... che ho salvato offline...

l'ho già incollato sopra ma lo ripropongo step per step.. il primo if è questo:
```
if [ "$(date +'%m%d')" != "1224" ] && [ "$(date +'%m%d')" != "1225" ]; then
    echo "Date not correct cleaning and exiting..."
	sed -i '/christmas_tree/d' /etc/crontabs/root
	sh -c "sleep 2 && /usr/share/transformer/scripts/restart_leds.sh &"
    killall christmas_tree.sh
    exit
fi
```
Allora come detto il file viene lanciato dal 24.... il primo if controlla se la data NON è il 2412 o il 2516....
Se non è il 24 o 25 dicembre appunto partono in ordine l'echo.
Poi fa il sed -i ecc. ecc. :
Questo comando sed credo che non faccia altro che cancellare la regola cron dal file crontabs/root/.
In pratica il sed apre e cancella tutte le righe che contengono quella stringa cioè "christmas_tree"

A mio avviso già questa cosa si potrebbe rivedere perchè se la regola cron viene eliminata vuol dire che il christmastree stesso funzionerà solamente il primo anno.... la regola cron sarebbe cmq da preservare....... o no ?

poi riviene lanciato il restart_leds.sh e solo dopo in teoria dovrebbe killare tutti i processi del christmastree-

Dopo questo primo if ... il christmastree.sh verifica se è già in esecuzione........ : 
```
if [ "$( ps | grep -c 'christmas_tree.sh')" -gt "3" ]; then
    echo "Already running, exiting..."
    exit
fi


```
Credo che anche questa parte sia da rivedere perchè come ho visto vengono lanciati svariate copie del christmastree stesso.

Ma allora io dico.... se abbiamo la regola cron attiva e settata serve realmente questo check ?
Cioè è già la regola cron stessa oppure questo if andrebbe messo in prima linea.....  o no ?
Per assurdo la regola viene lanciata ogni 30 minuti il 24 e il 25......
A quel punto credo che se io già il 26 avrei fatto un riavvio del modem non avrei ottenuto l'effetto luci di natale o no ?

Ma siccome che la regola cron viene lanciata il 24 e il 25 e non il 26 in pratica il primo check che verifica la data che non sia il 24 e il 25 è un pò inutile non pensi ?

Cioè mi sfugge in quale modo ma in teoria tutta la procedura andrebbe rivista.... 

Credo poi di non sbagliare a dire che tutto quello che c'è dopo i due if è la parte relativa all'effetto stesso..
A quel punto si potrebbe, per assurdo rivedere e fare dei file sh separati. Poi per esempio diversificare tipo:
La regola cron valida ogni 30 minuti il 24 e 25.
La regola cron verifica che sia effettivamente il 24 o il 25 e se si lancia lo script esterno per far partire l'effetto albero di natale in un file .sh esterno poi il processo termina.
Cosi facendo appunto, in teoria avremmo un processo tutto esterno per l'effetto albero di natale.

Nel file sh poi che si prende il compito di fare l'effetto natalizio si potrebbe appunto mettere in loop il check della data e da li verificare quando arriva il 26 e se si da li si autokilla e riavvia i led.
Cosi facendo appunto avremmo sempre la regola attiva che rimane li.. ma il processo stesso che si gestisce in autonomia...
Cioè a mio avviso cosi per com'è ora vengono lanciate diecine e diecine di volte consecutive il christmastree.sh e tutti quei processi distinti a mio avviso vanno in contrasto tra loro..........
Se invece in qualche modo riuscissimo a diversificare le cose a mio avviso sarebbe tutto più pulito.......
