### ISSUE TITLE
LED Ligfhts going bezerk

### ISSUE THREAD

**Issue by realindiahotel** [Ansuel/tch-nginx-gui#877]
TG789MYRvac v2 HP

The LED lights are going bezerk all different colours flashing and changing constantly.

Did you make some code to flash the LEDs for Xmas?

**Comment by exentio** [comment]
Yeah, I thought my router was killing itself. Just a easter egg for Christmas (a Christmas present?), see #876

**Comment by realindiahotel** [comment]
Ok thanks, I thought the same thing because it's been deadly hot here, I thought maybe it frioed itself but looking at logs and stuff I couldn't see abnormalities so I thought maybe it was some kind of funny trick like you say. Thanks for letting me know.

**Comment by FrancYescO** [comment]
Easter egg (1year old) to remove use code in #876
