### ISSUE TITLE
GUI non più raggiungibile con firm 1.1.2.004

### ISSUE THREAD

**Issue by miki8989** [Ansuel/tch-nginx-gui#88]
dall'aggiornamento alla richiesta di 192.168.0.1 chiede la password e poi
La pagina non funziona
192.168.0.1 non ha inviato dati.
ERR_EMPTY_RESPONSE

**Comment by Escart94** [comment]
We have tested It yesterday and there isn't any problem with the new firmware, It sound strange.
Please copy and paste here any error that you can see with "logread" command, so we can check the issue.

**Comment by miki8989** [comment]
grazie per la risposta..
ho resettato il router, reinstallato la 1.0.3, installata la gui, installato la 1.1.2.004 tutto ok funzionante perfettamente.
ho cambiato l'indirizzo del router da 192.168.1.1 a 192.168.0.1 la GUI non funziona più
ho rilasciato l'ip del pc, fatto riprendere, azzeratala cache, niente non entra più
il gateway e 192.168.0.1
se entro con winSCP funziona, ma se provo a leggere la cartella /tmp mi butta fuori

internet funziona regolarmente...
grazie

**Comment by Escart94** [comment]
We are checking this, actually we have discovered a little bug with Javascript.
Update coming soon.

**Comment by Alex2610** [comment]
Same problem here, after upgrading to AGTHP_1.1.2_003 i received the error "empty response" but solved it through reinstalling the GUI from SSH but there is another problem: Luci and other "extra apps" are not reachable, error: "connection refused".
