### ISSUE TITLE
Reboot after 1/2 minute

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#880]
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/4007813/log.txt)
[dump.txt](https://github.com/Ansuel/tch-nginx-gui/files/4007814/dump.txt)
[log2.txt](https://github.com/Ansuel/tch-nginx-gui/files/4007815/log2.txt)

It's happening something strange. After some minute the boot, the modem reboot newly. The log file are taken from ssh before the reboot. The dump file after insert a logread command in rc.local. After change the rc.local file the modem doesn't reboot anymore.

**Comment by FrancYescO** [comment]
After changing what in the rc.local? Do you have any USB devices attached?

**Comment by nclmrc** [comment]
i've inserted a ping 127.0.0.1, now i have resolved with a factory reset. i think the problem was derived by asterisk. there was a problem with sqlite3db

**Comment by FrancYescO** [comment]
so, not GUI related.
