### ISSUE TITLE
Improve upgrade from miniupnpd-tch to miniupnpd

### ISSUE THREAD

**Issue by Dark4Codrutz** [Ansuel/tch-nginx-gui#882]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here: 
[DebugHelper2019-12-29-1341.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4008037/DebugHelper2019-12-29-1341.tar.gz)
</b>

Device Model: DGA4132 fw 2.2.0
Gui Version: 9.5.10 - 9.5.45

Description of problem:
There are calls for " /etc/init.d/miniupnpd " like enable and restart that ends with exit code 127 (command not found). 
In my system the file is " /etc/init.d/miniupnpd-tch "

Workaround: `ln -s /etc/init.d/miniupnpd-tch /etc/init.d/miniupnpd`

**Comment by FrancYescO** [comment]
Ehm, so we are just doing the opposite thing
https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/etc/modgui_scripts/05_app.sh#L59-L73

**Comment by Dark4Codrutz** [comment]
/usr/sbin/miniupnpd binary and /etc/init.d/miniupnpd script were missing from my system.
Even though it said "Specific Apps installed" in the gui it seems that the "upgrade-pack-specificDGA" was never applied. 
Also I noticed miniupnpd-tch is dated on 2019 whereas miniupnpd from the pack is 2018, are they still applicable today with firmware 2.2.0 or should I stick with the newer ones ?

On another note: this is the case for ngnix binary as well, my system has a newer 554kb one whereas the upgrade-pack has an 1.2MB older one ... can this be the issue for the "nil value" return that causes issues around here ?

**Comment by FrancYescO** [comment]
execute `modgui.app.specific_app='0'` than go to the Mod GUI modal and install (again?) specific apps

the revision of the upgrade pack was already done after the 2.1.0 firmware, i'm not sure all is perfect, but actually just work as is.

**Comment by Dark4Codrutz** [comment]
@FrancYescO quick question, if you know something about this behaviour.. 
I manually placed the miniupnpd, scipt and binary files, from the upgrade-pack into their locations, gave them execute permissions but when trying to actually execute the binary either by service start either by manually calling the binary ash shell says the file doesn't exist in sbin... 
Am I missing something here ?

This is just more of a curios case, I will try what you suggest and get all the files from upgrade-pack ...

**Comment by Dark4Codrutz** [comment]
Is 02_specific.sh called by GUI/scripts with the tar file as first parameter $1 ?

**Comment by Dark4Codrutz** [comment]
> execute `modgui.app.specific_app='0'` than go to the Mod GUI modal and install (again?) specific apps
> 
> the revision of the upgrade pack was already done after the 2.1.0 firmware, i'm not sure all is perfect, but actually just work as is.

Yeah, files aren't getting unpacked. At least the miniupnpd script and binary files don't get copied over, I've renamed my manual added ones. 
There's no much logging going on either to indicate what it is doing/not doing, just appInstallRemoveUtility.sh call in logread

I'm researching the option to manually install the package but I'm not sure what script to call exactly: 02_specific.sh , appInstallRemoveUtility.sh with different parameters or pack's own setup.sh ? 
Running setup.sh from `/tmp/upgrade-pack-specificDGA` would be enough ?
... any quick tip would be much appreciated ^^

**Comment by Dark4Codrutz** [comment]
Just realised it checks for kernel version 3.4 which I have 4.1 .... so the whole block responsible for copying over the files (including miniupnpd) is not being executed

**Comment by FrancYescO** [comment]
as i said and you notices all the checks where already made during the install, if you started manually replacing binary idk in what state you are, so please just do a reset and be sure the issue is still present after a clean install of the GUI

**Comment by Dark4Codrutz** [comment]
> as i said and you notices all the checks where already made during the install (90% of the files in the specific pack are not used in fw with kernel 4, binaries get replaced only on if the kernel is 3.4), if you started manually replacing binaries idk in what state you are, so please just do a reset and be sure the issue is still present after a clean install of the GUI

ok I will reset and try ... do you suggest the "remove root" reset ?

I also tried setting specific_app to 0 again and do a force GUI update through offline file with some echo commands added to 02_specific.sh. One after line 21 and one after 35 echoing the files variables, they did not print so I don't know anymore... 
The only prints from "specific" script are the opkg saying packages are up to date

**Comment by FrancYescO** [comment]
These script are here not to be called randomly by the user, but in an exact sequence and only by scripts.

not needed to unroot, just reset (reset button or gateway modal) and reinstall the GUI

**Comment by Dark4Codrutz** [comment]
going back to the point of all of this Issue... still no miniupnpd files copied over from upgrade-pack, literally back to [OP](https://github.com/Ansuel/tch-nginx-gui/issues/882#issue-543381598)

Did the reset with "Reset Config" which doesn't remove root. I also reflashed 2.2.0 firmware (18.3.k-0451) and re-reset config.
