### ISSUE TITLE
Time of day / Access control - Cannot edit rules

### ISSUE THREAD

**Issue by xes** [Ansuel/tch-nginx-gui#884]
Device: DGA4132
FW: 2.2.0
TCH-DEV: 9.5.11

Any rule in "Time of day / Access control " can't be modified, just removed and then re-added.

The error produced is:
"Duplicate contents are not allowed"

Removing the rule and adding it again works as expected.

**Comment by FrancYescO** [comment]
cannot reproduce: i'm just able to edit
share your `/etc/config/tod` file

**Comment by xes** [comment]
cat /etc/config/tod 

config tod 'global'
	option enabled '1'
	option tod_enabled '1'
	option tracelevel '4'
	option time_change_monfreq '10'

config tod 'voicednd'
	option ringing 'off'
	option enabled '0'
	option timerandactionmodified '0'

config host 'CECE14F774CE630C2F3CD7C7534BE33B'
	option enabled '1'
	option id '00:09:C2:08:75:64'
	option start_time '16:00'
	option stop_time '23:00'
	option type 'mac'
	option mode 'block'
	list weekdays 'Mon'
	list weekdays 'Tue'
	list weekdays 'Wed'
	list weekdays 'Thu'
	list weekdays 'Fri'
	list weekdays 'Sat'
	list weekdays 'Sun'

config host '7950BB543C12F68E9E976D1615475A3B'
	option enabled '1'
	option id '00:09:C2:08:75:64'
	option type 'mac'
	option stop_time '14:00'
	option start_time '07:00'
	option mode 'block'
	list weekdays 'Mon'
	list weekdays 'Tue'
	list weekdays 'Wed'
	list weekdays 'Thu'
	list weekdays 'Fri'
	list weekdays 'Sat'
	list weekdays 'Sun'

config host '92667DF19CB646BA06C364C570E0FEE2'
	option type 'mac'
	option stop_time '23:59'
	option mode 'block'
	option start_time '00:00'
	option enabled '1'
	list weekdays 'Mon'
	list weekdays 'Tue'
	list weekdays 'Wed'
	list weekdays 'Thu'
	list weekdays 'Fri'
	list weekdays 'Sat'
	list weekdays 'Sun'
	option id '55:1F:67:FD:70:67'

**Comment by FrancYescO** [comment]
Confirmed, i was editing the wrong tod.

**Comment by xes** [comment]
Sorry, the problem remains. Same error, it's impossible to edit existing rules.
