### ISSUE TITLE
Problema  fonia con Pi-Hole

### ISSUE THREAD

**Issue by SoteraMarco** [Ansuel/tch-nginx-gui#885]
Salve a tutti. Avrei un problema con l'utilizzo del mio DGA4132 con root e GUI Ansuel abbianato con il Pi-Hole installato su un Raspberry 3 B+ collegato al modem via cavo ethernet. Premetto che ho fatto i dovuti aggiornamenti sia al modem e sia a Raspbian e Pi-Hole e come da guida, successivamente dalla pagina del modem "Accesso Internet" ho settato la voce DNS IP con l'IP (statico) del Raspberry al fine di filtrare tutta la pubblicità in ingresso in quel modem. La pubblicità viene filtrata senza problemi, il contatore nella pagina web server di Pi-Hole segna cosa sta bloccando correttamente, ma a tempo indeterminato, la fonia del modem smette di funzionare, lasciando il primo led relativo al telefono voip rosso impedendomi di usare il telefono fisso. A questo punto mi tocca spegnere il Raspberry o togliere l'IP da DNS IP per far ritornare il led verde e ripristinare il funzionamento del telefono fisso. Soluzioni per evitare questa interruzione del telefono fisso mentre uso Pi-Hole

**Comment by nclmrc** [comment]
Il consiglio mio è di mettere l ip del raspberry nel dhcp dns.

**Comment by SoteraMarco** [comment]
Grazie per la dritta, ho provato a settare l'IP del Raspberry nella sezione DHCP, nella sezione "Rete Locale" nel riquadro "Server DNS" del modem, ma il Pi-Hole non filtra nulla e nella sua sezione "Query Log" non vedo nessun aggiornamento.

**Comment by nclmrc** [comment]
Ma i client che dns prendono?

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/353#issuecomment-575753520

**Comment by SoteraMarco** [comment]
> [#353 (comment)](https://github.com/Ansuel/tch-nginx-gui/issues/353#issuecomment-575753520)

Ho provato a lanciare quei comandi via SSH, e adesso impostando da IP DNS, il PI-Hole non fa più il suo dovere, come se non lo avessi mai impostato, idem se lo setto in DHCP DNS

> Ma i client che dns prendono?

Cloudflare

**Comment by nclmrc** [comment]
Ti ripeto il pihole come dns serve esclusivamente ai client. Al router/modem non serve. Mettilo nel dhcp. O disabilita il dhcp sul router e mettilo nel raspberry.

**Comment by nclmrc** [comment]
Comunque penso di aver capito il tuo problema. Il dga assegna il dhcp dns come ipv6.

**Comment by nclmrc** [comment]
In rete locale disabilita ipv6

**Comment by SoteraMarco** [comment]
> Ti ripeto il pihole come dns serve esclusivamente ai client. Al router/modem non serve. Mettilo nel dhcp. O disabilita il dhcp sul router e mettilo nel raspberry.

ho appena cambiato

**Comment by SoteraMarco** [comment]
> In rete locale disabilita ipv6

ipv6 disattivato. Comunque avevo dimenticato di settare il DNS automatico dal mio PC, affinché pigliasse quello impostato dal modem. Per questo prima non mi funzionava. Adesso, dopo aver settato il Pi-Hole in IP DHCP e fatto quello consigliato FrancYescO, pare funzionare. Devo solo aspettare per verificare se la fonia rimane funzionante e concludere che il tutto funzioni a dovere

**Comment by SoteraMarco** [comment]
Dopo svariate ore posso constatare che i vostri consigli sono funzionati. Adesso ho Pi-Hole e fonia TIM funzionanti. Grazie
