### ISSUE TITLE
VLAN su DGA4132

### ISSUE THREAD

**Issue by tecufanujacu** [Ansuel/tch-nginx-gui#886]
È per caso possibile configurare delle vlan su un dga4132?
Dall'interfaccia Luci, in Network>Switch, nella sezione VLANs on "bcmsw" non mi appare nulla.
Vorrei tentare la stessa cosa che è stata chiesta tempo fa in questo topic:
https://www.ilpuntotecnico.com/forum/index.php?topic=78313.0

e mi sto scontrando con gli stessi problemi.
C'è qualcuno in grado di darmi una mano?

---

Is there some way to correctly configure a vlan in a dga4132?
From Luci, in Network>Switch, I have VLANs on "bcmsw" and a blank page.

**Comment by FrancYescO** [comment]
usa il forum per supporto magari uppa anche stesso quel topic specificando i problemi.

Luci non e' compatibile con la gestione delle VLAN su questo dispositivo
