### ISSUE TITLE
GUI.tar.bz2 remaining in /root

### ISSUE THREAD

**Issue by Koenigseggs-and-Crypto** [Ansuel/tch-nginx-gui#889]
Gui Version: 9.4.70-184d06d3
[Technicolor TG799vac]

Description of problem: Post-install there appears to be a full copy of GUI.tar.bz2 in the /root folder, taking up precious space of what little there is. Is this supposed to be the case, or is it acceptable to remove this file? Thanks.

**Comment by FrancYescO** [comment]
Basically the package is needed to allow the GUI persist in firmware upgrades

You can remove it safely but will be placed back on each GUI upgrade/install
