### ISSUE TITLE
Broadband card says "0undefined", errors in Log on page load

### ISSUE THREAD

**Issue by Flole998** [Ansuel/tch-nginx-gui#893]
Device Model: DGA4132
Gui Version: 9.4.70-184d06d3

Description of problem: When Bridge Mode is enabled and XDSL is disabled I am seeing this error whenever I try to load the cards in the GUI:

```
Sat Feb  1 14:31:21 2020 daemon.err nginx: 2020/02/01 14:31:21 [error] 4285#0: *5 lua entry thread aborted: runtime error: [string "002_broadband_bridge.lp"]:11: attempt to index a nil value stack traceback: coroutine 0:       [string "002_broadband_bridge.lp"]:11: in function 'n'  /usr/lib/lua/web/lp.lua:55: in function 'include'       [string "002_broadband.lp"]:3: in function 'n'  /usr/lib/lua/web/lp.lua:55: in function 'include'  /www/docroot/ajax/get_card.lua:11: in function 'n'      /usr/lib/lua/web/web.lua:99: in function 'process'      content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 192.168.1.183, server: localhost, request: "GET /ajax/get_card.lua?modal=/modals/broadband-modal.lp HTTP/1.1", host: "192.168.1.1", referrer: "http://192.168.1.1/""
```

The Broadband card is only contains the text "0undefined" and the title stays at "Loading...". Clicking on it opens the menu.

How to reproduce (if possible): See above

**Comment by Dark4Codrutz** [comment]
Correlated to issue #892

**Comment by Flole998** [comment]
I don't see any correlation, in my case it tries to read an attribute of a null object, that's not the case for your issue

**Comment by Dark4Codrutz** [comment]
ngix crashes the same for me too. Read the first log entry in my post

**Comment by Flole998** [comment]
First of all this is not at all a nginx crash (it is just a lua error), second the errors are in completely different files so they are not related at all. Also your broadband tab is loading according to the screenshots you provided.

**Comment by crazycorndog** [comment]
maybe related to #871

**Comment by FrancYescO** [comment]
could you check if the issue is still present on latest dev version?

**Comment by FrancYescO** [comment]
@Flole998

**Comment by Flole998** [comment]
My device broke so I can't do any tests. Thanks for your effort though.
