### ISSUE TITLE
runtime error: /usr/lib/lua/web/taint.lua:89: bad argument #4 to 'c' (no value)

### ISSUE THREAD

**Issue by EvoxOG** [Ansuel/tch-nginx-gui#894]
Device Model:  TG789MYRvac v2 HP
Gui Version: 9.4.70-184d06d3

Description of problem: keep getting this popping up in the logs. here is the full error in error.log [error] 4617#0: *1 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:89: bad argument #4 to 'c' (no value)
stack traceback:
coroutine 0:
	[C]: in function 'c'
	/usr/lib/lua/web/taint.lua:89: in function </usr/lib/lua/web/taint.lua:83>
	(tail call): ?
	[string "091_system.lp"]:25: in function 'n'
	/usr/lib/lua/web/lp.lua:55: in function 'include'
	/www/docroot/ajax/get_card.lua:11: in function 'n'
	/usr/lib/lua/web/web.lua:99: in function 'process'
	content_by_lua(nginx.conf:109):4: in function <content_by_lua(nginx.conf:109):1>, client: 192.168.1.4, server: localhost, request: "GET /ajax/get_card.lua?modal=/modals/system-modal.lp HTTP/1.1", host: "192.168.1.1", referrer: "https://192.168.1.1/"

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
check if the issue still present on latest dev version.

**Comment by EvoxOG** [comment]
yep lastest dev version has fixed it thanks
