### ISSUE TITLE
Wireless card error 500 and Wi-Fi off DGA4130

### ISSUE THREAD

**Issue by binc0** [Ansuel/tch-nginx-gui#898]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

[tmp.zip](https://github.com/Ansuel/tch-nginx-gui/files/4227301/tmp.zip)

.tar is not supported
Device Model: DGA4130
Gui Version: 9.5.16

Description of problem: Getting Error 500 in Wireless card and Wi-Fi is off

How to reproduce (if possible): Update to 9.5.16

Media/Photos (if possible):

**Comment by binc0** [comment]
Fixed with a gui reset and config reset

**Comment by Dark4Codrutz** [comment]
did it never happened again after the resets ?

**Comment by binc0** [comment]
No, I had that problem only one time
