### ISSUE TITLE
Root Script Error

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#899]
DGA4132 9.5.17

_Root Script Checking if intercept is enabled and disabling if it is...
**ash: 183.k: bad number**
...
Root Script Executing /etc/modgui_scripts/06_network.sh
**/etc/rc.common: /etc/modgui_scripts/06_network.sh: line 243: /usr/share/transformer/scripts/ispConfigHelper.sh: Permission denied**_

**Comment by Dark4Codrutz** [comment]
Cannot reproduce. 
I've successfully updated from dev 9.5.16 to stable 9.5.17, without warning or error.

**Comment by FrancYescO** [comment]
firmware?

please output of this command:

`uci get version.@version[0].marketing_version | sed 's#\.##'`
