### ISSUE TITLE
GUI not available without internet connection.

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#906]
Device Model: 4130 2.2.0, 4131 18.3.n.0439_FW_258
Gui Version: 9.5.33

Description of problem: When there is no connection the GUI is not available (Port 80 and 443 are not listening at all.) LUCI works perfectly on 9080 and SSH is also available. The GUI becomes again available when the internet connection is restored and the command "upgradegui" is sent (It might also works just a reboot or a nginx restart, I'm not sure).

How to reproduce (if possible): Plug-off the connection and reboot the router.

**Comment by Ansuel** [comment]
Will fix it today

**Comment by lorenzocanale-LC** [comment]
Thanks!!

**Comment by Ansuel** [comment]
Fixed in https://github.com/Ansuel/tch-nginx-gui/commit/c1b921ac3c3e93970a108cd47cdd34060b921175
