### ISSUE TITLE
Root script problems

### ISSUE THREAD

**Issue by aetonsi** [Ansuel/tch-nginx-gui#909]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
i have not found the "system extras" card

#### Device Model
DGA4132 Version Cobalt (18.3.k)

#### Gui Version
9.5.17-5b723682

#### Description of problem
Various errors are shown when trying to execute the install script `bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force` (either concatenated with `&&` or separated, it makes no difference).
I've installed the GUI multiple times in the past couple of days and i've always had some problem, and each time it was a different one.
I have even reflashed the 1.0.3 fw+root with autoflashgui (over an already installed 1.0.3) just to be sure, but i still got error messages.
I tried both with dsl cable connected and disconnected, still got errors.
Seems to be related to the closed issue #899 ; running `uci get version.@version[0].marketing_version | sed 's#\.##'` gives me `183.k`.

#### How to reproduce (if possible)
Install the GUI.

#### Media/Photos (if possible)
* Run number 1:
```
...

www/info-cards/007_network.lp
www/info-cards/004_graph.lp
root@modemtim:~# /etc/init.d/rootdevice force
Root Script: Installing in progress...
mv: can't rename '/tmp/ripdrv.ko': No such file or directory
Failed to find ripdrv. Maybe it is a built in module ?
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 259: can't create /proc/rip/delete: nonexistent directory
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 259: can't create /proc/rip/delete: nonexistent directory
module is not loaded
rm: can't remove '/lib/modules/3.4.11/ripdrv.ko': No such file or directory
```

* Run number 2:
```
...

Root Script: Installing in progress...
mv: can't rename '/tmp/ripdrv.ko': No such file or directory
Failed to find ripdrv. Maybe it is a built in module ?
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 283: can't create /proc/rip/delete: nonexistent directory
/etc/rc.common: /etc/modgui_scripts/02_specific.sh: line 283: can't create /proc/rip/delete: nonexistent directory
module is not loaded
rm: can't remove '/lib/modules/3.4.11/ripdrv.ko': No such file or directory
killall: ledfw.lua: no process killed
/etc/rc.common: /etc/modgui_scripts/06_network.sh: line 243: /usr/share/transformer/scripts/ispConfigHelper.sh: Permission denied
Success
JUMBO_PORT_MASK:0x00000000
  GPHY_0 port rejects jumbo frames.
  GPHY_1 port rejects jumbo frames.
  GMII_1 port rejects jumbo frames.
  GMII_2 port rejects jumbo frames.
  GPON_SERDES port rejects jumbo frames.
  MOCA port rejects jumbo frames.
  USB port rejects jumbo frames.
  GPON port rejects jumbo frames.
  MIPS port rejects jumbo frames.
Success
Command failed: Not found
Interface wan not found
```

* Run number 3:
```
...

www/info-cards/007_network.lp
www/info-cards/002_wanstats.lp
Root Script: Installing in progress...
ash: 183.k: bad number
/etc/rc.common: /etc/modgui_scripts/06_network.sh: line 243: /usr/share/transformer/scripts/ispConfigHelper.sh: Permission denied
```
![image](https://user-images.githubusercontent.com/18366087/77229713-bc305180-6b8f-11ea-9e8f-bb5a04a7465d.png)

**Comment by FrancYescO** [comment]
already fixed in dev

**Comment by aetonsi** [comment]
@FrancYescO thanks for the reply, i just tried it, and it showed just the following:
```
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
Invalid ISP
```
which i guess it's normal since i ran it without DSL cable connected, right?

thanks again

**Comment by FrancYescO** [comment]
Yes, it detect isp based on the wan configs

**Comment by aetonsi** [comment]
I tried again, started with a clean slate, done everything as expected, including bank panning, and the install of 9.5.38 gives me these messages:
```
Root Script: Installing in progress...
killall: ledfw.lua: no process killed
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
Invalid ISP
Success
JUMBO_PORT_MASK:0x00000000
  GPHY_0 port rejects jumbo frames.
  GPHY_1 port rejects jumbo frames.
  GMII_1 port rejects jumbo frames.
  GMII_2 port rejects jumbo frames.
  GPON_SERDES port rejects jumbo frames.
  MOCA port rejects jumbo frames.
  USB port rejects jumbo frames.
  GPON port rejects jumbo frames.
  MIPS port rejects jumbo frames.
Success
mkdir: can't create directory '/overlay/bank_1': File exists
cp: can't stat '/overlay/bank_2/*': No such file or directory
```


Is everything ok? The GUI seems to be working correctly by far...

**Comment by FrancYescO** [comment]
did you have done the bank planning before installing, did you disabled bank check?
the last 2 row are pretty strange, are you still in bank2?

**Comment by aetonsi** [comment]
i did [bank planning as described here](https://hack-technicolor.readthedocs.io/en/stable/Hacking/PostRoot/#bank-planning) (i **was** in bank_2 before planning) before installing the gui; i don't know about bank check.
my current output from `find /proc/banktable -type f -print -exec cat {} ';'` is:
```
root@modemtim:~# find /proc/banktable -type f -print -exec cat {} ';'
/proc/banktable/active
bank_1
/proc/banktable/booted
bank_1
/proc/banktable/inactive
bank_2
/proc/banktable/bootedoid
5db3204b4f5d980688c27cdc
/proc/banktable/notbooted
bank_2
/proc/banktable/notbootedoid
595b885abd3c1a55a7e453a4
/proc/banktable/activeversion
18.3.k.0451-3161011-20191025181819-3f83315f6d40733756f2a3ef5b192653d99f3c87
/proc/banktable/passiveversion
17.1.7812-0001019-20170704142146-f19db08ab5c86434318a24c8ee86cbce5ab51da6
```

**Comment by FrancYescO** [comment]
this GUI have some troubles with the OBP, basically you have to disable the bank check as it will force te GUI to run on bank1 as you can see actually you have active=booted=bank_1 instead of the OBP requirement that should be active=bank_1 booted=bank_2

a rework to change the default behaviours is still WIP https://github.com/Ansuel/tch-nginx-gui/pull/900

**Comment by aetonsi** [comment]
Oh ok i understand.
Do i have to disable bank check in the mean time, or the router going to work anyway? No problems so far

**Comment by FrancYescO** [comment]
you need to disable bank2 if you want to replicate OBP that is usefull in case of recovery is needed, nothing changes in the normal operations

**Comment by aetonsi** [comment]
Sorry for asking, but what is OBP and how do i disable bank 2 ?

**Comment by FrancYescO** [comment]
You should disable bank check (system extra in the webui) when in bank1, switchover to bank2, than follow the OBP (Optimal bank planning) instructions

**Comment by aetonsi** [comment]
Ok so, since i am in bank1 i disabled bank check, do i have to do a "clone bank" before switching to bank 2? Because i can see that my bank2 is on a different version:
```
Active Bank bank_1
Active Version 18.3.k.0451
Passive Bank bank_2
Passive Version 17.1.7812
```

**Comment by FrancYescO** [comment]
Bank check do the exact opposite of OBP: force the GUI to run on bank1, thats why i'm saying you should disable it if you want to setup OBP

**Comment by aetonsi** [comment]
Ok i understand.
Should i even do OBP? what is it for?

i was just following the [wiki for rooting the router](https://hack-technicolor.readthedocs.io/en/stable/Hacking/Type2/#final-type-2-steps) and it suggested doing it.
when i did it i was in bank_2 but i guess i did something wrong because now i am in bank_1...

can i just keep the bank check disabled and stay in bank_1?

**Comment by FrancYescO** [comment]
GUI first install = automatically get switched to bank1, so thats why you are in bank1.

OBP = https://hack-technicolor.readthedocs.io/en/stable/Hacking/PostRoot/#bank-planning

it's a "safety" procedure up to you if you want to do it, you just need to know that in the actual status this mod is not very friendly with it (as was ever forced to run in bank1, and the bank check was a default activated func that probably will be removed soon https://github.com/Ansuel/tch-nginx-gui/pull/900)

**Comment by aetonsi** [comment]
Ok so, if this GUI is not very friendly with OBP, can i safely disable bank check and just avoid OBP?

**Comment by FrancYescO** [comment]
yes, but in theory disabling bank check will also allow you to do the OBP.

**Comment by aetonsi** [comment]
Ok i understand. I will avoid doing OBP for now then, and i'll leave bank check enabled 

thanks
