### ISSUE TITLE
crontab jobs

### ISSUE THREAD

**Issue by nclmrc** [Ansuel/tch-nginx-gui#91]
ogni volta che si fa un upgradegui viene aggiunta una riga in /etc/crontab/root. creando diversi doppioni

**Comment by Ansuel** [comment]
Posso avere un esempio?

**Comment by nclmrc** [comment]
Prima:
0 5 * * * /usr/share/transformer/scripts/checkver Schedule >/dev/null 2>&1
*/10 * * * * /sbin/trafficmon.lua
*/3 * * * * /sbin/trafficdata.lua

Dopo:
0 5 * * * /usr/share/transformer/scripts/checkver Schedule >/dev/null 2>&1
*/10 * * * * /sbin/trafficmon.lua
*/3 * * * * /sbin/trafficdata.lua                                            0 5 * * * /usr/share/transformer/scripts/checkver Schedule >/dev/null 2>&1

**Comment by nclmrc** [comment]
Ho provveduto anche a ripulurlo un Po prima, ma vedo che le righe aumentano sempre

**Comment by nclmrc** [comment]
@Ansuel qual'è il contenuto del tuo file?

**Comment by nclmrc** [comment]
Tutte le volte aggiuunge questa riga.
