### ISSUE TITLE
force root permission denied

### ISSUE THREAD

**Issue by btrain-git** [Ansuel/tch-nginx-gui#915]
Product Name: Technicolor ( Technicolor **DJA0230TLS** )
Software Version: 17.2 Mint
GUI Version: 9.5.17-5b723682
when i run the command: /etc/init.d/rootdevice force I get the following error
/etc/rc.common: /etc/modgui_scripts/06_network.sh: line 243: /usr/share/transformer/scripts/ispConfigHelper.sh: _Permission denied_
What am I doing wrong and has anyone seen this before? thank you.
![image](https://user-images.githubusercontent.com/60606521/77908682-afbaa000-72d7-11ea-91b2-07aa8794841f.png)

**Comment by FrancYescO** [comment]
duplicate https://github.com/Ansuel/tch-nginx-gui/issues/909
