### ISSUE TITLE
PPPoe disconnects every 3 minutes

### ISSUE THREAD

**Issue by brucbr** [Ansuel/tch-nginx-gui#918]
**Device Model:** DJN2130
**Gui Version:** 9.5.35

**Description of problem:**
PPPoe disconnects roughly every three minutes, this has only started after the installation of this GUI

**How to reproduce (if possible):**
Connect to a Fixed Wireless ISP using PPPoe as the interface

**Media/Photos (if possible):**
N/?A

I am currently using a Mikrotik router which disconnects quite rarely (However is quite cheap and only supports 2.4Ghz, thus wanting to use my Gateway).

**Comment by brucbr** [comment]
I am currently using a Mikrotik router which disconnects quite rarely (However is quite cheap and only supports 2.4Ghz, thus wanting to use my Gateway).

**Comment by FrancYescO** [comment]
this happens also with wansensing off ?
the wireless (3/4G?) ISP is the only connection to the modem?
firmware version?

**Comment by brucbr** [comment]
I haven't tested with WANSensing off, I'll try that later today (Family members currently using the internet). Fixed Wireless isn't 4G as far as I know, it uses a dish by Cambium Networks.

Firmware Version: 17.2.0284-820-RA

**Comment by brucbr** [comment]
The sim card slot is empty as I won't be using mobile fallback

**Comment by FrancYescO** [comment]
ok so basically you are using an ethernet WAN?

**Comment by brucbr** [comment]
Yes

**Comment by brucbr** [comment]
With WAN sensing disabled and mode set  to Ethernet, the problem still occurs

**Comment by brucbr** [comment]
Albeit less frequently

**Comment by brucbr** [comment]
After disabling VLAN (No idea why it was enabled), Changing the DNS settings to cloudflare, Disabling xDSL (No idea why it was still enabled when WAN type was set to ethernet), Disabling Mobile (Should be disabled when no SIM is detected), Changing the LCP failure threshold and getting a static IP:

20minutes 38 seconds and still going.

I am currently stress testing it with multiple video streams and multiple downloads to see if it happens under high load.

**Comment by FrancYescO** [comment]
i suppose was not a software related issue... more something like a bad antenna signal

**Comment by brucbr** [comment]
Currently been running for several days without any issues. I will now close the issue.

**Comment by brucbr** [comment]
It disconnects at night (10pm-3am) quite frequently. Other than that, going pretty well.
