### ISSUE TITLE
problemi con le interfacce openwrt

### ISSUE THREAD

**Issue by stuzzica** [Ansuel/tch-nginx-gui#919]
io non so se è normale ma allego il log del mio DGA4131 impostato in pppoe TIM e vorrei sapere se le interfacce di OpenWRT sono settate correttamente 
![Immagine](https://user-images.githubusercontent.com/53705618/78314532-88273a00-755a-11ea-872d-abdc4bade668.jpg)
[log.txt](https://github.com/Ansuel/tch-nginx-gui/files/4424555/log.txt)

**Comment by FrancYescO** [comment]
si sono tutte quelle messe di default da quel firmware.

**Comment by stuzzica** [comment]
volevo sapere se erano configurate bene -_-

**Comment by FrancYescO** [comment]
se son settate bene o no lo sai tu in base a quello che ci devi fare con le interfacce, di sicuro non è un problema della GUI

**Comment by MichaelDevC** [comment]
Giorno come faccio ad installare la gui OPENWRT?? Su dga4131fwb

**Comment by FrancYescO** [comment]
Luci è tra le estensioni.

**Comment by MichaelDevC** [comment]
ok grazie
