### ISSUE TITLE
[Not a Bug] Forgotten root password SSH

### ISSUE THREAD

**Issue by billyourself** [Ansuel/tch-nginx-gui#922]
Hi, I successfully installed the firmware and rooted my TG789.. however I've already managed to forget the SSH root password.

I still have full admin access via the web UI and physical access to the device.

Any simple way to reset/work around the root password? Or will I need to do some kind of full reset and reinstall?

Thanks

**Comment by billyourself** [comment]
Never mind, managed to remember.

**Comment by Dark4Codrutz** [comment]
leaving it here... just reset the modem

**Comment by FrancYescO** [comment]
crontab manager can be used as an hacky way to reset (if you have at least webui access)
