### ISSUE TITLE
DGA4132 - Invalid ISP error

### ISSUE THREAD

**Issue by brusarp** [Ansuel/tch-nginx-gui#924]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: DGA4132

**ISP name and type: TIM with FTTH connected by internal MINIONT**

Gui Version: Upgrading to 9.5.38 from previous 9.5.17 Stable

Description of problem:
At the end of the bzcat script appear "Invalid ISP" error

How to reproduce (if possible):
Launch bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - && /etc/init.d/rootdevice force
from SSH
Media/Photos (if possible):
![Annotazione 2020-04-05 105517](https://user-images.githubusercontent.com/14950532/78471051-739b9b00-772e-11ea-8e18-f06eebd35dfc.jpg)

root@modemtim:/tmp# /etc/init.d/rootdevice debug
Root Script: Installing in progress...
Root Script Start rooting
Root Script Setting root flag
Root Script Reset unlock bit
Root Script Save root password if modified
Root Script Setting & Enabling Dropbear SSH Server
Root Script Restarting Dropbear SSH Server
Root Script Executing /etc/modgui_scripts/01_prereq.sh
Root Script Disabling watchdog...
Root Script Checking Free RAM...
Root Script Executing /etc/modgui_scripts/02_specific.sh
Root Script Checking opkg feeds...
Root Script Applying specific model fixes...
Package busybox_telnet (1.28.4-3) installed in root is up to date.
Package libopenssl (1.0.2s-1) installed in root is up to date.
Package openssl-util (1.0.2s-1) installed in root is up to date.
Root Script Executing /etc/modgui_scripts/03_various.sh
Root Script Enabling hardware serial console...
Root Script Fixing sysupgrade if needed...
Root Script Restoring and enabling few transformer mappers...
Root Script Transformer lib check
Root Script Creating custom GUI utils symlinks...
Root Script Add checkversion to cron...
Root Script Executing /etc/modgui_scripts/04_config.sh
Root Script Check original config
Root Script Unlocking web interface if needed
Root Script Check if variant_friendly_name set
Root Script Remove https check
Root Script Check driver setting
Root Script Check Dropbear config file
Root Script Check eco paramaters
Root Script Create GUI type in config
Root Script Add new web options
Root Script New DHCPRelay Option
Root Script Suppressing wansensing logs
Root Script Create new option for led definitions
Root Script Creating and checking real version
Root Script Implementing WoL
Root Script Apply new xDSL options
Root Script Adding fast cache options
Root Script Checking if wan_mode option exists...
Root Script Checking DoSprotect kernel modules...
Root Script Enabling and starting DoSprotect service...
Root Script Checking mobiled libs...
Root Script Checking if intercept is enabled and disabling if it is...
Root Script Disabling coredump reboot...
Root Script Restoring nginx additional options if needed...
Root Script Adding missing voicednd rule if needed
Root Script Doing various checks and generating hashes...
Root Script Update branch detected: STABLE
Root Script GUI hash set: 4d0b6b139e9a5fcb9a5f3966500d2823
Root Script Resetting version info...
Root Script Decrypting any encrypted password present in config
Root Script Executing /etc/modgui_scripts/05_app.sh
Root Script Trafficmon inizialization
Root Script Enable DLNAd
Root Script Enable new upnp
Root Script Move Aria2 dir
Root Script Reinstalling Telstra GUI if needed...
Root Script Executing /etc/modgui_scripts/06_network.sh
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
**Invalid ISP**
Root Script Adding ipoe in network config...
Root Script Removing default loopback DNS Servers...
Root Script Purify WAN network config...
Root Script Fix DNS bug, make sure odhcp is enabled
Root Script Enabling odhcpd on boot
Root Script Checking and fixing dnsmasq daemon naming...
Root Script Sync DHCP configuration for new GUI
Root Script Reworking sfp interface in network config...
Root Script Attempt to clean the wansensing script from hardcoded interfaces...
Root Script Cleaning cups firewall rule...
Root Script Apply CVE 2019-11477 workaround
Root Script Checking atmdevice interface naming...
Root Script Restarting dnsmasq if needed...
Root Script Executing /etc/modgui_scripts/99_postreq.sh
Root Script Applying modifications
Root Script Resetting cwmp and watchdog
Root Script Process done.
Root Script Restarting transformer
Root Script Stopping nginx
Root Script Restarting nginx...

**Comment by FrancYescO** [comment]
output of command `uci get modgui.var.isp` ?

e altra cosa offtopic... ma non hai gli stessi problemi di https://github.com/Ansuel/tch-nginx-gui/issues/917 ?

**Comment by brusarp** [comment]
Output command 'uci get modgui.var.isp'
correctly "TIM" (also in the ISP page of the GUI is correctly "TIM"). The error appears only during the script.
I don't know if I've the same #917 error because all is working smooth... Also I don't know how to change from SFP to GPON and if is on my interest ;-)
When the TIM technicians came to my house to change the FTTC to FTTH they reset the modem so I had to reinstall the GUI from scratch. But from that moment everything works properly and I haven't changed many settings (only wifi name and port forwarding rules ...)

**Comment by FrancYescO** [comment]
output of `/usr/share/transformer/scripts/ispConfigHelper.sh refresh`?

so probably you have just "ethernet" as a broadband connection and not GPON (that will show all infos from the GPON SFP module) ... the fiber cable is directly in the TIMHUB or there is an external mediaconverter?

**Comment by brusarp** [comment]
output of `/usr/share/transformer/scripts/ispConfigHelper.sh refresh`

IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
Invalid ISP

The fiber is connected directly to TIMHUB with MINIONT

**Comment by FrancYescO** [comment]
plese confirm it's fixed in the last dev..

**Comment by brusarp** [comment]
Installed 9.5.41dev all is OK!
Here the last lines:
Root Script: Installing in progress...
Package busybox_telnet (1.28.4-3) installed in root is up to date.
Package libopenssl (1.0.2s-1) installed in root is up to date.
Package openssl-util (1.0.2s-1) installed in root is up to date.
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
IspConfigHelper TIM ISP detected, finding CWMP server...
IspConfigHelper CWMP Server detected: https://regman-mon.interbusiness.it:10800/acs/
IspConfigHelper Restarting dnsmasq if needed...

Thank you @FrancYescO
