### ISSUE TITLE
Error during saving On Local Network tab for DGA4130

### ISSUE THREAD

**Issue by zixzix** [Ansuel/tch-nginx-gui#927]
As title, a missing space.

GUI Version: GUI DGA4130 9.5.38-ba81e28c

![image](https://user-images.githubusercontent.com/3858194/78643914-4fb69180-78b5-11ea-85c1-7f1ba9a0cbbe.png)

**Comment by FrancYescO** [comment]
looks already fixed https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/www/docroot/modals/ethernet-modal.lp#L1404
