### ISSUE TITLE
Vendor by MAC address not work correctly

### ISSUE THREAD

**Issue by brusarp** [Ansuel/tch-nginx-gui#928]
Device Model: DGA4132
Gui Version: 9.5.41dev

Description of problem: Vendor by MAC address is correct (sometimes) only for the first device. The others, after some seconds with rolling arrow, shows all the same wrong vendor.

How to reproduce (if possible): open Devices cards

Media/Photos (if possible):
![Annotazione 2020-04-08 161233](https://user-images.githubusercontent.com/14950532/78795896-d8b4f200-79b5-11ea-83cc-832e55601a6b.jpg)

**Comment by FrancYescO** [comment]
Was this happening on stable or previous versions?

**Comment by brusarp** [comment]
If I remember correctly it happened before but I had not yet opened the issue...

**Comment by giulio63** [comment]
I've the same problem ( dev versione ) also with the last version 9.5.48

**Comment by lionhe1966** [comment]
I also have the same issue: stable version. NGINX generates errors on syslog for each line in the card
 nginx: 2020/04/19 15:31:57 [emerg] 4576#0: *400 [lua] [string "header.lp"]:9: getVendor_xx:yy:zz:zz:c7:de_sync, client: 192.168.27.30, server: localhost, request: "POST / HTTP/1.1", host: "192.168.27.14", referrer: "http://192.168.27.14/cards.lp"
