### ISSUE TITLE
LuCI GUI not working on TG789vac V2

### ISSUE THREAD

**Issue by VismoDoc** [Ansuel/tch-nginx-gui#930]
Device Model: TG789vac v2 / VANT-6
Gui Version: 9.5.38 (stable)

Description of problem: LuCI not loading web page 

How to reproduce (if possible): install LuCI from router web page under "extensions", load http://192.168.1.1:9080 and LuCI GUI will not load. It just shows a index of a folder (reboot doesn't solve the problem)

Media/Photos (if possible):
![Screenshot (26)](https://user-images.githubusercontent.com/17516497/78935332-d5e8f880-7aac-11ea-8e58-a94f707e0e98.png)

**Comment by FrancYescO** [comment]
closing as probably related to https://github.com/Ansuel/tch-nginx-gui/issues/931
