### ISSUE TITLE
Broken opkg update on TG789vac

### ISSUE THREAD

**Issue by VismoDoc** [Ansuel/tch-nginx-gui#931]
Device Model: TG789vac v2 / VANT-6
Gui Version: 9.5.38 (stable)

Description of problem: when starting an "opkg update" via ssh it returns some wget errors

How to reproduce (if possible): login using ssh, input "opkg update"

Logs:

root@Gateway:~# opkg update
Downloading https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/base/Packages.gz.
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
Downloading https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/packages/Packages.gz.
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
Downloading https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/luci/Packages.gz.
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
Downloading https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/routing/Packages.gz.
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
Downloading https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/telephony/Packages.gz.
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
Downloading https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/management/Packages.gz.
wget: can't execute 'openssl': No such file or directory
wget: error getting response: Connection reset by peer
Downloading http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/base/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer.
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (luci http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (management http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/management). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (routing http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/routing). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (packages http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (telephony http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/telephony). Skipping.
 * opkg_download: Failed to download https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/base/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/packages/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/luci/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/routing/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/telephony/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://raw.githubusercontent.com/FrancYescO/789vacv2_opkg/master/management/Packages.gz, wget returned 1.

**Comment by FrancYescO** [comment]
did you installed the GUI online or offline?

**Comment by VismoDoc** [comment]
Online.  I've used the ssh command from the README (curl -k https://raw.githubusercontent.com/Ansuel/gui-dev-build-auto/master/GUI.tar.bz2 --output /tmp/GUI.tar.bz2 bzcat /tmp/GUI.tar.bz2 | tar -C / -xvf - /etc/init.d/rootdevice force)

**Comment by FrancYescO** [comment]
closing as motivation better exposed in https://github.com/Ansuel/tch-nginx-gui/issues/934
