### ISSUE TITLE
Won't install any Applications / Extensions on TG589vac

### ISSUE THREAD

**Issue by Duncan494** [Ansuel/tch-nginx-gui#932]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
[DebugHelper2020-04-09-2131.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4458533/DebugHelper2020-04-09-2131.tar.gz)

Device Model: TG589vac 16.3.7937
GUI Version: 9.5.38-ba81e28c

Description of problem: Won't install Transmission, Aria2 etc, States that it is installed however it is not and removal will reset status.

How to reproduce (if possible): As Standard

Media/Photos (if possible):
![image](https://user-images.githubusercontent.com/36572383/78938146-9cfb5480-7aa9-11ea-973c-d8d59cb8b530.png)

![image](https://user-images.githubusercontent.com/36572383/78938276-d92eb500-7aa9-11ea-98b1-8e11c7791590.png)

**Comment by FrancYescO** [comment]
GUI and this model was never tested so basically is not installing specific app, and wget is not able to download from HTTPS

you should first fix wget and set correct feed that try to use feeds from 789 or DGA based on the CPU of this model...

write here a result from `cat /proc/cpuinfo`

**Comment by Duncan494** [comment]
Result:
system type             : VANT-E
processor               : 0
cpu model               : Broadcom BMIPS4350 V8.0
BogoMIPS                : 397.31
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : no
hardware watchpoint     : no
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Broadcom BMIPS4350 V8.0
BogoMIPS                : 409.60
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : no
hardware watchpoint     : no
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by kalman6** [comment]
[DebugHelper2020-05-03-2107.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4570147/DebugHelper2020-05-03-2107.tar.gz)
Technicolor DJA0231
18.1.c Champagne
 ARMv7 Processor rev 1 (v7l)
Same problem

**Comment by FrancYescO** [comment]
apps are shown on-device (and firmware) base but in your case, as the cpu should be the same
DJA can be considered as a DGA device and 
TG589 as a TG789

you can fake up the `env.var.prod_friendly_name` to DGA4130 and than issue `/usr/share/transformer/scripts/appInstallRemoveUtility.sh install luci` to check that the install will work if all is okay we will add these app to the GUI

please also make sure your opkg feeds are populated https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/etc/modgui_scripts/02_specific.sh#L84-L92

**Comment by FrancYescO** [comment]
this should be fixed, actually apps and feeds are setted based on cpu type and firmware version.
