### ISSUE TITLE
[AGTHP] [9.5.38] Not able to connect via usb modem/key

### ISSUE THREAD

**Issue by mattodinaturas** [Ansuel/tch-nginx-gui#938]
Device Model: AGTHP
Gui Version: 9.5.38 stable

Description of problem: Unable to connect to the internet with a usb 3g key/modem. The GUI says all the time "connecting" and the led on the usb key continuously flashes (not connected). I've set up the correct apn profile and enabled the toggle on the card (see photos). All tests were done without the dsl cable plugged in 

How to reproduce (if possible): try to connect to the internet via a usb mobile key

Media/Photos (if possible):
![mobile](https://user-images.githubusercontent.com/30673373/79211961-337f9b00-7e47-11ea-90ec-94b9d31914f7.PNG)
![mobile2](https://user-images.githubusercontent.com/30673373/79211999-3f6b5d00-7e47-11ea-9729-8bee58be45e6.PNG)
![mobile3](https://user-images.githubusercontent.com/30673373/79212008-41352080-7e47-11ea-8545-01e0570dccbf.PNG)
![mobile4](https://user-images.githubusercontent.com/30673373/79212011-42fee400-7e47-11ea-8707-4202bb68878c.PNG)

**Comment by FrancYescO** [comment]
pretty sure cause is an icompatible dongle, what model is it? did you try using it on stock GUI?

**Comment by mattodinaturas** [comment]
> pretty sure cause is an icompatible dongle, what model is it? did you try using it on stock GUI?

it's an olicard 100 3g/2g usb key. I'll try on another modem on stock gui tomorrow

**Comment by FrancYescO** [comment]
news?

**Comment by FrancYescO** [comment]
@mattodinaturas post the result of `lsusb` and `dmesg | tail -n20` after inserting the usb key

**Comment by FrancYescO** [comment]
closing as no feedback provided, this probably can be fixed, after a reset and using latest GUI version, in a solution like this https://www.ilpuntotecnico.com/forum/index.php/topic,77519.msg255219.html#msg255219
