### ISSUE TITLE
unable to ssh

### ISSUE THREAD

**Issue by dga4130-renato** [Ansuel/tch-nginx-gui#939]
Latest dev.
ssh 192.168.0.2 -l root

Unable to negotiate with 192.168.0.1 port 22: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,kexguess2@matt.ucc.asn.au

**Comment by FrancYescO** [comment]
latest dev is not a version.
firmware missing.

and probably depends on the SSH client used.

**Comment by dga4130-renato** [comment]
true. ubuntu 20.04 breaks  diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 keys.
sorry for the mistake
