### ISSUE TITLE
Opening Devices card throws tens of errors

### ISSUE THREAD

**Issue by aetonsi** [Ansuel/tch-nginx-gui#941]
#### Device Model
DGA ( DGA4132 )
AGTHP_2.2.0
Version Cobalt (18.3.k)

#### Gui Version
9.5.54-3519b057

#### Description of problem
Whenever i open the "devices" tab, a lot of errors are thrown in the console, and "Error" is displayed under each mac address.

#### How to reproduce (if possible)
Open devices card , or switch to the tab while being in "device map", "wifi nurse" or "traffic monitor".

#### Media/Photos (if possible)
![image](https://user-images.githubusercontent.com/18366087/79728383-21da3f80-82ee-11ea-94b1-81883c199f7d.png)

**Comment by FrancYescO** [comment]
related to https://github.com/Ansuel/tch-nginx-gui/issues/941

**Comment by aetonsi** [comment]
> related to #941

Wait, 941 is this issue itself. I think you referenced the wrong issue

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/928
