### ISSUE TITLE
High ram usage

### ISSUE THREAD

**Issue by aetonsi** [Ansuel/tch-nginx-gui#944]
#### Device Model
DGA ( DGA4132 )
AGTHP_2.2.0
Version Cobalt (18.3.k)

#### Gui Version
9.5.54-3519b057

#### Description of problem
I found out that i have an extremely high ram usage, and i don't know why.
Is it normal?
I have installed just luci and aria2 as specific apps.

#### How to reproduce (if possible)
I don't know

#### Media/Photos (if possible)
![image](https://user-images.githubusercontent.com/18366087/79731268-53550a00-82f2-11ea-9007-319e8f0582c3.png)

##### (timestamps scrambled due to #942 )
![image](https://user-images.githubusercontent.com/18366087/79731278-56e89100-82f2-11ea-90dd-2a394088c952.png)

**Comment by FrancYescO** [comment]
RAM is here to be used

on my devices that is doing basically nothing (no device connected no app, just a PPP connection up) the use is ~350MB so just consider that usage normal

**Comment by aetonsi** [comment]
Oh ok i see...
I think i misread the graph. I thought that the device had 473.74mb **total available ram** (like 512mb total – X mb dedicated to the OS), so that the graph showed the **percentage of used ram**. That's why i reported it as an issue, i thought I was almost topping maxing out the ram usage.

But I just realized that 473.74mb is the **ram usage peak**... it could be useful seeing the total available ram, somewhere.
For example restructuring the graph to show the total available ram as Y axis maximum value, like this:
![image](https://user-images.githubusercontent.com/18366087/79754465-e5233e00-8317-11ea-8947-2ff286122858.png)
