### ISSUE TITLE
[enhancement] Add github link to currently installed version

### ISSUE THREAD

**Issue by aetonsi** [Ansuel/tch-nginx-gui#945]
#### Device Model
DGA ( DGA4132 )
AGTHP_2.2.0
Version Cobalt (18.3.k)

#### Gui Version
9.5.54-3519b057

#### Description of problem
It would be useful to have a link to the currently installed GUI version (eg., [9.5.54-3519b057](https://github.com/Ansuel/tch-nginx-gui/releases/tag/9.5.54) ) in the "GUI Settings" card (see example in the screenshot below).
Also, it would be useful to have a link on the auto update notification, when it shows.
Currently the GUI version is shown only **on** the GUI Settings card (which makes it difficult to copy, if necessary, because the card opens on click) and in the footer.

#### Media/Photos (if possible)
![image](https://user-images.githubusercontent.com/18366087/79732362-dcb90c00-82f3-11ea-891d-8304de3c3705.png)

![image](https://user-images.githubusercontent.com/18366087/79732888-957f4b00-82f4-11ea-9035-5b9fc83a7d09.png)

![image](https://user-images.githubusercontent.com/18366087/79732385-e478b080-82f3-11ea-9c0a-04d7e1227730.png)

**Comment by PrototypeGR** [comment]
Can you also do that for the version showing at the bottom?
![image](https://user-images.githubusercontent.com/14006475/102023170-419a0880-3d94-11eb-9c03-72088fd294af.png)

**Comment by FrancYescO** [comment]
footer is used for changelog
