### ISSUE TITLE
Version For Telstra TG799vac (TG789vac with DECT)

### ISSUE THREAD

**Issue by kevdagoat** [Ansuel/tch-nginx-gui#95]
Hi Guys,
Thanks for a great webui!! Works very well.
On behalf of the people at the Technicolor Gateways Custom Firmware Discussion (https://forums.whirlpool.net.au/forum-replies.cfm?t=2650998&p=1) could you try and make a version for the TG799vac. At the moment the TG789vac version of the web interface is working well apart from a few bugs, but doesn't include any DECT base settings.

Thanks

**Comment by Ansuel** [comment]
Ummmm the modal should be there... Can you provide a dump of the mtd3 and 4
partition?


Il Ven 3 Ago 2018, 11:42 kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
In what way, $ cat or physical copy?

**Comment by kevdagoat** [comment]
I am on firmware 16.3 currently

**Comment by Ansuel** [comment]
dd if=/dev/mtd3 of=/tmp/mtd3
Copy mtd3 in tmp and give it to me
Same for mtd4

Il Ven 3 Ago 2018, 13:09 kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
mtd3 [https://drive.google.com/open?id=1Q79tcCuP3UpNPumNUvdGK2PITFHDEeoH](url)

**Comment by Ansuel** [comment]
Also tell me the issue with this modem

Il Ven 3 Ago 2018, 14:00 kevdagoat <notifications@github.com> ha scritto:

**Comment by kevdagoat** [comment]
No telnet settings on system modal and uci invalid errors. No ability to install a different webui voip errors (as flywire has pointed out).

**Comment by kevdagoat** [comment]
In the system settings modal.

Do you have a MST/UNO 17.2 firmware for the TG799vac as it would fix all of these problems.

I will look at the log later.

**Comment by kevdagoat** [comment]
Also the static GUI tile reports “unsupported”.

**Comment by kevdagoat** [comment]
Not really. I’ll close it.
