### ISSUE TITLE
editing led lights a few questions 

### ISSUE THREAD

**Issue by EvoxOG** [Ansuel/tch-nginx-gui#951]
so i came across Hacking technicolour gateways and found the led stuff but i have a few questions 

1. when i turn the LEDs off via ssh is there a way to save it when after a  router reboot?
2. is there a way to edit the brightness of the LEDs and have that save after a reboot?
3. is it possible for a feature to be added to be able to turn all LEDs off at a click of a button in the GUI?
4. can i just stop/disable ledfw in init management to turn them off?

**Comment by FrancYescO** [comment]
1 no
2 no
3 yes
4 try

**Comment by EvoxOG** [comment]
> 
> 
> 1 no
> 2 no
> 3 yes
> 4 try

may I ask why 1 and 2 is not possible?

**Comment by FrancYescO** [comment]
no = not in the gui, using custom code you can do wheter you want.

**Comment by EvoxOG** [comment]
> 
> 
> no = not in the gui, using custom code you can do wheter you want.

where would the code be placed in what folder? if i was to try and write something like that? 

could i place this line > echo 0 > /sys/class/leds/power:red/brightness  somewhere in the router to auto issue that command when it is rebooted?

**Comment by FrancYescO** [comment]
`/etc/rc.local` is called on each boot.

**Comment by EvoxOG** [comment]
thanks so i went into that folder and it says this *by default this file does nothing* I just input that line in my post in the file and save it and it should work?

**Comment by FrancYescO** [comment]
probably yes or probably not as other services can turn on the led, just try

**Comment by EvoxOG** [comment]
thanks, I added all echo commands into that file and rebooted and it works only 1 problem is the command for wireless_5g does not work would you know why as all other commands worked fine? this was the command I used  > echo 0  /sys/class/leds/wireless_5g:green/brightness

**Comment by FrancYescO** [comment]
cause using /sys/class/leds/ will work until no other process access to the leds, you should find the service that is turning on the led and can be not that easy
