### ISSUE TITLE
Amule install/ uninstall script broken 

### ISSUE THREAD

**Issue by fdotcico** [Ansuel/tch-nginx-gui#953]
Device Model
TG789vac v2
Aqua (16.3.k)

Gui Version
9.5.58-7cec8715

Description of problem
Unable to install / start and uninstall the aMule extension

How to reproduce (if possible)
Look at pics below

Start/ Stop error (shares same error) :
![avvio](https://user-images.githubusercontent.com/64892891/81152393-33744600-8f82-11ea-8417-a5471bedcee9.PNG)

Uninstall error:
![uninstall](https://user-images.githubusercontent.com/64892891/81152409-366f3680-8f82-11ea-9a8e-8eab2e36f79c.PNG)

Grazie mille ragazzi per il supporto

**Comment by FrancYescO** [comment]
This should be fixed, pay attention that on MIPS devices some app install requires an USB inserted.
