### ISSUE TITLE
Bank 1 unknown version

### ISSUE THREAD

**Issue by neo82ita** [Ansuel/tch-nginx-gui#954]
Dopo aver aggiornato all’ultima dev .60, non mi vede più la versione del boot sul bank 1.
Dopo l’aggiornamento è un reboot si era resettato sulla gui originale, re installata ma dev ho questa situazione, non so se è normale o possa comportare dei problemi.
Per ora dopo qualche intoppo iniziale funziona tutto.

```

root@modemtim:~# find /proc/banktable -type f -print -exec cat {} ';'
/proc/banktable/active
bank_1
/proc/banktable/booted
bank_2
/proc/banktable/inactive
bank_2
/proc/banktable/bootedoid
5db3204b4f5d980688c27cdc
/proc/banktable/notbooted
bank_1
/proc/banktable/notbootedoid
Unknown/proc/banktable/activeversion
Unknown/proc/banktable/passiveversion
18.3.k.0451-3161011-20191025181819-3f83315f6d40733756f2a3ef5b192653d99f3c87
root@modemtim:~# cat /proc/banktable/active
bank_1
root@modemtim:~#

```

[DebugHelper2020-05-07-0028.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4589808/DebugHelper2020-05-07-0028.tar.gz)

**Comment by FrancYescO** [comment]
E' giusto così  ma non ho capito quando ti ha resettato la GUI originale, dopo il reboot non si è riavviato nuovamente?

**Comment by Ansuel** [comment]
la configurazione si è eliminata o si è resettata solo l'interfaccia?

Il giorno gio 7 mag 2020 alle ore 01:39 Francesco M <
notifications@github.com> ha scritto:

**Comment by neo82ita** [comment]
Dopo aver aggiornato alla dev.60, sopra nella schermata c’era scritto che dovevo fare un reboot.
Ho riavviato e mi sono ritrovato con la dev.49 😓, ho provato ad aggiornare da gui ma dava il messaggio di spazio insufficiente.
Allora ho riavviato di nuovo e la gui si è resettata a quella originale.
Non mi ricordo se al primo riavvio mi si erano cancellate anche tutte le impostazioni (dev.49), ho se si fosse completamente resettato al secondo riavvio (gui originale).
A questo punto ho installato da ssh.

**Comment by Dark4Codrutz** [comment]
Suggest: edit title

**Comment by FrancYescO** [comment]
risolto con https://github.com/Ansuel/tch-nginx-gui/commit/85c8a0961bee4fef7d703fd7da44dd89bbd559af
