### ISSUE TITLE
9.5.60 TG789vac V2

### ISSUE THREAD

**Issue by lorenzocanale-LC** [Ansuel/tch-nginx-gui#955]
The update from stable to latest dev 9.5.60 didn't work on my TG789vac v2 FW UNO 17.2
Scrivo in Italiano perché avevo già scritto il post sul puntotecnico
Procedura che mi ha portato in situazione di led arancio lampeggiante:
Ho collegato il tg789vac v2 in cascata LAN-WAN con il mio router, gli ho fatto prendere un indirizzo IP della mia LAN dal DHCP, ho installato l'ultima GUI stabile (Era afflitto dal bug dell'aggiornamento), e solo dopo ho aggiornato all'ultima DEV. (qua**) A questo punto mi è spuntato la scritta che un riavvio era atteso per effettuare il Bank Planning. Ho effettuato il riavvio manuale da GUI. Il primo riavvio è andato a buon fine, mi sono connesso, tutto funzionava, nel logread ho visto che stava ancora lavorando
A questo punto si è riavviato nuovamente ma adesso è in Arancio lampeggiante (Sospetto TFTP) ho sbagliato qualcosa?
P.S. Ecco il log https://pastebin.com/SGkTuTE9
P.S. 1: Ho caricato con TFTP, il router è partito subito con la configurazione che avevo prima dell'update alla dev, ho rifatto l'update alla dev e sono tornato qua** (Vedi sopra). Allora ho cancellato tutto l'overlay e ho ricominciato da capo. Stavolta ho effettuato l'optimal bank planning prima di installare la gui e tutto funzionava, ho installato la GUI e tutto funzionava, ma al primo riavvio siamo punto e a capo, led arancio lampeggiante... Sospetto che il TG789 non digerisca il fatto di usare il bank1 come overlay

**Comment by FrancYescO** [comment]
chiudo che stiamo portando avanti la questione su ilpuntotecnico https://www.ilpuntotecnico.com/forum/index.php/topic,81461.msg264337.html#msg264337
