### ISSUE TITLE
App TIM Modem non rileva TIM Hub

### ISSUE THREAD

**Issue by Faddix** [Ansuel/tch-nginx-gui#959]
Versione software : AGTHP_2.2.1_001
Versione GUI :  9.5.75-9192b5cc
In collegamento WIFI il router non viene conosciuto e quindi esce scritto modem generico, mentre con accesso remoto dice "Non è stato possibile procedere con la richiesta"

**Comment by FrancYescO** [comment]
penso sia semplicemente perchè stai usando un firmare beta tralaltro anche vecchio

**Comment by Faddix** [comment]
Ah e io che pensavo fosse l'ultimo fw... dove posso trovare l'ultima versione?

**Comment by FrancYescO** [comment]
2.2.0 https://drive.google.com/drive/u/0/folders/1sHmL087eixCzzokBD0kWpDZ8hDF0wTjY
