### ISSUE TITLE
Enhancement Request: Replace Traffic Monitor with vnstat

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#96]
Traffic Monitor is very limited.

It would be nice to replace with: vnstat -m|-d|-h

Persistent stats on USB drive is also nice.

Ref: https://openwrt.org/docs/guide-user/services/network_monitoring/vnstat?s[]=vnstat

**Comment by kevdagoat** [comment]
I think this needs to be closed now. The dev GUI has a Stats page with quite a good graph.

**Comment by flywire** [comment]
I disagree, they serve a different purpose. The stats page couldn't explain long term usage. Vnstats can, it uses minimal resources and is fairly resilient to reconfiguring the modem. There is also a graphical module in luci.

**Comment by kevdagoat** [comment]
Ok then will look into it.

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/244#issuecomment-426577498

**Comment by flywire** [comment]
@FrancYescO - something like this:

```
# Install vnstat
# https://openwrt.org/docs/guide-user/services/network_monitoring/vnstat

# if vnstat active goto :end

# if vnstat package not installed install it
# opkg update
# opkg install vnstat

# get WAN connection
. /lib/functions/network.sh; if network_get_device if_wan wan; then
echo "Your WAN Interface is: $if_wan"; else echo "Cant find a active WAN Connection, please activate it" [and goto :end]; fi

echo "Editing /etc/vnstat.conf"
sed -e 's/.*Interface "*/Interface "$if_wan"/' -i /etc/vnstat.conf
sed -e 's/.*UpdateInterval "*/UpdateInterval 300/' -i /etc/vnstat.conf

echo "Set day months change"
sed -e 's/.*MonthRotate "*/MonthRotate 23/' -i /etc/vnstat.conf

# if USB-A1 available
echo "Store persistent stats on USB-A1"
sed -e 's/.*DatabaseDir "*/DatabaseDir "/mnt/usb/USB-A1/vnstat"/' -i /etc/vnstat.conf

# start after reboot
/etc/init.d/vnstat enable
/etc/init.d/vnstat start

:end
```

**Comment by kevdagoat** [comment]
Looks good!
Will have a go with it tonight.

**Comment by flywire** [comment]
Packages info:

https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/base/etc/init.d/rootdevice
> apply_right_opkg_repo()

https://forums.whirlpool.net.au/archive/2650998#r56274778
>For all BCM63138 Technicolor Modem (DGA4130/DGA4132/TG800/...) you can use these ...
 Same as: https://github.com/Ansuel/tch-nginx-gui/tree/master/decompressed/upgrade-pack-specificDGA/etc

https://forums.whirlpool.net.au/archive/2650998#r56279066
>these packages are complied without support for NLS, and will NOT run on a Telia TG799vac with 16.2 Jade

**Comment by flywire** [comment]
@Kherby - Can you try https://github.com/Ansuel/tch-nginx-gui/issues/96#issuecomment-426968584?

**Comment by flywire** [comment]
@Ansuel - Can the https://github.com/Ansuel/tch-nginx-gui/issues/96#issuecomment-426968584 _reboot_ in script be replaced with something better? (Script works apart from package repo configuration.)

**Comment by Ansuel** [comment]
why we should reboot after vnstat update o.o

**Comment by flywire** [comment]
Execute in lua: `os.execute('vnstat -d')`

**Comment by Ansuel** [comment]
why not just run the command directly ?

**Comment by flywire** [comment]
I run command directly but others need gui. Even for me a couple of clicks in a gui is easy.

**Comment by flywire** [comment]
Note: It appears vnStat version 1.12 in tg799 package database is not compatible (older) than tg800 package version.

**Comment by kevdagoat** [comment]
Is this ok to close?

**Comment by flywire** [comment]
Is it OK to merge?

**Comment by flywire** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/96#issuecomment-426968584

Can we roll this out in the interim?

> For TG799 packages replace these files:
> 
> /etc/opkg.conf :
> 
> ```
> dest root /
> dest ram /tmp
> lists_dir ext /var/opkg-lists
> option overlay_root /overlay
> arch brcm63xx-tch 200
> arch brcm63xx 300
> ```
> /etc/opkg/distfeeds.conf :
> 
> ```
> src/gz base http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/base
> src/gz luci http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/luci
> src/gz management http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/management
> src/gz packages http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/packages
> src/gz routing http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/routing
> src/gz telephony http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/telephony
> ```

**Comment by kevdagoat** [comment]
Is this ok to close?

The TG799vac’s are running out of space so most likely not a good idea

**Comment by flywire** [comment]
> Is this ok to close?

Is it implemented yet? No.

btw storage used is miniscule.

**Comment by FrancYescO** [comment]
Closing as when possible we want to avoid replacing/adding stock packages.

Probably adding it as an installable extension is the better choice
