### ISSUE TITLE
Technicolor DGA 2231 Unlock Request

### ISSUE THREAD

**Issue by ic125** [Ansuel/tch-nginx-gui#962]
Trying to unlock the GUI tiles on a DGA 2231 with Firmware 18.1 Champagne. On the factory firmware many of the features listed in the datasheet are unavailable.

Datasheet: https://storage.googleapis.com/nxl/technicolor/technicolor-dga2231-datasheet.pdf

Product Name
MediaAccess DGA2231
Software Version
18.1
Firmware Version
18.1.0203-1641038-20180808175126
Firmware OID
5b6b117e7ba7b510faef5731
Bootloader Version
18.15.1085-0000000-20180411075238-650d1427bbf2244db69c4ae7b18202b2d7356a17
Hardware Version
VCNT-C

**Comment by FrancYescO** [comment]
better to open this here https://github.com/kevdagoat/hack-technicolor/issues

**Comment by FrancYescO** [comment]
@ic125 did you try something to get root?
