### ISSUE TITLE
voip tim non si registra

### ISSUE THREAD

**Issue by putipower** [Ansuel/tch-nginx-gui#964]
Device Model: 4132
Gui Version:9.5.82

Description of problem:non si registra il voip,registrazione rifiutata.durante l'installazione della gui scrive mapper error
rimessa 9.5.77 e il voip e' tornato a registrarsi subito e a funzionare

**Comment by FrancYescO** [comment]
serve il log dell'installazione fatta con opzione debug se ti ha dato mapper error

**Comment by putipower** [comment]
ho provato a fare lo zip debug ma mi si blocca il modem lampeggiando per decine di minuti e non crea il file...
comunque mapper erro me lo scriveva anche prima di questa versione mentre effettuo l'installazione di un aggiornamento

**Comment by FrancYescO** [comment]
ma mapper error visualizzato in alto nella modal? quello è ignorabile o comunque non c'entra nulla con questa issue

fai un logread quando il voip non si registra

**Comment by Gae-IT** [comment]
confermo che non e' per nulla facile configurare il voip, credevo di avere la configurazione funzionante come backup, ho rimesso i file mmpbxrvsipnet e mmpbx e non funzionava lo stesso, quindi ho editato mmpbxrvsipnet ed ho sostituito le stringhe del tipo "voiceE31B5D420A67D98465A7B68FF1A61A10" con "sip_net" e magicamente si e' registrato.

quando vengono modificati/salvati i campi del voip vengono generate quelle stringhe, sono sempre diverse, quando invece basterebbe lasciare "sip_net"

**Comment by FrancYescO** [comment]
la gui funziona se viene utilizzata come sola per configurare, se si iniziano a mixare i file di configurazione è normale non trovarsi piu con le config e avere roba non funzionante

**Comment by Gae-IT** [comment]
nel mio caso non mi riferivo a tim, ma ad altri 2 gestori
settimane fa avevo provato anche a cancellare tutto e riconfigurare da zero e non ci sono riuscito, ho risolto con file trovati online, dopo aver ottenuto 2 configurazioni funzionanti ho fatto backup
e quindi consiglio di fare backup dei file mmpbx* prima di fare prove per replicare il problema

**Comment by putipower** [comment]
ho notato che il problema si presenta solo se ho in uso il relay pppoe....se il modem secondario e' spento si registra immediatamente,mentre nel caso di doppio utilizzo per registrarsi il voip necessita di un cambio ip sul primario.
il voip e' sempre disattivato sul secondo mdem

**Comment by FrancYescO** [comment]
Non è un problema di GUI.
TIM autorizza la registrazione dell'account voip da una singolo IP, l'ultimo che prende la tua linea fisica, il modem secondario dovrebbe semplicemente condividere la connessione che fa il primo senza instaurare una seconda PPP.
