### ISSUE TITLE
Impossibile aggiornare la GUI su TG789vac v2

### ISSUE THREAD

**Issue by umbertoB67** [Ansuel/tch-nginx-gui#965]
Ho questo modem:
Produttore: Technicolor
Nome prodotto: MediaAccess TG789vac v2 ( MediaAccess TG789vac v2 )
Versione software: 16.3.7636-2921002-20170419153951
Versione datapump: A2pv6F039v2.d26m
OID firmware: 58f768a7e474f4c618fc2551
Versione bootloader: 2.0.85
OID bootloader: unknown
Versione hardware: VANT-6

**Versione GUI: 9.4.70-184d06d3**
**Canale aggiornamento: Stabile**

Quando mi collego all'interfaccia di amministrazione mi dice:
GUI non aggiornata - Aggiornamento disponibile! Versione: 9.5.84

Finora gli aggiornamenti sono sempre andati tutti senza problemi, ma, da qualche settimana, quando clicco su "AGGIORNA" e cerco di fare l'aggiornamento della GUI, il sistema resta così e non fa nulla:
![image](https://user-images.githubusercontent.com/10993001/83236262-844b1900-a193-11ea-9ef0-b743158ebf9d.png)

Quale potrebbe essere il problema?
Grazie. Ciao.

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/921
