### ISSUE TITLE
[Feature Request] Zerotier support

### ISSUE THREAD

**Issue by netizen428** [Ansuel/tch-nginx-gui#967]
Hi,
If possible with the hardware i'd like to request support for Zerotier? https://www.zerotier.com/ and https://openwrt.org/packages/pkgdata_lede17_1/zerotier

It's a very underrated alternative to a standard VPN server, especially if you are trying to establish a VPN server through double NAT such as found on mobile broadband connections without a public IP address...

**Comment by FrancYescO** [comment]
have you tried some generic openwrt install?
like
https://github.com/mwarning/zerotier-openwrt/wiki

**Comment by netizen428** [comment]
> have you tried some generic openwrt install?
> like
> https://github.com/mwarning/zerotier-openwrt/wiki

Thanks for the reply, unfortunately my initial attempt failed so it's not as simple as a few commands it seems....

`root@dsldevice:~# opkg install zerotier
Unknown package 'zerotier'.
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (luci http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (management http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/management). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (routing http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/routing). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (packages http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (telephony http://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/smp/packages/telephony). Skipping.
 * opkg_install_cmd: Cannot install package zerotier.
root@dsldevice:~#
`

**Comment by FrancYescO** [comment]
so you need to compile the package backported to openwrt 15.05..
