### ISSUE TITLE
Problem luci installation

### ISSUE THREAD

**Issue by mountmatt** [Ansuel/tch-nginx-gui#968]
I tried to install Luci but i had this problem:

> Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/Packages.gz

Updated list of available packages in /var/opkg-lists/chaos_calmer_base
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_packages
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_luci
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_routing
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/chaos_calmer_telephony
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management/Packages.gz
Updated listCollected errors:
 * opkg_conf_parse_file: Duplicate src declaratiNo packages removed.
Installing libuci-lua (2017-04-12.1-2) to root...
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/libuci-lua_2017-04-12.1-2_brcm63xx-tch.ipk
Installing luci (git-18.021.57137-5fa2132-1) to root...
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci/luci_git-18.021.57137-5fa2132-1_all.ipk
Installing rpcd (2016-06-30-23417e94d25570e6d62542bac46edd51e8e0243a) to root...
Downloading https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base/rpcd_2016-06-30-23417e94d25570e6d62542bac46edd51e8e0243a_brcm63xx-tch.ipk
Configuring rpcd.
icate src declaration (chaos_calmer_telephony https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (chaos_calmer_management https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/management). Skipping.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for libuci-lua:
 * 	libc * 	libc * 	libc * 	libc * 
 * opkg_install_cmd: Cannot install package libuci-lua.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	libc * 	kernel * 	kernel * 	kernel * 	kernel * 	kernel * 	kernel * 	libc * 	libc * 	libc * 	libc * 
 * opkg_install_cmd: Cannot install package luci.
mv: can't rename '/www/cgi-bin': No such file or directory
mv: can't rename '/www/luci-static': No such file or directory
mv: can't rename '/www/index.html': No such file or directory
rm: can't remove '/usr/lib/lua/uci.so': No such file or directory
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
> 
Someone can help me? THANKS!

**Comment by FrancYescO** [comment]
missing versions and model.

**Comment by mountmatt** [comment]
Sorry, DGA4132, firmware 2.0.0 e Versione GUI 9.5.38-ba81e28c, THANKS 
Now i see this on installation 
![image](https://user-images.githubusercontent.com/66991839/84771926-780bec00-afda-11ea-9fc6-c10a63741fa3.png)
 and this in Gui opions, no possibility to install any app
![image](https://user-images.githubusercontent.com/66991839/84772030-a4276d00-afda-11ea-939f-1d4430dbc746.png)

**Comment by FrancYescO** [comment]
Update to latest stable 2.2.0 firmware.

**Comment by mountmatt** [comment]
doesn't work ...2.2.0 amd last ansuel gui. I think (i look around on forums) i miss feed in distfeeds.conf and all in opkg.conf..i don't know why, can you help me? I' don't know what else can i do.

**Comment by FrancYescO** [comment]
just run `/etc/init.d/rootdevice debug` and post log

**Comment by mountmatt** [comment]
Here you are
/etc/ssl$ /etc/init.d/rootdevice debug
Root Script: Installing in progress...
Root Script Start rooting
Root Script Setting root flag
Root Script Reset unlock bit
Root Script Save root password if modified
Root Script Setting & Enabling Dropbear SSH Server
Root Script Restarting Dropbear SSH Server
Root Script Executing /etc/modgui_scripts/01_prereq.sh
Root Script Disabling watchdog...
Root Script Checking Free RAM...
Root Script Executing /etc/modgui_scripts/02_specific.sh
Root Script Checking opkg feeds...
Root Script Applying specific model fixes...
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (chaos_calmer_base https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/base). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (chaos_calmer_packages https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (chaos_calmer_luci https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (chaos_calmer_routing https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/routing). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (chaos_calmer_telephony https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/telephony). Skipping.
Package busybox_telnet (1.28.4-3) installed in root is up to date.
Package libopenssl (1.0.2s-1) installed in root is up to date.
Package openssl-util (1.0.2s-1) installed in root is up to date.
Root Script Executing /etc/modgui_scripts/03_various.sh
Root Script Enabling hardware serial console...
Root Script Fixing sysupgrade if needed...
Root Script Restoring and enabling few transformer mappers...
Root Script Transformer lib check
Root Script Creating custom GUI utils symlinks...
Root Script Add checkversion to cron...
Root Script Executing /etc/modgui_scripts/04_config.sh
Root Script Check original config
Root Script Unlocking web interface if needed
Root Script Check if variant_friendly_name set
Root Script Remove https check
Root Script Check driver setting
Root Script Check Dropbear config file
Root Script Check eco paramaters
Root Script Create GUI type in config
Root Script Add new web options
Root Script New DHCPRelay Option
Root Script Suppressing wansensing logs
Root Script Create new option for led definitions
Root Script Creating and checking real version
Root Script Implementing WoL
Root Script Apply new xDSL options
Root Script Adding fast cache options
Root Script Checking if wan_mode option exists...
Root Script Checking DoSprotect kernel modules...
Root Script Enabling and starting DoSprotect service...
Root Script Checking mobiled libs...
Root Script Checking if intercept is enabled and disabling if it is...
Root Script Disabling coredump reboot...
Root Script Restoring nginx additional options if needed...
Root Script Adding missing voicednd rule if needed
Root Script Doing various checks and generating hashes...
Root Script Update branch detected: STABLE
Root Script GUI hash set: f4d6992ba9f8d56ceacafe21b286361d
Root Script Resetting version info...
Root Script Decrypting any encrypted password present in config
Root Script Executing /etc/modgui_scripts/05_app.sh
Root Script Trafficmon inizialization
Root Script Enable DLNAd
Root Script Enable new upnp
Root Script Move Aria2 dir
Root Script Reinstalling Telstra GUI if needed...
Root Script Executing /etc/modgui_scripts/06_network.sh
IspConfigHelper Detecting ISP and cleanup...
IspConfigHelper Checking detected ISP and setting CWMP...
Invalid ISP
Root Script Adding ipoe in network config...
Root Script Removing default loopback DNS Servers...
Root Script Purify WAN network config...
Root Script Fix DNS bug, make sure odhcp is enabled
Root Script Enabling odhcpd on boot
Root Script Checking and fixing dnsmasq daemon naming...
Root Script Sync DHCP configuration for new GUI
Root Script Reworking sfp interface in network config...
Root Script Attempt to clean the wansensing script from hardcoded interfaces...
Root Script Cleaning cups firewall rule...
Root Script Apply CVE 2019-11477 workaround
Root Script Checking atmdevice interface naming...
Root Script Restarting dnsmasq if needed...
Root Script Executing /etc/modgui_scripts/99_postreq.sh
Root Script Applying modifications
Root Script Resetting cwmp and watchdog
Root Script Process done.
Root Script Restarting transformer
Root Script Stopping nginx
Root Script Restarting nginx...

**Comment by FrancYescO** [comment]
reset and/or try latest dev version

**Comment by FrancYescO** [comment]
news?

**Comment by FrancYescO** [comment]
should be okay.
