### ISSUE TITLE
Empty gateway page

### ISSUE THREAD

**Issue by Andrea055** [Ansuel/tch-nginx-gui#969]
Hello, when I try to access the router configuration page, the page appears empty without being able to see any cards.

The model is: TG789vac XTREAM 35B.
I leave attached the screen that appears empty.

![immagine](https://user-images.githubusercontent.com/26500347/84896118-a6a1c980-b0a3-11ea-9957-6a2c3b0c864b.png)

**Comment by Andrea055** [comment]
I forgot to attach the log.
Here it is: Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.645000] vrgEndptDoInit(): The EPPROV_XdrvSlicGains cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.654000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 189ms):Couldn't get the prov item !!! provItemID 628^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.664000] vrgEndptDoInit(): The EPPROV_Si3226x_General_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.673000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 209ms):Couldn't get the prov item !!! provItemID 629^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.684000] vrgEndptDoInit(): The EPPROV_Si3226x_Ring_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.693000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 228ms):Couldn't get the prov item !!! provItemID 630^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.704000] vrgEndptDoInit(): The EPPROV_Si3226x_Impedance_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.717000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 252ms):Couldn't get the prov item !!! provItemID 631^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.727000] vrgEndptDoInit(): The EPPROV_Si3226x_Dcfeed_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.736000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 271ms):Couldn't get the prov item !!! provItemID 632^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.747000] vrgEndptDoInit(): The EPPROV_Si3217x_General_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.756000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 291ms):Couldn't get the prov item !!! provItemID 633^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.767000] vrgEndptDoInit(): The EPPROV_Si3217x_Ring_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.775000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 311ms):Couldn't get the prov item !!! provItemID 634^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.786000] vrgEndptDoInit(): The EPPROV_Si3217x_Impedance_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.795000] ^[[0;33;41m[ERROR ept] Provision ,3080: (ts: 53s 331ms):Couldn't get the prov item !!! provItemID 635^[[0m
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.806000] vrgEndptDoInit(): The EPPROV_Si3217x_Dcfeed_Cfg cannot be found in provTable !!! ^M
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.846000] ******* DSP: Found BCM63138 *******
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.850000] ******* DSP: In PCM Mode *******
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.854000] ******* DSP: PCM running in 16 bit mode *******
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.860000] gInterruptCounter     = 0xBFFB3F10
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.864000] gInterruptErrors      = 0xBFFB3F14
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.869000] halShimEntryCount     = 0x00000002
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.874000] gDectTestMode           = 0xbffb405c
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.879000] dectBuffStart           = 0xbffb4044
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.883000] gDectRxOutOfSyncCounter = 0xbffb4060
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.888000] gDectTxOutOfSyncCounter = 0xbffb4064
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.893000] ddrAddrTxV              = 0xbffb3fe8
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.898000] ddrAddrRxV              = 0xbffb3fec
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.903000] 32 ms ECAN tail-length
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.906000] *** dmaCtl[0].rx[0].descVirt = 0xFFDE77D0
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.911000] *** dmaCtl[0].rx[1].descVirt = 0xFFDE77D8
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.917000] *** dmaCtl[0].tx[0].descVirt = 0xFFDE7000
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.922000] *** dmaCtl[0].tx[1].descVirt = 0xFFDE7008
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.927000] *** buffer size: 640
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.930000] *** Ownership for TX desc 1 not set. Use this buffer.
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.937000] bosTaskCreate: Task Name: HTSK Binding 0xcdc93ca0
Jun 17 14:01:53 OpenWrt kern.warn kernel: [  121.943000] ^[[0;35m[DBG xdrv_slic] slicSi32261Init: (ts: 53s 493ms):SLIC: Starting 32261 device and line initializion...^[[0m
Jun 17 14:01:54 OpenWrt kern.warn kernel: [  122.457000] ^[[0;35m[DBG xdrv_slic] deviceSiLabsReset: (ts: 54s 9  ms):SLIC: Reset applied on GPIO pin 7^[[0m
Jun 17 14:01:54 OpenWrt kern.warn kernel: [  122.471000] ^[[0;35m[DBG xdrv_slic] initSiLabsDevice: (ts: 54s 23 ms):SLIC: Initializing SiLabs device 0^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.763000] ^[[0;35m[DBG xdrv_slic] initSiLabsDevice: (ts: 55s 316ms):SLIC: SiLabs device BOM Type: 8^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.772000] ^[[0;35m[DBG xdrv_slic] initSiLabsDevice: (ts: 55s 325ms):SLIC: SiLabs device 0 initialized OK^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.783000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 335ms):SLIC: SiLabs Locale set to 13^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.792000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 344ms):SLIC: Initializing SiLabs FXS line 0^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.824000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 376ms):FXS channel 0 Rx Gain: -3^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.832000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 384ms):FXS channel 0 Tx Gain: -3^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.855000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 408ms):SLIC: FXS line 0 RX timeslot = 0 ^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.865000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 417ms):SLIC: FXS line 0 TX timeslot = 0 ^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.874000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 427ms):SLIC: SiLabs FXS line 0 initialized OK^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.885000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 437ms):SLIC: Initializing SiLabs FXS line 1^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.917000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 469ms):FXS channel 1 Rx Gain: -3^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.925000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 477ms):FXS channel 1 Tx Gain: -3^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.948000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 501ms):SLIC: FXS line 1 RX timeslot = 1 ^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.958000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 510ms):SLIC: FXS line 1 TX timeslot = 1 ^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.967000] ^[[0;35m[DBG xdrv_slic] initSiLabsLines: (ts: 55s 520ms):SLIC: SiLabs FXS line 1 initialized OK^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.978000] ^[[0;35m[DBG xdrv_slic] slicSi32261Init: (ts: 55s 530ms):SLIC: 32261 device 0 and FXS initializion COMPLETED OK !^[[0m
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.990000] boardHalInit completed
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.993000] bosTaskCreate: Task Name: HRTBEAT Binding 0xca0c7060
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  123.999000] bosTaskCreate: Task Name: VRGDISP Binding 0xcdea7660
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  124.006000] bosTaskCreate: Task Name: HCAS Binding 0xcdc970c0
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  124.014000] DSP: Interrupt Ids
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  124.016000] ---------------
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  124.019000] InterruptId      = 148
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  124.403000] EndpointInit completed
Jun 17 14:01:55 OpenWrt kern.warn kernel: [  124.406000] dgasp: kerSysRegisterDyingGaspHandler: endpoint registered
Jun 17 14:01:56 OpenWrt user.debug mmpbxd[5901]: [REFDEV]        :E: initialiseReferenceImpl:1674 - Async read handle registration failed^M
Jun 17 14:01:56 OpenWrt user.debug mmpbxd[5901]: [REFDEV]        :E: initialiseReferenceImpl:1678 - Async read handle registration failed^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 2] WARMLINE deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [**0] HOLD activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [**1] HOLD activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [**2] HOLD activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [profile_0] HOLD activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [profile_1] HOLD activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [**0] CLIP activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [**1] CLIP activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [**2] CLIP activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [profile_0] CLIP activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [profile_1] CLIP activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [***] CLIP activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 1] CONFERENCE deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 2] CONFERENCE deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 1] TRANSFER deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 2] TRANSFER deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 1] WARMLINE deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [FXS 2] WARMLINE deactivated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [profile_0] MWI activated^M
Jun 17 14:01:56 OpenWrt user.info mmpbxd[5901]: [profile_1] MWI activated^M
Jun 17 14:01:57 OpenWrt daemon.err nginx: 2020/06/17 14:01:57 [error] 4569#0: *5 open() "/www/docroot/theme/style.css" failed (2: No such file or directory), client: 192.168.1.100, server: localhost, request: "GET /theme//style.css?version= HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/password.lp"
Jun 17 14:01:58 OpenWrt daemon.notice miniupnpd[4943]: remove port mapping 54441 UDP because it has expired
Jun 17 14:01:58 OpenWrt daemon.notice miniupnpd[4943]: remove port mapping 54441 TCP because it has expired
Jun 17 14:02:00 OpenWrt daemon.err nginx: 2020/06/17 14:02:00 [error] 4569#0: *5 lua entry thread aborted: runtime error: /www/lua/cards_limiter.lua:1: loop or previous error loading module 'web.dyntab_helper' stack traceback: coroutine 0: [C]: in function 'require'      /www/lua/cards_limiter.lua:1: in function </www/lua/cards_limiter.lua:1>        (tail call): ?  /www/lua/cards.lua:71: in function 'cards'      [string "cards.lp"]:8: in function 'n'  /usr/lib/lua/web/lp.lua:55: in function 'include'       [string "/gateway.lp"]:6: in function 'n'      /usr/lib/lua/web/web.lua:101: in function 'process'      content_by_lua(nginx.conf:117):4: in function <content_by_lua(nginx.conf:117):1>, client: 192.168.1.100, server: localhost, request: "GET / HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/"
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Events are waiting, need to contact ACS
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: CONNECTION: Connecting to server retry 2.
Jun 17 14:02:02 OpenWrt daemon.err cwmpd[5596]: APP_TRACE: bad address ''
Jun 17 14:02:02 OpenWrt daemon.crit cwmpd[5596]: CONNECTION: Failed to resolve.
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Nb of retries 3
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Min retry wait time 20
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Max retry wait time 40
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Effective retry wait time 20
Jun 17 14:02:02 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: LAST STATE: <Idle>
Jun 17 14:02:04 OpenWrt daemon.err nginx: 2020/06/17 14:02:04 [error] 4569#0: *6 lua entry thread aborted: runtime error: /www/lua/cards_limiter.lua:1: loop or previous error loading module 'web.dyntab_helper' stack traceback: coroutine 0: [C]: in function 'require'      /www/lua/cards_limiter.lua:1: in function </www/lua/cards_limiter.lua:1>        (tail call): ?  /www/lua/cards.lua:71: in function 'cards'      [string "cards.lp"]:8: in function 'n'  /usr/lib/lua/web/lp.lua:55: in function 'include'       [string "/gateway.lp"]:6: in function 'n'      /usr/lib/lua/web/web.lua:101: in function 'process'      content_by_lua(nginx.conf:117):4: in function <content_by_lua(nginx.conf:117):1>, client: 192.168.1.100, server: localhost, request: "POST /gateway.lp HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/"
Jun 17 14:02:04 OpenWrt daemon.err nginx: 2020/06/17 14:02:04 [error] 4569#0: *14 open() "/www/docroot/theme/style.css" failed (2: No such file or directory), client: 192.168.1.100, server: localhost, request: "GET /theme//style.css?version= HTTP/1.1", host: "192.168.1.254", referrer: "http://192.168.1.254/gateway.lp"
Jun 17 14:02:13 OpenWrt user.info root: Mmpbx is started, mmpbx.state=RUNNING !
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Events are waiting, need to contact ACS
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: CONNECTION: Connecting to server retry 3.
Jun 17 14:02:22 OpenWrt daemon.err cwmpd[5596]: APP_TRACE: bad address ''
Jun 17 14:02:22 OpenWrt daemon.crit cwmpd[5596]: CONNECTION: Failed to resolve.
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Nb of retries 4
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Min retry wait time 40
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Max retry wait time 80
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Effective retry wait time 78
Jun 17 14:02:22 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: LAST STATE: <Idle>
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Events are waiting, need to contact ACS
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: CONNECTION: Connecting to server retry 4.
Jun 17 14:03:40 OpenWrt daemon.err cwmpd[5596]: APP_TRACE: bad address ''
Jun 17 14:03:40 OpenWrt daemon.crit cwmpd[5596]: CONNECTION: Failed to resolve.
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Nb of retries 5
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Min retry wait time 80
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Max retry wait time 160
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Effective retry wait time 105
Jun 17 14:03:40 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: LAST STATE: <Idle>
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Events are waiting, need to contact ACS
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: CONNECTION: Connecting to server retry 5.
Jun 17 14:05:25 OpenWrt daemon.err cwmpd[5596]: APP_TRACE: bad address ''
Jun 17 14:05:25 OpenWrt daemon.crit cwmpd[5596]: CONNECTION: Failed to resolve.
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Nb of retries 6
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Min retry wait time 160
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Max retry wait time 320
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: Effective retry wait time 290
Jun 17 14:05:25 OpenWrt daemon.info cwmpd[5596]: PROT_TRACE: LAST STATE: <Idle>
Jun 17 14:07:39 OpenWrt authpriv.info dropbear[6047]: Child connection from 192.168.1.100:55230
Jun 17 14:07:44 OpenWrt authpriv.notice dropbear[6047]: Password auth succeeded for 'root' from 192.168.1.100:55230
Jun 17 14:08:23 OpenWrt authpriv.info dropbear[6047]: Exit (root): Exited normally
Jun 17 14:08:30 OpenWrt authpriv.info dropbear[6060]: Child connection from 192.168.1.100:53110
Jun 17 14:08:33 OpenWrt authpriv.notice dropbear[6060]: Password auth succeeded for 'root' from 192.168.1.100:53110

**Comment by FrancYescO** [comment]
using unsupported firmware, update it.
