### ISSUE TITLE
DGA4130 impossibile sbloccare

### ISSUE THREAD

**Issue by antoweb** [Ansuel/tch-nginx-gui#971]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>
Ciao,
a parte che i link delle guide non portano a niente, ma dove sis carica il tool per eseguire root? 

Device Model: 
Gui Version:

Description of problem:

How to reproduce (if possible):

Media/Photos (if possible):

**Comment by FrancYescO** [comment]
Non mi risulta che i link nel README non portano a niente, i link son giusti quindi segui le guide forum e se serve chiedi supporto li.

**Comment by antoweb** [comment]
> Non mi risulta che i link nel README non portano a niente, i link son giusti quindi segui le guide forum e se serve chiedi supporto li.

Oggi me le apre. Grazie
