### ISSUE TITLE
supports sta?

### ISSUE THREAD

**Issue by jinglei207** [Ansuel/tch-nginx-gui#972]
Is it possible to connect modem to another wifi?

**Comment by FrancYescO** [comment]
this is client mode and not sta.
telstra do something about mesh mode on their firmware, but isn't clear how it works, basically the answer is no.

**Comment by jinglei207** [comment]
> this is client mode and not sta.
> telstra do something about mesh mode on their firmware, but isn't clear how it works, basically the answer is no.
Thanks
