### ISSUE TITLE
"Uncaught SyntaxError: unexpected token: keyword 'new'" when upgrading to developer GUI

### ISSUE THREAD

**Issue by t0rzz** [Ansuel/tch-nginx-gui#975]
Device Model: AGTHP 2.2.0 (18.3.k)
Gui Version: 9.5.38 stable

Description of problem:
When upgrading from stable to DEV, the javascript console shows _"Uncaught SyntaxError: unexpected token: keyword 'new'"_ and the upgrading status bar is just black and empty. It could be a jQuery problem.
**The upgrade anyway completes to the latest dev version.**

How to reproduce (if possible):
Upgrade from stable (9.5.38) to dev. A modal appears, and it remains empty.

Media/Photos (if possible):
No way right now.

**Comment by FrancYescO** [comment]
pretty sure already fixed in dev version

**Comment by t0rzz** [comment]
[OT]Fra, scrivo in inglese giusto perchè la community è globale, però sono italiano anche io.[/OT]
The 2.2.2(beta 1 - 19.4) version is not compatible with the binaries offered by the OpenWRT repository, can you confirm it?

Although I made it running with the GUI thanks to SCP (SFTP and BZ2 are not working with 19.4), but surely it misses the extra tools and some commands.

You can close the issue btw. Thank you!

**Comment by FrancYescO** [comment]
yes feeds are not compatible due to kernel changes, and probably we cannot ask src until a stable release is out
