### ISSUE TITLE
fix modoverlay hook broken on <=16.2

### ISSUE THREAD

**Issue by FrancYescO** [Ansuel/tch-nginx-gui#976]
@Ansuel @LuKePicci 
Seems 19.x (AGTHP_2.2.2_001) in preinit does not use random_seed but urandom-seed, this obviously cause to not mount modoverlay

```
Sat Jul 11 07:53:23 2020 user.info kernel: [    7.790033] init: - preinit -
Sat Jul 11 07:53:23 2020 kern.notice kernel: [    9.959985] jffs2: notice: (83) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
Sat Jul 11 07:53:23 2020 user.info kernel: [    9.977123] mount_root: switching to jffs2 overlay
Sat Jul 11 07:53:23 2020 user.info kernel: [    9.981540] mount_root: executing script in /lib/mount_root
Sat Jul 11 07:53:23 2020 user.info kernel: [    9.989183] mount_root: /lib/mount_root/00_rtfd_all
Sat Jul 11 07:53:23 2020 user.info kernel: [   10.017416] mount_root: /lib/mount_root/10_remove_due_to_upgrade
Sat Jul 11 07:53:23 2020 user.info kernel: [   10.038518] mount_root: /lib/mount_root/18_ispconfig_save
Sat Jul 11 07:53:23 2020 user.info kernel: [   10.049115] mount_root: /lib/mount_root/20_rtfd_remove
Sat Jul 11 07:53:23 2020 user.info kernel: [   10.059652] mount_root: /lib/mount_root/30_parameter_conversion
Sat Jul 11 07:53:23 2020 user.info kernel: [   10.086310] mount_root: /lib/mount_root/80_rtfd_restore
Sat Jul 11 07:53:23 2020 user.info kernel: [   10.121362] mount_root: /lib/mount_root/82_ispconfig_restore
Sat Jul 11 07:53:23 2020 user.warn kernel: [   10.323946] urandom-seed: Seeding with /etc/urandom.seed
Sat Jul 11 07:53:23 2020 kern.warn kernel: [   10.706709] tommath: module license 'unspecified' taints kernel.
Sat Jul 11 07:53:23 2020 kern.warn kernel: [   10.712339] Disabling lock debugging due to kernel taint
Sat Jul 11 07:53:23 2020 kern.warn kernel: [   10.730969] brcm_otp_init entry
```

but instead of hooking the new file what's wrong in just putting our `/usr/sbin/mount_modoverlay` in  `/lib/mount_root/` so it will be called by the official mount_root loop and is compatible hopefully to all firmwares

**Comment by Ansuel** [comment]
The scripts are enumerated before the overlay is mouned so our custom scripts are not present and not loaded

**Comment by FrancYescO** [comment]
What about the "mount verify" scripts folder

**Comment by LuKePicci** [comment]
> What about the "mount verify" scripts folder

same thing, just hook the new file (i.e. create another link)

PS: you still have to fix recursive insmod usage inside mount_root-mod to allow hooking on insmod for <= 16.2

**Comment by FrancYescO** [comment]
ok the issue was totally different and really stupid 
https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/base/usr/sbin/mount_modoverlay#L4
we cannot use `local` outside a func, really confused why this is working right now



> PS: you still have to fix recursive insmod usage inside mount_root-mod to allow hooking on insmod for <= 16.2

https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/base/sbin/mount_root-mod#L174
`[ ! -d "/proc/banktable" ] && insmod bankmgr 2>/dev/null`
 
enought?

**Comment by LuKePicci** [comment]
> really confused why this is working right now

https://github.com/FrancYescO/tch_firmware_extracted/blob/AGTHP_2.2.2_001_CLOSED/lib/preinit/99_random_seed

urandom_seed is different stuff, also urandom_seed is not in preinit_mount hook

> [ ! -d "/proc/banktable" ] && insmod bankmgr 2>/dev/null

nope, we have:
insmod tomsomething -> mount_root-mod -> do we need to load bankmgr? yes: -> insmod bankmgr -> mount_root-mod ->do we need to load bankmgr? yes: -> ...

just change it to /rom/sbin/insmod bankmgr

**Comment by FrancYescO** [comment]
i was talking about `local`: was a bash error that caused the modoverlay not mounting, the hook just work also on 19.x just removing the local keywork from the hooking script

`just change it to /rom/sbin/insmod bankmgr`
so the issue was just a not correct path for the insmod bin?
i was thinking that was loading the module multiple time and the 16.2 firmware was not managing correctly this..

**Comment by LuKePicci** [comment]
Well, the issue is that we hook on insmod and we have a call to the hooking insmod from inside our script. This clearly cause an infinite loop like this:
`insmod tomsomething -> mount_root-mod -> do we need to mount modoverlay? yes: -> do we need to load bankmgr? yes: -> insmod bankmgr -> mount_root-mod ->do we need to mount modoverlay? **still yes**: -> do we need to load bankmgr? no: ...`
since insmod is called each round unconditionally.

Of course you can avoid our script to run insmod again if it was already done previously, but this still cause the mount script to run twice like in my previous (edited) iteration sample.

**Comment by LuKePicci** [comment]
I'm not sure you can keep the condition before insmod call, there is an is_dual_bank check which is based upon it

**Comment by FrancYescO** [comment]
ok was not clear we was in a insmod call, but how calling it from rom could help? will not just recall our hooked random_seed (?) than again our hook?

**Comment by LuKePicci** [comment]
of course not, /sbin/insmod is our symlink hook, /rom/sbin/insmod is not

that's exactly what we do in the first line of /sbin/mount_modoverlay, we call the same command from /rom to run the original application in place of the hook

**Comment by FrancYescO** [comment]
ehm problably i'm missing something, actually we are not hooking insmod directly

**Comment by LuKePicci** [comment]
ok, first fix this by simply patching this https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/base/sbin/mount_root-mod#L174
this way:
`/rom/sbin/insmod bankmgr 2>/dev/null`

then, I suggest you try searching within preinit scripts where we actually hook modoverlay mounting

**Comment by LuKePicci** [comment]
https://github.com/Ansuel/tch-nginx-gui/blob/ea81db1c13d6dffae9c7bb094c504c375503c531/decompressed/base/etc/init.d/do_migrate_overlay#L67

/sbin/insmod must be in there, also the symlink isn't added yet

**Comment by FrancYescO** [comment]
that was what i was asking, we should also hook insmod 😅

but at this point is random_seed hook still needed? was insmod enough for all versions?

**Comment by LuKePicci** [comment]
random_seed is hooked in preinit_mount, which is just perfect for what we need to do here, insmod is hooked a little after, which is still fine but not so sweet as random_seed, so yes, keep it all, that's why I told you to name it in a generic way and reference it from multiple symlinks

**Comment by FrancYescO** [comment]
what if we hook  `/lib/preinit/99_10_run_init` directly ? seems is also present on all firmwares so we can also replace random_seed

just to avoid any "performance" issue as insmod is called multiple times, is just a little dirty

**Comment by LuKePicci** [comment]
I guess it's called before overlay is mounted

**Comment by FrancYescO** [comment]
with `/lib/preinit/99_10_run_init` not working, with `insmod` modem crashes, something other is needed

**Comment by LuKePicci** [comment]
Show me logs

**Comment by FrancYescO** [comment]
unfortunately i'm doing tests with no UART.. btw i think its due to the fact that insmod is by default a symlink to `../bin/busybox` or kmodloader so the trampoline function will not call correctly the original func

**Comment by LuKePicci** [comment]
Just run 'insmod sonething' from console.

That's strange, @larsen64it tested this a few months ago and module loading was working as far as I remember

**Comment by FrancYescO** [comment]
```
root@modemtim:/overlay/bank_2/usr/sbin# which insmod
/usr/sbin/insmod
root@modemtim:/overlay/bank_2/usr/sbin# ln -s mount_modoverlay insmod
root@modemtim:/overlay/bank_2/usr/sbin# insmod
Usage:
	insmod filename [args]
root@modemtim:/overlay/bank_2/usr/sbin# ll
drwxr-xr-x    2 root     root             0 Jul 12 13:00 ./
drwxr-xr-x    5 root     root             0 Jan  1  1970 ../
lrwxrwxrwx    1 root     root            16 Jul 12 13:00 insmod -> mount_modoverlay*
-rwxr-xr-x    1 root     root           868 Jul 12 12:58 mount_modoverlay*
root@modemtim:/overlay/bank_2/usr/sbin# mount
rootfs on / type rootfs (rw)
/dev/root on /rom type squashfs (ro,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
/dev/mtdblock2 on /overlay type jffs2 (rw,relatime,compr=zlib)
overlayfs:/overlay/bank_2 on / type overlayfs (rw,relatime,lowerdir=/,upperdir=/overlay/bank_2)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,mode=0755,size=512K)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000)
cgroup on /cgroups/cpumemblk type cgroup (rw,relatime,blkio,memory,cpu)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)
mvfs on /tmp/mvfs type fuse.mvfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
mountd(pid6551) on /tmp/run/mountd type autofs (rw,relatime,fd=5,pgrp=6549,timeout=600,minproto=5,maxproto=5,indirect)
```

actually seems the symlink wrote in bank2 totally ignored, but i'm pretty sure that a reboot will lead in a not booting device

**Comment by FrancYescO** [comment]
also this is pretty confusing...

https://github.com/FrancYescO/tch_firmware_extracted/blob/AGTHP_1.0.3_CLOSED/usr/sbin/insmod
https://github.com/FrancYescO/tch_firmware_extracted/blob/AGTHP_1.0.3_CLOSED/sbin/insmod

**Comment by LuKePicci** [comment]
The correct path of insmod is /sbin/insmod, there is no /usr/sbin/insmod in most firmwares

> seems the symlink wrote in bank2 totally ignored, but i'm pretty sure that a reboot will lead in a not booting device

```bash
cd /sbin && rm insmod
ln -s ../usr/sbin/mount_modoverlay insmod
```

**Comment by LuKePicci** [comment]
This won't work on that AGTHP_1.0.3 firmware, who cares, there is random_seed for it.

**Comment by FrancYescO** [comment]
> The correct path of insmod is /sbin/insmod, there is no /usr/sbin/insmod in most firmwares
> 
> > seems the symlink wrote in bank2 totally ignored, but i'm pretty sure that a reboot will lead in a not booting device
> 
> ```shell
> cd /sbin && rm insmod
> ln -s ../usr/sbin/mount_modoverlay insmod
> ```

this is what caused the brick on 19.x actually is working on 1.0.3 .. i'll retry

**Comment by LuKePicci** [comment]
I expect any >= 18.x to crash only if you use the above two lines for /usr/sbin/insmod instead of /sbin/insmod, since there exists no /rom/usr/sbin/insmod in those firmware versions

**Comment by FrancYescO** [comment]
idk what was wrong problably i messed up something trying to write to /overlay/bank_2/sbin/insmod while modoverlay mounted .. actually seems to work, hoping for all devices...
