### ISSUE TITLE
[BUG] Wrong QoS [enhancement] Ethernet Optimization

### ISSUE THREAD

**Issue by t0rzz** [Ansuel/tch-nginx-gui#977]
Device Model: AGTHP 4132 - Firmware 18.3.k (2.2.0 stable)
Gui Version: 9.5.88

Description of problem:
Default QoS for optical fiber connections (1000/100) is wrong. It limites your upload speed to 20Mbit/s by default. Disabling QoS on Ethernet ports (or globally) fixes the issue (and it reaches 100Mbps).
Also, just after installing the GUI, Ethernet EEE and Ethernet AutoGrEEEN are enabled. This leads the download speed to go down to ~700Mbps. Disabling those two options brings it back to normal (~920/950 Mbps).

How to reproduce (if possible):
Like above.

Media/Photos (if possible):
No need  (I guess?).

**Comment by FrancYescO** [comment]
AFAIK none of these settings are toggled when installing the GUI, you will only get the ability to show these

are you using fiber via SFP or external ONT (so basically an eth connection)? can you be more specific on what setting are you toggling on qos (as there is nothing that limit based on bandwith)?

**Comment by t0rzz** [comment]
Nice question. I believe the optical cable is connected to an adapter which is an Ethernet-similar adapter. There are no other external units besides the cable.
About the QoS, I am able to gain my original speed by toggling QoS off for Ethernet ports (as I am connected to the router through an Ethernet port).
Please note that with the stock GUI QoS works fine, no idea why.

Francesco Menghetti

**Comment by FrancYescO** [comment]
it's called ONT 
![image](https://user-images.githubusercontent.com/4574593/87462109-b44d5f00-c60f-11ea-92f2-ab6e611d68a7.png)

btw you must be more spiecific on what you disable on qos, as i said we make no edit to the stock config, also the speedtest of 700-900 can be influenced by other factors, to have a reliable results you must try a lan transfer.

you should also try to reset and retry to be sure all is reproducible

**Comment by t0rzz** [comment]
Nope it’s not an external unit, like I said. It’s just the optical fiber cable going into the router with just a very little adapter which seems like an Ethernet adapter.
I only have a router plugged in the AC, nothing else.
Btw I believe it’s easily reproducible: every time I install the custom GUI for the first time (after a router reset and rooting with firmware version 1.0.3 (the only rootable firmware?)) the QoS limits the upload bandwidth to 20Mbits. Probably when v1.0.3 was released that was the default (or max) value.
When I disable the QoS, in the QoS section, for the 4 Ethernet ports and the 2 WiFi channels, it starts working fine.
At this point I believe it’s an issue with the default config coming from version 1.0.3, which is then not updated when updating the firmware to v2.2.0.

About the Ethernet optimization (power saving options) it could be the same issue, so probably not GUI related.

Francesco Menghetti

**Comment by FrancYescO** [comment]
After upgrade to 2.2.0 reset it (root will stay here), than reinstall the GUI directly on 2.2.0

The "little adapter" is an SFP Mini-ONT, from how much your broadband line is active?

**Comment by t0rzz** [comment]
It’s been active since March 2020.

Thanks for your explanations :) 

Francesco Menghetti
