### ISSUE TITLE
19.x 5GHz Wifi settings: no Country Code, WPS always active, only auto channel

### ISSUE THREAD

**Issue by skdubg** [Ansuel/tch-nginx-gui#978]
hello community,

i see the following errors at the 5GHz wifi settings page
- no country code could be selected
- wps is always on
- only auto channel

saving the settings for wps and channel selection doenst work, it give an error

Device Model: DGA4132
Gui Version: 9.5.88

Description of problem: 5GHz Wifi Settings: no Country Code, WPS always active, only auto channel

How to reproduce (if possible):

Media/Photos (if possible): 
![Bildschirmfoto von 2020-07-16 07-55-13](https://user-images.githubusercontent.com/8874416/87632453-b90e3200-c739-11ea-941d-e0157b9b16ee.png)

![Bildschirmfoto von 2020-07-16 07-52-21](https://user-images.githubusercontent.com/8874416/87632367-8cf2b100-c739-11ea-96aa-f5adf46ce4e3.png)

[DebugHelper2020-07-16-0747.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4929560/DebugHelper2020-07-16-0747.tar.gz)

**Comment by skdubg** [comment]
with putty and manual config of /etc/config/wireless all options are configurable (country, wps_state, channel)
only country code doesn't show in the GUI

![Bildschirmfoto von 2020-07-16 12-23-11](https://user-images.githubusercontent.com/8874416/87660320-26808980-c75f-11ea-979c-f49a0ac681bd.png)

![Bildschirmfoto von 2020-07-16 12-23-42](https://user-images.githubusercontent.com/8874416/87660363-37c99600-c75f-11ea-8601-2bd5ab3e0c88.png)

**Comment by FrancYescO** [comment]
firmware 19.x bug, and is probably something that they will manage and change in the next betas: use the latest stable firmware and not beta

**Comment by skdubg** [comment]
Final 2.3.1 is available with Base 19.4
