### ISSUE TITLE
No Small Card Image

### ISSUE THREAD

**Issue by flywire** [Ansuel/tch-nginx-gui#98]
Some models are not supported eg [Telstra TG800](https://ibb.co/h7ZSve)
<a href="https://imgbb.com/"><img src="https://image.ibb.co/nt45gK/tg800.png" alt="tg800" border="0"></a>

**Comment by kevdagoat** [comment]
If you want my modified gateway modal with the tg799 image, whim me on whirlpool(TheHacker21)

**Comment by kevdagoat** [comment]
I will also code in the tg800 to save the guys some work.

**Comment by kevdagoat** [comment]
Here is the modified gateway card and the images associate:
[https://drive.google.com/open?id=1ZVYOCR1w4B8vfVyaf2aPZIsxHMwW3EO0](url)

**Comment by flywire** [comment]
Closed with #137
