### ISSUE TITLE
SSH always showing as disabled in GUI after reboot

### ISSUE THREAD

**Issue by Sam-arch99** [Ansuel/tch-nginx-gui#981]
Device Model: DGA4130, FW 2.2.0
Gui Version: 9.5.88-dev

Description of problem: Out of the box ssh is always showing as disabled in GUI even if it's enabled and working fine. If you enable it via GUI it will show ON but after a reboot is shown as OFF again.

How to reproduce (if possible): Enable ssh in GUI (System Extras) and reboot the device.

Media/Photos (if possible):  
![ssh_bug](https://user-images.githubusercontent.com/67625385/87996163-a2792980-caf1-11ea-8611-6c60dec6709a.PNG)

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/960
