### ISSUE TITLE
VPN client

### ISSUE THREAD

**Issue by IPTV-zeno** [Ansuel/tch-nginx-gui#983]
Ciao è possibile usare modem come VPN client in l2tp wireguard ecc?
Magari con un modulo

hi, is it possible to use the modem as a VPN client in l2tp or wireguard?
Magari con un plugin/modules

**Comment by FrancYescO** [comment]
probably, but you should rely on what openwrt offers and if you'll find modules installable on your modem, for now out of scope of tch-nginx-gui
