### ISSUE TITLE
AGTHP_2.2.2_001 cannot downgrade firmware (Error Code: 16)

### ISSUE THREAD

**Issue by Faddix** [Ansuel/tch-nginx-gui#985]
<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b> 
[DebugHelper2020-07-26-1422.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/4977576/DebugHelper2020-07-26-1422.tar.gz)

Device Model: DGA4132 (AGTHP_2.2.2_001)
Gui Version: 9.5.91-b7c7f327

Description of problem: Dato che, provando a impostare il Wake on LAN/WAN dalla scheda apposita, i cambiamenti non vengono salvati, ho provato a downgradare la versione del firmware a AGTHP_2.2.0, la quale funzionava perfettamente da quanto ricordo. Il problema è che quando provo a aggiornare il firmware dalla apposita scheda, dopo circa 10 secondi esce il messaggio di errore: Aggiornamento firmware fallito. (Codice errore: 16).

How to reproduce (if possible): Con versione di firmware AGTHP_2.2.2_001 provare a downgradare la versione del FW.

Media/Photos (if possible): 
![image](https://user-images.githubusercontent.com/60874864/88478963-68be7d80-cf4c-11ea-8fd7-d14ff4cfdaea.png)

**Comment by FrancYescO** [comment]
workaround should be, reset and use official (down)upgrade procedure

**Comment by dominovox** [comment]
@FrancYescO Got the same problem (my fault to upgrade I know it's not recommended), but I'm afraid to tell you that the official way to downgrade doesn't work:

Firmware upgrade failed. build signed with wrong key(Errorcode: 16)

Tried multiple versions (with the official way and with the .90 Dev GUI): AGTHP 1.0.3, 2.2.0, 2.2.1_004 etc

I still got root on the new version, but cant downgrade. So if you just want to take a look at the new beta firmware, stay away from it at the moment :)

**Comment by FrancYescO** [comment]
are you able to flash again the 2.2.2_001 over the GUI?

surely i've downgraded to 1.0.3 over TFTP flashing, but didn't notice the bootloader versions change thing... this is something we should elaborate better

**Comment by dominovox** [comment]
Last time I tried to flash the various firmware versions with the Dev GUI was some days ago, will check again momentarly.

Over the official way (access key etc) I got the error i posted for the older firmwares (was scared to loose my root with flashing the same version with the official way).

IF I remember correctly the bootloader version changed, but can't confirm it (dont have two DGA4132) rn.
Here is a screenshot from the official extended GUI:
![dga4132-versionofficialgui](https://user-images.githubusercontent.com/26336654/88547230-ba830880-d01d-11ea-9907-28cd5bcf7989.PNG)

**Comment by FrancYescO** [comment]
Bootloader version dose not change ;)
https://www.ilpuntotecnico.com/forum/index.php/topic,78162.msg228278.html#msg228278

**Comment by dominovox** [comment]
Oke, yes, sorry for confusion than - I was confused because I remembered something like a xx.06.xx version of the bootloader.

But I tried to upgrade from 2.2.2_001 to the same version with the Dev GUI .90 rn and it failes with Error 16 too.

**Comment by dominovox** [comment]
> surely i've downgraded to 1.0.3 over TFTP flashing, but didn't notice the bootloader versions change thing... this is something we should elaborate better

@FrancYescO so you downgraded from 2.2.2_001 to 1.0.3 with TFTP only? Do you have a link how to do this?

**Comment by dominovox** [comment]
TFTP flash directly to 1.0.3 didnt work twice, so i TFTP flashed 2.2.0 and downgraded to 1.0.3. Just need to get the root done.

**Comment by Faddix** [comment]
Is there any easy way to solve the problem? (without TFTP flashing)

**Comment by Faddix** [comment]
I solved the problem by resetting the router to factory settings and rooting it again from firmware version 1.0.3
I then installed the custom GUI and updated the firmware to 2.2.0 through it.
