### ISSUE TITLE
Success with TG589vac!

### ISSUE THREAD

**Issue by emoose** [Ansuel/tch-nginx-gui#986]
Just want to report that your GUI works great with TG589vac :)

```Product Name: MediaAccess TG
Friendly Name: MediaAccess TG589vac
ISP Name: Other
FW Version: 16.3.7937-2921014-20171017135155-58cd42d15b1fe4f200c81a3c944c836553fea108
DSL Version: A2pv6F039v2
Hardware Version: VANT-E
```

Only issues encountered:
- Gateway image doesn't exist at "/img/gateway_MediaAccess TG589vac.png" - fixed this by copying gateway.png to that filename, attached image for TG589vac in case you don't have it: 
![gateway_MediaAccess TG589vac](https://user-images.githubusercontent.com/1755499/88724457-6d3c8f00-d122-11ea-9291-99368b7d5c2d.png)
- Specific app & other installs fail since model TG589 isn't supported, I got around this by editing the scripts to make it think I used TG789 instead, seems all the apps built for TG789 run fine on TG589 :)

If any TG589vac owners are reading this, I used http://blog.superautomation.co.uk/2018/05/lan-side-root-on-technicolor.html method to get root, seems to work fine with latest TG589 FW.

Thanks for the nice GUI!

**Comment by FrancYescO** [comment]
looks we can use the same TG799 image https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/www/docroot/img/gateway_TG799vac.png
