### ISSUE TITLE
Web interface 404s unless the page is specified

### ISSUE THREAD

**Issue by falcorr** [Ansuel/tch-nginx-gui#989]
Device Model: DJA0230
Gui Version: 9.5.97-ed0ff8fc

E.g. for the past few days since having setup the device and this GUI, I had to specify 192.168.0.1/gateway.lp to reach the login interface. Otherwise I was met with a 404 page on which the provided button failed to go anywhere but to the 404 again. Oddly enough, today the issue seems to be resolved.

**Comment by FrancYescO** [comment]
no steps to reproduce and issue looks resolved so nothing to do here

**Comment by falcorr** [comment]
No idea how to reproduce. I'm sure it'll annoy the hell out of others too.
