### ISSUE TITLE
Internet toggle on its card remains 'off' despite being on

### ISSUE THREAD

**Issue by falcorr** [Ansuel/tch-nginx-gui#990]
Device Model: DJA0230
Gui Version: 9.5.97-ed0ff8fc

I.e. when looking at the cards interface, not having clicked on one and having all of them visible, the on-off toggle on 'internet' remains 'off' when the internet is connected. Toggling it to 'on' doesn't seem to disrupt the internet and it appears to stay that way for the time being but eventually ends up back at 'off'.

**Comment by FrancYescO** [comment]
provide screenshot and firmware used.

after a reset the issue remain here?

**Comment by nutterthanos** [comment]
yes i have that issue too on gui version 9.6.2

**Comment by FrancYescO** [comment]
https://github.com/Ansuel/tch-nginx-gui/issues/1001#issuecomment-720076483

**Comment by nutterthanos** [comment]
Nope still doing it 
https://gyazo.com/b704df469a40f56a45f95b5569149478

**Comment by FrancYescO** [comment]
try executing 
```
uci del network.wan
uci rename network.ppp=wan
```
