### ISSUE TITLE
[not sure if due to GUI] Ethernet devices not receiving full speed

### ISSUE THREAD

**Issue by falcorr** [Ansuel/tch-nginx-gui#992]
Device Model: DJA0230
Gui Version: 9.5.97-ed0ff8fc

Wireless devices are receiving full speed whereas ethernet ones are not. They don't seem to be significantly reaching into one another's bandwidth during simultaneous speed testing. Not sure where the fault lies but would be interested in knowing if it's possible this GUI is behind it, e.g. some sort of hidden or broken QoS going on that I'm not aware of.

**Comment by FrancYescO** [comment]
you are the only that can check that. simply reset and test without GUI than open an issue once you are sure it's caused from tch-nginx-gui provinding details.
