### ISSUE TITLE
Wireguard client features

### ISSUE THREAD

**Issue by SuperKali** [Ansuel/tch-nginx-gui#993]
Hello, i would to know if it's possible add wireguard vpn on TIM HUB FIBER.

**Comment by Ansuel** [comment]
Wireguard needs to be supported by the kernel and we currently can't modify
the kernel... We can try to build a module and see if it does load... (If
wireguard support can be compiled as a module)

Il Lun 17 Ago 2020, 15:58 Dany B | TradeHosting Provider <
notifications@github.com> ha scritto:

**Comment by oam7575** [comment]
According to this page : https://www.wireguard.com/compilation/
Wireguard requires Kernel 3.10 or newer and several kernel options enabled.

MY TG799VAC has software 17.2 with kernel 3.4.11

You might be able to custom compile Wireguard however it is likely this would require patches or other custom configuration and cross compile.

Not to say that it can't be done but at this stage not looking straight forward.
