### ISSUE TITLE
Luci install on TG800

### ISSUE THREAD

**Issue by nerfherder** [Ansuel/tch-nginx-gui#994]
Device Model: TG800
Gui Version: 9.5.98

Description of problem:

Can't install Luci from GUI, appears to be an issues with opkg feeds.

![Annotation 2020-08-18 154136](https://user-images.githubusercontent.com/2674434/90474731-56112000-e169-11ea-8b01-939347a4c078.jpg)

**Comment by FrancYescO** [comment]
does `/etc/opkg.conf` contains feeds?

**Comment by nerfherder** [comment]
No, only contains the following

> dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay

**Comment by FrancYescO** [comment]
try with 9.5.99 if feeds are setted

**Comment by nerfherder** [comment]
Those feeds fail

![image](https://user-images.githubusercontent.com/2674434/90574491-66bea600-e1fc-11ea-87ab-589df3df7427.png)

**Comment by FrancYescO** [comment]
issue these commands than reinstall or try an opkg update

```
curl https://raw.githubusercontent.com/Ansuel/tch-nginx-gui/master/decompressed/upgrade-pack-specificDGA/tmp/3.4_ipk/wget_1.17.1-1_brcm63xx-tch.ipk -o /tmp/w.ipk
opkg install /tmp/w.ipk
```

**Comment by nerfherder** [comment]
The install appeared to run smoothly, but there is no response at 10.0.0.138:9080

I ran `uhttpd -f -h /www_luci -p 8090` to test but it failed with 

> uhttpd: can't resolve symbol 'uloop_run_timeout'

**Comment by FrancYescO** [comment]
idk how to go over on it especially without the device, but try to do a factory reset (the first reset will not remove root) than install directly the 9.6.0 version of tch-nginx-gui than retry luci install (this time wget should be installed automatically if the modem is connected to internet)

**Comment by nerfherder** [comment]
Finally got a chance to do this - my vdsl line went down on Thursday so have had no internet access.

Still have the same error, will do some research into uhttpd and see what might be causing it.

I did find this past issue on the https://github.com/Ansuel/tch-nginx-gui/issues/243 DGA modems which appears to be the same problem - not sure what the solution ended up being.

**Comment by FrancYescO** [comment]
could you check with latest dev version?

**Comment by FrancYescO** [comment]
Closing as it should be fixed.

**Comment by nerfherder** [comment]
I'm away from home for the next week. I'll test when I get home, hopefully all works properly now

**Comment by nerfherder** [comment]
I can confirm this is now working
