### ISSUE TITLE
A bug doesn't allow to change the gui theme from Fritz!Box one to another one

### ISSUE THREAD

**Issue by simonerancati** [Ansuel/tch-nginx-gui#995]
NB: Before submitting an issue, check if there is one already open that suits the problem you are having!

<b>If you are on the latest dev, please go to Cards >> System Extras >> Debug Report and press the Generate button.
  Please attach the file here:</b>

Device Model: MediaAccess TG ( MediaAccess TG789vac v2 )

Gui Version: 9.6.1-a6bbdd63

Description of problem: After changing the gui to the Fritz!Box one I cannot change it again, it keeps reverting back to the Fritz!Box gui

How to reproduce (if possible): Change the gui to Fritz!Box and try to change it again

Media/Photos (if possible): I don't think photos can explain this problem, when I try to change the gui the website reloads and shows the Fritz!Box one

[DebugHelper2020-09-02-2107.tar.gz](https://github.com/Ansuel/tch-nginx-gui/files/5164594/DebugHelper2020-09-02-2107.tar.gz)

**Comment by skdubg** [comment]
is confirmed. I already mentioned [here](https://www.onlinekosten.de/forum/showthread.php?p=2528569#post2528569) (german language) that the Fritzbox GUI is not usable

**Comment by FrancYescO** [comment]
Seems i cannot reproduce..
Tim Enhanched changed to fritzbox, pressed save
from fritzbox gui selected blue, pressed save

switched successfully

**Comment by simonerancati** [comment]
I updated to the latest 9.6.2 but continue to have the problem

**Comment by FrancYescO** [comment]
could you attach a video? probably will help to have the bug sorted out...

**Comment by simonerancati** [comment]
Here it is. It’s an old video because some days ago I decided to reset the router and install the stable release of the GUI

[https://photos.app.goo.gl/FC9xM1mGtqMr9FSi6](video)

**Comment by simonerancati** [comment]
Here it is. It’s an old video because some days ago I decided to reset the router and install the stable release of the GUI

https://photos.app.goo.gl/Jat1fdCm3G6gv9NFA

**Comment by FrancYescO** [comment]
are you still having the issue after the reset?

**Comment by simonerancati** [comment]
After the reset and the reinstall of the version 9.5.38 the issue disappeared and the UI is much faster (in my video you can see that browsing the various menus was very slow)

**Comment by FrancYescO** [comment]
so i assume also this bug is due to some dirt config generated somehow..

**Comment by FrancYescO** [comment]
so i assume also this bug is due to some dirt config generated somehow..

**Comment by simonerancati** [comment]
Yeah, probably it was a rare bug that required particular conditions to happen. Anyway the fact that you were not able to reproduce it means that the update process went well, so you probably don’t have to worry too much
