### ISSUE TITLE
DGA4131 Access Point Mode

### ISSUE THREAD

**Issue by TraskIT** [Ansuel/tch-nginx-gui#996]
Device Model: Fastweb FASTgate - Technicolor DGA4131
Gui Version: 9.5.38

Description of problem: I'm trying to convert my DGA4131 to an access point. I also have a "TG789vac v2" and with the UNO firmware (without Ansuel GUI) there is a specific function that permit to disable all the modem functions and to convert it as an AP.
Is there a method to do that with the DGA4131?

**Comment by FrancYescO** [comment]
disable DHCP set a static lan IP in the same subnet of main gateway and don't use the WAN port to connect it to the main AP
