### ISSUE TITLE
TG789vac V2 MyRepublic Reboot Loop

### ISSUE THREAD

**Issue by Cossey** [Ansuel/tch-nginx-gui#997]
I installed the latest stable version available presently. That went fine and restarted router. Then I installed installed latest dev version from cli using `upgradegui`. 

The gui had a message about restarting the router for OBP or something like that. So I rebooted from cli, nothing happened so i rebooted physically. 

Now the router is stuck in a reboot loop, the red light flashes for about 4 seconds then all the led lights light up and then it keeps doing the same thing. No shell, no gui, no Wifi, no nothing. 

Any suggestions on what to do or do I now have a paperweight and no internet?

**Comment by FrancYescO** [comment]
use TFTP to restore firmware, this probably got fixed in 9.6.2

**Comment by Cossey** [comment]
I would use this method but there is no available firmware in RBI format for this particular model (TG789vac v2 HP VBNT-L) at the firmware repository. The only file I see is a raw dump.

Unless anyone here knows how to flash the raw dump available at the firmware repository...?

**Comment by FrancYescO** [comment]
that's pretty bad.. to flash bank dump you should have ssh access and use mtd write.

with no RBI file i think your only solutions are attaching the serial to the board too see if you are able to get a prompt to erase it or try to do a failboot than keep pushing the reset buttong

**Comment by Cossey** [comment]
Okay, I managed to speak with a MyRepublic support technician and he was more than happy to give me the RBI firmware file. He sent it via email so I don't have a http link to their firmware repository URL. I used the TFTP method with the firmware file and successfully restored the router.

@FrancYescO Do you help maintain the Technicolor Firmware Repository? Since the Repository doesn't have the RBI file maybe you could sort that out, if you don't mind? I have put the firmware file on Dropbox temporarily if you want to grab it and store it somewhere or seed it on BitTorrent.

Version: 16.3.7190
Hardware: VBNT-L

https://www.dropbox.com/s/gc6dzvgex04tdom/vbnt-l_16.3.7190-2761003-20170907085601-501361d1f0abcd3206e49f0897c4a6cca07a114d.rbi?dl=1

**Comment by FrancYescO** [comment]
Nice find, open an issue to their repo to add it or I'll do a PR later to have it added somehow.

Just to have this issue closed please confirm that the latest dev versions works good also on your device :D

**Comment by Cossey** [comment]
Hey @FrancYescO thanks for opening the PR. Please give me a few more days to test out latest dev versions and ill update you here.

**Comment by Cossey** [comment]
I have just re-rooted this device today and installed `9.6.90` without any issues. Sorry for the late reply.
